

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "53: Population Ecology > Practice Test";
	ak.quiz_loc_with_commas = "53: Population Ecology, Practice Test";
	ak.quiz_title = "Practice Test";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 38;
	ak.non_essay_total = 38;
	ak.scored_item_total = 38;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337013;


		
		

		
			
			p.question = "To calculate the human population density of your community, you would need to know the number of people living there and _____. (<script type=\"text/javascript\">ebook(\'5301\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the size of the area in which they live",
				true,
				"Correct. Density is the number of individuals of a population per unit area or volume.");
			
				p.addAnswer(2, "the birth rate of the population",
				false,
				"No. Birth rate may influence density, but that information is not needed for the calculation of density.");
			
				p.addAnswer(3, "whether population growth is logistic or exponential",
				false,
				"No. However, this may provide information about how a particular population density was achieved.");
			
				p.addAnswer(4, "the dispersion pattern of the population",
				false,
				"No. \"Dispersion\" refers to the relative positioning of the individuals of a population.");
			
				p.addAnswer(5, "the carrying capacity",
				false,
				"No. \"Carrying capacity\" refers to the maximum number of individuals of a given population that a given environment can support.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337014;


		
		

		
			
			p.question = "Which choice below is an example of an expression of population density? (<script type=\"text/javascript\">ebook(\'5301\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "255 dogfish sharks",
				false,
				"No. Population density is expressed on a per-unit-area or per-unit-volume basis.");
			
				p.addAnswer(2, "100 sea stars, barnacles, and mussels per 25 m<sup>2</sup> of a tide pool",
				false,
				"No. This count includes the combined number of individuals of three different populations.");
			
				p.addAnswer(3, "the number of <i>Paramecium caudatum</i> in a 250 mL solution in a glass flask",
				true,
				"Correct. Population density is the number of individuals of a species per unit area or volume.");
			
				p.addAnswer(4, "the total number of sturgeon per cubic meter in San Francisco Bay and in Tomales Bay",
				false,
				"No. This includes individuals from two different populations.");
			
				p.addAnswer(5, "the total dry mass of trout in a lake",
				false,
				"No. Population density is the number, not mass, of individuals.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337015;


		
		

		
			
			p.question = "When needed resources are unevenly distributed, organisms often show a(n) _____ dispersion pattern. (<script type=\"text/javascript\">ebook(\'5301\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "density-dependent",
				false,
				"No. This term does not refer to a pattern of dispersion.");
			
				p.addAnswer(2, "clumped",
				true,
				"Correct. Individuals will be found in proximity to resources.");
			
				p.addAnswer(3, "exponential",
				false,
				"No. This does not refer to a pattern of dispersion.");
			
				p.addAnswer(4, "random",
				false,
				"No. The dispersion pattern is not random, because the organisms will distribute themselves in relation to resources.");
			
				p.addAnswer(5, "uniform",
				false,
				"No. Organisms will distribute themselves in relation to resources, which are unevenly distributed.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337016;


		
		

		
			
			p.question = "Organisms that live in a homogenous abiotic environment and cooperate to avoid being eaten would likely show a(n) _____ pattern of dispersion. (<script type=\"text/javascript\">ebook(\'5301\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "continuous",
				false,
				"No. Organisms are not distributed continuously within a population.");
			
				p.addAnswer(2, "uniform",
				false,
				"No. This pattern results from competitive interactions among individuals.");
			
				p.addAnswer(3, "even",
				false,
				"No. This is the same as a uniform pattern. This pattern results from competitive interactions among individuals.");
			
				p.addAnswer(4, "random",
				false,
				"No. This pattern results from an even distribution of resources and a lack of social behavior.");
			
				p.addAnswer(5, "clumped",
				true,
				"Correct. This pattern results from an uneven distribution of resources or from a certain social behavior.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337017;


		
		

		
			
			p.question = "Herring gulls fiercely defend the areas around their nests in cliff-top breeding colonies. Within the colony they would show a _____ dispersion pattern. (<script type=\"text/javascript\">ebook(\'5301\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "uniform",
				true,
				"Correct. Territorial behavior often results in a uniform distribution.");
			
				p.addAnswer(2, "random",
				false,
				"No. Random distribution is an unlikely result of the interaction among individuals of a population.");
			
				p.addAnswer(3, "dense",
				false,
				"No. This term does not refer to a dispersion pattern.");
			
				p.addAnswer(4, "density-independent",
				false,
				"No. This term does not refer to a dispersion pattern.");
			
				p.addAnswer(5, "clumped",
				false,
				"No. A clumped distribution is usually the result of the distribution of a resource, not territorial behavior.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337018;


		
		

		
			
			p.question = "Pine trees in a forest tend to shade and kill pine seedlings that sprout nearby. This causes the pine trees to _____. (<script type=\"text/javascript\">ebook(\'5301\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "increase exponentially",
				false,
				"No. The question refers to the killing of individuals; such an event does not promote a rapid increase in the size of a population.");
			
				p.addAnswer(2, "grow in a clumped pattern",
				false,
				"No. Because nearby seedlings tend to die, pine trees will normally not be found in clumps.");
			
				p.addAnswer(3, "grow in a uniform pattern",
				true,
				"Correct. The area shaded by each tree will determine pine tree distribution.");
			
				p.addAnswer(4, "exceed their carrying capacity",
				false,
				"No. Killing nearby trees limits the size of the population.");
			
				p.addAnswer(5, "grow in a random pattern",
				false,
				"No. Since pine trees interact in the determination of the dispersion pattern, random distribution is unlikely to result.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337019;


		
		

		
			
			p.question = "A demographer may study _____. (<script type=\"text/javascript\">ebook(\'5301\',\'quiz\')</script>)";
			p.incorrect_any_expl = "No. This answer is correct, but there is a better answer.";
			p.incorrect_any_expl_flag = 1;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "birth rates in a small town in Iowa",
				false,
				"");
			
				p.addAnswer(2, "emigration rates in a forest that has been cleared partially for farming",
				false,
				"");
			
				p.addAnswer(3, "offspring mortality rates in humpback whales",
				false,
				"");
			
				p.addAnswer(4, "immigration rates in Melbourne, Australia",
				false,
				"");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct. Demography is the study of vital statistics of populations and how they change over time.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337020;


		
		

		
			
			p.question = "Life tables typically follow the fate of a cohort, a _____. (<script type=\"text/javascript\">ebook(\'5301\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "group of individuals who live in the same community",
				false,
				"No. This may be true, but there is a more important characteristic that unites them.");
			
				p.addAnswer(2, "group of individuals who migrated to the same area at the same time",
				false,
				"No. Life tables are age-specific summaries of the survival pattern of a population.");
			
				p.addAnswer(3, "group of individuals who died from the same disease",
				false,
				"No. Life tables are age-specific summaries of the survival pattern of a population.");
			
				p.addAnswer(4, "group of individuals who reproduced at the same age",
				false,
				"No. A cohort is a group of individuals who are of the same age. They may all reproduce at different ages.");
			
				p.addAnswer(5, "group of individuals who are the same age",
				true,
				"Correct. Life tables are age-specific summaries of the survival pattern of a population.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337021;


		
		

		
			
			p.question = "An oak tree produces thousands of acorns, but very few grow into mature oak trees. The oak tree exhibits a _____ survivorship curve. (<script type=\"text/javascript\">ebook(\'5301\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Type I",
				false,
				"No. A Type I survivorship curve is typical of populations with low rates of juvenile mortality.");
			
				p.addAnswer(2, "Type II",
				false,
				"No. A Type II survivorship curve is one in which the probability of survivorship does not change with age. In this instance, the probability of survivorship does change with age.");
			
				p.addAnswer(3, "Type III",
				true,
				"Correct. This is the name given to the survivorship curve that displays high rates of juvenile mortality.");
			
				p.addAnswer(4, "Type I or II",
				false,
				"No. A Type I survivorship curve is typical of populations with low rates of juvenile mortality. A Type II survivorship curve is one in which the probability of survivorship does not change with age.");
			
				p.addAnswer(5, "Type I or III",
				false,
				"No. Only one of these choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337022;


		
		

		
			
			p.question = "Chimpanzees have a relatively low birth rate. They care for their young, and most chimps live a long life. The chimp survivorship curve would look like _____. (<script type=\"text/javascript\">ebook(\'5301\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a line that slopes gradually upward",
				false,
				"No. The number of individuals of a given age will not increase with time.");
			
				p.addAnswer(2, "a relatively flat line that drops steeply at the end",
				true,
				"Correct. There is a high probability of survival through adulthood, with the probability of death increasing significantly in old age.");
			
				p.addAnswer(3, "a line that drops steeply at first, then flattens out",
				false,
				"No. Such a line would be indicative of a high mortality rate early in life.");
			
				p.addAnswer(4, "a line that slopes gradually downward",
				false,
				"No. Such a line would indicate that the probability of survivorship remains relatively constant throughout the life span.");
			
				p.addAnswer(5, "a horizontal line",
				false,
				"No. This would indicate immortality.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337023;


		
		

		
			
			p.question = "Which of the following describes the distribution of survivorship or mortality for a population that has a Type II survivorship curve? (<script type=\"text/javascript\">ebook(\'5301\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Little death occurs until late in life.",
				false,
				"No. This is characteristic of a population with a Type I survivorship curve.");
			
				p.addAnswer(2, "Most of the mortality occurs among younger individuals.",
				false,
				"No. This is characteristic of a population with a Type III survivorship curve.");
			
				p.addAnswer(3, "Survivorship is greatest in younger individuals.",
				false,
				"No. This is characteristic of a population with a Type I survivorship curve.");
			
				p.addAnswer(4, "Survivorship is greatest in individuals that are intermediate in age.",
				false,
				"No. No population with any of the three types of survivorship curves has this characteristic.");
			
				p.addAnswer(5, "The chance of death is roughly constant over all ages.",
				true,
				"Correct. The curve is intermediate between Type I and Type III survivorship curves.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337024;


		
		

		
			
			p.question = "What are three basic issues that life histories entail? (<script type=\"text/javascript\">ebook(\'5302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "when reproduction begins, how often the organism breeds, and how many offspring from each reproductive episode survive to also reproduce",
				false,
				"No. The third example is not an issue that would affect the schedule of reproduction and survival of the parent organism.");
			
				p.addAnswer(2, "whether or not reproduction is a conscious decision, how often the organism breeds, and how many offspring are produced during each reproductive episode",
				false,
				"No. Reproduction is only a conscious decision in human populations.");
			
				p.addAnswer(3, "when reproduction begins, level of parental care, and how many offspring are produced during each reproductive episode",
				false,
				"No. Level of parental care and how many offspring are produced are related issues.");
			
				p.addAnswer(4, "when reproduction begins, how often the organism breeds, and how many offspring are produced during each reproductive episode",
				true,
				"Correct. The various possibilities associated with these basic issues are integrated into the life history patterns observed in nature.");
			
				p.addAnswer(5, "whether or not reproduction is a conscious decision, level of parental care, and how many offspring are produced during each reproductive episode",
				false,
				"No. Reproduction is only a conscious decision in human populations. And the number of offspring produced is related to level of parental care.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337025;


		
		

		
			
			p.question = "A dog gives birth to 3 puppies one year. Three years later, she gives birth to 6 puppies. Which type of life history pattern is characteristic of this organism? (<script type=\"text/javascript\">ebook(\'5302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "semelparity",
				false,
				"No. This is another term for big-bang reproduction, which describes organisms that produce a large amount of offspring, but only one time before they die.");
			
				p.addAnswer(2, "exponential population growth",
				false,
				"No. This term describes population growth under ideal conditions. It is not a life history pattern.");
			
				p.addAnswer(3, "big-bang reproduction",
				false,
				"No. This is another term for semelparity, which describes organisms that produce a large amount of offspring, but only one time before they die.");
			
				p.addAnswer(4, "iteroparity",
				true,
				"Correct. This term refers to repeated reproduction.");
			
				p.addAnswer(5, "<i>r</i>-selection",
				false,
				"No. This refers to the selection for life history traits that maximize reproductive success in uncrowded environments (low densities).");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337026;


		
		

		
			
			p.question = "Although there are organisms whose life histories fall somewhere between iteroparity and semelparity, life history always represents a trade-off. Why is this? (<script type=\"text/javascript\">ebook(\'5302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Parents always try to leave adequate resources for their offspring, so the parents may suffer.",
				false,
				"No. While some organisms expend a great deal of energy making sure that their offspring are taken care of, there are many organisms that leave the young to fend for themselves and may even compete with them for resources.");
			
				p.addAnswer(2, "The energy cost of reproduction is high, so there are not enough resources to reproduce often, produce many offspring, and take care of them.",
				true,
				"Correct. Life histories represent an attempt to optimize several factors. Given that resources are limited, all of the factors cannot be optimized at once.");
			
				p.addAnswer(3, "In unpredictable environments iteroparity is favored because it may require many attempts to successfully reproduce.",
				false,
				"No. Iteroparity is usually favored in stable environments.");
			
				p.addAnswer(4, "Where resource competition is intense, semelparity is favored because of the many offspring produced, only a few will survive.",
				false,
				"No. Iteroparity is usually favored in environments where resource competition is intense.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. There is only one correct answer");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337027;


		
		

		
			
			p.question = "Kingfish, Louisiana, had a population of 1,100 individuals. They had a birth rate of 12/100, a death rate of 8/100, and an emigration (individuals leaving the population) rate of 2/100. How many people were added to Kingfish\'s population in one year? (<script type=\"text/javascript\">ebook(\'5303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "No. The birth rate of 12/100 should yield 132 new babies; the death rate of 8/100 should yield 88 deaths; the emigration rate of 2/100 indicates 22 people moved out. The net gain is 132 - 88 - 22 = 22.";
			p.incorrect_any_expl_flag = 1;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "2",
				false,
				"");
			
				p.addAnswer(2, "6",
				false,
				"");
			
				p.addAnswer(3, "20",
				false,
				"");
			
				p.addAnswer(4, "22",
				true,
				"Correct. The birth rate of 12/100 should yield 132 new babies; the death rate of 8/100 should yield 88 deaths; the emigration rate of 2/100 indicates 22 people moved out. The net gain is 132 - 88 - 22 = 22.");
			
				p.addAnswer(5, "1,122",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337028;


		
		

		
			
			p.question = "Using the data in question 15 above, what was the per capita rate of increase, including emigration, for this year in Kingfish? (<script type=\"text/javascript\">ebook(\'5303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "4",
				false,
				"No. The per capita rate of increase would be per capita birth rate minus per capita death rate minus per capita emigration rate or 0.12 - 0.08 - 0.02 = 0.02.");
			
				p.addAnswer(2, "22",
				false,
				"No. The per capita rate of increase would be per capita birth rate minus per capita death rate minus per capita emigration rate or 0.12 - 0.08 - 0.02 = 0.02.");
			
				p.addAnswer(3, "2",
				false,
				"No. The per capita rate of increase would be per capita birth rate minus per capita death rate minus per capita emigration rate or 0.12 - 0.08 - 0.02 = 0.02.");
			
				p.addAnswer(4, "0.02",
				true,
				"Correct. The per capita rate of increase would be per capita birth rate minus per capita death rate minus per capita emigration rate or 0.12 - 0.08 - 0.02 = 0.02.");
			
				p.addAnswer(5, "0.22",
				false,
				"No. The per capita rate of increase would be per capita birth rate minus per capita death rate minus per capita emigration rate or 0.12 - 0.08 - 0.02 = 0.02.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337029;


		
		

		
			
			p.question = "When the per capita birth rate equals the per capita death rate, _____. (<script type=\"text/javascript\">ebook(\'5303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a population grows rapidly",
				false,
				"No. Think about the equation by which <i>r</i> is calculated.");
			
				p.addAnswer(2, "the size of a population remains constant",
				true,
				"Correct. Excluding the possible effects of migration, when the per capita birth rate and per capita death rate are equal, the population size will remain constant.");
			
				p.addAnswer(3, "density-dependent limiting factors do not affect the population",
				false,
				"No. Both density-dependent and density-independent factors affect per capita birth and death rates. However, they do not provide information on their effect when both of those rates are equal.");
			
				p.addAnswer(4, "a population is in danger of extinction",
				false,
				"No. Think about the equation by which <i>r</i> is calculated.");
			
				p.addAnswer(5, "a population goes through up and down cycles",
				false,
				"No. Taken alone, equal birth and death rates will not result in cyclic changes in population size. Think about the equation by which <i>r</i> is calculated.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337030;


		
		

		
			
			p.question = "A population will always grow exponentially _____. (<script type=\"text/javascript\">ebook(\'5303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "if it is limited only by density-dependent factors",
				false,
				"No. A population will not experience continuous exponential growth if it is limited by either density-dependent or density-independent factors.");
			
				p.addAnswer(2, "until it reaches carrying capacity",
				false,
				"No. As carrying capacity is neared, the population growth rate approaches zero.");
			
				p.addAnswer(3, "if there are no limiting factors",
				true,
				"Correct. Limiting factors determine the maximum number of individuals that can be supported by a given environment. In the absence of such factors, a population will reproduce at its maximum rate.");
			
				p.addAnswer(4, "if it is a population with an equilibrium life history",
				false,
				"No. Populations with such a life history would not be growing exponentially.");
			
				p.addAnswer(5, "if it shows logistic growth",
				false,
				"No. A logistic growth curve exhibits a slowing of the growth rate as carrying capacity is approached.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337031;


		
		

		
			
			p.question = "Which of the following populations probably exhibits exponential growth? (<script type=\"text/javascript\">ebook(\'5303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a protozoan population grown in a sealed glass culture flask",
				false,
				"No. A limited supply of food and oxygen regulates the population.");
			
				p.addAnswer(2, "a fruit fly population that recently arrived on a lush mid-oceanic island previously inhabited only by plants",
				true,
				"Correct. Growth of the fruit fly population is not limited by competition from other organisms.");
			
				p.addAnswer(3, "a redwood tree population in a forest",
				false,
				"No. Trees of other species in the forest and other factors regulate the redwood tree population.");
			
				p.addAnswer(4, "a population of deer in an area with few palatable food plants",
				false,
				"No. The food resource limits the growth of the deer population.");
			
				p.addAnswer(5, "a population of deer in an area with many hungry wolves",
				false,
				"No. The predators regulate the growth of the deer population.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337032;


		
		

		
			
			p.question = "No population can grow indefinitely. The ultimate size of any population is limited by _____. (<script type=\"text/javascript\">ebook(\'5304\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "its <i>r</i>",
				false,
				"No. <i>r</i> affects the rate of population growth; it does not place an upper limit on population size.");
			
				p.addAnswer(2, "its birth rate",
				false,
				"No. Birth rate affects the rate of population growth; it does not place an upper limit on population size.");
			
				p.addAnswer(3, "its death rate",
				false,
				"No. Death rate affects the rate of population growth; it does not place an upper limit on population size.");
			
				p.addAnswer(4, "the carrying capacity of its environment",
				true,
				"Correct. Ecologists define \"carrying capacity\" as the maximum population size that a particular environment can support.");
			
				p.addAnswer(5, "reproductive isolation",
				false,
				"No. Reproductive isolation is evidence that speciation has occurred.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337033;


		
		

		
			
			p.question = "A newly mated queen ant founds a nest in an unoccupied patch of suitable habitat. Assuming that no disasters strike the nest, which one of the following types of equations is likely to best describe the population growth of the new colony? (<script type=\"text/javascript\">ebook(\'5304\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "linear",
				false,
				"No. This would assume that the mated queen does not have offspring.");
			
				p.addAnswer(2, "circular",
				false,
				"No. There are no population growth models that are circular.");
			
				p.addAnswer(3, "logistic",
				true,
				"Correct. The logistic model of population growth assumes there is a maximum population size that the environment can support and that population growth slows as the population approaches that carrying capacity.");
			
				p.addAnswer(4, "quadratic",
				false,
				"No. There are no population growth models that are quadratic.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337034;


		
		

		
			
			p.question = "In an equilibrium population (at its carrying capacity), thousands of eggs and hundreds of tadpoles are produced by a single pair of frogs. On average, about how many offspring per pair will live to reproduce? (<script type=\"text/javascript\">ebook(\'5304\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "0",
				false,
				"No. Having no offspring, or no offspring that survive to reproduce, would quickly drive the population to extinction.");
			
				p.addAnswer(2, "2",
				true,
				"Correct. Ecologists define \"carrying capacity\" as the maximum population size that a particular environment can support. A single pair of frogs would be expected to only replace itself.");
			
				p.addAnswer(3, "10 to 20",
				false,
				"No. If 10 to 20 individuals replaced every pair, the population size would increase rapidly.");
			
				p.addAnswer(4, "100",
				false,
				"No. This would result in a rapid increase in the size of the population.");
			
				p.addAnswer(5, "more than 100",
				false,
				"No. This would result in a very rapid increase in the size of the population.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337035;


		
		

		
			
			p.question = "A wildlife biologist is trying to predict what will happen to a bear population if bear hunting is banned. He had the equations all worked out but then realized that he had grossly underestimated the amount of food available to the bears. To make his prediction more accurate he should _____ the value of _____ in his equation. (Consider food to be a factor that limits the size of the bear population.) (<script type=\"text/javascript\">ebook(\'5304\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "decrease; <i>N</i>",
				false,
				"No. Change in <i>N</i>, population size, is what the biologist is trying to predict.");
			
				p.addAnswer(2, "increase; <i>N</i>",
				false,
				"No. Change in <i>N</i>, population size, is what the biologist is trying to predict.");
			
				p.addAnswer(3, "decrease; <i>K</i>",
				false,
				"No. Because food is a factor that limits the size of the particular bear population, the increased food availability would increase carrying capacity.");
			
				p.addAnswer(4, "increase; <i>K</i>",
				true,
				"Correct. Because food is a factor that limits the size of the particular bear population, the increased food availability would increase carrying capacity.");
			
				p.addAnswer(5, "decrease; <i>r</i>",
				false,
				"No. Because food is a factor that limits the size of the particular bear population, the increased food availability would not decrease the per capita population growth rate.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337036;


		
		

		
			
			p.question = "Assuming that <i>r</i> has a positive value, in the formula <i>dN/dt</i> = <i>r</i><sub>max</sub><i>N</i>(<i>K</i> - <i>N</i>)/<i>K</i> the factor <i>rN</i> tends to cause the population to _____. (<script type=\"text/javascript\">ebook(\'5304\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "grow increasingly rapidly",
				true,
				"Correct. The difference between birth rates and death rates is represented by <i>r</i>. <i>N</i> is the population size. Therefore, <i>rN</i> is the population growth rate.");
			
				p.addAnswer(2, "remain stable at the carrying capacity",
				false,
				"No. The equation <i>dN/dt</i> = <i>rN</i> does not consider limits on population growth.");
			
				p.addAnswer(3, "decrease in size",
				false,
				"No. Per capita population growth rate is represented by <i>r</i>.");
			
				p.addAnswer(4, "grow at a slower rate than the (<i>K</i> - <i>N/K</i>) factor",
				false,
				"No. <i>K</i> symbolizes carrying capacity, a limit on the population size.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337037;


		
		

		
			
			p.question = "A population that grows rapidly at first and then levels off at carrying capacity can be modeled _____. (<script type=\"text/javascript\">ebook(\'5304\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "by a logistic equation",
				true,
				"Correct. The logistic equation, <i>dN/dt</i> = <i>r</i><sub>max</sub><i>N</i>(<i>K</i> - <i>N</i>)/<i>K</i> describes such a curve.");
			
				p.addAnswer(2, "as <i>dN/dt</i> = <i>b</i> - <i>d</i>",
				false,
				"No. This equation would result in a constant rate of change of population size, the rate being zero if <i>b</i> equals <i>d.</i>");
			
				p.addAnswer(3, "as an opportunistic species",
				false,
				"No. Such species are usually described as having high rates of population growth and as not being subject to limitations in such a way that population size would level off.");
			
				p.addAnswer(4, "as <i>dN/dt</i> = <i>rN</i>",
				false,
				"No. This equation applies in the absence of limiting factors and will result in a J-shaped curve.");
			
				p.addAnswer(5, "as being relatively unaffected by limiting factors",
				false,
				"No. Under conditions such as these, the population growth curve would take on the shape of the letter J.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337038;


		
		

		
			
			p.question = "A population that is growing logistically _____. (<script type=\"text/javascript\">ebook(\'5304\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "grows fastest when density is lowest",
				false,
				"No. Population growth curves may only indirectly reflect population density.");
			
				p.addAnswer(2, "has a high <i>r</i>",
				false,
				"No. Traditionally, species with a high <i>r</i> are viewed as opportunistic species, little affected by limiting factors.");
			
				p.addAnswer(3, "grows fastest at an intermediate population density",
				true,
				"Correct. At very small population sizes the population growth rate will be low, but it will increase as the population increases, up to a point. At this point the population growth rate slows as carrying capacity is approached.");
			
				p.addAnswer(4, "grows fastest as it approaches carrying capacity",
				false,
				"No. As carrying capacity is neared, population growth rates approach zero.");
			
				p.addAnswer(5, "is always slowed by density-independent factors",
				false,
				"No. Both density-dependent and density-independent factors may play a role in limiting the growth rate of a population.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337039;


		
		

		
			
			p.question = "The logistic growth model differs from the exponential growth model in that it _____. (<script type=\"text/javascript\">ebook(\'5304\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "expresses the effects of population-limiting factors on exponential growth",
				true,
				"Correct. In the logistic model, the term (<i>K</i> - <i>N</i>)/<i>K</i> represents the effects of population-limiting factors that depress the exponential growth tendency, <i>rN</i>, to a greater degree as population size approaches the carrying capacity.");
			
				p.addAnswer(2, "is J-shaped and the exponential growth model is S-shaped",
				false,
				"No. The exponential curve is J-shaped, and the logistic curve is S-shaped.");
			
				p.addAnswer(3, "never shows the effects of population-limiting factors",
				false,
				"No. The exponential model does not show the effects of population-limiting factors, but the logistic model does.");
			
				p.addAnswer(4, "implies that population size stabilizes at <i>K</i> when the birth rate is zero",
				false,
				"No. At <i>K</i>, the birth and death rates are equal. Also, the exponential model doesn\'t show a stabilization of population size at <i>K</i>.");
			
				p.addAnswer(5, "implies that a population\'s growth rate will be highest when the population is small",
				false,
				"No. In the logistic model, a population\'s growth rate is greatest at intermediate population sizes. In the exponential model, a population\'s growth rate always increases as population size increases.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337040;


		
		

		
			
			p.question = "Which sentence below summarizes the Allee effect? (<script type=\"text/javascript\">ebook(\'5304\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "New individuals are added to the population most rapidly at intermediate population size.",
				false,
				"No. Although this idea does support the Allee effect, it does not summarize it.");
			
				p.addAnswer(2, "Individuals have a more difficult time surviving or reproducing if the population size is too small.",
				true,
				"Correct. Individuals, and therefore, populations may benefit from the protection of others. Or, in the example of rhinoceroses, small populations could mean that individuals cannot locate each other in order to mate.");
			
				p.addAnswer(3, "Populations adjust instantaneously and approach carrying capacity smoothly.",
				false,
				"No. This is an assumption of the logistic model.");
			
				p.addAnswer(4, "Different populations of the same species may show a balance of <i>K</i>-selected and <i>r</i>-selected traits.",
				false,
				"No. This has been shown in laboratory experiments, but it is not an example of the Allee effect.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337041;


		
		

		
			
			p.question = "A variety of opossum that lives on an island with no predators lives much longer than its relatives on the mainland, even when both are kept safely in a zoo. The island variant\'s genes have been selected for slow aging, while the mainland variant\'s have been selected for quick reproduction. The island opossum exhibits _____ selection, and the mainland opossum exhibits _____ selection. (<script type=\"text/javascript\">ebook(\'5304\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "<i>r</i>; <i>K</i>",
				false,
				"No. The opposite is true.");
			
				p.addAnswer(2, "<i>K</i>; <i>r</i>",
				true,
				"Correct. <i>K</i>-selection is most likely at work in the island population because many of the opossums live for a long time, making resource competition more of an issue. The mainland opossums do not approach their carrying capacity because of predation, so <i>r</i>-selection is most likely occurring in that population.");
			
				p.addAnswer(3, "nutrient; territory",
				false,
				"No. These are not types of selection.");
			
				p.addAnswer(4, "iteroparity; semelparity",
				false,
				"No. These are types of life histories, not types of selection.");
			
				p.addAnswer(5, "Clumped; uniform",
				false,
				"No. These are types of distributions, not types of selection.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337042;


		
		

		
			
			p.question = "Which one of the following would most likely be an example of a density-independent factor limiting population growth? (<script type=\"text/javascript\">ebook(\'5305\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "food availability",
				false,
				"No. Food availability increases and decreases with population size.");
			
				p.addAnswer(2, "diseases",
				false,
				"No. The ease with which a disease spreads increases and decreases with population size.");
			
				p.addAnswer(3, "accumulation of toxic wastes",
				false,
				"No. The accumulation of toxic wastes increases and decreases with population size.");
			
				p.addAnswer(4, "parasites",
				false,
				"No. The ease with which parasites spread through a population increases and decreases with population size.");
			
				p.addAnswer(5, "daily temperature extremes",
				true,
				"Correct. Density-independent factors such as daily temperatures are unrelated to population size.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337043;


		
		

		
			
			p.question = "A certain species of seal breeds and rears its young on rocky beaches. Competition for breeding sites is fierce, and males that do not secure a site will not reproduce. This behavior is an example of which mechanism of density-dependent population regulation? (<script type=\"text/javascript\">ebook(\'5305\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "competition for resources",
				false,
				"No. The seal\'s resources are out in the ocean and are presumably unlimited.");
			
				p.addAnswer(2, "toxic wastes",
				false,
				"No. Toxic wastes are not the issue here.");
			
				p.addAnswer(3, "intrinsic factors",
				false,
				"No. Intrinsic factors do not appear to limit seal reproduction.");
			
				p.addAnswer(4, "predation",
				false,
				"No. The seals have very few predators when they are out of the water.");
			
				p.addAnswer(5, "territoriality",
				true,
				"Correct. The inability of a male to secure a breeding territory will limit his ability to mate.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337044;


		
		

		
			
			p.question = "A particular environmental change causes the deaths of 25 individuals in a herd of 100 wild horses, and it kills 50 individuals in a herd of 200 horses. In this case, the growth of a wild horse population is most likely limited by _____. (Assume that the two herds are found in territories of equal size.) (<script type=\"text/javascript\">ebook(\'5305\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a density-dependent factor",
				false,
				"No. A density-dependent factor affects a larger percentage of the population as population density increases.");
			
				p.addAnswer(2, "food supply",
				false,
				"No. Food supply is usually a density-dependent factor. A density-dependent factor affects a larger percentage of the population as population density increases.");
			
				p.addAnswer(3, "a predator",
				false,
				"No. A predator is usually a density-dependent factor. A density-dependent factor affects a larger percentage of the population as population density increases.");
			
				p.addAnswer(4, "a density-independent factor",
				true,
				"Correct. A density-independent factor affects the same percentage of the population regardless of population density.");
			
				p.addAnswer(5, "the presence of another species that uses the same food resource",
				false,
				"No. Competition with individuals of another species is usually a density-dependent factor.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337045;


		
		

		
			
			p.question = "Which one of the following is most likely a density-dependent growth regulator of animal populations? (<script type=\"text/javascript\">ebook(\'5305\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a decrease in clutch size",
				true,
				"Correct. A density-dependent factor intensifies as the population increases in size.");
			
				p.addAnswer(2, "hurricanes",
				false,
				"No. The size of a population is unlikely to affect the occurrence and intensity of a hurricane.");
			
				p.addAnswer(3, "fires",
				false,
				"No. The size of an animal population is unlikely to affect the occurrence and intensity of a fire.");
			
				p.addAnswer(4, "droughts",
				false,
				"No. The size of an animal population is unlikely to affect the occurrence and intensity of a drought.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. Only one of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337046;


		
		

		
			
			p.question = "The cyclic growth exhibited by populations of snowshoe hares in the North American taiga most likely results from _____. (<script type=\"text/javascript\">ebook(\'5305\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "predation by lynx",
				false,
				"No. Fluctuations in the hare\'s food resources are important, too.");
			
				p.addAnswer(2, "fluctuations in the hare\'s food resources",
				false,
				"No. Predation by lynx is important, too.");
			
				p.addAnswer(3, "predation by lynx and fluctuations in the hare\'s food resources",
				true,
				"Correct. Recent studies indicate that both factors are involved.");
			
				p.addAnswer(4, "hunting by humans",
				false,
				"No. There is no evidence that hunting by humans is involved.");
			
				p.addAnswer(5, "weather changes",
				false,
				"No. There is no evidence that abiotic environmental factors are involved.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337047;


		
		

		
			
			p.question = "If you wanted to determine what percentage of the population of Thailand is less than 10 years old, you could look at _____. (<script type=\"text/javascript\">ebook(\'5306\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a logistic curve for the population",
				false,
				"No. A logistic curve is one type of curve that results from plotting population size against time. Such a plot does not distinguish among individuals of different age groups.");
			
				p.addAnswer(2, "the population\'s age structure",
				true,
				"Correct. A population\'s age structure is a plot that illustrates the number of individuals in each age group.");
			
				p.addAnswer(3, "a life table for the population",
				false,
				"No. A life table contains information on the probability of a particular event occurring at a particular age.");
			
				p.addAnswer(4, "a plot of population density",
				false,
				"No. Population density refers to the number of individuals per unit area regardless of age.");
			
				p.addAnswer(5, "the population\'s survivorship curve",
				false,
				"No. This provides information on the likelihood of surviving to a particular age.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337048;


		
		

		
			
			p.question = "An ecologist would suspect a population to be growing rapidly if it _____. (<script type=\"text/javascript\">ebook(\'5306\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "contains many more prereproductive than reproductive individuals",
				true,
				"Correct. Such an age structure would result in many individuals becoming reproductive and producing many offspring.");
			
				p.addAnswer(2, "is near its carrying capacity",
				false,
				"No. As carrying capacity is neared, the growth rate of a population approaches zero.");
			
				p.addAnswer(3, "is limited only by density-dependent factors",
				false,
				"No. This would not provide sufficient information to determine a population\'s growth rate.");
			
				p.addAnswer(4, "shows a clumped pattern of dispersion",
				false,
				"No. This concerns the distribution of a population, not the number of individuals of that population or the potential for change in population size.");
			
				p.addAnswer(5, "is far below its carrying capacity",
				false,
				"No. While a population far below its carrying capacity may be in a position to grow rapidly, it will not necessarily do so.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337049;


		
		

		
			
			p.question = "What absolutely essential resource is likely to limit the carrying capacity of Earth for humans? (<script type=\"text/javascript\">ebook(\'5306\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "oil",
				false,
				"No. There are alternative energy sources available.");
			
				p.addAnswer(2, "raw materials such as metals",
				false,
				"No. Raw materials will be a problem, but recycling should help keep them from limiting carrying capacity.");
			
				p.addAnswer(3, "water",
				true,
				"Correct. No organism can live without water. Water is already limiting the carrying capacity in many underdeveloped countries.");
			
				p.addAnswer(4, "space",
				false,
				"No. So far humans have shown a large capacity for living in crowded conditions.");
			
				p.addAnswer(5, "oxygen",
				false,
				"No. So far oxygen has not been in short supply, and humans can live in a slightly less oxygen-rich atmosphere.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337050;


		
		

		
			
			p.question = "To calculate the _____ of a nation, researchers summarize arable land, pasture, fossil energy land, and several other factors appropriated by each nation to produce all of the resources it consumes and to absorb all the waste it generates. (<script type=\"text/javascript\">ebook(\'5306\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "ecological footprint",
				true,
				"Correct. This concept summarizes the aggregate land and water area appropriated by each nation to produce all the resources it consumes and to absorb all the waste it generates.");
			
				p.addAnswer(2, "carrying capacity",
				false,
				"No. Although this is a related term, it is not the best answer. Carrying capacity is defined as the maximum population size that a particular environment can support.");
			
				p.addAnswer(3, "ecological capacity",
				false,
				"No. This refers to the actual resource base of each country.");
			
				p.addAnswer(4, "principles of energy flow",
				false,
				"No. These principles are explained in Chapter 55 and have to do with the flow of energy through ecosystems.");
			
				p.addAnswer(5, "life history",
				false,
				"No. Life history has to do with traits that affect an organism\'s survival and reproductive success, rather than resources of a nation.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

