

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "38: Angiosperm Reproduction and Biotechnology > Practice Test";
	ak.quiz_loc_with_commas = "38: Angiosperm Reproduction and Biotechnology, Practice Test";
	ak.quiz_title = "Practice Test";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 31;
	ak.non_essay_total = 31;
	ak.scored_item_total = 31;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336206;


		
		

		
			
			p.question = "In alternation of generations in plants _____. (<script type=\"text/javascript\">ebook(\'3801\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a sporophyte grows from a spore",
				false,
				"No. The sporophyte develops from an embryo; a spore grows into a gametophyte.");
			
				p.addAnswer(2, "the gametes are produced by the gametophyte through meiosis and cellular differentiation",
				false,
				"No. Gametophytes are haploid and therefore do not undergo meiosis.");
			
				p.addAnswer(3, "the spores are produced by the gametophyte by meiosis and cellular differentiation",
				false,
				"No. Gametophytes are haploid and therefore do not undergo meiosis.");
			
				p.addAnswer(4, "the sporophyte is the haploid generation",
				false,
				"No. The sporophyte is the diploid generation.");
			
				p.addAnswer(5, "the gametes are produced by the gametophyte through mitosis and cellular differentiation",
				true,
				"Correct. The haploid gametophyte produces gametes by mitosis and cellular differentiation.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336207;


		
		

		
			
			p.question = "Which association below is correct? (<script type=\"text/javascript\">ebook(\'3801\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "carpels; attraction of pollinators",
				false,
				"No. Petals are often brightly colored to attract pollinators.");
			
				p.addAnswer(2, "sepals; containment of sporangia",
				false,
				"No. Sepals do not contain sporangia; they enclose and protect a floral bud prior to its opening.");
			
				p.addAnswer(3, "stamens; development of female gametophytes",
				false,
				"No. Stamens are the sites at which male gametophytes develop.");
			
				p.addAnswer(4, "carpels; development of male gametophytes",
				false,
				"No. Carpels are the sites at which female gametophytes develop.");
			
				p.addAnswer(5, "stamens; development of filament and anther",
				true,
				"Correct. A stamen consists of a filament capped by a sporangia-bearing anther.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336208;


		
		

		
			
			p.question = "The male structures of angiosperms are called _____, and they produce _____. (<script type=\"text/javascript\">ebook(\'3801\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "stigmas; ovules",
				false,
				"No. Both of these are female structures.");
			
				p.addAnswer(2, "ovaries; ovules",
				false,
				"No. Both of these are female structures.");
			
				p.addAnswer(3, "anthers; ovaries",
				false,
				"No. However, this choice is partially correct.");
			
				p.addAnswer(4, "anthers; pollen",
				true,
				"Correct. Within the sporangia, or pollen sacs, of the anther, diploid microsporocytes undergo meiosis, each forming four haploid microspores that will develop into pollen grains.");
			
				p.addAnswer(5, "anthers; ovules",
				false,
				"No. However, this choice is partially correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336209;


		
		

		
			
			p.question = "The female structures of angiosperms are called _____, and they produce _____. (<script type=\"text/javascript\">ebook(\'3801\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "sepals; ovules",
				false,
				"No. Sepals protect buds, but they are not related to reproduction.");
			
				p.addAnswer(2, "carpels; ovules",
				true,
				"Correct. The female reproductive structure of flowers is the carpel, which encloses an ovary at the base, containing one or more ovules.");
			
				p.addAnswer(3, "anthers; sperm",
				false,
				"No. Both of these are male structures.");
			
				p.addAnswer(4, "anthers; pollen",
				false,
				"No. Both of these are male structures.");
			
				p.addAnswer(5, "anthers; ovules",
				false,
				"No. Anthers are male structures.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336210;


		
		

		
			
			p.question = "Flowers bear seeds in protective chambers called _____. (<script type=\"text/javascript\">ebook(\'3801\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "cones",
				false,
				"No. Flowers are produced by angiosperms; cones are produced by certain gymnosperms.");
			
				p.addAnswer(2, "anthers",
				false,
				"No. Anthers are male reproductive structures with chambers in which pollen grains are produced; it is the female reproductive structure that protects the seeds.");
			
				p.addAnswer(3, "sepals",
				false,
				"No. Sepals protect the entire flower bud as it develops.");
			
				p.addAnswer(4, "ovaries",
				true,
				"Correct. Embryo sacs develop inside ovules, which become the seeds; seeds are enclosed by ovaries, the basal part of carpels.");
			
				p.addAnswer(5, "antheridia",
				false,
				"No. Antheridia are male reproductive structures and are not associated with angiosperms.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336211;


		
		

		
			
			p.question = "Which two structures of a flower bear sporangia? (<script type=\"text/javascript\">ebook(\'3801\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "ovules and stamens",
				false,
				"No. This is not the best answer. Ovules do bear sporangia, but only part of the stamen does (the anther).");
			
				p.addAnswer(2, "ovaries and the receptacle",
				false,
				"No. Ovaries do house the ovules, which contain sporangia. The receptacle is the area where the four basic floral organs attach to the stem.");
			
				p.addAnswer(3, "sepal and the filament",
				false,
				"No. The sepal is a protective part of the flower, not reproductive. The filament is the part of the stamen that does not contain sporangia.");
			
				p.addAnswer(4, "ovules and anthers",
				true,
				"Correct. These are the structures that bear sporangia, where spores are produced by meiosis and gametophytes develop.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. Only ovules and anthers bear sporangia.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336212;


		
		

		
			
			p.question = "A generative cell and a tube cell originate when _____. (<script type=\"text/javascript\">ebook(\'3801\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a microsporocyte undergoes meiosis",
				false,
				"No. This process results in the formation of four haploid microspores that later give rise to the generative cell and the tube cell.");
			
				p.addAnswer(2, "a microsporocyte undergoes mitosis",
				false,
				"No. Microsporocytes are diploid and undergo meiosis to give rise to four haploid microspores.");
			
				p.addAnswer(3, "a microspore undergoes meiosis and cytokinesis",
				false,
				"No. Microspores are haploid; they do not undergo meiosis.");
			
				p.addAnswer(4, "a microspore undergoes mitosis and cytokinesis",
				true,
				"Correct. When a microspore undergoes mitosis and cytokinesis, two separate cells are produced that, along with a spore wall, make up a pollen grain.");
			
				p.addAnswer(5, "microspore mother cells undergo mitosis and cytokinesis",
				false,
				"No. Microspore mother cells are another name for microsporocytes.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336213;


		
		

		
			
			p.question = "How many pollen grains can potentially result from one microsporocyte? (<script type=\"text/javascript\">ebook(\'3801\',\'quiz\')</script>)";
			p.incorrect_any_expl = "No. A microsporocyte undergoes meiosis, producing four haploid microspores. Each microspore undergoes mitosis, resulting in two separate cells that become part of one pollen grain. Therefore, the division of four microspores results in four pollen grains.";
			p.incorrect_any_expl_flag = 1;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "1",
				false,
				"");
			
				p.addAnswer(2, "2",
				false,
				"");
			
				p.addAnswer(3, "4",
				true,
				"Correct. A microsporocyte undergoes meiosis, producing four haploid microspores. Each microspore undergoes mitosis, resulting in two separate cells that become part of one pollen grain. Therefore, the division of four microspores results in four pollen grains.");
			
				p.addAnswer(4, "8",
				false,
				"");
			
				p.addAnswer(5, "16",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336214;


		
		

		
			
			p.question = "What is the purpose of synergids in an ovule? (<script type=\"text/javascript\">ebook(\'3801\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Synergids divide, producing megaspores.",
				false,
				"No. This is the role of megasporocytes.");
			
				p.addAnswer(2, "Synergids divide, producing one large cell with eight haploid nuclei.",
				false,
				"No. This occurs in megaspores.");
			
				p.addAnswer(3, "Synergids function in the guidance of the pollen tube to the embryo sac.",
				true,
				"Correct. Synergids flank the egg cell.");
			
				p.addAnswer(4, "The function of synergids is unknown.",
				false,
				"No. This is true of antipodal cells.");
			
				p.addAnswer(5, "Synergids are the polar nuclei that share the cytoplasm of the large central cells of the embryo sac.",
				false,
				"No. These are just known as polar nuclei.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336215;


		
		

		
			
			p.question = "In the process of pollination, pollen grains are transferred from the _____ to the _____. (<script type=\"text/javascript\">ebook(\'3801\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "ovary; anther",
				false,
				"No. The ovary is the site of ovum production, and ova are not transferred during pollination.");
			
				p.addAnswer(2, "stigma; ovary",
				false,
				"No. The stigma, style, and ovary are all parts of the carpel.");
			
				p.addAnswer(3, "anther; sepal",
				false,
				"No. A sepal is a structure that encloses and protects the flower bud.");
			
				p.addAnswer(4, "carpel; stigma",
				false,
				"No. The stigma forms a portion of the carpel.");
			
				p.addAnswer(5, "anther; stigma",
				true,
				"Correct. Pollen is produced within the anther and is transferred to the stigma, from which it can migrate to the ova.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336216;


		
		

		
			
			p.question = "Like gymnosperms, many grasses and angiosperm trees are wind-pollinated. To conserve energy, these angiosperms do not produce complete flowers (complete flowers have all four of the basic parts). Which basic part would most likely be missing from wind-pollinated angiosperm flowers? (<script type=\"text/javascript\">ebook(\'3801\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "petals",
				true,
				"Correct. Petals are nonreproductive parts of a flower. They advertise a flower to pollinators and would not be needed by wind-pollinated angiosperms.");
			
				p.addAnswer(2, "sepals",
				false,
				"No. Sepals enclose and protect a floral bud prior to its opening.");
			
				p.addAnswer(3, "anthers",
				false,
				"No. Anthers are the sites of pollen production.");
			
				p.addAnswer(4, "ovaries",
				false,
				"No. Ovaries house ovules.");
			
				p.addAnswer(5, "fruits",
				false,
				"No. Fruits, which develop from ovaries, play a role in seed dispersal.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336217;


		
		

		
			
			p.question = "After fertilization, the _____ develops into a seed and the _____ develops into a fruit. (<script type=\"text/javascript\">ebook(\'3801\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "ovule; ovary",
				true,
				"Correct. The integuments of the ovule develop into the seed coat, which protects the embryo, and the ovary develops into a fruit.");
			
				p.addAnswer(2, "pollen grain; ovule",
				false,
				"No. The pollen grain carries the male gamete. The ovule houses the female gametophyte and develops into the seed.");
			
				p.addAnswer(3, "ovary; ovule",
				false,
				"No. The ovary develops into a fruit, and the ovule houses the female gametophyte and develops into the seed.");
			
				p.addAnswer(4, "egg; ovule",
				false,
				"No. Fertilization of the egg gives rise to an embryo. The female gametophyte, which produces the egg, is housed within the ovule.");
			
				p.addAnswer(5, "egg; ovary",
				false,
				"No. Fertilization of the egg gives rise to an embryo. However, the ovary does develop into a fruit.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336218;


		
		

		
			
			p.question = "A pea pod is formed from _____. A pea inside the pod is formed from _____. (<script type=\"text/javascript\">ebook(\'3801\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "an ovule; a carpel",
				false,
				"No. An ovule contains the female gametophyte and develops into the seed, not into the pea pod. The carpel forms the entire fruit, which is the pea pod.");
			
				p.addAnswer(2, "an ovary; an ovule",
				true,
				"Correct. A pod is a fruit, and a fruit develops from an ovary. The pea develops from an ovule surrounding a zygote and its food supply.");
			
				p.addAnswer(3, "an ovary; a pollen grain",
				false,
				"No. The ovary does develop into the pea pod. However, a pollen grain, which carries the male gamete, does not develop into the pea.");
			
				p.addAnswer(4, "an anther; an ovule",
				false,
				"No. The anther houses sporangia that give rise to the male gametophyte. However, the pea does develop from the ovule and the tissues that it surrounds.");
			
				p.addAnswer(5, "endosperm; an ovary",
				false,
				"No. Endosperm is a food source found within a seed. The ovary develops into the pea pod, not into the pea.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336219;


		
		

		
			
			p.question = "What are the results of the first mitotic division in a plant zygote? (<script type=\"text/javascript\">ebook(\'3801\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "suspensor and endosperm",
				false,
				"No. The suspensor is the result of subsequent divisions of the basal cell. Endosperm development precedes embryo development.");
			
				p.addAnswer(2, "basal cell and suspensor",
				false,
				"No. A basal cell is one result of this first division, but the suspensor is the result of subsequent divisions of the basal cell.");
			
				p.addAnswer(3, "proembryo and terminal cell",
				false,
				"No. A terminal cell is one result of this first division, but a proembryo is the result of subsequent divisions of the terminal cell.");
			
				p.addAnswer(4, "basal cell and terminal cell",
				true,
				"Correct. The terminal cell eventually gives rise to most of the embryo. The basal cell continues to divide, producing the suspensor that anchors the embryo to the parent plant.");
			
				p.addAnswer(5, "endosperm and proembryo",
				false,
				"No. Endosperm development precedes embryo development. A proembryo is the result of subsequent divisions of the terminal cell.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336220;


		
		

		
			
			p.question = "Which portion of an embryonic plant consists of the shoot tip with a pair of miniature leaves? (<script type=\"text/javascript\">ebook(\'3801\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "seed coat",
				false,
				"No. The seed coat is a hard, protective layer that forms from the integuments of the ovule.");
			
				p.addAnswer(2, "epicotyl",
				true,
				"Correct. This is the portion of the embryonic axis above where the cotyledons are attached.");
			
				p.addAnswer(3, "radicle",
				false,
				"No. This is the embryonic root and the area where the hypocotyl terminates.");
			
				p.addAnswer(4, "scutellum",
				false,
				"No. This is a specialized cotyledon found in members of the grass family.");
			
				p.addAnswer(5, "hypocotyl",
				false,
				"No. This is the area of the embryonic axis below where the cotyledons are attached.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336221;


		
		

		
			
			p.question = "Which one of the following best describes the function of fruits? (<script type=\"text/javascript\">ebook(\'3801\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "protection and dispersal of seeds",
				true,
				"Correct. When seeds develop from ovules, the ovary of a flower develops into a fruit, which protects the enclosed seeds and aids in their dispersal by wind or animals.");
			
				p.addAnswer(2, "rewards for pollinators",
				false,
				"No. Fruits are produced after pollination has occurred.");
			
				p.addAnswer(3, "protection from pollinators",
				false,
				"No. Fruits are produced after pollination has occurred.");
			
				p.addAnswer(4, "storage of food for the plant to consume through the winter",
				false,
				"No. Most fruits detach from the plant when ripe; therefore, they cannot be food storage organs for the plant.");
			
				p.addAnswer(5, "deterrent to herbivores, stopping them from eating leaves",
				false,
				"No. There is a considerable amount of energy stored in fruit; there are energetically less expensive ways of deterring herbivores.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336222;


		
		

		
			
			p.question = "What is the correct definition of an aggregate fruit? (<script type=\"text/javascript\">ebook(\'3801\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a fruit that results from a single flower that has more than one carpel, each forming a small fruit",
				true,
				"Correct. An example of an aggregate fruit is a raspberry.");
			
				p.addAnswer(2, "a fruit in which other floral parts in addition to ovaries contribute to what we call the fruit",
				false,
				"No. Apples are an example of this type of fruit, called an accessory fruit.");
			
				p.addAnswer(3, "a fruit that develops from a group of flowers tightly clustered together",
				false,
				"No. Pineapples are an example of this type of fruit, called a multiple fruit.");
			
				p.addAnswer(4, "a fruit derived from a single carpel or several fused carpels",
				false,
				"No. A peach is an example of this type of fruit, called a simple fruit.");
			
				p.addAnswer(5, "a fruit that ripens about the same time that its seeds complete their development",
				false,
				"No. This is a characteristic typical of most fruits.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336223;


		
		

		
			
			p.question = "Why do seeds need water to germinate? (<script type=\"text/javascript\">ebook(\'3801\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Water provides energy.",
				false,
				"No. However, plants need water for many life processes.");
			
				p.addAnswer(2, "Imbibition of water causes the seed coat to swell and allows the cells of the embryo to rehydrate.",
				true,
				"Correct. Imbibing water causes the seed coat to swell and split open and triggers metabolic changes in the embryo.");
			
				p.addAnswer(3, "Water activates the chlorophyll molecules so that photosynthesis can begin.",
				false,
				"No. Photosynthesis cannot begin until after germination.");
			
				p.addAnswer(4, "Water dissolves the minerals in the soil so that they become available to the seed.",
				false,
				"No. A seed cannot do much with minerals in the soil before germination.");
			
				p.addAnswer(5, "Because water has a neutral pH, it balances the soil pH and makes it favorable for seed germination.",
				false,
				"No. Soil and rainwater are not exactly neutral. Furthermore, a neutral solution does not necessarily function as a buffer.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336224;


		
		

		
			
			p.question = "What is the underlying feature that allows plants to reproduce asexually? (<script type=\"text/javascript\">ebook(\'3802\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "They have two types of undifferentiated, dividing cells, parenchyma cells and meristems.",
				true,
				"Correct. Plants grow indeterminately, so they always have a supply of cells that can divide rapidly and undergo differentiation.");
			
				p.addAnswer(2, "They don\'t require a pollinator.",
				false,
				"No. Not requiring a pollinator is an advantage of asexual reproduction, but it is not an underlying cause.");
			
				p.addAnswer(3, "They can form adventitious roots.",
				false,
				"No. The ability to form adventitious roots depends on the underlying feature.");
			
				p.addAnswer(4, "They can form adventitious shoots.",
				false,
				"No. The ability to form adventitious shoots depends on the underlying feature.");
			
				p.addAnswer(5, "They don\'t require genetic recombination.",
				false,
				"No. This is not the underlying feature that allows plants to reproduce asexually.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336225;


		
		

		
			
			p.question = "In an environment that is very stable, with reliable moisture and temperature, what type of reproduction would be most advantageous for a plant and why? (<script type=\"text/javascript\">ebook(\'3802\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Sexual reproduction because it is always better to increase genetic variation.",
				false,
				"No. If the plant is well-adapted to the environment, asexual reproduction will ensure that genes that are \"working\" will be passed on to the next generation. Rolling the dice with sexual reproduction may produce poorly adapted offspring.");
			
				p.addAnswer(2, "Asexual reproduction because it ensures that the genes that have proven to adapt the plant well to the environment will be passed on to the next generation.",
				true,
				"Correct. Sexual reproduction will inevitably produce some offspring that are not as well adapted as the parent. If it works, don\'t fix it.");
			
				p.addAnswer(3, "Sexual reproduction because it will ensure that the most advantageous genes are passed on to the next generation.",
				false,
				"No. Sexual reproduction is a roll of the dice. There is no way to ensure that the most advantageous genes will be passed on.");
			
				p.addAnswer(4, "Asexual reproduction because it increases the genetic variation with in the population.",
				false,
				"No. Asexual reproduction produces clones. It does not increase genetic variation.");
			
				p.addAnswer(5, "Sexual reproduction because it requires less energy.",
				false,
				"No. In general sexual reproduction requires more energy.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336226;


		
		

		
			
			p.question = "Which statement below accurately describes the role of <i>S</i>-genes in plants? (<script type=\"text/javascript\">ebook(\'3802\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "<i>S</i>-genes are unique to plants and make them more susceptible to manipulation by bioengineers.",
				false,
				"No. This is not an accurate description of <i>S</i>-genes.");
			
				p.addAnswer(2, "<i>S</i>-genes are involved in self-recognition. They prevent self-fertilization in many plant species.",
				true,
				"Correct. If a pollen grain has an <i>S</i>-gene allele that matches an allele of the stigma upon which it lands, the pollen tube fails to grow.");
			
				p.addAnswer(3, "<i>S</i>-genes make plants more resistant to pests.",
				false,
				"No. This is not an accurate description of <i>S</i>-genes.");
			
				p.addAnswer(4, "If pollen from another species lands on the stigma of a mustard plant, <i>S</i>-genes block the pollen tube growth.",
				false,
				"No. <i>S</i>-genes are involved in stopping self-fertilization. Other mechanisms are involved in blocking interspecific fertilization.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336227;


		
		

		
			
			p.question = "How do most flowering plants avoid self-fertilization? (<script type=\"text/javascript\">ebook(\'3802\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Most plant species are dioecious.",
				false,
				"No. Although dioecious plants avoid self-fertilization, this is not the most common strategy.");
			
				p.addAnswer(2, "The physical arrangement of stamens and carpels makes self-fertilization unlikely.",
				false,
				"No. This strategy is used by many plants, but it is not the most common strategy.");
			
				p.addAnswer(3, "Stamens and carpels on the same plant mature at different times.",
				false,
				"No. This strategy is used by many plants, but it is not the most common strategy.");
			
				p.addAnswer(4, "They have self-incompatibility and reject their own pollen.",
				true,
				"Correct. Self-incompatibility is the most common anti-selfing mechanism in plants.");
			
				p.addAnswer(5, "They discourage pollinators.",
				false,
				"No. Not all flowering plants require pollinators, but those that do have mechanisms to encourage pollinators.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336228;


		
		

		
			
			p.question = "In this type of asexual reproduction, seeds are produced even without the joining of sperm and eggs. (<script type=\"text/javascript\">ebook(\'3802\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "callus",
				false,
				"No. This is a group of undifferentiated cells that forms at the end of a cut shoot. Adventitious roots develop from the callus.");
			
				p.addAnswer(2, "fragmentation",
				false,
				"No. This is the separation of a parent plant into parts that develop into whole plants.");
			
				p.addAnswer(3, "apomixis",
				true,
				"Correct. A diploid cell in the ovule gives rise to the embryo, and the ovule matures into seeds.");
			
				p.addAnswer(4, "cloning",
				false,
				"No. Clones are the result of fragmentation, or clones can be grown from cuttings.");
			
				p.addAnswer(5, "grafting",
				false,
				"No. Grafting occurs when a twig or bud from one plant is grafted onto a plant of a closely related species or a different variety of the same species.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336229;


		
		

		
			
			p.question = "A botanist had an apple tree in his yard that produced eight different varieties of apple. This tree was most likely produced by _____. (<script type=\"text/javascript\">ebook(\'3802\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "repeated selection of seedlings with desirable qualities",
				false,
				"No. Selection would be for a single phenotype&#151;a single variety.");
			
				p.addAnswer(2, "inducing mutations in the young seedling",
				false,
				"No. However, inducing mutations is a tool that a breeder could use to increase variability upon which selections can be made.");
			
				p.addAnswer(3, "grafting scions of different varieties onto the same root stock",
				true,
				"Correct. Grafting is an asexual means of combining one or more different shoot phenotypes on a single root stock.");
			
				p.addAnswer(4, "protoplast fusion of different varieties in the same culture tube",
				false,
				"No. Protoplast fusion could be used to combine two different varieties, but the offspring would be unique and different from either of the two donors.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. Grafting can be used to combine any number of different compatible scions onto a compatible root stock.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336230;


		
		

		
			
			p.question = "Which statement below accurately describes protoplast fusion? (<script type=\"text/javascript\">ebook(\'3802\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "It is not possible to fuse two protoplasts from different plant species that are not reproductively compatible.",
				false,
				"No. It is possible to fuse two protoplasts from different plant species that otherwise would not be reproductively compatible.");
			
				p.addAnswer(2, "Protoplasts can be screened for mutations that may improve the agricultural value of the plant.",
				true,
				"Correct. This is the accurate statement.");
			
				p.addAnswer(3, "Protoplasts are plant cells with their nuclei removed by fungal enzyme treatments.",
				false,
				"No. Protoplasts are plant cells that have had their cell walls removed by fungal enzyme treatments.");
			
				p.addAnswer(4, "Researchers can couple protoplast fusion with grafting techniques to invent new plant varieties.",
				false,
				"No. Researchers can couple protoplast fusion with tissue culture methods to invent new plant varieties.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. Only one of the statements is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336231;


		
		

		
			
			p.question = "Which of the following can be done by using biotechnology, but cannot be done using traditional agricultural breeding practices? (<script type=\"text/javascript\">ebook(\'3803\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "clone production of desirable plants",
				false,
				"No. Asexual reproduction by cuttings also produces clones.");
			
				p.addAnswer(2, "variability for selection in a population",
				false,
				"No. Sexual reproduction, particularly open pollination, provides variability for breeders.");
			
				p.addAnswer(3, "introduction of genes into a crop from a related species",
				false,
				"No. Some crops are intergeneric hybrids, such as triticale.");
			
				p.addAnswer(4, "introduction of non-plant genes into a crop",
				true,
				"Correct. DNA from any organism can be introduced into a plant, using genetic engineering.");
			
				p.addAnswer(5, "All of the above can be performed by traditional methods.",
				false,
				"No. DNA from non-plants can be introduced into a plant using genetic engineering.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336232;


		
		

		
			
			p.question = "What is the importance of triticale in battling world hunger? (<script type=\"text/javascript\">ebook(\'3803\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "It shows that hybridization can occur across genus boundaries.",
				false,
				"No. This is true, but it does not have a lot to do with world hunger.");
			
				p.addAnswer(2, "It is a hybrid grain with good tolerance of cold and moisture that grows well on marginal land.",
				true,
				"Correct. Crops like triticale may be important because they can be grown on land that has not traditionally been used for agriculture. Putting more marginal land into production can increase food production.");
			
				p.addAnswer(3, "It shows that good results can be obtained with persistence.",
				false,
				"No. Although this is a good lesson, it does not really relate to world hunger.");
			
				p.addAnswer(4, "It is an example of artificial selection because some of the intermediate varieties would not have survived on their own.",
				false,
				"No. This is probably true, but it does not relate directly to battling world hunger.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the answers is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336233;


		
		

		
			
			p.question = "What does the \"<i>Bt</i>\" in <i>Bt</i> maize refer to? (<script type=\"text/javascript\">ebook(\'3803\',\'quiz\')</script>)";
			p.incorrect_any_expl = "No. <i>Bt</i> maize contains genes from <i>Bacillus thuringiensis</i>, which encode for a protein that causes plant cells to release a protoxin. The protoxin is activated into a harmful toxin in the guts of insects.";
			p.incorrect_any_expl_flag = 1;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a gene that makes the husk of the corn too tough for insects to penetrate",
				false,
				"");
			
				p.addAnswer(2, "a gene that causes the plants to emit a weed toxin",
				false,
				"");
			
				p.addAnswer(3, "a gene that reduces the amount of water the plants need to grow",
				false,
				"");
			
				p.addAnswer(4, "a gene that causes the plants to produce a chemical that becomes toxic within insect guts",
				true,
				"Correct. <i>Bt</i> maize contains genes from <i>Bacillus thuringiensis</i>, which encode for a protein that causes plant cells to release a protoxin. The protoxin is activated into a harmful toxin in the guts of insects.");
			
				p.addAnswer(5, "a gene that increases the level of vitamin A found in maize",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336234;


		
		

		
			
			p.question = "Why is switchgrass being considered as a source for biofuels? (<script type=\"text/javascript\">ebook(\'3803\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "It can grow 3-4 meters per year.",
				false,
				"No. Some species of poplars can grow that fast.");
			
				p.addAnswer(2, "It can be burned without producing CO<sub>2</sub>.",
				false,
				"No. So far nothing organic can make that claim.");
			
				p.addAnswer(3, "It can be grown in areas that are not suitable for most agricultural crops.",
				true,
				"Correct. It is difficult to justify using agricultural land to produce fuel when we are having difficulty feeding all the humans in the world.");
			
				p.addAnswer(4, "It is easy to genetically modify.",
				false,
				"No. Switchgrass has not proven to be very different from other plants as far as genetic modification.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. Only one of the answers is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336235;


		
		

		
			
			p.question = "What is a major advantage of herbicide-resistant crops? (<script type=\"text/javascript\">ebook(\'3803\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "They allow farmers to \"weed\" with herbicides, cutting down on soil tillage and erosion.",
				true,
				"Correct. There are many pros and cons to herbicide-resistant crops, but they do allow no-till cultivation which preserves the soil.");
			
				p.addAnswer(2, "They have greater nutritional value.",
				false,
				"No. Some transgenic crops have been developed to have greater nutritional value, but that is not the case with herbicide-resistant crops.");
			
				p.addAnswer(3, "They are more resistant to disease.",
				false,
				"No. They are just resistant to herbicides.");
			
				p.addAnswer(4, "They produce toxins that kill insects but are harmless to humans.",
				false,
				"No. <i>Bt</i> crops do this.");
			
				p.addAnswer(5, "They allow farmers to use as much herbicide as they want without worrying about harming the crops.",
				false,
				"No. This is not an advantage of herbicide-resistant crops, but it is feared that some farmers will use more herbicide than necessary, putting more toxins into the environment.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336236;


		
		

		
			
			p.question = "\"Transgene escape\" would occur if _____. (<script type=\"text/javascript\">ebook(\'3803\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a genetically modified crop from one country is transplanted to another country",
				false,
				"No. Transgene escape refers to the transfer of a genetically modified gene from the transformed plant to a neighboring plant, particularly related weedy plants.");
			
				p.addAnswer(2, "a genetically modified crop is hybridized with a local weed",
				true,
				"Correct. Transgene escape refers to a modified gene crossing from the modified crop to an interfertile local weed.");
			
				p.addAnswer(3, "a genetically modified crop is allowed to freely self-pollinate",
				false,
				"No. Transgene escape refers to the transfer of a genetically modified gene from the transformed plant to a neighboring plant, particularly related weedy plants.");
			
				p.addAnswer(4, "terminator genes also are inserted into a genetically modified crop",
				false,
				"No. Transgene escape refers to the transfer of a genetically modified gene from the transformed plant to a neighboring plant, particularly related weedy plants.");
			
				p.addAnswer(5, "chloroplast DNA is genetically modified",
				false,
				"No. Transgene escape refers to the transfer of a genetically modified gene from the transformed plant to a neighboring plant, particularly related weedy plants.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

