

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "54: Community Ecology > Activities Quiz";
	ak.quiz_loc_with_commas = "54: Community Ecology, Activities Quiz";
	ak.quiz_title = "Activities Quiz";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 15;
	ak.non_essay_total = 15;
	ak.scored_item_total = 15;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337054;


		
		

		
			
			p.question = "A human eats a deer. Which of these terms applies to the relationship between the human and the deer? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?53&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Interspecific Interactions</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "predation",
				true,
				"The human is the predator and the deer is the prey.");
			
				p.addAnswer(2, "competition",
				false,
				"In this situation the human and the deer are not competing for the same resource.");
			
				p.addAnswer(3, "parasitism",
				false,
				"While it is not parasitism per se, the relationship between the human and the deer can be viewed as an extreme form of parasitism.");
			
				p.addAnswer(4, "commensalism",
				false,
				"In commensalism, one member of the species pair benefits and the other is unaffected.");
			
				p.addAnswer(5, "mutualism",
				false,
				"In mutualism, both members of the species pair benefit.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337055;


		
		

		
			
			p.question = "Humans and sharks both eat fish. Which of these terms applies to the relationship between the human and the shark? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?53&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Interspecific Interactions</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "predation",
				false,
				"Predation requires that one member of the species pair kills and eats the other.");
			
				p.addAnswer(2, "competition",
				true,
				"The human and the shark are both competing for a resource (fish).");
			
				p.addAnswer(3, "parasitism",
				false,
				"The human is neither a host for, nor a parasite of, the shark.");
			
				p.addAnswer(4, "commensalism",
				false,
				"In commensalism, one member of the species pair benefits and the other is unaffected; in this case neither the human nor the shark gets as much fish as they would get in the absence of the other.");
			
				p.addAnswer(5, "mutualism",
				false,
				"In mutualism, both members of the species pair benefit; neither the human nor the shark benefit from this relationship.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337056;


		
		

		
			
			p.question = "Humans who have pets tend to be healthier than humans who do not have pets. Which of these terms applies to the relationship between a human and a pet? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?53&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Interspecific Interactions</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "predation",
				false,
				"Predation requires that one member of the species pair kills and eats the other.");
			
				p.addAnswer(2, "competition",
				false,
				"A human does not compete for resources with a pet (though sometimes my cats lead me to think we are).");
			
				p.addAnswer(3, "parasitism",
				false,
				"The human is neither a host for, nor a parasite of, a pet.");
			
				p.addAnswer(4, "commensalism",
				false,
				"In commensalism, one member of the species pair benefits and the other is unaffected; in this case both the human and the pet are being affected by the relationship.");
			
				p.addAnswer(5, "mutualism",
				true,
				"In mutualism, both members of the species pair benefit; in this case the human is healthier and the pet is getting room and board.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337057;


		
		

		
			
			p.question = "Which of these terms applies to the relationship between a dog and a blood-sucking tick? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?53&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Interspecific Interactions</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "predation",
				false,
				"Predation requires that one member of the species pair kills and eats the other.");
			
				p.addAnswer(2, "competition",
				false,
				"The dog and the tick are not competing for resources.");
			
				p.addAnswer(3, "parasitism",
				true,
				"The tick benefits at the expense of the dog; the dog is the host and the tick is the parasite.");
			
				p.addAnswer(4, "commensalism",
				false,
				"In commensalism, one member of the species pair benefits and the other is unaffected; in this case both the dog and the tick are being affected.");
			
				p.addAnswer(5, "mutualism",
				false,
				"In mutualism, both members of the species pair benefit; in this case the tick is provides no benefit to the dog.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337058;


		
		

		
			
			p.question = "An egret eats insects stirred up by grazing animals. Which of these terms applies to the relationship between the egret and the grazing animal? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?53&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Interspecific Interactions</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "predation",
				false,
				"Predation requires that one member of the species pair kills and eats the other.");
			
				p.addAnswer(2, "competition",
				false,
				"The egret and the grazing animal are not competing for a resource.");
			
				p.addAnswer(3, "parasitism",
				false,
				"The egret is neither a host for, nor a parasite of, the grazing animal.");
			
				p.addAnswer(4, "commensalism",
				true,
				"In commensalism, one member of the species pair benefits and the other is unaffected; in this case the egret is getting a meal and the grazing animals are unaffected.");
			
				p.addAnswer(5, "mutualism",
				false,
				"In mutualism, both members of the species pair benefit; in this case only one member of the species pair benefits.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337059;


		
		

		
			
			p.question = "In an ecosystem, phytoplankton are _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?53&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Food Webs</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "producers",
				true,
				"Autotrophs, such as phytoplankton, are producers.");
			
				p.addAnswer(2, "primary consumers",
				false,
				"Phytoplankton do not feed on producers.");
			
				p.addAnswer(3, "secondary consumers",
				false,
				"Phytoplankton do not feed on primary consumers.");
			
				p.addAnswer(4, "tertiary consumers",
				false,
				"Phytoplankton do not feed on secondary consumers.");
			
				p.addAnswer(5, "detritivores",
				false,
				"The phytoplankton do not feed on either wastes or already dead organisms.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337060;


		
		

		
			
			p.question = "An earthworm that feeds on the remains of plants and animals is acting as a _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?53&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Food Webs</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "producer",
				false,
				"Producers are autotrophs; earthworms are not autotrophs.");
			
				p.addAnswer(2, "primary consumer",
				false,
				"The earthworm is not feeding on producers.");
			
				p.addAnswer(3, "secondary consumer",
				false,
				"The earthworm is not feeding on primary consumers.");
			
				p.addAnswer(4, "tertiary consumer",
				false,
				"The earthworm is not feeding on secondary consumers.");
			
				p.addAnswer(5, "detritivore",
				true,
				"The earthworm is feeding on the remains of dead organisms.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337061;


		
		

		
			
			p.question = "When a human eats a steak, the human is acting as a _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?53&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Food Webs</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "producer",
				false,
				"Producers are autotrophs; humans are not autotrophs.");
			
				p.addAnswer(2, "primary consumer",
				false,
				"The cow is a primary consumer.");
			
				p.addAnswer(3, "secondary consumer",
				true,
				"By feeding on a primary consumer, the human is acting as a secondary consumer.");
			
				p.addAnswer(4, "tertiary consumer",
				false,
				"The human is not eating a secondary consumer.");
			
				p.addAnswer(5, "detritivore",
				false,
				"The human is not feeding on wastes or the remains of an organism killed by nonhumans.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337062;


		
		

		
			
			p.question = "A cow eating grass is an example of a _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?53&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Food Webs</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "producer",
				false,
				"The grass is a producer.");
			
				p.addAnswer(2, "primary consumer",
				true,
				"By feeding on a producer, the cow is acting as a primary consumer.");
			
				p.addAnswer(3, "secondary consumer",
				false,
				"The cow is not feeding on a primary consumer.");
			
				p.addAnswer(4, "tertiary consumer",
				false,
				"The cow is not feeding on secondary consumers.");
			
				p.addAnswer(5, "detritivore",
				false,
				"The cow is not feeding on either wastes or already dead organisms.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337063;


		
		

		
			
			p.question = "A human who just ate a hamburger is eaten by a shark while swimming. The shark is acting as a _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?53&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Food Webs</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "producer",
				false,
				"Producers are autotrophs; sharks are not autotrophs.");
			
				p.addAnswer(2, "primary consumer",
				false,
				"The cow that became the hamburger is the primary consumer.");
			
				p.addAnswer(3, "secondary consumer",
				false,
				"The human that ate the cow is the secondary consumer.");
			
				p.addAnswer(4, "tertiary consumer",
				true,
				"The shark that ate the human that ate the cow that ate the grass is the tertiary consumer.");
			
				p.addAnswer(5, "detritivore",
				false,
				"The shark is not feeding on either wastes or already dead organisms.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337064;


		
		

		
			
			p.question = "Which of these is a starting point for primary succession? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?53&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Primary Succession</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a surface exposed by a retreating glacier",
				true,
				"Such a surface lacks any life and is thus a starting point for primary succession.");
			
				p.addAnswer(2, "abandoned farmland",
				false,
				"Abandoned farmland is a starting point for secondary succession.");
			
				p.addAnswer(3, "an abandoned city",
				false,
				"An abandoned city is a starting point for secondary succession.");
			
				p.addAnswer(4, "a neglected yard",
				false,
				"A neglected yard is a starting point for secondary succession.");
			
				p.addAnswer(5, "none of these is a starting point for primary succession",
				false,
				"One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337065;


		
		

		
			
			p.question = "According to island biogeography, what is the relationship between an island\'s distance from the mainland and the number of species present on the island? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?53&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Exploring Island Biogeography</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The closer an island is to the mainland, the fewer the number of species found on the island.",
				false,
				"The closer an island is to the mainland, the easier it is for colonizers to reach the island.");
			
				p.addAnswer(2, "The farther an island is from the mainland, the larger the number of species found on the island.",
				false,
				"The farther an island is from the mainland, the harder it is for colonizers to reach the island.");
			
				p.addAnswer(3, "The farther an island is from the mainland, the fewer the number of species found on the island.",
				true,
				"Increasing the distance from the mainland increases the difficulty of colonizers reaching the island; thus, the greater the distance, the fewer the number of species on the island.");
			
				p.addAnswer(4, "The closer an island is to the mainland, the fewer the number of species found on the island; and the farther an island is from the mainland, the larger the number of species found on the island.",
				false,
				"Neither of these statements is correct.");
			
				p.addAnswer(5, "There is no relationship between the distance from the mainland and the number of species found on an island.",
				false,
				"Yes, there is.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337066;


		
		

		
			
			p.question = "Why is a new island more hospitable to colonizers than an older island is? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?53&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Exploring Island Biogeography</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Competition is more intense on the newer island.",
				false,
				"Competition is less intense on the newer island.");
			
				p.addAnswer(2, "Predation is less of a factor on older islands.",
				false,
				"Predation is less of a factor on newer islands.");
			
				p.addAnswer(3, "The extinction rate is higher on the newer island.",
				false,
				"The extinction rate is lower on the newer island.");
			
				p.addAnswer(4, "Competition is less intense on the newer island.",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(5, "The intensity of both competition and predation is less on the newer island.",
				true,
				"Immigrants to a newer island are likely to experience lower levels of both competition and predation than are immigrants to older islands.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337067;


		
		

		
			
			p.question = "What is the relationship between colonizing success and the number of species already established on an island? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?53&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Exploring Island Biogeography</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "As the number of established species on an island decreases, colonizing success also decreases.",
				false,
				"Consider that fewer species already established on an island could mean less competition than if there were a larger number of established species.");
			
				p.addAnswer(2, "There is no relationship between the number of established species on an island and colonizing success.",
				false,
				"Yes, there is.");
			
				p.addAnswer(3, "As the number of established species on an island increases, colonizing success also decreases.",
				true,
				"As the number of established species on an island increases, there is likely to be a concomitant increase in the intensity of competition and predation, which make colonization more difficult.");
			
				p.addAnswer(4, "As the number of established species on an island increases, colonizing success also increases.",
				false,
				"Consider that as the number of established species on an island increases, the intensity of competition and predation is also likely to increase.");
			
				p.addAnswer(5, "As the number of established species on an island decreases, colonizing success also decreases; and as the number of established species on an island increases, colonizing success also increases.",
				false,
				"Both of these statements are incorrect. Fewer species on an island would likely mean that competition and predation are less intense, and more species on an island would likely mean that competition and predation are more intense.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337068;


		
		

		
			
			p.question = "The number of species on an island remains relatively constant when _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?53&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Exploring Island Biogeography</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the rate of successful colonization is less than the extinction rate",
				false,
				"Such a situation would result in a decrease in the number of species found on the island.");
			
				p.addAnswer(2, "the rate of successful colonization equals the extinction rate",
				true,
				"At this point the number of successful introductions to an island equals the number of extinctions, and thus the total number of species remains unchanged.");
			
				p.addAnswer(3, "the rate of successful colonization is greater than the extinction rate",
				false,
				"Such a situation results in an increase in the number of species on the island.");
			
				p.addAnswer(4, "species richness increases",
				false,
				"Increased species richness means there has been an increase in the number of species.");
			
				p.addAnswer(5, "none of these occur",
				false,
				"One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

