

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "GraphIt! Quiz > GraphIt! Quiz > Animal Food Production Efficiency and Food Policy";
	ak.quiz_loc_with_commas = "GraphIt! Quiz, GraphIt! Quiz, Animal Food Production Efficiency and Food Policy";
	ak.quiz_title = "Animal Food Production Efficiency and Food Policy";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 7;
	ak.non_essay_total = 7;
	ak.scored_item_total = 7;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337453;


		
		

		
			
			p.question = "Which animal product is least efficient at converting feed consumed into the final product?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "eggs",
				false,
				"");
			
				p.addAnswer(2, "milk",
				false,
				"");
			
				p.addAnswer(3, "chicken",
				false,
				"");
			
				p.addAnswer(4, "beef",
				true,
				"");
			
				p.addAnswer(5, "pork",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337454;


		
		

		
			
			p.question = "Roughly how many pounds of pork do you expect to get for every 100 pounds of feed consumed?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "20",
				true,
				"");
			
				p.addAnswer(2, "100",
				false,
				"");
			
				p.addAnswer(3, "130",
				false,
				"");
			
				p.addAnswer(4, "10",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337455;


		
		

		
			
			p.question = "Assume you are raising beef and that feed is costing you $1.00 per pound. Roughly how much money are you spending on feed for each pound of beef produced?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "$1.20",
				false,
				"");
			
				p.addAnswer(2, "$0.12",
				false,
				"");
			
				p.addAnswer(3, "$120.00",
				false,
				"");
			
				p.addAnswer(4, "$12.00",
				true,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337456;


		
		

		
			
			p.question = "Surprisingly, milk has a conversion efficiency greater than 100%. What is the best explanation for this?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Most of milk\'s mass comes from water consumption, not feed consumption.",
				true,
				"");
			
				p.addAnswer(2, "Cows and cattle are generally better than other animals at converting feed into product.",
				false,
				"");
			
				p.addAnswer(3, "Milk producers have been applying innovative practices that should soon raise milk production efficiency to 150%.",
				false,
				"");
			
				p.addAnswer(4, "This represents a measurement error in the data.",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337457;


		
		

		
			
			p.question = "For a country with abundant land and water resources but limited financial resources, which animal product would most likely be favored by agricultural policy?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "milk",
				true,
				"");
			
				p.addAnswer(2, "pork",
				false,
				"");
			
				p.addAnswer(3, "chicken",
				false,
				"");
			
				p.addAnswer(4, "eggs",
				false,
				"");
			
				p.addAnswer(5, "beef",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337458;


		
		

		
			
			p.question = "For a country where chicken raising and eating is a cultural taboo but water resources are scarce, which animal product would most likely be favored by agricultural policy?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "chicken",
				false,
				"");
			
				p.addAnswer(2, "milk",
				false,
				"");
			
				p.addAnswer(3, "pork",
				true,
				"");
			
				p.addAnswer(4, "eggs",
				false,
				"");
			
				p.addAnswer(5, "beef",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337459;


		
		

		
			
			p.question = "Despite its high resource usage, beef is a major commodity due to the high value per pound of the final product. Which of the following changes would cause a reduction in beef production?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "an agricultural program that subsidized pork production so that the profit per pound of pork was comparable to that for beef",
				false,
				"");
			
				p.addAnswer(2, "a precipitous fall in the price per pound of beef",
				false,
				"");
			
				p.addAnswer(3, "a dramatic rise in the cost of feed, land, and water to the beef producer",
				false,
				"");
			
				p.addAnswer(4, "all of the above",
				true,
				"");
			
				p.addAnswer(5, "none of the above",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

