

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "Investigation Quiz > How Do Thyroxine and TSH Affect Metabolism?";
	ak.quiz_loc_with_commas = "Investigation Quiz, How Do Thyroxine and TSH Affect Metabolism?";
	ak.quiz_title = "How Do Thyroxine and TSH Affect Metabolism?";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 17;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 17;
	ak.non_essay_total = 0;
	ak.scored_item_total = 0;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337826;


		
		

		
			p.question = "What is the oxygen consumption per hour for the normal rat (ml/hour)?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337827;


		
		

		
			p.question = "Now that you have the amount of oxygen used per hour by the normal rat, determine the oxygen consumption per kilogram of body weight per hour. (Note that you will need to convert the weight data from g to kg.)";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337828;


		
		

		
			p.question = "What is the oxygen consumption per kilogram of body weight per hour for the thyroidectomized rat?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337829;


		
		

		
			p.question = "What is the oxygen consumption per kilogram of body weight per hour for the hypophysectomized rat?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337830;


		
		

		
			p.question = "How did the metabolic rates of the three rats differ? Why did they differ?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337831;


		
		

		
			p.question = "What is the oxygen consumption per kilogram of body weight per hour for the normal rat with thyroxine injection?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337832;


		
		

		
			p.question = "What was the effect of thyroxine on the normal rat\'s metabolic rate? Why was this effect seen?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337833;


		
		

		
			p.question = "What is the oxygen consumption per kilogram of body weight per hour for the thyroidectomized rat with thyroxine injection?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337834;


		
		

		
			p.question = "What was the effect of thyroxine on the thyroidectomized rat\'s metabolic rate? Why was this effect seen?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337835;


		
		

		
			p.question = "What is the oxygen consumption per kilogram of body weight per hour for the hypophysectomized rat with thyroxine injection?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337836;


		
		

		
			p.question = "What was the effect of thyroxine on the hypophysectomized rat\'s metabolic rate? Why was this effect seen?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337837;


		
		

		
			p.question = "What is the oxygen consumption per kilogram of body weight per hour for the normal rat with TSH injection?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337838;


		
		

		
			p.question = "What was the effect of TSH on the normal rat\'s metabolic rate? Why was this effect seen?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337839;


		
		

		
			p.question = "What is the oxygen consumption per kilogram of body weight per hour for the thyroidectomized rat with TSH injection?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337840;


		
		

		
			p.question = "What was the effect of TSH on the thyroidectomized rat\'s metabolic rate? Why was this effect seen?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337841;


		
		

		
			p.question = "What is the oxygen consumption per kilogram of body weight per hour for the hypophysectomized rat with TSH injection?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337842;


		
		

		
			p.question = "What was the effect of TSH on the hypophysectomized rat\'s metabolic rate? Why was this effect seen?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

