

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "Investigation Quiz > What Affects Urine Production?";
	ak.quiz_loc_with_commas = "Investigation Quiz, What Affects Urine Production?";
	ak.quiz_title = "What Affects Urine Production?";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 10;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 10;
	ak.non_essay_total = 0;
	ak.scored_item_total = 0;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337815;


		
		

		
			p.question = "What happened to the urine concentration as the gradient concentration was increased?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337816;


		
		

		
			p.question = "What factor limits the maximum possible urine concentration?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337817;


		
		

		
			p.question = "The solute concentration of the blood is about 300 mOsm, and the highest interstitial solute concentration in a human kidney is about 1200 mOsm. This means that the maximum urine solute concentration is about four times that of the blood. What would be the maximum possible urine concentration if the maximum interstitial solute concentration were 3000 mOsm instead of 1200 mOsm? Explain.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337818;


		
		

		
			p.question = "In your experiment with aldosterone, how does the volume of urine differ from the previously measured baseline volume?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337819;


		
		

		
			p.question = "Explain the difference in the total amount of potassium in the urine between this run and the baseline run.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337820;


		
		

		
			p.question = "In your experiment with ADH, how does the volume of urine differ from the baseline measurement?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337821;


		
		

		
			p.question = "Is there a difference in the total amount of potassium in this run and the total amount of potassium in the baseline run? Explain. (Hint: the urine volume with ADH present is about one-tenth the urine volume when it is not present.)";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337822;


		
		

		
			p.question = "Are the effects of aldosterone and ADH similar or antagonistic?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337823;


		
		

		
			p.question = "Consider this situation: we want to reabsorb sodium ions but do not want to increase the volume of the blood by reabsorbing water from the filtrate. Assuming that aldosterone and ADH are both present, how would you adjust the hormones to accomplish the task?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337824;


		
		

		
			p.question = "If the interstitial gradient ranged from 300 mOsm to 3000 mOsm and ADH was not present, what would be the maximum possible urine concentration?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

