

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "56: Conservation Biology and Restoration Ecology > Activities Quiz";
	ak.quiz_loc_with_commas = "56: Conservation Biology and Restoration Ecology, Activities Quiz";
	ak.quiz_title = "Activities Quiz";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 15;
	ak.non_essay_total = 15;
	ak.scored_item_total = 15;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337154;


		
		

		
			
			p.question = "What percent of the plant species found on Madagascar are unique to that island? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?55&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Madagascar and the Biodiversity Crisis</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "10",
				false,
				"Higher.");
			
				p.addAnswer(2, "20",
				false,
				"Higher.");
			
				p.addAnswer(3, "40",
				false,
				"Higher.");
			
				p.addAnswer(4, "80",
				true,
				"This despite Madagascar\'s having only 2% of the land area of Africa.");
			
				p.addAnswer(5, "90",
				false,
				"Lower.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337155;


		
		

		
			
			p.question = "The human population of Madagascar doubles about every _____ years. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?55&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Madagascar and the Biodiversity Crisis</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "10",
				false,
				"Higher.");
			
				p.addAnswer(2, "25",
				true,
				"On Madagascar, the average woman has more than five children.");
			
				p.addAnswer(3, "40",
				false,
				"Lower.");
			
				p.addAnswer(4, "60",
				false,
				"Lower.");
			
				p.addAnswer(5, "80",
				false,
				"Lower.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337156;


		
		

		
			
			p.question = "What is a lemur? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?55&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Madagascar and the Biodiversity Crisis</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a primate only found on Madagascar",
				true,
				"Lemurs were once widespread in Europe, Africa, and America; however, now they are found only on Madagascar.");
			
				p.addAnswer(2, "a poisonous snake found only on Madagascar",
				false,
				"Lemurs are not snakes.");
			
				p.addAnswer(3, "a type of orchid found only on Madagascar",
				false,
				"Lemurs are not plants.");
			
				p.addAnswer(4, "a type of tree found only on Madagascar",
				false,
				"Lemurs are not plants.");
			
				p.addAnswer(5, "a type of cuckoo found only on Madagascar",
				false,
				"Lemurs are not birds.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337157;


		
		

		
			
			p.question = "Much of the original forest cover on Madagascar has been destroyed primarily as a result of _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?55&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Madagascar and the Biodiversity Crisis</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the building of malls",
				false,
				"This is not the primary cause of the destruction of the Madagascaran forest.");
			
				p.addAnswer(2, "pollution from automobile emissions",
				false,
				"This is not the primary cause of the destruction of the Madagascaran forest.");
			
				p.addAnswer(3, "the building of tract housing",
				false,
				"This is not the primary cause of the destruction of the Madagascaran forest.");
			
				p.addAnswer(4, "burning for agricultural purposes",
				true,
				"The traditional farming method was to burn a region of the forest and then plant crops. Crops would be grown in this region for several seasons, after which it would be abandoned to revert to forest. As the human population increased, the need for agricultural land increased, land was burned more frequently, soil become infertile and easily eroded, and neither crops nor forest could be supported.");
			
				p.addAnswer(5, "industrial activity",
				false,
				"This is not the primary cause of the destruction of the Madagascaran forest.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337158;


		
		

		
			
			p.question = "What is the cause of the red color of the waters about Madagascar? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?55&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Madagascar and the Biodiversity Crisis</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "dinoflagellates",
				false,
				"Dinoflagellates are not the usual cause of the red color of the waters about Madagascar.");
			
				p.addAnswer(2, "a persistent red tide",
				false,
				"Dinoflagellates, the usual cause of red tides, are not the usual cause of the red color of the waters about Madagascar.");
			
				p.addAnswer(3, "the high concentration of iron found in these waters",
				false,
				"Rust is not the reason the water is red.");
			
				p.addAnswer(4, "soil that has washed into the ocean",
				true,
				"Agricultural practices have produced easily eroded soil that is washed into the ocean.");
			
				p.addAnswer(5, "red algae",
				false,
				"Red algae are not responsible for this red color.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337159;


		
		

		
			
			p.question = "From 1930 to 1939 fire ants spread inland about 60 miles from their point of introduction in Mobile, Alabama. What was the cause of their spread over this distance? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?55&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Introduced Species: Fire Ants</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a natural spread",
				true,
				"This rate of spread corresponds to a natural spread.");
			
				p.addAnswer(2, "airplanes",
				false,
				"The spread was slower than transport by airplane would have been, and all the colonies were in the Mobile, Alabama, area.");
			
				p.addAnswer(3, "being transported along with soil",
				false,
				"The spread was slower than transport by truck would have been.");
			
				p.addAnswer(4, "being transported along with plants",
				false,
				"The spread was slower than transport by truck would have been.");
			
				p.addAnswer(5, "dispersion via ship ballast",
				false,
				"Most of the spread was inland.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337160;


		
		

		
			
			p.question = "From 1940 to 1970 fire ants spread through many southern states, sometimes at a rate of 100 miles in a year. What was the cause of their spread over this distance? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?55&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Introduced Species: Fire Ants</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a natural spread",
				false,
				"Some natural spread occurred, but the overall rate of spread was too fast to be natural.");
			
				p.addAnswer(2, "dispersion via ship ballast",
				false,
				"Most of the spread was inland.");
			
				p.addAnswer(3, "airplanes",
				false,
				"Probably not, since most of the new colonies were not concentrated near airports.");
			
				p.addAnswer(4, "being transported along with plants",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(5, "being transported along with plants and soil",
				true,
				"This is the most likely explanation of the 1940&#8211;1970 spread.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337161;


		
		

		
			
			p.question = "In 1958 federal law restricted the movement of soil and plants from areas where fire ants were established. Why was this law unsuccessful in stopping the spread of fire ant colonies? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?55&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Introduced Species: Fire Ants</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "People were unaware of the federal law and, when they moved, transported plants bearing fire ant colonies.",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(2, "A single mated queen can be transported without being noticed.",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(3, "Many states originally thought to be free of fire ant colonies already had them.",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(4, "People were unaware of the federal law and, when they moved, transported plants bearing fire ant colonies; moreover, a single mated queen can be transported without being noticed.",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(5, "People were unaware of the federal law and, when they moved, transported plants bearing fire ant colonies; a single mated queen can be transported without being noticed; and many states thought to be free of fire ant colonies already had them.",
				true,
				"All of these are reasons that the federal law may have been unsuccessful at stopping the spread of fire ant colonies.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337162;


		
		

		
			
			p.question = "Techniques used, or are being considered for use, in controlling the spread of fire ants include _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?55&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Introduced Species: Fire Ants</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "setting baits that kill the queen when they are carried back to the nest",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(2, "applying chemical powders that kill the colony",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(3, "introducing a protist to infect the fire ant queen and her eggs",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(4, "introducing a fly that lays eggs in fire ants so that the eggs will hatch into larvae that eat their way into the ants\' heads, which will then fall off",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(5, "setting baits that kill the queen when they are carried back to the nest, applying chemical powders that kill the colony, introducing a protist to infect the fire ant queen and her eggs, and introducing a fly that lays eggs in fire ants so that the eggs will hatch into larvae that eat their way into the ants\' heads, which will then fall off",
				true,
				"The first two of these are being done and the second two are being investigated as possible techniques for controlling fire ants.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337163;


		
		

		
			
			p.question = "As of the time of the writing of Activity: Introduced Species: Fire Ants, fire ants have caused about _____ deaths in the United States. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?55&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Introduced Species: Fire Ants</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "5",
				false,
				"More.");
			
				p.addAnswer(2, "20",
				true,
				"As of the time of the writing of Activity: Introduced Species: Fire Ants, fire ants have caused about 20 deaths in the United States.");
			
				p.addAnswer(3, "50",
				false,
				"Fewer.");
			
				p.addAnswer(4, "100",
				false,
				"Fewer.");
			
				p.addAnswer(5, "1,000",
				false,
				"Fewer.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337164;


		
		

		
			
			p.question = "One of the most severe consequences of habitat degradation is the _____ of a population. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?55&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Conservation Biology Review</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "magnification",
				false,
				"Populations decrease when their habitat is degraded.");
			
				p.addAnswer(2, "eutrophication",
				false,
				"Eutrophication occurs when excessive nutrients are added to a lake.");
			
				p.addAnswer(3, "fragmentation",
				true,
				"Severe habitat degradation fragments a larger population into more vulnerable smaller populations.");
			
				p.addAnswer(4, "fossilization",
				false,
				"Well, eventually, those individuals that die may become fossils, but so may you and I.");
			
				p.addAnswer(5, "precipitation",
				false,
				"\"Precipitation\" refers to the formation of a condensate.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337165;


		
		

		
			
			p.question = "A sink habitat is where a subpopulation\'s death rate is _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?55&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Conservation Biology Review</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "equal to its reproductive rate",
				false,
				"This is not the definition of a sink habitat.");
			
				p.addAnswer(2, "greater than its reproductive rate",
				true,
				"In sink habitats, populations experience a net loss of individuals.");
			
				p.addAnswer(3, "less than its reproductive rate",
				false,
				"In source habitats the death rate is less than the reproductive rate.");
			
				p.addAnswer(4, "at its lowest",
				false,
				"Sink habitats have higher death rates than other habitats.");
			
				p.addAnswer(5, "either equal to its reproductive rate or less than its reproductive rate",
				false,
				"Neither of these is accurate with regard to a sink habitat.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337166;


		
		

		
			
			p.question = "Fertilizer runoff can result in _____ a lake. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?55&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Conservation Biology Review</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the eutrophication of",
				true,
				"The addition of fertilizer to a lake can cause an algal bloom. When the algae die, decomposition depletes the oxygen in the lake and this lack of oxygen kills the animal life.");
			
				p.addAnswer(2, "the ozonation of",
				false,
				"The addition of fertilizer does not increase the ozone levels found in a lake.");
			
				p.addAnswer(3, "the creation of source habitats for fish within",
				false,
				"In such a lake it is unlikely that, over the long term, any fish population will have a reproductive rate that exceeds its death rate.");
			
				p.addAnswer(4, "the irrigation of",
				false,
				"Irrigation occurs when humans supply water to an area that does not have sufficient water to satisfy their purposes.");
			
				p.addAnswer(5, "an increase in the biodiversity of",
				false,
				"The ultimate result of fertilizer runoff would be a decrease in the biodiversity of a lake.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337167;


		
		

		
			
			p.question = "Most biodiversity hot spots are in the _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?55&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Conservation Biology Review</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Arctic",
				false,
				"The Arctic, while not untouched by human activity, is not the location of most biodiversity hot spots.");
			
				p.addAnswer(2, "coniferous forests",
				false,
				"While endangered by human activities, coniferous forests are not the location of most biodiversity hot spots.");
			
				p.addAnswer(3, "deserts",
				false,
				"While endangered by human activities, deserts are not the location of most biodiversity hot spots.");
			
				p.addAnswer(4, "grasslands",
				false,
				"While much grassland has been destroyed by human activity, grasslands are not the location of most biodiversity hot spots.");
			
				p.addAnswer(5, "tropics",
				true,
				"The tropics are home to many endangered endemic species.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337168;


		
		

		
			
			p.question = "_____ is the increase in pesticide concentration as the pesticides pass up a food chain. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?55&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Conservation Biology Review</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Eutrophication",
				false,
				"\"Eutrophication\" refers to the consequences of adding fertilizer to a lake.");
			
				p.addAnswer(2, "Biodiversity",
				false,
				"\"Biodiversity\" refers to the number of species found in a particular area.");
			
				p.addAnswer(3, "The greenhouse effect",
				false,
				"\"The greenhouse effect\" refers to an increase in global temperatures attributable to the release of gases such as carbon dioxide and methane into the atmosphere.");
			
				p.addAnswer(4, "Precipitation",
				false,
				"\"Precipitation\" refers to the formation of a condensate.");
			
				p.addAnswer(5, "Biological magnification",
				true,
				"\"Biological magnification\" refers to the accumulation of toxins as they are passed up the food chain.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

