

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "Investigation Quiz > How Can the Frequency of Crossing Over Be Estimated?";
	ak.quiz_loc_with_commas = "Investigation Quiz, How Can the Frequency of Crossing Over Be Estimated?";
	ak.quiz_title = "How Can the Frequency of Crossing Over Be Estimated?";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 13;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 13;
	ak.non_essay_total = 0;
	ak.scored_item_total = 0;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337611;


		
		

		
			p.question = "What is the percent of crossovers? (number of asci with crossovers divided by total number of asci multiplied by 100)";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337612;


		
		

		
			p.question = "For the sample shown here, what is the map distance between the gene for spore color and the centromere? (% of crossovers divided by 2)";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337613;


		
		

		
			p.question = "In the second set of data, how many of these asci contain a spore arrangement that resulted from crossing over?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337614;


		
		

		
			p.question = "From this second small sample, calculate the map distance between the gene and centromere.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337615;


		
		

		
			p.question = "In what cellular processes is mitosis involved? In what cellular process is meiosis involved?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337616;


		
		

		
			p.question = "In what type of cells does mitosis occur? In what type of cells does meiosis occur?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337617;


		
		

		
			p.question = "How many times does DNA replicate in mitosis? How many times does DNA replicate in meiosis?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337618;


		
		

		
			p.question = "How many cellular divisions occur in mitosis? How many cellular divisions occur in meiosis?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337619;


		
		

		
			p.question = "How many daughter cells are formed by mitosis? How many daughter cells are formed by meiosis?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337620;


		
		

		
			p.question = "What is the chromosome number in daughter cells formed by mitosis from diploid parent cells? What is the chromosome number in daughter cells formed by meiosis from diploid parent cells?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337621;


		
		

		
			p.question = "In mitosis, are daughter cells identical to or different from parent cells? In meiosis, are daughter cells identical to or different from parent cells?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337622;


		
		

		
			p.question = "In mitosis, when do synapsis and crossing over occur? In meiosis, when do synapsis and crossing over occur?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337623;


		
		

		
			p.question = "The cell cycle in a certain cell type has a duration of 16 hours. The nuclei of 660 cells showed 13 cells in anaphase. What is the approximate duration of anaphase in these cells?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

