

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "49: Nervous Systems > Practice Test";
	ak.quiz_loc_with_commas = "49: Nervous Systems, Practice Test";
	ak.quiz_title = "Practice Test";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 32;
	ak.non_essay_total = 32;
	ak.scored_item_total = 32;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336820;


		
		

		
			
			p.question = "Which would be present in an animal with a nerve net? (<script type=\"text/javascript\">ebook(\'4901\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "bilateral symmetry",
				false,
				"No. Animals with a nerve net are most often radially symmetrical.");
			
				p.addAnswer(2, "neurons",
				true,
				"Correct. The nerve net is a web-like system of neurons.");
			
				p.addAnswer(3, "fused ganglia",
				false,
				"No. A nerve net does not have this complexity of development.");
			
				p.addAnswer(4, "cephalization",
				false,
				"No. Animals with cephalization, or concentration of the nervous system at the anterior end of the body, would not have a simple net of nerves.");
			
				p.addAnswer(5, "centralization",
				false,
				"No. Centralization indicates the presence of a central nervous system, which involves more than a simple nerve net.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336821;


		
		

		
			
			p.question = "What is the difference between a neuron and a nerve? (<script type=\"text/javascript\">ebook(\'4901\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "One has sensory functions, the other motor.",
				false,
				"No. Both neurons and nerves can be either sensory or motor, although most nerves are mixed, indicating that they consist of both motor and sensory components.");
			
				p.addAnswer(2, "Nerves are found only in the central nervous system.",
				false,
				"No. Actually, nerves are found only in the peripheral nervous system.");
			
				p.addAnswer(3, "They consist of different numbers of cells.",
				true,
				"Correct. A neuron is a single cell. A nerve consists of many neurons bundled together by connective tissue.");
			
				p.addAnswer(4, "Neurons are made of white matter, nerves of gray matter.",
				false,
				"No. The white matter found within the nervous system is myelin.");
			
				p.addAnswer(5, "Neurons are found only in vertebrates.",
				false,
				"No. Recall the early work done with the nervous system of the squid.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336822;


		
		

		
			
			p.question = "A cluster of nerve cell bodies outside the central nervous system is referred to as a(n) _____. (<script type=\"text/javascript\">ebook(\'4901\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "cranial nerve",
				false,
				"No. A cranial nerve consists of bundles of axons.");
			
				p.addAnswer(2, "nucleus",
				false,
				"No. With regard to the structure of the nervous system, a nucleus is an aggregation of nerve cell bodies within the central nervous system.");
			
				p.addAnswer(3, "association area",
				false,
				"No. Association areas consist of many interconnected neurons.");
			
				p.addAnswer(4, "ganglion",
				true,
				"Correct. A ganglion is a cluster of nerve cell bodies, often of similar function, in the peripheral nervous system.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336823;


		
		

		
			
			p.question = "A neuron that transmits an impulse to the central nervous system after the neuron is stimulated by the environment is called a(n) _____. (<script type=\"text/javascript\">ebook(\'4901\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "sensory neuron",
				true,
				"Correct. Sensory neurons communicate information between sensory receptors and the central nervous system about the external and internal environments.");
			
				p.addAnswer(2, "motor neuron",
				false,
				"No. Motor neurons transmit impulses to effectors.");
			
				p.addAnswer(3, "interneuron",
				false,
				"No. Interneurons are found within the central nervous system; they do not relay information from the external environment to the central nervous system.");
			
				p.addAnswer(4, "autonomic neuron",
				false,
				"No. The autonomic nervous system innervates effectors.");
			
				p.addAnswer(5, "Schwann cell",
				false,
				"No. Schwann cells form the myelin sheath of peripheral nerves.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336824;


		
		

		
			
			p.question = "Which of the following is specifically a part or a function of the central nervous system? (<script type=\"text/javascript\">ebook(\'4901\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "sensory receptors",
				false,
				"No. These parts of the peripheral nervous system detect changes in an animal\'s external environment.");
			
				p.addAnswer(2, "sensory input",
				false,
				"No. These parts of the peripheral nervous system relay messages from sensory receptors to the central nervous system.");
			
				p.addAnswer(3, "integration",
				true,
				"Correct. Integration is the interpretation of sensory signals and the formulation of responses. It is a principal function of the central nervous system.");
			
				p.addAnswer(4, "motor output",
				false,
				"No. Motor output may originate in the central nervous system, but it is transmitted through the peripheral nervous system.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the choices above is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336825;


		
		

		
			
			p.question = "Which of the following describes a reflex response? (<script type=\"text/javascript\">ebook(\'4901\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "It requires a sensory neuron, an interneuron, and motor nerves.",
				true,
				"Correct.");
			
				p.addAnswer(2, "The response only involves interneurons.",
				false,
				"No. The response involves more than this.");
			
				p.addAnswer(3, "Pain receptors in the skin send a message to the brain to initiate motor movement, away from a painful stimulus.",
				false,
				"No. Reflexes bypass the brain.");
			
				p.addAnswer(4, "It is a conscious response to painful stimuli.",
				false,
				"No. Reflexes bypass the brain and so are not conscious.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the choices above is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336826;


		
		

		
			
			p.question = "Schwann cells make up the _____. (<script type=\"text/javascript\">ebook(\'4901\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "neurons",
				false,
				"No. Schwann cells cover the axons of certain neurons.");
			
				p.addAnswer(2, "nodes of Ranvier",
				false,
				"No. Nodes of Ranvier are gaps in the covering of a myelin sheath.");
			
				p.addAnswer(3, "myelin sheath",
				true,
				"Correct. In the peripheral nervous system, supporting cells called Schwann cells wrap many axons with an insulating myelin sheath.");
			
				p.addAnswer(4, "radial glia",
				false,
				"No. Radial glia direct neurons during development.");
			
				p.addAnswer(5, "neurotransmitter secretory vesicles",
				false,
				"No. Vesicles are membrane-bound structures found within axon terminals.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336827;


		
		

		
			
			p.question = "The glia present throughout the vertebrate brain or spinal cord include _____. (<script type=\"text/javascript\">ebook(\'4901\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Schwann cells",
				false,
				"No. This is true, but there is a better response.");
			
				p.addAnswer(2, "astrocytes",
				false,
				"No. This is true, but there is a better response.");
			
				p.addAnswer(3, "oligodendrocytes",
				false,
				"No. This is true, but there is a better response.");
			
				p.addAnswer(4, "microglia",
				false,
				"No. This is true, but there is a better response.");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336828;


		
		

		
			
			p.question = "Which of the following includes all the others? (<script type=\"text/javascript\">ebook(\'4901\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "autonomic nervous system (ANS)",
				false,
				"No. The ANS is a component of the peripheral nervous system (PNS).");
			
				p.addAnswer(2, "motor system",
				false,
				"No. The term \"motor system\" refers to the somatic and visceral motor neurons of the peripheral nervous system (PNS).");
			
				p.addAnswer(3, "sympathetic division",
				false,
				"No. The sympathetic division is part of the autonomic nervous system (ANS), which is a component of the peripheral nervous system (PNS).");
			
				p.addAnswer(4, "peripheral nervous system (PNS)",
				true,
				"Correct. The PNS, which is broken down into sensory and motor components, includes all nervous tissue outside the central nervous system (CNS).");
			
				p.addAnswer(5, "parasympathetic division",
				false,
				"No. The sympathetic division is part of the autonomic nervous system (ANS), which is a component of the peripheral nervous system (PNS).");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336829;


		
		

		
			
			p.question = "Which one of the following structures is (are) found only in the peripheral nervous system? (<script type=\"text/javascript\">ebook(\'4901\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "medulla oblongata",
				false,
				"No. The medulla oblongata is a component of the central nervous system.");
			
				p.addAnswer(2, "gray matter",
				false,
				"No. Gray matter is found in the central nervous system.");
			
				p.addAnswer(3, "spinal cord",
				false,
				"No. The spinal cord is a component of the central nervous system.");
			
				p.addAnswer(4, "taste receptors",
				true,
				"Correct. The central nervous system consists of the brain and spinal cord; the peripheral nervous system consists of paired cranial and spinal nerves and associated ganglia.");
			
				p.addAnswer(5, "cerebral cortex",
				false,
				"No. The cerebral cortex is a component of the central nervous system.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336830;


		
		

		
			
			p.question = "The gray matter of the cerebral cortex, where most higher-level thinking occurs, is composed mostly of _____. (<script type=\"text/javascript\">ebook(\'4901\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "neuron cell bodies, dendrites, and unmyelinated axons",
				true,
				"Correct. The gray matter is involved in relaying incoming sensory information and outgoing motor commands. It processes this information and develops the appropriate response, an activity sometimes called thinking.");
			
				p.addAnswer(2, "myelinated axons of neurons",
				false,
				"No. Axons, whether myelinated or not, are involved only with the conduction of the impulse.");
			
				p.addAnswer(3, "sensory neuron cell bodies",
				false,
				"No. Sensory neuron cell bodies are typically found in the posterior root ganglia associated with the spinal cord.");
			
				p.addAnswer(4, "Schwann cells",
				false,
				"No. Schwann cells provide the myelination for nerves of the peripheral nervous system.");
			
				p.addAnswer(5, "motor neuron cell bodies",
				false,
				"No. Motor neuron cell bodies are found primarily in the anterior gray horns of the spinal cord.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336831;


		
		

		
			
			p.question = "Which of the following structures constitutes the mammalian forebrain? (<script type=\"text/javascript\">ebook(\'4902\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "cerebrum only",
				false,
				"No. However, the cerebrum is a component of the forebrain.");
			
				p.addAnswer(2, "cerebellum and medulla oblongata",
				false,
				"No. Both the cerebellum and the medulla oblongata are components of the hindbrain.");
			
				p.addAnswer(3, "pons",
				false,
				"No. The pons is a component of the hindbrain.");
			
				p.addAnswer(4, "cerebrum and cerebellum",
				false,
				"No. However, this choice is partially correct.");
			
				p.addAnswer(5, "thalamus, epithalamus, hypothalamus, and cerebrum",
				true,
				"Correct. The embryonic forebrain gives rise to the telencephalon and the diencephalon. The thalamus, epithalamus, and hypothalamus develop from the diencephalon; the cerebrum develops from the telencephalon.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336832;


		
		

		
			
			p.question = "A physician friend of yours tells you about a patient with a head injury who suddenly stopped breathing during the examination. What portion of the brain was probably injured? (<script type=\"text/javascript\">ebook(\'4902\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "medulla oblongata",
				true,
				"Correct. The medulla oblongata contains centers that control several visceral functions, such as breathing, heart and blood vessel activity, swallowing, vomiting, and digestion.");
			
				p.addAnswer(2, "cerebrum",
				false,
				"No. The cerebrum contains the higher brain centers and is primarily given over to integrative functions.");
			
				p.addAnswer(3, "cerebellum",
				false,
				"No. The cerebellum receives sensory information about the joints and the length of the muscles and uses this information to provide the automatic coordination of movements and balance.");
			
				p.addAnswer(4, "hypothalamus",
				false,
				"No. The hypothalamus plays a major role in homeostatic regulation.");
			
				p.addAnswer(5, "pituitary",
				false,
				"No. The pituitary gland is involved in endocrine function.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336833;


		
		

		
			
			p.question = "As you start to pick up your biology book, you suddenly realize that it is much heavier than you expected. Which of the following brain regions is responsible for the rapid adjustment of muscle force that allows you to pick up the book smoothly? (<script type=\"text/javascript\">ebook(\'4902\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "medulla oblongata",
				false,
				"No. The medulla oblongata is involved in the regulation of various autonomic homeostatic functions.");
			
				p.addAnswer(2, "cerebrum",
				false,
				"No. The cerebrum contains the higher brain centers and mainly participates in integrative functions.");
			
				p.addAnswer(3, "cerebellum",
				true,
				"Correct. The cerebellum receives sensory information about the joints and the length of the muscles and uses this information to provide the automatic coordination of movements and balance.");
			
				p.addAnswer(4, "hypothalamus",
				false,
				"No. The hypothalamus plays a major role in homeostatic regulation.");
			
				p.addAnswer(5, "pituitary",
				false,
				"No. The pituitary gland is involved in endocrine function.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336834;


		
		

		
			
			p.question = "Monitoring blood CO<sub>2</sub> levels and triggering breathing at the appropriate times are functions of the _____. (<script type=\"text/javascript\">ebook(\'4902\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "cerebrum",
				false,
				"No. The cerebrum contains the higher brain centers and mainly participates in integrative functions.");
			
				p.addAnswer(2, "hypothalamus",
				false,
				"No. This is something the hypothalamus is not directly involved in regulating.");
			
				p.addAnswer(3, "medulla oblongata",
				true,
				"Correct. The medulla oblongata contains centers that control several visceral functions, such as breathing, heart and blood vessel activity, swallowing, vomiting, and digestion.");
			
				p.addAnswer(4, "thalamus",
				false,
				"No. The thalamus is a primary relay center for sensory information.");
			
				p.addAnswer(5, "cerebellum",
				false,
				"No. The cerebellum receives sensory information about the joints and the length of the muscles and uses this information to provide the automatic coordination of movements and balance.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336835;


		
		

		
			
			p.question = "The main input center for sensory information going to the cerebrum is the _____. (<script type=\"text/javascript\">ebook(\'4902\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "thalamus",
				true,
				"Correct. The thalamus is a relay center for motor and sensory messages, except those from olfactory receptors, in all vertebrate classes.");
			
				p.addAnswer(2, "cerebrum",
				false,
				"No. The cerebrum contains the higher brain centers and mainly participates in integrative functions.");
			
				p.addAnswer(3, "cerebellum",
				false,
				"No. The cerebellum receives sensory information about the joints and the length of the muscles and uses this information to provide the automatic coordination of movements and balance.");
			
				p.addAnswer(4, "pons",
				false,
				"No. The pons contains centers involved in functions such as the regulation of breathing and sleep.");
			
				p.addAnswer(5, "medulla oblongata",
				false,
				"No. The medulla oblongata contains centers that control several visceral functions, such as breathing, heart and blood vessel activity, swallowing, vomiting, and digestion.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336836;


		
		

		
			
			p.question = "A man is admitted to the hospital suffering from an abnormally low body temperature, a loss of appetite, and extreme thirst. A brain scan shows a tumor located in the _____. (<script type=\"text/javascript\">ebook(\'4902\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "hypothalamus",
				true,
				"Correct. Each of the problems experienced by the patient is associated with specific functions of the hypothalamus and its role in maintaining homeostasis.");
			
				p.addAnswer(2, "cerebellum",
				false,
				"No. The cerebellum refines motor activity.");
			
				p.addAnswer(3, "pons",
				false,
				"No. However, the pons is critical to life because of its role in basic life-support activities such as heart and respiratory rate.");
			
				p.addAnswer(4, "right cerebral hemisphere",
				false,
				"No. The right cerebral hemisphere is associated with motor activity and sensory perception on the left side of the body.");
			
				p.addAnswer(5, "corpus callosum",
				false,
				"No. The corpus callosum is an interhemispherical pathway that permits the left and right hemispheres to share information.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336837;


		
		

		
			
			p.question = "In mammals, the part of the brain that increases in size and complexity most significantly is derived from the embryonic _____. (<script type=\"text/javascript\">ebook(\'4902\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "forebrain",
				true,
				"Correct. The cerebral cortex develops from the telencephalon, an outgrowth of the forebrain.");
			
				p.addAnswer(2, "forebrain and midbrain",
				false,
				"No. However, this choice is partially correct.");
			
				p.addAnswer(3, "midbrain",
				false,
				"No. The midbrain, a part of the brainstem, is not the brain region that undergoes the most significant embryonic increase in size and complexity in mammals.");
			
				p.addAnswer(4, "midbrain and hindbrain",
				false,
				"No. Neither of these regions undergoes the most significant embryonic increase in size and complexity.");
			
				p.addAnswer(5, "hindbrain",
				false,
				"No. The hindbrain, which includes structures such as the medulla oblongata and pons, is not the brain region that undergoes the most significant embryonic increase in size and complexity.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336838;


		
		

		
			
			p.question = "The corpus callosum connects the _____. (<script type=\"text/javascript\">ebook(\'4902\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "cerebellum and spinal cord",
				false,
				"No. The cerebellum lacks direct connections to the spinal cord.");
			
				p.addAnswer(2, "right and left cerebral hemispheres",
				true,
				"Correct. A thick band of fibers known as the corpus callosum connects the right and left cerebral hemispheres.");
			
				p.addAnswer(3, "pituitary and the hypothalamus",
				false,
				"No. A stalk (the infundibulum) connects the hypothalamus and pituitary gland.");
			
				p.addAnswer(4, "gray and white matter of the spinal cord",
				false,
				"No. The corpus callosum is not located within the spinal cord.");
			
				p.addAnswer(5, "optic chiasm and the optic lobe",
				false,
				"No. The optic tract connects the optic chiasm and the optic lobe.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336839;


		
		

		
			
			p.question = "An important concept in biology is that evolution is a process that remodels ancestral body plans. Developmental sequences in embryos often display evidence of evolutionary relationships. Using this evidence, which part of the brain was most prominent in early vertebrates? (<script type=\"text/javascript\">ebook(\'4902\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the hindbrain",
				true,
				"Correct. The hindbrain maintains homeostasis, necessary for all animals, and makes up a significant portion of the brain of a one-month-old embryo.");
			
				p.addAnswer(2, "the telencephalon",
				false,
				"No. This is the part that develops into the elaborate cerebral cortex in humans but is not elaborately developed in earlier vertebrates.");
			
				p.addAnswer(3, "the cerebral cortex",
				false,
				"No. This is a part highly developed in humans but not in earlier vertebrates.");
			
				p.addAnswer(4, "the pituitary gland",
				false,
				"No. The pituitary gland is attached to the brain, but it is not a part of it.");
			
				p.addAnswer(5, "the neocortex",
				false,
				"No. As the name indicates, the neocortex is a \"newer\" evolutionary development.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336840;


		
		

		
			
			p.question = "Which of the following parts of the nervous system would allow you to discover the qualities of a mouthful of black pepper? (<script type=\"text/javascript\">ebook(\'4903\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "somatic nervous system",
				false,
				"No. This division carries messages from the brain to skeletal muscles. It would give you the brain\'s reaction to the black pepper by advising you to spit it out.");
			
				p.addAnswer(2, "somatosensory cortex",
				true,
				"Correct. This division is responsible for monitoring both the external and internal environment. It would send information to the brain about the qualities of substances you taste and smell.");
			
				p.addAnswer(3, "motor division",
				false,
				"No. This division carries messages from the brain to all parts of the body. It would bring about voluntary and involuntary reactions to the taste of this robust spice.");
			
				p.addAnswer(4, "sympathetic division",
				false,
				"No. This division carries messages from the brain to involuntary parts of the body that react. It would not help you discover pepper\'s qualities, but it would promote a hearty sneeze.");
			
				p.addAnswer(5, "parasympathetic division",
				false,
				"No. The parasympathetic division\'s reaction to your mouthful of pepper would help your body to calm down after the crisis was over and you had washed your mouth out.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336841;


		
		

		
			
			p.question = "Damage to the occipital lobe would be most likely expressed as _____. (<script type=\"text/javascript\">ebook(\'4903\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a numbness in the extremities",
				false,
				"No. Sensory perception and visual association are located in the occipital lobe.");
			
				p.addAnswer(2, "visual impairment",
				true,
				"Correct. Visual perception and visual association are located in the occipital lobe.");
			
				p.addAnswer(3, "auditory impairment",
				false,
				"No. Hearing is located in the temporal lobe.");
			
				p.addAnswer(4, "spastic paralysis",
				false,
				"No. Spastic activity results when motor pathways from the spinal cord are intact and interneurons from the brain to the spinal cord are injured.");
			
				p.addAnswer(5, "the impairment of speech",
				false,
				"No. Speech centers are found in the frontal lobe.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336842;


		
		

		
			
			p.question = "The auditory (hearing) centers are located in the _____. (<script type=\"text/javascript\">ebook(\'4903\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "temporal lobes of the cerebral cortex",
				true,
				"Correct. Hearing centers are located in the temporal lobes of the cerebral cortex.");
			
				p.addAnswer(2, "occipital lobes of the cerebral cortex",
				false,
				"No. Vision centers are located in the occipital lobe.");
			
				p.addAnswer(3, "frontal lobe of the cerebral cortex",
				false,
				"No. The frontal lobe is concerned with functions such as voluntary movements in addition to personality, judgment, and planning.");
			
				p.addAnswer(4, "parietal lobes of the cerebral cortex",
				false,
				"No. The parietal lobes are primarily concerned with general sensory input (touch, for example).");
			
				p.addAnswer(5, "cerebellum",
				false,
				"No. The cerebellum plays a role in coordinating muscular function.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336843;


		
		

		
			
			p.question = "Which of the following is <b>not</b> regulated by the association areas in the cerebral cortex? (<script type=\"text/javascript\">ebook(\'4903\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "balance",
				true,
				"Correct. With the exception of balance, which is controlled by the cerebellum, all the other listed functions occur in the cerebral cortex.");
			
				p.addAnswer(2, "thought and language",
				false,
				"No. This is a function of the cerebral cortex.");
			
				p.addAnswer(3, "learning and memory",
				false,
				"No. This is a function of the cerebral cortex.");
			
				p.addAnswer(4, "judgment",
				false,
				"No. This is a function of the cerebral cortex.");
			
				p.addAnswer(5, "personality",
				false,
				"No. This is a function of the cerebral cortex.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336844;


		
		

		
			
			p.question = "After a stroke, Bill can feel his left leg but is unable to move it. His neurologists suspect damage to the _____. (<script type=\"text/javascript\">ebook(\'4903\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "right frontal lobe",
				true,
				"Correct. Voluntary motor control originates in the frontal lobe. Because the organization of the cerebral cortex is contralateral, the right cortex controls the left side of the body.");
			
				p.addAnswer(2, "right parietal lobe",
				false,
				"No. The major activity of the parietal lobe is sensory perception.");
			
				p.addAnswer(3, "left frontal lobe",
				false,
				"No. Although the frontal lobe does control voluntary motor activity, the cortex is organized contralaterally.");
			
				p.addAnswer(4, "left parietal lobe",
				false,
				"No. The major activity of the parietal lobe is sensory perception.");
			
				p.addAnswer(5, "cerebellum",
				false,
				"No. The cerebellum modifies and edits motor activity, but it does not originate voluntary movement.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336845;


		
		

		
			
			p.question = "The limbic system is involved in _____. (<script type=\"text/javascript\">ebook(\'4903\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "emotion and memory",
				true,
				"Correct. Mostly associated with emotion, the limbic system also includes two regions, the amygdala and hippocampus, which function in memory.");
			
				p.addAnswer(2, "speech and hearing",
				false,
				"No. These activities are localized within the lobes of the cerebrum.");
			
				p.addAnswer(3, "vision",
				false,
				"No. Visual perception and association occur within the occipital lobe of the cerebrum.");
			
				p.addAnswer(4, "sleep and wakefulness",
				false,
				"No. These activities are regulated by a diffuse functional system termed the \"reticular formation.\"");
			
				p.addAnswer(5, "control of heartbeat and respiration",
				false,
				"No. These functions are primarily regulated from various areas within the brainstem and are influenced by higher centers.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336846;


		
		

		
			
			p.question = "Which part of the brain\'s limbic system ties an event to a scent, making it possible for a long-term memory to be triggered by a smell? (<script type=\"text/javascript\">ebook(\'4903\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the occipital lobe",
				false,
				"No. The occipital lobe processes the things you see.");
			
				p.addAnswer(2, "the reticular formation",
				false,
				"No. The reticular formation determines which sensory inputs deserve more attention.");
			
				p.addAnswer(3, "the amygdala",
				true,
				"Correct. The amygdala ties emotion, the scenery, and the event to a scent, whether it is sweet or noxious.");
			
				p.addAnswer(4, "the olfactory lobe",
				false,
				"No. It merely acts as intake for the scent, which is encoded as a neural transmission and sent along to higher parts of the brain for processing.");
			
				p.addAnswer(5, "the hippocampus",
				false,
				"No. The hippocampus is closely associated with the part in question, but it is more involved in determining the appropriate response to the event.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336847;


		
		

		
			
			p.question = "The developing embryonic brain is shaped by __________. (<script type=\"text/javascript\">ebook(\'4904\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the selective elimination in neurons and synapses",
				true,
				"Correct.");
			
				p.addAnswer(2, "differences in the rates of blood vessel growth",
				false,
				"No. This is not the main way that the brain is shaped during embryogenesis.");
			
				p.addAnswer(3, "pressures exerted by the growing skull",
				false,
				"No. This is not a significant way that the brain is shaped during embryogenesis.");
			
				p.addAnswer(4, "variations in the levels of nutrients received across the placenta",
				false,
				"No. This is not the main way that the brain is shaped during embryogenesis.");
			
				p.addAnswer(5, "an oxygen gradient that promotes growth where oxygen is most concentrated",
				false,
				"No. This is not the main way that the brain is shaped during embryogenesis.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336848;


		
		

		
			
			p.question = "Which of the following contributes to learning and memory storage in the brain? (<script type=\"text/javascript\">ebook(\'4904\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "repeated, weak stimulation of receiving neurons",
				false,
				"No. This results in long-term neural depression, a decreased response to an action potential.");
			
				p.addAnswer(2, "a decline in long-term potentiation",
				false,
				"No. An increase in long-term potentiation would enhance learning and memory storage.");
			
				p.addAnswer(3, "excitatory neurotransmitters sent from neurons into synapses",
				true,
				"Correct.");
			
				p.addAnswer(4, "a decreased concentration of calcium ions entering receiving neurons through calcium channels",
				false,
				"No. An increase of calcium ions into the receiving neuron through calcium channels would trigger greater responsiveness to individual action potentials and contribute to memory.");
			
				p.addAnswer(5, "an enzyme change that nullifies responsiveness to an action potential within receiving neurons",
				false,
				"No. Memory comes as the result of enzyme changes that increase responsiveness to an action potential.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336849;


		
		

		
			
			p.question = "Which of the following neurotransmitters is most closely associated with schizophrenia, addiction, and Parkinson\'s disease? (<script type=\"text/javascript\">ebook(\'4905\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "dopamine",
				true,
				"Correct.");
			
				p.addAnswer(2, "acetylcholine",
				false,
				"No. Acetylcholine is frequently found at a neuromuscular synapse.");
			
				p.addAnswer(3, "endorphins",
				false,
				"No. Endorphins are natural analgesics, decreasing pain perception.");
			
				p.addAnswer(4, "all of the above",
				false,
				"No. Only one of the choices is correct.");
			
				p.addAnswer(5, "none of the above",
				false,
				"One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336850;


		
		

		
			
			p.question = "Taking illegal amphetamines (\"speed\") can induce symptoms similar to _____. (<script type=\"text/javascript\">ebook(\'4905\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "schizophrenia",
				true,
				"Correct.");
			
				p.addAnswer(2, "Parkinson\'s disease",
				false,
				"No. Parkinson\'s disease is caused by a shortage of dopamine. These illegal drugs mimic the effects of too much dopamine.");
			
				p.addAnswer(3, "bipolar disorder",
				false,
				"No. Bipolar disorder is often treated with drugs that increase the brain concentration of biogenic amines.");
			
				p.addAnswer(4, "Alzheimer\'s disease",
				false,
				"No. Alzheimer\'s disease is associated with cell death and not an abundance of dopamine like substances.");
			
				p.addAnswer(5, "none of the above",
				false,
				"One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336851;


		
		

		
			
			p.question = "Which one of the following is caused by the death of neurons in the brain that release dopamine?  (<script type=\"text/javascript\">ebook(\'4905\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Parkinson\'s disease",
				true,
				"Correct.");
			
				p.addAnswer(2, "schizophrenia",
				false,
				"No. Schizophrenia is not thought to be caused by massive cell death.");
			
				p.addAnswer(3, "Alzheimer\'s disease",
				false,
				"No. Alzheimer\'s disease is associated with cell death of cells in many areas of the brain, including the hippocampus and cerebral cortex.");
			
				p.addAnswer(4, "major depressive disorder",
				false,
				"No. Major depressive disorder is not thought to be caused by massive cell death.");
			
				p.addAnswer(5, "none of the above",
				false,
				"One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

