

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "Investigation Quiz > How Is the Rate of Photosynthesis Measured?";
	ak.quiz_loc_with_commas = "Investigation Quiz, How Is the Rate of Photosynthesis Measured?";
	ak.quiz_title = "How Is the Rate of Photosynthesis Measured?";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 5;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 5;
	ak.non_essay_total = 0;
	ak.scored_item_total = 0;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337592;


		
		

		
			p.question = "Which graph would be the most likely result of performing the photosynthesis experiment using fresh chloroplasts placed in light and DPIP?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337593;


		
		

		
			p.question = "What is the best explanation for graph B?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337594;


		
		

		
			p.question = "What effect would adding more DPIP to each experimental tube have on these results?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337595;


		
		

		
			p.question = "What is the role of DPIP in this experiment?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337596;


		
		

		
			p.question = "Some students were not able to get many data points in this experiment because the solution went from blue to colorless in only 5 minutes for the unboiled chloroplasts exposed to light. What modification to the experiment do you think would be most likely to provide better results?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

