

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "15: The Chromosomal Basis of Inheritance > Practice Test";
	ak.quiz_loc_with_commas = "15: The Chromosomal Basis of Inheritance, Practice Test";
	ak.quiz_title = "Practice Test";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 41;
	ak.non_essay_total = 41;
	ak.scored_item_total = 41;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334957;


		
		

		
			
			p.question = "The chromosome theory of inheritance states that _____. (<script type=\"text/javascript\">ebook(\'1501\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "genes occupy specific positions on chromosomes",
				false,
				"No. This answer is correct, but it is not the best answer.");
			
				p.addAnswer(2, "homologous chromosomes segregate from each other during meiosis",
				false,
				"No. This answer is correct, but it is not the best answer.");
			
				p.addAnswer(3, "chromosomes assort independently during meiosis",
				false,
				"No. This answer is correct, but it is not the best answer.");
			
				p.addAnswer(4, "The first and second answers are correct.",
				false,
				"No. This answer is correct, but it is not the best answer.");
			
				p.addAnswer(5, "The first, second, and third answers are correct.",
				true,
				"Correct. The theory encompasses these three basic elements.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334958;


		
		

		
			
			p.question = "Why did Morgan choose <i>Drosophila</i><b> </b>for his genetics experiments? (<script type=\"text/javascript\">ebook(\'1501\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "They have a long generation time.",
				false,
				"No. <i>Drosophila</i> actually has a <b>short</b> generation time, making it feasible to carry out experiments that involve multiple generations.");
			
				p.addAnswer(2, "A single mating can produce many offspring.",
				false,
				"No. This trait is a good reason to use the fruit flies. Single matings producing many offspring are useful because it allows for statistical analysis of progeny, but there is a better answer.");
			
				p.addAnswer(3, "They have a large number of chromosomes.",
				false,
				"No. <i>Drosophila</i> has only four pairs of chromosomes. The relatively low chromosome number makes them easier to keep track of, map, and so on.");
			
				p.addAnswer(4, "<i>Drosophila</i> chromosomes can be easily distinguishable under a light microscope.",
				false,
				"No. <i>Drosophila\'s</i> small number of chromosomes can be distinguished under a light microscope, which can be useful for detecting deletions and other chromosomal abnormalities, but there is a better answer.");
			
				p.addAnswer(5, "both b and d",
				true,
				"Correct. The small number of chromosomes and the large number of offspring per mating contribute to <i>Drosophila\'s</i> usefulness as an experimental animal for genetics experiments.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334959;


		
		

		
			
			p.question = "Wild type refers to _____. (<script type=\"text/javascript\">ebook(\'1501\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the most common phenotype thought to be found in the natural population",
				true,
				"Correct. The wild type is the phenotype most often seen in the wild.");
			
				p.addAnswer(2, "the most extreme mutant phenotype observed in an experiment",
				false,
				"No. Wild type is not a mutant phenotype.");
			
				p.addAnswer(3, "any mutant genotype",
				false,
				"No. Wild type refers to a phenotype.");
			
				p.addAnswer(4, "a kind of chromosomal deletion",
				false,
				"No. Wild type refers to a phenotype.");
			
				p.addAnswer(5, "extranuclear genes",
				false,
				"No. Wild type refers to a phenotype.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334960;


		
		

		
			
			p.question = "Which of the following results of Thomas Hunt Morgan\'s experiments with white-eyed mutant flies was unexpected in light of Mendelian genetics? (<script type=\"text/javascript\">ebook(\'1501\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "In the parental cross, a white-eyed male was crossed with a red-eyed female. The F<sub>1</sub> progeny all had red eyes.",
				false,
				"No. This result would be expected with strictly dominant/recessive alleles.");
			
				p.addAnswer(2, "The F<sub>1</sub> flies were crossed with each other, and the F<sub>2</sub> progeny included red-eyed and white-eyed flies in a 3:1 ratio.",
				false,
				"No. This result would be expected with strictly dominant/recessive alleles.");
			
				p.addAnswer(3, "The mutant allele (white eyes) was recessive.",
				false,
				"No. This result was not unexpected. Either allele could be recessive according to Mendelian genetics.");
			
				p.addAnswer(4, "Among the F<sub>2</sub> progeny, only males had white eyes. All of the females had red eyes.",
				true,
				"Correct. This result was unexpected and led to the discovery of sex-linked genes.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. All but one of the answers follow normal Mendelian laws.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334961;


		
		

		
			
			p.question = "What is the probability that a male will inherit an X-linked recessive allele from his father? (<script type=\"text/javascript\">ebook(\'1502\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "0%",
				true,
				"Correct. A male receives a Y chromosome from his father, not an X.");
			
				p.addAnswer(2, "25%",
				false,
				"No. The correct answer is 0% because a son cannot receive an X chromosome from his father.");
			
				p.addAnswer(3, "50%",
				false,
				"No. The correct answer is 0% because a son cannot receive an X chromosome from his father.");
			
				p.addAnswer(4, "75%",
				false,
				"No. The correct answer is 0% because a son cannot receive an X chromosome from his father.");
			
				p.addAnswer(5, "100%",
				false,
				"No. The correct answer is 0% because a son cannot receive an X chromosome from his father.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334962;


		
		

		
			
			p.question = "In an X-linked, or sex-linked, trait, it is the contribution of _____ that determines whether a son will display the trait. (<script type=\"text/javascript\">ebook(\'1502\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the mother",
				true,
				"Correct. The son receives his single X chromosome from his mother and the Y from his father.");
			
				p.addAnswer(2, "the father",
				false,
				"No. A son does not inherit an X from his father.");
			
				p.addAnswer(3, "the paternal grandmother",
				false,
				"No. A male cannot trace his X chromosome to his paternal grandmother.");
			
				p.addAnswer(4, "the paternal grandfather",
				false,
				"No. However, a male can trace his Y chromosome to his paternal grandfather.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334963;


		
		

		
			
			p.question = "If a mother is heterozygous for a recessive sex-linked trait and her husband has the dominant allele, which one of the following is true about the probabilities for their children? (<script type=\"text/javascript\">ebook(\'1502\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "All of their sons will have the recessive trait.",
				false,
				"No. Their mother is heterozygous.");
			
				p.addAnswer(2, "Half of their sons will have the recessive trait.",
				true,
				"Correct. All the sons will receive Y chromosomes from their father. The X must come from the heterozygous mother; therefore, each son has a 50% chance of inheriting the recessive allele.");
			
				p.addAnswer(3, "None of their sons will have the recessive trait.",
				false,
				"No. Their mother is heterozygous.");
			
				p.addAnswer(4, "All of their daughters will be heterozygous.",
				false,
				"No. Their mother is heterozygous. Any daughters would have a 50% chance of being heterozygous.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334964;


		
		

		
			
			p.question = "In werewolves (hypothetically), pointy ears (<i>P</i>) are dominant over round ears (<i>p</i>). The gene is on the X chromosome. (Sex determination in werewolves is the same as for \"other\" humans.) A certain female werewolf has pointy ears even though her father had round ears. What percentage of her sons will have round ears if she mates with a werewolf with round ears? (<script type=\"text/javascript\">ebook(\'1502\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "0%",
				false,
				"No. Higher.");
			
				p.addAnswer(2, "25%",
				false,
				"No. Higher.");
			
				p.addAnswer(3, "50%",
				true,
				"Correct. The female werewolf must be heterozygous, because her father has round ears. Each of her sons has a 50% chance of inheriting the round allele.");
			
				p.addAnswer(4, "75%",
				false,
				"No. Lower.");
			
				p.addAnswer(5, "100%",
				false,
				"No. Lower.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334965;


		
		

		
			
			p.question = "A woman is red-green color-blind. What can we conclude, if anything, about her father? (<script type=\"text/javascript\">ebook(\'1502\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "We have too little information to tell.",
				false,
				"No. There is sufficient information to answer the question.");
			
				p.addAnswer(2, "There is a 50% probability that he has normal vision.",
				false,
				"No. A normal male cannot father a red-green color-blind daughter.");
			
				p.addAnswer(3, "He is red-green color-blind.",
				true,
				"Correct. For the woman to be affected with this sex-linked recessive trait, she must be homozygous; therefore, she must have received a recessive allele from her father. The father\'s single X must have the recessive allele.");
			
				p.addAnswer(4, "He has two Y chromosomes.",
				false,
				"No. A YY zygote would not survive.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334966;


		
		

		
			
			p.question = "A woman is a carrier for red-green color blindness, a sex-linked trait. Her husband is normal (not color-blind) for this trait. What are the chances that their newborn daughter will be red-green color-blind? (<script type=\"text/javascript\">ebook(\'1502\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "0%",
				true,
				"Correct. The daughter must receive one of her X chromosomes from her normal father and will not be color-blind.");
			
				p.addAnswer(2, "25%",
				false,
				"No. The father only has a single, normal allele.");
			
				p.addAnswer(3, "50%",
				false,
				"No. The father only has a single, normal allele.");
			
				p.addAnswer(4, "75%",
				false,
				"No. The father only has a single, normal allele.");
			
				p.addAnswer(5, "100%",
				false,
				"No. The father only has a single, normal allele.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334967;


		
		

		
			
			p.question = "Duchenne muscular dystrophy is caused by a sex-linked recessive allele. Its victims are almost invariably boys, who usually die before the age of 20. Why is this disorder almost never seen in girls? (<script type=\"text/javascript\">ebook(\'1502\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Sex-linked traits are never seen in girls.",
				false,
				"No. Females can express an X-linked recessive allele if they carry the allele on both X chromosomes.");
			
				p.addAnswer(2, "The allele is carried on the Y chromosome.",
				false,
				"No. An X-linked gene causes Duchenne muscular dystrophy.");
			
				p.addAnswer(3, "Nondisjunction occurs in males but not in females.",
				false,
				"No. Nondisjunction occurs in both males and females.");
			
				p.addAnswer(4, "To express an X-linked recessive allele, a female must have two copies of the allele.",
				true,
				"Correct. Moreover, males carrying the allele have less of an opportunity to have offspring.");
			
				p.addAnswer(5, "A sex-linked allele cannot be passed from mother to daughter.",
				false,
				"No. A daughter receives an X chromosome from her mother.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334968;


		
		

		
			
			p.question = "Hemophilia is a sex-linked disorder. The daughter of a father with hemophilia and a carrier mother has a _____ probability of having hemophilia. (<script type=\"text/javascript\">ebook(\'1502\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "100%",
				false,
				"No. The mother is heterozygous.");
			
				p.addAnswer(2, "25%",
				false,
				"No. The mother is heterozygous.");
			
				p.addAnswer(3, "50%",
				true,
				"Correct. The mother is X<sup><i>H</i></sup>X<sup><i>h</i></sup>, and the father is X<sup><i>h</i></sup>Y. The daughter must receive X<sup><i>h</i></sup> from the father and has a 50% chance of receiving X<sup><i>h</i></sup> from the mother.");
			
				p.addAnswer(4, "0%",
				false,
				"No. The mother is heterozygous.");
			
				p.addAnswer(5, "33%",
				false,
				"No. The mother is heterozygous.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334969;


		
		

		
			
			p.question = "Queen Victoria was a carrier of a recessive sex-linked allele for hemophilia. Which one of the following possibilities could explain the presence of the hemophilia allele in her genotype? (<script type=\"text/javascript\">ebook(\'1502\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Either her mother was a carrier or her father had hemophilia.",
				true,
				"Correct. Queen Victoria must have had the hemophilia allele on one of her X chromosomes. Either her mother was a carrier or her father was affected.");
			
				p.addAnswer(2, "Either her mother was homozygous dominant or her father had hemophilia.",
				false,
				"No. A homozygous dominant mother could not be responsible for a carrier daughter.");
			
				p.addAnswer(3, "Both her mother and her father had hemophilia.",
				false,
				"No. In this case, Queen Victoria would have had hemophilia.");
			
				p.addAnswer(4, "Either her mother was a carrier or her father had a dominant allele.",
				false,
				"No. A father with a dominant allele could not be responsible for a carrier daughter.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334970;


		
		

		
			
			p.question = "In a certain fish, fin rays (supporting structures for the fins) can be either bony or soft in adult fish. Sex linkage in a fish is similar to that in humans. What evidence would most strongly support the idea that the ray locus is on the X chromosome? (<script type=\"text/javascript\">ebook(\'1502\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Bony ray males can pass on bony rays only to their male offspring.",
				false,
				"No. This would support Y-linkage.");
			
				p.addAnswer(2, "Matings of soft ray males and bony ray females give different results from the matings of bony ray males and soft ray females.",
				true,
				"Correct. Genes affecting sex-linked traits will give particular sex ratios in the offspring, and reciprocal crosses (males with the dominant trait crossed with females with the recessive trait, and males with the recessive trait crossed with females with the dominant trait) would not have the same results.");
			
				p.addAnswer(3, "Females with either bony or soft rays can reproduce, but males with soft rays cannot transfer sperm to the female.",
				false,
				"No. An ability or inability to reproduce is not indicative of sex linkage.");
			
				p.addAnswer(4, "Females with bony rays cannot pass bony rays to female offspring even if they are mating with a bony ray male.",
				false,
				"No. Females can pass sex-linked traits to their offspring.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. Only one of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334971;


		
		

		
			
			p.question = "A genetic defect in humans results in the absence of sweat glands in the skin. Some men have this defect all over their bodies, but in women it is usually expressed in a peculiar way: A woman with this defect typically has small patches of skin with sweat glands and other patches without sweat glands. In women, the pattern of sweat-gland distribution can best be explained by _____. (<script type=\"text/javascript\">ebook(\'1502\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a mutation",
				false,
				"No. This would not explain the patched pattern.");
			
				p.addAnswer(2, "X chromosome inactivation",
				true,
				"Correct. This pattern suggests that a gene on the X chromosome is involved in the production of sweat glands. If a female has one X chromosome that directs sweat-gland production and one that does not, then she will have patches both with and without sweat glands.");
			
				p.addAnswer(3, "RNA splicing",
				false,
				"No. This process is involved in the production of mRNA.");
			
				p.addAnswer(4, "an operon",
				false,
				"No. An operon is involved in the regulation of gene expression in prokaryotes.");
			
				p.addAnswer(5, "a homeobox",
				false,
				"No. Homeoboxes are involved in the regulation of major developmental features.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334972;


		
		

		
			
			p.question = "With a microscope, you examine some somatic cells from a woman and notice that each nucleus has two Barr bodies. What can you infer about the sex chromosomes in this individual? (<script type=\"text/javascript\">ebook(\'1502\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "She is XX.",
				false,
				"No. A normal human female cell has only one Barr body.");
			
				p.addAnswer(2, "She is XXX.",
				true,
				"Correct. Inactive X chromosomes in the cells of a female condense into compact objects known as Barr bodies. All X chromosomes in excess of 1 are inactivated.");
			
				p.addAnswer(3, "She is XXXX.",
				false,
				"No. Such a female would have three Barr bodies.");
			
				p.addAnswer(4, "She is XXY, but the Y chromosome lacks the SRY gene.",
				false,
				"No. That individual would have only one Barr body.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334973;


		
		

		
			
			p.question = "If two genes are linked, _____. (<script type=\"text/javascript\">ebook(\'1503\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "they are on different chromosomes",
				false,
				"No. Such genes are not linked.");
			
				p.addAnswer(2, "they assort independently",
				false,
				"No. Genes that assort independently are not linked.");
			
				p.addAnswer(3, "they code for the same protein",
				false,
				"No. Genes encoding entirely unrelated proteins can be linked.");
			
				p.addAnswer(4, "they are on the same chromosome",
				true,
				"Correct. Genes located on the same chromosome are inherited together and are said to be linked.");
			
				p.addAnswer(5, "they are on sex chromosomes",
				false,
				"No. Linked genes are not limited to sex chromosomes.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334974;


		
		

		
			
			p.question = "In a particular species of mammal, black hair (<i>B</i>) is dominant to green hair (<i>b</i>), and red eyes (<i>R</i>) are dominant to white eyes (<i>r</i>). When a <i>BbRr</i> individual is mated with a <i>bbrr</i> individual, offspring are produced in a ratio of 5 black hair and red eyes:5 green hair and white eyes:1 black hair and white eyes:1 green hair and red eyes. Which of these explanations accounts for this ratio? (<script type=\"text/javascript\">ebook(\'1503\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Green-haired individuals have a higher prenatal mortality than black-haired individuals.",
				false,
				"No. If this were so, there would have been fewer green-haired, white-eyed offspring.");
			
				p.addAnswer(2, "The genes for hair color and the genes for eye color are carried on different chromosomes.",
				false,
				"No. If they were, the observed results would have matched the expected results.");
			
				p.addAnswer(3, "The expected results did not take genetic recombination into account.",
				false,
				"No. The expected results assumed that the genes recombined at random.");
			
				p.addAnswer(4, "The genes for both of these traits are carried on the autosomes.",
				false,
				"No. This is true, but it does not explain the results.");
			
				p.addAnswer(5, "The genes for hair color and eye color are linked.",
				true,
				"Correct. This explains why the parental types occur more often than would be expected if the traits assorted at random.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334975;


		
		

		
			
			p.question = "A gray-bodied, vestigial-winged fly is crossed with a black-bodied, normal-winged fly. The F<sub>1</sub> progeny is testcrossed. Among the resulting offspring, _____ is a parental type, and _____ is a recombinant type. (<script type=\"text/javascript\">ebook(\'1503\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "gray-bodied, normal-winged; black-bodied, vestigial-winged",
				false,
				"No. Gray-bodied, normal-winged is not a parental type.");
			
				p.addAnswer(2, "gray-bodied, vestigial-winged; black-bodied, normal-winged",
				false,
				"No. Black-bodied, normal-winged is not a recombinant type.");
			
				p.addAnswer(3, "gray-bodied, normal-winged; black-bodied, normal-winged",
				false,
				"No. Gray-bodied, normal-winged is not a parental type, and black-bodied, normal-winged is not a recombinant type.");
			
				p.addAnswer(4, "black-bodied, normal-winged; black-bodied, vestigial-winged",
				true,
				"Correct. The two parental types are gray-bodied, vestigial-winged and black-bodied, normal-winged, and the two recombinant types are gray-bodied, normal-winged and black-bodied, vestigial-winged.");
			
				p.addAnswer(5, "black-bodied, normal-winged; black-bodied, normal-winged",
				false,
				"No. Black-bodied, normal-winged is a parental type, and not a recombinant type.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334976;


		
		

		
			
			p.question = "You perform a testcross using F<sub>1</sub> dihybrid flies. If, in the resulting offspring, the percentages of parental and recombinant offspring are about the same, this would indicate that the two genes are _____. (<script type=\"text/javascript\">ebook(\'1503\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "linked",
				false,
				"No. An excess number of parental over recombinant offspring would have indicated linkage.");
			
				p.addAnswer(2, "unlinked",
				true,
				"Correct. Two genes on different chromosomes assort independently.");
			
				p.addAnswer(3, "similar in DNA sequence",
				false,
				"No. The relative proportions of parental and recombinant offspring give clues regarding linkage, not DNA sequence.");
			
				p.addAnswer(4, "mutated",
				false,
				"No. The relative proportions of parental and recombinant offspring give clues regarding linkage, not whether the genes are mutant or not.");
			
				p.addAnswer(5, "imprinted",
				false,
				"No. Imprinting refers to the sex-specific inactivation of certain genes during gametogenesis.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334977;


		
		

		
			
			p.question = "The recombination frequency between two gene loci is _____.\n (<script type=\"text/javascript\">ebook(\'1503\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "dependent on the sex of the parent",
				false,
				"No. Recombination frequency is the same in males and females.");
			
				p.addAnswer(2, "greater as the distance between the two loci increases",
				true,
				"Correct. The farther apart two genes are, the higher the probability that a crossover will occur between them, and therefore the higher the recombination frequency.");
			
				p.addAnswer(3, "greater as the distance between the two loci decreases",
				false,
				"No. In fact, the opposite is true.");
			
				p.addAnswer(4, "dependent on whether dominant or recessive alleles are carried at the two loci",
				false,
				"No. This is not relevant.");
			
				p.addAnswer(5, "equal to the size of the chromosome",
				false,
				"No. Recombination frequency has to do with how far apart the genes are on a chromosome, not the size of the chromosome.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334978;


		
		

		
			
			p.question = "Four genes (A, B, C, and D) are on the same chromosome. The recombination frequencies are as follows: A-B: 19%; B-C: 14%; A-C: 5%; B-D: 2%; A-D: 21%; C-D: 16%. Based on this information, which sequence of genes is correct? (<script type=\"text/javascript\">ebook(\'1503\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "ABCD",
				false,
				"No. The A-B distance is greater than the A-C distance.");
			
				p.addAnswer(2, "ABDC",
				false,
				"No. The A-B distance is greater than the A-C distance.");
			
				p.addAnswer(3, "ACBD",
				true,
				"Correct. C must lie between A and B (5 +14 = 19). Similarly, D must be beyond B to be 21 units from A and 2 units from B.");
			
				p.addAnswer(4, "ACDB",
				false,
				"No. The A-B distance is less than the A-D distance.");
			
				p.addAnswer(5, "ADBC",
				false,
				"No. The A-B distance is greater than the A-C distance.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334979;


		
		

		
			
			p.question = "In question 18, the observed distribution of offspring was as follows: black-red 1,070; black-white 177; green-red 180; green-white 1,072. Based on these data, what is the recombination frequency? (<script type=\"text/javascript\">ebook(\'1503\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "86%",
				false,
				"No. Recombination frequency = (number of recombinants)/(total offspring) x 100.");
			
				p.addAnswer(2, "7%",
				false,
				"No. Recombination frequency = (number of recombinants)/(total offspring) x 100.");
			
				p.addAnswer(3, "approximately 17%",
				false,
				"No. Recombination frequency = (number of recombinants)/(total offspring) x 100.");
			
				p.addAnswer(4, "approximately 14%",
				true,
				"Correct. 177 + 180 = 357 recombinants. 357 recombinants/2,499 total offspring x 100 = 14% (approximately).");
			
				p.addAnswer(5, "30%",
				false,
				"No. Recombination frequency = (number of recombinants)/(total offspring) x 100.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334980;


		
		

		
			
			p.question = "A linkage map _____. (<script type=\"text/javascript\">ebook(\'1503\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "orders genes on a chromosome based on recombination frequencies",
				true,
				"Correct. A linkage map presents the correct order of genes on the chromosome, although it is not necessarily an accurate representation of the actual distances between genes.");
			
				p.addAnswer(2, "can be constructed only for sex chromosomes",
				false,
				"No. Linkage maps can be constructed for both sex chromosomes and autosomes.");
			
				p.addAnswer(3, "orders genes on a chromosome based on their location with respect to a stained band",
				false,
				"No. This is a feature of a cytological map.");
			
				p.addAnswer(4, "shows the ordering and exact spacing of genes on a chromosome",
				false,
				"No. However, DNA technology has made the construction of such a map possible.");
			
				p.addAnswer(5, "predicts the probability that you will have a male or female child",
				false,
				"No. A linkage map contains the location of genes on a chromosome.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334981;


		
		

		
			
			p.question = "Because the frequency of crossing over is not uniform along the length of a chromosome, _____. (<script type=\"text/javascript\">ebook(\'1503\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the recombination frequency between two genes cannot be used to calculate the number of map units separating them",
				false,
				"No. Map units always reflect recombination frequency.");
			
				p.addAnswer(2, "map units do not necessarily correlate to physical distances along the chromosome",
				true,
				"Correct. Map units reflect recombination frequency, but not physical distance.");
			
				p.addAnswer(3, "pairs of homologous chromosomes contain small but significant differences in gene order",
				false,
				"No. Homologous pairs of chromosomes have the same genes, in the same order.");
			
				p.addAnswer(4, "the centimorgan is an unreliable unit of measurement, and is rarely used today",
				false,
				"No. Centimorgans are an ever-useful indication of recombination frequency.");
			
				p.addAnswer(5, "recombination frequency cannot be used to determine the number of centimorgans separating two genes",
				false,
				"No. Map units (centimorgans) always reflect recombination frequency.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334982;


		
		

		
			
			p.question = "During meiosis, homologous chromosomes sometimes \"stick together\" and do not separate properly. This phenomenon is known as _____. (<script type=\"text/javascript\">ebook(\'1504\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "cellular sterility",
				false,
				"No. Another term is used to describe the phenomenon.");
			
				p.addAnswer(2, "meiotic failure",
				false,
				"No. Another term is used to describe the phenomenon.");
			
				p.addAnswer(3, "gametic infertility",
				false,
				"No. Another term is used to describe the phenomenon.");
			
				p.addAnswer(4, "nondisjunction",
				true,
				"Correct. In nondisjunction, chromosomes fail to separate properly at meiosis.");
			
				p.addAnswer(5, "sticky chiasmata",
				false,
				"No. Another term is used to describe the phenomenon.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334983;


		
		

		
			
			p.question = "In Klinefelter syndrome, individuals are phenotypically male, but they have reduced sperm production and may have some breast development in adolescence. The cells of Klinefelter individuals have two X chromosomes and one Y (they are XXY instead of XY). This occurs because of what meotic error? (<script type=\"text/javascript\">ebook(\'1504\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "translocation",
				false,
				"No. A translocation occurs when fragments produced by chromosomal breakage join nonhomologous chromosomes.");
			
				p.addAnswer(2, "polyploidy",
				false,
				"No. This refers to a condition in which a cell has more than two complete chromosomal sets.");
			
				p.addAnswer(3, "aneuploidy",
				true,
				"Correct. Aneuploidy is a chromosomal condition in which one or more chromosomes are present in extra copies or are deficient in number.");
			
				p.addAnswer(4, "duplication",
				false,
				"No. Duplication refers to the presence of additional segments within a single chromosome, not to the presence of additional chromosomes.");
			
				p.addAnswer(5, "monosomy",
				false,
				"No. Monosomy means one chromosome too few.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334984;


		
		

		
			
			p.question = "Cells that have a number of chromosomes different from the normal number for their species are known as _____. (<script type=\"text/javascript\">ebook(\'1504\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "aneuploid",
				true,
				"Correct. Any deviation in chromosome number is called aneuploidy.");
			
				p.addAnswer(2, "diploid",
				false,
				"No. Diploidy is two sets of chromosomes.");
			
				p.addAnswer(3, "polyploid",
				false,
				"No. Some organisms have more than two complete sets of chromosomes and are called polyploid. This is only one type of aneuploidy.");
			
				p.addAnswer(4, "nanoploid",
				false,
				"No. Another term is the correct one.");
			
				p.addAnswer(5, "trisomy",
				false,
				"No. In trisomy, there is one chromosome too many; but this represents only one kind of aneuploidy");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334985;


		
		

		
			
			p.question = "_____ is usually less severe than _____, and _____ species have been observed in plants, fish, amphibians, and even mammals. (<script type=\"text/javascript\">ebook(\'1505\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Polyploidy; aneuploidy; polyploid",
				true,
				"Correct. Polyploidy appears to disrupt genetic balance less than aneuploidy, and it has been observed among animals and especially plants.");
			
				p.addAnswer(2, "Aneuploidy; polyploidy; aneuploid",
				false,
				"No. Aneuploidy is generally more severe than polyploidy.");
			
				p.addAnswer(3, "Monosomy; trisomy; monosomic",
				false,
				"No. The correct answer deals with polyploidy and aneuploidy. Monosomy is always serious in a diploid species.");
			
				p.addAnswer(4, "Trisomy; monosomy; trisomic",
				false,
				"No. The correct answer deals with polyploidy and aneuploidy.");
			
				p.addAnswer(5, "Nondisjunction; disjunction; nondisjunctional",
				false,
				"No. The correct answer deals with polyploidy and aneuploidy.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334986;


		
		

		
			
			p.question = "Gene A is normally found on chromosome number 15 in humans. If amniocentesis reveals fetal cells containing gene A on chromosome 17, but not on 15, the best explanation would be that _____. (<script type=\"text/javascript\">ebook(\'1504\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "crossing over occurred during synapsis of meiosis I in one parent\'s gametes",
				false,
				"Crossing over occurs between homologous chromosomes and does not change the chromosome position of genes.");
			
				p.addAnswer(2, "base substitution occurred either during gametogenesis or in the mitotic divisions following fertilization",
				false,
				"No. A base substitution would not account for this observation.");
			
				p.addAnswer(3, "an inversion of gene A occurred on chromosome 15",
				false,
				"No. An inversion does not result in a gene moving from one chromosome to another.");
			
				p.addAnswer(4, "translocation occurred",
				true,
				"Correct. Fragments produced by chromosomal breakage may join nonhomologous chromosomes, a rearrangement known as a translocation.");
			
				p.addAnswer(5, "at least one parent probably had a genetic syndrome",
				false,
				"No. Not necessarily.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334987;


		
		

		
			
			p.question = "The chromosomal abnormality in which a fragment of a chromosome breaks off and then reattaches to the original chromosome in the same place but in the reverse direction is called _____. (<script type=\"text/javascript\">ebook(\'1504\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "inversion",
				true,
				"Correct. As the name suggests, an inversion is a backwards piece of a chromosome.");
			
				p.addAnswer(2, "translocation",
				false,
				"No. When fragments produced by chromosomal breakage join nonhomologous chromosomes, the rearrangement is known as a translocation.");
			
				p.addAnswer(3, "transduction",
				false,
				"No. Transduction can relate to the viral transfer of genetic material from one prokaryote to another or to signal-transduction pathways.");
			
				p.addAnswer(4, "transformation",
				false,
				"No. Transformation is the process by which prokaryotes take up genetic material from their surrounding environment.");
			
				p.addAnswer(5, "duplication",
				false,
				"No. This is when an exact copy of a region of a chromosome is added to that chromosome.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334988;


		
		

		
			
			p.question = "Why are individuals with an extra chromosome 21, which causes Down syndrome, more numerous than individuals with an extra chromosome 3 or chromosome 16? (<script type=\"text/javascript\">ebook(\'1504\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "There are probably more genes on chromosome 21 than on the others.",
				false,
				"No. This is not likely since chromosome 21 is the smallest of the three.");
			
				p.addAnswer(2, "Chromosome 21 is a sex chromosome, and 3 and 16 are not.",
				false,
				"No. All three of these chromosomes are autosomes.");
			
				p.addAnswer(3, "Down syndrome is not more common, just more serious.",
				false,
				"No. In fact, trisomies of other autosomes are even more damaging than trisomy 21.");
			
				p.addAnswer(4, "Extra copies of the other chromosomes are probably fatal to the developing embryo.",
				true,
				"Correct. Nearly all trisomies have lethal effects.");
			
				p.addAnswer(5, "Nondisjunction of chromosomes 3 and 16 probably occurs much less frequently.",
				false,
				"No. Nondisjunction occurs for all chromosomes, but it is most likely fatal unless it involves a sex chromosome or a small chromosome such as chromosome 21.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334989;


		
		

		
			
			p.question = "When a person has Down syndrome, he or she has an extra chromosome 21. Therefore, Down syndrome is a kind of _____ and results from _____. (<script type=\"text/javascript\">ebook(\'1504\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "aneuploidy; nondisjunction of chromosome 21 during meiosis I",
				true,
				"Correct. One aneuploid condition, Down syndrome, is the result of an extra chromosome 21.");
			
				p.addAnswer(2, "polyploidy; occurrence of meiosis without cytokinesis",
				false,
				"No. Polyploidy refers to extra sets of chromosomes.");
			
				p.addAnswer(3, "genomic imprint; excessive methylation of either the paternal or maternal chromosome 21",
				false,
				"No. Genomic imprinting produces differences in the effects of alleles depending on whether they are inherited from the mother or the father. Down syndrome does not result from imprinting.");
			
				p.addAnswer(4, "replication error; an extra cycle of DNA synthesis during the S phase",
				false,
				"No. An extra cycle of DNA synthesis during the S phase is not responsible for Down syndrome.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334990;


		
		

		
			
			p.question = "A person with two X chromosomes and one Y chromosome would appear to be _____. (<script type=\"text/javascript\">ebook(\'1504\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "male",
				true,
				"Correct. The presence of the Y chromosome determines maleness in humans. A male with an extra X chromosome has Klinefelter syndrome.");
			
				p.addAnswer(2, "female",
				false,
				"No. The presence of the Y chromosome would trigger male development.");
			
				p.addAnswer(3, "both male and female",
				false,
				"No. The presence of the Y chromosome would trigger male development, regardless of how many Xs are present.");
			
				p.addAnswer(4, "neither male nor female",
				false,
				"No. The presence of the Y chromosome would trigger male development.");
			
				p.addAnswer(5, "any of the above, depending on the number of other chromosomes",
				false,
				"No. This is not the mechanism of sex determination in humans.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334991;


		
		

		
			
			p.question = "Which one of the following is the only known viable human monosomy? (<script type=\"text/javascript\">ebook(\'1504\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "XYY",
				false,
				"No. This is a trisomy.");
			
				p.addAnswer(2, "XO",
				true,
				"Correct. Turner\'s syndrome, or XO, is the only viable human monosomy.");
			
				p.addAnswer(3, "YO",
				false,
				"No. A monosomy Y zygote would not survive.");
			
				p.addAnswer(4, "XY",
				false,
				"No. This is a normal human male.");
			
				p.addAnswer(5, "XXY",
				false,
				"No. This is a trisomy.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334992;


		
		

		
			
			p.question = "Which type of chromosomal alteration is responsible for the <i>cri du chat</i> syndrome? (<script type=\"text/javascript\">ebook(\'1504\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "inversion",
				false,
				"No. This type of alteration is not responsible.");
			
				p.addAnswer(2, "duplication",
				false,
				"No. This type of alteration is not responsible.");
			
				p.addAnswer(3, "genetic imprinting",
				false,
				"No. Genetic imprinting is a normal exception to the rules of Mendelian genetics.");
			
				p.addAnswer(4, "deletion",
				true,
				"Correct. A specific deletion from chromosome 5 leads to this disorder, which is characterized by mental retardation, small head and unusual facial features, and a cry that sounds like a distressed cat.");
			
				p.addAnswer(5, "translocation",
				false,
				"No. This type of alteration is not responsible.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334993;


		
		

		
			
			p.question = "What appears to be the mechanism for genomic imprinting? (<script type=\"text/javascript\">ebook(\'1505\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "DNA methylation that silences particular genes",
				false,
				"No. In some cases DNA methylation does silence genes on either the maternal or paternal chromosome, but there is a better answer.");
			
				p.addAnswer(2, "crossing over",
				false,
				"No. Crossing over does not appear to play a part in genomic imprinting.");
			
				p.addAnswer(3, "DNA methylation that activates particular genes",
				false,
				"No. In some cases DNA methylation does activate certain genes, but there is a better answer.");
			
				p.addAnswer(4, "non-disjunction",
				false,
				"No. Non-disjunction does not appear to play a role in genomic imprinting.");
			
				p.addAnswer(5, "both a and c",
				true,
				"Correct. DNA methylation appears to be the major mechanism involved in genomic imprinting, but in come cases it silences a gene while in others it activates a gene.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334994;


		
		

		
			
			p.question = "Genomic imprinting in mammals appears to affect primarily genes involved in ______. (<script type=\"text/javascript\">ebook(\'1505\',\'quiz\')</script>)";
			p.incorrect_any_expl = "No. Most known imprinted genes are important for embryonic development.";
			p.incorrect_any_expl_flag = 1;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "embryonic development",
				true,
				"Correct. Igf2 is an example of a growth factor required fro normal prenatal development. Experiments have also shown that organisms with improperly imprinted genes often die before birth.");
			
				p.addAnswer(2, "function of the nervous system",
				false,
				"");
			
				p.addAnswer(3, "sex determination",
				false,
				"");
			
				p.addAnswer(4, "digestion",
				false,
				"");
			
				p.addAnswer(5, "vision",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334995;


		
		

		
			
			p.question = "Both chloroplasts and mitochondria _____. (<script type=\"text/javascript\">ebook(\'1505\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "are found within the nucleus",
				false,
				"No. Both of these organelles are found outside the nucleus.");
			
				p.addAnswer(2, "have linear DNA",
				false,
				"No. The DNA of these organelles is circular.");
			
				p.addAnswer(3, "carry extranuclear genes",
				true,
				"Correct. Both chloroplasts and mitochondria carry extranuclear genes.");
			
				p.addAnswer(4, "are inherited from both parents",
				false,
				"No. Both of these organelles are inherited only from the maternal parent.");
			
				p.addAnswer(5, "display a Mendelian pattern of inheritance",
				false,
				"No. Both of these organelles display a non-Mendelian pattern of inheritance.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334996;


		
		

		
			
			p.question = "It is proposed that a certain disorder affecting the inner ear is caused by mitochondrial DNA. Which of the following observations would be the most decisive evidence <b>against</b> this idea? (<script type=\"text/javascript\">ebook(\'1505\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Fathers with the disorder pass it on to all their children, but mothers with the disorder do not pass it along.",
				true,
				"Correct. Maternal inheritance is the rule for mitochondrial genes in mammals, because the mitochondria in the zygote all come from the cytoplasm of the egg.");
			
				p.addAnswer(2, "Females and males have the disorder in equal numbers.",
				false,
				"No. Mitochondrial disorders can affect both males and females, so this would be consistent with mitochondrial inheritance.");
			
				p.addAnswer(3, "Mothers pass the disorder on to their offspring, but fathers do not.",
				false,
				"No. This would support the mitochondrial inheritance of this condition.");
			
				p.addAnswer(4, "The precise cause of the disorder is found to involve the nervous system.",
				false,
				"No. Mitochondrial diseases often affect the nervous system.");
			
				p.addAnswer(5, "All of the above would be evidence against mitochondrial inheritance of this condition.",
				false,
				"No. Only one of the above provides strong evidence against the mitochondrial inheritance of this condition.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334997;


		
		

		
			
			p.question = "A person\'s remains are found, and officials are trying to identify them. A couple believes that the remains belong to their missing daughter. Because the remains have decayed considerably, mitochondrial DNA is being used to determine the person\'s identity. In order to determine if the remains belong to someone in this couple\'s family, whose mitochondrial DNA should be used for comparison? (<script type=\"text/javascript\">ebook(\'1505\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the husband\'s",
				false,
				"No. The mitochondria in the zygote all come from the cytoplasm of the egg, so the husband would not have contributed to the mitochondrial DNA of his daughter.");
			
				p.addAnswer(2, "either the husband\'s or the wife\'s",
				false,
				"No. The mitochondria in the zygote all come from the cytoplasm of the egg, so the husband would not have contributed to the mitochondrial DNA of his daughter.");
			
				p.addAnswer(3, "the husband\'s mother",
				false,
				"No. Although the husband would have inherited his mitochondrial DNA from his mother, he would not have passed it on to his children.");
			
				p.addAnswer(4, "one of the couple\'s other children",
				true,
				"Correct. Because mitochondrial DNA all comes from the egg, a mother passes essentially the same mitochondrial DNA to each of her children. A child from the same family should be nearly identical.");
			
				p.addAnswer(5, "Anyone from the same family will have nearly identical mitochondrial DNA.",
				false,
				"No. The father does not contribute mitochondrial DNA to his offspring.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

