

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "47: Animal Development > Practice Test";
	ak.quiz_loc_with_commas = "47: Animal Development, Practice Test";
	ak.quiz_title = "Practice Test";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 30;
	ak.non_essay_total = 30;
	ak.scored_item_total = 30;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336727;


		
		

		
			
			p.question = "The idea that an egg or sperm contains a preformed, miniature infant that in turn contains a preformed, miniature infant is known as _____. (<script type=\"text/javascript\">ebook(\'47OV\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "preformation",
				true,
				"Correct. This idea, no longer considered valid, considered the entire human race to be nested inside itself, like a series of Russian nesting dolls.");
			
				p.addAnswer(2, "cleavage",
				false,
				"No. Cleavage is a succession of rapid cell divisions.");
			
				p.addAnswer(3, "gastrulation",
				false,
				"No. Gastrulation is a dramatic rearrangement of the cells of the blastula, forming a three-layered embryo with a primitive gut.");
			
				p.addAnswer(4, "implantation",
				false,
				"No. Implantation is the process by which a developing embryo begins to grow within the uterus.");
			
				p.addAnswer(5, "cell differentiation",
				false,
				"No. Cell differentiation is the specialization of cells in their structure and function.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336728;


		
		

		
			
			p.question = "In many species, the uneven distribution of _____ within the unfertilized eggs causes the embryonic cells to develop differently. (<script type=\"text/javascript\">ebook(\'47OV\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "cytoplasmic determinants",
				true,
				"Correct. During cleavage, different mRNAs, proteins, and other molecules are sorted into the blastomeres, influencing their fate.");
			
				p.addAnswer(2, "tissues",
				false,
				"No. Tissues are groups of cells.");
			
				p.addAnswer(3, "nuclei",
				false,
				"No. Most unfertilized eggs have just one nucleus.");
			
				p.addAnswer(4, "gametes",
				false,
				"No. Eggs and sperm are types of gametes.");
			
				p.addAnswer(5, "cortical granules",
				false,
				"No. Cortical granules, formed during oogenesis, release their contents into the space between the plasma membrane and the vitelline layer during fertilization.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336729;


		
		

		
			
			p.question = "As an animal develops, organs form and the body transforms into a shape typical of the species, in a process called _____. (<script type=\"text/javascript\">ebook(\'47OV\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "morphogenesis",
				true,
				"Correct. Morphogenesis is the overall process by which specialized cells become organized into organs, organ systems, and collectively into an organism.");
			
				p.addAnswer(2, "preformation",
				false,
				"No. Preformation is an old idea that the egg or sperm contains an embryo that simply becomes enlarged during development.");
			
				p.addAnswer(3, "cleavage",
				false,
				"No. Cleavage partitions the cytoplasm of the zygote into many smaller cells called blastomeres.");
			
				p.addAnswer(4, "cell differentiation",
				false,
				"No. Although this is part of the process, the answer to this question is more specific.");
			
				p.addAnswer(5, "gastrulation",
				false,
				"No. Gastrulation is a dramatic rearrangement of the cells of the blastula, forming a three-layered embryo with a primitive gut.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336730;


		
		

		
			
			p.question = "A sea urchin sperm penetrates the jelly coat of an egg and adheres to receptor proteins on the egg\'s surface as a result of _____. (<script type=\"text/javascript\">ebook(\'4701\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the acrosomal reaction",
				true,
				"Correct. The acrosomal reaction is a dramatic change in the shape of the sperm head as a sperm approaches an egg.");
			
				p.addAnswer(2, "cleavage",
				false,
				"No. Cleavage partitions the cytoplasm of the zygote into many smaller cells called blastomeres.");
			
				p.addAnswer(3, "gastrulation",
				false,
				"No. Gastrulation is a dramatic rearrangement of the cells of the blastula, forming a three-layered embryo with a primitive gut.");
			
				p.addAnswer(4, "the cortical reaction",
				false,
				"No. The cortical reaction is part of the slow block to polyspermy.");
			
				p.addAnswer(5, "depolarization",
				false,
				"No. Depolarization is a change in the egg\'s membrane that is part of the fast block to polyspermy.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336731;


		
		

		
			
			p.question = "How does a zygote differ from an ovum? (<script type=\"text/javascript\">ebook(\'4701\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A zygote has more chromosomes.",
				true,
				"Correct. In humans, for example, the haploid ovum has 23 chromosomes, whereas the zygote has 46.");
			
				p.addAnswer(2, "A zygote is smaller.",
				false,
				"No. Both the ovum and zygote are single cells. Fertilization adds the sperm nucleus to the zygote but produces no appreciable change in size.");
			
				p.addAnswer(3, "A zygote consists of more than one cell.",
				false,
				"No. Both the ovum and zygote are single cells.");
			
				p.addAnswer(4, "A zygote is much larger.",
				false,
				"No. Both the ovum and zygote are single cells. Fertilization adds the sperm nucleus to the zygote but produces no appreciable change in size.");
			
				p.addAnswer(5, "A zygote divides by meiosis.",
				false,
				"No. Meiosis results in a reduction of chromosome number. The zygote divides by mitosis.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336732;


		
		

		
			
			p.question = "After a sperm penetrates an egg, a fertilization envelope forms. This envelope _____. (<script type=\"text/javascript\">ebook(\'4701\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "secretes important hormones",
				false,
				"No. The membrane has no known hormonal function.");
			
				p.addAnswer(2, "enables the fertilized egg to implant itself in the wall of the uterus",
				false,
				"No. Implantation is the process by which a developing embryo begins to grow within the uterus.");
			
				p.addAnswer(3, "prevents more than one sperm from entering the egg",
				true,
				"Correct. The new fertilization envelope, along with other changes to the egg\'s surface, is the slow block to polyspermy. The fertilization envelope develops about one minute after the fusion of egg and sperm.");
			
				p.addAnswer(4, "attracts additional sperm to the egg",
				false,
				"No. In fact, the fertilization envelope prevents additional sperm from contacting receptors on the plasma membrane of the egg.");
			
				p.addAnswer(5, "is responsible for the fast block to polyspermy",
				false,
				"No. Depolarization of the egg cell\'s plasma membrane is the fast block to polyspermy.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336733;


		
		

		
			
			p.question = "Cell divisions called _____ proceed so rapidly in the developing embryo that there is no growth of the cells between divisions. (<script type=\"text/javascript\">ebook(\'4701\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "meiosis",
				false,
				"No. The developing embryo consists of diploid cells.");
			
				p.addAnswer(2, "binary fission",
				false,
				"No. Bacterial cells but not animal cells divide by binary fission.");
			
				p.addAnswer(3, "cleavage",
				true,
				"Correct. Cleavage is a succession of rapid cell divisions that follow fertilization. During cleavage the embryo does not enlarge.");
			
				p.addAnswer(4, "fragmentation",
				false,
				"No. Fragmentation is an asexual mode of reproduction that involves breaking the body into several pieces.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336734;


		
		

		
			
			p.question = "During cleavage the single large zygote is converted into a _____. (<script type=\"text/javascript\">ebook(\'4701\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "multicellular embryo consisting of smaller cells called blastomeres",
				true,
				"Correct. Cleavage reduces cell size by dividing the zygote into smaller cells that form the morula and then the blastula.");
			
				p.addAnswer(2, "three-layered embryo called a gastrula",
				false,
				"No. Eventually the zygote becomes a gastrula, but an important step occurs before gastrulation.");
			
				p.addAnswer(3, "multicellular embryo with a blastopore and an archenteron",
				false,
				"No. The blastopore and archenteron are features of a gastrula. A developmental stage occurs prior to gastrulation.");
			
				p.addAnswer(4, "multicellular embryo consisting of a zona pellucida and a zygote",
				false,
				"No. The zona pellucida is a layer of follicle cells that accompany the ovum after ovulation.");
			
				p.addAnswer(5, "fetus",
				false,
				"No. The term \"fetus\" indicates a well-developed embryo. In humans, the term \"fetus\" is used after the eighth week of development.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336735;


		
		

		
			
			p.question = "How is the animal hemisphere of a frog blastula different from the vegetal hemisphere? (<script type=\"text/javascript\">ebook(\'4701\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The cells of the vegetal hemisphere have more yolk than the cells of the animal hemisphere.",
				true,
				"Correct. The yolk is more concentrated in the vegetal hemisphere end of the egg and resulting embryo.");
			
				p.addAnswer(2, "The cells of the vegetal hemisphere do not participate in gastrulation.",
				false,
				"No. All of the cells in both hemispheres participate in gastrulation.");
			
				p.addAnswer(3, "The vegetal hemisphere is where the polar bodies were produced during oogenesis.",
				false,
				"No. The animal hemisphere is where the polar bodies were produced during oogenesis.");
			
				p.addAnswer(4, "The cells of the vegetal hemisphere are pigmented more darkly than the cells of the animal hemisphere.",
				false,
				"No. The cells of the animal hemisphere are pigmented more darkly than the cells of the vegetal hemisphere.");
			
				p.addAnswer(5, "The blastomeres in the animal hemisphere are larger than the cells in the vegetal hemisphere.",
				false,
				"No. The blastomeres in the vegetal hemisphere are larger than the cells in the animal hemisphere.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336736;


		
		

		
			
			p.question = "In a frog gastrula, the area where the gray crescent occurred will be the _____ of the embryo and the blastopore its _____. (<script type=\"text/javascript\">ebook(\'4701\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "dorsal side; anus",
				true,
				"Correct. The head end is the point on the embryo at the opposite point of the blastopore.");
			
				p.addAnswer(2, "dorsal side; mouth",
				false,
				"No. The orientation is different.");
			
				p.addAnswer(3, "ventral side; mouth",
				false,
				"No. The orientation is different.");
			
				p.addAnswer(4, "ventral side; anus",
				false,
				"No. The orientation is different.");
			
				p.addAnswer(5, "mouth; dorsal side",
				false,
				"No. The orientation is different.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336737;


		
		

		
			
			p.question = "In meroblastic cleavage in birds _____. (<script type=\"text/javascript\">ebook(\'4701\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "all cell divisions are perpendicular to the animal-vegetal pole",
				false,
				"No. In most embryos the first two cleavage divisions are polar, or vertical to the axis. In any case, \"meroblastic\" does not refer to the cleavage orientation.");
			
				p.addAnswer(2, "mesoderm and endoderm differentiate via cell division from mesenchyme",
				false,
				"No. The differentiation of embryonic tissues occurs during gastrulation, an event that follows cleavage.");
			
				p.addAnswer(3, "newly formed cells migrate toward the interior of the embryo",
				false,
				"No. The migration of cells to the interior of the embryo occurs during gastrulation.");
			
				p.addAnswer(4, "the zygote and later blastomeres completely divide with each round of cell division",
				false,
				"No. This type of cleavage is called holoblastic cleavage.");
			
				p.addAnswer(5, "cell division is restricted to a small disk of yolk-free cytoplasm at the animal pole of the zygote",
				true,
				"Correct. Yolk impedes cell division. In cells with a large yolk supply, cleavage is often initially restricted to the animal pole.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336738;


		
		

		
			
			p.question = "During gastrulation, the primitive _____ forms. (<script type=\"text/javascript\">ebook(\'4701\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "eye",
				false,
				"No. The eye does not form during gastrulation.");
			
				p.addAnswer(2, "gut",
				true,
				"Correct. Gastrulation rearranges the blastula, forming a three-layered embryo with a primitive gut.");
			
				p.addAnswer(3, "nervous system",
				false,
				"No. However, the germ layer that will give rise to the nervous system forms during gastrulation.");
			
				p.addAnswer(4, "heart",
				false,
				"No. However, the germ layer that will give rise to the heart forms during gastrulation.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336739;


		
		

		
			
			p.question = "What is the embryonic origin of the lining of the digestive tube? (<script type=\"text/javascript\">ebook(\'4701\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "endoderm",
				true,
				"Correct. Endoderm is the embryonic source of the lining of the digestive tube.");
			
				p.addAnswer(2, "ectoderm",
				false,
				"No. The ectoderm does not give rise to this structure.");
			
				p.addAnswer(3, "mesoderm",
				false,
				"No. The mesoderm does not give rise to this structure.");
			
				p.addAnswer(4, "both endoderm and mesoderm",
				false,
				"No. The mesoderm does not give rise to this structure.");
			
				p.addAnswer(5, "all three germ layers",
				false,
				"No. The endoderm is the embryonic source of the lining of the digestive tube.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336740;


		
		

		
			
			p.question = "One difference between the blastula and gastrula stages of development is that _____. (<script type=\"text/javascript\">ebook(\'4701\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "blastula cells are more differentiated than gastrula cells",
				false,
				"No. The gastrula is a later developmental stage than the blastula; therefore, its cells are more specialized.");
			
				p.addAnswer(2, "there are many more cells in a blastula",
				false,
				"No. The blastula is an earlier embryonic stage with fewer cells.");
			
				p.addAnswer(3, "the blastula consists of more cell layers",
				false,
				"No. The blastula is a hollow sphere of cells without distinct cell layers.");
			
				p.addAnswer(4, "the blastula is a solid ball of cells, but the gastrula is hollow",
				false,
				"No. The blastula and gastrula are both hollow spheres of cells.");
			
				p.addAnswer(5, "there is an opening from the cavity inside the gastrula to the outside",
				true,
				"Correct. This opening to the archenteron is called the blastopore.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336741;


		
		

		
			
			p.question = "Which of the following events occurs only during organogenesis? (<script type=\"text/javascript\">ebook(\'4701\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "cell migration",
				false,
				"No. Cell migration is an important part of gastrulation.");
			
				p.addAnswer(2, "obliteration of the blastocoel",
				false,
				"No. The blastocoel, formed earlier by the cleavage of the zygote, is obliterated as the archenteron expands during gastrulation.");
			
				p.addAnswer(3, "formation of the archenteron",
				false,
				"No. The archenteron is formed and grows larger throughout gastrulation.");
			
				p.addAnswer(4, "sorting of cells into three layers",
				false,
				"No. The formation of the three germ layers is a main feature of gastrulation.");
			
				p.addAnswer(5, "differentiation of cells into tissues",
				true,
				"Correct. The differentiation of tissues and the development of embryonic organs such as the notochord and neural tube occur after gastrulation as the embryo begins to take form.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336742;


		
		

		
			
			p.question = "The primitive streak of a bird embryo is the functional equivalent of the _____ in a frog. (<script type=\"text/javascript\">ebook(\'4701\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "blastopore",
				true,
				"Correct. Along the blastopore, future endoderm and mesoderm cells on the surface of the embryo roll over the edge of the lip into the interior of the embryo, a process called involution.");
			
				p.addAnswer(2, "archenteron",
				false,
				"No. The archenteron is a space that will become the future lumen of the digestive tract.");
			
				p.addAnswer(3, "yolk plug",
				false,
				"No. The yolk plug consists of the outer food-laden cells protruding through the blastopore.");
			
				p.addAnswer(4, "blastocoel",
				false,
				"No. The blastocoel is a fluid-filled cavity that forms within the morula.");
			
				p.addAnswer(5, "zona pellucida",
				false,
				"No. The zona pellucida is an extracellular matrix of a mammalian egg.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336743;


		
		

		
			
			p.question = "Which one of the following describes the correct sequence of stages during embryogenesis? (<script type=\"text/javascript\">ebook(\'4701\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "cleavage, morula, blastula, gastrula",
				true,
				"Correct. The zygote initially undergoes cleavage until the blastula stage is reached. Gastrulation is a dramatic rearrangement of the cells of the blastula.");
			
				p.addAnswer(2, "cleavage, gastrula, morula, blastula",
				false,
				"No. The formation of the blastula precedes gastrulation.");
			
				p.addAnswer(3, "blastula, cleavage, morula, gastrula",
				false,
				"No. Cleavage precedes the formation of the blastula.");
			
				p.addAnswer(4, "morula, blastula, cleavage, gastrula",
				false,
				"No. Cleavage precedes the formation of the blastula.");
			
				p.addAnswer(5, "gastrula, cleavage, morula, blastula",
				false,
				"No. Cleavage precedes gastrulation.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336744;


		
		

		
			
			p.question = "The human brain develops from _____. (<script type=\"text/javascript\">ebook(\'4701\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "endoderm",
				false,
				"No. The endoderm does not give rise to the brain.");
			
				p.addAnswer(2, "mesoderm",
				false,
				"No. The mesoderm does not give rise to the brain.");
			
				p.addAnswer(3, "ectoderm",
				true,
				"Correct. Ectoderm forms the skin and nervous system.");
			
				p.addAnswer(4, "both mesoderm and ectoderm",
				false,
				"No. However, the brain is derived from one of these germ layers.");
			
				p.addAnswer(5, "both ectoderm and endoderm",
				false,
				"No. However, the brain is derived from one of these germ layers.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336745;


		
		

		
			
			p.question = "In humans, the skeleton and muscles develop from the embryonic _____. (<script type=\"text/javascript\">ebook(\'4701\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "endoderm",
				false,
				"No. The endoderm gives rise to neither skeleton nor muscle.");
			
				p.addAnswer(2, "ectoderm",
				false,
				"No. The ectoderm gives rise to neither skeleton nor muscle.");
			
				p.addAnswer(3, "mesoderm",
				true,
				"Correct. The notochord, skeletal system, and muscles arise from mesoderm.");
			
				p.addAnswer(4, "haploderm",
				false,
				"No. This is not an embryonic tissue.");
			
				p.addAnswer(5, "endoderm and ectoderm",
				false,
				"No. Neither of these is the major source of the skeleton or muscles.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336746;


		
		

		
			
			p.question = "Which one of the following statements is true? (<script type=\"text/javascript\">ebook(\'4701\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The eggs of placental mammals are quite large, with much more yolk than is found in bird eggs.",
				false,
				"No. The eggs of placental mammals are quite small, with much less yolk than is found in bird eggs.");
			
				p.addAnswer(2, "Cleavage in mammals is meroblastic, whereas cleavage in birds is holoblastic.",
				false,
				"No. Cleavage in mammals is holoblastic, whereas cleavage in birds is meroblastic.");
			
				p.addAnswer(3, "Birds have three extraembryonic membranes, whereas mammals have four.",
				false,
				"No. Birds and mammals have four extraembryonic membranes.");
			
				p.addAnswer(4, "The mammalian zygote undergoes compaction during gastrulation.",
				false,
				"No. The mammalian zygote experiences compaction at the eight-cell stage.");
			
				p.addAnswer(5, "none of the above",
				true,
				"Correct. All of the statements above are false.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336747;


		
		

		
			
			p.question = "Which one of the following extraembryonic membranes functions in gas exchange and encloses a chamber for the deposition of wastes of a bird embryo? (<script type=\"text/javascript\">ebook(\'4701\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "allantois",
				true,
				"Correct. The allantois is a sac for the disposal of metabolic wastes. It also functions in gas exchange.");
			
				p.addAnswer(2, "amnion",
				false,
				"No. The amnion encloses the embryo in a fluid-filled sac.");
			
				p.addAnswer(3, "chorion",
				false,
				"No. The chorion is the outermost of the extraembryonic membranes, and it routinely participates in gas exchange. It is not involved in the storage of nitrogenous waste.");
			
				p.addAnswer(4, "fertilization envelope",
				false,
				"No. The fertilization envelope prevents the entry of additional sperm into a fertilized egg.");
			
				p.addAnswer(5, "yolk sac",
				false,
				"No. The yolk sac stores yolk and thus provides nutritional support to the embryo.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336748;


		
		

		
			
			p.question = "If you wanted to examine the extraembryonic membranes surrounding a lizard or mouse embryo, you would first have to cut through which of the following to see all the others? (<script type=\"text/javascript\">ebook(\'4701\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "yolk sac",
				false,
				"No. The yolk sac is not the outermost membrane.");
			
				p.addAnswer(2, "amnion",
				false,
				"No. The amnion is not the outermost membrane.");
			
				p.addAnswer(3, "endoderm",
				false,
				"No. The endoderm is not an extraembryonic membrane.");
			
				p.addAnswer(4, "allantois",
				false,
				"No. The allantois is not the outermost membrane.");
			
				p.addAnswer(5, "chorion",
				true,
				"Correct. The chorion is the outermost membrane in a mammalian, avian, or reptilian embryo.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336749;


		
		

		
			
			p.question = "In mammals, the allantois is an extraembryonic membrane that is continuous with _____. (<script type=\"text/javascript\">ebook(\'4701\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the trophoblast cells",
				false,
				"No. The trophoblast cells form the outer layer of the blastocyst. They invade the endometrium and form the embryo\'s part of the placenta.");
			
				p.addAnswer(2, "the rudimentary gut",
				true,
				"Correct. The allantois is an extension of the rudimentary gut that becomes part of the umbilical cord and part of the urinary bladder.");
			
				p.addAnswer(3, "the chorion",
				false,
				"No. The chorion is an extraembryonic membrane that comes from trophoblast cells. It eventually produces the chorionic villi, which absorb nutrients and deliver wastes to the mother.");
			
				p.addAnswer(4, "the amnion",
				false,
				"No. The amnion is another extraembryonic membrane. It develops from the inner cell mass of the blastocyst and cradles the developing child in a cushion of amniotic fluid.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336750;


		
		

		
			
			p.question = "Diseases (such as rubella), drugs, alcohol, and radiation can disrupt human embryonic development. These exposures have the most severe effects on the fetus if they occur during the first three months of gestation, because at this time _____. (<script type=\"text/javascript\">ebook(\'4701\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "substances can most easily enter the embryo through the placenta",
				false,
				"No. The membranes that form the placenta retain their basic properties throughout gestation.");
			
				p.addAnswer(2, "the embryo has not yet been implanted in the wall of the uterus",
				false,
				"No. Implantation occurs much earlier than the end of the first trimester.");
			
				p.addAnswer(3, "the mother\'s hormone levels are highest",
				false,
				"No. Some hormones, such as progesterone, are high; others, such as FSH, are low. Maternal hormones have little impact on the developing fetus.");
			
				p.addAnswer(4, "the most drastic and rapid changes are occurring in the embryo",
				true,
				"Correct. During this time, organogenesis is taking place. By the end of the first trimester, all major organ systems will have been formed.");
			
				p.addAnswer(5, "the cells of the embryo are not yet fully activated",
				false,
				"No. Although induction continues to recruit new cells throughout development, the critical activations occur very early during development.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336751;


		
		

		
			
			p.question = "Which one of the following statements is true? (<script type=\"text/javascript\">ebook(\'4702\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Morphogenesis in animals and plants involves the movement of cells.",
				false,
				"No. Morphogenesis in animals, but not plants, involves the movement of cells.");
			
				p.addAnswer(2, "Cells do not migrate individually. Instead, they migrate as a sheet.",
				false,
				"No. Sometimes cells migrate individually, and other times they migrate as a sheet.");
			
				p.addAnswer(3, "During cleavage, gastrulation, and organogenesis, cells do not change shape.",
				false,
				"No. During cleavage, gastrulation, and organogenesis, cells change shape.");
			
				p.addAnswer(4, "During cleavage, gastrulation, and organogenesis, cells do not change position.",
				false,
				"No. During cleavage, gastrulation, and organogenesis, cells change position.");
			
				p.addAnswer(5, "The cytoskeleton drives cell migration.",
				true,
				"Correct. This is a true statement.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336752;


		
		

		
			
			p.question = "Which one of the following statements is true? (<script type=\"text/javascript\">ebook(\'4702\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Fibronectin inhibits cell migration.",
				false,
				"No. Fibronectin promotes cell migration.");
			
				p.addAnswer(2, "The extracellular matrix is not involved in the migration of cells.",
				false,
				"No. The extracellular matrix can direct the migration of cells.");
			
				p.addAnswer(3, "Fibronectin is a glycoprotein that is an important part of the cytoskeleton.",
				false,
				"No. Fibronectin is a glycoprotein found in the extracellular matrix.");
			
				p.addAnswer(4, "Cell adhesion molecules are located inside of cells.",
				false,
				"No. Cell adhesion molecules are located on cell surfaces.");
			
				p.addAnswer(5, "Cell adhesion molecules bind to cell adhesion molecules on other cells.",
				true,
				"Correct. This is a true statement.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336753;


		
		

		
			
			p.question = "Up to the eight-cell stage, the blastomeres of a mouse embryo can each form a complete embryo if isolated. This indicates that _____. (<script type=\"text/javascript\">ebook(\'4703\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "differentiation does not depend on cytoplasmic determinants",
				false,
				"No. All embryos depend on cytoplasmic determinants to some degree, but you are on the right track. These cells have not yet differentiated.");
			
				p.addAnswer(2, "the mouse embryo is strongly polarized",
				false,
				"No. \"Polarization\" refers to the establishment of an axis, with the position along the axis influencing the developmental fate of the cell.");
			
				p.addAnswer(3, "cells of mammalian embryos remain totipotent until at least the eight-cell stage",
				true,
				"Correct.  Until that stage, the isolated blastomeres could each divide and differentiate to produce all the cells in an organism.");
			
				p.addAnswer(4, "cytoplasmic determinants are unevenly distributed during the early cleavage divisions",
				false,
				"No. The uneven distribution of determinants influences the developmental fate of each cell in different directions.");
			
				p.addAnswer(5, "mammalian embryos do not experience the progressive restriction of potency characteristic of other classes",
				false,
				"No. The progressive restriction of potency is a general feature seen in all animals. What varies is the stage in embryonic development when potency is lost or restricted.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336754;


		
		

		
			
			p.question = "In an experiment on eye development, a thin piece of aluminum foil was placed between the bulging wall of the brain and the overlying ectoderm where the eye normally forms. Wherever the foil was placed, the lens failed to develop, because the foil _____. (<script type=\"text/javascript\">ebook(\'4703\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "prevented the inductive contact that normally stimulates the lens to form",
				true,
				"Correct. The foil simply prevented the two tissues from touching, which was enough to prevent the induction of the lens.");
			
				p.addAnswer(2, "changed the gravity in the region",
				false,
				"No. Although gravity can influence development, gravity is not known to influence eye development to this extent. In addition, it is unclear how much effect foil would have on the immediate gravity in this region.");
			
				p.addAnswer(3, "rearranged the cytoplasmic determinants in the adjacent cells",
				false,
				"No. It is unclear whether the foil would have any impact on the arrangement of the cytoplasmic determinants in the adjacent cells. There is a better explanation.");
			
				p.addAnswer(4, "prevented the cortical reaction",
				false,
				"No. The cortical reaction occurs in an egg in response to the penetration of a sperm.");
			
				p.addAnswer(5, "prevented the acrosomal reaction",
				false,
				"No. The acrosomal reaction occurs in a sperm as part of the process of fertilization.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336755;


		
		

		
			
			p.question = "The digits of a developing vertebrate limb respond to molecules that establish an anterior-posterior axis. These molecules originate in _____. (<script type=\"text/javascript\">ebook(\'4703\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the zone of polarizing activity (ZPA)",
				true,
				"Correct. Cells nearest the ZPA give rise to posterior structures, while those farthest away give rise to anterior structures.");
			
				p.addAnswer(2, "a specialized cluster of cells called Sonic hedgehog",
				false,
				"No. \"Sonic hedgehog\" is a term given to a protein growth factor. It is one of the molecules that establish a developmental axis.");
			
				p.addAnswer(3, "the apical epidermal ridge (AER)",
				false,
				"No. The AER establishes the proximal-distal axis for the growing limb.");
			
				p.addAnswer(4, "the primary organizer",
				false,
				"No. The primary organizer occurs much earlier than limb formation. It is related to the development of the notochord.");
			
				p.addAnswer(5, "the gray crescent",
				false,
				"No. The gray crescent is a distinguishable band of cytoplasm seen in a zygote opposite the point of sperm entry.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336756;


		
		

		
			
			p.question = "The two main genetic and cellular mechanisms that underlie differentiation are _____. (<script type=\"text/javascript\">ebook(\'4703\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the uneven distribution of cytoplasmic determinants and induction",
				true,
				"Correct.  These differences set the stage for distinct programs of gene expression, and send particular cells down specialized paths.");
			
				p.addAnswer(2, "the equal distribution of cytoplasmic determinants and induction",
				false,
				"No. The uneven distribution of cytoplasmic determinants and induction are the two main mechanisms of differentiation.");
			
				p.addAnswer(3, "temperature and pressure of the surrounding environment",
				false,
				"No. Although these environmental factors influence development, they are not the mechanisms of differentiation. The uneven distribution of cytoplasmic determinants and induction are the two main mechanisms of differentiation.");
			
				p.addAnswer(4, "gravity and temperature",
				false,
				"No. Although these environmental factors influence development, they are not the mechanisms of differentiation. The uneven distribution of cytoplasmic determinants and induction are the two main mechanisms of differentiation.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the choices above is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

