

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "11: Cell Communication > Practice Test";
	ak.quiz_loc_with_commas = "11: Cell Communication, Practice Test";
	ak.quiz_title = "Practice Test";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 37;
	ak.non_essay_total = 37;
	ak.scored_item_total = 37;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334682;


		
		

		
			
			p.question = "Evidence that cell signaling evolved early in the history of life comes from _____. (<script type=\"text/javascript\">ebook(\'1101\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "comparative studies of mitochondrial DNA",
				false,
				"No. This would provide genetic evidence of the historical relationships among organisms.");
			
				p.addAnswer(2, "comparative studies of ribosomal RNA",
				false,
				"No. This would provide genetic evidence of the historical relationships among organisms.");
			
				p.addAnswer(3, "the fossil record",
				false,
				"No. Cell-signaling pathways are not preserved in the fossil record.");
			
				p.addAnswer(4, "the study of protein receptors embedded in the nuclear membrane",
				false,
				"No. Because receptors for signaling molecules are present in plasma membrane or in the cytoplasm, studying receptors on the nuclear envelope would not provide any information concerning the evolution of signaling mechanisms.");
			
				p.addAnswer(5, "the similarity of the mechanisms in organisms that have a very distant common ancestor",
				true,
				"Correct. The molecular details of signal transduction in yeast and mammals are strikingly similar, suggesting that early versions of the cell-signaling mechanisms used today evolved well before the first multicellular creatures appeared on Earth.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334683;


		
		

		
			
			p.question = "When a platelet contacts a damaged blood vessel, it is stimulated to release thromboxane A<sub>2</sub>. Thromboxane A<sub>2</sub> in turn stimulates vascular spasm and attracts additional platelets to the injured site. In this example thromboxane A<sub>2</sub> is acting as a _____. (<script type=\"text/javascript\">ebook(\'1101\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "neurotransmitter",
				false,
				"No. Thromboxane is not a neurotransmitter.");
			
				p.addAnswer(2, "transcription factor",
				false,
				"No. mRNA synthesis is being neither promoted nor inhibited.");
			
				p.addAnswer(3, "protein kinase",
				false,
				"No. A protein kinase transfers a phosphate group from ATP to a protein.");
			
				p.addAnswer(4, "local regulator",
				true,
				"Correct. A transmitting cell can secrete molecules of a local regulator, a substance that influences cells in the vicinity.");
			
				p.addAnswer(5, "G protein",
				false,
				"No. Thromboxane A<sub>2</sub> is not a G protein.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334684;


		
		

		
			
			p.question = "Early work on signal transduction and glycogen depolymerization by Sutherland indicated that _____. (<script type=\"text/javascript\">ebook(\'1101\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the signal molecule combined directly with a cytosolic enzyme to form an active quaternary structure",
				false,
				"No. In cell extract experiments, the signal molecule could not activate the enzyme.");
			
				p.addAnswer(2, "the signal molecule worked equally well with intact or disrupted cells",
				false,
				"No. When the experiment was performed with disrupted cells, no response was observed.");
			
				p.addAnswer(3, "the signal molecule did not interact directly with the cytosolic enzyme, but required an intact plasma membrane before the enzyme could be activated",
				true,
				"Correct. Enzyme activation could proceed only when the plasma membrane was intact.");
			
				p.addAnswer(4, "the cell-signaling pathway involves two separate steps: transduction and response",
				false,
				"No. The cell-signaling pathway has three steps: reception, transduction, and response.");
			
				p.addAnswer(5, "epinephrine is involved in response to stress",
				false,
				"No. While true, this choice does not address the question.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334685;


		
		

		
			
			p.question = "Certain yeast cells secrete a molecule called the &alpha; factor. The purpose of this molecule is to _____. (<script type=\"text/javascript\">ebook(\'1101\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "kill other yeast cells nearby, which may be competing for access to food",
				false,
				"No. The &alpha; factor molecule is a signal molecule.");
			
				p.addAnswer(2, "kill bacteria nearby, which may be competing for access to food",
				false,
				"No. The observation of an antibacterial compound secreted by fungi led to the discovery of antibiotics.");
			
				p.addAnswer(3, "stimulate an <b>a</b> yeast cell to grow toward the &alpha; cell",
				true,
				"Correct. The &alpha; factor molecule is a signal molecule that eventually leads to the fusion of opposite yeast mating types.");
			
				p.addAnswer(4, "attract other yeast cells of the same mating type to assemble",
				false,
				"No. The &alpha; factor is a signal molecule that causes yeast cells of the opposite mating <b>a</b> to grow toward &alpha; cells.");
			
				p.addAnswer(5, "enzymatically process food into a form that can be easily absorbed",
				false,
				"No. The &alpha; factor molecule is a signal molecule.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334686;


		
		

		
			
			p.question = "Cells use different signaling strategies to achieve different goals. In hormonal signaling _____. (<script type=\"text/javascript\">ebook(\'1101\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "numerous cells can receive and respond to a signal produced in their vicinity",
				false,
				"No. The type of signal described is called a local regulator.");
			
				p.addAnswer(2, "the signal can be directed to a very specific target because a narrow space separates the target cell from the transmitting cell",
				false,
				"No. This type of signal is common in the nervous system, where cells are separated by a synapse.");
			
				p.addAnswer(3, "a concentration gradient between the signaling cell and its target cells is established, causing cells along the gradient to respond in different ways",
				false,
				"No. Hormonal recognition requires a specific receptor, which is activated when the appropriate hormone is present.");
			
				p.addAnswer(4, "specialized cells release hormone molecules into the circulatory system, permitting distant cells to be affected",
				true,
				"Correct. Endocrine cells release molecules into the circulatory system, permitting their rapid distribution throughout the body.");
			
				p.addAnswer(5, "special molecules are passed through cell junctions",
				false,
				"No. Although this type of communication occurs, the molecules passed in this fashion are not hormones.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334687;


		
		

		
			
			p.question = "Testosterone and estrogen are lipid-soluble signal molecules that cross the plasma membrane by simple diffusion. If these molecules can enter all cells, why do only specific cells respond to their presence? (<script type=\"text/javascript\">ebook(\'1102\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Nontarget cells possess enzymes that immediately degrade the molecules as they enter the cell.",
				false,
				"No. There is a simpler explanation.");
			
				p.addAnswer(2, "Nontarget cells lack the inactive enzymes that the signal molecules activate.",
				false,
				"No. There is a simpler explanation.");
			
				p.addAnswer(3, "Nontarget cells lack the intracellular receptors that, when activated by the signal molecule, can interact with genes in the cell\'s nucleus.",
				true,
				"Correct. Nonpolar signal molecules easily enter cells, but only those cells with functional intracellular receptors respond.");
			
				p.addAnswer(4, "The signal molecules diffuse from the cell before an effective concentration can be achieved.",
				false,
				"No. There is a simpler explanation.");
			
				p.addAnswer(5, "In nontarget cells, these signal molecules cross the membranes of the endoplasmic reticulum and are captured by vesicles.",
				false,
				"No. There is a simpler explanation.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334688;


		
		

		
			
			p.question = "Steroid hormones can enter a cell by simple diffusion. Therefore steroids _____. (<script type=\"text/javascript\">ebook(\'1102\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "are not an example of signaling molecules",
				false,
				"No. Steroid hormones can trigger a specific cellular response.");
			
				p.addAnswer(2, "do not bind to receptors",
				false,
				"No. Steroid hormone receptors are involved.");
			
				p.addAnswer(3, "directly bind to DNA",
				false,
				"No. Steroid hormones do not directly bind to DNA.");
			
				p.addAnswer(4, "do not initiate cell signaling by interacting with a receptor in the plasma membrane.",
				true,
				"Correct. Steroid hormones, because of their hydrophobic characteristics, readily cross cell membranes and bind to receptors in the cytoplasm, activating the receptor. The active receptor protein then binds to and turns off genes in the nucleus that control the response. Thus, the receptor carries out the complete transduction of the signal.");
			
				p.addAnswer(5, "act by phosphorylating DNA",
				false,
				"No. Steroid hormones do not phosphorylate DNA.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334689;


		
		

		
			
			p.question = "A small molecule that specifically binds to a larger molecule is called a(n) _____. (<script type=\"text/javascript\">ebook(\'1102\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "&alpha; protein",
				false,
				"No. &alpha; factor plays a role in yeast reproduction.");
			
				p.addAnswer(2, "ligand",
				true,
				"Correct. A ligand is a small molecule that specifically binds to a larger one.");
			
				p.addAnswer(3, "protein kinase",
				false,
				"No. Protein kinase uses a phosphate from ATP to phosphorylate a protein.");
			
				p.addAnswer(4, "competitive inhibitor",
				false,
				"No. Not necessarily. Think in terms of molecules that bind to receptors.");
			
				p.addAnswer(5, "DAG",
				false,
				"No. DAG (diacylglycerol) is a second messenger.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334690;


		
		

		
			
			p.question = "Receptors for signal molecules _____. (<script type=\"text/javascript\">ebook(\'1102\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "all work via protein kinases",
				false,
				"No. For example, G-protein-linked receptors do not act via protein kinases.");
			
				p.addAnswer(2, "are never found in the nucleus of a cell",
				false,
				"No. After steroids bind to their receptors in the cytoplasm, the activated hormone-receptor complex is transported into the nucleus where it regulates gene expression.");
			
				p.addAnswer(3, "can be found as part of the plasma membrane or found within the cytoplasm",
				true,
				"Correct. Not all signal receptors are membrane proteins. Some are located in the cytoplasm of target cells.");
			
				p.addAnswer(4, "all work by opening ion channels",
				false,
				"No. Ion-channel receptors are not the only kind of receptor that permits or restricts the passage of ions across membranes.");
			
				p.addAnswer(5, "are only found associated with the plasma membrane",
				false,
				"No. This is not the only location of signal receptors.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334691;


		
		

		
			
			p.question = "Testosterone does not affect all cells of the body because _____. (<script type=\"text/javascript\">ebook(\'1102\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "testosterone cannot cross the plasma membrane",
				false,
				"No. Testosterone is hydrophobic and can cross the plasma membrane by simple diffusion.");
			
				p.addAnswer(2, "not all cells in the body have membrane receptors for testosterone",
				false,
				"No. You are on the right track, but go back and review steroid hormone receptors.");
			
				p.addAnswer(3, "it is a local regulator",
				false,
				"No. Testosterone is produced in the gonads and adrenal glands, but exerts its effects at various other parts of the body.");
			
				p.addAnswer(4, "it affects only cells that have ion-channel receptors",
				false,
				"No. Testosterone does not work via ion-channel receptors.");
			
				p.addAnswer(5, "not all cells have cytoplasmic receptors for testosterone",
				true,
				"Correct. Steroid hormones, such as testosterone, readily enter cells all over the body, but they stimulate a response only in target cells&#151;those with receptor molecules in the cytoplasm.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334692;


		
		

		
			
			p.question = "G-protein-linked receptors _____, whereas receptor tyrosine kinases _____. (<script type=\"text/javascript\">ebook(\'1102\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "act by phosphorylating a protein; open an ion channel when bound to a signal molecule",
				false,
				"No. G proteins do not have kinase activity. Ligand-gated ion channels are the only type of receptor that allows ions to cross a membrane directly in response to a signal.");
			
				p.addAnswer(2, "are transmembrane proteins; are found only on the cytoplasmic side of the plasma membrane",
				false,
				"No. Tyrosine kinase receptors are transmembrane proteins.");
			
				p.addAnswer(3, "are not enzymes; have enzymatic function",
				true,
				"Correct. A G protein functions as a switch that is on or off depending on whether it is attached to GTP or GDP. Receptor tyrosine kinases are in the membrane that attach phosphates to protein tyrosines.");
			
				p.addAnswer(4, "form a dimer when activated; catalyze the transfer of a phosphate group from ATP to an amino acid",
				false,
				"No. G-protein-linked receptors do not form dimers.");
			
				p.addAnswer(5, "phosphorylate the amino acid guanine; phosphorylate the amino acid threonine",
				false,
				"No. G proteins do not phosphorylate. Tyrosine kinases only add phosphate groups to tyrosines.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334693;


		
		

		
			
			p.question = "Which of the following is activated when the binding of single molecules causes it to form a dimer? (<script type=\"text/javascript\">ebook(\'1102\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "ion-channel receptors",
				false,
				"No. Ion-channel receptors open and close in response to a signal. They do not form dimers.");
			
				p.addAnswer(2, "protein phosphatase receptors",
				false,
				"No. Protein phosphatases reverse the effects of protein kinases.");
			
				p.addAnswer(3, "G-protein-linked receptors",
				false,
				"No. These receptors do not form dimers. G proteins are activated in response to the signal molecule binding to the receptor.");
			
				p.addAnswer(4, "adenylyl cyclase receptors",
				false,
				"No. Adenylyl cyclase is an enzyme that converts ATP to cAMP.");
			
				p.addAnswer(5, "tyrosine-kinase receptors",
				true,
				"Correct. Ligand binding causes two tyrosine-kinase receptor polypeptides to aggregate, forming a dimer.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334694;


		
		

		
			
			p.question = "The binding of a signal molecule to a ligand-gated ion channel _____. (<script type=\"text/javascript\">ebook(\'1102\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "phosphorylates an amino acid",
				false,
				"No. Kinases phosphorylate.");
			
				p.addAnswer(2, "results in the formation of a dimer",
				false,
				"No. Dimers are formed when ligands bind to tyrosinase-kinase receptors.");
			
				p.addAnswer(3, "promotes the binding of a steroid hormone to its receptor in the cytoplasm",
				false,
				"No. Ligand-gated ion channels are found as integral membrane proteins in the plasma membrane.");
			
				p.addAnswer(4, "alters the expression of genes, especially in neurons",
				false,
				"No. In neurons, ligand-gated ion channels are important for the propagation of signals from one cell to the next.");
			
				p.addAnswer(5, "affects the membrane potential",
				true,
				"Correct. Ligand-gated ion channels are protein pores in the plasma membrane that open or close in response to a chemical signal, allowing or blocking the flow of specific ions.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334695;


		
		

		
			
			p.question = "Nitric oxide is unusual among animal signal molecules in that it _____. (<script type=\"text/javascript\">ebook(\'1102\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "enters the cell via a protein channel",
				false,
				"No. Nitric oxide does not enter the cell via a protein channel.");
			
				p.addAnswer(2, "acts by directly binding to DNA",
				false,
				"No. Nitric oxide activates an enzyme that produces a second messenger (cGMP).");
			
				p.addAnswer(3, "binds to membrane receptors and cytoplasm receptors",
				false,
				"No. Nitric oxide diffuses into cells.");
			
				p.addAnswer(4, "is a gas",
				true,
				"Correct. Chemical messengers with intracellular receptors include the steroid hormones and even the small gaseous molecule nitric oxide.");
			
				p.addAnswer(5, "activates proteins by removing phosphate",
				false,
				"No. Nitric oxide is not a phosphatase.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334696;


		
		

		
			
			p.question = "A G protein is active when _____. (<script type=\"text/javascript\">ebook(\'1102\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "GDP replaces GTP",
				false,
				"No. When the GTP that is bound to the active G protein is hydrolyzed to form GDP, the G protein is inactivated.");
			
				p.addAnswer(2, "it is bound by its ligand and transported to the nucleus",
				false,
				"No. This describes the activation of a steroid hormone receptor.");
			
				p.addAnswer(3, "GTP is bound to it",
				true,
				"Correct. When GDP is bound, the G protein is inactive; when GTP is bound, it is active.");
			
				p.addAnswer(4, "it is phosphorylated by protein kinase",
				false,
				"No. G proteins are not activated by phosphorylation.");
			
				p.addAnswer(5, "Ca<sup>2+</sup> binds to a G-protein-linked receptor",
				false,
				"No. Calcium ions are second messengers. They do not interact with G proteins.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334697;


		
		

		
			
			p.question = "If a modified form of GTP that cannot be enzymatically converted to GDP were added to a culture of cells, the likely result would be _____. (<script type=\"text/javascript\">ebook(\'1102\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the inactivation of ligand-gated ion channels",
				false,
				"No. GTP is not involved in the regulation of ligand-gated ion channels.");
			
				p.addAnswer(2, "the inactivation of G-protein-linked signaling pathways",
				false,
				"No. You should review the mechanism of G-protein activation.");
			
				p.addAnswer(3, "that the activated G proteins would remain locked in the \"on\" position, transmitting signal even in the absence of a signaling molecule",
				true,
				"Correct. GTP-bound G proteins remain active until the GTP is converted to GDP. If the GTP cannot be hydrolyzed to GDP, the G protein remains active.");
			
				p.addAnswer(4, "the inhibition of pathways stimulated by tyrosine-kinase receptors",
				false,
				"No. GTP is not involved in the signaling mediated by receptor tyrosine kinases.");
			
				p.addAnswer(5, "receptor tyrosine kinases would be stimulated by the additional phosphate groups present in the modified GTP",
				false,
				"No. GTP is not involved in the signaling mediated by receptor tyrosine kinases.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334698;


		
		

		
			
			p.question = "What event would activate a G protein? (<script type=\"text/javascript\">ebook(\'1102\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "hydrolysis of GTP to GDP",
				false,
				"No, just the opposite is true. Activated G proteins hydrolyze bound GTP to GDP, which terminates the activation.");
			
				p.addAnswer(2, "hydrolysis of GDP to GTP",
				false,
				"No. GTP cannot be produced by the hydrolysis of GDP.");
			
				p.addAnswer(3, "phosphorylation of GDP to GTP",
				false,
				"No. However, the conversion of GDP to GTP would require phosphorylation.");
			
				p.addAnswer(4, "replacement of GDP with GTP",
				true,
				"Correct. Inactive G proteins are bound to GDP. The activated receptor replaces the GDP with GTP, thereby activating the G protein.");
			
				p.addAnswer(5, "phosphorylation of GTP to GDP",
				false,
				"No. The phosphorylation of GTP would not produce GDP.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334699;


		
		

		
			
			p.question = "The cellular response of a signal pathway that terminates at a transcription factor would be _____. (<script type=\"text/javascript\">ebook(\'1102\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the synthesis of mRNA",
				true,
				"Correct. Transcription factors are proteins that regulate the transcription of DNA into mRNA.");
			
				p.addAnswer(2, "the activation of an inactive enzyme",
				false,
				"No. However, some signal pathways result in enzyme activation.");
			
				p.addAnswer(3, "alteration of the cytoskeleton",
				false,
				"No. However, some signal pathways result in cytoskeletal reorganization.");
			
				p.addAnswer(4, "a change in the chemical composition of the cytosolic environment",
				false,
				"No. However, some signal pathways open or close ion channels.");
			
				p.addAnswer(5, "the activation of a metabolic pathway",
				false,
				"No. However, some signal pathways may initiate a metabolic process.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334700;


		
		

		
			
			p.question = "Cholera develops when the bacterial toxin _____. (<script type=\"text/javascript\">ebook(\'1103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "inhibits the enzyme that normally breaks down cAMP",
				false,
				"No. However, abnormally high levels of cAMP are characteristic of cholera.");
			
				p.addAnswer(2, "prevents G-protein inactivation, which leads to the continuous production of cAMP",
				true,
				"Correct. The activated G protein continuously stimulates adenylyl cyclase to make cAMP, which causes the intestinal cells to secrete large amounts of water and salts into the intestines.");
			
				p.addAnswer(3, "inhibits adenylyl cyclase, preventing the cell from producing cAMP",
				false,
				"No. Cholera results from too much cAMP, not too little.");
			
				p.addAnswer(4, "blocks the receptor site for cAMP",
				false,
				"No. Cholera results from a process that produces too much cAMP. If a cAMP receptor site were blocked, the cell would behave as if there were too little cAMP.");
			
				p.addAnswer(5, "phosphorylates the cAMP, producing ADP",
				false,
				"No. cAMP is a second messenger. It is not phosphorylated.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334701;


		
		

		
			
			p.question = "What did Sutherland discover about glycogen metabolism in liver cells? (<script type=\"text/javascript\">ebook(\'1103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Glucagon breaks down glycogen to glucose in liver cells.",
				false,
				"No. He found that epinephrine triggers the breakdown of glycogen into glucose.");
			
				p.addAnswer(2, "The hormone that breaks down glycogen into glucose enters the liver cell.",
				false,
				"No. He found that the hormone epinephrine never enters the cell where glycogen is metabolized to glucose.");
			
				p.addAnswer(3, "The hormone epinephrine binds to a specific receptor on the plasma membrane of the liver cell.",
				true,
				"Correct. Epinephrine activates the receptor to carry out the breakdown of glycogen into glucose.");
			
				p.addAnswer(4, "Glucose is produced from glycogen when epinephrine binds to a cytoplasmic protein.",
				false,
				"No. Glucose was produced only when whole cells with intact plasma membranes were used, which indicated that epinephrine does not interact directly with a cytoplasmic protein.");
			
				p.addAnswer(5, "A cytoplasmic receptor triggers the signal transduction pathway that produces glucose from glycogen.",
				false,
				"No. Glucose was produced only when whole cells with intact plasma membranes were used, which indicated that epinephrine does not interact directly with a cytoplasmic protein.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334702;


		
		

		
			
			p.question = "The general name for an enzyme that transfers phosphate groups from ATP to a protein is _____. (<script type=\"text/javascript\">ebook(\'1103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "protein dehydrogenase",
				false,
				"No. Dehydrogenases are involved with redox reactions. They participate in the movement of electrons and hydrogen.");
			
				p.addAnswer(2, "protein phosphatase",
				false,
				"No. Protein phosphatases catalyze the removal of a phosphate group from another protein.");
			
				p.addAnswer(3, "protein kinase",
				true,
				"Correct. Most protein kinases attach phosphate groups to proteins different from themselves. However, some protein kinases phosphorylate other protein kinases of the same type.");
			
				p.addAnswer(4, "peptidase",
				false,
				"No. Peptidases are enzymes that hydrolyze peptide bonds.");
			
				p.addAnswer(5, "protein cyclase",
				false,
				"No. A cyclase is an enzyme, such as adenylyl cyclase, that converts its substrate into a ring structure.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334703;


		
		

		
			
			p.question = "Phosphorylation _____. (<script type=\"text/javascript\">ebook(\'1103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "always inactivates a protein",
				false,
				"No. Sometimes, but not always.");
			
				p.addAnswer(2, "activates G-protein-linked receptors",
				false,
				"No. G-protein-linked receptors are not activated by phosphorylation.");
			
				p.addAnswer(3, "can either activate or inactivate a protein",
				true,
				"Correct. The addition of a phosphate often activates a protein, although in other cases phosphorylation decreases the activity of the protein.");
			
				p.addAnswer(4, "is accomplished by protein phosphatases",
				false,
				"No. Protein phosphatases remove phosphate groups from proteins.");
			
				p.addAnswer(5, "always activates a protein",
				false,
				"No. This is often the case, but not always.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334704;


		
		

		
			
			p.question = "The source of phosphate for a phosphorylation cascade is _____. (<script type=\"text/javascript\">ebook(\'1103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "cAMP",
				false,
				"No. cAMP is a second messenger. It does not donate phosphate groups.");
			
				p.addAnswer(2, "ATP",
				true,
				"Correct. The general name for an enzyme that transfers phosphate groups from ATP to a protein is a protein kinase.");
			
				p.addAnswer(3, "protein kinase",
				false,
				"No. Protein kinases transfer phosphate groups from one molecule to another.");
			
				p.addAnswer(4, "GTP",
				false,
				"No. GTP is important for the activation of G proteins in signal transduction pathways.");
			
				p.addAnswer(5, "protein phosphatase",
				false,
				"No. Protein phosphatases remove phosphate groups from proteins.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334705;


		
		

		
			
			p.question = "Second messengers tend to be water-soluble and small. This accounts for their ability to _____. (<script type=\"text/javascript\">ebook(\'1103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "rapidly cross the plasma membrane",
				false,
				"No. Even though they are small, second messengers cannot penetrate the hydrophobic core of the plasma membrane.");
			
				p.addAnswer(2, "rapidly move throughout the cell by diffusion",
				true,
				"Correct. Diffusion permits a wide dispersal of the molecules from the site of their entry or production at a membrane.");
			
				p.addAnswer(3, "pass quickly from cell to cell",
				false,
				"No. This would imply that they were able to cross membranes freely, a difficult task for a polar molecule or ion.");
			
				p.addAnswer(4, "move from substrate to substrate during a phosphorylation cascade",
				false,
				"No. During a cascade, each substrate becomes the activator for the next substrate. A second messenger would be needed to start the process, but would then participate no further.");
			
				p.addAnswer(5, "cross the nuclear membrane and interact with DNA",
				false,
				"No. Second messengers do not interact with DNA.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334706;


		
		

		
			
			p.question = "cAMP usually directly activates _____. (<script type=\"text/javascript\">ebook(\'1103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "phosphodiesterase",
				false,
				"No. Phosphodiesterase inactivates cAMP.");
			
				p.addAnswer(2, "receptor tyrosine kinases",
				false,
				"No. Receptor tyrosine kinases reside as integral membrane proteins in the plasma membrane.");
			
				p.addAnswer(3, "G proteins",
				false,
				"No. cAMP is produced as a result of G protein activation.");
			
				p.addAnswer(4, "adenylyl cyclase",
				false,
				"No. Adenylyl cyclase converts ATP to cAMP.");
			
				p.addAnswer(5, "protein kinase A",
				true,
				"Correct. The relay molecule immediately after cAMP in a signaling cascade is usually protein kinase A, a serine/threonine kinase, which is activated by cAMP.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334707;


		
		

		
			
			p.question = "In a typical cell, calcium ions _____. (<script type=\"text/javascript\">ebook(\'1103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "are far more abundant in the cytoplasm than the blood and other extracellular fluid",
				false,
				"No. Actually, the cytosolic concentrations of calcium are generally very low.");
			
				p.addAnswer(2, "are rapidly transported into the endoplasmic reticulum in response to G-protein-mediated signals",
				false,
				"No. In fact, calcium is often released from the endoplasmic reticulum in response to G-protein-mediated signals.");
			
				p.addAnswer(3, "are often concentrated within the endoplasmic reticulum",
				true,
				"Correct. Low intracellular concentrations are achieved by transporting calcium across the plasma membrane or into storage sites within the ER.");
			
				p.addAnswer(4, "are not very widely used as second messengers",
				false,
				"No. Actually, just the opposite is true.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. Only one of the choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334708;


		
		

		
			
			p.question = "During the transduction of a signal, one molecule or ion may be closely associated with the activity of another. Select the pair that is correctly combined. (<script type=\"text/javascript\">ebook(\'1103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "calcium, IP<sub>3</sub>",
				false,
				"No. Although this is correct, there is a better choice.");
			
				p.addAnswer(2, "cAMP, adenylyl cyclase",
				false,
				"No. Although this is correct, there is a better choice.");
			
				p.addAnswer(3, "cAMP, protein kinase A",
				false,
				"No. Although this is correct, there is a better choice.");
			
				p.addAnswer(4, "DAG, IP<sub>3</sub>",
				false,
				"No. Although this is correct, there is a better choice.");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct. Each of the pairs above is properly associated.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334709;


		
		

		
			
			p.question = "A difference between the mechanisms of cAMP and Ca<sup>2+</sup> in signal transduction is that cAMP _____ and Ca<sup>2+</sup> _____. (<script type=\"text/javascript\">ebook(\'1103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "is always present at high levels in the cytosol; is present at low levels in the absence of a signal",
				false,
				"No. cAMP is present only when adenylyl cyclase has been activated by an appropriate signal.");
			
				p.addAnswer(2, "is synthesized by an enzyme in response to a signal; is released from intracellular stores",
				true,
				"Correct. Adenylyl cyclase catalyzes the conversion of ATP to cAMP. Calcium released from the endoplasmic reticulum increases the cytosolic concentration of calcium and causes many responses in animal cells, including muscle-cell contraction.");
			
				p.addAnswer(3, "is stored in the endoplasmic reticulum; is never stored in the cell",
				false,
				"No. cAMP is not stored in the ER. Ca<sup>2+</sup> is stored in the ER.");
			
				p.addAnswer(4, "is tyrosine-kinase-receptor linked; is G-protein-receptor linked",
				false,
				"No. Calcium and cAMP are both second messengers involved in G-protein-mediated signaling pathways.");
			
				p.addAnswer(5, "enters the cell via a transmembrane protein channel; enters the cell by diffusing across the plasma membrane",
				false,
				"No. cAMP does not enter the cell via a transmembrane protein channel. It is synthesized by adenylyl cyclase in the cytoplasm. Calcium enters the cell through specific channels and is stored in the endoplasmic reticulum.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334710;


		
		

		
			
			p.question = "IP<sub>3</sub> (inositol trisphosphate) is produced as a result of _____. (<script type=\"text/javascript\">ebook(\'1103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "protein kinase A activation",
				false,
				"No. Protein kinase A phosphorylates proteins.");
			
				p.addAnswer(2, "Ca<sup>2+</sup>",
				false,
				"No. Calcium acts as a second messenger.");
			
				p.addAnswer(3, "the cleavage of a certain kind of phospholipid in the plasma membrane.",
				true,
				"Correct. Phospholipase C cleaves a special membrane phospholipid, PIP<sub>2</sub>, producing diacylglycerol and inositol trisphosphate.");
			
				p.addAnswer(4, "DAG",
				false,
				"No. However, the molecule from which IP<sub>3</sub> is derived is also involved in the formation of DAG.");
			
				p.addAnswer(5, "phospholipase C",
				false,
				"No. However, this enzyme plays a role in the formation of both IP<sub>3</sub> and DAG.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334711;


		
		

		
			
			p.question = "IP<sub>3</sub> (inositol trisphosphate) acts by _____. (<script type=\"text/javascript\">ebook(\'1103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "activating cAMP",
				false,
				"No. Review the section on second messengers.");
			
				p.addAnswer(2, "phosphorylating signal receptors",
				false,
				"No. IP<sub>3</sub> is not a kinase.");
			
				p.addAnswer(3, "opening Ca<sup>2+</sup> channels",
				true,
				"Correct. IP<sub>3</sub> stimulates the release of calcium from the endoplasmic reticulum.");
			
				p.addAnswer(4, "activating PIP<sub>2</sub>",
				false,
				"No. Phospholipase C cleaves PIP<sub>2</sub> into IP<sub>3</sub> and DAG.");
			
				p.addAnswer(5, "activating DAG",
				false,
				"No. IP<sub>3</sub> and DAG are both products of the cleavage of PIP<sub>2</sub> by phospholipase C. Neither activates the other.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334712;


		
		

		
			
			p.question = "Which of the following is <b>not</b> a potential source of Ca<sup>2+</sup> for the cytosol? (<script type=\"text/javascript\">ebook(\'1103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "blood",
				false,
				"No. Blood transports calcium.");
			
				p.addAnswer(2, "extracellular fluid",
				false,
				"No. Calcium is found in the extracellular fluid.");
			
				p.addAnswer(3, "mitochondria",
				false,
				"No. Mitochondria can be a source of Ca<sup>2+</sup>.");
			
				p.addAnswer(4, "endoplasmic reticulum",
				false,
				"No. The endoplasmic reticulum does store Ca<sup>2+</sup>.");
			
				p.addAnswer(5, "lysosomes",
				true,
				"Correct. Lysosomes are not a potential source of Ca<sup>2+</sup> for the cytosol. The level of calcium in the blood and extracellular fluid of an animal often exceeds that in the cytosol by more than 10,000 times. Calcium ions are actively transported out of the cell and are actively imported from the cytosol into the endoplasmic reticulum.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334713;


		
		

		
			
			p.question = "In eukaryotic cells, which one of the following is a second messenger that is produced as a response to an external signal such as a hormone? (<script type=\"text/javascript\">ebook(\'1103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "glycogen",
				false,
				"No. In animals, glycogen is the storage form of carbohydrate. It is not a second messenger.");
			
				p.addAnswer(2, "cyclic AMP",
				true,
				"Correct. The first messenger, the hormone, causes a membrane enzyme to synthesize cAMP, which transmits the signal to the cytoplasm.");
			
				p.addAnswer(3, "tRNA",
				false,
				"No. tRNA is important for the synthesis of proteins. It is not a second messenger.");
			
				p.addAnswer(4, "epinephrine",
				false,
				"No. Epinephrine is a hormone. It is not a second messenger.");
			
				p.addAnswer(5, "glucose",
				false,
				"No. Glucose is a sugar that cells utilize as a source of energy. It is not a second messenger.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334714;


		
		

		
			
			p.question = "In the inherited disorder Wiskott-Aldrich syndrome, _____. (<script type=\"text/javascript\">ebook(\'1104\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "muscle cells lack the appropriate membrane receptor",
				false,
				"No. However, a missing or defective receptor would certainly result in a disease process.");
			
				p.addAnswer(2, "a multifunctional relay protein involved with the proliferation of immune cells is defective",
				true,
				"Correct. The defective protein is thought to represent an important intersection point for a complex transduction network.");
			
				p.addAnswer(3, "nerve cells lack the ability to produce cAMP",
				false,
				"No. This disorder is not related to the production of cAMP.");
			
				p.addAnswer(4, "G proteins are unable to phosphorylate GDP",
				false,
				"No. G proteins are not involved with the disorder, and G proteins normally hydrolyze GTP to terminate their activation rather than phosphorylating GDP.");
			
				p.addAnswer(5, "the endoplasmic reticulum is unable to store calcium",
				false,
				"No. This disorder is not related to calcium concentrations within the cell.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334715;


		
		

		
			
			p.question = "In liver cells, epinephrine stimulates the breakdown of glycogen. As the signal-transduction pathway progresses, _____. (<script type=\"text/javascript\">ebook(\'1104\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the signal is reduced",
				false,
				"No. Many cAMPs are formed; thus, the signal is not reduced.");
			
				p.addAnswer(2, "the number of molecules involved decreases",
				false,
				"No. Many cAMPs are formed; thus, the number of molecules does not decrease.");
			
				p.addAnswer(3, "the number of molecules involved remains constant",
				false,
				"No. Many cAMPs are formed; thus, the number of molecules involved does not remain constant.");
			
				p.addAnswer(4, "the signal is amplified",
				true,
				"Correct. The signal transduction pathway from epinephrine to the breakdown of glycogen amplifies the hormonal signal because the receptor protein can activate many molecules of G protein and so on.");
			
				p.addAnswer(5, "glycogenesis is stimulated",
				false,
				"No. This signal transduction pathway stimulates glycogenolysis (the catabolic conversion of glycogen into glucose), which is the opposite of glycogenesis.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334716;


		
		

		
			
			p.question = "Cells of the gastrointestinal (GI) tract and cells of the heart respond differently to epinephrine because _____. (<script type=\"text/javascript\">ebook(\'1104\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "there are differences in the proteins found in the two types of cells",
				true,
				"Correct. The specific proteins a cell possesses determine which signal molecules it responds to and the nature of that response.");
			
				p.addAnswer(2, "the GI tract does not have epinephrine receptors",
				false,
				"No. GI tract cells have epinephrine receptors.");
			
				p.addAnswer(3, "in cells of the GI tract epinephrine operates via a cytosolic receptor, whereas in cells of the heart epinephrine acts via a plasma membrane receptor",
				false,
				"No. Epinephrine works via a plasma membrane receptor regardless of cell type.");
			
				p.addAnswer(4, "the concentration of Ca<sup>2+</sup> is lower in the cytosol of GI-tract cells than in the cytosol of heart cells",
				false,
				"No. Calcium is not a second messenger in epinephrine\'s signal transduction pathway.");
			
				p.addAnswer(5, "cells of the GI tract lack cAMP",
				false,
				"No. Cells in the GI tract do not lack cAMP.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334717;


		
		

		
			
			p.question = "Apoptosis _____. (<script type=\"text/javascript\">ebook(\'1105\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "typically involves only a single signaling pathway",
				false,
				"No.<b> </b>Apoptosis<b> </b>typically involves multiple signaling pathways.");
			
				p.addAnswer(2, "occurs randomly during embryonic development of a nematode",
				false,
				"No. Apoptosis occurs at defined times during the embryonic development of a nematode.");
			
				p.addAnswer(3, "is only triggered by signals from outside the cell",
				false,
				"No. Apoptosis can be triggered by signals from outside or inside the cell.");
			
				p.addAnswer(4, "is essential for normal development of the nervous system",
				true,
				"Correct. Apoptosis protects neighboring cells by controlling cell death.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. Only one of the choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334718;


		
		

		
			
			p.question = "Which of the following statements are correct? (<script type=\"text/javascript\">ebook(\'1105\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Some apoptotic signals originate from outside a cell.",
				false,
				"No. Although this is correct, it is not the best choice.");
			
				p.addAnswer(2, "Some apoptotic signals come from the nucleus, when DNA has suffered irreparable damage.",
				false,
				"No.<b> </b>Although this is correct, it is not the best choice.");
			
				p.addAnswer(3, "Some apoptotic signals come from the endoplasmic reticulum when excessive protein misfolding occurs.",
				false,
				"No. Although this is correct, it is not the best choice.");
			
				p.addAnswer(4, "Some apoptotic signals come from mitochondria.",
				false,
				"No. Although this is correct, it is not the best choice.");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct. All of the choices are correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

