

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "GraphIt! Quiz > GraphIt! Quiz > Municipal Solid Waste Trends in the U.S.";
	ak.quiz_loc_with_commas = "GraphIt! Quiz, GraphIt! Quiz, Municipal Solid Waste Trends in the U.S.";
	ak.quiz_title = "Municipal Solid Waste Trends in the U.S.";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 7;
	ak.non_essay_total = 7;
	ak.scored_item_total = 7;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337478;


		
		

		
			
			p.question = "What general trend is indicated by the graph of total MSW generation?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "constant increase in MSW generation",
				true,
				"");
			
				p.addAnswer(2, "stable generation of MSW",
				false,
				"");
			
				p.addAnswer(3, "constant decline in MSW generation",
				false,
				"");
			
				p.addAnswer(4, "accelerating generation of MSW",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337479;


		
		

		
			
			p.question = "By how much has total MSW generation changed since 1960?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "It has been cut in half.",
				false,
				"");
			
				p.addAnswer(2, "It has increased more than two times.",
				true,
				"");
			
				p.addAnswer(3, "It has increased more than ten times.",
				false,
				"");
			
				p.addAnswer(4, "The net change is zero.",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337480;


		
		

		
			
			p.question = "Which of the following represents the best statement regarding this graph?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Growth in total MSW generation is most likely due to population increases rather than per capita generation increases.",
				false,
				"");
			
				p.addAnswer(2, "Growth in per capita MSW generation accounts for all growth in total generation.",
				false,
				"");
			
				p.addAnswer(3, "Total MSW generation has increased in spite of a decrease in per capita generation.",
				false,
				"");
			
				p.addAnswer(4, "Both total and per capita MSW generation grew steadily through 1990, while per capita generation seems to have recently stabilized.",
				true,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337481;


		
		

		
			
			p.question = "Assume that per capita MSW generation had grown between 1990 and 2000 at roughly the same rate as in previous years. How would that have affected the total MSW curve?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Growth in total MSW generation would be unaffected between 1990 and 2000.",
				false,
				"");
			
				p.addAnswer(2, "Growth in total MSW generation would be greater between 1990 and 2000.",
				true,
				"");
			
				p.addAnswer(3, "Growth in total MSW generation would be smaller between 1990 and 2000.",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337482;


		
		

		
			
			p.question = "Which form of MSW management experienced the greatest growth between 1960 and 2000?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "recovery for recycling",
				false,
				"");
			
				p.addAnswer(2, "combustion",
				false,
				"");
			
				p.addAnswer(3, "recovery for composting",
				true,
				"");
			
				p.addAnswer(4, "landfill",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337483;


		
		

		
			
			p.question = "Assuming the trends indicated by the graph continue, when will there no longer be a need for new sanitary landfills in the United States?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "not for the foreseeable future",
				true,
				"");
			
				p.addAnswer(2, "within 50 years",
				false,
				"");
			
				p.addAnswer(3, "starting now",
				false,
				"");
			
				p.addAnswer(4, "within 10 years",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337484;


		
		

		
			
			p.question = "Which of the following future trends would result in dominance of recycling as a MSW management strategy?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "continued growth in tonnage going to recycling",
				false,
				"");
			
				p.addAnswer(2, "slowing and stabilizing of total MSW generation",
				false,
				"");
			
				p.addAnswer(3, "landfill and combustion maintaining current percentages",
				false,
				"");
			
				p.addAnswer(4, "a combination of the first and second choices",
				true,
				"");
			
				p.addAnswer(5, "a combination of the second and third choices",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

