

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "Investigation Quiz > How Do Abiotic Factors Affect Distribution of Organisms?";
	ak.quiz_loc_with_commas = "Investigation Quiz, How Do Abiotic Factors Affect Distribution of Organisms?";
	ak.quiz_title = "How Do Abiotic Factors Affect Distribution of Organisms?";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 8;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 8;
	ak.non_essay_total = 0;
	ak.scored_item_total = 0;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337876;


		
		

		
			p.question = "Summarize and explain the effects of an increase in sunlight.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337877;


		
		

		
			p.question = "Summarize and explain the effects of a decrease in sunlight.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337878;


		
		

		
			p.question = "Summarize and explain the effects of an increase in water.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337879;


		
		

		
			p.question = "Summarize and explain the effects of a decrease in water.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337880;


		
		

		
			p.question = "Summarize and explain the effects of an increase in wind.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337881;


		
		

		
			p.question = "Summarize and explain the effects of a decrease in wind.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337882;


		
		

		
			p.question = "Summarize and explain the effects of an increase in temperature.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337883;


		
		

		
			p.question = "Summarize and explain the effects of a decrease in temperature.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

