

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "34: Vertebrates and Other Chordates > Practice Test";
	ak.quiz_loc_with_commas = "34: Vertebrates and Other Chordates, Practice Test";
	ak.quiz_title = "Practice Test";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 31;
	ak.non_essay_total = 31;
	ak.scored_item_total = 31;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335995;


		
		

		
			
			p.question = "If an animal has segments, bilateral symmetry, pharyngeal clefts, a post-anal tail, and deuterostomic development, it must be a member of the _____. (<script type=\"text/javascript\">ebook(\'3401\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Annelida",
				false,
				"No. Annelids lack, for example, a post-anal tail.");
			
				p.addAnswer(2, "Arthropoda",
				false,
				"No. Arthropods are protostomes.");
			
				p.addAnswer(3, "Chordata",
				true,
				"Correct. Chordates are deuterostomes that have four anatomical structures appearing at some time in development: a notochord, a hollow dorsal nerve cord, pharyngeal clefts, and a muscular post-anal tail.");
			
				p.addAnswer(4, "Mollusca",
				false,
				"No. Molluscs are protostomes.");
			
				p.addAnswer(5, "Platyhelminthes",
				false,
				"No. Platyhelminths (flatworms) lack, for example, pharyngeal gill clefts.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335996;


		
		

		
			
			p.question = "A _____ is a chordate but not a vertebrate. (<script type=\"text/javascript\">ebook(\'3401\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "lamprey",
				false,
				"No. Lampreys have a cartilaginous tube around their notochord; they qualify as vertebrates.");
			
				p.addAnswer(2, "shark",
				false,
				"No. Sharks have cartilaginous vertebrae.");
			
				p.addAnswer(3, "lancelet",
				true,
				"Correct. Lancelets are cephalochordates and, throughout their life, retain the notochord as the primary support of the appendicular skeleton.");
			
				p.addAnswer(4, "sea star",
				false,
				"No. Sea stars are echinoderms.");
			
				p.addAnswer(5, "frog",
				false,
				"No. Frogs are amphibians; amphibians are vertebrates.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335997;


		
		

		
			
			p.question = "Which one of the following chordate characteristics contributes most to the formation of your ears? (<script type=\"text/javascript\">ebook(\'3401\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "pharyngeal slits or clefts",
				true,
				"Correct. In mammals, derivatives of the pharyngeal slits contribute to the development of portions of our ears.");
			
				p.addAnswer(2, "dorsal, hollow nerve cord",
				false,
				"No. Although our ears have components of the nervous system, this is not the best choice.");
			
				p.addAnswer(3, "muscular, post-anal tail",
				false,
				"No. This is the wrong end of the animal.");
			
				p.addAnswer(4, "notochord",
				false,
				"No. The notochord does not contribute to the ear.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335998;


		
		

		
			
			p.question = "Which one of the following chordate characteristics contributes most to suspension-feeding devices in many invertebrate chordates? (<script type=\"text/javascript\">ebook(\'3401\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "pharyngeal slits or clefts",
				true,
				"Correct. In mammals, derivatives of the pharyngeal slits contribute to suspension-feeding devices in many invertebrate chordates.");
			
				p.addAnswer(2, "dorsal, hollow nerve cord",
				false,
				"No. Although there are nerves associated with these suspension-feeding devices, this is not the best choice.");
			
				p.addAnswer(3, "muscular, post-anal tail",
				false,
				"No. This is the wrong end of the animal.");
			
				p.addAnswer(4, "notochord",
				false,
				"No. Although there are skeletal structures associated with these suspension-feeding devices, this is not the best choice.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335999;


		
		

		
			
			p.question = "Which of the following pairs is <b>not</b> a correct match? (<script type=\"text/javascript\">ebook(\'3402\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Gnathostomata, hagfish",
				true,
				"Correct. Gnathostomes are jawed vertebrates. A hagfish is an agnathan, a jawless vertebrate.");
			
				p.addAnswer(2, "Mammalia, kangaroo",
				false,
				"No. Marsupials are mammals.");
			
				p.addAnswer(3, "Osteichthyes, perch",
				false,
				"No. A perch is a bony fish.");
			
				p.addAnswer(4, "Chondrichthyes, great white shark",
				false,
				"No. Sharks are cartilaginous fish.");
			
				p.addAnswer(5, "Aves, canary",
				false,
				"No. A canary is a bird.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336000;


		
		

		
			
			p.question = "What is unique about hagfish, compared to craniates such as sharks, frogs, alligators, and rats? Unlike these other craniates, hagfish do not have _____. (<script type=\"text/javascript\">ebook(\'3402\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "vertebrae",
				true,
				"Correct. The main skeletal element running along the mid-length of the body is the notochord.");
			
				p.addAnswer(2, "pharyngeal slits",
				false,
				"No. Hagfish have pharyngeal slits.");
			
				p.addAnswer(3, "a notochord",
				false,
				"No. Hagfish have a notochord.");
			
				p.addAnswer(4, "a dorsal, hollow nerve tube",
				false,
				"No. Hagfish have a dorsal, hollow nerve tube.");
			
				p.addAnswer(5, "a muscular, post-anal tail",
				false,
				"No. Hagfish have a muscular, post-anal tail.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336001;


		
		

		
			
			p.question = "Which of the following can be found in craniates but not in lancelets and tunicates? (<script type=\"text/javascript\">ebook(\'3402\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "neural crest",
				false,
				"No. Although this is correct, this is not the best choice.");
			
				p.addAnswer(2, "two clusters of Hox genes",
				false,
				"No.<b> </b>Although this is correct, this is not the best choice.");
			
				p.addAnswer(3, "duplications of genes that produce signaling molecules and transcription factors",
				false,
				"No. Although this is correct, it is not the best choice.");
			
				p.addAnswer(4, "all of the above",
				true,
				"Correct.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. All of the other choices are correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336002;


		
		

		
			
			p.question = "A lamprey, a shark, a lizard, and a rabbit share all the following characteristics <b>except</b> _____. (<script type=\"text/javascript\">ebook(\'3403\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "pharyngeal clefts in the embryo",
				false,
				"No. Such pharyngeal clefts are one of the defining features of chordates.");
			
				p.addAnswer(2, "vertebrae",
				false,
				"No. All of these chordates are vertebrates.");
			
				p.addAnswer(3, "hinged jaws",
				true,
				"Correct. The lamprey is jawless; all the other listed animals have jaws.");
			
				p.addAnswer(4, "a dorsal, hollow nerve cord",
				false,
				"No. A dorsal, hollow nerve cord is one of the defining features of chordates.");
			
				p.addAnswer(5, "a post-anal tail",
				false,
				"No. A post-anal tail is one of the defining features of chordates.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336003;


		
		

		
			
			p.question = "Which one of the following groups represents the oldest living lineage of vertebrates? (<script type=\"text/javascript\">ebook(\'3403\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "lampreys",
				true,
				"Correct.  Because of this, lampreys may offer clues to early chordate evolution.");
			
				p.addAnswer(2, "conodonts",
				false,
				"No. Conodonts are an extinct group of vertebrates.");
			
				p.addAnswer(3, "hagfish",
				false,
				"No. Hagfish are not vertebrates.");
			
				p.addAnswer(4, "sharks",
				false,
				"No. Sharks evolved after lampreys.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336004;


		
		

		
			
			p.question = "Some sharks are viviparous, which means that _____. (<script type=\"text/javascript\">ebook(\'3404\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the young develop within the female\'s body",
				true,
				"Correct. Some sharks are viviparous, which means that their young develop within the female body after hatching from eggs in the uterus.");
			
				p.addAnswer(2, "they lay eggs",
				false,
				"No. \"Vivi-\" means live; thus, viviparous animals bear \"live\" young; they do not lay eggs.");
			
				p.addAnswer(3, "they have a tendency toward multiple births",
				false,
				"No. The term does not refer to litter size.");
			
				p.addAnswer(4, "they have a tendency toward single births",
				false,
				"No. The term does not refer to litter size.");
			
				p.addAnswer(5, "they maintain a constant body temperature",
				false,
				"No. You would expect such a term to contain the suffix \"-therm.\"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336005;


		
		

		
			
			p.question = "The gill flap, or operculum, was an important adaptation for fish because it helps with _____. (<script type=\"text/javascript\">ebook(\'3404\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "orientation in currents",
				false,
				"No. The operculum does not play a significant role in orientation.");
			
				p.addAnswer(2, "maintaining a supply of oxygen",
				true,
				"Correct. Water is drawn into the mouth, through the pharynx, and out between the gills by movement of the operculum and contraction of muscles surrounding the gill chambers.");
			
				p.addAnswer(3, "sensing chemicals in water",
				false,
				"No. The operculum is not a sensory structure.");
			
				p.addAnswer(4, "adjusting buoyancy",
				false,
				"No. The swim bladder of bony fish plays a major role in adjusting buoyancy.");
			
				p.addAnswer(5, "underwater sex",
				false,
				"No. The operculum helps with obtaining oxygen. Water is drawn into the mouth, through the pharynx, and out between the gills by movement of the operculum and contraction of muscles surrounding the gill chambers.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336006;


		
		

		
			
			p.question = "A feature of bony fish not found in sharks is _____. (<script type=\"text/javascript\">ebook(\'3404\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "gills",
				false,
				"No. Other classes of fish have gills.");
			
				p.addAnswer(2, "mineralized teeth",
				false,
				"No. Gnathostomes have mineralized teeth.");
			
				p.addAnswer(3, "pelvic and pectoral fins with bony supports",
				false,
				"No. This is a feature of lobe-fins, and it provides evidence that this group may be ancestral to the tetrapods.");
			
				p.addAnswer(4, "a swim bladder",
				true,
				"Correct. A swim bladder, an aid in the maintenance of buoyancy, is a characteristic of most bony fish.");
			
				p.addAnswer(5, "a lateral line system",
				false,
				"No. Sharks also possess a lateral line system.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336007;


		
		

		
			
			p.question = "Which one of the following sets of animals contains only gnathostomes? (<script type=\"text/javascript\">ebook(\'3404\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "rays, turtles, pigeons, and tuna",
				true,
				"Correct.  As you can see, living gnathostomes are a diverse group.");
			
				p.addAnswer(2, "lampreys, conodonts, and hagfish",
				false,
				"No. None of these animals have or had jaws.");
			
				p.addAnswer(3, "conodonts, placoderms, and acanthodians",
				false,
				"No. Conodonts did not possess jaws.");
			
				p.addAnswer(4, "sharks, hagfish, and whales",
				false,
				"No. Hagfish do not have jaws.");
			
				p.addAnswer(5, "hagfish, bass, sharks, and frogs",
				false,
				"No. Hagfish do not have jaws.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336008;


		
		

		
			
			p.question = "The first vertebrates to live on land were _____. (<script type=\"text/javascript\">ebook(\'3405\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "agnathans",
				false,
				"No. Agnathans are jawless chordates restricted to aquatic environments.");
			
				p.addAnswer(2, "reptiles",
				false,
				"No. Reptiles are well adapted to land, and they are not the most primitive terrestrial vertebrate.");
			
				p.addAnswer(3, "amphibians",
				true,
				"Correct. Amphibians, though tied to water for reproduction, include species that are, otherwise, entirely terrestrial.");
			
				p.addAnswer(4, "chondrichthyans",
				false,
				"No. Chondrichthyans are restricted to aquatic environments.");
			
				p.addAnswer(5, "mammals",
				false,
				"No. Mammals, which are found in both aquatic and terrestrial environments, are not the most primitive terrestrial vertebrates.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336009;


		
		

		
			
			p.question = "Which one of the following animals is an amphibian? (<script type=\"text/javascript\">ebook(\'3405\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "caecilian",
				false,
				"No. Although a caecilian is an amphibian, this is not the best choice.");
			
				p.addAnswer(2, "frog",
				false,
				"No.<b> </b>Although a frog is an amphibian, this is not the best choice.");
			
				p.addAnswer(3, "salamander",
				false,
				"No. Although a salamander is an amphibian, this is not the best choice.");
			
				p.addAnswer(4, "all of the above",
				true,
				"Correct.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. All of the above are amphibians.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336010;


		
		

		
			
			p.question = " Habitat loss, the spread of a fungal pathogen, climate change, and pollution are causing severe population declines and extinction in _____. (<script type=\"text/javascript\">ebook(\'3405\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "amphibians",
				true,
				"Correct.");
			
				p.addAnswer(2, "sharks",
				false,
				"No. Large-scale commercial fishing seems to be causing most of the decline in sharks.");
			
				p.addAnswer(3, "birds",
				false,
				"No. Birds do not seem to be as sensitive to these problems.");
			
				p.addAnswer(4, "turtles",
				false,
				"No. Turtles do not seem to be as sensitive to these problems.");
			
				p.addAnswer(5, "rodents",
				false,
				"No. Rodent populations do not seem to be as sensitive to these problems.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336011;


		
		

		
			
			p.question = "The adaptation that freed vertebrates from water for reproduction and allowed them to radiate into diverse terrestrial environments was the _____. (<script type=\"text/javascript\">ebook(\'3406\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "operculum",
				false,
				"No. An operculum is a bony flap that protects the gills of bony fish.");
			
				p.addAnswer(2, "placenta",
				false,
				"No. Vertebrates had radiated into terrestrial, aquatic, and aerial habitats prior to the evolution of the placenta.");
			
				p.addAnswer(3, "lateral line system",
				false,
				"No. This is a sensory structure characteristic of many aquatic vertebrates.");
			
				p.addAnswer(4, "bony appendage",
				false,
				"No. Bony appendages are a shared primitive character also found in amphibians and some bony fish.");
			
				p.addAnswer(5, "amniotic egg",
				true,
				"Correct. The amniotic egg allows for reproduction and development within a structure that provides moisture, food, waste storage, and gas exchange.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336012;


		
		

		
			
			p.question = "Which of the following characteristics is <b>not</b> shared by extant birds and extant reptiles? (<script type=\"text/javascript\">ebook(\'3406\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "endothermic metabolism",
				true,
				"Correct. Birds are endothermic, but extant reptiles are ectothermic. There is much debate over whether some groups of extinct reptiles, such as the dinosaurs, were endotherms or ectotherms.");
			
				p.addAnswer(2, "amniotic eggs",
				false,
				"No. Birds and reptiles do lay amniotic eggs.");
			
				p.addAnswer(3, "vertebrae",
				false,
				"No. Birds and reptiles do have a bony vertebral column.");
			
				p.addAnswer(4, "scales containing keratin",
				false,
				"No. Both of these groups do have keratinized scales.");
			
				p.addAnswer(5, "pharyngeal clefts in the embryo",
				false,
				"No. This is a diagnostic feature of the chordates.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336013;


		
		

		
			
			p.question = "Which one of the following is an archosaur group? (<script type=\"text/javascript\">ebook(\'3406\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "crocodiles",
				true,
				"Correct.  Crocodiles belong to an archosaur lineage that reaches back to the late Triassic.");
			
				p.addAnswer(2, "lizards",
				false,
				"No. These are lepidosaurs.");
			
				p.addAnswer(3, "snakes",
				false,
				"No. These are lepidosaurs.");
			
				p.addAnswer(4, "tuatara",
				false,
				"No. These are lepidosaurs.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the above is a group of archosaurs.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336014;


		
		

		
			
			p.question = "All mammals _____. (<script type=\"text/javascript\">ebook(\'3407\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "bear live young",
				false,
				"No. Monotremes are egg-laying mammals.");
			
				p.addAnswer(2, "complete their embryonic development in the uterus",
				false,
				"No. This applies only to placental mammals.");
			
				p.addAnswer(3, "nourish their offspring through mammary glands",
				true,
				"Correct. Mammary glands that produce milk are as distinctively mammalian as hair.");
			
				p.addAnswer(4, "all of the above",
				false,
				"No. Only one of the choices is correct.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336015;


		
		

		
			
			p.question = "The opossum is an example of a(n) _____ mammal. (<script type=\"text/javascript\">ebook(\'3407\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "marsupial",
				true,
				"Correct. Opossums, kangaroos, bandicoots, and koalas are examples of marsupial mammals.");
			
				p.addAnswer(2, "placental",
				false,
				"No. In placental mammals embryonic development is completed within the uterus; this is not true for opossums.");
			
				p.addAnswer(3, "monotreme",
				false,
				"No. Opossums do not lay eggs.");
			
				p.addAnswer(4, "oviparous",
				false,
				"No. Opossums do not lay eggs.");
			
				p.addAnswer(5, "eutherian",
				false,
				"No. This is another term for placental. In placental mammals embryonic development is completed within the uterus; this is not true for opossums.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336016;


		
		

		
			
			p.question = "Primates are distinguished from other mammals by _____. (<script type=\"text/javascript\">ebook(\'3407\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "opposable thumbs, nails, and good depth perception",
				true,
				"Correct. Arboreal adaptations that distinguish primates from other mammals include opposable thumbs, nails rather than claws, eyes on the front of the head (giving good depth perception), and small litters.");
			
				p.addAnswer(2, "fur, claws, and small litters",
				false,
				"No. Primates have flat nails, not the claws typical of other mammals.");
			
				p.addAnswer(3, "stereoscopic vision, mammary glands, and single births",
				false,
				"No. However, this choice is partially correct.");
			
				p.addAnswer(4, "eutherian reproduction, opposable thumbs, and good depth perception",
				false,
				"No. However, this choice is partially correct.");
			
				p.addAnswer(5, "long tails used for balance, stereoscopic vision, and opposable thumbs",
				false,
				"No. However, this choice is partially correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336017;


		
		

		
			
			p.question = "Humans and the loris share many traits that probably evolved in our early primate ancestors, including _____. (<script type=\"text/javascript\">ebook(\'3407\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "opposable big toes",
				false,
				"No. Humans do not have opposable big toes.");
			
				p.addAnswer(2, "an arboreal way of life",
				false,
				"No. Humans do not live in trees.");
			
				p.addAnswer(3, "a thumb that is relatively mobile and separate from the fingers",
				true,
				"Correct. All primates have such thumbs. Anthropoids have a fully opposable thumb; that is, they can touch the ventral surface (fingerprint side) of the tip of all four fingers with the ventral surface of the thumb of the same hand.");
			
				p.addAnswer(4, "culture",
				false,
				"No. Culture is not well documented in all primates and it has been reported in non-primate mammals.");
			
				p.addAnswer(5, "bipedalism (upright walking)",
				false,
				"No. Only hominids, including modern humans, are bipedal.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336018;


		
		

		
			
			p.question = "Humans, apes, and monkeys are classified together as _____. (<script type=\"text/javascript\">ebook(\'3407\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "hominids",
				false,
				"No. Of the three, only humans are hominids.");
			
				p.addAnswer(2, "anthropoids",
				true,
				"Correct. Anthropoids include humans, apes, and monkeys.");
			
				p.addAnswer(3, "hominoids",
				false,
				"No. Of the three, apes and humans are hominoids.");
			
				p.addAnswer(4, "brachiators",
				false,
				"No. Brachiators use their arms to swing themselves when they move from tree to tree.");
			
				p.addAnswer(5, "Australopithecinae",
				false,
				"No. None of the three is an australopithecine.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336019;


		
		

		
			
			p.question = "All species of New World monkeys are _____. (<script type=\"text/javascript\">ebook(\'3407\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "nocturnal",
				false,
				"No. Most monkeys are diurnal.");
			
				p.addAnswer(2, "ground dwelling",
				false,
				"No. Just the opposite.");
			
				p.addAnswer(3, "arboreal",
				true,
				"Correct.");
			
				p.addAnswer(4, "solitary",
				false,
				"No. Most monkeys are highly social.");
			
				p.addAnswer(5, "oviparous",
				false,
				"No. Monkeys do not lay eggs.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336020;


		
		

		
			
			p.question = "Included among the modern genera of apes are ______. (<script type=\"text/javascript\">ebook(\'3407\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "gibbons, orangutans, gorillas, chimpanzees, and bonobos",
				true,
				"Correct. The modern genera of apes include gibbons, orangutans, gorillas, chimpanzees, and bonobos.");
			
				p.addAnswer(2, "lemurs and lorises",
				false,
				"No. Lemurs and lorises are not apes.");
			
				p.addAnswer(3, "tarsiers and gorillas",
				false,
				"No. Tarsiers are not apes.");
			
				p.addAnswer(4, "Old World monkeys and New World monkeys",
				false,
				"No. While monkeys and apes are anthropoids, monkeys are not apes.");
			
				p.addAnswer(5, "New World monkeys and orangutans",
				false,
				"No. Orangutans are considered apes, but monkeys are not.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336021;


		
		

		
			
			p.question = "Which of the following traits distinguishes hominids from apes? (<script type=\"text/javascript\">ebook(\'3408\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the use of tools",
				false,
				"No. Some apes (chimpanzees) and some hominids (members of the genus <i>Homo</i>) use, or used, tools.");
			
				p.addAnswer(2, "the use of fire",
				false,
				"No. Only some hominids (<i>Homo erectus</i> and <i>Homo sapiens</i>) use, or used, fire.");
			
				p.addAnswer(3, "an enlarged brain (relative to body size)",
				false,
				"No. The australopithecines (hominids) had small brains.");
			
				p.addAnswer(4, "bipedalism (upright walking)",
				true,
				"Correct. The australopithecines and members of the genus <i>Homo</i>, but no apes, are or were bipedal.");
			
				p.addAnswer(5, "the absence of a tail",
				false,
				"No. Neither apes nor hominids have tails.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336022;


		
		

		
			
			p.question = "Which of the following correctly lists probable ancestors of modern humans from the oldest to the most recent? (<script type=\"text/javascript\">ebook(\'3408\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "<i>Sahelanthropus, Homo, Australopithecus</i>",
				false,
				"No. <i>Australopithecus</i> is not the most recent.");
			
				p.addAnswer(2, "<i>Sahelanthropus, Australopithecus, Homo</i>",
				true,
				"Correct.");
			
				p.addAnswer(3, "<i>Australopithecus, Sahelanthropus, Homo</i>",
				false,
				"No. <i>Sahelanthropus</i> is the oldest.");
			
				p.addAnswer(4, "<i>Homo, Sahelanthropus, Australopithecus</i>",
				false,
				"No. <i> Homo</i> is not the oldest.");
			
				p.addAnswer(5, "<i>Homo, Australopithecus, Sahelanthropus</i>",
				false,
				"No. <i>Homo</i> is not the oldest.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336023;


		
		

		
			
			p.question = "_____ arose very early in hominid evolution; _____ evolved more recently. (<script type=\"text/javascript\">ebook(\'3408\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Large brains; prominent brow ridges",
				false,
				"No. Modern humans do not have prominent brow ridges.");
			
				p.addAnswer(2, "Large brains; upright posture",
				false,
				"No. An upright posture evolved earlier than did a large brain.");
			
				p.addAnswer(3, "Upright posture; forward-looking eyes",
				false,
				"No. The evolution of forward-looking eyes preceded the evolution of an upright posture.");
			
				p.addAnswer(4, "Upright posture; large brains",
				true,
				"Correct. Various human characteristics, such as upright posture and large brains, did not evolve in unison. Different features evolved at different rates, with erect posture leading the way.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336024;


		
		

		
			
			p.question = "What was the earliest hominid to have an enlarged brain (relative to body size)? (<script type=\"text/javascript\">ebook(\'3408\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "<i>Ardipithecus</i>",
				false,
				"No. <i>Ardipithecus</i> had a small brain.");
			
				p.addAnswer(2, "<i>Australopithecus</i>",
				false,
				"No. <i>Australopithecus</i> had a small brain.");
			
				p.addAnswer(3, "<i>Homo habilis</i>",
				true,
				"Correct. The brain of this species was intermediate in size between that of <i>Australopithecus</i> and that of <i>Homo sapiens</i>.");
			
				p.addAnswer(4, "<i>Homo erectus</i>",
				false,
				"No. <i>Homo erectus</i> had an enlarged brain, but <i>Homo habilis</i> appeared first.");
			
				p.addAnswer(5, "<i>Homo neanderthalensis</i>",
				false,
				"No. The Neanderthals had enlarged brains, but <i>Homo habilis</i> appeared first.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336025;


		
		

		
			
			p.question = "Analysis of mitochondrial DNA and Y chromosomes of modern humans has led most researchers to agree that _____. (<script type=\"text/javascript\">ebook(\'3408\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the common ancestor of <i>Homo sapiens</i> was a Neanderthal",
				false,
				"No. All living humans are more closely related to each other than to Neanderthals.");
			
				p.addAnswer(2, "modern humans emerged from Africa",
				true,
				"Correct. Older species (perhaps <i>H. ergaster </i>or <i>H. erectus</i>) gave rise to newer species, such as <i>H. heidelbergensis</i> and ultimately <i>H. sapiens</i>, who migrated from Africa.");
			
				p.addAnswer(3, "<i>Homo sapiens</i> evolved from <i>H. erectus</i> in several parts of the world.",
				false,
				"No. Most researchers agree that <i>Homo sapiens</i> evolved in Africa<i>.</i>");
			
				p.addAnswer(4, "<i>Homo sapiens</i> has many common ancestors",
				false,
				"No.  Most evidence suggests that human evolution followed a fairly streamlined course.");
			
				p.addAnswer(5, "<i>Homo sapiens</i> settled in the New World approximately 75,000 years ago",
				false,
				"No. Although this is a subject of much debate, the oldest generally accepted evidence puts that date at 15,000 years ago.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

