

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "4: Carbon and the Molecular Diversity of Life > Practice Test";
	ak.quiz_loc_with_commas = "4: Carbon and the Molecular Diversity of Life, Practice Test";
	ak.quiz_title = "Practice Test";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 31;
	ak.non_essay_total = 31;
	ak.scored_item_total = 31;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334203;


		
		

		
			
			p.question = "At the beginning of the 19th century, it was thought that the substances that made up living things were special and could not be synthesized by ordinary chemical methods. This now-discarded theory was called the theory of _____. (<script type=\"text/javascript\">ebook(\'0401\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "special creation",
				false,
				"No. This refers to belief-based ideas concerning the origin of life.");
			
				p.addAnswer(2, "spontaneous generation",
				false,
				"No. This refers to a discarded hypothesis concerning the origin of life.");
			
				p.addAnswer(3, "vitalism",
				true,
				"Correct. Vitalism is a belief in a life force outside the jurisdiction of physical and chemical laws.");
			
				p.addAnswer(4, "materialism",
				false,
				"No. Materialism is the theory that only natural things exist.");
			
				p.addAnswer(5, "mechanism",
				false,
				"No. Mechanism is the belief that all natural phenomena, including life processes, are governed by physical and chemical laws.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334204;


		
		

		
			
			p.question = "The first organic molecule to be synthesized from inorganic substances that could be prepared directly from inorganic substances was _____. (<script type=\"text/javascript\">ebook(\'0401\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "urea",
				false,
				"No. Urea, synthesized by Friedrich W&ouml;hler, was the first organic molecule synthesized. However, W&ouml;hler\'s accomplishment was not universally recognized because he extracted cyanate from animal blood.");
			
				p.addAnswer(2, "acetic acid",
				true,
				"Correct. Acetic acid was the first organic molecule synthesized from nothing but inorganic substances.");
			
				p.addAnswer(3, "ammonium cyanate",
				false,
				"No. W&ouml;hler tried to make ammonium cyanate, an inorganic salt, but to his surprise he made urea instead.");
			
				p.addAnswer(4, "insulin",
				false,
				"No. Insulin is an organic molecule (a protein), but it was discovered much later.");
			
				p.addAnswer(5, "DNA",
				false,
				"No. DNA is an organic compound (a nucleic acid), but it was discovered much later.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334205;


		
		

		
			
			p.question = "Stanley Miller\'s experiments were significant because he demonstrated that _____. (<script type=\"text/javascript\">ebook(\'0401\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the behavior of any molecule containing a carbon atom was fundamentally the same",
				false,
				"No. The behavior of molecules containing carbon can be quite different and is influenced primarily by the construction of the carbon skeleton and the presence and variety of functional groups.");
			
				p.addAnswer(2, "under certain circumstances the theory of vitalism was valid",
				false,
				"No. Miller\'s experiments provided the evidence needed to fully invalidate the theory of vitalism.");
			
				p.addAnswer(3, "a variety of simple organic compounds could be spontaneously synthesized from components in Earth\'s primitive atmosphere",
				true,
				"Correct. By discharging an electrode in a mixture similar to Earth\'s primitive atmosphere, Miller was able to synthesize a variety of simple organic molecules.");
			
				p.addAnswer(4, "lightning discharges could produce the molecules previously presumed to have originated in volcanic outgassings",
				false,
				"No. Using volcanic gases, Miller showed that these gas molecules, with the energy from lightning, could become a variety of simple organic molecules.");
			
				p.addAnswer(5, "urea could be synthesized from entirely naturally occurring salts",
				false,
				"No. Miller experimented with the gases thought to have made up Earth\'s primitive atmosphere.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334206;


		
		

		
			
			p.question = "Which is an organic molecule? (<script type=\"text/javascript\">ebook(\'0402\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Ne",
				false,
				"No. Neon is not an organic molecule. Neon is an element.");
			
				p.addAnswer(2, "O<sub>2</sub>",
				false,
				"No. Oxygen is not an organic molecule. Compounds containing carbon are said to be organic. O<sub>2</sub> is a molecule of oxygen gas.");
			
				p.addAnswer(3, "CH<sub>4</sub>",
				true,
				"Correct. Compounds containing carbon are said to be organic.");
			
				p.addAnswer(4, "NaCl",
				false,
				"No. NaCl (salt) is not an organic molecule. Compounds containing carbon are said to be organic.");
			
				p.addAnswer(5, "H<sub>2</sub>O",
				false,
				"No. Water is not an organic molecule. Compounds containing carbon are said to be organic.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334207;


		
		

		
			
			p.question = "Which element is always associated with organic chemistry? (<script type=\"text/javascript\">ebook(\'0402\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "carbon",
				true,
				"Correct. Compounds containing carbon are said to be organic.");
			
				p.addAnswer(2, "sulfur",
				false,
				"No. Sulfur is not diagnostic of organic chemistry.");
			
				p.addAnswer(3, "nitrogen",
				false,
				"No. Nitrogen is not diagnostic of organic chemistry.");
			
				p.addAnswer(4, "hydrogen",
				false,
				"No. Hydrogen is not diagnostic of organic chemistry.");
			
				p.addAnswer(5, "oxygen",
				false,
				"No. Oxygen is not diagnostic of organic chemistry.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334208;


		
		

		
			
			p.question = "What is the three-dimensional shape created by hybrid orbitals that are formed when a carbon atom is covalently bonded with four other atoms? (<script type=\"text/javascript\">ebook(\'0402\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a flat sheet with carbon in the center",
				false,
				"No. Bonding electrons are positioned as distantly from one another as possible. A flat sheet does not provide the greatest possible distance between electron pairs.");
			
				p.addAnswer(2, "a triangle with carbon in the center",
				false,
				"No. A triangle has three vertices; the carbon atom in the question is bonded to four other atoms.");
			
				p.addAnswer(3, "a cube with carbon in the center",
				false,
				"No. A cube has six vertices; the carbon atom in the question is bonded to four other atoms.");
			
				p.addAnswer(4, "a tetrahedron with carbon in the center",
				true,
				"Correct. The pairs of bonding electrons are oriented as distantly as possible from one another in a tetrahedron with the carbon atom at the center and the other four atoms at the vertices of the tetrahedron.");
			
				p.addAnswer(5, "All of the above are possible.",
				false,
				"No. Only one of the above is a correct answer.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334209;


		
		

		
			
			p.question = "A straight-chain carbon compound constructed from _____ must contain at least one carbon-carbon double bond. (<script type=\"text/javascript\">ebook(\'0402\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "6 hydrogen, 2 carbon",
				false,
				"No. This is a typical hydrocarbon with single bonds, in which the number of hydrogen atoms is equal to two times the number of carbon atoms plus 2.");
			
				p.addAnswer(2, "6 hydrogen, 3 carbon",
				true,
				"Correct. There must be a carbon-carbon double bond for this molecule to exist.");
			
				p.addAnswer(3, "6 hydrogen, 2 carbon, 1 oxygen",
				false,
				"No. If the carbons were double-bonded, only four additional bonds could be formed.");
			
				p.addAnswer(4, "8 hydrogen, 3 carbon, 3 oxygen",
				false,
				"No. If two carbons were double-bonded, there would not be enough bonds for the rest of the atoms, even though three hydrogen bind to three oxygen.");
			
				p.addAnswer(5, "14 hydrogen, 6 carbon",
				false,
				"No. This is a typical hydrocarbon with single bonds, in which the number of hydrogen atoms is equal to two times the number of carbon atoms plus 2.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334210;


		
		

		
			
			p.question = "Carbon atoms are the most versatile building blocks of the molecules used by living organisms because _____. (<script type=\"text/javascript\">ebook(\'0402\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "carbon is the central atom of carbon dioxide, a necessary molecule for photosynthesis",
				false,
				"No. But it\'s true that carbon is the central atom in carbon dioxide. What other quality makes carbon versatile?");
			
				p.addAnswer(2, "carbon is the central atom in urea, a molecule used by many living organisms to transport wastes from the body",
				false,
				"No. But it\'s true that carbon is the central atom in urea. What other quality makes carbon versatile?");
			
				p.addAnswer(3, "each carbon atom acts as an intersection point from which a molecule can branch off in up to four directions",
				true,
				"Correct. Carbon has the potential to form molecules that can be straight, branched, or ringed. Along with the ability to form double and triple bonds, this ability permits the formation of an almost infinite number of different molecules.");
			
				p.addAnswer(4, "carbon can combine with hydrogen to form hydrocarbons",
				false,
				"No. But it\'s true that hydrocarbons are formed from carbon and hydrogen. What other quality makes carbon versatile?");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. All of the above are true statements, but they do not all answer the question. Carbon is a versatile building block for only one of the above reasons.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334211;


		
		

		
			
			p.question = "The carbon atom is tetravalent; this means that _____. (<script type=\"text/javascript\">ebook(\'0402\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "carbon readily forms ionic bonds",
				false,
				"No. To form an ion, carbon must lose or gain an electron, but with 4 valence electrons this is unlikely.");
			
				p.addAnswer(2, "carbon\'s first electron shell holds 4 electrons",
				false,
				"No. The first electron shell for carbon and all atoms, except hydrogen, holds 2 electrons (hydrogen has 1 electron).");
			
				p.addAnswer(3, "a carbon atom can complete its valence shell by forming four covalent bonds",
				true,
				"Correct. With 4 valence electrons, carbon usually shares its 4 electrons in covalent bonds to complete its outer shell.");
			
				p.addAnswer(4, "the bond angle between each bond is 90&#176;, forming an arrangement like the points on a compass",
				false,
				"No. Bonds orient as far from one another as possible, but in a three-dimensional molecule the bond angle becomes 109&#176; and forms a tetrahedron.");
			
				p.addAnswer(5, "carbon has a total of 4 electrons",
				false,
				"No. All carbon atoms have 6 protons and thus 6 electrons. Carbon has 4 electrons in its outer shell.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334212;


		
		

		
			
			p.question = "Which of the following are properties of hydrocarbons? (<script type=\"text/javascript\">ebook(\'0402\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Hydrophobic, polar, charged",
				false,
				"No. Hydrocarbons are hydrophobic, but not polar and not charged.");
			
				p.addAnswer(2, "Hydrophilic, good source of stored energy, consist primarily of carbon and hydrogen",
				false,
				"No. Hydrocarbons are definitely not hydrophilic.");
			
				p.addAnswer(3, "Hydrophobic, nonpolar, good source of stored energy",
				true,
				"Correct. Because they are nonpolar, hydrocarbons are hydrophobic. They also provide energy in the forms of things like fossil fuels and fats.");
			
				p.addAnswer(4, "Hydrophilic, contain numerous carboxyl groups, nonpolar",
				false,
				"No. Hydrocarbons are hydrophobic and do not contain carboxyl groups.");
			
				p.addAnswer(5, "Hydrophobic, contain numerous amine groups, polar",
				false,
				"No. Hydrocarbons are nonpolar and do not contain amine groups.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334213;


		
		

		
			
			p.question = "A molecule has one carbon-carbon double bond and four monovalent atoms or groups. How many different geometric isomers exist for this molecule? (<script type=\"text/javascript\">ebook(\'0402\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "none",
				false,
				"No. Try drawing possible configurations on a piece of scrap paper.");
			
				p.addAnswer(2, "two",
				true,
				"Correct. Only two geometric isomers exist. The number of structural isomers, however, is larger.");
			
				p.addAnswer(3, "four",
				false,
				"No. Try drawing possible configurations on a piece of scrap paper.");
			
				p.addAnswer(4, "six",
				false,
				"No. Try drawing possible configurations on a piece of scrap paper.");
			
				p.addAnswer(5, "eight",
				false,
				"No. Try drawing possible configurations on a piece of scrap paper.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334214;


		
		

		
			
			p.question = "The two compounds <br><IMG SRC=\""+qzmediapath+"bc_campbell_biology_8/img/practice_tests/ch4q12a.gif\" ALT=\"Question #12\" BORDER=\"0\" ><br><IMG SRC=\""+qzmediapath+"bc_campbell_biology_8/img/practice_tests/ch4q12b.gif\" ALT=\"Question #12\" BORDER=\"0\" ><br> are related to each other by being _____. (<script type=\"text/javascript\">ebook(\'0402\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "hydrocarbons",
				false,
				"No. True, they are both hydrocarbons, but that isn\'t the only answer.");
			
				p.addAnswer(2, "organic compounds",
				false,
				"No. True, they are both organic compounds, but that isn\'t the only answer.");
			
				p.addAnswer(3, "isomers",
				false,
				"No. True, they are isomers of each other, but that isn\'t the only answer.");
			
				p.addAnswer(4, "double-bonded compounds",
				false,
				"No. True, they are both double-bonded compounds, but that isn\'t the only answer.");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct. All of the above answers are true statements about the two compounds.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334215;


		
		

		
			
			p.question = "Pharmaceutical companies are selling close to $200 billion worth of single-enantiomer drugs. Why might it be important to use only one form of an enantiomer? (<script type=\"text/javascript\">ebook(\'0402\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "It is cheaper to manufacture only one of the enantiomers.",
				false,
				"No. In most cases it is more expensive to separate the left-handed version from the right-handed one.");
			
				p.addAnswer(2, "It is not important. Both enantiomers will be equally effective.",
				false,
				"No. In some cases both enantiomers can be effective, but in many drugs only one enantiomer is safe and effective.");
			
				p.addAnswer(3, "The left-handed version of the enantiomer is always the effective one.",
				false,
				"No. Depending on the molecule, either enantiomer may be the effective one, and in some cases both are effective.");
			
				p.addAnswer(4, "It is not important. Both enantiomers constantly flip from right-handed to left-handed.",
				false,
				"No. Not all enantiomers spontaneously change from one to the other, but it is important to understand their behavior in the body.");
			
				p.addAnswer(5, "One enantiomer may provide an effective treatment while the other may be ineffective or even toxic.",
				true,
				"Correct. Depending on the body\'s ability to recognize and use different enantiomers, one version may have dangerous effects as in the case of thalidomide.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334216;


		
		

		
			
			p.question = "Which of the following functional groups is present in all amino acids? (<script type=\"text/javascript\">ebook(\'0403\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "-SH",
				false,
				"No. This is a sulfhydryl group. This group is not present in all amino acids.");
			
				p.addAnswer(2, "-COH",
				false,
				"No. This is a carbonyl group. This group is not present in all amino acids.");
			
				p.addAnswer(3, "-OH",
				false,
				"No. This is a hydroxyl group. This group is not present in all amino acids.");
			
				p.addAnswer(4, "-NH<sub>2</sub>",
				true,
				"Correct. This is the amino group. This group is present in all amino acids.");
			
				p.addAnswer(5, "-OPO<sub>3</sub><sup>-2</sup>",
				false,
				"No. This is a phosphate group. This group is not present in all amino acids.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334217;


		
		

		
			
			p.question = "Which of these is found in all amino acids? (<script type=\"text/javascript\">ebook(\'0403\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "-COOH",
				false,
				"No. This answer is partially correct. This is the carboxyl functional group. It is present in all amino acids. But there is a better answer.");
			
				p.addAnswer(2, "-COH",
				false,
				"No. This is a carbonyl functional group. It is present in some, but not all, amino acids.");
			
				p.addAnswer(3, "-OH",
				false,
				"No. This is a hydroxyl functional group. It is present in some, but not all, amino acids.");
			
				p.addAnswer(4, "-NH<sub>2</sub>",
				false,
				"No. This answer is partially correct. This is the amino functional group. It is present in all amino acids, but there is a better answer.");
			
				p.addAnswer(5, "Both -COOH and -NH<sub>2</sub>",
				true,
				"Correct. For a compound to be an amino acid, it must contain at least one carboxyl functional group and one amino functional group. In addition, it may contain one or more of the other functional groups.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334218;


		
		

		
			
			p.question = "Glucose and hexanoic acid each contain six carbon atoms, but they have completely different properties. Glucose is a nutrient found in food; hexanoic acid is poisonous. Their differences must be due to different _____. (<script type=\"text/javascript\">ebook(\'0403\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "monomers",
				false,
				"No. Monomers are the subunits that assemble to form macromolecules. Glucose is the monomer in molecules such as starch and cellulose.");
			
				p.addAnswer(2, "macromolecules",
				false,
				"No. Glucose and hexanoic acid are small molecules. Macromolecules, such as cellulose and starch, consist of many relatively small molecules, called monomers.");
			
				p.addAnswer(3, "isomers",
				false,
				"No. Isomers are compounds that have the same numbers of atoms of each of their composite elements but different structures and hence different properties.");
			
				p.addAnswer(4, "quaternary structures",
				false,
				"No. Quaternary structure is produced when molecular subunits assemble into a larger molecule. The term is typically applied only to proteins.");
			
				p.addAnswer(5, "functional groups",
				true,
				"Correct. Functional groups most commonly determine chemical properties such as the polarity and reactivity of molecules.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334219;


		
		

		
			
			p.question = "Although the structures of the functional groups that are most important to life vary, they share one thing in common: They _____. (<script type=\"text/javascript\">ebook(\'0403\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "all contain oxygen",
				false,
				"No. Amino functional groups lack oxygen.");
			
				p.addAnswer(2, "all have at least one double bond",
				false,
				"No. Amino, hydroxyl, and sulfhydryl functional groups lack a double bond.");
			
				p.addAnswer(3, "always cause the carbon to which they are attached to become an asymmetric carbon, thus they convert the molecule into an enantiomer",
				false,
				"No. For a carbon atom to be asymmetric, the carbon must bond to four different atoms or groups of atoms.");
			
				p.addAnswer(4, "all are hydrophilic and increase the organic compound\'s water solubility",
				true,
				"Correct. Functional groups are all hydrophilic.");
			
				p.addAnswer(5, "force straight chains of carbons into closed rings of carbon",
				false,
				"No. None of the functional groups force straight-chain carbon skeletons into a closed ring.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334220;


		
		

		
			
			p.question = "Ethanol, propanol, and methanol are three simple alcohols. They can be grouped together because they _____. (<script type=\"text/javascript\">ebook(\'0403\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "all share the same functional group: a hydroxyl",
				true,
				"Correct. Alcohols are distinguished by the presence of the hydroxyl (-OH) functional group.");
			
				p.addAnswer(2, "are soluble in water",
				false,
				"No. They are soluble in water, but so are many other molecules that are not alcohols.");
			
				p.addAnswer(3, "are hydrophobic",
				false,
				"No. These molecules possess a functional group that increases their polarity, and thus solubility, in water.");
			
				p.addAnswer(4, "all contain a carbonyl group",
				false,
				"No. Ethanol, propanol, and methanol do not contain the carbonyl functional group. The presence of a carbonyl group would result in an aldehyde or ketone.");
			
				p.addAnswer(5, "increase the acidity of solutions",
				false,
				"No. The dissociation of a hydrogen ion is a characteristic of the carboxyl functional group.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334221;


		
		

		
			
			p.question = "Which one of the following molecules has a carboxyl functional group? (<script type=\"text/javascript\">ebook(\'0403\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "R-NH<sub>2</sub>",
				false,
				"No. The molecule R-NH<sub>2</sub> contains the amino functional group (-NH<sub>2</sub>).");
			
				p.addAnswer(2, "R-COH",
				false,
				"No. The molecule R-COH contains the carbonyl functional group (-COH).");
			
				p.addAnswer(3, "R-COOH",
				true,
				"Correct. The molecule R-COOH contains the carboxyl functional group (-COOH). The presence of this group would make the molecule a weak acid.");
			
				p.addAnswer(4, "R-OPO<sub>3</sub><sup>-2</sup>",
				false,
				"No. The molecule R-OPO<sub>3</sub><sup>-2 </sup>contains the phosphate functional group (-OPO<sub>3</sub><sup>-2</sup>).");
			
				p.addAnswer(5, "R-SH",
				false,
				"No. The molecule (R-SH) contains the sulfhydryl functional group (-SH).");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334222;


		
		

		
			
			p.question = "Which one of the following molecules is a weak base? (<script type=\"text/javascript\">ebook(\'0403\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "R-NH<sub>2</sub>",
				true,
				"Correct. The amino group (-NH<sub>2</sub>) of R-NH<sub>2 </sub>can function as a base. It can accept a proton (H<sup>+</sup>).");
			
				p.addAnswer(2, "R-SH",
				false,
				"No. The sulfhydryl group (-SH) of R-SH cannot accept a proton (H<sup>+</sup>).");
			
				p.addAnswer(3, "R-OH",
				false,
				"No. The hydroxyl group (-OH<sup>-</sup>) of R-OH cannot accept a proton (H<sup>+</sup>).");
			
				p.addAnswer(4, "R-COOH",
				false,
				"No. The carboxyl group (-COOH) of R-COOH can donate a proton, but it cannot accept a proton (H<sup>+</sup>).");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the above answers is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334223;


		
		

		
			
			p.question = "Which of the following molecules is a weak acid? (<script type=\"text/javascript\">ebook(\'0403\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "R-NH<sub>2</sub>",
				false,
				"No. The amino group (-NH<sub>2</sub>) of R-NH<sub>2 </sub>can<sub> </sub>function as a base. It can accept a proton (H<sup>+</sup>), but it cannot donate a proton (H<sup>+</sup>).");
			
				p.addAnswer(2, "R-SH",
				false,
				"No. The sulfhydryl group of R-SH cannot donate a proton (H<sup>+</sup>).");
			
				p.addAnswer(3, "R-OH",
				false,
				"No. The hydroxyl group (-OH<sup>-</sup>) of R-OH cannot donate a proton (H<sup>+</sup>).");
			
				p.addAnswer(4, "R-COOH",
				true,
				"Correct. The carboxyl group (-COOH) of R-COOH can donate a proton (H<sup>+</sup>).");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the above is a correct answer.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334224;


		
		

		
			
			p.question = "Which one of the following functional groups increases the solubility of organic compounds in water? (<script type=\"text/javascript\">ebook(\'0403\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "-SH",
				false,
				"No. This is true, but there is a better answer.");
			
				p.addAnswer(2, "-COOH",
				false,
				"No. This is true, but there is a better answer.");
			
				p.addAnswer(3, "-COH",
				false,
				"No. This is true, but there is a better answer.");
			
				p.addAnswer(4, "-NH<sub>2</sub>",
				false,
				"No. This is true, but there is a better answer.");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct. All of the functional groups are hydrophilic and thus increase the solubility of organic molecules in water.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334225;


		
		

		
			
			p.question = "Which of the following examples describes a unique functional property of the carboxyl group? (<script type=\"text/javascript\">ebook(\'0403\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Its compounds may be structural isomers with different properties.",
				false,
				"No. This is a property of the carbonyl group.");
			
				p.addAnswer(2, "Two groups can interact to help stabilize protein structure.",
				false,
				"No. This is a property of the sulfhydryl group.");
			
				p.addAnswer(3, "It is polar as a result of the electronegative oxygen atom drawing electrons toward itself.",
				false,
				"No. This is true, but it is not the best answer.");
			
				p.addAnswer(4, "The covalent bond between oxygen and hydrogen is so polar that hydrogen ions tend to dissociate reversibly.",
				true,
				"Correct. This is a property of the carboxyl group.");
			
				p.addAnswer(5, "It acts as a base.",
				false,
				"No. This is a property of the amino group.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334226;


		
		

		
			
			p.question = "Which of the following functional groups is associated with a release of energy that cells can harvest to perform many functions?\n (<script type=\"text/javascript\">ebook(\'0403\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "amino",
				false,
				"No. Consider which group is associated with the molecule ATP.");
			
				p.addAnswer(2, "phosphate",
				true,
				"Correct. Cleaving a phosphate group from ATP releases energy that is used to perform many cellular functions.");
			
				p.addAnswer(3, "sulfhydryl",
				false,
				"No. Consider which group is associated with the molecule ATP.");
			
				p.addAnswer(4, "hydroxyl",
				false,
				"No. Consider which group is associated with the molecule ATP.");
			
				p.addAnswer(5, "carboxyl",
				false,
				"No. Consider which group is associated with the molecule ATP.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334227;


		
		

		
			
			p.question = "Which functional group would you predict is part of abscisic acid (ABA)? (<script type=\"text/javascript\">ebook(\'0403\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "carboxyl",
				true,
				"Correct. Compounds containing the carboxyl functional group (-COOH) are known as carboxylic acids or organic acids. They can donate a hydrogen ion (proton) to a solution.");
			
				p.addAnswer(2, "hydroxyl",
				false,
				"No. The hydroxyl functional group does not donate protons.");
			
				p.addAnswer(3, "carbonyl",
				false,
				"No. The carbonyl functional group does not donate protons.");
			
				p.addAnswer(4, "amino",
				false,
				"No. The amino functional group is a proton acceptor, not a proton donator.");
			
				p.addAnswer(5, "sulfhydryl",
				false,
				"No. The sulfhydryl functional group (-SH) does not donate protons.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334228;


		
		

		
			
			p.question = "The ionized or dissociated carboxyl group may be written as _____. (<script type=\"text/javascript\">ebook(\'0403\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "-COOH",
				false,
				"No. This is the nonionized or nondissociated form of the carboxyl functional group.");
			
				p.addAnswer(2, "-OH",
				false,
				"No. This is the hydroxyl functional group.");
			
				p.addAnswer(3, "-COO<sup>-</sup>",
				true,
				"Correct. The carboxyl functional group (-COOH) is an oxygen atom double-bonded to a carbon atom that is also bonded to a hydroxyl group. When a proton or hydrogen ion dissociates from the group, the negatively charged -COO<sup>-</sup> is the result.");
			
				p.addAnswer(4, "NH<sub>4</sub><sup>+</sup>",
				false,
				"No. This is the ammonium ion.");
			
				p.addAnswer(5, "-C=O",
				false,
				"No. This is the carbonyl functional group.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334229;


		
		

		
			
			p.question = "Which of the following groups is capable of hydrogen bonding with an oxygen atom on another functional group? (<script type=\"text/javascript\">ebook(\'0403\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "amino",
				false,
				"No. Amino groups are polar, but there is a better answer.");
			
				p.addAnswer(2, "hydroxyl",
				false,
				"No. Hydroxyl groups are polar, but there is a better answer.");
			
				p.addAnswer(3, "carboxylic acid",
				false,
				"No. Carboxyl groups are polar, but there is a better answer.");
			
				p.addAnswer(4, "sulfhydryl",
				false,
				"No. Sulfhydryl groups are polar, but there is a better answer.");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct. All of the above functional groups are polar, thus capable of hydrogen bonding with the oxygen of another molecule.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334230;


		
		

		
			
			p.question = "Choose the pair of terms that complete this sentence about functional groups in organic chemistry: Carboxyl is to ______ as ______ is to base.\n (<script type=\"text/javascript\">ebook(\'0403\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "acid; carbonyl",
				false,
				"No. This answer is partially correct. The carboxyl functional group can donate a proton (hydrogen ion) to a solution; however, the carbonyl functional group cannot accept a proton (hydrogen ion) from a solution.");
			
				p.addAnswer(2, "sulfhydryl; carbonyl",
				false,
				"No. The sulfhydryl functional group cannot donate a proton (hydrogen ion) to a solution. The carbonyl functional group cannot accept a proton (hydrogen ion) from solution.");
			
				p.addAnswer(3, "acid; amino",
				true,
				"Correct. A carboxyl group has acidic properties because it can donate a proton (hydrogen ion) to a solution. The amino group acts as a base because it can pick up or accept a proton (hydrogen ion) from a solution.");
			
				p.addAnswer(4, "hydroxyl; amino",
				false,
				"No. This answer is partially correct. The hydroxyl functional group cannot donate a proton (hydrogen ion) to a solution, but the amino group can accept a proton (hydrogen ion) from a solution.");
			
				p.addAnswer(5, "ketone; phosphate",
				false,
				"No. A ketone is a carbonyl type of functional group; hence, it cannot donate a proton (hydrogen ion) to a solution. The phosphate functional group can donate protons (hydrogen ions) to a solution.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334231;


		
		

		
			
			p.question = "Which of these is a thiol? (<script type=\"text/javascript\">ebook(\'0403\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "-SH",
				false,
				"No. This is the sulfhydryl functional group. The presence of this group in a molecule would make the molecule a thiol. This is only a functional group and not a molecule.");
			
				p.addAnswer(2, "-COH",
				false,
				"No. This is the carbonyl functional group.");
			
				p.addAnswer(3, "-OH",
				false,
				"No. This is the hydroxyl functional group.");
			
				p.addAnswer(4, "-NH<sub>2</sub>",
				false,
				"No. This is the amino functional group.");
			
				p.addAnswer(5, "none of the above",
				true,
				"Correct. A thiol is a molecule containing a sulfhydryl functional group.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334232;


		
		

		
			
			p.question = "What is ATP\'s importance in the cell?\n (<script type=\"text/javascript\">ebook(\'0403\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "ATP contains a long hydrocarbon tail and is important in storing energy.",
				false,
				"No. Although ATP is said to store energy, it does so in the bonds linking phosphate groups, not in carbon-hydrogen bonds.");
			
				p.addAnswer(2, "ATP can add phosphate groups, thereby releasing energy that can be used in cellular processes.",
				false,
				"No. Energy is released from ATP when a phosphate group is removed.");
			
				p.addAnswer(3, "ATP stores the potential to react with water, thereby removing a phosphate group and releasing energy for cellular processes.",
				true,
				"Correct. ATP releases energy during a hydrolysis reaction that removes a phosphate group.");
			
				p.addAnswer(4, "ATP stores energy in carbonyl groups. When a carbonyl group is removed, energy is released to be used in cellular processes.",
				false,
				"No. ATP contains three phosphate groups, not carbonyl groups.");
			
				p.addAnswer(5, "ATP is an important component of cell membranes because it is nonpolar and hydrophobic.",
				false,
				"No. ATP is the energy currency in the cell, not a component of cell membranes.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334233;


		
		

		
			
			p.question = "What are the six most important chemical elements of life? (<script type=\"text/javascript\">ebook(\'04RV\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Carbon, nitrogen, calcium, oxygen, phosphate, iron.",
				false,
				"No. Calcium and iron are important elements for living organisms, but they don\'t make the list.");
			
				p.addAnswer(2, "Carbon, nitrogen, oxygen, calcium, phosphate, hydrogen",
				false,
				"No. Regardless of what the milk advertisements say, calcium is not on the list.");
			
				p.addAnswer(3, "Carbon, nitrogen, sulfur, hydrogen, iron, magnesium",
				false,
				"No. Iron and magnesium are important trace elements, but they are not on the list.");
			
				p.addAnswer(4, "Carbon, nitrogen, oxygen, hydrogen, phosphate, sulfur",
				true,
				"Correct. These are all capable of forming strong covalent bonds, important in building large, complex molecules.");
			
				p.addAnswer(5, "Carbon, nitrogen, calcium, zinc, iron, hydrogen",
				false,
				"No. Calcium, zinc, and iron are all important elements, but they are not on the list.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

