

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "12: The Cell Cycle > Practice Test";
	ak.quiz_loc_with_commas = "12: The Cell Cycle, Practice Test";
	ak.quiz_title = "Practice Test";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 40;
	ak.non_essay_total = 40;
	ak.scored_item_total = 40;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334742;


		
		

		
			
			p.question = "The person credited with first recognizing (in the 1860s) that living cells cannot arise spontaneously, but arise only from previously existing cells, is _____. (<script type=\"text/javascript\">ebook(\'12OV\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Louis Pasteur",
				false,
				"No. Pasteur, among other things, falsified spontaneous generation.");
			
				p.addAnswer(2, "Robert Hooke",
				false,
				"No. Hooke was the discoverer of the cell.");
			
				p.addAnswer(3, "Rudolf Virchow",
				true,
				"Correct. In 1855 Rudolf Virchow stated, \"Where a cell exists, there must have been a preexisitng cell.\"");
			
				p.addAnswer(4, "Anton van Leeuwenhoek",
				false,
				"No. Leeuwenhoek discovered single-celled organisms.");
			
				p.addAnswer(5, "Watson",
				false,
				"No. Along with Crick, Watson determined the structure of DNA.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334743;


		
		

		
			
			p.question = "The function of the cell cycle is to produce daughter cells that _____. (<script type=\"text/javascript\">ebook(\'1201\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "are genetically identical to the parent cell (assuming no mutation has occurred)",
				true,
				"Correct. Cell division involves the distribution of identical genetic material (DNA) to two daughter chromosomes.");
			
				p.addAnswer(2, "have the same number of chromosomes as the parent cell but not the same genetic content",
				false,
				"No. This choice is partially correct.");
			
				p.addAnswer(3, "have a random assortment of maternal and paternal chromosomes",
				false,
				"No. Both daughter cells of a mitotic division have complete sets of maternal and paternal chromosomes identical to those of the parent cell.");
			
				p.addAnswer(4, "have the same number of chromatids as the parent cell had chromosomes",
				false,
				"No. Consider the structure of a chromatid.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334744;


		
		

		
			
			p.question = "Sister chromatids _____. (<script type=\"text/javascript\">ebook(\'1201\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "are created when DNA is replicated",
				false,
				"No. Although this response is correct, there is a better choice.");
			
				p.addAnswer(2, "are attached at the centromere prior to division",
				false,
				"No. Although this response is correct, there is a better choice.");
			
				p.addAnswer(3, "are separated during mitosis",
				false,
				"No. Although this response is correct, there is a better choice.");
			
				p.addAnswer(4, "have matching copies of the chromosome\'s DNA",
				false,
				"No. Although this response is correct, there is a better choice.");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334745;


		
		

		
			
			p.question = "The complex of DNA and protein that makes up a eukaryotic chromosome is properly called _____. (<script type=\"text/javascript\">ebook(\'1201\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a chromatid",
				false,
				"No. A chromatid is one of two duplicated chromosomes.");
			
				p.addAnswer(2, "a chloroplast",
				false,
				"No. A chloroplast is an organelle found in photosynthetic organisms.");
			
				p.addAnswer(3, "chromatin",
				true,
				"Correct. The DNA-protein complex called chromatin is organized into a long, thin fiber.");
			
				p.addAnswer(4, "a chromoplast",
				false,
				"No. This is a pigment-storing organelle.");
			
				p.addAnswer(5, "a centrosome",
				false,
				"No. The centrosome is the organelle from which microtubules originate.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334746;


		
		

		
			
			p.question = "The region of a chromosome holding the two double strands of replicated DNA together is called _____. (<script type=\"text/javascript\">ebook(\'1201\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "chromatin",
				false,
				"No. Chromatin is a complex of DNA and protein.");
			
				p.addAnswer(2, "a centriole",
				false,
				"No. Centrioles are components of centrosomes.");
			
				p.addAnswer(3, "a centromere",
				true,
				"Correct. The chromosome has a narrow \"waist\" at a specialized region, called the centromere, where the two chromatids are attached to each other.");
			
				p.addAnswer(4, "a chromatid",
				false,
				"No. A duplicated chromosome is composed of two chromatids.");
			
				p.addAnswer(5, "an aster",
				false,
				"No. An aster is a microtubule array that radiates from a centrosome.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334747;


		
		

		
			
			p.question = "If an intestinal cell in a grasshopper contains 24 chromosomes, a grasshopper sperm cell would contain _____ chromosomes. (<script type=\"text/javascript\">ebook(\'1201\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "3",
				false,
				"No. The production of gametes by meiosis produces cells with half the chromosome number of a somatic cell. After fertilization, the diploid chromosome number is restored.");
			
				p.addAnswer(2, "6",
				false,
				"No. The production of gametes by meiosis produces cells with half the chromosome number of a somatic cell. After fertilization, the diploid chromosome number is restored.");
			
				p.addAnswer(3, "12",
				true,
				"Correct. The production of gametes by meiosis produces cells with half the chromosome number of a somatic cell. After fertilization, the diploid chromosome number is restored.");
			
				p.addAnswer(4, "24",
				false,
				"No. If sperm cells were produced by mitosis, the next generation of grasshoppers would have 48 chromosomes, rather than 24.");
			
				p.addAnswer(5, "48",
				false,
				"No. Sperm and egg cells are produced by a type of division that reduces the number of chromosomes.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334748;


		
		

		
			
			p.question = "The centromere is a region in which _____. (<script type=\"text/javascript\">ebook(\'1201\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "chromosomes become aligned during metaphase",
				false,
				"No. Chromosomes align along the metaphase plate.");
			
				p.addAnswer(2, "microtubules are fastened to the centrioles during anaphase",
				false,
				"No. Microtubules are fastened to the kinetochore during anaphase.");
			
				p.addAnswer(3, "the new cell plate forms in telophase",
				false,
				"No. The cell plate forms at a cell\'s equatorial plane.");
			
				p.addAnswer(4, "sister chromatids are attached to one another in prophase",
				true,
				"Correct. The chromosome has a narrow \"waist\" at a specialized region called the centromere, where sister chromatids are attached.");
			
				p.addAnswer(5, "the chromosomes are connected to the cell plate in metaphase",
				false,
				"No. Chromosomes do not connect to the cell plate.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334749;


		
		

		
			
			p.question = "How many maternal chromosomes are present in a somatic human cell not engaged in cell division? (<script type=\"text/javascript\">ebook(\'1201\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "23",
				true,
				"Correct. Human somatic cells contain a total of 46 chromosomes, half of which are maternally derived.");
			
				p.addAnswer(2, "46",
				false,
				"No. Each human somatic cell has a total of 46 chromosomes. Only half are maternal chromosomes.");
			
				p.addAnswer(3, "92",
				false,
				"No. Human somatic cells have a total of 46 chromosomes. Only half are maternal chromosomes.");
			
				p.addAnswer(4, "184",
				false,
				"No. Human somatic cells have a total of 46 chromosomes. Only half are maternal chromosomes.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334750;


		
		

		
			
			p.question = "A cell entering the cell cycle with 32 chromosomes will produce two daughter cells, each with _____. (<script type=\"text/javascript\">ebook(\'1201\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "16 chromosomes",
				false,
				"No. Cells with 16 chromosomes would be produced by meiosis.");
			
				p.addAnswer(2, "32 chromosomes",
				true,
				"Correct. Cell division involves the distribution of identical genetic material to two daughter cells.");
			
				p.addAnswer(3, "32 pairs of chromosomes",
				false,
				"No. This would mean that each daughter cell has 64 chromosomes.");
			
				p.addAnswer(4, "64 pairs of chromosomes",
				false,
				"No. This would mean that each daughter cell has 128 chromosomes.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334751;


		
		

		
			
			p.question = "\"Cytokinesis\" refers to _____. (<script type=\"text/javascript\">ebook(\'1201\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "division of the entire cell",
				false,
				"No. The division of the nucleus precedes the division of the rest of the cell.");
			
				p.addAnswer(2, "division of the nucleus",
				false,
				"No. The nucleus does not divide during cytokinesis.");
			
				p.addAnswer(3, "division of the cytoplasm",
				true,
				"Correct. Cytokinesis is the division of the cytoplasm that follows the mitotic division of the nucleus.");
			
				p.addAnswer(4, "reduction in the number of chromosomes",
				false,
				"No. Cytokinesis does not involve chromosomes.");
			
				p.addAnswer(5, "movement of a cell from one place to another",
				false,
				"No. In a sense, cell movement is involved, but this is not the best choice.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334752;


		
		

		
			
			p.question = "Chromatids are _____. (<script type=\"text/javascript\">ebook(\'1201\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "found only in aberrant chromosomes",
				false,
				"No. Chromatids are not found within chromosomes.");
			
				p.addAnswer(2, "held together by the centrioles",
				false,
				"No. Centrioles are associated in animal cells with the centrosomes.");
			
				p.addAnswer(3, "identical copies of each other if they are part of the same chromosome",
				true,
				"Correct. Each duplicated chromosome consists of two identical sister chromatids.");
			
				p.addAnswer(4, "the bacterial equivalent of eukaryotic chromosomes",
				false,
				"No. Bacterial cells have a single, circular chromosome, but chromatids are found only in eukaryotic cells.");
			
				p.addAnswer(5, "composed of RNA",
				false,
				"No. Chromatids are composed of DNA and protein.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334753;


		
		

		
			
			p.question = "If a cell contains 60 chromatids at the start of mitosis, how many chromosomes will be found in each daughter cell at the completion of the cell cycle? (<script type=\"text/javascript\">ebook(\'1202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "15",
				false,
				"No. The cell cycle does not reduce the chromosomal complement.");
			
				p.addAnswer(2, "30",
				true,
				"Correct. In this case, mitosis starts with 30 chromosomes, each of which consists of two chromatids. At the completion of mitosis, each daughter cell will contain 30 chromosomes.");
			
				p.addAnswer(3, "45",
				false,
				"No. At the completion of the cell cycle, each daughter cell will have the same chromosomal complement as the parent cell.");
			
				p.addAnswer(4, "60",
				false,
				"No. Consider that interphase precedes mitosis.");
			
				p.addAnswer(5, "120",
				false,
				"No. At the completion of the cell cycle, each daughter cell will have the same chromosomal complement as the parent cell.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334754;


		
		

		
			
			p.question = "A biochemist measured the amount of DNA in cells growing in the laboratory and found that the quantity of DNA in the cells doubled _____. (<script type=\"text/javascript\">ebook(\'1202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "between prophase and anaphase",
				false,
				"No. This period is characterized by fragmentation of the nuclear envelope, condensation of chromosomes, and their alignment on the metaphase plate.");
			
				p.addAnswer(2, "between the G<sub>1</sub> and G<sub>2</sub> phases",
				true,
				"Correct. Between these two phases of the cell cycle, the DNA is replicated during the S phase.");
			
				p.addAnswer(3, "during the M phase of the cell cycle",
				false,
				"No. Duplicated chromosomes are separated from each other during the M phase.");
			
				p.addAnswer(4, "between the G<sub>2</sub> phase and prophase",
				false,
				"No. During this time period, the chromosomes begin to condense and the nucleoli disappear.");
			
				p.addAnswer(5, "between anaphase and telophase",
				false,
				"No. During this time, period, sister chromatids are separated to the opposite poles of the cell and reorganized into new nuclei.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334755;


		
		

		
			
			p.question = "A cell biologist carefully measured the quantity of DNA in grasshopper cells growing in cell culture. Cells examined during the G<sub>2</sub> phase of the cell cycle contained 200 units of DNA. What would be the amount of DNA at G<sub>1</sub> of the cell cycle in one of the grasshopper daughter cells? (<script type=\"text/javascript\">ebook(\'1202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "50 units",
				false,
				"No. Fifty units would be the quantity of DNA following meiosis.");
			
				p.addAnswer(2, "100 units",
				true,
				"Correct. Recall that G<sub>2</sub> follows S and that during the S phase, DNA is replicated.");
			
				p.addAnswer(3, "between 50 and 100 units",
				false,
				"No. Cell division is very exact. The amount of DNA would never be indicated by a range.");
			
				p.addAnswer(4, "200 units",
				false,
				"No. Remember, G<sub>2</sub> immediately precedes mitosis; DNA replication has already occurred.");
			
				p.addAnswer(5, "400 units",
				false,
				"No. The 200 units of DNA in the sister chromatids of cells in G<sub>2</sub> will be divided equally during the M phase, resulting in daughter cells each containing 100 units of DNA.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334756;


		
		

		
			
			p.question = "During interphase, the genetic material of a typical eukaryotic cell is _____. (<script type=\"text/javascript\">ebook(\'1202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "dispersed in the nucleus as long strands of chromatin",
				true,
				"Correct. During interphase, the chromosomes cannot be distinguished individually because they are still in the form of loosely packed chromatin fibers.");
			
				p.addAnswer(2, "dispersed in the cytoplasm as long strands of chromatin",
				false,
				"No. Consider the location of the genetic material during interphase.");
			
				p.addAnswer(3, "condensed and the chromosomes are often visible under the light microscope",
				false,
				"No. Compare the events of interphase and early mitosis.");
			
				p.addAnswer(4, "attached to microtubule spindle fibers",
				false,
				"No. This occurs during prophase.");
			
				p.addAnswer(5, "transported through the nuclear pores",
				false,
				"No. RNA and proteins are transported through the nuclear pores.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334757;


		
		

		
			
			p.question = "DNA replication occurs in _____. (<script type=\"text/javascript\">ebook(\'1202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "prophase of both mitosis and meiosis",
				false,
				"No. In meiosis, the genetic material is doubled once and halved twice.");
			
				p.addAnswer(2, "metaphase of meiosis only",
				false,
				"No. You need to review the stages of the cell cycle.");
			
				p.addAnswer(3, "the S phase of interphase in both somatic and reproductive cells",
				true,
				"Correct. Chromosomes are duplicated only during the S phase (\"S\" stands for synthesis of DNA).");
			
				p.addAnswer(4, "the G<sub>1</sub> phase of interphase in reproductive cells only",
				false,
				"No. Review the phases of interphase.");
			
				p.addAnswer(5, "the cytokinesis portion of the cell\'s life cycle",
				false,
				"No. This is when a single cell completes its division into two daughter cells.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334758;


		
		

		
			
			p.question = "Chromatids form _____. (<script type=\"text/javascript\">ebook(\'1202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "during G<sub>1</sub>",
				false,
				"No. DNA synthesis does not occur during G<sub>1</sub>.");
			
				p.addAnswer(2, "during G<sub>2</sub>",
				false,
				"No. DNA synthesis does not occur during G<sub>2</sub>.");
			
				p.addAnswer(3, "during the S phase",
				true,
				"Correct. Each duplicated chromosome consists of two sister chromatids, produced during the S phase.");
			
				p.addAnswer(4, "at the start of mitosis",
				false,
				"No. Mitosis excludes interphase.");
			
				p.addAnswer(5, "at the start of meiosis",
				false,
				"No. Meiosis excludes interphase.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334759;


		
		

		
			
			p.question = "If a somatic human cell is just about to divide, it has _____ chromatids. (<script type=\"text/javascript\">ebook(\'1202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "92",
				true,
				"Correct. Human somatic cells have 92 chromatids just prior to cell division due to the replication of the 46 chromosomes that occurred during the S phase.");
			
				p.addAnswer(2, "23",
				false,
				"No. Consider the number of chromosomes in a human somatic cell and review what takes place during the S phase.");
			
				p.addAnswer(3, "46",
				false,
				"No. This is the number of chromosomes in human somatic cells.");
			
				p.addAnswer(4, "0",
				false,
				"No. Sister chromatids remain paired until anaphase of mitosis.");
			
				p.addAnswer(5, "There is insufficient information to answer the question.",
				false,
				"No. This chapter contains all the information you need to answer the question.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334760;


		
		

		
			
			p.question = "Which one of the following does <b>not</b> occur during mitosis? (<script type=\"text/javascript\">ebook(\'1202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the movement of chromosomes to opposite poles",
				false,
				"No. This occurs during anaphase.");
			
				p.addAnswer(2, "condensed chromatin",
				false,
				"No. This occurs during prophase of mitosis.");
			
				p.addAnswer(3, "separation of chromatids",
				false,
				"No. This occurs during anaphase.");
			
				p.addAnswer(4, "replication of chromosomes",
				true,
				"Correct. The DNA of the chromosomes is replicated in the S phase before mitosis.");
			
				p.addAnswer(5, "alignment of chromosomes along the cell\'s equator",
				false,
				"No. This occurs during metaphase.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334761;


		
		

		
			
			p.question = "During what phase in the cell cycle, would you find the most DNA per cell? (<script type=\"text/javascript\">ebook(\'1202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "G<sub>1</sub>",
				false,
				"No. G<sub>1</sub> occurs prior to the duplication of the genetic material.");
			
				p.addAnswer(2, "G<sub>2</sub>",
				true,
				"Correct. Chromosomes are duplicated only during the S phase (\"S\" stands for synthesis of DNA). The phase following completion of the S phase is G<sub>2</sub>.");
			
				p.addAnswer(3, "S<sub>1</sub>",
				false,
				"No. There is no such phase.");
			
				p.addAnswer(4, "S",
				false,
				"No. Although DNA synthesis is indeed taking place during the S phase, it is not until this phase is complete that the cell has the maximum amount of DNA.");
			
				p.addAnswer(5, "prophase II",
				false,
				"No. Prophase II is not a phase of the cell cycle.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334762;


		
		

		
			
			p.question = "In telophase of mitosis, the mitotic spindle breaks down and the chromatin uncoils. This is essentially the opposite of what happens in _____. (<script type=\"text/javascript\">ebook(\'1202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "prophase",
				true,
				"Correct. During prophase, we observe the formation of the spindle, the condensation of chromatin, and the disappearance of the nucleolus.");
			
				p.addAnswer(2, "interphase",
				false,
				"No. During interphase, the chromatin cannot be seen, and the spindle has not yet begun to form.");
			
				p.addAnswer(3, "metaphase",
				false,
				"No. During metaphase, the chromosomes line up on the metaphase plate.");
			
				p.addAnswer(4, "S phase",
				false,
				"No. The S phase is a part of the cell cycle that precedes mitosis.");
			
				p.addAnswer(5, "anaphase",
				false,
				"No. During anaphase, the paired centromeres separate, and the once joined sister chromatids begin to move to opposite poles of the cell.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334763;


		
		

		
			
			p.question = "Which of the following phases of mitosis is essentially the opposite of prometaphase in terms of the nuclear envelope? (<script type=\"text/javascript\">ebook(\'1202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "telophase",
				true,
				"Correct. In prometaphase the nuclear envelope fragments and the kinetochores attach to microtubules. During telophase, fragments of the nuclear envelope begin to reassemble along with portions of the endomembrane system.");
			
				p.addAnswer(2, "metaphase",
				false,
				"No. In prometaphase the nuclear envelope fragments and the kinetochores attach to microtubules. What happens in metaphase?");
			
				p.addAnswer(3, "S phase",
				false,
				"No. In prometaphase the nuclear envelope fragments and the kinetochores attach to microtubules. What happens in the S phase?");
			
				p.addAnswer(4, "interphase",
				false,
				"No. In prometaphase the nuclear envelope fragments and the kinetochores attach to microtubules. What happens in interphase?");
			
				p.addAnswer(5, "anaphase",
				false,
				"No. In prometaphase the nuclear envelope fragments and the kinetochores attach to microtubules. What happens in anaphase?");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334764;


		
		

		
			
			p.question = "Assume that you are dealing with a species in which the number of chromosomes in each somatic cell is 14. How many sister chromatids are present in the early telophase of mitosis? (<script type=\"text/javascript\">ebook(\'1202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "0",
				true,
				"Correct. In this case, mitosis starts with 14 chromosomes, each of which consists of two chromatids, because the cell has been through the S phase. By telophase, the chromatids have separated and the individual units of DNA (now called chromosomes) are arriving at the poles. There are no chromatids at this point.");
			
				p.addAnswer(2, "7",
				false,
				"No. Review the relationship between chromosomes and chromatids.");
			
				p.addAnswer(3, "14",
				false,
				"No. Review the relationship between chromosomes and chromatids.");
			
				p.addAnswer(4, "28",
				false,
				"No. Review the relationship between chromosomes and chromatids.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334765;


		
		

		
			
			p.question = "At which point in the cell cycle do centrosomes begin to move apart to two poles of the cell in a dividing human skin cell? (<script type=\"text/javascript\">ebook(\'1202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "S phase",
				false,
				"No. The genetic material duplicates during the S phase.");
			
				p.addAnswer(2, "G<sub>2</sub> phase",
				false,
				"No. This is a cell cycle checkpoint.");
			
				p.addAnswer(3, "prophase",
				true,
				"Correct. The centrosomes move away from each other during prophase, apparently propelled along the surface of the nucleus by the lengthening bundles of microtubules between them.");
			
				p.addAnswer(4, "metaphase",
				false,
				"No. During this phase, the chromosomes align along the metaphase plate.");
			
				p.addAnswer(5, "anaphase",
				false,
				"No. This is the phase during which the centromere divides and former sister chromatids migrate to opposite poles of the cell.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334766;


		
		

		
			
			p.question = "The phase of mitosis during which the chromosomes move toward separate poles of the cell is _____. (<script type=\"text/javascript\">ebook(\'1202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "telophase",
				false,
				"No. Telophase essentially undoes the events of prophase and prometaphase.");
			
				p.addAnswer(2, "anaphase",
				true,
				"Correct. Anaphase begins when the paired centromeres of each chromosome separate, liberating the sister chromatids, which begin moving toward opposite poles of the cell.");
			
				p.addAnswer(3, "metaphase",
				false,
				"No. During this phase, the chromosomes align along the metaphase plate.");
			
				p.addAnswer(4, "prophase",
				false,
				"No. The question does not refer to any of the events of prophase.");
			
				p.addAnswer(5, "prometaphase",
				false,
				"No. The question does not refer to any of the events of prometaphase.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334767;


		
		

		
			
			p.question = "One event occurring during prophase is _____. (<script type=\"text/javascript\">ebook(\'1202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the beginning of the formation of a spindle apparatus",
				true,
				"Correct. During prophase, the mitotic spindle begins to form.");
			
				p.addAnswer(2, "the synthesis of a new nuclear envelope",
				false,
				"No. This occurs during telophase.");
			
				p.addAnswer(3, "the alignment of chromosomes in a single plane",
				false,
				"No. This occurs during metaphase.");
			
				p.addAnswer(4, "cytokinesis",
				false,
				"No. This usually accompanies telophase.");
			
				p.addAnswer(5, "division of the centromere",
				false,
				"No. This occurs during anaphase.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334768;


		
		

		
			
			p.question = "During anaphase of mitosis _____. (<script type=\"text/javascript\">ebook(\'1202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the centromeres divide",
				false,
				"No. Although this response is correct, there is a better choice.");
			
				p.addAnswer(2, "the centrioles are at opposite poles",
				false,
				"No. Although this response is correct, there is a better choice.");
			
				p.addAnswer(3, "a spindle made of microtubules is present",
				false,
				"No. Although this response is correct, there is a better choice.");
			
				p.addAnswer(4, "identical chromatids move to opposite poles",
				false,
				"No. Although this response is correct, there is a better choice.");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct. Anaphase begins when the paired centromeres of each chromosome separate, liberating the sister chromatids, which begin moving toward opposite poles of the cell.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334769;


		
		

		
			
			p.question = "Which one of the following represents a <b>mismatch</b> or incorrect description? (<script type=\"text/javascript\">ebook(\'1202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "prophase: chromosomes become more tightly coiled",
				false,
				"No. This does occur during prophase.");
			
				p.addAnswer(2, "metaphase: chromosomes line up on the equatorial plane",
				false,
				"No. This does occur during metaphase.");
			
				p.addAnswer(3, "metaphase: the nuclear envelope disappears",
				true,
				"Correct. During prometaphase, the nuclear envelope fragments.");
			
				p.addAnswer(4, "anaphase: there is movement of the chromosomes to the poles",
				false,
				"No. This does occur during anaphase.");
			
				p.addAnswer(5, "telophase: chromosomes become more extended",
				false,
				"No. This does occur during telophase.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334770;


		
		

		
			
			p.question = "Sister chromatids separate during _____. (<script type=\"text/javascript\">ebook(\'1202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "anaphase",
				true,
				"Correct. Anaphase begins when the paired centromeres of each chromosome separate, liberating the sister chromatids, which begin moving toward opposite poles of the cell.");
			
				p.addAnswer(2, "G<sub>1</sub> phase",
				false,
				"No. This phase encompasses cell growth and contains a cell cycle checkpoint.");
			
				p.addAnswer(3, "G<sub>2</sub> phase",
				false,
				"No. This phase contains a cell cycle checkpoint.");
			
				p.addAnswer(4, "metaphase",
				false,
				"No. During this phase, the chromosomes align along the metaphase plate.");
			
				p.addAnswer(5, "prophase",
				false,
				"No. The question does not describe prophase.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334771;


		
		

		
			
			p.question = "In animal cell mitosis, the cleavage furrow forms during _____. (<script type=\"text/javascript\">ebook(\'1202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "anaphase",
				false,
				"No. Anaphase begins when the paired centromeres of each chromosome separate, liberating the sister chromatids, which begin moving toward opposite poles of the cell.");
			
				p.addAnswer(2, "the G<sub>1</sub> phase",
				false,
				"No. This phase encompasses cell growth and is a cell cycle checkpoint.");
			
				p.addAnswer(3, "cytokinesis",
				true,
				"Correct. Cytokinesis is usually well under way by telophase. In animal cells, cytokinesis involves the formation of a cleavage furrow, which pinches the cell in two.");
			
				p.addAnswer(4, "metaphase",
				false,
				"No. During this phase, the chromosomes align along the metaphase plate.");
			
				p.addAnswer(5, "prophase",
				false,
				"No. The question does not describe prophase.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334772;


		
		

		
			
			p.question = "At which stage of mitosis are chromosomes lined up in one plane in preparation for their separation to opposite poles of the cell? (<script type=\"text/javascript\">ebook(\'1202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "prophase",
				false,
				"No. The question does not describe prophase.");
			
				p.addAnswer(2, "metaphase",
				true,
				"Correct. The chromosomes convene on the metaphase plate, an imaginary plane that is equidistant from the spindle\'s two poles.");
			
				p.addAnswer(3, "anaphase",
				false,
				"No. Anaphase begins when the paired centromeres of each chromosome separate, liberating the sister chromatids, which begin moving toward opposite poles of the cell.");
			
				p.addAnswer(4, "telophase",
				false,
				"No. Telophase essentially undoes the events of prophase and prometaphase.");
			
				p.addAnswer(5, "interphase",
				false,
				"No. Interphase is not a part of mitosis.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334773;


		
		

		
			
			p.question = "You would know a dividing cell was a plant cell rather than an animal cell if you saw that _____. (<script type=\"text/javascript\">ebook(\'1202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "it had formed a cell plate",
				true,
				"Correct. The cell plate, which divides the cytoplasm in two, forms during the telophase of mitosis in a plant cell.");
			
				p.addAnswer(2, "it had two pairs of centrioles during prophase",
				false,
				"No. Plant cells lack centrioles.");
			
				p.addAnswer(3, "it had microtubules",
				false,
				"No. Both plant and animal cells have microtubules.");
			
				p.addAnswer(4, "the nucleolus was visible during metaphase",
				false,
				"No. Nucleoli are dispersed at this time in both plant and animal cells.");
			
				p.addAnswer(5, "it had formed a cleavage furrow",
				false,
				"No. Animal cells divide by forming a cleavage furrow.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334774;


		
		

		
			
			p.question = "Which one of the following processes does <b>not</b> occur in dividing bacteria? (<script type=\"text/javascript\">ebook(\'1202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "replication of DNA",
				false,
				"No. This process does occur in dividing bacteria, assuring that the daughter cells have the same genetic complement as the parental cell.");
			
				p.addAnswer(2, "separation of the origins of replication",
				false,
				"No. This is an event of bacterial cell division.");
			
				p.addAnswer(3, "mitosis",
				true,
				"Correct. Mitosis does <b>not</b> occur in dividing bacteria. Mitosis might have had its origins in simpler bacterial mechanisms of cell reproduction. Prokaryotes (bacteria) reproduce by a type of cell division called binary fission.");
			
				p.addAnswer(4, "binary fission",
				false,
				"No. This is the name given to bacterial cell division.");
			
				p.addAnswer(5, "inward growth of the plasma membrane",
				false,
				"No. This is an event of bacterial cell division.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334775;


		
		

		
			
			p.question = "During binary fission in a bacterium _____. (<script type=\"text/javascript\">ebook(\'1202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the two DNA molecules float free in the cell and are guided to daughter cells by a spindle-like apparatus",
				false,
				"No. Bacteria lack a spindle-like apparatus.");
			
				p.addAnswer(2, "the origins of replication move apart",
				true,
				"Correct. This occurs during binary fission.");
			
				p.addAnswer(3, "the two DNA molecules divide in half, forming four DNA fragments",
				false,
				"No. Beginning at the origin of replication, the circular DNA molecule is replicated, forming two identical copies of the bacterial chromosome.");
			
				p.addAnswer(4, "the two DNA molecules attach to the centrioles",
				false,
				"No. Bacterial cells lack centrioles.");
			
				p.addAnswer(5, "the two DNA molecules break up into plasmids",
				false,
				"No. Beginning at the origin of replication, the circular DNA molecule is replicated, forming two identical copies of the bacterial chromosome.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334776;


		
		

		
			
			p.question = "Binary fission in bacterial cells involves _____. (<script type=\"text/javascript\">ebook(\'1202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "prophase, prometaphase, metaphase, anaphase, and telophase",
				false,
				"No. These are the stages of mitosis. Mitosis does not occur in bacterial cells.");
			
				p.addAnswer(2, "disintegration of the nuclear membrane",
				false,
				"No. Prokaryotes do not have a nucleus.");
			
				p.addAnswer(3, "distribution of a copy of the single parental chromosome to each daughter cell",
				true,
				"Correct. Prokaryotes reproduce by a type of cell division called binary fission, which involves replicating the single chromosome and distributing the copies equally to two daughter cells.");
			
				p.addAnswer(4, "formation of a cell plate",
				false,
				"No. Bacterial cells divide by inward growth of the plasma membrane. Cell plates form in plant cells.");
			
				p.addAnswer(5, "formation of a spindle apparatus",
				false,
				"No. Bacterial cells do not develop a spindle apparatus.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334777;


		
		

		
			
			p.question = "When a cell in S phase is fused with a cell in G<sub>1</sub>, _____. (<script type=\"text/javascript\">ebook(\'1203\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "DNA synthesis begins immediately in the original G<sub>1</sub> nucleus",
				true,
				"Correct. This observation indicates that cytoplasmic signals can participate in the regulation of the cell cycle.");
			
				p.addAnswer(2, "the replication of DNA occurring in the original S nucleus is terminated",
				false,
				"No. The cell in S phase has moved past the G<sub>1</sub> checkpoint.");
			
				p.addAnswer(3, "the two nuclei fuse and further division is arrested",
				false,
				"No. Because the cell in S phase has passed the G<sub>1</sub> checkpoint, it will continue to advance toward mitosis.");
			
				p.addAnswer(4, "the chromosomes of the original G<sub>1</sub> nucleus condense in preparation for mitosis",
				false,
				"No. Condensation occurs after the cell has passed the M-phase checkpoint, but before that can occur, the G<sub>2</sub> phase must be completed.");
			
				p.addAnswer(5, "the original G<sub>1</sub> cell will divide immediately",
				false,
				"No. The fused cells are now effectively one single cell. The original cell no longer exists; thus, it cannot divide on its own.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334778;


		
		

		
			
			p.question = "Tissue culture experiments with PDGF demonstrate that without this substance _____. (<script type=\"text/javascript\">ebook(\'1203\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "bacterial cells lose their resistance to antibiotics",
				false,
				"No. Perhaps you were thinking about the use of antibiotics in the medium used for tissue culture.");
			
				p.addAnswer(2, "cells divide in an uncontrolled fashion, confirming its role as a cell division inhibitor",
				false,
				"No. Actually, just the opposite is true. PDGF is a growth factor.");
			
				p.addAnswer(3, "fibroblasts fail to divide",
				true,
				"Correct. PDGF is a specific growth factor for fibroblasts.");
			
				p.addAnswer(4, "animal cells are unable to attach to the substratum",
				false,
				"No. However, it is true that animal cells must attach to a substrate before division can occur.");
			
				p.addAnswer(5, "the various kinases, such as MPF, are unable to bind to cyclin",
				false,
				"No. However, there are many cyclin-dependent kinases that participate in regulating cell division.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334779;


		
		

		
			
			p.question = "You would be unlikely to see which of the following human cells dividing? (<script type=\"text/javascript\">ebook(\'1203\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "nerve cell",
				true,
				"Correct. Nerve cells are quite complex and specialized. After reaching maturity, they enter the G<sub>0</sub> phase.");
			
				p.addAnswer(2, "skin cell",
				false,
				"No. Think of all the different times you cut or scratched your skin.");
			
				p.addAnswer(3, "cancer cell",
				false,
				"No. Cancer cells are characterized by the failure to recognize or respond to the signals that prevent cell division.");
			
				p.addAnswer(4, "cell from an embryo",
				false,
				"No. If this were true, it would be impossible for the embryo to grow.");
			
				p.addAnswer(5, "intestinal lining cell",
				false,
				"No. The lining of the intestine, and surfaces that directly contact the external environment, are replaced quite regularly.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334780;


		
		

		
			
			p.question = "Observations of cancer cells in culture support the hypothesis that cancer cells _____. (<script type=\"text/javascript\">ebook(\'1203\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "do not exhibit density-dependent inhibition",
				true,
				"Correct. Normal cells respond to density-dependent inhibition by growing in culture to form a single layer of cells.");
			
				p.addAnswer(2, "produce molecules that inhibit the growth factors required for cell division",
				false,
				"No. If they were inhibited, cell division could not occur.");
			
				p.addAnswer(3, "exhibit anchorage dependence",
				false,
				"No. Cancer cells are characterized by the lack of anchorage dependence.");
			
				p.addAnswer(4, "spend the majority of their time in the G<sub>0</sub> phase",
				false,
				"No. Cells in the G<sub>0</sub> phase have assumed a nondividing state.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. Only one of the choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334781;


		
		

		
			
			p.question = "What is the difference between a benign tumor and a malignant tumor? (<script type=\"text/javascript\">ebook(\'1203\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Benign tumors arise by transformation; malignant tumors do not.",
				false,
				"No. Both types of tumors arise when a single cell undergoes transformation.");
			
				p.addAnswer(2, "Cells of benign tumors do not metastasize; those of malignant tumors do.",
				true,
				"Correct. Cells of malignant tumors spread from their site of origin to other parts of the body.");
			
				p.addAnswer(3, "Cells of benign tumors metastasize; those of malignant tumors do not.",
				false,
				"No. Benign tumors do not metastasize.");
			
				p.addAnswer(4, "Benign tumors will not kill you; malignant tumors will.",
				false,
				"No. Consider an untreated or inoperable benign brain tumor.");
			
				p.addAnswer(5, "Benign tumors do not arise by transformation; malignant tumors do.",
				false,
				"No. Both types of tumors arise when a single cell undergoes transformation.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

