

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "30: Plant Diversity II: The Evolution of Seed Plants > Activities Quiz";
	ak.quiz_loc_with_commas = "30: Plant Diversity II: The Evolution of Seed Plants, Activities Quiz";
	ak.quiz_title = "Activities Quiz";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 15;
	ak.non_essay_total = 15;
	ak.scored_item_total = 15;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335786;


		
		

		
			
			p.question = "Which of these is a male gametophyte? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?30&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Pine Life Cycle</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/3001q.jpg\" ALT=\"Question #1\" BORDER=\"1\" >";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A",
				false,
				"This is an ovule.");
			
				p.addAnswer(2, "B",
				false,
				"This is a megasporangium.");
			
				p.addAnswer(3, "C",
				false,
				"This is a megasporocyte (megaspore mother cell).");
			
				p.addAnswer(4, "D",
				false,
				"This is a micropyle.");
			
				p.addAnswer(5, "E",
				true,
				"Pollen grains are male gametophytes.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335787;


		
		

		
			
			p.question = "In pines, the female gametophyte contains _____, each of which contains a(n) _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?30&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Pine Life Cycle</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "archegonia ... egg",
				true,
				"In pines, a megaspore repeatedly grows and divides, giving rise to a female gametophyte. The female gametophyte is the site in which egg-bearing gametophytes develop.");
			
				p.addAnswer(2, "archegonia ... sperm cell",
				false,
				"You are getting your sexes mixed up.");
			
				p.addAnswer(3, "antheridia ... egg",
				false,
				"You are getting your sexes mixed up.");
			
				p.addAnswer(4, "antheridia ... sperm cell",
				false,
				"The question is asking about female structures; this response is referring to male structures.");
			
				p.addAnswer(5, "microsporangia ... egg cell",
				false,
				"You are getting your sexes mixed up.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335788;


		
		

		
			
			p.question = "In pines, an embryo is a(n) _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?30&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Pine Life Cycle</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "seed",
				false,
				"An embryo is found within a seed.");
			
				p.addAnswer(2, "immature sporophyte",
				true,
				"The diploid embryo will develop into a seedling and then into a mature pine tree.");
			
				p.addAnswer(3, "food reserve for the immature sporophyte",
				false,
				"The immature sporophyte\'s food reserve is composed of gametophyte tissue.");
			
				p.addAnswer(4, "immature male gametophyte",
				false,
				"The embryo is diploid, while the gametophyte is haploid.");
			
				p.addAnswer(5, "immature female gametophyte",
				false,
				"The embryo is diploid, while the gametophyte is haploid.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335789;


		
		

		
			
			p.question = "In pine trees, pollen grains get to the ovule via the _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?30&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Pine Life Cycle</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "micropyle",
				true,
				"Pollen grains gain entry into the ovule via the micropyle.");
			
				p.addAnswer(2, "eggs",
				false,
				"An egg is found within an ovule.");
			
				p.addAnswer(3, "megaspore",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(4, "pollen cone",
				false,
				"Pollen cones produce pollen.");
			
				p.addAnswer(5, "integument",
				false,
				"The integument surrounds the megasporangium.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335790;


		
		

		
			
			p.question = "Which of these statements is true about the gametophyte tissue that surrounds the pine embryo? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?30&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Pine Life Cycle</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "It functions as a haploid food reserve.",
				true,
				"This gametophyte tissue is a source of nourishment for the embryo.");
			
				p.addAnswer(2, "It functions as a diploid food reserve.",
				false,
				"Gametophyte tissue is haploid.");
			
				p.addAnswer(3, "It functions as a triploid food reserve.",
				false,
				"Gametophyte tissue is haploid.");
			
				p.addAnswer(4, "It develops from the fusion of a microspore and a megaspore.",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(5, "It is the remnant of the pollen tube.",
				false,
				"No, it isn\'t.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335791;


		
		

		
			
			p.question = "Of the four haploid cells produced by a pine cone\'s megasporocyte (megaspore mother cell), _____ survive(s). (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?30&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Pine Life Cycle</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "one",
				true,
				"Correct.");
			
				p.addAnswer(2, "two",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(3, "three",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(4, "four",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(5, "integuments",
				false,
				"The integuments surround the megasporangium.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335792;


		
		

		
			
			p.question = "In the pine, microsporangia form _____ microspores by _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?30&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Pine Life Cycle</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "triploid ... fertilization",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(2, "diploid ... mitosis",
				false,
				"Cells in the microsporangia undergo meiosis, giving rise to haploid microspores.");
			
				p.addAnswer(3, "diploid ... meiosis",
				false,
				"Microspores are haploid.");
			
				p.addAnswer(4, "haploid ... mitosis",
				false,
				"Cells in the microsporangia undergo meiosis, giving rise to haploid microspores.");
			
				p.addAnswer(5, "haploid ... meiosis",
				true,
				"Diploid microsporangia form haploid microspores by meiosis.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335793;


		
		

		
			
			p.question = "Ovules are found within structure _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?30&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Angiosperm Life Cycle</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/3008q.jpg\" ALT=\"Question #8\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A",
				false,
				"This is a sepal.");
			
				p.addAnswer(2, "B",
				true,
				"Ovules are housed within ovaries.");
			
				p.addAnswer(3, "C",
				false,
				"This is a petal.");
			
				p.addAnswer(4, "D",
				false,
				"This is an anther.");
			
				p.addAnswer(5, "E",
				false,
				"This is a filament.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335794;


		
		

		
			
			p.question = "Which of these is unique to flowering plants? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?30&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Angiosperm Life Cycle</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a dominant sporophyte generation",
				false,
				"The sporophyte generation is dominant in seedless vascular plants and gymnosperms as well as angiosperms.");
			
				p.addAnswer(2, "an embryo surrounded by nutritive tissue",
				false,
				"You might want to review the activity on the pine life cycle.");
			
				p.addAnswer(3, "haploid gametophytes",
				false,
				"All gametophytes are haploid.");
			
				p.addAnswer(4, "double fertilization",
				true,
				"In flowering plants one sperm nucleus fertilizes the egg and the other sperm nucleus fuses with two other nuclei found within the ovule, thus forming triploid endosperm.");
			
				p.addAnswer(5, "pollen production",
				false,
				"You might want to review the activity on the pine life cycle.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335795;


		
		

		
			
			p.question = "The male gametophytes of flowering plants are also referred to as _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?30&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Angiosperm Life Cycle</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "endosperm",
				false,
				"Endosperm is a triploid tissue that serves as a food reserve.");
			
				p.addAnswer(2, "male sporophytes",
				false,
				"Gametophytes are haploid; sporophytes are diploid.");
			
				p.addAnswer(3, "megaspores",
				false,
				"Megaspores are female structures.");
			
				p.addAnswer(4, "pollen grains",
				true,
				"Pollen grains are male gametophytes.");
			
				p.addAnswer(5, "embryo sacs",
				false,
				"Embryo sacs are produced within ovules.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335796;


		
		

		
			
			p.question = "In flowering plants the integuments of the ovule develop into a(n) _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?30&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Angiosperm Life Cycle</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "endosperm",
				false,
				"Endosperm is formed when one sperm nucleus fuses with two of the nuclei found within the ovule.");
			
				p.addAnswer(2, "cotyledon",
				false,
				"Cotyledons are formed when the zygote undergoes mitotic divisions.");
			
				p.addAnswer(3, "fruit",
				false,
				"The ovary surrounding the ovules develops into the fruit.");
			
				p.addAnswer(4, "sporophyte",
				false,
				"The embryo develops into a mature sporophyte.");
			
				p.addAnswer(5, "seed coat",
				true,
				"The integuments of the ovule develop into a tough seed coat.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335797;


		
		

		
			
			p.question = "A carpel is composed of _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?30&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Angiosperm Life Cycle</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "ovary, ovule, and anther",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(2, "ovule, megasporocyte, and anther",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(3, "zygote, anther, and endosperm",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(4, "stigma, style, and ovary",
				true,
				"These are the components of a carpel.");
			
				p.addAnswer(5, "petal, sepal, and stamen",
				false,
				"No, that is incorrect.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335798;


		
		

		
			
			p.question = "In flowering plants one megaspore gives rise to _____ nuclei. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?30&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Angiosperm Life Cycle</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "four diploid",
				false,
				"Megaspores are haploid.");
			
				p.addAnswer(2, "four haploid",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(3, "eight haploid",
				true,
				"The haploid megaspore undergoes three mitotic divisions.");
			
				p.addAnswer(4, "eight diploid",
				false,
				"Megaspores are haploid.");
			
				p.addAnswer(5, "microsporangia",
				false,
				"No, that is incorrect.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335799;


		
		

		
			
			p.question = "A stamen consists of _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?30&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Angiosperm Life Cycle</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "anther and filament",
				true,
				"These are the components of a stamen.");
			
				p.addAnswer(2, "stigma and style",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(3, "stigma and anther",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(4, "stigma and filament",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(5, "ovary and sepal",
				false,
				"No, that is incorrect.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335800;


		
		

		
			
			p.question = "In angiosperms, pollination is the transfer of pollen grain to the _____ of a flower on the same plant or another plant of the same species. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?30&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Angiosperm Life Cycle</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "style",
				false,
				"Close but not quite.");
			
				p.addAnswer(2, "anther",
				false,
				"Pollen grains develop within anthers.");
			
				p.addAnswer(3, "ovulate cone",
				false,
				"You are confusing the life cycle of a pine with that of a flowering plant.");
			
				p.addAnswer(4, "stigma",
				true,
				"Pollen sticks to the sticky stigma.");
			
				p.addAnswer(5, "ovary",
				false,
				"Sperm nuclei eventually get to the ovary via a pollen tube, however.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

