

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "1: Introduction: Themes in the Study of Life > Activities Quiz";
	ak.quiz_loc_with_commas = "1: Introduction: Themes in the Study of Life, Activities Quiz";
	ak.quiz_title = "Activities Quiz";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 16;
	ak.non_essay_total = 16;
	ak.scored_item_total = 16;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334004;


		
		

		
			
			p.question = "An organ, such as the liver, is composed of _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?1&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Levels of Life Card Game</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "organs",
				false,
				"The liver is an organ.");
			
				p.addAnswer(2, "populations",
				false,
				"Two or more populations make up a community.");
			
				p.addAnswer(3, "atoms",
				false,
				"Well, yes, but there is a better choice listed here.");
			
				p.addAnswer(4, "communities",
				false,
				"Communities are composed of two or more populations.");
			
				p.addAnswer(5, "tissues",
				true,
				"Organs are composed of two or more different types of tissues.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334005;


		
		

		
			
			p.question = "Which of these is an organ system? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?1&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Levels of Life Card Game</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "stomach",
				false,
				"The stomach is an organ.");
			
				p.addAnswer(2, "mucosa",
				false,
				"Muscosa is a tissue.");
			
				p.addAnswer(3, "dog",
				false,
				"A dog is an organism.");
			
				p.addAnswer(4, "digestive",
				true,
				"The digestive system is composed of structures such as the stomach and small intestine.");
			
				p.addAnswer(5, "gamete",
				false,
				"A gamete is a cell.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334006;


		
		

		
			
			p.question = "What are the two main types of cells? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?1&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Levels of Life Card Game</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "bacteria and archaea",
				false,
				"These are both examples of one of the two main types of cells.");
			
				p.addAnswer(2, "plant and animal",
				false,
				"These are both examples of one of the two main types of cells.");
			
				p.addAnswer(3, "bacteria and protists",
				false,
				"These are not examples of the two main types of cells.");
			
				p.addAnswer(4, "prokaryotes and eukaryotes",
				true,
				"Prokaryotic cells lack the nucleus and other organelles found in eukaryotic cells.");
			
				p.addAnswer(5, "bacteria and eukaryotes",
				false,
				"This answer is partially correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334007;


		
		

		
			
			p.question = "The cell in the figure is a(n) _____ cell. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?1&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Energy Flow and Chemical Cycling</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0104q.jpg\" ALT=\"Question #4\" BORDER=\"1\" >";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "prokaryotic",
				false,
				"Prokaryotic cells lack many of the internal structures seen in eukaryotic cells.");
			
				p.addAnswer(2, "fungal",
				false,
				"Fungal cells have a cell wall.");
			
				p.addAnswer(3, "animal",
				true,
				"The illustrated cell is an animal cell.");
			
				p.addAnswer(4, "bacterial",
				false,
				"The illustrated cell has many of the internal structures that are lacking in bacterial cells.");
			
				p.addAnswer(5, "plant",
				false,
				"Plant cells have a cell wall.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334008;


		
		

		
			
			p.question = "The cell in the figure is a(n) _____ cell. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?1&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Energy Flow and Chemical Cycling</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0105q.jpg\" ALT=\"Question #5\" BORDER=\"1\" >";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "prokaryotic",
				false,
				"Prokaryotic cells lack the internal structures seen in this cell.");
			
				p.addAnswer(2, "bacterial",
				false,
				"Bacteria are prokaryotes.");
			
				p.addAnswer(3, "animal",
				false,
				"Animal cells do not have a cell wall.");
			
				p.addAnswer(4, "archaeal",
				false,
				"Archaea are prokaryotes.");
			
				p.addAnswer(5, "plant",
				true,
				"The cell is surrounded by a cell wall and contains the internal structures characteristic of a plant cell.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334009;


		
		

		
			
			p.question = "DNA is composed of building blocks called _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?1&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Heritable Information: DNA</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "nucleic acids",
				false,
				"DNA is a type of nucleic acid.");
			
				p.addAnswer(2, "Gs",
				false,
				"In the structure of DNA, G represents a component of DNA known as guanine.");
			
				p.addAnswer(3, "nucleotides",
				true,
				"DNA is a composed of nucleotide units.");
			
				p.addAnswer(4, "adenines",
				false,
				"Adenine, a nitrogenous base, is a component of DNA.");
			
				p.addAnswer(5, "amino acids",
				false,
				"Proteins are composed of amino acids.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334010;


		
		

		
			
			p.question = "In eukaryotic cells DNA has the appearance of a _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?1&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Heritable Information: DNA</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "single strand",
				false,
				"Eukaryotic DNA molecules are not single-stranded.");
			
				p.addAnswer(2, "letter U",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(3, "double helix",
				true,
				"Eukaryotic DNA is organized as a double helix.");
			
				p.addAnswer(4, "triple helix",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(5, "circle",
				false,
				"Eukaryotic DNA molecules are not circular.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334011;


		
		

		
			
			p.question = "Which of the following is a correct match of cell type with structure? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?1&G','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Form Fits Function: Cells</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "nerve cell ... closely joined",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(2, "skin cell ... has a large volume",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(3, "intestinal cell ... closely joined",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(4, "muscle cell ... has proteins that slide back and forth",
				true,
				"These proteins help muscles to contract.");
			
				p.addAnswer(5, "skin cell ... has long extensions",
				false,
				"No, that is incorrect.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334012;


		
		

		
			
			p.question = "Which of these provides your body with energy? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?1&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Energy Flow and Chemical Cycling</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "minerals",
				false,
				"Inorganic substances, such as minerals, do not provide the body with energy.");
			
				p.addAnswer(2, "fats",
				true,
				"Organic molecules, such as fats, are a source of energy.");
			
				p.addAnswer(3, "oxygen",
				false,
				"Oxygen, while it helps with obtaining energy from food, is not a source of energy.");
			
				p.addAnswer(4, "vitamins",
				false,
				"For humans, vitamins are not a source of energy.");
			
				p.addAnswer(5, "light",
				false,
				"The human body cannot use light as a source of energy.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334013;


		
		

		
			
			p.question = "Plants use _____ as a source of energy. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?1&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Energy Flow and Chemical Cycling</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "minerals",
				false,
				"Inorganic substances, such as minerals, do not provide plants with energy.");
			
				p.addAnswer(2, "fats",
				false,
				"Fats are not a source of energy for plants");
			
				p.addAnswer(3, "oxygen",
				false,
				"Oxygen is not a source of energy.");
			
				p.addAnswer(4, "vitamins",
				false,
				"For plants, vitamins are not a source of energy.");
			
				p.addAnswer(5, "light",
				true,
				"Plants use light as a source of energy.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334014;


		
		

		
			
			p.question = "What element is found in all organic compounds? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?1&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Energy Flow and Chemical Cycling</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "carbon",
				true,
				"All organic compounds contain carbon.");
			
				p.addAnswer(2, "oxygen",
				false,
				"Oxygen is not the element that is diagnostic of organic compounds.");
			
				p.addAnswer(3, "helium",
				false,
				"Helium is not the element that is diagnostic of organic compounds.");
			
				p.addAnswer(4, "iron",
				false,
				"Iron is not the element that is diagnostic of organic compounds.");
			
				p.addAnswer(5, "nitrogen",
				false,
				"Nitrogen is not the element that is diagnostic of organic compounds.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334015;


		
		

		
			
			p.question = "Plants obtain carbon from _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?1&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Energy Flow and Chemical Cycling</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "water",
				false,
				"Water does not contain carbon.");
			
				p.addAnswer(2, "carbon dioxide",
				true,
				"Plants obtain carbon from carbon dioxide.");
			
				p.addAnswer(3, "sugar",
				false,
				"Plants use carbon to produce organic compounds such as sugars.");
			
				p.addAnswer(4, "oxygen",
				false,
				"Oxygen does not contain carbon.");
			
				p.addAnswer(5, "glucose",
				false,
				"Plants use carbon to produce organic compounds such as glucose.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334016;


		
		

		
			
			p.question = "What name is given to organisms that convert the carbon in organic compounds into carbon in carbon dioxide? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?1&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Energy Flow and Chemical Cycling</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "autotrophs",
				false,
				"Autotrophs manufacture organic compounds.");
			
				p.addAnswer(2, "heterotrophs",
				false,
				"There is a better choice than this.");
			
				p.addAnswer(3, "plants",
				false,
				"Plants incorporate the carbon from carbon dioxide into organic compounds.");
			
				p.addAnswer(4, "recyclers",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(5, "decomposers",
				true,
				"Decomposers are organisms that recycle organic molecules into inorganic molecules.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334017;


		
		

		
			
			p.question = "Prokaryotic cells are found in the domain(s) _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?1&F','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Classification Schemes</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Bacteria and Archaea",
				true,
				"Both of these domains are composed of prokaryotic cells.");
			
				p.addAnswer(2, "Bacteria and Eukarya",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(3, "Bacteria and Protista",
				false,
				"Protists are in the domain Eukarya.");
			
				p.addAnswer(4, "Bacteria",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(5, "Protista and Archaea",
				false,
				"Protists are in the domain Eukarya.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334018;


		
		

		
			
			p.question = "In the five-kingdom system, prokaryotes are placed in the kingdom _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?1&F','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Classification Schemes</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Protista",
				false,
				"Protists are eukaryotes.");
			
				p.addAnswer(2, "Animalia",
				false,
				"Animals are composed of eukaryotic cells.");
			
				p.addAnswer(3, "Fungi",
				false,
				"Fungi are composed of eukaryotic cells.");
			
				p.addAnswer(4, "Plantae",
				false,
				"Plants are composed of eukaryotic cells.");
			
				p.addAnswer(5, "Monera",
				true,
				"All monerans are prokaryotes.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334019;


		
		

		
			
			p.question = "Which one of the following statements is true? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?1&H','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Science, Technology, and Society: DDT</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "DDT does not help prevent disease from passing from agricultural animals to humans.",
				false,
				"DDT does indeed help prevent such transmission by killing insects that spread disease.");
			
				p.addAnswer(2, "Cost was a major factor in the United States government\'s decision to ban DDT.",
				false,
				"The ban was not based on cost considerations. DDT is a relatively inexpensive insecticide.");
			
				p.addAnswer(3, "Many African governments concluded that the potential long-term health effects of DDT were not as serious as the immediate problem of insect control.",
				true,
				"They concluded that the immediate benefits of DDT outweighed the possible long-term harmful effects.");
			
				p.addAnswer(4, "DDT cannot accumulate in the fat of animals.",
				false,
				"DDT does indeed accumulate in animal fat.");
			
				p.addAnswer(5, "The DDT ban in the United States has made it very difficult to control agricultural insect pests.",
				false,
				"Insects can still be controlled without DDT, but at a higher cost to farmers and consumers.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

