

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "40: Basic Principles of Animal Form and Function > Practice Test";
	ak.quiz_loc_with_commas = "40: Basic Principles of Animal Form and Function, Practice Test";
	ak.quiz_title = "Practice Test";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 47;
	ak.non_essay_total = 47;
	ak.scored_item_total = 47;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336307;


		
		

		
			
			p.question = "Which one of the following is a question about physiology? (<script type=\"text/javascript\">ebook(\'40OV\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "How is blood pressure affected by physical activity?",
				true,
				"Correct. This question asks about the functional properties of the circulatory system.");
			
				p.addAnswer(2, "Do salamanders and frogs have the same number of toes on their front feet?",
				false,
				"No. This is a question about biological form.");
			
				p.addAnswer(3, "Is it true that apes do not have fleshy tails like monkeys?",
				false,
				"No. This is a question about biological form.");
			
				p.addAnswer(4, "Are there any living birds with claws on the ends of their wings?",
				false,
				"No. This is a question about biological form.");
			
				p.addAnswer(5, "Do baleen whales have teeth?",
				false,
				"No. This is a question about biological form.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336308;


		
		

		
			
			p.question = "Most cells are microscopic because at this small size _____. (<script type=\"text/javascript\">ebook(\'4001\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "free-living unicellular organisms are difficult for predatory organisms to detect and capture",
				false,
				"No. But it may be true that smaller organisms are more likely to be undetected by predators.");
			
				p.addAnswer(2, "many more cells can be packed into an organ while maintaining its compact size",
				false,
				"No. It would be more efficient to produce an organ from a smaller number of large cells than from many small cells.");
			
				p.addAnswer(3, "the ratio of surface area to cell volume is maximized",
				true,
				"Correct. Cells obtain all of their nutrients and gases across their plasma membranes. Because volume increases at a faster rate than surface area, larger cells are limited by the area available for diffusion.");
			
				p.addAnswer(4, "cells require fewer nutrients and increase the probability of survival",
				false,
				"No. Although this may be true, it is not the fundamental reason why cells are small.");
			
				p.addAnswer(5, "the amount of vulnerable plasma membrane is minimized relative to that of a larger, more stable cytoplasm",
				false,
				"No. Just the opposite is true. Volume increases at a faster rate than surface area.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336309;


		
		

		
			
			p.question = "Which of the following is a benefit of multicellularity compared to organisms consisting of just one cell? (<script type=\"text/javascript\">ebook(\'4001\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "All cells in a multicellular organism can perform all metabolic functions.",
				false,
				"No. Whereas a unicellular organism must perform all metabolic functions within its single cell, multicellularity allows for cell specialization, which can lead to tissue, organ, and organ system formation.");
			
				p.addAnswer(2, "Single-celled organisms can grow to larger sizes than multicellular organisms.",
				false,
				"No. This is a benefit of multicellularity.");
			
				p.addAnswer(3, "Cells can specialize.",
				true,
				"Correct. This is a benefit of multicellularity.");
			
				p.addAnswer(4, "Single-celled organisms can form tissues.",
				false,
				"No. This is a benefit of multicellularity.");
			
				p.addAnswer(5, "Single-celled organisms can form organs and organ systems.",
				false,
				"No. This is a benefit of multicellularity.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336310;


		
		

		
			
			p.question = "Which of these is most likely a characteristic of a large but not small aquatic animal? (<script type=\"text/javascript\">ebook(\'4001\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "extensive branching of internal respiratory surfaces",
				true,
				"Correct. Small animals bathed in fluid would not need to have their respiratory surfaces located internally, nor would they need branching to increase surface area.");
			
				p.addAnswer(2, "adequate exposed plasma membrane for exchange with the environment",
				false,
				"No. Small animals have most cells exposed to the fluid environment; therefore, they do have adequate exchange surface.");
			
				p.addAnswer(3, "two-layered or thin body",
				false,
				"No. Many small aquatic animals such as hydra have a two-layered body but few large animals have this body plan.");
			
				p.addAnswer(4, "most cells exposed to a fluid medium",
				false,
				"No. If the animal is small and aquatic, most of the cells are exposed to the water in which it lives.");
			
				p.addAnswer(5, "intracellular food digestion",
				false,
				"No. Many single-celled and small multicellular animals have no internal organs for digesting food because most digestion is intracellular.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336311;


		
		

		
			
			p.question = "An epithelial cell with a relatively large amount of cytoplasm probably has what function? (<script type=\"text/javascript\">ebook(\'4001\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "abrasion resistance",
				false,
				"No. The small, flattened, stratified squamous epithelium has this function.");
			
				p.addAnswer(2, "absorption and secretion",
				true,
				"Correct. This provides for the production of secretory products such as mucus, digestive juices, sweat, and oils as well as absorption of nutrients.");
			
				p.addAnswer(3, "regeneration and rapid tissue replacement",
				false,
				"No. This function is handled by the small, flattened, stratified squamous epithelial cells.");
			
				p.addAnswer(4, "anchorage for the basement membrane",
				false,
				"No. A large amount of cytoplasm is not a prerequisite for connection to the basement membrane.");
			
				p.addAnswer(5, "debris collection",
				false,
				"No. Not every epithelial cell with a large amount of cytoplasm will have this function. Many will simply be secretory and absorptive cells, such as those in the stomach and intestine.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336312;


		
		

		
			
			p.question = "Which of the following are types of cells found in epithelial tissues? (<script type=\"text/javascript\">ebook(\'4001\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "squamous, cuboidal, and columnar cells",
				true,
				"Correct. Epithelial cells are distinguished on the basis of shape: squamous, cuboidal, and columnar.");
			
				p.addAnswer(2, "chondrocytes and osteocytes",
				false,
				"No. These are connective tissue cells.");
			
				p.addAnswer(3, "neurons",
				false,
				"No. Neurons are nervous system cells.");
			
				p.addAnswer(4, "erythrocytes and platelets",
				false,
				"No. These are connective tissue cells.");
			
				p.addAnswer(5, "fibroblasts and osteoblasts",
				false,
				"No. These are connective tissue cells.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336313;


		
		

		
			
			p.question = "Which one of the following tissues bind and support other tissues in the body? (<script type=\"text/javascript\">ebook(\'4001\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "nervous tissue",
				false,
				"No. Nervous tissue senses stimuli and transmits signals.");
			
				p.addAnswer(2, "epithelial tissue",
				false,
				"No. Occurring in sheets of tightly packed cells, epithelial tissue covers the outside of the body and lines organs and cavities within the body.");
			
				p.addAnswer(3, "muscle tissue",
				false,
				"No. Muscle tissue actively contracts and causes body movements.");
			
				p.addAnswer(4, "connective tissues",
				true,
				"Correct. Connective tissues connect, bind, and support other tissues in the body.");
			
				p.addAnswer(5, "skin",
				false,
				"No. Skin is not a single tissue. Skin is composed of many tissues.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336314;


		
		

		
			
			p.question = "Microscopic analysis of an unknown tissue sample reveals the presence of chondrocytes, indicating that the sample probably includes _____. (<script type=\"text/javascript\">ebook(\'4001\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "bone",
				false,
				"No. The presence of osteocytes would indicate bone.");
			
				p.addAnswer(2, "loose connective tissue",
				false,
				"No. The presence of fibroblasts would indicate loose connective tissue.");
			
				p.addAnswer(3, "cartilage",
				true,
				"Correct. Chondrocytes secrete the matrix found in cartilage.");
			
				p.addAnswer(4, "stratified columnar epithelium",
				false,
				"No. Epithelial tissues are found with a free surface on one edge and a basement membrane on the other.");
			
				p.addAnswer(5, "adipose",
				false,
				"No. Adipose tissues store fat in adipose cells.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336315;


		
		

		
			
			p.question = "The matrix of blood tissue, where water, salts, and dissolved proteins are found, is _____. (<script type=\"text/javascript\">ebook(\'4001\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the outer covering of the blood vessels",
				false,
				"No. This is the epithelium.");
			
				p.addAnswer(2, "the red and white blood cells",
				false,
				"No. Red and white blood cells are the cellular portion of blood tissue; the matrix is extracellular.");
			
				p.addAnswer(3, "the blood plasma",
				true,
				"Correct. Blood plasma is the fluid matrix of blood tissue.");
			
				p.addAnswer(4, "made of cuboidal epithelium",
				false,
				"No. Cuboidal epithelium is epithelial tissue, not blood tissue.");
			
				p.addAnswer(5, "subject to abrasion",
				false,
				"No. Blood is fluid, although it carries cells and particles that subject the inner vessel surfaces to abrasion.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336316;


		
		

		
			
			p.question = "Which of the six major types of connective tissue has a rigid matrix which includes collagen and calcium salts? (<script type=\"text/javascript\">ebook(\'4001\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "fibrous connective",
				false,
				"No. This tissue has a matrix of dense parallel collagen fibers without calcium.");
			
				p.addAnswer(2, "cartilage",
				false,
				"No. This tissue has a dense matrix of collagen fibers embedded in a rubbery matrix.");
			
				p.addAnswer(3, "bone",
				true,
				"Correct. The matrix of bone is hard, but not brittle because of the collagen fibers included in the bone matrix.");
			
				p.addAnswer(4, "adipose",
				false,
				"No. Adipose tissue has relatively little matrix.");
			
				p.addAnswer(5, "loose connective",
				false,
				"No. This tissue\'s matrix is a loose weave of strong, ropelike collagen fibers.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336317;


		
		

		
			
			p.question = "Ligaments are what kind of connective tissue? (<script type=\"text/javascript\">ebook(\'4001\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "cartilage",
				false,
				"No. Cartilage surrounds the ends of bones and supports the nose and ears. Ligaments do not do this.");
			
				p.addAnswer(2, "adipose",
				false,
				"No. Adipose is a fatty tissue with little matrix. Ligaments have a dense matrix of collagen fibers.");
			
				p.addAnswer(3, "loose connective",
				false,
				"No. Ligaments are made of a dense pack of collagen fibers. Loose connective tissue is made of a loose weave of collagen fibers.");
			
				p.addAnswer(4, "fibrous connective",
				true,
				"Correct. Both ligaments and tendons are fibrous connective tissue made of densely packed, nonelastic, collagen fibers; they are strong and flexible.");
			
				p.addAnswer(5, "specialized for holding bone to muscle",
				false,
				"No. Ligaments hold bone to bone. Tendons hold bone to muscle. Moreover, the question asks about the composition of ligaments.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336318;


		
		

		
			
			p.question = "Cells that secrete cartilage are called _____. (<script type=\"text/javascript\">ebook(\'4001\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "fibroblasts",
				false,
				"No. These are cells scattered in connective tissue.");
			
				p.addAnswer(2, "osteons",
				false,
				"No. These are units found in bones.");
			
				p.addAnswer(3, "chondrocytes",
				true,
				"Correct. Chondroitin sulfate and collagen are secreted by chondrocytes, cells confined to scattered spaces in the matrix called lacunae.");
			
				p.addAnswer(4, "adipocytes",
				false,
				"No. These are fat cells.");
			
				p.addAnswer(5, "stem cells",
				false,
				"No. These are undifferentiated cells.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336319;


		
		

		
			
			p.question = "Ligaments connect _____ to _____. (<script type=\"text/javascript\">ebook(\'4001\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "muscle; tendon",
				false,
				"No. Tendons connect muscle to bone.");
			
				p.addAnswer(2, "tendon; tendon",
				false,
				"No. Tendons connect muscle to bone.");
			
				p.addAnswer(3, "tendon; bone",
				false,
				"No. Tendons connect muscle to bone.");
			
				p.addAnswer(4, "muscle; bone",
				false,
				"No. Tendons connect muscle to bone.");
			
				p.addAnswer(5, "bone; bone",
				true,
				"Correct. Fibrous connective tissue is found in tendons, which connect muscles to bones, and in ligaments, which connect bones at joints.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336320;


		
		

		
			
			p.question = "Which of the following are connective tissues? (<script type=\"text/javascript\">ebook(\'4001\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "adipose tissue, cartilage, bone, and blood",
				true,
				"Correct. Connective tissues include loose and dense connective tissue, elastic connective tissue, reticular connective tissue, adipose tissue, cartilage, bone, blood, lymph, and blood-producing cells.");
			
				p.addAnswer(2, "bone, blood, and skin",
				false,
				"No. Skin is composed of several types of tissue.");
			
				p.addAnswer(3, "red blood cells and neurons",
				false,
				"No. Neurons are cells of the nervous system.");
			
				p.addAnswer(4, "cartilage, bone, and epithelium",
				false,
				"No. Epithelium is not a connective tissue.");
			
				p.addAnswer(5, "adipose tissue, dense and loose connective tissues, and neurons",
				false,
				"No. Neurons are cells of the nervous system.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336321;


		
		

		
			
			p.question = "Bone cells are called _____. (<script type=\"text/javascript\">ebook(\'4001\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "osteocytes",
				true,
				"Correct. Osteocytes are bone cells.");
			
				p.addAnswer(2, "chondrocytes",
				false,
				"No. Chondrocytes are cells that secrete collagen and chondroitin sulfate, which make up cartilage.");
			
				p.addAnswer(3, "neurons",
				false,
				"No. Neurons are cells of the nervous system.");
			
				p.addAnswer(4, "osteoblasts",
				false,
				"No. Right prefix, but osteoblasts secrete the bone matrix.");
			
				p.addAnswer(5, "erythrocytes",
				false,
				"No. Erythrocytes are red blood cells.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336322;


		
		

		
			
			p.question = "\"Striated\" is a description that would apply to which kind of animal tissue? (<script type=\"text/javascript\">ebook(\'4001\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "stratified squamous epithelium",
				false,
				"No. This type of epithelium is made of flattened, densely packed cells.");
			
				p.addAnswer(2, "nerve",
				false,
				"No. Nerve cells are not striated.");
			
				p.addAnswer(3, "muscle",
				true,
				"Correct. Muscle cells are striated.");
			
				p.addAnswer(4, "skin",
				false,
				"No. Skin consists of many tissues.");
			
				p.addAnswer(5, "connective",
				false,
				"No. The term \"extracellular matrix\" applies to this type of tissue.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336323;


		
		

		
			
			p.question = "Myosin and actin are _____. (<script type=\"text/javascript\">ebook(\'4001\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "proteins that play a major role in muscle contraction",
				true,
				"Correct. Myosin and actin are two proteins that are the chief components of myofibrils. They play a key role in muscle contraction.");
			
				p.addAnswer(2, "part of a negative feedback loop",
				false,
				"No. The molecules work together.");
			
				p.addAnswer(3, "types of skeletal muscle",
				false,
				"No. Actin and myosin are proteins found in muscle tissue.");
			
				p.addAnswer(4, "found localized in intercalated disks",
				false,
				"No. Intercalated disks are found in cardiac muscle.");
			
				p.addAnswer(5, "unique to cardiac muscle",
				false,
				"No. They are more common than this.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336324;


		
		

		
			
			p.question = "A neuron consists of _____. (<script type=\"text/javascript\">ebook(\'4001\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "effectors, actin, and striated muscle fibers",
				false,
				"No. None of these are components of neurons. Neurons transmit impulses toward effectors.");
			
				p.addAnswer(2, "sarcomeres, axons, and dendrites",
				false,
				"No. Neurons contain axons and dendrites, but do not have sarcomeres, which are units of muscle tissue.");
			
				p.addAnswer(3, "a cell body, matrix, and myosin",
				false,
				"No. Neurons do have a cell body, but they do not have a matrix or myosin.");
			
				p.addAnswer(4, "a cell body, dendrites, and axons",
				true,
				"Correct. These are the three basic parts of a neuron.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336325;


		
		

		
			
			p.question = "Food processing, absorption, and distribution in your body are mainly accomplished by the _____ systems. (<script type=\"text/javascript\">ebook(\'4001\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "integumentary and excretory",
				false,
				"No. The integumentary system includes the skin, and the excretory system includes the kidneys and bladder.");
			
				p.addAnswer(2, "immune and lymphatic",
				false,
				"No. These systems are largely involved in the body\'s defense against disease and infectious agents.");
			
				p.addAnswer(3, "digestive and circulatory",
				true,
				"Correct. The digestive system breaks down and selectively absorbs nutrients, which are then distributed by the circulatory system.");
			
				p.addAnswer(4, "endocrine and integumentary",
				false,
				"No. The endocrine system coordinates the body\'s activities. The integumentary system consists of the skin, protecting against infection and injury and performing many other functions.");
			
				p.addAnswer(5, "respiratory and circulatory",
				false,
				"No. Partially correct. The respiratory system helps to move gases in and out of the body and is not involved with food. However, the circulatory system does help to distribute gases and nutrients throughout the body.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336326;


		
		

		
			
			p.question = "Which one of the following systems is correctly paired with one of its parts? (<script type=\"text/javascript\">ebook(\'4001\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "circulatory system; lung",
				false,
				"No. The lung is part of the respiratory system.");
			
				p.addAnswer(2, "respiratory system; heart",
				false,
				"No. The heart is part of the circulatory system.");
			
				p.addAnswer(3, "endocrine system; thyroid gland",
				true,
				"Correct. The thyroid gland is part of the endocrine system.");
			
				p.addAnswer(4, "integumentary system; kidneys",
				false,
				"No. The integumentary system includes the skin and its derivatives. The excretory system includes the kidneys and bladder.");
			
				p.addAnswer(5, "excretory system; intestine",
				false,
				"No. The excretory system includes the kidneys and bladder. The intestine is a component of the digestive system.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336327;


		
		

		
			
			p.question = "An organ such as the heart or liver consists of _____. (<script type=\"text/javascript\">ebook(\'4001\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "muscle tissue",
				false,
				"No. It is true that heart contraction requires muscle, but is that the only tissue found in these organs?");
			
				p.addAnswer(2, "nervous tissue",
				false,
				"No. It is true that nerves provide the rhythm and stimulus for the heart to beat, but is that the only tissue found in these organs?");
			
				p.addAnswer(3, "connective tissue",
				false,
				"No. Connective tissue fibers strengthen the wall of the heart, but is that the only tissue found in these organs?");
			
				p.addAnswer(4, "epithelial tissue",
				false,
				"No. The inner lining of the chambers and the surface of the heart are epithelium, but is that the only tissue found in these organs?");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct. Most organs consist of all four types of tissue.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336328;


		
		

		
			
			p.question = "An organism is to an albatross as a(n) _____ is to an intestine. (<script type=\"text/javascript\">ebook(\'4001\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "cell",
				false,
				"No. The intestine is made of many kinds of cells: muscle, secretory, epithelial, and so on.");
			
				p.addAnswer(2, "tissue",
				false,
				"No. The intestine contains several kinds of tissues: muscle, connective, and so on.");
			
				p.addAnswer(3, "organ",
				true,
				"Correct. The intestine is an organ on the same hierarchical level as the heart, lung, blood vessels, and so on. An intestine is a type of organ just as an albatross is a type of organism.");
			
				p.addAnswer(4, "organ system",
				false,
				"No. The intestine is one part of an organ system: the digestive system.");
			
				p.addAnswer(5, "organism",
				false,
				"No. The intestine is not a specific type of organism.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336329;


		
		

		
			
			p.question = "The _____ system and the _____ system work together to coordinate and control the bodies of most animals. (<script type=\"text/javascript\">ebook(\'4001\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "nervous; circulatory",
				false,
				"No, but half correct. The nervous system does help control the body, but another system works more closely with it.");
			
				p.addAnswer(2, "nervous; endocrine",
				true,
				"Correct. Together, these systems provide most of the control of the physiology of animals.");
			
				p.addAnswer(3, "endocrine; immune",
				false,
				"No, but half correct. The endocrine system does help control the body, but another system works more closely with it.");
			
				p.addAnswer(4, "circulatory; respiratory",
				false,
				"No. These systems work together to help move gases within the body.");
			
				p.addAnswer(5, "circulatory; digestive",
				false,
				"No. These systems work together to help move nutrients within the body.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336330;


		
		

		
			
			p.question = "Hormones are _____. (<script type=\"text/javascript\">ebook(\'4001\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "chemical signals broadcast throughout the body",
				false,
				"No. Although this is true, is this the only correct response?");
			
				p.addAnswer(2, "specific only for cells that have receptors for a specific hormone",
				false,
				"No. Although this is true, is this the only correct response?");
			
				p.addAnswer(3, "relatively slow acting",
				false,
				"No. Although this is true, is this the only correct response?");
			
				p.addAnswer(4, "distributed by the blood stream",
				false,
				"No. Although this is true, is this the only correct response?");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct. All of the statements are true.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336331;


		
		

		
			
			p.question = "Which one of the following is a characteristic of the nervous system but not the endocrine system? (<script type=\"text/javascript\">ebook(\'4001\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The signal is broadcast throughout the body.",
				false,
				"No. Signals of the nervous system typically target a specific cell or cells.");
			
				p.addAnswer(2, "Signaling usually involves more than one type of signal.",
				true,
				"Correct.");
			
				p.addAnswer(3, "Signals travel slowly, often taking many seconds to have an effect.",
				false,
				"No. This is true about the action of hormones.");
			
				p.addAnswer(4, "Signals are often long-lasting.",
				false,
				"No. This is true about the action of hormones.");
			
				p.addAnswer(5, "Signals generally coordinate gradual changes that affect the entire body.",
				false,
				"No. This is true about the action of hormones.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336332;


		
		

		
			
			p.question = "Interstitial fluid is _____. (<script type=\"text/javascript\">ebook(\'4001\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the blood",
				false,
				"No. Blood is restricted to the blood vessels.");
			
				p.addAnswer(2, "found only in the interior of compartments like the heart and stomach",
				false,
				"No. Interstitial fluids are found elsewhere.");
			
				p.addAnswer(3, "any place beneath the skin",
				false,
				"No. This answer is too general.");
			
				p.addAnswer(4, "any fluid inside the body",
				false,
				"No, but you are close. Some fluids within the body, such as saliva, are restricted to the glands that produce them.");
			
				p.addAnswer(5, "the fluid that fills the spaces between cells of vertebrates",
				true,
				"Correct. The interstitial spaces are those around individual cells. It is here that exchange of nutrients, gases, and wastes takes place.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336333;


		
		

		
			
			p.question = "Which of the following best illustrates homeostasis? (<script type=\"text/javascript\">ebook(\'4002\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "All the cells in the body have much the same chemical composition.",
				false,
				"No. The similarity of chemical composition results from the chemical requirements for life.");
			
				p.addAnswer(2, "DNA stores the genetic information in a cell.",
				false,
				"No. This is an example of a structural-functional relationship.");
			
				p.addAnswer(3, "When blood CO<sub>2</sub> increases, you breathe faster, ridding the body of excess CO<sub>2</sub>.",
				true,
				"Correct. Homeostasis maintains an internal consistency by negative feedback; in this example, an increase in CO<sub>2</sub> promotes its elimination.");
			
				p.addAnswer(4, "All organs are composed of the same four kinds of tissues.",
				false,
				"No. Although this is a true statement, homeostasis is a concept of physiology, not anatomy.");
			
				p.addAnswer(5, "The lung has a large surface for exchange of gases.",
				false,
				"No. This is an example of a structural-functional relationship.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336334;


		
		

		
			
			p.question = "Negative feedback is a method of homeostatic control that _____. (<script type=\"text/javascript\">ebook(\'4002\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "increases the speed and rapidity of negative responses",
				false,
				"No. Since the initial change is being enhanced, this is positive feedback. (\"I\'ve got some and I want more of the same!\")");
			
				p.addAnswer(2, "counteracts a change in a condition by causing the change to either moderate or stop",
				true,
				"Correct. Negative feedback reverses the response. (\"I\'ve got plenty, thank you.\")");
			
				p.addAnswer(3, "promotes decreases in metabolism rather than increases",
				false,
				"No. It can go either way. (\"I\'ve got plenty, please stop\" or \"I don\'t have enough, please give me more.\")");
			
				p.addAnswer(4, "produces a response by lowering some set point of an organism\'s metabolism",
				false,
				"No. Negative feedback is triggered by the set point of the control center.");
			
				p.addAnswer(5, "causes an effector to signal the control center of an organism, which creates the stimulus to make a response",
				false,
				"No. The sensor, or receptor, detects the stimulus and signals to the control center, causing the effector to produce the response.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336335;


		
		

		
			
			p.question = "If hormone A is part of a negative feedback loop with hormone B, then we can expect that _____. (<script type=\"text/javascript\">ebook(\'4002\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A and B will tend to have the same concentration",
				false,
				"No. This would not bring homeostasis.");
			
				p.addAnswer(2, "their concentrations will rise and fall at the same time, but in a regular cycle",
				false,
				"No. This would not hold in a negative-feedback situation.");
			
				p.addAnswer(3, "A will be highest when B is lowest, and vice versa",
				true,
				"Correct. In systems that involve negative feedback, the presence of the effector (one of the hormones) would turn off production of the other hormone.");
			
				p.addAnswer(4, "the concentrations of A and B will have no obvious relation to one another",
				false,
				"No. The question states that the hormones are in a negative feedback loop.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336336;


		
		

		
			
			p.question = "When we talk of feedback systems, the word \"stimulus\" means _____. (<script type=\"text/javascript\">ebook(\'4002\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a signal from the outside environment",
				false,
				"No. Stimuli can arise internally.");
			
				p.addAnswer(2, "a difference between the environment and the set point",
				true,
				"Correct. The receptor monitors the set point for a variable in the environment. If there is a discrepancy between the set point and the actual situation (a stimulus), the receptor signals the control center to produce an effector that will alter the environment and bring it to the set point.");
			
				p.addAnswer(3, "a signal that the effector gives to the sensor",
				false,
				"No. The effector does not directly signal the sensor.");
			
				p.addAnswer(4, "any signal passed between the sensor, integrator, and effector",
				false,
				"No. Feedback is a particular kind of signal.");
			
				p.addAnswer(5, "a signal from the internal environment",
				false,
				"No. Stimuli can arise externally.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336337;


		
		

		
			
			p.question = "The role of an effector in a feedback loop is to _____. (<script type=\"text/javascript\">ebook(\'4002\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "detect the stimulus",
				false,
				"No. Effectors are not sensory structures.");
			
				p.addAnswer(2, "influence the stimulus",
				true,
				"Correct. The receptor monitors the set point for a variable in the environment. If there is a discrepancy between the set point and the actual situation (a stimulus), the receptor signals the control center to produce an effector that will alter the environment and bring it to the set point.");
			
				p.addAnswer(3, "allow the integrator to keep working even though conditions have changed",
				false,
				"No. An effector brings about an action.");
			
				p.addAnswer(4, "act as a sensor",
				false,
				"No. Effectors are not sensory structures.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. Only one of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336338;


		
		

		
			
			p.question = "When a jogger starts to run, the rate at which his muscles produce CO<sub>2</sub> rises sharply. But the CO<sub>2</sub> in his blood rises only slightly before he starts to breathe faster and his heart starts beating stronger. Soon his increased rate of CO<sub>2</sub> production is balanced by an increased rate of CO<sub>2</sub> removal. This would be an example of _____ feedback because the jogger\'s circulatory and respiratory systems are _____. (<script type=\"text/javascript\">ebook(\'4002\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "positive; improving the operating conditions in the jogger\'s body",
				false,
				"No. The body is acting to decrease CO<sub>2</sub> levels.");
			
				p.addAnswer(2, "negative; acting to oppose the increase of CO<sub>2</sub> from the preferred concentration",
				true,
				"Correct. In negative feedback, a change in the variable being monitored triggers the control mechanism to counteract further change in the same direction.");
			
				p.addAnswer(3, "positive; decreasing the CO<sub>2</sub> concentration",
				false,
				"No. Positive feedback acts in the same direction as the initial change. Therefore, if this were positive feedback, the result would be a continued increase in the jogger\'s rate of CO<sub>2</sub> production.");
			
				p.addAnswer(4, "positive; restoring the CO<sub>2</sub> concentration to the set point",
				false,
				"No. The body is acting to decrease CO<sub>2</sub> levels; positive feedback would act to continue the increase in the jogger\'s rate of CO<sub>2</sub> production.");
			
				p.addAnswer(5, "negative; acting in opposition to one another",
				false,
				"No. The circulatory and respiratory systems are working together to decrease CO<sub>2</sub> levels.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336339;


		
		

		
			
			p.question = "_____ feedback most directly maintains homeostasis because it _____. (<script type=\"text/javascript\">ebook(\'4002\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Negative; tends to keep a system at a desirable \"set point\"",
				true,
				"Correct. In negative feedback, a change in the variable being monitored triggers the control mechanism to counteract further change in the same direction.");
			
				p.addAnswer(2, "Negative; accentuates fluctuations and keeps the system from reaching equilibrium",
				false,
				"No. Positive feedback acts to increase the intensity of the initial stimulus.");
			
				p.addAnswer(3, "Positive; keeps systems constant despite fluctuations in the external environment",
				false,
				"No. Positive feedback acts to increase the intensity of the initial stimulus.");
			
				p.addAnswer(4, "Positive; magnifies deviations from the \"set point\"",
				false,
				"No. This does not maintain homeostasis.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336340;


		
		

		
			
			p.question = "By definition, an ectotherm _____. (<script type=\"text/javascript\">ebook(\'4003\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "is cold-blooded",
				false,
				"No. The term \"ectotherm\" is used to describe the source of heat for an organism.");
			
				p.addAnswer(2, "is warm-blooded",
				false,
				"No. The term \"ectotherm\" is used to describe the source of heat for an organism.");
			
				p.addAnswer(3, "obtains most of its heat from its environment",
				true,
				"Correct. Many ectotherms regulate body heat through behavioral methods such as basking in the sun, seeking shade, or generating heat through movement.");
			
				p.addAnswer(4, "can generate enough metabolic heat to keep its body temperature above that of its surroundings",
				false,
				"No. This is the description of an endotherm.");
			
				p.addAnswer(5, "has a body temperature that varies considerably",
				false,
				"No. Although the body temperature of some ectotherms may vary with external temperatures, many ectotherms live in environments where the external temperature is remarkably constant. There is a better answer.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336341;


		
		

		
			
			p.question = "The term \"endotherm\" refers specifically to _____. (<script type=\"text/javascript\">ebook(\'4003\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a warm-blooded animal",
				false,
				"No. Temperature of the blood is not the crucial element.");
			
				p.addAnswer(2, "a cold-blooded animal",
				false,
				"No. Most endotherms have blood warmer than their environment, but temperature of the blood is not the crucial element.");
			
				p.addAnswer(3, "an animal that gets most of its body heat from its metabolism",
				true,
				"Correct. Endotherms have special adaptations for conserving metabolic heat.");
			
				p.addAnswer(4, "an animal that temporarily abandons warm-bloodedness",
				false,
				"No. This is an animal involved in some kind of torpor to conserve energy.");
			
				p.addAnswer(5, "an animal that regulates its body temperature by its behavior",
				false,
				"No. This is generally an ectotherm\'s method of heat regulation, although some endotherms do also exhibit behavioral practices that supplement endothermy.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336342;


		
		

		
			
			p.question = "Which statement is true regarding thermoregulation? (<script type=\"text/javascript\">ebook(\'4003\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "An ectotherm such as a lizard does not maintain a fairly constant body temperature.",
				false,
				"No. A lizard maintains a fairly constant body temperature by moving between warm and cool places as needed to regulate heat absorption and loss.");
			
				p.addAnswer(2, "Ectotherms generally do not conserve body heat as effectively as do polar bears.",
				true,
				"Correct. Ectotherms spend much less energy on adaptations that conserve heat than do polar bears.");
			
				p.addAnswer(3, "Endotherms must always maintain a fairly constant body temperature to survive.",
				false,
				"No. Many endotherms\' temperatures lower significantly for hibernation and in daily or nightly torpor.");
			
				p.addAnswer(4, "In furry animals, raised hairs keep the animal cooler than lowered hairs.",
				false,
				"No. The raised hairs trap more heat in the additional calm air space created.");
			
				p.addAnswer(5, "A dilated blood vessel conserves more heat than a constricted one.",
				false,
				"No. A dilated blood vessel radiates more heat than a constricted one.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336343;


		
		

		
			
			p.question = "The wolf, his coat glowing in the early spring sunshine, sat atop a cold boulder after unsuccessfully pursuing a plump jackrabbit. He continued to pant while _____. (<script type=\"text/javascript\">ebook(\'4003\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "his body heat evaporated into the rock",
				false,
				"No. Body heat would be conducted into the solid rock.");
			
				p.addAnswer(2, "heat escaped his gaping jaws by conduction",
				false,
				"No. He would lose heat through the evaporation of saliva from his gaping jaws.");
			
				p.addAnswer(3, "receiving heat by conduction from the sun",
				false,
				"No. He would receive heat by radiation from the sun.");
			
				p.addAnswer(4, "heat was conducted away by the gentle breeze",
				false,
				"No. Heat was carried away by convection on the breeze.");
			
				p.addAnswer(5, "heat radiated from his tired body",
				true,
				"Correct. Heat would radiate away from his body; heat would also radiate from the sun to him.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336344;


		
		

		
			
			p.question = "It is a cold day in the lecture hall. When you rest your arm on the cool laminated desktop at your seat, heat is transferred _____. (<script type=\"text/javascript\">ebook(\'4003\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "from your body to the desk by radiation",
				false,
				"No. Radiation does not involve a direct transfer of heat.");
			
				p.addAnswer(2, "from your body to the desk by conduction",
				true,
				"Correct. Conduction is the direct transfer of heat between molecules of the environment and those of the body surface. Heat is always conducted from a body of higher temperature to one of lower temperature.");
			
				p.addAnswer(3, "from the desk to your body by radiation",
				false,
				"No. Radiation does not involve a direct transfer of heat.");
			
				p.addAnswer(4, "from the desk to your body by conduction",
				false,
				"No. Your body is warmer than the desk.");
			
				p.addAnswer(5, "from the air to your body by convection",
				false,
				"No. Your body is warmer than the air.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336345;


		
		

		
			
			p.question = "When your body temperature is too _____, _____ helps to correct the situation because it _____. (<script type=\"text/javascript\">ebook(\'4003\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "high; peripheral vasodilation; redirects heat from the body core to the outside",
				true,
				"Correct. Increased blood flow usually results from vasodilation, which results in more heat being transferred to the environment, cooling the animal.");
			
				p.addAnswer(2, "high; sweating; lowers the metabolic rate by dumping toxic ions",
				false,
				"No. Sweating does lower the temperature, but it does not dump toxic ions.");
			
				p.addAnswer(3, "low; peripheral vasodilation; conserves heat in the body core",
				false,
				"No. Peripheral vasodilation causes heat loss.");
			
				p.addAnswer(4, "low; shivering; lowers the metabolic rate and conserves blood sugar",
				false,
				"No. Shivering raises the metabolic rate.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336346;


		
		

		
			
			p.question = "Humid weather makes you feel warmer because humid air, which is saturated with water molecules _____. (<script type=\"text/javascript\">ebook(\'4003\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "interferes with heat loss by conduction",
				false,
				"No. Conductive heat loss involves the direct transfer of heat energy from one object to another.");
			
				p.addAnswer(2, "holds warm water vapor",
				false,
				"No. However, because the solubility of water in air is sensitive to temperature, high humidity can often be associated with high temperatures.");
			
				p.addAnswer(3, "interferes with heat loss by evaporation",
				true,
				"Correct. For evaporative cooling to occur, water molecules must leave the skin and become water vapor. When the humidity of the air is high, the air is closer to its saturation value for water vapor.");
			
				p.addAnswer(4, "prevents countercurrent heat exchange from occurring",
				false,
				"No. Countercurrent heat exchange involves the arrangement of blood vessels and heat transfer by conduction.");
			
				p.addAnswer(5, "increases metabolic heat production",
				false,
				"No. The generation of heat as a metabolic by-product is related to the specific biochemical reactions involved, not the humidity of the air.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336347;


		
		

		
			
			p.question = "Sweating _____. (<script type=\"text/javascript\">ebook(\'4003\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "can be prevented by drinking adequate amounts of water",
				false,
				"No. Dehydration reduces sweating; thus, dehydration can cause the body to overheat dangerously. Drinking water makes sweating easier when it is necessary to cool the body.");
			
				p.addAnswer(2, "happens only on hot days",
				false,
				"No. It happens any time an individual is overheated. Sweating can also occur in the winter.");
			
				p.addAnswer(3, "is common in dogs",
				false,
				"No. Dogs pant for evaporative cooling.");
			
				p.addAnswer(4, "helps the body thermoregulate",
				true,
				"Correct. Sweating is a beneficial and effective method to regulate overheating.");
			
				p.addAnswer(5, "results in irreversible dehydration",
				false,
				"No. As long as water intake balances water loss, sweating can continue indefinitely without dehydration.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336348;


		
		

		
			
			p.question = "Which description is a behavior that helps warm the body? (<script type=\"text/javascript\">ebook(\'4003\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "An elephant rolls in the mud and sprays water over its back.",
				false,
				"No. This provides the animal with evaporative cooling as well as portable shade.");
			
				p.addAnswer(2, "A marine iguana dives into the surf after sunning on a rock.",
				false,
				"No. The iguana, having warmed itself enough to go foraging, will cool off in the sea.");
			
				p.addAnswer(3, "A woman puts on a wide-brimmed hat while laboring in the sunshine.",
				false,
				"No. The woman is providing herself with portable shade.");
			
				p.addAnswer(4, "A falcon migrates from San Francisco to Brazil for the winter.",
				true,
				"Correct. Brazil is on the equator, where winters are much warmer than in northern coastal California.");
			
				p.addAnswer(5, "Sweat oozes from the hide of a thirsty antelope in the drought-stricken Serengeti plains.",
				false,
				"No. This is neither behavioral nor warming. It is a physiological method of cooling. Drinking water would be a cooling behavior.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336349;


		
		

		
			
			p.question = "In the late fall, bats hibernate in clusters with many bats pressed together and holding on to one another. Which of the following advantages of huddling behavior is, in reality, not true? (<script type=\"text/javascript\">ebook(\'4003\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Less surface area is exposed to the environment.",
				false,
				"No. This advantage is true. Because much of the bat\'s surface is pressed against other bats, less surface area is exposed to the colder environmental temperature.");
			
				p.addAnswer(2, "In this configuration, less heat is needed for each bat and, therefore, each bat requires less food.",
				false,
				"No. This advantage is true. Any heat given off by any bat is shared with the rest. That coupled with the lowered body temperature of the bats means they need much less fuel.");
			
				p.addAnswer(3, "Huddling behavior helps bats stay warm while they feed.",
				true,
				"Correct. This cannot be an advantage, because huddling behavior is not possible while bats fly and catch food. This represents a compromise of feeding and thermoregulation.");
			
				p.addAnswer(4, "Any heat generated by any bat is shared by other bats.",
				false,
				"No. This is a major advantage of huddling.");
			
				p.addAnswer(5, "Huddling behavior decreases the amount of food needed for bats to stay warm.",
				false,
				"No. This advantage is true. The inactivity and lowered body temperature of hibernation allows these animals to survive on stored energy supplies and fewer calories.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336350;


		
		

		
			
			p.question = "On a cold day, blood vessels in the skin _____. (<script type=\"text/javascript\">ebook(\'4003\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "dilate, allowing blood to keep the skin warm",
				false,
				"No. Dilation causes the diameter of blood vessels to increase, in this case increasing blood flow to the skin and heat loss at the same time.");
			
				p.addAnswer(2, "constrict, forcing blood to flow through vessels in the skin",
				false,
				"No. Vasoconstriction reduces blood flow through a vessel.");
			
				p.addAnswer(3, "constrict, reducing heat loss from blood at the surface",
				true,
				"Correct. Since blood vessels lie close to the surface of the skin, they give off heat to the external environment easily. Constricting blood vessels in the skin reduces heat loss.");
			
				p.addAnswer(4, "dilate, causing blood to pass through the cold skin more quickly",
				false,
				"No. If the vessels were to dilate, blood flow would increase to the skin, giving off heat.");
			
				p.addAnswer(5, "dilate, preventing blood flow to the surface",
				false,
				"No. Vasodilation increases blood flow, which would increase heat loss.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336351;


		
		

		
			
			p.question = "During a fever, the _____ readjusts the set point of the body to a _____ temperature. (<script type=\"text/javascript\">ebook(\'4003\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "thyroid; lower",
				false,
				"No. The thyroid gland releases hormones that can influence body temperature. However, the thyroid gland is not the main thermostat in the body. Further, a fever is associated with a higher temperature set point.");
			
				p.addAnswer(2, "hypothalamus; higher",
				true,
				"Correct. The hypothalamus is the main thermostat in the body.");
			
				p.addAnswer(3, "hypothalamus; lower",
				false,
				"No. Partially correct. The hypothalamus is the main thermostat in the body. However, fever is associated with a higher temperature set point, not a lower set point.");
			
				p.addAnswer(4, "pineal gland; higher",
				false,
				"No. The pineal gland helps to regular sleep cycles and seasonal changes. It is not the main thermostat of the body.");
			
				p.addAnswer(5, "adrenal glands; lower",
				false,
				"No. The adrenal glands release hormones involved in responses of the autonomic nervous system. Adrenal glands are not the main thermostat of the body. Further, a fever is associated with a higher temperature set point.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336352;


		
		

		
			
			p.question = "Which one of the following animals would you expect to consume food at the highest rate (kilograms of food per kilogram of body weight per day)? (<script type=\"text/javascript\">ebook(\'4004\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "dog",
				false,
				"No. Of the organisms listed here, dogs are not the smallest endotherms.<b> </b>In general, larger endotherms require fewer calories per kilogram of body weight than smaller endotherms.");
			
				p.addAnswer(2, "sparrow",
				true,
				"Correct. Metabolic rates are highest for small organisms and during intense physical activity, such as flying.");
			
				p.addAnswer(3, "human",
				false,
				"No. Humans are large endotherms. In general, larger endotherms require fewer calories per kilogram of body weight than smaller endotherms.");
			
				p.addAnswer(4, "alligators",
				false,
				"No. Alligators are ectotherms and generally require fewer calories per kilogram of body weight than endotherms.");
			
				p.addAnswer(5, "bullfrog",
				false,
				"No. Bullfrogs are ectotherms and generally require fewer calories per kilogram of body weight than endotherms.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336353;


		
		

		
			
			p.question = "In most animals, food is digested by _____, _____ are absorbed by body cells, and most energy-containing molecules are used to generate _____. (<script type=\"text/javascript\">ebook(\'4004\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "enzymatic hydrolysis; DNA and RNA; more cells",
				false,
				"No. Although it is true that food is digested by enzymatic hydrolysis, what is absorbed and what is generated is not correct.");
			
				p.addAnswer(2, "enzymatic hydrolysis; nutrients; ATP",
				true,
				"Correct.");
			
				p.addAnswer(3, "blood cells; nutrients; DNA",
				false,
				"No. Although it is true that nutrients are absorbed, how food is digested and what is generated is not correct.");
			
				p.addAnswer(4, "mitochondria; carbon dioxide; DNA",
				false,
				"No. None of these responses are correct.");
			
				p.addAnswer(5, "acids; nutrients; ATP",
				false,
				"No. Although it is true that nutrients are absorbed and ATP is generated, acids are not the way that food is digested.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

