

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "38: Angiosperm Reproduction and Biotechnology > Activities Quiz";
	ak.quiz_loc_with_commas = "38: Angiosperm Reproduction and Biotechnology, Activities Quiz";
	ak.quiz_title = "Activities Quiz";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 11;
	ak.non_essay_total = 11;
	ak.scored_item_total = 11;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336194;


		
		

		
			
			p.question = "Ovules are found within structure _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?30&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Angiosperm Life Cycle</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/3801q.jpg\" ALT=\"Question #1\" BORDER=\"1\" >";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A",
				false,
				"This is a sepal.");
			
				p.addAnswer(2, "B",
				true,
				"Ovules are housed within ovaries.");
			
				p.addAnswer(3, "C",
				false,
				"This is a petal.");
			
				p.addAnswer(4, "D",
				false,
				"This is an anther.");
			
				p.addAnswer(5, "E",
				false,
				"This is a filament.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336195;


		
		

		
			
			p.question = "Which of these is unique to flowering plants? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?30&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Angiosperm Life Cycle</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a dominant sporophyte generation",
				false,
				"The sporophyte generation is dominant in seedless vascular plants and gymnosperms, as well as angiosperms.");
			
				p.addAnswer(2, "an embryo surrounded by nutritive tissue",
				false,
				"You might want to review the Chapter 30 activity on the pine life cycle.");
			
				p.addAnswer(3, "haploid gametophytes",
				false,
				"All gametophytes are haploid.");
			
				p.addAnswer(4, "double fertilization",
				true,
				"In flowering plants one sperm nucleus fertilizes the egg and the other sperm nucleus fuses with two nuclei found within the ovule, thus forming triploid endosperm.");
			
				p.addAnswer(5, "pollen production",
				false,
				"You might want to review the Chapter 30 activity on the pine life cycle.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336196;


		
		

		
			
			p.question = "The male gametophytes of flowering plants are also referred to as _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?30&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Angiosperm Life Cycle</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "endosperm",
				false,
				"Endosperm is a triploid tissue that serves as a food reserve.");
			
				p.addAnswer(2, "male sporophytes",
				false,
				"Gametophytes are haploid; sporophytes are diploid.");
			
				p.addAnswer(3, "megaspores",
				false,
				"Megaspores are female structures.");
			
				p.addAnswer(4, "pollen grains",
				true,
				"Pollen grains are male gametophytes.");
			
				p.addAnswer(5, "embryo sacs",
				false,
				"Embryo sacs are produced within ovules.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336197;


		
		

		
			
			p.question = "In flowering plants the integuments of the ovule develop into a(n) _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?30&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Angiosperm Life Cycle</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "endosperm",
				false,
				"Endosperm is formed when one of the sperm nuclei fuses with two of the nuclei found within the ovule.");
			
				p.addAnswer(2, "cotyledon",
				false,
				"Cotyledons are formed when the zygote undergoes mitotic divisions.");
			
				p.addAnswer(3, "fruit",
				false,
				"The ovary surrounding the ovules develops into the fruit.");
			
				p.addAnswer(4, "sporophyte",
				false,
				"The embryo develops into a mature sporophyte.");
			
				p.addAnswer(5, "seed coat",
				true,
				"The integuments of the ovule develop into a tough seed coat.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336198;


		
		

		
			
			p.question = "A carpel is composed of _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?30&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Angiosperm Life Cycle</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "ovary, ovule, and anther",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(2, "ovule, megasporocyte, and anther",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(3, "zygote, anther, and endosperm",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(4, "stigma, style, and ovary",
				true,
				"These are the components of a carpel.");
			
				p.addAnswer(5, "petal, sepal, and stamen",
				false,
				"No, that is incorrect.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336199;


		
		

		
			
			p.question = "In flowering plants one megaspore gives rise to _____ nuclei. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?30&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Angiosperm Life Cycle</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "four diploid",
				false,
				"Megaspores are haploid.");
			
				p.addAnswer(2, "four haploid",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(3, "eight haploid",
				true,
				"The haploid megaspore undergoes three mitotic divisions.");
			
				p.addAnswer(4, "eight diploid",
				false,
				"Megaspores are haploid.");
			
				p.addAnswer(5, "microsporangia",
				false,
				"No, that is incorrect.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336200;


		
		

		
			
			p.question = "A stamen consists of _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?30&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Angiosperm Life Cycle</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "anther and filament",
				true,
				"These are the components of a stamen.");
			
				p.addAnswer(2, "stigma and style",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(3, "stigma and anther",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(4, "stigma and filament",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(5, "ovary and sepal",
				false,
				"No, that is incorrect.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336201;


		
		

		
			
			p.question = "In angiosperms, pollination is the transfer of pollen grain to the _____ of a flower on the same plant or another plant of the same species. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?30&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Angiosperm Life Cycle</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "style",
				false,
				"Close but not quite.");
			
				p.addAnswer(2, "anther",
				false,
				"Pollen grains develop within anthers.");
			
				p.addAnswer(3, "ovulate cones",
				false,
				"You are confusing the pine life cycle with that of a flowering plant.");
			
				p.addAnswer(4, "stigma",
				true,
				"Pollen adheres to the sticky stigma.");
			
				p.addAnswer(5, "ovary",
				false,
				"Sperm nuclei eventually get to the ovary via a pollen tube, however.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336202;


		
		

		
			
			p.question = "What is endosperm? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?38&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Seed and Fruit Development</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the male portion of a flowering plant",
				false,
				"The stamen is the male portion of a flowering plant.");
			
				p.addAnswer(2, "via cotyledons, a source of food for the embryo",
				true,
				"The triploid endosperm is a source of nourishment for the embryo.");
			
				p.addAnswer(3, "the leaves that are a part of the embryo",
				false,
				"An embryo\'s leaves are referred to as cotyledons.");
			
				p.addAnswer(4, "the female portion of a flowering plant",
				false,
				"The carpel is the female portion of a flowering plant.");
			
				p.addAnswer(5, "tissue that develops into a protective seed coat surrounding the embryo",
				false,
				"The embryo and endosperm are enclosed in a protective seed coat that develops from the integuments.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336203;


		
		

		
			
			p.question = "The pointer is indicating a diploid cell that develops into the _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?38&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Seed and Fruit Development</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/3810q.jpg\" ALT=\"Question #10\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "endosperm",
				false,
				"Endosperm is a nutritive triploid tissue.");
			
				p.addAnswer(2, "ovule",
				false,
				"The pointer is indicating a cell within the ovule.");
			
				p.addAnswer(3, "seed coat",
				false,
				"The seed coat develops from the integuments that surround the ovule.");
			
				p.addAnswer(4, "carpel",
				false,
				"The pointer is indicating a cell within the ovule of an ovary, which is a part of a carpel.");
			
				p.addAnswer(5, "embryo",
				true,
				"This region of an ovule develops into an embryo.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336204;


		
		

		
			
			p.question = "Fruits evolved primarily as structures specialized to _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?38&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Seed and Fruit Development</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "protect seeds",
				false,
				"While fruits may have some protective value, this is not their primary function.");
			
				p.addAnswer(2, "disperse seeds",
				true,
				"Fruits evolved as seed-dispersing structures.");
			
				p.addAnswer(3, "protect pollen",
				false,
				"Pollen is involved in setting off a chain of events that lead to fruit formation. However, fruit itself does not protect pollen.");
			
				p.addAnswer(4, "provide food for humans",
				false,
				"Humans have exploited the nutritive value of certain fruits. Or, perhaps, certain plants have used their fruits to exploit humans: Humans promote the survival, growth, and reproduction of certain fruit-bearing plants. However, fruit did not evolve to be a source of food for humans.");
			
				p.addAnswer(5, "provide a source of food to the plant\'s embryo",
				false,
				"Endosperm is an embryo\'s primary source of food. Often, the fruit is gone by the time the seed germinates. Fruit did not evolve to provide food to the embryo.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

