

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "56: Conservation Biology and Restoration Ecology > Practice Test";
	ak.quiz_loc_with_commas = "56: Conservation Biology and Restoration Ecology, Practice Test";
	ak.quiz_title = "Practice Test";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 30;
	ak.non_essay_total = 30;
	ak.scored_item_total = 30;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337170;


		
		

		
			
			p.question = "The integration of several sciences such as ecology and genetics to sustain biological diversity at all levels is known as _____. (<script type=\"text/javascript\">ebook(\'56OV\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "conservation biology",
				true,
				"Correct. Conservation biology is the study and protection of biological diversity.");
			
				p.addAnswer(2, "restoration ecology",
				false,
				"No. Whereas conservation biologists work to sustain existing ecosystems, restoration ecologists attempt to fix areas that have been damaged.");
			
				p.addAnswer(3, "ecology",
				false,
				"No. Ecology is the study of how organisms interact with their environment; however, the answer to this question must consider ecological questions.");
			
				p.addAnswer(4, "bioremediation",
				false,
				"No. This is the use of living organisms to detoxify polluted ecosystems.");
			
				p.addAnswer(5, "biological augmentation",
				false,
				"No. Biological augmentation uses organisms to add essential materials to a degraded ecosystem.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337171;


		
		

		
			
			p.question = "Extinction is a naturally occurring phenomenon that has occurred on Earth since life began. Why are scientists so concerned about extinction now? (<script type=\"text/javascript\">ebook(\'5601\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "One of the greatest periods of mass extinction is occurring now.",
				false,
				"No. This is true, but there is a better response.");
			
				p.addAnswer(2, "Human activities are directly responsible for today\'s mass extinctions.",
				false,
				"No. This is true, but there is a better response.");
			
				p.addAnswer(3, "Extinction is occurring faster than ever before and faster than rates at which new species form.",
				false,
				"No. This is true, but there is a better response.");
			
				p.addAnswer(4, "Large numbers of plant species, which form the base of terrestrial food webs, are becoming extinct.",
				false,
				"No. This is true, but there is a better response.");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct. All of the above are explanations of scientists\' concerns about modern extinctions.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337172;


		
		

		
			
			p.question = "What are the three levels of biodiversity? (<script type=\"text/javascript\">ebook(\'5601\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "genetic, species, biome",
				false,
				"No. You have two out of three correct. After species, the next level of biodiversity is ecosystem.");
			
				p.addAnswer(2, "molecular, species, biome",
				false,
				"No. The three main components, or levels, of biodiversity are genetic, species, and ecosystem.");
			
				p.addAnswer(3, "genetic, population, ecosystem",
				false,
				"No. The three main components, or levels, of biodiversity are genetic, species, and ecosystem.");
			
				p.addAnswer(4, "genetic, species, ecosystem",
				true,
				"Correct. All three levels are being decreased by human activity.");
			
				p.addAnswer(5, "molecular, species, ecosystem",
				false,
				"No. The three main components, or levels, of biodiversity are genetic, species, and ecosystem.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337173;


		
		

		
			
			p.question = "Crop pollination, water purification, and moderation of weather extremes are just a few examples of _____. (<script type=\"text/javascript\">ebook(\'5601\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "ecosystem diversity",
				false,
				"No. Ecosystem diversity is one of the components of biodiversity.");
			
				p.addAnswer(2, "biological augmentation",
				false,
				"No. This refers to using plants or other organisms to add certain materials to an ecosystem.");
			
				p.addAnswer(3, "disruption of interaction networks",
				false,
				"No. This domino effect occurs when an ecosystem loses a keystone species.");
			
				p.addAnswer(4, "ecosystem services",
				true,
				"Correct. Ecosystem services encompass all the processes through which natural ecosystems and the species they contain help sustain human life on Earth.");
			
				p.addAnswer(5, "the extinction vortex",
				false,
				"No. A small population is prone to positive feedback loops of inbreeding and genetic drift that draw the population down an extinction vortex toward smaller and smaller population size until no individuals exist.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337174;


		
		

		
			
			p.question = "The major cause of extinction of species today is _____. (<script type=\"text/javascript\">ebook(\'5601\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "habitat destruction",
				true,
				"Correct. Habitat destruction is the most significant cause of species extinction today.");
			
				p.addAnswer(2, "global warming",
				false,
				"No. Although global warming affects biodiversity, it is not the major cause of extinction.");
			
				p.addAnswer(3, "predation",
				false,
				"No. Predation is not the major cause of extinction.");
			
				p.addAnswer(4, "the greenhouse effect",
				false,
				"No. The greenhouse effect is a natural phenomenon that keeps Earth at a moderate temperature sustainable for life. Alone, it does not cause extinctions.");
			
				p.addAnswer(5, "thinning of the ozone layer",
				false,
				"No. Although thinning of the ozone layer affects life, it is not the major cause of extinction.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337175;


		
		

		
			
			p.question = "Which of the following threaten biodiversity? (<script type=\"text/javascript\">ebook(\'5601\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "habitat destruction",
				false,
				"No. Although this is a threat to biodiversity, it is not the best choice.");
			
				p.addAnswer(2, "overexploitation",
				false,
				"No. Although this is a threat to biodiversity, it is not the best choice.");
			
				p.addAnswer(3, "introduced species",
				false,
				"No. Although this is a threat to biodiversity, it is not the best choice.");
			
				p.addAnswer(4, "all of the above",
				true,
				"Correct.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337176;


		
		

		
			
			p.question = "The natural human connection to nature and other forms of life is called _____. (<script type=\"text/javascript\">ebook(\'5601\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "biophilia",
				true,
				"Correct.  This term was coined by Edward O. Wilson.");
			
				p.addAnswer(2, "biodiversity",
				false,
				"No. Biodiversity is a measure of the genetic, species, and ecosystem diversity.");
			
				p.addAnswer(3, "bioremediation",
				false,
				"No. Bioremediation is the use of organisms, usually prokaryotes, fungi, or plants, to detoxify polluted ecosystems.");
			
				p.addAnswer(4, "photophilia",
				false,
				"No. This is not a recognized term in biology.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337177;


		
		

		
			
			p.question = "Which of the following groups is most severely threatened with extinction? (<script type=\"text/javascript\">ebook(\'5601\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "amphibians",
				true,
				"Correct.");
			
				p.addAnswer(2, "birds",
				false,
				"No. However, 12% of the bird species of the world are considered to be threatened with extinction.");
			
				p.addAnswer(3, "mammals",
				false,
				"No. However, 20% of the mammal species of the world are considered to be threatened with extinction.");
			
				p.addAnswer(4, "plants",
				false,
				"No. About 5% of the plant species in the United States are threatened with extinction or have gone extinct since records have been kept.");
			
				p.addAnswer(5, "trilobites",
				false,
				"No. All trilobites went extinct about 250 million years ago.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337178;


		
		

		
			
			p.question = "Which major threat to biodiversity has contributed to about 40% of the extinctions recorded since 1750, and is brought on by humans deliberately and accidentally? (<script type=\"text/javascript\">ebook(\'5601\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "habitat destruction",
				false,
				"No. Although this is the greatest threat today, habitat destruction by humans is rarely an accident.");
			
				p.addAnswer(2, "bioremediation",
				false,
				"No. Bioremediation is not a major threat to biodiversity.");
			
				p.addAnswer(3, "introduced species",
				true,
				"Correct. Introduced species have been brought to new ecosystems unintentionally (on the hulls of boats, for example) and intentionally (such as kudzu, which was brought to the United States from Japan to fight erosion).");
			
				p.addAnswer(4, "overexploitation",
				false,
				"No. This is also a major threat to biodiversity and has contributed to many extinctions, but not 40% in the last 250+ years.");
			
				p.addAnswer(5, "disruption of interaction networks",
				false,
				"No. This is not the correct answer, although the correct answer can cause disruptions of interaction networks.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337179;


		
		

		
			
			p.question = "Clearing a forest to create a region for grazing cattle is an example of what type of threat to biodiversity? (<script type=\"text/javascript\">ebook(\'5601\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "habitat loss",
				true,
				"Correct.  Every organism living in that forest would suffer habitat loss.");
			
				p.addAnswer(2, "introduced species",
				false,
				"No. The introduction of nonnative species is not best illustrated by the destruction of a forest.");
			
				p.addAnswer(3, "overexploitation",
				false,
				"No. Overexploitation is the excessive harvesting of a natural resource.");
			
				p.addAnswer(4, "bioremediation",
				false,
				"No. Bioremediation is the use of organisms, usually prokaryotes, fungi, or plants, to detoxify polluted ecosystems.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337180;


		
		

		
			
			p.question = "What is the key factor driving an extinction vortex? (<script type=\"text/javascript\">ebook(\'5602\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the size of the endangered organisms",
				false,
				"No. This has a lot to do with how much land the organism needs to survive, but it is not the key factor driving an extinction vortex.");
			
				p.addAnswer(2, "loss of genetic variation",
				true,
				"Correct. Populations depend on genetic variation for evolutionary response to environmental change.");
			
				p.addAnswer(3, "the size of the population",
				false,
				"No. The importance of this factor varies depending on the species in question.");
			
				p.addAnswer(4, "the major threats to biodiversity that were involved in making the species endangered",
				false,
				"No. The type of threat involved is not the key factor in the extinction vortex.");
			
				p.addAnswer(5, "how involved humans are in saving the population from extinction",
				false,
				"No. Human involvement is not the key factor, although humans can influence the key factor.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337181;


		
		

		
			
			p.question = "What is the effective population size of a population containing 1,200 individuals of whom 500 females breed with 500 males? (<script type=\"text/javascript\">ebook(\'5602\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "1,000 or 83.3%",
				true,
				"Correct. <i>N</i><sub>e</sub> = 4<i>N</i><sub>f </sub><i>N</i><sub>m</sub>/<i>N</i><sub>f</sub> + <i>N</i><sub>m</sub>");
			
				p.addAnswer(2, "1,000 or 100%",
				false,
				"No. If the actual population is 1,200, but only 1,000 members breed, then less than 100% of the population is effective.");
			
				p.addAnswer(3, "250 or 20.8%",
				false,
				"No. A far greater number of the population is effective. Did you forget to multiply <i>N</i><sub>f </sub><i>N</i><sub>m</sub> by 4?");
			
				p.addAnswer(4, "1,200 or 100%",
				false,
				"No. Not all 1,200 members of the population breed.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337182;


		
		

		
			
			p.question = "The declining-population approach _____. (<script type=\"text/javascript\">ebook(\'5602\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "emphasizes the environmental factors that caused a population\'s decline",
				true,
				"Correct. The declining-population approach focuses on threatened and endangered populations that show a downward trend.");
			
				p.addAnswer(2, "emphasizes smallness itself as an ultimate cause of a population\'s extinction",
				false,
				"No. This describes the small-population approach.");
			
				p.addAnswer(3, "emphasizes the impact of the loss of genetic diversity in a population",
				false,
				"No. This describes the small-population approach.");
			
				p.addAnswer(4, "was used to help increase the population size of prairie chickens in Illinois",
				false,
				"No. The small-population approach was used in this case.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. Only one of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337183;


		
		

		
			
			p.question = "What is one viable solution to help increase the effective size and genetic variation in the grizzly bear population in Yellowstone National Park? (<script type=\"text/javascript\">ebook(\'5602\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Conservation biologists could increase genetic diversity by selectively breeding bears within the Yellowstone population that have not bred together before.",
				false,
				"No. The gene pool is so small within this population that this would not help.");
			
				p.addAnswer(2, "Conservation biologists could introduce another population of bears of equal size to Yellowstone.",
				false,
				"No. This would be overkill. Introducing just two bears from another population might be enough.");
			
				p.addAnswer(3, "Conservation biologists could introduce just two new bears each decade from another population.",
				true,
				"Correct. Computer models predict that introducing only two unrelated bears each decade into a population of 100 individuals would reduce the loss of genetic variation by about half.");
			
				p.addAnswer(4, "The park should be closed to humans until the bear population can revive.",
				false,
				"No. This could solve some problems for the bears, but it won\'t increase genetic variation.");
			
				p.addAnswer(5, "Conservation biologists could develop methods to help bears locate each other for breeding.",
				false,
				"No. This won\'t increase genetic variation in the population.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337184;


		
		

		
			
			p.question = "Which statement below describes a finding of researchers who studied the decline of red-cockaded woodpeckers? (<script type=\"text/javascript\">ebook(\'5602\',\'quiz\')</script>).";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The population decline could be traced to periodic brush fires.",
				false,
				"No. In fact, periodic brush fires are required for the success of the woodpeckers. They require a clear flight path between their home trees and the neighboring feeding grounds.");
			
				p.addAnswer(2, "The woodpeckers live in groups of one breeding pair and up to four sterile \"helpers\" that help incubate eggs and feed nestlings.",
				false,
				"No. The helpers are not necessarily sterile. Some of them eventually attain breeding status when older members of the population die.");
			
				p.addAnswer(3, "Individuals generally have a better chance of reproducing by remaining behind than by dispersing and excavating homes in new territories.",
				true,
				"Correct. It can take several years for the young birds to excavate new nesting cavities.");
			
				p.addAnswer(4, "The birds would not occupy nesting cavities created by the researchers.",
				false,
				"No. The researchers created 20 new cavities. Eighteen of the cavities were occupied by red-cockaded woodpeckers.");
			
				p.addAnswer(5, "Red-cockaded woodpeckers drill small holes around their nest cavities. The resin that accumulates around the holes attracts small insects for the nestlings feed to eat.",
				false,
				"No. The resin seems to repel certain predators, such as corn snakes, that eat bird eggs and nestlings.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337185;


		
		

		
			
			p.question = "Which of the following is a step in the declining-population approach to species conservation? (<script type=\"text/javascript\">ebook(\'5602\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "confirm that the species is in decline",
				false,
				"No. Although this is a step in the declining-population approach to species conservation, there is a better choice.");
			
				p.addAnswer(2, "determine the species\' environmental requirements",
				false,
				"No.<b> </b>Although this is a step in the declining-population approach to species conservation, there is a better choice.");
			
				p.addAnswer(3, "develop hypotheses for all possible causes of the decline",
				false,
				"No. Although this is a step in the declining-population approach to species conservation, there is a better choice.");
			
				p.addAnswer(4, "test the most likely hypothesis first",
				false,
				"No. Although this is a step in the declining-population approach to species conservation, there is a better choice.");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct. This approach requires many different steps.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337186;


		
		

		
			
			p.question = "The MVP of a population _____. (<script type=\"text/javascript\">ebook(\'5602\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "requires that researchers calculate the effective population size",
				true,
				"Correct.");
			
				p.addAnswer(2, "is largely based upon the dietary habits of the species",
				false,
				"No. The MVP is a measure of the minimum viable population size.");
			
				p.addAnswer(3, "is used to estimate the impact that a species has on other species in its environment",
				false,
				"No. The MVP is a measure of the minimum viable population size.");
			
				p.addAnswer(4, "applies only to those species that migrate over great distances to reproduce",
				false,
				"No. The MVP is a measure of the minimum viable population size.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337187;


		
		

		
			
			p.question = "Which of the following is most closely associated with the declining-population approach? (<script type=\"text/javascript\">ebook(\'5602\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the evaluation of population declines on a case-by-case basis",
				true,
				"Correct.  In this approach, species are evaluated by whether or not their population has declined, and what is causing this decline (regardless of the population\'s actual size).");
			
				p.addAnswer(2, "extinction vortex",
				false,
				"No. This is an important aspect of the small-population approach.");
			
				p.addAnswer(3, "minimum viable population size",
				false,
				"No. This is an important aspect of the small-population approach.");
			
				p.addAnswer(4, "effective population size",
				false,
				"No. This is an important aspect of the small-population approach.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337188;


		
		

		
			
			p.question = "What did the researchers do that caused red-cockaded woodpeckers to form new breeding groups at new sites? (<script type=\"text/javascript\">ebook(\'5602\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "constructed nesting cavities at new sites",
				true,
				"Correct.  This allowed new individuals to settle in an area without excavating their own nesting cavities.");
			
				p.addAnswer(2, "killed corn snakes in the area",
				false,
				"No. The researchers did not do this.");
			
				p.addAnswer(3, "introduced new species of insects to the surrounding region as a new food source",
				false,
				"No. The researchers did not do this. Introducing new species anywhere risks the problems associated with introduced species.");
			
				p.addAnswer(4, "introduced 20 new red-cockaded woodpeckers to the breeding population",
				false,
				"No. The researchers did not do this.");
			
				p.addAnswer(5, "permitted the understory around the pines to grow taller than usual",
				false,
				"No. The researchers did the opposite of this. They included controlled burning to keep the understory low.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337189;


		
		

		
			
			p.question = "Which of the following statements about edge effects is correct? (<script type=\"text/javascript\">ebook(\'5603\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "They are defining features of landscapes.",
				false,
				"No. This is true, but there is a better choice.");
			
				p.addAnswer(2, "Edges have their own set of physical conditions, which differ from those on either side.",
				false,
				"No. This is true, but there is a better choice.");
			
				p.addAnswer(3, "As a habitat patch becomes progressively smaller, the percentage of the patch influenced by the edge effect increases.",
				false,
				"No. This is true, but there is a better choice.");
			
				p.addAnswer(4, "As habitats are fragmented, edge-adapted species benefit at the expense of other species that are not edge-adapted.",
				false,
				"No. This is true, but there is a better choice.");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct.  These statements all describe edge effects.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337190;


		
		

		
			
			p.question = "Which statement below about movement corridors is correct? (<script type=\"text/javascript\">ebook(\'5603\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Lakes often serve as corridors.",
				false,
				"No. Streamside habitats often serve as corridors.");
			
				p.addAnswer(2, "Corridors have been shown to decrease the exchange of individuals among populations.",
				false,
				"No. Corridors have been shown to increase the exchange of individuals among populations.");
			
				p.addAnswer(3, "Artificial corridors such as bridges and tunnels have saved many animals from being killed crossing highways.",
				true,
				"Correct. This is a true statement.");
			
				p.addAnswer(4, "Corridors are especially important to species that do not migrate.",
				false,
				"No. Corridors are especially important to species that migrate among different habitats seasonally.");
			
				p.addAnswer(5, "Corridors have been instrumental in stopping the spread of disease.",
				false,
				"No. A corridor can be instrumental in the spread of disease, which is especially harmful in regard to small populations.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337191;


		
		

		
			
			p.question = "The \"zoned reserve\" system of landscape management calls for _____. (<script type=\"text/javascript\">ebook(\'5603\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "many small interconnected nature reserves",
				false,
				"No. However, this is another approach to land management.");
			
				p.addAnswer(2, "protected areas to be surrounded by buffer zones",
				true,
				"Correct. In transitional areas, sustainable land use is promoted and the most destructive human activities are conducted on the outermost fringes.");
			
				p.addAnswer(3, "bioremediation",
				false,
				"No. Bioremediation is the use of organisms to detoxify pollutants.");
			
				p.addAnswer(4, "assisting the movement of individuals from a source to a sink population",
				false,
				"No. This is not applicable to the zoned reserve system.");
			
				p.addAnswer(5, "movement corridors",
				false,
				"No. Movement corridors are helpful in areas that have been fragmented.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337192;


		
		

		
			
			p.question = "What country is a world leader in zoned reserves? (<script type=\"text/javascript\">ebook(\'5603\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Costa Rica",
				true,
				"Correct.  Costa Rica contains eight zoned reserves.");
			
				p.addAnswer(2, "Canada",
				false,
				"No. Canada is not in Central America.");
			
				p.addAnswer(3, "Peru",
				false,
				"No. Peru is not in Central America.");
			
				p.addAnswer(4, "Belize",
				false,
				"No. However, Belize is an ecologically important country in Central America.");
			
				p.addAnswer(5, "Panama",
				false,
				"No. However, Panama is an ecologically important country in Central America.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337193;


		
		

		
			
			p.question = "Connections between habitat fragments are referred to as _____. (<script type=\"text/javascript\">ebook(\'5603\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "movement corridors",
				true,
				"Correct. Movement corridors allow the movement of species among patches.");
			
				p.addAnswer(2, "highways",
				false,
				"No. This is not the term used for such connections, but human-made highways are responsible for some habitat fragmentation.");
			
				p.addAnswer(3, "minimum dynamic areas",
				false,
				"No. The minimum dynamic area is the amount of area needed to maintain a self-perpetuating population.");
			
				p.addAnswer(4, "riparian areas",
				false,
				"No. Riparian areas may allow for movement between fragments, but not all movement between fragments takes place through riparian areas.");
			
				p.addAnswer(5, "landscapes",
				false,
				"No. Landscapes are composed of a group of interacting ecosystems.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337194;


		
		

		
			
			p.question = "Biodiversity hot spots are _____. (<script type=\"text/javascript\">ebook(\'5603\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "distributed evenly throughout the biosphere",
				false,
				"No. Biodiversity hot spots are concentrated in the tropics.");
			
				p.addAnswer(2, "regions with the potential for high levels of extinction",
				true,
				"Correct. Biodiversity hot spots are regions with a high concentration of endemic species; these species are at high risk of extinction should the hot spot be degraded.");
			
				p.addAnswer(3, "the same for all groups of organisms",
				false,
				"No. Not all groups of organisms share hot spots.");
			
				p.addAnswer(4, "regions where thermophilic species thrive",
				false,
				"No. In this instance, the word \"hot\" is not being used in reference to temperature.");
			
				p.addAnswer(5, "resistant to environmental degradation due to their large number of species",
				false,
				"No. Biodiversity hot spots are not necessarily more or less resistant to degradation than any other area.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337195;


		
		

		
			
			p.question = "_____ is the science of facilitating the return of a degraded ecosystem to a more natural condition. (<script type=\"text/javascript\">ebook(\'5604\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "population viability analysis",
				false,
				"No. However, population viability analysis (PVA) is a tool that can be used to aid in the process of returning an ecosystem to its predegraded state.");
			
				p.addAnswer(2, "preservationism",
				false,
				"No. Preservationism is the attempt to keep designated areas free from direct human intervention.");
			
				p.addAnswer(3, "landscape management",
				false,
				"No. Landscape management is primarily concerned with the preservation of undisturbed areas.");
			
				p.addAnswer(4, "restoration ecology",
				true,
				"Correct. Restoration ecology applies ecological principles to the restoration of degraded ecosystems.");
			
				p.addAnswer(5, "biophilia",
				false,
				"No. Biophilia is the term used to describe the human sense of connectedness to nature.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337196;


		
		

		
			
			p.question = "The use of organisms to add essential materials to degraded systems defines _____. (<script type=\"text/javascript\">ebook(\'5604\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "biophilia",
				false,
				"No. Biophilia is the term used to describe the human sense of connectedness to nature.");
			
				p.addAnswer(2, "restoration ecology",
				false,
				"No. Restoration ecology applies ecological principles to the restoration of degraded ecosystems.");
			
				p.addAnswer(3, "bioremediation",
				false,
				"No. Bioremediation is a strategy to remove harmful substances from disturbed regions.");
			
				p.addAnswer(4, "biological augmentation",
				true,
				"Correct. This process uses organisms to supply necessary nutrients that allow damaged habitats to recover more speedily.");
			
				p.addAnswer(5, "landscape management",
				false,
				"No. Landscape management is primarily concerned with the preservation of undisturbed areas.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337197;


		
		

		
			
			p.question = "What does E. O. Wilson propose regarding the concept of biophilia? (<script type=\"text/javascript\">ebook(\'5605\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Humans cannot control the urge to \"subdue\" Earth.",
				false,
				"No. Just the opposite is true. Wilson proposed that biophilia is innate and is part of human evolution.");
			
				p.addAnswer(2, "Biophilia is an evolutionary product of natural selection acting on a brainy species whose survival depended on a close connection to the environment.",
				true,
				"Correct. Biologists are hopeful that this is the case.");
			
				p.addAnswer(3, "\"We must consider our planet to be on loan from our children, rather than being a gift from our ancestors.\"",
				false,
				"No. This is a quote from Bruntland, former prime minister of Norway.");
			
				p.addAnswer(4, "We should concentrate on our desire to save the environment for its resources.",
				false,
				"No. This was not Wilson\'s theory, and many environmentalists hope that we can look beyond our \"needs\" and make efforts to save species just for the sake of saving them.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337198;


		
		

		
			
			p.question = "One of the most impressive models of sustainable development can be seen in the _____. (<script type=\"text/javascript\">ebook(\'5605\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "United States\' national park system",
				false,
				"No. Although an admirable piece of conservation, the national parks are not subject to development, sustainable or otherwise.");
			
				p.addAnswer(2, "use of petroleum products in Western countries",
				false,
				"No. Oil is a finite resource and, at the current usage rate, is not sustainable.");
			
				p.addAnswer(3, "increasing popularity of organic farming",
				false,
				"No. Although organic farming has minimal ecological impact, it is not clear whether organic farms can feed the world\'s population.");
			
				p.addAnswer(4, "Costa Rican zoned reserves",
				true,
				"Correct. Costa Rica\'s commitment to conservation is succeeding economically and ecologically.");
			
				p.addAnswer(5, "growth of open lands programs sponsored by a variety of government entities",
				false,
				"No. While admirable programs, they do not encourage development.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337199;


		
		

		
			
			p.question = "Which of the following factors can decrease biodiversity? (<script type=\"text/javascript\">ebook(\'5605\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "complex population interactions",
				false,
				"No. Complex population interactions increase biodiversity.");
			
				p.addAnswer(2, "introduced species",
				true,
				"Correct. Introduced species do frequently reduce biodiversity.");
			
				p.addAnswer(3, "a higher degree of habitat heterogeneity",
				false,
				"No. This plays a role in increased biodiversity. The more heterogeneous the habitat, the larger the number of possible niches.");
			
				p.addAnswer(4, "narrower niches",
				false,
				"No. This plays a role in increased biodiversity. The narrower the niche, the less competition for resources and the greater the potential for biodiversity.");
			
				p.addAnswer(5, "increased energy availability",
				false,
				"No. Energy, primarily in the form of sunlight, regulates primary productivity. Increasing productivity does increase the availability of resources.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

