

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "33: Invertebrates > Practice Test";
	ak.quiz_loc_with_commas = "33: Invertebrates, Practice Test";
	ak.quiz_title = "Practice Test";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 38;
	ak.non_essay_total = 38;
	ak.scored_item_total = 38;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335942;


		
		

		
			
			p.question = "Sponges feed by _____. (<script type=\"text/javascript\">ebook(\'3301\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "filtering small particles from water",
				true,
				"Correct. Sponges trap food from the water circulating through their porous bodies.");
			
				p.addAnswer(2, "scraping bacteria and algae from hard substrates",
				false,
				"No. Sponges lack the anatomy to do this.");
			
				p.addAnswer(3, "paralyzing small crustaceans with stinging cells",
				false,
				"No. Sponges do not have paralyzing structures.");
			
				p.addAnswer(4, "absorbing nutrients from the guts of their hosts",
				false,
				"No. Sponges are not endoparasites.");
			
				p.addAnswer(5, "performing photosynthesis",
				false,
				"No. Some sponges do harbor photosynthetic endosymbionts, but they still obtain the bulk of their nutrition from suspension feeding.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335943;


		
		

		
			
			p.question = "Sponges lack _____. (<script type=\"text/javascript\">ebook(\'3301\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a complete digestive tract",
				false,
				"No. This choice is correct, but there is a better response.");
			
				p.addAnswer(2, "a nervous system",
				false,
				"No. This choice is correct, but there is a better response.");
			
				p.addAnswer(3, "the ability to make organic compounds from CO<sub>2</sub> and water",
				false,
				"No. This choice is correct, but there is a better response.");
			
				p.addAnswer(4, "true tissues",
				false,
				"No. This choice is correct, but there is a better response.");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct. Sponges have no nerves or muscles, and they are suspension feeders that trap food from water circulated through their porous bodies.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335944;


		
		

		
			
			p.question = "Some digestion in sponges takes place in the _____. (<script type=\"text/javascript\">ebook(\'3301\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "amoebocytes",
				true,
				"Correct. Amoebocytes digest the food that sponges pick up from water and from choanocytes.");
			
				p.addAnswer(2, "osculum",
				false,
				"No. Water that has been drawn into a sponge\'s central cavity exits via the osculum.");
			
				p.addAnswer(3, "gastrovascular cavity",
				false,
				"No. Sponges do not have a gastrovascular cavity.");
			
				p.addAnswer(4, "spongocoel",
				false,
				"No. The spongocoel is the central cavity of a sponge into which water flows, and from which food is captured. However, food is not digested here.");
			
				p.addAnswer(5, "gastrointestinal tract",
				false,
				"No. Sponges do not have a gastrointestinal tract.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335945;


		
		

		
			
			p.question = "Which of the following is(are) characteristic of sponges? (<script type=\"text/javascript\">ebook(\'3301\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "They have collar cells.",
				false,
				"No. This choice is correct, but there is a better response.");
			
				p.addAnswer(2, "They consist of two layers of cells with a noncellular gelatinous layer between them.",
				false,
				"No. This choice is correct, but there is a better response.");
			
				p.addAnswer(3, "They have holes, or pores, in specialized cells, through which water enters.",
				false,
				"No. This choice is correct, but there is a better response.");
			
				p.addAnswer(4, "all of the above",
				true,
				"Correct. These are all characteristic of sponges.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. All of the traits above are characteristic of sponges.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335946;


		
		

		
			
			p.question = "Which one of the following features is characteristic of the poriferan (sponge) body plan or life history? (<script type=\"text/javascript\">ebook(\'3301\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "closed circulatory system",
				false,
				"No. Sponges do not exhibit this degree of complexity.");
			
				p.addAnswer(2, "ventral nerve chord",
				false,
				"No. Sponges do not exhibit this degree of complexity.");
			
				p.addAnswer(3, "motile larvae",
				true,
				"Correct. Zygotes develop into flagellated, swimming larvae that disperse from the parent.");
			
				p.addAnswer(4, "extracellular digestion",
				false,
				"No. Sponges lack a cavity in which digestion could take place.");
			
				p.addAnswer(5, "specialized respiratory surfaces",
				false,
				"No. Sponges do not exhibit this degree of complexity.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335947;


		
		

		
			
			p.question = "Some cnidarians go through both a motile and a sessile (attached) stage during their life cycle. The attached stage is called a(n) _____. (<script type=\"text/javascript\">ebook(\'3302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "embryo",
				false,
				"No. This is neither the motile nor the sessile stage referred to in this question.");
			
				p.addAnswer(2, "medusa",
				false,
				"No. The medusa is not an attached form.");
			
				p.addAnswer(3, "larva",
				false,
				"No. The larva is not an attached form.");
			
				p.addAnswer(4, "mesoglea",
				false,
				"No. This is a part of a cnidarian\'s body.");
			
				p.addAnswer(5, "polyp",
				true,
				"Correct. Sessile polyps are cylindrical forms that attach to a substratum and extend their tentacles, waiting for prey.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335948;


		
		

		
			
			p.question = "Through what means do coral animals capture their food? (<script type=\"text/javascript\">ebook(\'3302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "photosynthesis",
				false,
				"No. However, some corals do harbor photosynthetic endosymbionts.");
			
				p.addAnswer(2, "tentacles that trap food particles",
				true,
				"Correct. Coral animals, like all cnidarians, have tentacles armed with batteries of stinging cells called cnidocytes. They use those tentacles to capture prey and push food into the gastrovascular cavity.");
			
				p.addAnswer(3, "absorption of predigested food through their cuticle",
				false,
				"No. Corals do not have this ability.");
			
				p.addAnswer(4, "dinoflagellates, photosynthetic protists that live in the coral\'s tissues",
				false,
				"No. However, some corals do harbor photosynthetic endosymbionts.");
			
				p.addAnswer(5, "teeth that shred their prey",
				false,
				"No. Coral animals lack teeth.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335949;


		
		

		
			
			p.question = "_____ are members of the phylum _____ and feed by _____. (<script type=\"text/javascript\">ebook(\'3302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Sponges; Urochordata; scraping away organic films covering the rocks on which they grow",
				false,
				"No. Urochordates are a chordate subphylum.");
			
				p.addAnswer(2, "Leeches; Porifera; filtering tiny particles from water passing through their bodies",
				false,
				"No. Leeches are not a type of sponge.");
			
				p.addAnswer(3, "Corals; Cnidaria; using stinging cells to capture small animals that venture too close to them",
				true,
				"Correct. Cnidaria, including coral animals, have tentacles armed with cnidocytes, unique stinging cells that function in defense and in the capture of prey.");
			
				p.addAnswer(4, "Bivalves; Annelida; killing small animals with electric shock",
				false,
				"No. Bivalves are molluscan suspension feeders.");
			
				p.addAnswer(5, "Rotifers; Arthropoda; a lophophore",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335950;


		
		

		
			
			p.question = "Jellies and corals are members of the same _____, all members of which _____. (<script type=\"text/javascript\">ebook(\'3302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "family; have a complete circulatory system",
				false,
				"No. Neither has a complete circulatory system.");
			
				p.addAnswer(2, "phylum; have a colonial lifestyle",
				false,
				"No. Although they are in the same phylum, jellies are not colonial organisms.");
			
				p.addAnswer(3, "order; are herbivorous",
				false,
				"No. The two groups are in different orders.");
			
				p.addAnswer(4, "phylum; have special stinging cells on their tentacles",
				true,
				"Correct. Jellies and coral animals are cnidarians, which have tentacles armed with batteries of stinging cells called cnidocytes.");
			
				p.addAnswer(5, "genus; lack a circulatory system",
				false,
				"No. The two groups are in different genera. In fact, they are in different classes!");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335951;


		
		

		
			
			p.question = "The choanocyte of a sponge and the nematocyst of a cnidarian both function in _____. (<script type=\"text/javascript\">ebook(\'3302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "reproduction",
				false,
				"No. Lining the inside of a spongocoel are flagellated choanocytes, which trap food particles. Nematocysts are stinging capsules that function in defense and in the capture of prey.");
			
				p.addAnswer(2, "locomotion",
				false,
				"No. Lining the inside of a spongocoel are flagellated choanocytes, which trap food particles. Nematocysts are stinging capsules that function in defense and in the capture of prey.");
			
				p.addAnswer(3, "obtaining food",
				true,
				"Correct. Lining the inside of a spongocoel are flagellated choanocytes, which trap food particles. Nematocysts are stinging capsules that function in defense and in the capture of prey.");
			
				p.addAnswer(4, "locating mates",
				false,
				"No. Lining the inside of a spongocoel are flagellated choanocytes, which trap food particles. Nematocysts are stinging capsules that function in defense and in the capture of prey.");
			
				p.addAnswer(5, "sight",
				false,
				"No. Neither of these types of animals can \"see.\" Lining the inside of a spongocoel are flagellated choanocytes, which trap food particles. Nematocysts are stinging capsules that function in defense and in the capture of prey.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335952;


		
		

		
			
			p.question = "Which of the following is true about the phylum Cnidaria? (<script type=\"text/javascript\">ebook(\'3302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The bodies of its members are organized around a gastrovascular cavity.",
				true,
				"Correct. This statement does describe the phylum Cnidaria.");
			
				p.addAnswer(2, "This phylum has more species than any other phylum.",
				false,
				"No. The phylum Arthropoda has more species than any other phylum.");
			
				p.addAnswer(3, "All cnidarians except corals are in the medusa stage.",
				false,
				"No. The life cycles of many of its members alternate between a feeding polyp and a reproductive medusa.");
			
				p.addAnswer(4, "The bodies of its members are bilaterally symmetrical and show cephalization.",
				false,
				"No. The bodies of its members are radially symmetrical and show no cephalization.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. Only one of the statements is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335953;


		
		

		
			
			p.question = "Tapeworms are highly specialized worms that make their living as endoparasites. To which of the following phyla and classes do the tapeworms belong? (<script type=\"text/javascript\">ebook(\'3303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "phylum Annelida, class Oligochaeta",
				false,
				"No. Tapeworms are not annelids.");
			
				p.addAnswer(2, "phylum Annelida, class Hirudinoidea",
				false,
				"No. Tapeworms are not annelids.");
			
				p.addAnswer(3, "phylum Nematoda, class Polychaeta",
				false,
				"No. Tapeworms are not nematodes (and neither are polychaetes).");
			
				p.addAnswer(4, "phylum Platyhelminthes, class Cestoidea",
				true,
				"Correct. Tapeworms are platyhelminths and belong to the class Cestoidea.");
			
				p.addAnswer(5, "phylum Platyhelminthes, class Turbellaria",
				false,
				"No. Right phylum, wrong class.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335954;


		
		

		
			
			p.question = "Which of the following classes is (are) completely parasitic? (<script type=\"text/javascript\">ebook(\'3303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Cestoidea",
				false,
				"No. This choice is correct, but there is a better response.");
			
				p.addAnswer(2, "Turbellaria",
				false,
				"No. Most turbellarians are free-living.");
			
				p.addAnswer(3, "Trematoda",
				false,
				"No. This choice is correct, but there is a better response.");
			
				p.addAnswer(4, "Cestoidea and Trematoda",
				true,
				"Correct. Trematodes (class Trematoda) and tapeworms (class Cestoidea) are parasitic, as are monogeneans (class Monogenea).");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. One of the other choices is most correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335955;


		
		

		
			
			p.question = "The proglottids of a tapeworm contain an elaborate _____ system. (<script type=\"text/javascript\">ebook(\'3303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "sensory",
				false,
				"No. Proglottids are sacs of sex organs.");
			
				p.addAnswer(2, "digestive",
				false,
				"No. Tapeworms do not have a digestive system.");
			
				p.addAnswer(3, "circulatory",
				false,
				"No. Tapeworms do not have a circulatory system.");
			
				p.addAnswer(4, "reproductive",
				true,
				"Correct. Posterior to the head, or scolex, is a long ribbon of units called proglottids, which are little more than sacs of sex organs.");
			
				p.addAnswer(5, "attachment",
				false,
				"No. The scolex plays a role in attachment.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335956;


		
		

		
			
			p.question = "Some species of rotifers undergo parthenogenesis, which means that _____. (<script type=\"text/javascript\">ebook(\'3303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "their larval stage of development looks completely different from the adult stage",
				false,
				"No. This describes complete metamorphosis, which occurs in many insect species.");
			
				p.addAnswer(2, "they shed their exoskeleton as they grow",
				false,
				"No. This refers to molting, which occurs several times during the lives of most arthropods.");
			
				p.addAnswer(3, "each individual functions as both male and female in sexual reproduction by producing sperm and eggs",
				false,
				"No. This is true of hermaphrodites and does not describe parthenogenesis.");
			
				p.addAnswer(4, "the species consists of only females that produce more females from unfertilized eggs",
				true,
				"Correct. How these species of rotifers have survived for millions of years with this type of reproduction is a puzzle.");
			
				p.addAnswer(5, "during development of adult forms, some of the organs that were bilateral are reduced in size or are lost on one side of the body",
				false,
				"No. This is called torsion, and it is a characteristic of gastropods.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335957;


		
		

		
			
			p.question = "Consider the following list of animals: giant squid, earthworm, largemouth bass, snail, tapeworm, coral, and starfish. The two that belong to the same phylum are the _____, and their phylum is _____. (<script type=\"text/javascript\">ebook(\'3303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "bass and giant squid; Mollusca",
				false,
				"No. The bass is a fish, not a mollusc.");
			
				p.addAnswer(2, "earthworm and tapeworm; Annelida",
				false,
				"No. Tapeworms are not annelids.");
			
				p.addAnswer(3, "coral and starfish; Echinodermata",
				false,
				"No. Corals are not echinoderms.");
			
				p.addAnswer(4, "giant squid and snail; Mollusca",
				true,
				"Correct. The giant squid and the snail are both molluscs.");
			
				p.addAnswer(5, "snail and coral; Annelida",
				false,
				"No. Neither of these is an annelid.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335958;


		
		

		
			
			p.question = "An active marine predator is found possessing these characteristics: a series of tentacles (modified from the foot), a highly developed nervous system, and elaborate eyes. To which of the following animal classes does this organism most likely belong? (<script type=\"text/javascript\">ebook(\'3303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Chelicerata",
				false,
				"No. Chelicerates are arthropods which do not have tentacles modified from a foot.");
			
				p.addAnswer(2, "Cephalopoda",
				true,
				"Correct. The foot of a cephalopod has been modified into a muscular siphon and parts of the tentacles and head. Cephalopods use beak-like jaws to bite their prey. They have a well-developed nervous system with a complex brain.");
			
				p.addAnswer(3, "Polyplacophora",
				false,
				"No. Correct phylum but wrong class.");
			
				p.addAnswer(4, "Polychaeta",
				false,
				"No. Polychaetes are annelids.");
			
				p.addAnswer(5, "Bivalvia",
				false,
				"No. Correct phylum, wrong class.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335959;


		
		

		
			
			p.question = "Cephalopods are the only molluscs _____. (<script type=\"text/javascript\">ebook(\'3303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "that have a mantle that produces a shell",
				false,
				"No. The cephalopod mantle covers the visceral mass but, with the exception of the chambered nautilus, no extant cephalopod has a shell.");
			
				p.addAnswer(2, "with a closed circulatory system",
				true,
				"Correct. No other mollusc has a closed circulatory system. Cephalopods also have a complex brain and exhibit complex behavior and the ability to learn.");
			
				p.addAnswer(3, "that reproduce sexually",
				false,
				"No. Molluscs typically reproduce sexually.");
			
				p.addAnswer(4, "with segmented bodies",
				false,
				"No. Although chitons have segmented dorsal plates, molluscs do not have a clearly segmented body.");
			
				p.addAnswer(5, "that are hermaphrodites",
				false,
				"No. In cephalopods the sexes are separate.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335960;


		
		

		
			
			p.question = "Annelids _____. (<script type=\"text/javascript\">ebook(\'3303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "include leeches, earthworms, and polychaete worms",
				false,
				"No. This choice is correct, but there is a better response.");
			
				p.addAnswer(2, "have characteristically long bodies with both internal and external segmentation",
				false,
				"No. This choice is correct, but there is a better response.");
			
				p.addAnswer(3, "use their coeloms as hydrostatic skeletons",
				false,
				"No. This choice is correct, but there is a better response.");
			
				p.addAnswer(4, "have a mouth that is separate from the anus",
				false,
				"No. This choice is correct, but there is a better response.");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct. Annelids are segmented worms. The phylum includes earthworms, polychaete worms, and leeches. They have characteristically long bodies with both internal and external segmentation. They have coeloms, which function as hydrostatic skeletons, and they have a two-opening digestive system.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335961;


		
		

		
			
			p.question = "Which of the following are lophotrochozoans that have a lophophore? (<script type=\"text/javascript\">ebook(\'3303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "nematodes",
				false,
				"No. Nematodes are not lophotrochozoans.");
			
				p.addAnswer(2, "sea urchins",
				false,
				"No. Sea urchins are not lophotrochozoans.");
			
				p.addAnswer(3, "tapeworms",
				false,
				"No. Although tapeworms are lophotrochozoans, they do not have a lophophore.");
			
				p.addAnswer(4, "ectoprocts and brachiopods",
				true,
				"Correct. Both groups are lophotrochozoans that have a lophophore.");
			
				p.addAnswer(5, "cephalopods",
				false,
				"No. Although cephalopods are lophotrochozoans, they do not have a lophophore.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335962;


		
		

		
			
			p.question = "Which one of the following phyla contains animals that are lophotrochozoans with a mouth, anus, and true coelom? (<script type=\"text/javascript\">ebook(\'3303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Platyhelminthes",
				false,
				"No. Flatworms do not have an anus, a coelom, or segmentation.");
			
				p.addAnswer(2, "Rotifers",
				false,
				"No. Rotifers have a pseudocoelom.");
			
				p.addAnswer(3, "Annelida",
				true,
				"Correct.");
			
				p.addAnswer(4, "Cnidaria",
				false,
				"No. Cnidarians are not lophotrochozoans.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. Only one phylum above matches the description.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335963;


		
		

		
			
			p.question = "During typical earthworm reproduction _____. (<script type=\"text/javascript\">ebook(\'3303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "each individual fertilizes its own eggs with its own sperm (in self-fertilization)",
				false,
				"No. Earthworms do not fertilize their own eggs.");
			
				p.addAnswer(2, "fertilization takes place during copulation between males and females",
				false,
				"No. Earthworms are hermaphrodites.");
			
				p.addAnswer(3, "hermaphroditic individuals exchange sperm",
				true,
				"Correct. Earthworms are hermaphrodites, but they cross-fertilize.");
			
				p.addAnswer(4, "hermaphroditic individuals exchange eggs",
				false,
				"No. They do not exchange eggs.");
			
				p.addAnswer(5, "reproduction is by parthenogenesis, with no male participation",
				false,
				"No. Earthworms are hermaphrodites that cross-fertilize.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335964;


		
		

		
			
			p.question = "Which of the following is/are true about polychaete worms? (<script type=\"text/javascript\">ebook(\'3303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "They feed by using nematocysts.",
				false,
				"No. This is a characteristic of some cnidarians.");
			
				p.addAnswer(2, "They are ecdysozoans.",
				false,
				"No. Polychaetes are lophotrochozoans.");
			
				p.addAnswer(3, "They typically live in a marine environment.",
				true,
				"Correct. Most polychaetes are marine animals.");
			
				p.addAnswer(4, "They are unsegmented with a radially symmetrical body.",
				false,
				"No. Annelids are segmented with a bilaterally symmetrical body.");
			
				p.addAnswer(5, "They have a water vascular system.",
				false,
				"No. A water vascular system is unique to echinoderms.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335965;


		
		

		
			
			p.question = "Leeches are members of the phylum _____ in the clade of bilaterally symmetric animals called _____. (<script type=\"text/javascript\">ebook(\'3303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Nematoda; Ecdysozoa",
				false,
				"No. Leeches are not roundworms.");
			
				p.addAnswer(2, "Cnidaria; Lophotrochozoa",
				false,
				"No. Leeches have a more complex structure than cnidarians, including an anus and coelom.");
			
				p.addAnswer(3, "Platyhelminthes; Deuterostomia",
				false,
				"No. Leeches are not flatworms. Moreover, flatworms are in the clade Lophotrochozoa.");
			
				p.addAnswer(4, "Annelida; Lophotrochozoa",
				true,
				"Correct.");
			
				p.addAnswer(5, "Arthropoda; Deuterostomia",
				false,
				"No. Leeches are not arthropods. In addition, arthropods are in the clade Ecdysozoa.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335966;


		
		

		
			
			p.question = "Which one of the following groups has a true coelom, a lophophore, and no distinct head? (<script type=\"text/javascript\">ebook(\'3303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "rotifers",
				false,
				"No. Rotifers have a pseudocoelom.");
			
				p.addAnswer(2, "flatworms",
				false,
				"No. Flatworms have no body cavity.");
			
				p.addAnswer(3, "ectoprocts",
				true,
				"Correct.");
			
				p.addAnswer(4, "tapeworms",
				false,
				"No. Tapeworms have no coelom.");
			
				p.addAnswer(5, "sponges",
				false,
				"No. Sponges do not have a coelom or lophophore.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335967;


		
		

		
			
			p.question = "Animals such as _____ are the simplest animals to have _____. (<script type=\"text/javascript\">ebook(\'3304\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "sponges; bilateral symmetry",
				false,
				"No. Sponges do not exhibit bilateral symmetry.");
			
				p.addAnswer(2, "flatworms; a body cavity",
				false,
				"No. Flatworms are acoelomates.");
			
				p.addAnswer(3, "roundworms; a complete digestive tract",
				true,
				"Correct. Nematodes have a complete digestive tract.");
			
				p.addAnswer(4, "jellies; a complete digestive tract",
				false,
				"No. Cnidarians have a gastrovascular cavity.");
			
				p.addAnswer(5, "snails; a body cavity",
				false,
				"No. Almost all molluscs have a coelom, but they are not the simplest animals to have a coelom.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335968;


		
		

		
			
			p.question = "An unidentified species of animal displays the following characteristics: bilateral symmetry, a complete digestive system, an open circulatory system, distinct body segmentation, and it molts when it grows. To which one of the following animal phyla does this species most likely, belong. (<script type=\"text/javascript\">ebook(\'3304\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Cnidaria",
				false,
				"No. Cnidarians exhibit radial symmetry.");
			
				p.addAnswer(2, "Platyhelminthes",
				false,
				"No. Flatworms are not segmented.");
			
				p.addAnswer(3, "Nematoda",
				false,
				"No. Nematodes are not segmented.");
			
				p.addAnswer(4, "Annelida",
				false,
				"No. Annelids have a closed circulatory system.");
			
				p.addAnswer(5, "Arthropoda",
				true,
				"Correct. Arthropods have bilateral symmetry, body segmentation, a complete digestive system, an open circulatory system, and they molt when they grow.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335969;


		
		

		
			
			p.question = "The arthropods superficially resemble earthworms in that both groups _____, yet the two are distinctly different because arthropods, but not earthworms, _____. (<script type=\"text/javascript\">ebook(\'3304\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "have prominently segmented bodies; have jointed appendages",
				true,
				"Correct. Both groups do have segmented bodies, but arthropods have jointed appendages.");
			
				p.addAnswer(2, "have closed circulatory systems; have bristles",
				false,
				"No. Arthropods have an open circulatory system.");
			
				p.addAnswer(3, "are cephalized and bilaterally symmetrical; have true organs",
				false,
				"No. Annelids have true organs.");
			
				p.addAnswer(4, "have a true coelom; have an anus",
				false,
				"No. Both groups have an anus.");
			
				p.addAnswer(5, "are acoelomates; are segmented",
				false,
				"No. Both are coelomates, and both are segmented.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335970;


		
		

		
			
			p.question = "A major characteristic of arthropods is _____. (<script type=\"text/javascript\">ebook(\'3304\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "flame bulbs",
				false,
				"No. Flame bulbs are excretory structures found in flatworms.");
			
				p.addAnswer(2, "radial symmetry",
				false,
				"No. Arthropods exhibit bilateral symmetry.");
			
				p.addAnswer(3, "a pseudocoelom",
				false,
				"No. Arthropods have a true coelom, although it is typically reduced in size.");
			
				p.addAnswer(4, "a chitinous exoskeleton",
				true,
				"Correct. The body of an arthropod is completely covered by the cuticle, an exoskeleton constructed from layers of protein and chitin.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. Only one of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335971;


		
		

		
			
			p.question = "In most insects, gas exchange is accomplished by _____. (<script type=\"text/javascript\">ebook(\'3304\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "flame bulbs",
				false,
				"No. These are the excretory organs of flatworms.");
			
				p.addAnswer(2, "book lungs",
				false,
				"No. These carry out gas exchange in most spiders.");
			
				p.addAnswer(3, "lungs",
				false,
				"No. Insects do not have lungs.");
			
				p.addAnswer(4, "a tracheal system",
				true,
				"Correct. These are branched air ducts leading into the interior from pores in the cuticle.");
			
				p.addAnswer(5, "diffusion across the exoskeleton",
				false,
				"No. The exoskeleton does not allow for gas exchange.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335972;


		
		

		
			
			p.question = "Sowbugs are really crustaceans, not insects. Therefore, a sowbug does <b>not</b> have _____. (<script type=\"text/javascript\">ebook(\'3304\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "an exoskeleton",
				false,
				"No. An exoskeleton is a characteristic shared by all arthropods.");
			
				p.addAnswer(2, "an open circulatory system",
				false,
				"No. This is a characteristic of all arthropods.");
			
				p.addAnswer(3, "three pairs of legs",
				true,
				"Correct. Insects have six legs; crustaceans have a multitude of appendages.");
			
				p.addAnswer(4, "antennae",
				false,
				"No. Both insects and crustaceans have antennae.");
			
				p.addAnswer(5, "jointed appendages",
				false,
				"No. This is a characteristic of all arthropods.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335973;


		
		

		
			
			p.question = "The majority of animal species are _____. (<script type=\"text/javascript\">ebook(\'3304\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "insects",
				true,
				"Correct. In species diversity, insects outnumber all other forms of life combined.");
			
				p.addAnswer(2, "nematodes",
				false,
				"No. Although nematodes are abundant, they are far outnumbered by insects.");
			
				p.addAnswer(3, "marine",
				false,
				"No. In species diversity, insects (which are almost entirely terrestrial) outnumber all other forms of life combined.");
			
				p.addAnswer(4, "acoelomates",
				false,
				"No. Insects, which have a coelom, have the greatest number of species.");
			
				p.addAnswer(5, "vertebrates",
				false,
				"No. Only about five percent of known animal species are vertebrates.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335974;


		
		

		
			
			p.question = "In arthropods, molting is necessary because _____. (<script type=\"text/javascript\">ebook(\'3304\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the chitinous exoskeleton cannot grow",
				true,
				"Correct. The rigid exoskeleton must be shed for an arthropod to grow.");
			
				p.addAnswer(2, "arthropod appendages generally increase in number as the animal ages",
				false,
				"No. The appendages increase in size, not number.");
			
				p.addAnswer(3, "the environment degrades the exoskeleton, which therefore must be shed and replaced",
				false,
				"No. The chitinous exoskeleton is very durable.");
			
				p.addAnswer(4, "worn exoskeletons make arthropods more susceptible to predators",
				false,
				"No. Arthropods outgrow the exoskeletons.");
			
				p.addAnswer(5, "the exoskeleton is progressively reabsorbed by body tissue",
				false,
				"No. Arthropods outgrow their exoskeletons.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335975;


		
		

		
			
			p.question = "Complete metamorphosis _____. (<script type=\"text/javascript\">ebook(\'3304\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "features a larval stage that looks different from the adult",
				true,
				"Correct. Insects with complete metamorphosis have larval stages specialized for eating and growing, which look entirely different from the adult.");
			
				p.addAnswer(2, "is a feature in the life history of a just a few insect species",
				false,
				"No. Complete metamorphosis is common in insects.");
			
				p.addAnswer(3, "is only seen in grasshoppers",
				false,
				"No. Incomplete metamorphosis is more common in grasshoppers.");
			
				p.addAnswer(4, "is accompanied by a complete rearrangement of the genome",
				false,
				"No. The genome is not rearranged, although in some groups chromosomes are lost at metamorphosis.");
			
				p.addAnswer(5, "does not occur in wasps, bees, or ants",
				false,
				"No. It does.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335976;


		
		

		
			
			p.question = "Which of the following animals are most closely related to spiders? (<script type=\"text/javascript\">ebook(\'3304\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "scorpions",
				true,
				"Correct. Scorpions are arachnids, a class that also includes spiders.");
			
				p.addAnswer(2, "grasshoppers",
				false,
				"No. Spiders are not insects.");
			
				p.addAnswer(3, "pill bugs",
				false,
				"No. Spiders are not in the class Malacostraca.");
			
				p.addAnswer(4, "mosquitoes",
				false,
				"No. Spiders are not insects.");
			
				p.addAnswer(5, "millipedes",
				false,
				"No. Spiders are not in the class Diplopoda.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335977;


		
		

		
			
			p.question = "The water vascular system of a sea star functions in _____. (<script type=\"text/javascript\">ebook(\'3305\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "movement of the tube feet",
				true,
				"Correct. The water vascular system functions to power the tube feet.");
			
				p.addAnswer(2, "digestion",
				false,
				"No. Sea stars have a stomach and digestive glands.");
			
				p.addAnswer(3, "pumping water for swimming movements",
				false,
				"No. Sea stars walk.");
			
				p.addAnswer(4, "vision",
				false,
				"No. Photoreceptors, if they occur, are usually present at the tips of the rays.");
			
				p.addAnswer(5, "keeping all parts of the body moist at low tide",
				false,
				"No. This is not a function of the water vascular system");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335978;


		
		

		
			
			p.question = "Which one of the following statements about the phylum Echinodermata is true? (<script type=\"text/javascript\">ebook(\'3305\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Many species possess an internal calcareous skeleton and spiny dermal projections.",
				false,
				"No. Many species do possess an internal calcareous skeleton, but this is not the only true statement.");
			
				p.addAnswer(2, "Larval forms show evidence of bilateral symmetry, which is mostly lost in the adult form.",
				false,
				"No. Larval echinoderms do show evidence of bilateral symmetry, but this is not the only true statement.");
			
				p.addAnswer(3, "One of the classes in this phylum is Asteroidea&#151;the sea stars.",
				false,
				"No. This is the class to which sea stars belong, but this is not the only true statement.");
			
				p.addAnswer(4, "All possess a water vascular system, which permits movements via tube feet.",
				false,
				"No. All echinoderms do possess a water vascular system, but this is not the only true statement.");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335979;


		
		

		
			
			p.question = "What is one visible feature that makes it easy to identify sea cucumbers as echinoderms? (<script type=\"text/javascript\">ebook(\'3305\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "They have spines.",
				false,
				"No. Unlike many other members of the phylum Echinodermata, sea cucumbers do not have spines.");
			
				p.addAnswer(2, "The endoskeleton is not reduced.",
				false,
				"No. The endoskeleton in sea cucumbers is very reduced compared to other echinoderms.");
			
				p.addAnswer(3, "They have five rows of tube feet.",
				true,
				"Correct. This is a visible feature that makes it clear that sea cucumbers are echinoderms.");
			
				p.addAnswer(4, "They are elongated in the oral-aboral axis.",
				false,
				"No. This structure gives them the elongated appearance from which they get their common name. The feature makes them look very different from other echinoderms.");
			
				p.addAnswer(5, "They move by serpentine lashing of their arms.",
				false,
				"No. This is a characteristic of brittle stars.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

