

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "GraphIt! Quiz > GraphIt! Quiz > Global Fresh Water Resources";
	ak.quiz_loc_with_commas = "GraphIt! Quiz, GraphIt! Quiz, Global Fresh Water Resources";
	ak.quiz_title = "Global Fresh Water Resources";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 7;
	ak.non_essay_total = 7;
	ak.scored_item_total = 7;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337493;


		
		

		
			
			p.question = "Which continent has more than 12,000 cubic kilometers of water available per year?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Europe",
				false,
				"");
			
				p.addAnswer(2, "Africa",
				false,
				"");
			
				p.addAnswer(3, "South America",
				false,
				"");
			
				p.addAnswer(4, "Asia",
				true,
				"");
			
				p.addAnswer(5, "Australia",
				false,
				"");
			
				p.addAnswer(6, "North America",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337494;


		
		

		
			
			p.question = "Africa is much larger than Europe. Why doesn\'t it have much more fresh water?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The equator crosses it.",
				false,
				"");
			
				p.addAnswer(2, "Much of its land area is covered with desert.",
				true,
				"");
			
				p.addAnswer(3, "War and conflict have restricted access to water.",
				false,
				"");
			
				p.addAnswer(4, "Its population is greater.",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337495;


		
		

		
			
			p.question = "Which continent has the highest ratio of available fresh water to population size?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Australia",
				true,
				"");
			
				p.addAnswer(2, "North America",
				false,
				"");
			
				p.addAnswer(3, "Africa",
				false,
				"");
			
				p.addAnswer(4, "South America",
				false,
				"");
			
				p.addAnswer(5, "Asia",
				false,
				"");
			
				p.addAnswer(6, "Europe",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337496;


		
		

		
			
			p.question = "Which continents currently have sufficient water to meet the needs of their populations?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Europe, Africa, and Asia",
				false,
				"");
			
				p.addAnswer(2, "North America, South America, Africa, and Australia",
				true,
				"");
			
				p.addAnswer(3, "North America, Asia, and South America",
				false,
				"");
			
				p.addAnswer(4, "Europe, Africa, and Australia",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- truefalse ------------
		//
		
			p = new Problem("truefalse");
		
		p.id = 337497;


		
		

		
			
			p.question = "Fresh water available per capita should remain stable over the next 50 years.";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			
				
				p.addAnswer(1, "True", false, "");
				
			
				
				p.addAnswer(2, "False", true, "");
				
				

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- truefalse ------------
		//
		
			p = new Problem("truefalse");
		
		p.id = 337498;


		
		

		
			
			p.question = "Asia has abundant water resources, but its high population size is causing water shortages.";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			
				
				p.addAnswer(1, "True", true, "");
				
			
				
				p.addAnswer(2, "False", false, "");
				
				

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- truefalse ------------
		//
		
			p = new Problem("truefalse");
		
		p.id = 337499;


		
		

		
			
			p.question = "If some of Australia\'s water resources could be diverted to Asia, it would eliminate Asia\'s water shortages.";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			
				
				p.addAnswer(1, "True", false, "");
				
			
				
				p.addAnswer(2, "False", true, "");
				
				

		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

