

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "36: Transport in Vascular Plants > Practice Test";
	ak.quiz_loc_with_commas = "36: Transport in Vascular Plants, Practice Test";
	ak.quiz_title = "Practice Test";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 35;
	ak.non_essay_total = 35;
	ak.scored_item_total = 35;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336107;


		
		

		
			
			p.question = "What type of phyllotaxy allows leaves to get maximum sunlight with minimum shading of lower leaves? (<script type=\"text/javascript\">ebook(\'3601\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "opposite phyllotaxy",
				false,
				"No. Opposite phyllotaxy appears to be advantageous in areas of high sunlight where some shading of lower leaves is helpful.");
			
				p.addAnswer(2, "spiral (or alternate) phyllotaxy with an angle of 97.5 degrees between each leaf",
				false,
				"No. Spiral phyllotaxy is correct, but the angle is incorrect.");
			
				p.addAnswer(3, "whorled phyllotaxy",
				false,
				"No. Spiral phyllotaxy with a particular angle is most advantageous.");
			
				p.addAnswer(4, "spiral (or alternate) phyllotaxy with an angle of 137.5 degrees between each leaf",
				true,
				"Correct. A spiral arrangement with this angle between leaves provides maximum sunlight with minimum shading, according to mathematical analyses.");
			
				p.addAnswer(5, "spiral (or alternate) phyllotaxy with an angle of 167.5 degrees between each leaf",
				false,
				"No. Spiral phyllotaxy is correct, but the angle is incorrect.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336108;


		
		

		
			
			p.question = "What type of root architecture allows plants to grow taller? (<script type=\"text/javascript\">ebook(\'3601\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "rhizoids",
				false,
				"No.  Rhizoids are very weak anchoring structures found in non-vascular plants.");
			
				p.addAnswer(2, "taproots",
				true,
				"Correct. Taproots with lateral roots provide the most secure anchoring system and allow plants to grow tall.");
			
				p.addAnswer(3, "fibrous roots",
				false,
				"No. Fibrous roots spread out near the surface and are not as effective at anchoring a tall plant.");
			
				p.addAnswer(4, "root hairs",
				false,
				"No. Root hairs greatly increase the root\'s surface area for absorption, but they are not useful in anchoring the plant.");
			
				p.addAnswer(5, "mycorrhizae",
				false,
				"No. Mycorrhizae are mutualistic associations between plant roots and fungi. They are very important in absorption but not effective in anchoring the plant.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336109;


		
		

		
			
			p.question = "The purpose of the xylem is to _______. (<script type=\"text/javascript\">ebook(\'3601\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "transport water and minerals from shoots to roots",
				false,
				"No. The direction of transport in the xylem is just the opposite.");
			
				p.addAnswer(2, "transport sugar from sources to sinks",
				false,
				"No. The phloem transports sugar.");
			
				p.addAnswer(3, "transport water and minerals from roots to shoots",
				true,
				"Correct. Xylem transports water and minerals from roots to shoots via cohesion bulk transport driven by transpiration.");
			
				p.addAnswer(4, "transport sugar from sinks to sources.",
				false,
				"No. The phloem transports sugar.");
			
				p.addAnswer(5, "both a and c",
				false,
				"No. Xylem transport is unidirectional.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336110;


		
		

		
			
			p.question = "The greatest increase in surface area for absorption in the root is due to _____. (<script type=\"text/javascript\">ebook(\'3601\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "branch roots",
				false,
				"No. Branch roots do increase surface area, but not as much as either root hairs or mycorrhizae.");
			
				p.addAnswer(2, "root hairs",
				false,
				"No. Root hairs do increase surface area, but not as much as mycorrhizae.");
			
				p.addAnswer(3, "mycorrhizae",
				true,
				"Correct. Mycorrhizae reach a far greater volume of soil than the root alone could penetrate.");
			
				p.addAnswer(4, "root nodules",
				false,
				"No. Root nodules are involved with nitrogen fixation.");
			
				p.addAnswer(5, "formation of a periderm",
				false,
				"No. Periderm forms in older parts of the root not involved with absorption.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336111;


		
		

		
			
			p.question = "The proton pump _____. (<script type=\"text/javascript\">ebook(\'3602\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "pumps H<sup>+</sup> out of the cell",
				true,
				"Correct. By pumping H<sup>+</sup> out of the cell, the proton pump creates a membrane potential.");
			
				p.addAnswer(2, "pumps H<sup>+</sup> into the cell",
				false,
				"No. The pump moves H<sup>+</sup> out of the cell.");
			
				p.addAnswer(3, "generates energy by producing ATP",
				false,
				"No. The proton pump uses energy from ATP.");
			
				p.addAnswer(4, "provides energy for active transport",
				false,
				"No. The pump requires energy.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336112;


		
		

		
			
			p.question = "Which of the following processes is aided by the membrane potential established by the proton pump? (<script type=\"text/javascript\">ebook(\'3602\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "uptake of cations such as K<sup>+</sup>",
				false,
				"No. Cation uptake is facilitated, but this is not the best answer.");
			
				p.addAnswer(2, "cotransport of anions",
				false,
				"No. Cotransport of anions is facilitated, but this is not the best answer.");
			
				p.addAnswer(3, "cotransport of neutral solutes",
				false,
				"No. Cotransport of neutral solutes is facilitated, but this is not the only correct answer.");
			
				p.addAnswer(4, "both b and c",
				false,
				"No. This is a correct answer, but there is a better response.");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct. Membrane potential is necessary for all of the above.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336113;


		
		

		
			
			p.question = "A plant cell placed in a solution with a higher water potential will _____. (<script type=\"text/javascript\">ebook(\'3602\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "lose water and crenate",
				false,
				"No. Water moves from higher to lower water potential.");
			
				p.addAnswer(2, "lose water and become turgid",
				false,
				"No. Turgor pressure is the result of water gain.");
			
				p.addAnswer(3, "gain water and become turgid",
				true,
				"Correct. Because water moves from a region of higher water potential to a region of lower water potential, a cell in such a solution will gain water and become turgid.");
			
				p.addAnswer(4, "lose water and plasmolyze",
				false,
				"No. Water moves from a region of higher water potential to a region of lower water potential.");
			
				p.addAnswer(5, "gain water and plasmolyze",
				false,
				"No. Turgor pressure is the result of water gain by a plant cell.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336114;


		
		

		
			
			p.question = "The water potential of a cell is defined by the equation &Psi; = &Psi;<sub>S</sub> + &Psi;<sub>P</sub>. Which of the following statements is true? (<script type=\"text/javascript\">ebook(\'3602\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "&Psi;<sub>S</sub> may be either positive or negative.",
				false,
				"No. The maximum possible &Psi;<sub>S</sub> is that found in pure water and it is defined as 0. The &Psi;<sub>S</sub> of any solution is less than 0.");
			
				p.addAnswer(2, "&Psi;<sub>S</sub> is always greater than &Psi;<sub>P</sub>.",
				false,
				"No. &Psi;<sub>S</sub> must be less than 0; &Psi;<sub>P</sub> may be positive.");
			
				p.addAnswer(3, "&Psi;<sub>P</sub> may be either positive or negative.",
				true,
				"Correct. Pressure potential may be positive (push) or negative (tension or pull).");
			
				p.addAnswer(4, "&Psi;<sub>S</sub> is always positive.",
				false,
				"No. &Psi;<sub>S</sub> is always less than 0, and &Psi;<sub>P</sub> may be negative.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. &Psi;<sub>S</sub> is always less than 0, and &Psi;<sub>P</sub> may be positive or negative.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336115;


		
		

		
			
			p.question = "A cell has a pressure potential of 0 and a solute potential of -0.7 MPa. What is its water potential? (<script type=\"text/javascript\">ebook(\'3602\',\'quiz\')</script>)";
			p.incorrect_any_expl = "No. Water potential = pressure potential + solute potential.";
			p.incorrect_any_expl_flag = 1;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "-0.7 MPa",
				true,
				"Correct. Water potential = pressure potential + solute potential.");
			
				p.addAnswer(2, "0 MPa",
				false,
				"");
			
				p.addAnswer(3, "0.7 MPa",
				false,
				"");
			
				p.addAnswer(4, "> -0.7 MPa",
				false,
				"");
			
				p.addAnswer(5, "< -0.7 MPa",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336116;


		
		

		
			
			p.question = "If pure water is separated from a 0.1 <i>M</i> solution in an open, U-shaped tube by a membrane impermeable to the solute, what will happen? (<script type=\"text/javascript\">ebook(\'3602\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Water will move to the 0.1 <i>M</i> solution side until the concentrations are equal on both sides of the membrane.",
				false,
				"No. The solution side can never have the same concentration of water as pure water.");
			
				p.addAnswer(2, "Solute in the solution will diffuse to the pure water side until equilibrium is reached.",
				false,
				"No. The membrane is impermeable to the solute.");
			
				p.addAnswer(3, "Water will diffuse toward the solution side until a piston pushes it back at an equal rate.",
				false,
				"No. This is an open system. There is no piston in the system.");
			
				p.addAnswer(4, "Water will diffuse to the solution side until the pressure potential due to a higher water column is equal, but opposite in sign, to the osmotic potential.",
				true,
				"Correct. At this point, the water potential will be 0 and the system will be at dynamic equilibrium.");
			
				p.addAnswer(5, "All the water will diffuse to the solution side.",
				false,
				"No. As water diffuses, pressure potential begins to build, which counteracts the osmotic potential.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336117;


		
		

		
			
			p.question = "Which of the following is true for a plant that is wilting? (<script type=\"text/javascript\">ebook(\'3602\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The pressure potential in the xylem will be more negative than in a turgid plant.",
				true,
				"Correct. Except when there is root pressure, the pressure potential in xylem is always negative. The greater the tension, the more negative the pressure.");
			
				p.addAnswer(2, "The pressure potential in guard cells will be high to keep them closed.",
				false,
				"No. High pressure potential causes guard cells to open.");
			
				p.addAnswer(3, "The pressure potential in endodermal cells will be positive.",
				false,
				"No. All cells in a wilted plant will have negative pressure potentials.");
			
				p.addAnswer(4, "Root hair cells will have a positive pressure potential.",
				false,
				"No. All cells in a wilted plant will have negative pressure potentials.");
			
				p.addAnswer(5, "Mesophyll cells will have a positive pressure potential.",
				false,
				"No. All cells in a wilted plant will have negative pressure potentials.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336118;


		
		

		
			
			p.question = "In a turgid cell _____. (<script type=\"text/javascript\">ebook(\'3602\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "&Psi;<sub>S</sub> is always positive",
				false,
				"No. Solute potential is always less than 0.");
			
				p.addAnswer(2, "&Psi;<sub>P</sub> is 0",
				false,
				"No. In a turgid cell, pressure potential must be positive.");
			
				p.addAnswer(3, "&Psi; = 0",
				true,
				"Correct. In a turgid cell, solute potential and pressure potential are equal and opposite values, so water potential is 0.");
			
				p.addAnswer(4, "&Psi;<sub>P</sub> < 0",
				false,
				"No. In a turgid cell, pressure potential must be positive.");
			
				p.addAnswer(5, "&Psi; = &Psi;<sub>S</sub>",
				false,
				"No. In a turgid cell, water potential = 0.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336119;


		
		

		
			
			p.question = "Water molecules cross a plasma membrane of a plant cell due to _____. (<script type=\"text/javascript\">ebook(\'3602\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "diffusion",
				false,
				"No. It is true that water molecules can cross a plasma membrane due to diffusion, but there must be other methods to account for the amount of water that can flow into a plant cell in a given time.");
			
				p.addAnswer(2, "transport proteins",
				false,
				"No. It is true that some transport proteins facilitate diffusion of water, but this is not the best answer.");
			
				p.addAnswer(3, "aquaporins",
				false,
				"No. Aquaporins are transport proteins that facilitate the diffusion of water, but this is not the best answer.");
			
				p.addAnswer(4, "Increases in cytoplasmic Ca<sup>2+</sup>",
				false,
				"No. Evidence is accumulating that the rate of water movement through transport proteins is regulated by phosphorylation of the aquaporin proteins induced by changes in second messengers such as Ca<sup>2+</sup> ions. But this is not the best answer.");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct. All of the above contribute to water molecules crossing the plasma membranes of plant cells.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336120;


		
		

		
			
			p.question = "The cytoplasmic continuum connecting neighboring cells is called the _____. (<script type=\"text/javascript\">ebook(\'3602\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "tonoplast",
				false,
				"No. The tonoplast regulates the flow of material between the vacuole and cytosol of the plant cell.");
			
				p.addAnswer(2, "apoplast",
				false,
				"No. The apoplast is the continuum of cell walls.");
			
				p.addAnswer(3, "aquaporin",
				false,
				"No. Aquaporin is a protein that facilitates osmosis.");
			
				p.addAnswer(4, "symplast",
				true,
				"Correct. The symplast is the cytoplasmic connection between adjacent plant cells.");
			
				p.addAnswer(5, "cell wall",
				false,
				"No. The cell wall is not part of the cytoplasm.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336121;


		
		

		
			
			p.question = "The continuum of cell walls connecting neighboring cells is defined as the _____. (<script type=\"text/javascript\">ebook(\'3602\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "tonoplast",
				false,
				"No. The tonoplast regulates the flow of material between the vacuole and cytosol of the plant cell.");
			
				p.addAnswer(2, "apoplast",
				true,
				"Correct. The apoplast is the continuum of cell walls.");
			
				p.addAnswer(3, "aquaporin",
				false,
				"No. Aquaporin is a protein that facilitates osmosis.");
			
				p.addAnswer(4, "symplast",
				false,
				"No. The symplast is the cytoplasmic connection between adjacent plant cells.");
			
				p.addAnswer(5, "plasmodesmata",
				false,
				"No. Plasmodesmata are cytoplasmic connections through adjacent plant cell walls.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336122;


		
		

		
			
			p.question = "Which of the cells below are involved with bulk flow? (<script type=\"text/javascript\">ebook(\'3602\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "tracheids, vessels, and sieve tubes",
				true,
				"Correct. Tracheids and vessels are xylem cells, and sieve tubes are phloem cells.");
			
				p.addAnswer(2, "tracheids, vessels, and guard cells",
				false,
				"No. Guard cells are not involved in bulk flow.");
			
				p.addAnswer(3, "tracheids, tonoplasts, and sieve tubes",
				false,
				"No. Tonoplasts are not involved with bulk flow.");
			
				p.addAnswer(4, "guard cells, vessels, and sieve tubes",
				false,
				"No. Guard cells are not involved in bulk flow.");
			
				p.addAnswer(5, "tracheids, vessels, and tonoplasts",
				false,
				"No. Tonoplasts are not involved with bulk flow.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336123;


		
		

		
			
			p.question = "The last thing all water and solute molecules pass through before they enter the vascular system of roots and move upward to the leaves is _____. (<script type=\"text/javascript\">ebook(\'3603\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a stoma",
				false,
				"No. Stomata are openings on the surfaces of leaves.");
			
				p.addAnswer(2, "a root hair cell",
				false,
				"No. Root hairs are extensions of epidermal cells that increase the surface area for absorption of nutrients.");
			
				p.addAnswer(3, "an endodermal cell",
				true,
				"Correct. The endodermis is the innermost layer of the root cortex and surrounds the vascular tissue.");
			
				p.addAnswer(4, "an epidermal cell",
				false,
				"No. Epidermal cells are found on surfaces and form the first barrier through which water and solutes pass on their way to vascular tissue.");
			
				p.addAnswer(5, "a tonoplast",
				false,
				"No. The tonoplast is the large central vacuole of a plant cell.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336124;


		
		

		
			
			p.question = "A botanist discovered a mutant plant that is unable to produce the material that forms the Casparian strip. This plant is _____. (<script type=\"text/javascript\">ebook(\'3603\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "unable to fix nitrogen",
				false,
				"No. Only certain prokaryotes are capable of nitrogen fixation.");
			
				p.addAnswer(2, "unable to transport water or solutes to the leaves",
				false,
				"No. The Casparian strip is a barrier to the flow of water and solutes.");
			
				p.addAnswer(3, "able to exert greater root pressure than normal plants",
				false,
				"No. Without the Casparian strip, water would be able to flow back out of the stele to the root cortex.");
			
				p.addAnswer(4, "unable to control the amounts of water and solutes it absorbs",
				true,
				"Correct. The Casparian strip blocks the flow of water and other solutes across the apoplast connecting the endodermis and vascular tissue.");
			
				p.addAnswer(5, "unable to lose water by transpiration",
				false,
				"No. The lack of a Casparian strip would not decrease the availability of water to a plant.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336125;


		
		

		
			
			p.question = "In a plant root, the one cell type in which water <b>cannot</b> move via the apoplast is the _____. (<script type=\"text/javascript\">ebook(\'3603\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "epidermis",
				false,
				"No. The epidermis, the outermost layer of a root, is permeable to water.");
			
				p.addAnswer(2, "endodermis",
				true,
				"Correct. Within the wall of each endodermal cell is the Casparian strip, a band of waxy material that blocks the passage of water and dissolved minerals.");
			
				p.addAnswer(3, "pericycle",
				false,
				"No. The pericycle gives rise to lateral roots.");
			
				p.addAnswer(4, "cortex",
				false,
				"No. The cortex is ground tissue.");
			
				p.addAnswer(5, "vascular tissues",
				false,
				"No. Vascular tissue transports fluids.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336126;


		
		

		
			
			p.question = "A friend of yours has a terrarium on her windowsill containing various houseplants. She wonders why the glass is often fogged with water droplets. What would you tell her is the cause of the droplets? (<script type=\"text/javascript\">ebook(\'3603\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "root pressure",
				false,
				"No. Root pressure is upward pressure generated by the accumulation of water in the stele.");
			
				p.addAnswer(2, "adhesion",
				false,
				"No. Adhesion is the sticking together of two substances.");
			
				p.addAnswer(3, "photosynthesis",
				false,
				"No. This is the process by which light energy is converted to chemical energy stored in the bonds of organic compounds.");
			
				p.addAnswer(4, "pressure flow",
				false,
				"No. Pressure flow can be responsible for the movement of water, but not for a change in the state of water.");
			
				p.addAnswer(5, "transpiration",
				true,
				"Correct. By definition, transpiration is the evaporation of water from a plant.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336127;


		
		

		
			
			p.question = "Root pressure is attributable to _____. (<script type=\"text/javascript\">ebook(\'3603\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "transpiration",
				false,
				"No. Transpiration, the evaporation of water from stomata, pulls fluid up the xylem.");
			
				p.addAnswer(2, "the accumulation of minerals in the vascular cylinder",
				true,
				"Correct. The accumulation lowers the water potential in the vascular cylinder. Water flows into the root cortex, generating root pressure.");
			
				p.addAnswer(3, "the high water potential of the vascular cylinder relative to the root cortex",
				false,
				"No. Due to an accumulation of minerals, the vascular cylinder has a lower water potential than the root cortex.");
			
				p.addAnswer(4, "guttation",
				false,
				"No. Root pressure causes guttation.");
			
				p.addAnswer(5, "the pumping of minerals out of the vascular cylinder",
				false,
				"No. Pumping minerals out of the vascular cylinder would result in the movement of water from the vascular cylinder to the root cortex.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336128;


		
		

		
			
			p.question = "Which of the following conditions will result in the fastest transport through the xylem in a tree, assuming adequate water supply in the roots? (<script type=\"text/javascript\">ebook(\'3603\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "negative pressure potential in the leaf mesophyll",
				true,
				"Correct. The more negative the pressure potential, the greater the tension that will be created in the xylem.");
			
				p.addAnswer(2, "positive pressure potential in the xylem",
				false,
				"No. Positive pressure in the xylem, root pressure, is only effective over short distances.");
			
				p.addAnswer(3, "positive pressure potential in the mesophyll",
				false,
				"No. Positive pressure in the mesophyll can only occur if there is no transpiration, the driving force for water transport in the xylem.");
			
				p.addAnswer(4, "negative pressure potential in the guard cells",
				false,
				"No. Negative pressure in living plant cells results in plasmolysis. Guard cells open the stoma when under positive pressure.");
			
				p.addAnswer(5, "phloem transport being in the opposite direction from the xylem transport",
				false,
				"No. Transport in the xylem is independent of phloem transport.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336129;


		
		

		
			
			p.question = "What keeps the force of gravity from overcoming transpirational pull? (<script type=\"text/javascript\">ebook(\'3603\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "upward pressure from the roots",
				false,
				"No. Though root pressure plays a role, it is effective over only a few meters. Even in small plants, transpirational pull plays a greater role.");
			
				p.addAnswer(2, "high water pressure in the leaves",
				false,
				"No. The water pressure in leaves is less than atmospheric pressure.");
			
				p.addAnswer(3, "the Casparian strip blocking water molecules from moving out",
				false,
				"No. Though this has an effect on root pressure, transpirational pull plays a greater role.");
			
				p.addAnswer(4, "movement of water toward a sugar sink",
				false,
				"No. This type of movement concerns the flow of phloem sap and not the flow of water in xylem.");
			
				p.addAnswer(5, "cohesion and adhesion of water molecules",
				true,
				"Correct. Cohesion, the attraction of water molecules to each other, causes the water molecules leaving the leaf to tug on adjacent water molecules. Adhesion, the attraction of water molecules to hydrophilic cell walls, plays a role in maintaining the water pressure below atmospheric pressure.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336130;


		
		

		
			
			p.question = "Normally when an aphid feeds by puncturing plant tissues, it does not have to suck the sap out. If an aphid, however, inserted its feeding tube in the wrong place, the fluid in the aphid\'s guts could be sucked out through the feeding tube. What could explain this phenomenon? (<script type=\"text/javascript\">ebook(\'3603\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The aphid pierced the Casparian strip.",
				false,
				"No. Sap does not flow within or across the Casparian strip.");
			
				p.addAnswer(2, "The aphid punctured a root nodule.",
				false,
				"No. Root nodules consist of plant cells that contain nitrogen-fixing bacteria.");
			
				p.addAnswer(3, "The aphid punctured xylem cells.",
				true,
				"Correct. The upward, transpirational pull occurring in the cells will suck the fluid out of the gut of the aphid.");
			
				p.addAnswer(4, "The aphid punctured a sieve tube cell.",
				false,
				"No. The hydrostatic pressure within the phloem would force the fluid into the gut of the aphid.");
			
				p.addAnswer(5, "The aphid punctured a stoma.",
				false,
				"No. A stoma is an opening through which a leaf exchanges gases.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336131;


		
		

		
			
			p.question = "During winter, tree sap can sometimes freeze and <i>cavitation</i> (the formation of an air pocket) may occur. Which one of the following mechanisms of sap transport would you expect to be most immediately affected by cavitation? (<script type=\"text/javascript\">ebook(\'3603\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "symplast function",
				false,
				"No. Symplasts are involved with root transport, not sap flow.");
			
				p.addAnswer(2, "pressure flow (mass flow)",
				false,
				"No. Cavitation affects tension, not positive pressure.");
			
				p.addAnswer(3, "cohesion transpiration",
				true,
				"Correct. The cohesion of water due to hydrogen bonding makes it possible to pull a column of sap from above without separating the water, but cavitation breaks the chain.");
			
				p.addAnswer(4, "root pressure",
				false,
				"No. Root pressure would not be affected.");
			
				p.addAnswer(5, "active transport",
				false,
				"No. Active transport is a cellular process.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336132;


		
		

		
			
			p.question = "What is the main source of energy that moves water upward in the trunk of a tree? (<script type=\"text/javascript\">ebook(\'3603\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "contraction of xylem cells",
				false,
				"No. Xylem cells contract when the fluid within is under tension. It is an effect, not a cause.");
			
				p.addAnswer(2, "evaporation of water by the sun",
				true,
				"Correct. As water evaporates through the stomata, more water is drawn up by transpirational pull.");
			
				p.addAnswer(3, "pressure exerted by root cells",
				false,
				"No. Transpiration, not root pressure, is the major force moving xylem sap upward.");
			
				p.addAnswer(4, "breakdown and release of energy of sugar molecules",
				false,
				"No. Transpiration does not require the plant to expend energy.");
			
				p.addAnswer(5, "osmotic changes caused by alterations in salt content",
				false,
				"No. The transport of water is dependent on relative water potentials, as well as the cohesion and adhesion of water.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336133;


		
		

		
			
			p.question = "The rate of transpiration is expected to be greatest on a _____ day. (<script type=\"text/javascript\">ebook(\'3603\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "cool and moist",
				false,
				"No. Such conditions do not promote evaporation.");
			
				p.addAnswer(2, "warm and moist",
				false,
				"No. Warmth promotes transpiration, but moisture does not.");
			
				p.addAnswer(3, "cool and dry",
				false,
				"No. Dryness promotes transpiration, but cool air does not.");
			
				p.addAnswer(4, "warm and dry",
				true,
				"Correct. The rate of transpiration will be greatest on a day that is sunny, warm, dry, and windy because those are the environmental factors that increase the evaporation of water.");
			
				p.addAnswer(5, "windy and cool",
				false,
				"No. Wind promotes transpiration, but cool air does not.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336134;


		
		

		
			
			p.question = "What contributes directly to the turgor pressure that opens and closes stomata? (<script type=\"text/javascript\">ebook(\'3604\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "respiration",
				false,
				"No. Respiration is a cellular process for producing energy by breaking down organic compounds.");
			
				p.addAnswer(2, "transpiration",
				false,
				"No. This is the evaporation of water from the surface of a leaf.");
			
				p.addAnswer(3, "guttation",
				false,
				"No. This is the release of water droplets from leaves.");
			
				p.addAnswer(4, "potassium accumulation in guard cells",
				true,
				"Correct. Stomata open when guard cells actively accumulate K<sup>+</sup> from neighboring epidermal cells.");
			
				p.addAnswer(5, "plasmolysis",
				false,
				"No. Plasmolysis occurs when a plant cell loses water.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336135;


		
		

		
			
			p.question = "Stomata open during the day in response to _____. (<script type=\"text/javascript\">ebook(\'3604\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "blue light triggering the efflux of K<sup>+</sup> from guard cells",
				false,
				"No. An efflux of K<sup>+</sup> would lead to a loss of water from guard cells and the closing of stomata.");
			
				p.addAnswer(2, "increased temperatures",
				false,
				"No. Stomatal closure can be the result of excessively high temperatures.");
			
				p.addAnswer(3, "increased CO<sub>2</sub> levels",
				false,
				"No. It is decreased CO<sub>2</sub> levels that cause stomata to open.");
			
				p.addAnswer(4, "blue light triggering the uptake of K<sup>+</sup> by guard cells",
				true,
				"Correct. The uptake of K<sup>+</sup> makes guard cells turgid, causing the stomata between the cells to open.");
			
				p.addAnswer(5, "the production of abscisic acid",
				false,
				"No. Abscisic acid, produced in response to water loss, triggers the closing of stomata.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336136;


		
		

		
			
			p.question = "Which of the following describes how some plants are adapted to arid environments? (<script type=\"text/javascript\">ebook(\'3604\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "They can liberate carbon dioxide stored in intermediate molecules during the night and fix it during the day even when stomata are closed.",
				true,
				"Correct. Mesophyll cells in a CAM plant have enzymes that can incorporate CO<sub>2</sub> into organic acids during the night. During the daytime when the stomata are closed, the organic acids are broken down to release CO<sub>2</sub>, and sugars are synthesized by the conventional photosynthetic pathway.");
			
				p.addAnswer(2, "They lose more water to transpiration than C<sub>3</sub> plants.",
				false,
				"No. CAM plants are more conservative of water than are C<sub>3</sub> pants.");
			
				p.addAnswer(3, "They have evolved alternatives to the Calvin cycle.",
				false,
				"No. The initial steps of carbon fixation and the Calvin cycle occur at different times.");
			
				p.addAnswer(4, "They can leave their stomata open even on very hot, dry days.",
				false,
				"No. CAM plants keep their stomata closed during the day.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336137;


		
		

		
			
			p.question = "In an apple tree that is producing sugars, sugar might flow from _____ to _____. (<script type=\"text/javascript\">ebook(\'3605\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a developing apple; a mature leaf",
				false,
				"No. An apple stores sugar and a leaf produces sugar.");
			
				p.addAnswer(2, "the trunk; a leaf",
				false,
				"No. The leaf is the sugar source.");
			
				p.addAnswer(3, "a growing root; a growing shoot tip",
				false,
				"No. A growing root does not function as a sugar source.");
			
				p.addAnswer(4, "a leaf; a developing apple",
				true,
				"Correct. A leaf is a sugar source, and a developing fruit is a sugar sink.");
			
				p.addAnswer(5, "a growing shoot tip; the trunk",
				false,
				"No. Neither of these structures functions as a sugar source.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336138;


		
		

		
			
			p.question = "Companion cells that are specialized for the transport of sugar between apoplast and symplast are _____ cells. (<script type=\"text/javascript\">ebook(\'3605\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "epidermal",
				false,
				"No. Epidermal cells are not a component of phloem.");
			
				p.addAnswer(2, "guard",
				false,
				"No. Guard cells regulate the opening of stomata.");
			
				p.addAnswer(3, "mycorrhizae",
				false,
				"No. Mycorrhizae are symbiotic associations of roots and fungi.");
			
				p.addAnswer(4, "aquaporin",
				false,
				"No. Aquaporin is a protein that facilitates osmosis.");
			
				p.addAnswer(5, "transfer",
				true,
				"Correct. Transfer cells have an increased surface area that facilitates the transport of solutes.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336139;


		
		

		
			
			p.question = "When referring to phloem transport, the \"sink\" in roots is created by _____. (<script type=\"text/javascript\">ebook(\'3605\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the active transport of mineral ions into xylem cells",
				false,
				"No. Consider what phloem transports.");
			
				p.addAnswer(2, "the osmosis of water into xylem cells",
				false,
				"No. Phloem transport is not related to xylem transport, and osmosis cannot occur in xylem because xylem cells have no cell membranes.");
			
				p.addAnswer(3, "the absorption of water from the soil through epidermal cells",
				false,
				"No. Phloem transport is not related to absorption.");
			
				p.addAnswer(4, "the active transport of sugars from phloem to cortex cells",
				true,
				"Correct. A sugar sink is an organ that consumes or stores sugar, such as a root.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. Only one of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336140;


		
		

		
			
			p.question = "When sugar is transported in plants, _____. (<script type=\"text/javascript\">ebook(\'3606\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "sugar always moves upwards from roots to leaves",
				false,
				"No. Sugar is transported from sources to sinks, and the nature of a particular part of a plant may change throughout the plant\'s development.");
			
				p.addAnswer(2, "leaves are always sugar sources and roots are always sugar sinks",
				false,
				"No. Young leaves that are growing rapidly may be sugar sinks, and roots may provide sugar that has been stored.");
			
				p.addAnswer(3, "leaves are always sugar sinks and roots are always sugar sources",
				false,
				"No. Especially during the summer when the leaves are mature, they act as sugar sources that may send sugar to roots for storage.");
			
				p.addAnswer(4, "leaves may be sinks or sources, but roots are always sinks",
				false,
				"No. In the spring when leaves are growing rapidly, sugar that was stored in roots may be sent to the leaves to power their growth.");
			
				p.addAnswer(5, "none of the above",
				true,
				"Correct. During different seasons or different phases of a plant\'s development, roots and leaves may act as both sources and sinks.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336141;


		
		

		
			
			p.question = "In order to be transported throughout a plant, viruses exploit _____. (<script type=\"text/javascript\">ebook(\'3606\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the ability of plasmodesmata to dilate to allow large particles to move between cells",
				true,
				"Correct. Although plasmodesmata are generally too small for viruses to pass through, they can dilate to allow larger molecules such as proteins and RNA to pass through. Viruses exploit this ability by mimicking cellular signals that cause the plasmodesmata to dilate.");
			
				p.addAnswer(2, "the xylem\'s ability to transport minerals from roots to shoots",
				false,
				"No. Viruses use the phloem to spread throughout the plant.");
			
				p.addAnswer(3, "the apoplast",
				false,
				"No. Viruses use the phloem to spread throughout the plant.");
			
				p.addAnswer(4, "the ability of phloem to transmit electrical signals",
				false,
				"No. Viruses do not exploit pathways that transmit electrical signals.");
			
				p.addAnswer(5, "the Casparian strip",
				false,
				"No. The Casparian strip would tend to keep viruses from entering the plant.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

