

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "24: The Origin of Species > Activities Quiz";
	ak.quiz_loc_with_commas = "24: The Origin of Species, Activities Quiz";
	ak.quiz_title = "Activities Quiz";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 5;
	ak.non_essay_total = 5;
	ak.scored_item_total = 5;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335491;


		
		

		
			
			p.question = "Feathers either play a role, or may have played a role, in _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?24&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Overview of Macroevolution</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "courtship",
				false,
				"This is a possible function of feathers.");
			
				p.addAnswer(2, "gliding",
				false,
				"This is a possible function of feathers.");
			
				p.addAnswer(3, "flight",
				false,
				"This is a possible function of feathers.");
			
				p.addAnswer(4, "extended hops",
				false,
				"This is a possible function of feathers.");
			
				p.addAnswer(5, "all of these",
				true,
				"All of these are, or may have been, functions of feathers.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335492;


		
		

		
			
			p.question = "_____ is rapid speciation under conditions in which there is little competition. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?24&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Overview of Macroevolution</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Microevolution",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(2, "Paedomorphosis",
				false,
				"Paedomorphosis is the retention of juvenile characteristics in the adult.");
			
				p.addAnswer(3, "Gene flow",
				false,
				"Gene flow is the movement of alleles into, or out of, a population.");
			
				p.addAnswer(4, "Genetic drift",
				false,
				"While genetic drift can play a role in rapid speciation, it is not the correct response to this question.");
			
				p.addAnswer(5, "Adaptive radiation",
				true,
				"Adaptive radiation is rapid speciation under conditions in which there is little competition.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335493;


		
		

		
			
			p.question = "Mass extinctions create conditions that promote _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?24&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Overview of Macroevolution</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "microevolution",
				false,
				"There is a better response to the question.");
			
				p.addAnswer(2, "paedomorphosis",
				false,
				"Paedomorphosis is the retention of juvenile characteristics in the adult.");
			
				p.addAnswer(3, "gene flow",
				false,
				"There is a better response to the question.");
			
				p.addAnswer(4, "genetic drift",
				false,
				"There is a better response to the question.");
			
				p.addAnswer(5, "adaptive radiation",
				true,
				"Mass extinctions reduce competition and allow for periods of rapid speciation.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335494;


		
		

		
			
			p.question = "The appearance of an evolutionary novelty promotes _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?24&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Overview of Macroevolution</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "gene flow",
				false,
				"Possibly, but there is a better response to the question.");
			
				p.addAnswer(2, "mutation",
				false,
				"Mutations are involved in the appearance of an evolutionary novelty.");
			
				p.addAnswer(3, "mass extinction",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(4, "paedomorphosis",
				false,
				"Paedomorphosis is the retention of juvenile characteristics in the adult.");
			
				p.addAnswer(5, "adaptive radiation",
				true,
				"The appearance of an evolutionary novelty may allow for the exploitation of previously unexploited niches.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335495;


		
		

		
			
			p.question = "The different finch species found on the Gal&aacute;pagos Islands probably arose as a result of _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?24&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Overview of Macroevolution</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "artificial selection",
				false,
				"Natural selection would be a correct response.");
			
				p.addAnswer(2, "adaptive radiation",
				true,
				"The finches that initially immigrated to the Gal&aacute;pagos Islands experienced little competition, the result of which was the promotion of speciation.");
			
				p.addAnswer(3, "mass extinction",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(4, "gene flow",
				false,
				"The finches that initially arrived on the Gal&aacute;pagos Islands were isolated from other finch populations.");
			
				p.addAnswer(5, "paedomorphosis",
				false,
				"Paedomorphosis is the retention of juvenile characteristics in the adult.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

