

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "22: Descent with Modification: A Darwinian View of Life > Activities Quiz";
	ak.quiz_loc_with_commas = "22: Descent with Modification: A Darwinian View of Life, Activities Quiz";
	ak.quiz_title = "Activities Quiz";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 15;
	ak.non_essay_total = 15;
	ak.scored_item_total = 15;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335387;


		
		

		
			
			p.question = "The Gal&aacute;pagos Islands are cooled by the _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?22&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Darwin and the Gal&#225;pagos Islands</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Equatorial Countercurrent",
				false,
				"The Equatorial Countercurrent is a warm-water current.");
			
				p.addAnswer(2, "Humboldt Current",
				true,
				"The Humboldt carries cool water northward from Antarctica.");
			
				p.addAnswer(3, "Monsoon Drift",
				false,
				"The Monsoon Drift is a warm-water Asian current.");
			
				p.addAnswer(4, "Gulf Stream",
				false,
				"The Gulf Stream current carries warm water northward along the coast of the southeastern United States.");
			
				p.addAnswer(5, "Kuroshio Current",
				false,
				"The Kuroshio Current is an Asian warm-water current.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335388;


		
		

		
			
			p.question = "How many finch species did Darwin send to the British Museum? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?22&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Darwin and the Gal&#225;pagos Islands</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "13",
				true,
				"Thirteen distinct species of finch were identified.");
			
				p.addAnswer(2, "15",
				false,
				"Fewer.");
			
				p.addAnswer(3, "17",
				false,
				"Fewer.");
			
				p.addAnswer(4, "21",
				false,
				"Fewer.");
			
				p.addAnswer(5, "30",
				false,
				"Fewer.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335389;


		
		

		
			
			p.question = "Darwin\'s thinking while on the <i>Beagle</i> was greatly influenced by his reading of a book written by _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?22&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Voyage of the <i>Beagle</i>: Darwin\'s Trip Around the World</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Bishop Ussher",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(2, "Lyell",
				true,
				"Darwin was greatly influenced by Lyell\'s <i>Principles of Geology</i>.");
			
				p.addAnswer(3, "Chaucer",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(4, "Wallace",
				false,
				"Wallace independently formulated a theory of evolution by natural selection.");
			
				p.addAnswer(5, "Shakespeare",
				false,
				"No, that is incorrect.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335390;


		
		

		
			
			p.question = "According to this climatograph, London experiences more precipitation during _____ than during any other month. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?22&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Voyage of the <i>Beagle</i>: Darwin\'s Trip Around the World</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/2204q.jpg\" ALT=\"Question #4\" BORDER=\"1\" >";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "January",
				false,
				"This is not the month during which London receives the most precipitation.");
			
				p.addAnswer(2, "February",
				false,
				"February is one of the months that receive the least precipitation.");
			
				p.addAnswer(3, "October",
				true,
				"Precipitation is greatest in October.");
			
				p.addAnswer(4, "June",
				false,
				"While one of the wetter months, this is not the month during which there is the greatest amount of precipitation.");
			
				p.addAnswer(5, "July",
				false,
				"While one of the wetter months, this is not the month during which there is the greatest amount of precipitation.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335391;


		
		

		
			
			p.question = "Which of these is a consequence of uniformitarianism? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?22&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Voyage of the <i>Beagle</i>: Darwin\'s Trip Around the World</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Earth is round, not flat.",
				false,
				"This is not a consequence of uniformitarianism.");
			
				p.addAnswer(2, "Populations evolve.",
				false,
				"This is not a consequence of uniformitarianism.");
			
				p.addAnswer(3, "Populations reproduce faster than their food supply.",
				false,
				"This is not a consequence of uniformitarianism.");
			
				p.addAnswer(4, "A Creator made Earth.",
				false,
				"This is not a consequence of uniformitarianism.");
			
				p.addAnswer(5, "Earth is very old.",
				true,
				"Uniformitarianism holds that geologic processes occur today in much the same way as they did in the past.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335392;


		
		

		
			
			p.question = "The Argentinean pampas are a type of _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?22&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Voyage of the <i>Beagle</i>: Darwin\'s Trip Around the World</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "chaparral",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(2, "grassland",
				true,
				"The pampas are treeless plains.");
			
				p.addAnswer(3, "temperate deciduous forest",
				false,
				"The pampas lack trees.");
			
				p.addAnswer(4, "tropical forest",
				false,
				"The pampas lack trees.");
			
				p.addAnswer(5, "desert",
				false,
				"No, that is incorrect.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335393;


		
		

		
			
			p.question = "At the fossil site at Punta Alta, Darwin found evidence _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?22&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Voyage of the <i>Beagle</i>: Darwin\'s Trip Around the World</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "that the pampas could support large mammals",
				false,
				"Darwin questioned whether the pampas could support large mammals.");
			
				p.addAnswer(2, "that extinction does not happen",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(3, "of extinction",
				true,
				"At Punta Alta, Darwin found the bones of types of mammals that no longer lived.");
			
				p.addAnswer(4, "that Brazilian flatworms were a type of slug",
				false,
				"Brazilian flatworms are not mollusks.");
			
				p.addAnswer(5, "of divine creation",
				false,
				"No, that is incorrect.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335394;


		
		

		
			
			p.question = "Patagonia is a _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?22&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Voyage of the <i>Beagle</i>: Darwin\'s Trip Around the World</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "grassland",
				false,
				"The pampas are grasslands.");
			
				p.addAnswer(2, "savanna",
				false,
				"Savannas are characterized by grasses and scattered trees.");
			
				p.addAnswer(3, "tropical forest",
				false,
				"Patagonia is not noted for an abundance of trees.");
			
				p.addAnswer(4, "chaparral",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(5, "desert",
				true,
				"Patagonia is a desert.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335395;


		
		

		
			
			p.question = "His experiences with Fuegians and slavery convinced Darwin that differences among all peoples are primarily _____ differences. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?22&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Voyage of the <i>Beagle</i>: Darwin\'s Trip Around the World</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "cultural",
				true,
				"Darwin observed that there is no inborn superiority or inferiority separating different peoples.");
			
				p.addAnswer(2, "genetic",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(3, "cultural and genetic",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(4, "due to height",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(5, "genetic and height-related",
				false,
				"No, that is incorrect.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335396;


		
		

		
			
			p.question = "Species in hot climates tend to _____ compared to species in cold climates. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?22&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Voyage of the <i>Beagle</i>: Darwin\'s Trip Around the World</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "experience less interspecific competition",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(2, "have larger surface-to-volume ratios",
				true,
				"This makes it easier for these species to cool off.");
			
				p.addAnswer(3, "have smaller surface-to-volume ratios",
				false,
				"No.  This would promote the conservation of heat.");
			
				p.addAnswer(4, "be less colorful",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(5, "have less fear of humans",
				false,
				"No, that is incorrect.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335397;


		
		

		
			
			p.question = "In the Andes, at elevations of 12,000 feet, Darwin collected fossilized marine shells. The existence of marine shells at this altitude provided evidence that _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?22&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Voyage of the <i>Beagle</i>: Darwin\'s Trip Around the World</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "marine organisms can survive at great elevation",
				false,
				"Not if they are out of water.");
			
				p.addAnswer(2, "the deposit had been gradually uplifted to its present location",
				true,
				"The location where the marine shells were found was once at the bottom of an ocean.");
			
				p.addAnswer(3, "geologic  processes occur at a rapid rate",
				false,
				"The finding of fossilized marine shells is not sufficient to draw conclusions about the rate at which geologic processes occur.");
			
				p.addAnswer(4, "someone carried them from the oceans and left them on the mountains",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(5, "Earth\'s surface does not change",
				false,
				"No, that is incorrect.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335398;


		
		

		
			
			p.question = "The Gal&#225;pagos Islands are located _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?22&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Voyage of the <i>Beagle</i>: Darwin\'s Trip Around the World</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "in the Arctic",
				false,
				"Go south.");
			
				p.addAnswer(2, "in the Antarctic",
				false,
				"Go north.");
			
				p.addAnswer(3, "off the coast of California",
				false,
				"Go south.");
			
				p.addAnswer(4, "Off the coast of Ecuador",
				true,
				"The Gal&#225;pagos Islands are located on the equator off the coast of Ecuador.");
			
				p.addAnswer(5, "off the coast of Brazil",
				false,
				"Go west.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335399;


		
		

		
			
			p.question = "Why were the Gal&#225;pagos Islands so important to Darwin\'s formulation of natural selection? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?22&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Voyage of the <i>Beagle</i>: Darwin\'s Trip Around the World</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "They provided evidence in support of uniformitarianism.",
				false,
				"While this is so, another choice better focuses on their importance in the formulation of natural selection.");
			
				p.addAnswer(2, "They are where Darwin did most of his writing.",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(3, "The Gal&#225;pagos Islands are the only place in the world where finches are found.",
				false,
				"The distribution of finches is not limited to the Gal&#225;pagos Islands.");
			
				p.addAnswer(4, "Each island in the Gal&#225;pagos possessed unique species.",
				true,
				"The origin of so many unique species in a small geographical area intrigued Darwin, and played a role in his formulation of natural selection.");
			
				p.addAnswer(5, "The species found on the Gal&#225;pagos Islands are also found in Australia.",
				false,
				"No, they aren\'t.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335400;


		
		

		
			
			p.question = "Which of the following is(are) homologous to the bones in this image? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?22&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Reconstructing Forelimbs</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/2214q.jpg\" ALT=\"Question #14\" BORDER=\"1\" >";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "<IMG SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/2214a1.jpg\" ALT=\"Question #14, Answer #1\" BORDER=\"1\" >",
				false,
				"This is the humerus of a bat wing.");
			
				p.addAnswer(2, "<IMG SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/2214a2.jpg\" ALT=\"Question #14, Answer #2\" BORDER=\"1\" >",
				false,
				"This is the humerus of a cat limb.");
			
				p.addAnswer(3, "<IMG SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/2214a3.jpg\" ALT=\"Question #14, Answer #3\" BORDER=\"1\" >",
				true,
				"The digits of a cat are homologous to those of these whale bones.");
			
				p.addAnswer(4, "<IMG SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/2214a4.jpg\" ALT=\"Question #14, Answer #4\" BORDER=\"1\" >",
				false,
				"This is a human ulna.");
			
				p.addAnswer(5, "<IMG SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/2214a5.jpg\" ALT=\"Question #14, Answer #5\" BORDER=\"1\" >",
				false,
				"These are human carpals.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335401;


		
		

		
			
			p.question = "The wing of a bat is homologous to the _____ of a whale. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?22&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Reconstructing Forelimbs</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "tail",
				false,
				"These are not homologous structures.");
			
				p.addAnswer(2, "blowhole",
				false,
				"Be serious.");
			
				p.addAnswer(3, "flipper",
				true,
				"The bones of a bat wing and a whale flipper are homologous.");
			
				p.addAnswer(4, "rib cage",
				false,
				"These are not homologous structures.");
			
				p.addAnswer(5, "baleen",
				false,
				"These are not homologous structures.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

