

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "Investigation Quiz > How Can Antibiotic-Resistant Plasmids Transform <i>E. coli?</i>";
	ak.quiz_loc_with_commas = "Investigation Quiz, How Can Antibiotic-Resistant Plasmids Transform <i>E. coli?</i>";
	ak.quiz_title = "How Can Antibiotic-Resistant Plasmids Transform <i>E. coli?</i>";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 5;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 5;
	ak.non_essay_total = 0;
	ak.scored_item_total = 0;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337679;


		
		

		
			p.question = "On which petri dish do only transformed cells grow?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337680;


		
		

		
			p.question = "Which of the plates is used as a control to show that nontransformed <i>E. coli</i> will not grow in the presence of kanamycin?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337681;


		
		

		
			p.question = "If a student wants to verify that transformation has occurred, what procedure should the student use?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337682;


		
		

		
			p.question = "Which antibiotic plasmid has been used?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337683;


		
		

		
			p.question = "What is the explanation for these results?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

