

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "Investigation Quiz > How Does the Fungus <i>Pilobolus</i> Succeed as a Decomposer?";
	ak.quiz_loc_with_commas = "Investigation Quiz, How Does the Fungus <i>Pilobolus</i> Succeed as a Decomposer?";
	ak.quiz_title = "How Does the Fungus <i>Pilobolus</i> Succeed as a Decomposer?";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 7;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 7;
	ak.non_essay_total = 0;
	ak.scored_item_total = 0;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337746;


		
		

		
			p.question = "If the hypothesis that spores or mycelium arrive after manure is deposited is correct, which set of samples should have the least <i>Pilobolus</i>?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337747;


		
		

		
			p.question = "Do your results support the hypothesis that spores or mycelium arrive on manure after it is deposited? Why?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337748;


		
		

		
			p.question = "Which of the treatments is the experimental treatment?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337749;


		
		

		
			p.question = "The other three treatments are controls. Why?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337750;


		
		

		
			p.question = "Do your results support the Modified Hypothesis?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337751;


		
		

		
			p.question = "Do your results support or refute your hypothesis that <i>Pilobolus</i> can aim its sporangia toward light before shooting them in that direction?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337752;


		
		

		
			p.question = "If the spores are aimed off the manure, where are many of them likely to land? How is this adaptive for these fungi?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

