

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "46: Animal Reproduction > Practice Test";
	ak.quiz_loc_with_commas = "46: Animal Reproduction, Practice Test";
	ak.quiz_title = "Practice Test";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 42;
	ak.non_essay_total = 42;
	ak.scored_item_total = 42;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336666;


		
		

		
			
			p.question = "In general, what is the ploidy (<i>n</i>) state of human cells? (<script type=\"text/javascript\">ebook(\'4601\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "diploid except for gametes",
				true,
				"Correct. Human somatic cells are diploid, and meiosis produces haploid gametes.");
			
				p.addAnswer(2, "haploid except for zygotes",
				false,
				"No. Most cells are derived by mitosis from the diploid zygote.");
			
				p.addAnswer(3, "diploid early in life, becoming haploid with age",
				false,
				"No. In humans, ploidy does not change with age.");
			
				p.addAnswer(4, "haploid early in life, becoming diploid with age",
				false,
				"No. In humans, ploidy does not change with age.");
			
				p.addAnswer(5, "diploid in females, haploid in males",
				false,
				"No. Human males and females have the same ploidy; however, this does apply to bees.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336667;


		
		

		
			
			p.question = "Which one of the following statements about parthenogenesis is correct? (<script type=\"text/javascript\">ebook(\'4601\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Reproduction in social insects does not involve parthenogenesis.",
				false,
				"No. Certain members of the social organization of some insects are produced parthenogenetically.<b> </b>For example, this is true of certain bees, wasps, and ants.");
			
				p.addAnswer(2, "Sometimes a parthenogenetically produced egg may double in chromosome number to produce a \"zygote.\"",
				true,
				"Correct. This is true of some fishes, amphibians, and lizards.");
			
				p.addAnswer(3, "Parthenogenetic species are typically all male.",
				false,
				"No. Many parthenogenetic species are all female. For example, some species of lizards are all females.");
			
				p.addAnswer(4, "In parthenogenesis, courtship is absent because only one sex is involved in reproduction.",
				false,
				"No. In some parthenogenetic lizards, females imitating males court other females prior to reproduction.");
			
				p.addAnswer(5, "In parthenogenesis, males and females each contribute half of the genetic material for the next generation.",
				false,
				"No. This is a definition of sexual reproduction involving meiotically produced gametes from two parents.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336668;


		
		

		
			
			p.question = "A hermaphrodite is an animal that _____. (<script type=\"text/javascript\">ebook(\'4601\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "fuses with one of the opposite sex",
				false,
				"No. Hermaphroditus, the mythical son of Hermes and Aphrodite, is the only male described as having successfully fused with a female to form a single, bisexual individual.");
			
				p.addAnswer(2, "contains both male and female reproductive systems in its body",
				true,
				"Correct. Depending on the species, either self-fertilization or cross-fertilization is possible.");
			
				p.addAnswer(3, "can produce zygotes of either sex",
				false,
				"No. Hermaphrodites have neither male nor female offspring. They have hermaphroditic offspring.");
			
				p.addAnswer(4, "reproduces only asexually",
				false,
				"No. Individuals of hermaphroditic species are technically neither male nor female; however, they do produce eggs and sperm that fuse to form zygotes, which makes their mode of reproduction sexual.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. Only one of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336669;


		
		

		
			
			p.question = "Which of the following is a form of asexual reproduction? (<script type=\"text/javascript\">ebook(\'4601\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "budding",
				false,
				"No. Although this is a form of asexual reproduction, there is a better choice.");
			
				p.addAnswer(2, "fragmentation and regeneration",
				false,
				"No.<b> </b>Although this is a form of asexual reproduction, there is a better choice.");
			
				p.addAnswer(3, "parthenogenesis",
				false,
				"No. Although this is a form of asexual reproduction, there is a better choice.");
			
				p.addAnswer(4, "all of the above",
				true,
				"Correct. All three of these choices are examples of asexual reproduction.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336670;


		
		

		
			
			p.question = "Which reproductive method is the most prevalent in mammals? (<script type=\"text/javascript\">ebook(\'4602\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "fragmentation",
				false,
				"No. Fragmentation is an asexual form of reproduction wherein an elephant or a panda would have to split into several pieces, with each piece growing into a mature individual. This does not happen.");
			
				p.addAnswer(2, "budding",
				false,
				"No. Were a whale a budder like the sea anemone, it would be able to split off little whales from its flukes or back. This does not happen.");
			
				p.addAnswer(3, "regeneration",
				false,
				"No. Regeneration does not produce new animals; it just restores missing parts of old ones. Mammals are not able to accomplish this above the tissue level.");
			
				p.addAnswer(4, "external fertilization",
				false,
				"No. This involves sending the gametes off to meet and fuse outside the female\'s body.");
			
				p.addAnswer(5, "internal fertilization",
				true,
				"Correct. In mammals, the sperm are deposited within the female\'s body, and the resulting zygote develops into a fetus and is later born of the mother.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336671;


		
		

		
			
			p.question = "Which one of the following is an example of a <b>mismatch</b>? (<script type=\"text/javascript\">ebook(\'4602\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "internal fertilization; terrestrial environment",
				false,
				"No. This is a correct match.<b> </b>Delicate eggs and sperm cannot be deposited into a dry environment. Internal fertilization brings them together under moist conditions.");
			
				p.addAnswer(2, "courtship behavior; aquatic and terrestrial environments",
				false,
				"No. This is a correct match. Courtship behavior promotes the release of sperm and eggs at times appropriate to maximize fertilization probability in land and water animals.");
			
				p.addAnswer(3, "seasonal sexual maturity; aquatic and terrestrial environments",
				false,
				"No. This is a correct match because both types of organisms have young during the time when the environment is most likely to allow survival.");
			
				p.addAnswer(4, "shedding gametes into the environment; terrestrial environments",
				true,
				"Correct. This is a mismatch because shedding gametes into the environment is characteristic of aquatic animals. Shedding gametes into a dry terrestrial environment would be certain death for those gametes.");
			
				p.addAnswer(5, "eggs released by females to be fertilized by males; aquatic environments",
				false,
				"No. This is a correct match. This does happen in an aquatic environment. Swimming sperm must have a fluid medium, and eggs must not dry out.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336672;


		
		

		
			
			p.question = "Individuals clustered in the same area that release their gametes into the water at the same time are engaging in _____. (<script type=\"text/javascript\">ebook(\'4602\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "spawning",
				true,
				"Correct.");
			
				p.addAnswer(2, "regeneration",
				false,
				"No. Regeneration is not a sexual form of reproduction.");
			
				p.addAnswer(3, "budding",
				false,
				"No. Budding is a form of asexual reproduction.");
			
				p.addAnswer(4, "parthenogenesis",
				false,
				"No. Parthenogenesis is a form of asexual reproduction.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336673;


		
		

		
			
			p.question = "An ovarian follicle undergoes several changes during the human female\'s menstrual cycle. Which one of the following sequences is correct, beginning with the oocyte? (<script type=\"text/javascript\">ebook(\'4603\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "corpus luteum development; follicle development; ovulation",
				false,
				"No. The corpus luteum develops after ovulation.");
			
				p.addAnswer(2, "follicle development; ovulation; corpus luteum development",
				true,
				"Correct. The ovarian cycle consists of a follicular phase, during which follicles grow to maturity, followed by ovulation. This is followed by a luteal phase during which the old follicle cells that were left behind form the corpus luteum.");
			
				p.addAnswer(3, "corpus luteum development; ovulation; follicle development",
				false,
				"No. The corpus luteum develops after ovulation.");
			
				p.addAnswer(4, "follicle development; corpus luteum development; ovulation",
				false,
				"No. The corpus luteum develops after ovulation.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336674;


		
		

		
			
			p.question = "Immediately after ovulation into the coelom, an egg is collected into the _____. (<script type=\"text/javascript\">ebook(\'4603\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "uterus",
				false,
				"No. The oocyte arrives at the uterus via the oviduct.");
			
				p.addAnswer(2, "oviduct",
				true,
				"Correct. The oocyte arrives at the oviduct shortly after ovulation.");
			
				p.addAnswer(3, "ovary",
				false,
				"No. Ovulation is the release of an oocyte from an ovary.");
			
				p.addAnswer(4, "vagina",
				false,
				"No. The uterus empties into the vagina, the birth canal through which a baby is born.");
			
				p.addAnswer(5, "cervix",
				false,
				"No. The cervix is the neck of the uterus.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336675;


		
		

		
			
			p.question = "How do egg cells enter the oviduct after ovulation? (<script type=\"text/javascript\">ebook(\'4603\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Follicle contraction squirts them into the oviduct.",
				false,
				"No. The follicle releases the egg when it bursts, but the follicle does not propel it into the oviduct.");
			
				p.addAnswer(2, "Ciliary currents bring fluid inside, carrying the egg cell along.",
				true,
				"Correct. The oviduct has a funnel-like opening, and cilia on the inner epithelium lining the duct help collect the egg cell by drawing fluid from the body cavity into the duct.");
			
				p.addAnswer(3, "The ovaries are contained within the oviducts.",
				false,
				"No. They are not in the oviducts.");
			
				p.addAnswer(4, "Muscular projections of the uterine wall grasp the egg cell and force it into the tube.",
				false,
				"No. The action is more delicate than this.");
			
				p.addAnswer(5, "The egg cell actively swims to the tube, using its flagellum.",
				false,
				"No. An egg cell has neither cilia nor flagella. Sperm are the gametes with a flagellum.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336676;


		
		

		
			
			p.question = "Bartholin\'s gland _____. (<script type=\"text/javascript\">ebook(\'4603\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "contains spongy tissue that fills with blood during arousal",
				false,
				"No. This would be the shaft of the female\'s clitoris.");
			
				p.addAnswer(2, "secretes progesterone and estrogen to maintain pregnancy",
				false,
				"No. This is the function of the corpus luteum, the glandular tissue that develops in a vacant follicle.");
			
				p.addAnswer(3, "covers the vagina before sexual intercourse",
				false,
				"No. This is a thin membrane of uncertain function called the hymen.");
			
				p.addAnswer(4, "secretes lubricating fluid",
				true,
				"Correct. Bartholin\'s gland is located posterior to the vaginal opening and protects delicate tissues from abrasion during sexual activity.");
			
				p.addAnswer(5, "produces secretions that contribute to semen",
				false,
				"No. Males do not have a Bartholin\'s gland.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336677;


		
		

		
			
			p.question = "Where do developing sperm cells undergo meiosis? (<script type=\"text/javascript\">ebook(\'4603\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "in the epididymis",
				false,
				"No. The epididymis is a site where stored sperm mature.");
			
				p.addAnswer(2, "in the vas deferens",
				false,
				"No. The vas deferens is a passageway that connects the epididymis to an ejaculatory duct.");
			
				p.addAnswer(3, "in the seminal vesicle",
				false,
				"No. The seminal vesicle is an accessory semen-secreting gland.");
			
				p.addAnswer(4, "in the seminiferous tubules",
				true,
				"Correct. The site of spermatogenesis is the seminiferous tubules of the testes.");
			
				p.addAnswer(5, "in the prostate gland",
				false,
				"No. The prostate gland is an accessory semen-secreting gland.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336678;


		
		

		
			
			p.question = "The _____ is(are) the site of testosterone production in the testis. (<script type=\"text/javascript\">ebook(\'4603\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "seminiferous tubules",
				false,
				"No. Testosterone is secreted by cells scattered between the seminiferous tubules.");
			
				p.addAnswer(2, "epididymis",
				false,
				"No. The epididymis is outside the testes.");
			
				p.addAnswer(3, "Leydig cells",
				true,
				"Correct. Leydig cells scattered among the seminiferous tubules produce testosterone.");
			
				p.addAnswer(4, "seminal vesicle",
				false,
				"No. The seminal vesicle is outside the testes.");
			
				p.addAnswer(5, "prostate gland",
				false,
				"No. The prostate gland is outside the testes.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336679;


		
		

		
			
			p.question = "In many mammals, the testes are located outside the abdominal cavity within the scrotum because _____. (<script type=\"text/javascript\">ebook(\'4603\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the elevated pressure within the abdominal cavity would collapse the small passageways within the testes",
				false,
				"No. Although the testes are outside the abdominal cavity, a portion of the passageway returns there as secretions from various glands are added to the semen. Collapse is not a problem.");
			
				p.addAnswer(2, "this location allows for a shorter pathway to the urethra",
				false,
				"No. The ducts are longer than they would be if the testes were in the abdominal cavity.");
			
				p.addAnswer(3, "blood flow to the scrotum is not interrupted during erection",
				false,
				"No. Each organ in the body receives blood through an individual capillary network. Blood flow is temporarily altered within the penis, but this has no impact on other organs.");
			
				p.addAnswer(4, "sperm are unable to mature properly at the higher temperatures found within the abdominal cavity",
				true,
				"Correct. The testes are about 2&deg;C cooler than the abdominal cavity.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. Only one of the other answers is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336680;


		
		

		
			
			p.question = "Which part of the male reproductive tract stores sperm as they mature until they exit from the male\'s body? (<script type=\"text/javascript\">ebook(\'4603\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "epididymis",
				true,
				"Correct. Sperm finish their development in the epididymis, where they are primed to swim and participate in fertilization, and they are held there for delivery.");
			
				p.addAnswer(2, "vas deferens",
				false,
				"No. This is a transport tube that delivers sperm from the scrotum into the excretory system\'s discharge tube.");
			
				p.addAnswer(3, "glans",
				false,
				"No. The glans is the distal end of the male\'s sperm-delivery apparatus, the penis.");
			
				p.addAnswer(4, "urethra",
				false,
				"No. The urethra is the common passage through the penis for both sperm and urine (but never at the same time).");
			
				p.addAnswer(5, "seminal vesicle",
				false,
				"No. The seminal vesicles secrete a thick fluid that nourishes the sperm and lubricates their passageway.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336681;


		
		

		
			
			p.question = "Where is one <b>least</b> likely to find complete semen (in which all the components are present)? (<script type=\"text/javascript\">ebook(\'4603\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "in the vagina of a woman after copulation",
				false,
				"No. All the components of sperm are present prior to ejaculation.");
			
				p.addAnswer(2, "in the epididymis",
				true,
				"Correct. Semen consists of sperm and the secretions of the seminal vesicles, the bulbourethral glands, and the prostate. In the epididymis, the glandular structures have not yet contributed their secretions to the semen.");
			
				p.addAnswer(3, "prior to the junction of the bulbourethral duct and the urethra",
				false,
				"No. Bulbourethral secretions are the last component added to sperm.");
			
				p.addAnswer(4, "at the male urethral opening",
				false,
				"No. All the components of sperm are present prior to ejaculation.");
			
				p.addAnswer(5, "in the urethra",
				false,
				"No. All the components of sperm are present prior to ejaculation.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336682;


		
		

		
			
			p.question = "Which structure is part of the excretory and reproductive systems in males? (<script type=\"text/javascript\">ebook(\'4603\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "ureter",
				false,
				"No. The ureter carries urine from the kidney to the bladder. It never connects with the reproductive system.");
			
				p.addAnswer(2, "urethra",
				true,
				"Correct. Both urine and semen pass out of the male\'s body through this duct (but never at the same time).");
			
				p.addAnswer(3, "seminal vesicle",
				false,
				"No. The seminal vesicle is a gland that adds a nutrient secretion to the sperm as they leave the body.");
			
				p.addAnswer(4, "urinary bladder",
				false,
				"No. The urinary bladder never holds the products of the reproductive system.");
			
				p.addAnswer(5, "vas deferens",
				false,
				"No. The vas deferens is a duct that transports sperm into the excretory system\'s outlet.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336683;


		
		

		
			
			p.question = "Which one of the following choices correctly lists the four phases of the sexual response cycle in their proper sequence? (<script type=\"text/javascript\">ebook(\'4603\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "excitement, plateau, orgasm, resolution",
				true,
				"Correct.");
			
				p.addAnswer(2, "plateau, excitement, orgasm, resolution",
				false,
				"No. The plateau phase comes after the excitement phase.");
			
				p.addAnswer(3, "excitement, plateau, resolution, orgasm",
				false,
				"No. The resolution phase comes after the orgasm phase.");
			
				p.addAnswer(4, "excitement, orgasm, plateau, resolution",
				false,
				"No. The orgasm phase comes after the plateau phase.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336684;


		
		

		
			
			p.question = "Sperm has several components; the function of the acrosome is to _____. (<script type=\"text/javascript\">ebook(\'4604\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "produce a base to neutralize the acidic environment of the female reproductive system",
				false,
				"No. Alkaline secretions originate in the seminal vesicles and bulbourethral glands.");
			
				p.addAnswer(2, "metabolize the sugars provided by the semen for energy",
				false,
				"No. Mitochondria located behind the head metabolize the sugars to produce ATP.");
			
				p.addAnswer(3, "release an enzyme that breaks down the membrane of the ovum",
				true,
				"Correct. The membrane surrounding the ovum must be digested before penetration of the sperm can occur.");
			
				p.addAnswer(4, "propel the sperm as they swim through the fluid of the female reproductive tract",
				false,
				"No. Sperm are equipped with a flagellum.");
			
				p.addAnswer(5, "All of the above.",
				false,
				"No. Only one of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336685;


		
		

		
			
			p.question = "Which part of the human sperm carries a haploid set of chromosomes? (<script type=\"text/javascript\">ebook(\'4604\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "head",
				true,
				"Correct. The head contains the nucleus, which contains the haploid chromosomes.");
			
				p.addAnswer(2, "neck",
				false,
				"No. The neck is merely the region that joins the head of the sperm to the part carrying a large mitochondrion.");
			
				p.addAnswer(3, "middle piece",
				false,
				"No. This part of the sperm contains a large spiral mitochondrion that provides energy to power the flagellum.");
			
				p.addAnswer(4, "acrosome",
				false,
				"No. The acrosome contains enzymes that help the sperm penetrate the egg\'s jelly coat, providing an opening for the chromosomes to enter the egg.");
			
				p.addAnswer(5, "vitelline layer",
				false,
				"No. The vitelline layer surrounds the plasma membrane of the egg and is not part of a sperm.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336686;


		
		

		
			
			p.question = "In mammals, meiosis to produce the female egg cell is initiated in the _____. (<script type=\"text/javascript\">ebook(\'4604\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "ovary",
				true,
				"Correct. Oogenesis begins with primordial germ cells in the ovary.");
			
				p.addAnswer(2, "vagina",
				false,
				"No. The vagina is the birth canal and the site into which sperm are deposited.");
			
				p.addAnswer(3, "uterus",
				false,
				"No. The uterus is the site of prenatal development.");
			
				p.addAnswer(4, "oviduct",
				false,
				"No. The oviduct leads from the ovary to the uterus.");
			
				p.addAnswer(5, "cervix",
				false,
				"No. The cervix is the neck of the uterus.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336687;


		
		

		
			
			p.question = "From a single cell, oogenesis in a mammal will produce _____. (<script type=\"text/javascript\">ebook(\'4604\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "four ova (eggs)",
				false,
				"No. Not all resulting cells become functional ova.");
			
				p.addAnswer(2, "four spermatozoa",
				false,
				"No. Sperm are produced by spermatogenesis.");
			
				p.addAnswer(3, "an ovum and three polar bodies",
				true,
				"Correct. Meiosis I produces one large secondary oocyte and a polar body. These cells divide again at meiosis II, producing a single large ovum and three polar bodies.");
			
				p.addAnswer(4, "a primary oocyte",
				false,
				"No. The primary oocyte is what undergoes meiosis.");
			
				p.addAnswer(5, "four polar bodies",
				false,
				"No. This outcome does not allow for the formation of a functional ovum.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336688;


		
		

		
			
			p.question = "In spermatogenesis, each primary spermatocyte gives rise to _____ sperm. (<script type=\"text/javascript\">ebook(\'4604\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "one",
				false,
				"No. Remember sperm have small amounts of cytoplasm.");
			
				p.addAnswer(2, "two",
				false,
				"No. There are two meiotic divisions leading to spermatids, producing more than two cells.");
			
				p.addAnswer(3, "four",
				true,
				"Correct. Each diploid primary spermatocyte gives rise to four haploid sperm.");
			
				p.addAnswer(4, "eight",
				false,
				"No. There are two meiotic divisions leading to spermatids. This would take three divisions.");
			
				p.addAnswer(5, "millions of",
				false,
				"No. Not from a single spermatocyte.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336689;


		
		

		
			
			p.question = "At what point does the secondary oocyte complete meiosis? (<script type=\"text/javascript\">ebook(\'4604\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "when the luteinizing hormone triggers ovulation",
				false,
				"No. At ovulation, the follicle releases a secondary oocyte, which has not yet undergone meiosis II.");
			
				p.addAnswer(2, "after species-specific proteins of sperm and ovum combine",
				true,
				"Correct. When the proteins on the ovum\'s vitelline layer bind with sperm head proteins and the plasma membranes fuse, then meiosis II finishes.");
			
				p.addAnswer(3, "when the secondary oocyte implants in the endometrium of the uterus",
				false,
				"No. By the time of implantation, fertilization has occurred and rapid mitotic division of the zygote is under way.");
			
				p.addAnswer(4, "when the egg is fully surrounded by sperm and semen",
				false,
				"No. Meiosis is not completed at this time.");
			
				p.addAnswer(5, "when acrosomal enzymes begin to break down the egg\'s jelly coat",
				false,
				"No. Meiosis is completed at a later time.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336690;


		
		

		
			
			p.question = "The amount of cytoplasm found in an animal egg cell is _____ that found in the polar bodies. (<script type=\"text/javascript\">ebook(\'4604\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "greater than",
				true,
				"Correct. Meiotic divisions in oogenesis involve unequal cytokinesis; the result is a single large oocyte and much smaller polar bodies.");
			
				p.addAnswer(2, "equal to",
				false,
				"No. Consider that ova are energy-rich.");
			
				p.addAnswer(3, "less than",
				false,
				"No. Consider that ova are energy-rich.");
			
				p.addAnswer(4, "thinner",
				false,
				"No. The cytoplasm comes from the same original cell and is similar in composition.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices above is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336691;


		
		

		
			
			p.question = "Which of the following statements about oogenesis and spermatogenesis is correct? (<script type=\"text/javascript\">ebook(\'4605\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Follicle-stimulating hormone promotes egg but not sperm development.",
				false,
				"No. FSH, which regulates gamete formation, is produced by the anterior pituitary in both males and females.");
			
				p.addAnswer(2, "Luteinizing hormone triggers ovulation in females but is not important in males.",
				false,
				"No. LH stimulates ovulation and androgen-mediated sperm production.");
			
				p.addAnswer(3, "Releasing hormone triggers the anterior pituitary to release FSH and LH in males but not females.",
				false,
				"No. The source and effect of releasing hormone are the same in males and females.");
			
				p.addAnswer(4, "Primary oocytes and primary spermatocytes follow a similar pattern of development through meiosis.",
				false,
				"No. The result of meiosis in females is one gamete and three polar bodies, whereas the result of meiosis in males is four functional gametes.");
			
				p.addAnswer(5, "The principal sex hormones in males and females are steroid hormones.",
				true,
				"Correct.  Steroid hormones regulate gametogenesis in both sexes.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336692;


		
		

		
			
			p.question = "Menstruation results in the discharge of _____. (<script type=\"text/javascript\">ebook(\'4605\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the follicle",
				false,
				"No. Follicles are not discharged during menstruation.");
			
				p.addAnswer(2, "the endometrial lining",
				true,
				"Correct. In menstrual cycles, the endometrium is shed from the uterus through the cervix and vagina.");
			
				p.addAnswer(3, "the corpus luteum of the uterus",
				false,
				"No. The corpus luteum degenerates within the ovary.");
			
				p.addAnswer(4, "surface cells from the vagina",
				false,
				"No. Menstruation begins in the uterus.");
			
				p.addAnswer(5, "blood from the outer surface of the uterus",
				false,
				"No. Materials are shed from the interior of the uterus.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336693;


		
		

		
			
			p.question = "In males, FSH _____. (<script type=\"text/javascript\">ebook(\'4605\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "is not produced; it is a female hormone",
				false,
				"No. Males produce FSH.");
			
				p.addAnswer(2, "is directly responsible for facial hair growth beginning at puberty",
				false,
				"No. The growth of facial hair is attributable to testosterone.");
			
				p.addAnswer(3, "is produced by the hypothalamus",
				false,
				"No. FSH is produced by the anterior pituitary.");
			
				p.addAnswer(4, "stimulates development of sperm cells in the testes",
				true,
				"Correct. FSH acts on the seminiferous tubules to increase spermatogenesis.");
			
				p.addAnswer(5, "stimulates the release of semen by the prostate gland during ejaculation",
				false,
				"No. Gonadotropic hormones act on the gonads.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336694;


		
		

		
			
			p.question = "Which one of the following statements about luteinizing hormone in the female reproductive system is correct? (<script type=\"text/javascript\">ebook(\'4605\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "It is produced by the hypothalamus.",
				false,
				"No. LH is produced by the anterior pituitary in response to releasing hormone from the hypothalamus.");
			
				p.addAnswer(2, "It causes mitosis of the primary oocyte.",
				false,
				"No. FSH stimulates the primary oocyte to undergo meiosis, producing the secondary oocyte.");
			
				p.addAnswer(3, "It inhibits ovulation.",
				false,
				"No. LH stimulates ovulation.");
			
				p.addAnswer(4, "It triggers development of endometrium in the corpus luteum.",
				false,
				"No. It triggers development of the corpus luteum in the vacant follicle after ovulation. The endometrium is in the uterus.");
			
				p.addAnswer(5, "It is responsible for mediating the production of estrogen and progesterone simultaneously.",
				true,
				"Correct. Luteinizing hormone causes the corpus luteum to develop and produce these two hormones.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336695;


		
		

		
			
			p.question = "After ovulation occurs, the empty follicle _____. (<script type=\"text/javascript\">ebook(\'4605\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "can be recycled to produce more eggs",
				false,
				"No. The follicle becomes a structure that produces a hormone, which maintains the lining of the uterus for the remainder of the cycle.");
			
				p.addAnswer(2, "changes into the corpus luteum and makes hormones",
				true,
				"Correct. Unless reinforced by human chorionic gonadotropin (HCG), the corpus luteum disintegrates after about two weeks. Without its hormones, the endometrium breaks down, and a menstrual cycle begins.");
			
				p.addAnswer(3, "quickly degenerates",
				false,
				"No. The follicle will survive for at least two weeks and, during pregnancy, much longer.");
			
				p.addAnswer(4, "immediately initiates menstruation",
				false,
				"No. If this were true, the newly ovulated egg, if fertilized, would not have the proper uterine environment for its development.");
			
				p.addAnswer(5, "becomes the site of the implantation of a fertilized egg",
				false,
				"No. The follicle remains within the ovary. Implantation should occur in the uterus.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336696;


		
		

		
			
			p.question = "Concentrations of which hormone stimulate the hypothalamus to increase or decrease hormones that stimulate sperm production in the testes? (<script type=\"text/javascript\">ebook(\'4605\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "follicle-stimulating hormone",
				false,
				"No. FSH is released from the anterior pituitary after stimulation from a hypothalamic releasing factor.");
			
				p.addAnswer(2, "luteinizing hormone",
				false,
				"No. LH is released from the anterior pituitary after stimulation from a hypothalamic releasing factor.");
			
				p.addAnswer(3, "testosterone",
				true,
				"Correct. High concentrations of testosterone in the blood inhibit the production of releasing hormone by the hypothalamus. This slows sperm production. Low concentrations of testosterone have the opposite effect.");
			
				p.addAnswer(4, "releasing hormone",
				false,
				"No. Releasing hormone is secreted from the hypothalamus in response to the hormone in question.");
			
				p.addAnswer(5, "progesterone",
				false,
				"No. Progesterone is a hormone that regulates events in the female\'s reproductive cycle.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336697;


		
		

		
			
			p.question = "After the menstrual period, which of the following hormones is the first to increase significantly every 28 days or so, initiating the ovarian cycle? (<script type=\"text/javascript\">ebook(\'4605\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "progesterone",
				false,
				"No. Progesterone is secreted by the corpus luteum after ovulation has occurred.");
			
				p.addAnswer(2, "follicle-stimulating hormone",
				true,
				"Correct. FSH stimulates a small number of immature follicles to begin growth and to secrete estrogen.");
			
				p.addAnswer(3, "estrogen",
				false,
				"No. Follicles produce estrogen after they have been stimulated by FSH.");
			
				p.addAnswer(4, "luteinizing hormone",
				false,
				"No. At the beginning of the ovarian cycle, the developing follicles have yet to express LH receptors.");
			
				p.addAnswer(5, "human chorionic gonadotropin",
				false,
				"No. This hormone is produced by the embryo and, of course, is only detectable during pregnancy.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336698;


		
		

		
			
			p.question = "What is the source of the hormones that, when suddenly absent, are directly responsible for the onset of menstruation? (<script type=\"text/javascript\">ebook(\'4605\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "hypothalamus",
				false,
				"No. The hypothalamus does not produce these hormones, but it does produce the releasing hormone.");
			
				p.addAnswer(2, "pituitary",
				false,
				"No. The pituitary does not produce these hormones, but it does make FSH, which stimulates an ovarian follicle to develop.");
			
				p.addAnswer(3, "ovarian follicle",
				false,
				"No. The ovarian follicle produces estrogen, which promotes endometrium formation.");
			
				p.addAnswer(4, "corpus luteum",
				true,
				"Correct. The corpus luteum produces estrogen and progesterone; it disintegrates if pregnancy does not occur, and the sudden absence of these hormones triggers menstruation.");
			
				p.addAnswer(5, "Bartholin\'s glands",
				false,
				"No. Bartholin\'s glands produce a lubricating secretion in the vagina, not hormones.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336699;


		
		

		
			
			p.question = "A large number of hormones function in the human menstrual cycle, but only two of them are called female sex hormones. These are _____. (<script type=\"text/javascript\">ebook(\'4605\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "follicle-stimulating hormone and estradiol",
				false,
				"No. Males also produce FSH.");
			
				p.addAnswer(2, "follicle-stimulating hormone and progesterone",
				false,
				"No. Males also produce FSH.");
			
				p.addAnswer(3, "follicle-stimulating hormone and luteinizing hormone",
				false,
				"No. Males also produce both of these hormones.");
			
				p.addAnswer(4, "progesterone and estrogen",
				true,
				"Correct. The female sex hormones, estrogen and progesterone, are secreted primarily by the ovary.");
			
				p.addAnswer(5, "gonadotropin-releasing hormone and follicle-stimulating hormone",
				false,
				"No. Males also produce both of these hormones.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336700;


		
		

		
			
			p.question = "On its way to fertilize a human egg, a sperm cell does not have to pass through which of the following? (<script type=\"text/javascript\">ebook(\'4606\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "oviduct",
				false,
				"No. Because fertilization usually occurs in the oviduct, sperm must pass through it as they move toward the egg.");
			
				p.addAnswer(2, "vagina",
				false,
				"No. The vagina is the entrance to the female reproductive system. Because fertilization usually occurs in the oviduct, sperm must pass through the vagina as they move toward the egg.");
			
				p.addAnswer(3, "ovary",
				true,
				"Correct. The ovary is the source of the mature egg cells. After ovulation, the egg cell enters the oviduct (or, rarely, the abdominal cavity), where fertilization occurs.");
			
				p.addAnswer(4, "vas deferens",
				false,
				"No. The vas deferens is part of the pathway through which sperm travel as they leave the male\'s body.");
			
				p.addAnswer(5, "cervix",
				false,
				"No. The cervix is the entrance to the uterus. Because fertilization usually occurs in the oviduct, sperm must pass through the cervix.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336701;


		
		

		
			
			p.question = "Pregnancy tests detect a hormone in a woman\'s urine that is present only when an embryo is developing in her uterus. This hormone is secreted by _____. (<script type=\"text/javascript\">ebook(\'4606\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the ovary",
				false,
				"No. The ovary produces estrogen and progesterone.");
			
				p.addAnswer(2, "the embryo",
				true,
				"Correct. The embryo produces human chorionic gonadotropin (HCG), which maintains the corpus luteum and its production of progesterone and estrogen.");
			
				p.addAnswer(3, "a follicle",
				false,
				"No. Following ovulation, the follicle becomes the corpus luteum and produces estrogen and progesterone for several weeks.");
			
				p.addAnswer(4, "the pituitary",
				false,
				"No. The pituitary produces several hormones that influence reproduction, labor, and nursing, but none that would indicate pregnancy.");
			
				p.addAnswer(5, "the endometrium",
				false,
				"No. The endometrium is not a site of hormone production.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336702;


		
		

		
			
			p.question = "Which of the following is a function of the placenta? (<script type=\"text/javascript\">ebook(\'4606\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "providing oxygen to the fetus",
				false,
				"No. Although this is a function of the placenta, there is a better choice.");
			
				p.addAnswer(2, "carrying wastes from the fetus to the mother\'s circulatory system",
				false,
				"No. Although this is a function of the placenta, there is a better choice.");
			
				p.addAnswer(3, "secreting hormones that keep the uterine lining from breaking down",
				false,
				"No. Although this is a function of the placenta, there is a better choice.");
			
				p.addAnswer(4, "obtaining nutrients from the mother\'s blood",
				false,
				"No. Although this is a function of the placenta, there is a better choice.");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct. The diffusion of material between maternal and embryonic circulations across the placenta provides nutrients, exchanges respiratory gases, and disposes of fetal metabolic wastes.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336703;


		
		

		
			
			p.question = "Which one of the following is the <b>least</b> effective method of birth control? (<script type=\"text/javascript\">ebook(\'4606\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "vasectomy",
				false,
				"No. A vasectomy prevents sperm from being ejaculated.");
			
				p.addAnswer(2, "the pill",
				false,
				"No. The birth control pill prevents ovulation.");
			
				p.addAnswer(3, "morning after pill",
				false,
				"No. The morning after pill is a high-dose combination birth control pill that prevents fertilization or implantation.");
			
				p.addAnswer(4, "rhythm method",
				true,
				"Correct. A pregnancy rate of 10&#150;20% is typically reported for couples practicing the rhythm method.");
			
				p.addAnswer(5, "condom",
				false,
				"No. When used properly, a condom does block sperm from entering the female.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336704;


		
		

		
			
			p.question = "If a woman wants to become pregnant, what is the optimal day on which to have sexual intercourse? (<script type=\"text/javascript\">ebook(\'4606\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "one week before ovulation",
				false,
				"No. Sperm cannot survive a week in the female reproductive tract.");
			
				p.addAnswer(2, "three days before ovulation",
				false,
				"No. Few sperm can survive within the female reproductive tract for this period of time.");
			
				p.addAnswer(3, "the day of ovulation, approximately mid-cycle",
				true,
				"Correct. Because the egg can survive in the oviduct for 24 to 48 hours, intercourse should be timed to coincide with ovulation.");
			
				p.addAnswer(4, "the day before menstruation is due to begin",
				false,
				"No. This is about two weeks from ovulation.");
			
				p.addAnswer(5, "one week after ovulation",
				false,
				"No. The egg cannot survive this long.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336705;


		
		

		
			
			p.question = "Birth control pills contain synthetic estrogen and progesterone. How do these hormones prevent pregnancy? (<script type=\"text/javascript\">ebook(\'4606\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "They trigger premature ovulation, before an egg is mature.",
				false,
				"No. The egg and the ovary are influenced by FSH and LH; estrogen and progesterone have no direct effect.");
			
				p.addAnswer(2, "They cause the lining of the uterus to be sloughed off.",
				false,
				"No. Estrogen and progesterone stimulate the development and maintenance of the endometrium.");
			
				p.addAnswer(3, "They cause the corpus luteum to degenerate.",
				false,
				"No. The corpus luteum degenerates spontaneously unless stimulated by human chorionic gonadotropin.");
			
				p.addAnswer(4, "They inhibit the pituitary from secreting FSH and LH, preventing ovulation.",
				true,
				"Correct. Estrogen and progesterone are maintained at high concentrations during pregnancy and provide negative feedback that suppresses the release of FSH and LH.");
			
				p.addAnswer(5, "They prevent the monthly development of the uterine lining.",
				false,
				"No. The normal action of these two hormones is the development of the uterine lining.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336706;


		
		

		
			
			p.question = "A vasectomy is an effective technique for birth control in males because it _____. (<script type=\"text/javascript\">ebook(\'4606\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "reduces the alkaline secretions in the semen, and the sperm are then destroyed in the female reproductive tract",
				false,
				"No. The alkalinity of the semen originates in the seminal vesicles (as well as the bulbourethral glands); their connection to the male reproductive system is not through the vas deferens.");
			
				p.addAnswer(2, "causes the prostate gland to enlarge and seal off the ejaculatory duct",
				false,
				"No. An enlarged prostate is a common problem in older men; it is usually treated surgically or with drugs, but it is unrelated to a vasectomy.");
			
				p.addAnswer(3, "severs the capillaries to the spermatozoa, which then die",
				false,
				"No. Severing capillaries would do much more damage than just having an adverse effect on sperm production. The vas deferens is the tube that is severed in a vasectomy.");
			
				p.addAnswer(4, "severs the capillaries of the testes and prevents the arrival of pituitary hormone",
				false,
				"No. Blood does not move through the vas deferens, and if the testes were destroyed, several problems would result from the absence of testosterone. The vas deferens is the tube that is severed in a vasectomy.");
			
				p.addAnswer(5, "severs the route used by the sperm to exit the male\'s body",
				true,
				"Correct. Each vas deferens is located between the epididymis and the urethra. If the vas deferens is severed, sperm are unable to exit the body.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336707;


		
		

		
			
			p.question = "Which of the following is the best way to reduce the chances of conception and the spread of sexually transmitted diseases? (<script type=\"text/javascript\">ebook(\'4606\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "condom",
				true,
				"Correct. When used properly, a condom prevents the actual contact of tissues and secretions, in addition to preventing contact between sperm and egg.");
			
				p.addAnswer(2, "birth control pill",
				false,
				"No. Birth control pills alter a woman\'s reproductive cycle, but they provide no barrier against the transmission of pathogens.");
			
				p.addAnswer(3, "diaphragm",
				false,
				"No. A diaphragm may prevent sperm from entering the uterus, but it provides no barrier against the transmission of pathogens.");
			
				p.addAnswer(4, "intrauterine device",
				false,
				"No. An IUD prevents the implantation of the blastocyst in the uterus, but it provides no barrier against the transmission of pathogens.");
			
				p.addAnswer(5, "withdrawal",
				false,
				"No. In addition to having only moderate success as a contraceptive strategy, withdrawal provides no barrier against the transmission of pathogens.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

