

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "GraphIt! Quiz > GraphIt! Quiz > Global Fisheries and Overfishing";
	ak.quiz_loc_with_commas = "GraphIt! Quiz, GraphIt! Quiz, Global Fisheries and Overfishing";
	ak.quiz_title = "Global Fisheries and Overfishing";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 8;
	ak.non_essay_total = 8;
	ak.scored_item_total = 8;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337469;


		
		

		
			
			p.question = "During which time period was the growth of fish captures greatest?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "1955 to 1970",
				true,
				"");
			
				p.addAnswer(2, "1970 to 1985",
				false,
				"");
			
				p.addAnswer(3, "1985 to 2000",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337470;


		
		

		
			
			p.question = "Choose the likeliest explanation for the trend shown in this graph.";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "New fisheries are constantly being discovered and developed.",
				false,
				"");
			
				p.addAnswer(2, "Most potential fisheries in the world\'s oceans had been discovered by about 1970.",
				true,
				"");
			
				p.addAnswer(3, "Most of the world\'s fisheries had been severely overfished by about 1970.",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337471;


		
		

		
			
			p.question = "Which development stage consistently represents the highest proportion of fisheries resources since 1950?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "fully developed",
				false,
				"");
			
				p.addAnswer(2, "developing",
				true,
				"");
			
				p.addAnswer(3, "undeveloped",
				false,
				"");
			
				p.addAnswer(4, "senescent",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337472;


		
		

		
			
			p.question = "Which development stage(s) increased in proportion by more than 20% since 1950?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "undeveloped",
				false,
				"");
			
				p.addAnswer(2, "developing",
				false,
				"");
			
				p.addAnswer(3, "fully developed",
				false,
				"");
			
				p.addAnswer(4, "senescent",
				false,
				"");
			
				p.addAnswer(5, "the second and third choices",
				false,
				"");
			
				p.addAnswer(6, "the third and fourth choices",
				true,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337473;


		
		

		
			
			p.question = "Choose the best statement for how this graph explains the global fish capture trends in Step 1.";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Developing fisheries have replaced undeveloped fisheries, leading to accelerated growth in the global fish catch.",
				false,
				"");
			
				p.addAnswer(2, "Fully developed and senescent fisheries have been increasing relative to others, leading to slowed growth in the global fish catch.",
				true,
				"");
			
				p.addAnswer(3, "New, undeveloped fisheries have disappeared, leading to a precipitous drop in the global fish catch.",
				false,
				"");
			
				p.addAnswer(4, "The proportion of developing fisheries has declined, leading to slowed growth in the global fish catch.",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337474;


		
		

		
			
			p.question = "For projection 2, which resource stage represents roughly 50% of all resources in 2025?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "developing",
				false,
				"");
			
				p.addAnswer(2, "senescent",
				false,
				"");
			
				p.addAnswer(3, "undeveloped",
				false,
				"");
			
				p.addAnswer(4, "fully developed",
				true,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337475;


		
		

		
			
			p.question = "Given that projection 1 holds true, choose the most likely trend for global fish captures over the next 40 years.";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "stable or slightly declining fish captures",
				false,
				"");
			
				p.addAnswer(2, "rapidly accelerating fish captures",
				false,
				"");
			
				p.addAnswer(3, "rapidly declining fish captures",
				true,
				"");
			
				p.addAnswer(4, "steadily increasing fish captures",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337476;


		
		

		
			
			p.question = "Given that projection 2 holds true, choose the most likely trend for global fish captures over the next 40 years.";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "stable or slightly declining fish captures",
				true,
				"");
			
				p.addAnswer(2, "rapidly accelerating fish captures",
				false,
				"");
			
				p.addAnswer(3, "rapidly declining fish captures",
				false,
				"");
			
				p.addAnswer(4, "steadily increasing fish captures",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

