

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "Investigation Quiz > How Can Gel Electrophoresis Be Used to Analyze DNA?";
	ak.quiz_loc_with_commas = "Investigation Quiz, How Can Gel Electrophoresis Be Used to Analyze DNA?";
	ak.quiz_title = "How Can Gel Electrophoresis Be Used to Analyze DNA?";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 6;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 6;
	ak.non_essay_total = 0;
	ak.scored_item_total = 0;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337685;


		
		

		
			p.question = "What is the relationship of migration distance to fragment size?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337686;


		
		

		
			p.question = "Approximately how many base pairs are there in the fragment circled in red at left?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337687;


		
		

		
			p.question = "Which lane shows a digest with BamHI only?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337688;


		
		

		
			p.question = "Which lane shows a digest with EcoRI only?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337689;


		
		

		
			p.question = "Which lane shows the fragments produced when the plasmid was incubated with both EcoRI and BamHI?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337690;


		
		

		
			p.question = "A segment of DNA has two restriction sites--I and II. When incubated with restriction enzymes I and II, three fragments will be formed &ndash; a, b, and c. Which of the gels produced by electrophoresis would represent the separation and identity of these fragments?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

