

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "Investigation Quiz > How Do Molecular Data Fit Traditional Phylogenies?";
	ak.quiz_loc_with_commas = "Investigation Quiz, How Do Molecular Data Fit Traditional Phylogenies?";
	ak.quiz_title = "How Do Molecular Data Fit Traditional Phylogenies?";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 8;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 8;
	ak.non_essay_total = 0;
	ak.scored_item_total = 0;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337754;


		
		

		
			p.question = "The rotifer is a bilaterally symmetrical pseudocoelomate. What is the most closely related animal phylum to rotifers? Support your answer with evidence from the data you gathered.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337755;


		
		

		
			p.question = "There are three major invertebrate phyla that are called \"worms\". What are they? Despite being all \"worms\", these phyla are not considered to be closely related. Explain why the worms are dissimilar based on your data.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337756;


		
		

		
			p.question = "Echinoderms (such as a seastar) are closer to chordates than any of the other invertebrate phyla. Yet arthropods appear to share many more characteristics with chordates than echinoderms -- bilateral symmetry, cephalization, and specialized sensory apparatuses. Why do evolutionary biologists place echninoderms in the same phylogenetic branch as chordates? Do you think that the feature used in grouping these two phyla together is phylogenetically more important than other features such as symmetry, cephalization, and metamorphosis?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337757;


		
		

		
			p.question = "Which groupings are the same between the traditional and the 18S rRNA cladograms? Which phyla are still in the same clades?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337758;


		
		

		
			p.question = "Which phyla are linked together into new clades?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337759;


		
		

		
			p.question = "Which shared derived characters in the traditional cladogram must be thrown out if the 18S rRNA data indicate the definitive invertebrate clades?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337760;


		
		

		
			p.question = "What are the shared derived characters that unite each of clades A, B, C, and D as distinct and separate groups? A letter within a circle in the 18S rRNA cladogram identifies each clade in this question.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337761;


		
		

		
			p.question = "New research that shows molecular similarities in nucleotide sequences has caused biologists to revise their thinking about traditional taxonomic relationships between everything from bacteria to humans. However, many evolutionary biologists point to potential pitfalls in using only nucleotide sequence similarities in constructing cladograms. Review the chapter on molecular taxonomy in your book. Describe at least one major pitfall of using only molecular data to construct phylogenies.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

