

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "Investigation Quiz > What Role Does Amylase Play in Digestion?";
	ak.quiz_loc_with_commas = "Investigation Quiz, What Role Does Amylase Play in Digestion?";
	ak.quiz_title = "What Role Does Amylase Play in Digestion?";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 7;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 7;
	ak.non_essay_total = 0;
	ak.scored_item_total = 0;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337803;


		
		

		
			p.question = "What do tubes 2, 6, and 7 reveal about pH and amylase activity?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337804;


		
		

		
			p.question = "Which pH buffer allowed the highest amylase activity?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337805;


		
		

		
			p.question = "Which tube indicates that the amylase did not contain maltose?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337806;


		
		

		
			p.question = "Which tubes indicate that the deionized water did not contain starch or maltose?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337807;


		
		

		
			p.question = "If we left out control tubes 3, 4, or 5, what objections could be raised to the statement: \"Amylase digests starch to maltose\"? (Hint: think about the purity of the chemical solutions.)";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337808;


		
		

		
			p.question = "Would the amylase present in saliva be active in the stomach? Explain your answer.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337809;


		
		

		
			p.question = "What effect does boiling have on enzyme activity?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

