

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "29: Plant Diversity I: How Plants Colonized Land > Practice Test";
	ak.quiz_loc_with_commas = "29: Plant Diversity I: How Plants Colonized Land, Practice Test";
	ak.quiz_title = "Practice Test";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 37;
	ak.non_essay_total = 37;
	ak.scored_item_total = 37;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335746;


		
		

		
			
			p.question = "Which of the following statements about algae and plants is true? (<script type=\"text/javascript\">ebook(\'2901\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Plant cells have rigid cellulose walls, and algal cells do not.",
				false,
				"No. Both plants and algae have cell walls made of cellulose.");
			
				p.addAnswer(2, "Both plant and algal zygotes develop into embryos.",
				false,
				"No. Algae do not produce embryos.");
			
				p.addAnswer(3, "Algae have different types of chlorophyll molecules from plants.",
				false,
				"No. Both plant and algal chloroplasts contain chlorophylls a and b.");
			
				p.addAnswer(4, "Plants are multicellular, whereas algae are unicellular.",
				false,
				"No. Many algae are multicellular.");
			
				p.addAnswer(5, "Plants have a waxy, waterproof cuticle, and algae do not.",
				true,
				"Correct. Algae do not need a waterproof cuticle since they live in the water.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335747;


		
		

		
			
			p.question = "Which of the following homologies are shared by land plants and their closest living algal relatives? (<script type=\"text/javascript\">ebook(\'2901\',\'quiz\')</script>)";
			p.incorrect_any_expl = "No. This is true, but there is a better answer.";
			p.incorrect_any_expl_flag = 1;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "rosette cellulose-synthesizing complexes",
				false,
				"");
			
				p.addAnswer(2, "many of the details of cell division",
				false,
				"");
			
				p.addAnswer(3, "the presence of peroxisomes",
				false,
				"");
			
				p.addAnswer(4, "the structure of flagellated sperm (when present)",
				false,
				"");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct. All of these characteristics are shared by land plants and charophyte algae.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335748;


		
		

		
			
			p.question = "In moving to land, plants had to overcome which of the following challenges? (<script type=\"text/javascript\">ebook(\'2901\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "less available CO<sub>2</sub> in the atmosphere than in the oceans",
				false,
				"No. Just the opposite is true.");
			
				p.addAnswer(2, "desiccation",
				false,
				"No. This is true, but there is a better answer.");
			
				p.addAnswer(3, "lack of structural support",
				false,
				"No. This is true, but there is a better answer.");
			
				p.addAnswer(4, "many herbivores on land",
				false,
				"No. When plants first began to inhabit terrestrial environments, there were very few herbivores of any kind.");
			
				p.addAnswer(5, "both b and c",
				true,
				"Correct. Desiccation and lack of support against the full force of gravity were important challenges to be overcome as plants moved into terrestrial environments.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335749;


		
		

		
			
			p.question = "Alternation of generations _____. (<script type=\"text/javascript\">ebook(\'2901\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "is unique to plants",
				false,
				"No. Some algae exhibit this type of life cycle.");
			
				p.addAnswer(2, "is distinguished by a unicellular haploid stage and a multicellular diploid generation",
				false,
				"No. This is not the life cycle in the alternation of generations.");
			
				p.addAnswer(3, "consists of a diploid gametophyte stage alternating with a haploid sporophyte stage",
				false,
				"No. The gametophyte is haploid and the sporophyte is diploid.");
			
				p.addAnswer(4, "is distinguished by haploid and diploid stages that are both multicellular",
				true,
				"Correct. This is what distinguishes alternation of generations from the condition common to all sexually reproducing organisms that have haploid and diploid conditions.");
			
				p.addAnswer(5, "cycles between homomorphic stages in extant plants",
				false,
				"No. The generations have different forms, but they are heteromorphic.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335750;


		
		

		
			
			p.question = "Plants undergo alternation of generations in which _____. (<script type=\"text/javascript\">ebook(\'2901\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the sporophyte generation alternates with the gametophyte generation",
				true,
				"Correct. The life cycles of all plants include a gametophyte (or haploid generation) that alternates with a sporophyte (or diploid) generation.");
			
				p.addAnswer(2, "the vascular generation alternates with the nonvascular generation",
				false,
				"No. This plant trait does not alternate between generations.");
			
				p.addAnswer(3, "male plants alternate with female plants",
				false,
				"No. The life cycles of all plants include a gametophyte (or haploid generation) that alternates with a sporophyte (or diploid) generation.");
			
				p.addAnswer(4, "antheridia alternate with archegonia",
				false,
				"No. The life cycles of all plants include a gametophyte (or haploid) generation that alternates with a sporophyte (or diploid) generation.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. Only one of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335751;


		
		

		
			
			p.question = "Gametangia are_____. (<script type=\"text/javascript\">ebook(\'2901\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "single-celled in algae, multicellular in most plants",
				true,
				"Correct. Most plants possess multicellular sex organs called gametangia. The gametangia of algae are single-celled. Plants\' gametangia have a layer of protective cells that protect the gametes. After fertilization, the fertilized egg develops into an embryo within the female gametangia of plants. In algae, the fertilized eggs develop away from the gametangia. In some algae, the gametes are released prior to fertilization.");
			
				p.addAnswer(2, "multicellular in algae, single-celled in most plants",
				false,
				"No. Most plants possess multicellular sex organs; algae gametangia are single-celled.");
			
				p.addAnswer(3, "responsible for the plant\'s ability to retain moisture in arid environments",
				false,
				"No. The plant has numerous other adaptations that promote water conservation.");
			
				p.addAnswer(4, "the site of development of the fertilized egg in algae",
				false,
				"No. This is true of most plants.");
			
				p.addAnswer(5, "structures specialized for gradual spore discharge",
				false,
				"No. This describes a structure called a peristome.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335752;


		
		

		
			
			p.question = "_____ protect(s) pollen grains from environmental damage. (<script type=\"text/javascript\">ebook(\'2901\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "tannins",
				false,
				"No. Tannins are compounds that are noxious and toxic to herbivores and, therefore, protect plants from excessive herbivory.");
			
				p.addAnswer(2, "sporopollenin",
				true,
				"Correct. Sporopollenin, found in the coverings of pollen grains, resists environmental damage.");
			
				p.addAnswer(3, "lignin",
				false,
				"No. Lignin reinforces the cell walls of woody tissues.");
			
				p.addAnswer(4, "cuticles",
				false,
				"No. The cuticle is the water-resistant covering of leaves.");
			
				p.addAnswer(5, "stomata",
				false,
				"No. Stomata are pores in the surfaces of leaves that allow for the exchange of gas.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335753;


		
		

		
			
			p.question = "Which is a key difference between alternation of generations in plants and sexual reproduction in non-plant organisms? (<script type=\"text/javascript\">ebook(\'2901\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "In plants, the haploid and diploid stages are both multicellular.",
				true,
				"Correct. The life cycle of humans, for example, includes a single-celled haploid stage and a multicellular diploid stage.");
			
				p.addAnswer(2, "In plants, only the haploid stage is multicellular.",
				false,
				"No. In plants, both stages are multicellular.");
			
				p.addAnswer(3, "In plants, the haploid generation is always dependent on the diploid generation.",
				false,
				"No. In bryophytes, the diploid generation is dependent on the haploid generation.");
			
				p.addAnswer(4, "In other sexually reproducing organisms, the haploid and diploid generations are both multicellular.",
				false,
				"No. The life cycle of humans, for example, includes a single-celled haploid stage and a multicellular diploid stage.");
			
				p.addAnswer(5, "In other sexually reproducing organisms, the fusion of gametes forms a zygote before an embryo.",
				false,
				"No. This also occurs in plants.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335754;


		
		

		
			
			p.question = "The development of the _____ prevents plants from drying out and protects them from microbes. (<script type=\"text/javascript\">ebook(\'2901\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "cuticle",
				true,
				"Correct. The waxy cuticle, which is not found in algae, gives the aerial portion of the plant protection from desiccation.");
			
				p.addAnswer(2, "apical meristem",
				false,
				"No. This is a type of plant tissue in the tips of roots and buds of shoots that generates new cells for lengthwise growth.");
			
				p.addAnswer(3, "gametangia",
				false,
				"No. These are gamete-producing structures.");
			
				p.addAnswer(4, "terpene",
				false,
				"No. Terpene is a chemical produced by plants that deters herbivores.");
			
				p.addAnswer(5, "flavonoid",
				false,
				"No. Flavonoids absorb ultraviolet radiation and act as signals in symbiotic relationships.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335755;


		
		

		
			
			p.question = "Which example below is a clade of nonvascular plants? (<script type=\"text/javascript\">ebook(\'2901\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "lycophytes",
				false,
				"No. Lycophytes, which include the club mosses and relatives, are a clade of vascular plants.");
			
				p.addAnswer(2, "pterophytes",
				false,
				"No. Pterophytes, which include the ferns, are a clade of vascular plants.");
			
				p.addAnswer(3, "seed plants",
				false,
				"No. Seed plants are vascular plants.");
			
				p.addAnswer(4, "bryophytes",
				true,
				"Correct. Bryophytes, including the mosses, are nonvascular plants.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. Bryophytes, including the mosses, are nonvascular plants.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335756;


		
		

		
			
			p.question = "Which term is most nearly synonymous with <b>land plants</b>? (<script type=\"text/javascript\">ebook(\'2901\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "tracheophytes",
				false,
				"No. The tracheophytes are all of the vascular land plants.");
			
				p.addAnswer(2, "vascular plants",
				false,
				"No. Many land plants are not vascular plants.");
			
				p.addAnswer(3, "seed plants",
				false,
				"No. Seed plants include only the gymnosperms and angiosperms.");
			
				p.addAnswer(4, "embryophytes",
				true,
				"Correct. All land plants include a multicellular embryo protected within a set of sterile cells.");
			
				p.addAnswer(5, "photoautotrophs",
				false,
				"No. This term also applies to some bacteria.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335757;


		
		

		
			
			p.question = "A major division in plant systematics is based on whether a particular species has _______. (<script type=\"text/javascript\">ebook(\'2901\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "sporopollenin",
				false,
				"No. Sporopollenin is common in all plants.");
			
				p.addAnswer(2, "apical meristems",
				false,
				"No. Apical meristems are common in all plants.");
			
				p.addAnswer(3, "vascular tissue",
				true,
				"Correct. The major branch point is plant systematics occurs between vascular and nonvascular plants.");
			
				p.addAnswer(4, "gametophytes",
				false,
				"No. Gametophytes are found in all plants.");
			
				p.addAnswer(5, "alternation of generations",
				false,
				"No. All plants exhibit alternation of generations.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335758;


		
		

		
			
			p.question = "The gametophyte stage of the plant life cycle is most conspicuous in _____. (<script type=\"text/javascript\">ebook(\'2902\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "ferns",
				false,
				"No. The sporophyte is the conspicuous stage of the ferns.");
			
				p.addAnswer(2, "mosses",
				true,
				"Correct. They have a dominant gametophyte.");
			
				p.addAnswer(3, "horsetails",
				false,
				"No. The sporophyte is the dominant stage.");
			
				p.addAnswer(4, "quillworts",
				false,
				"No. The sporophyte is the dominant stage.");
			
				p.addAnswer(5, "seed plants",
				false,
				"No. In seed plants the sporophyte is the dominant stage.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335759;


		
		

		
			
			p.question = "When you see a green, \"leafy\" moss, you are looking at the _____. (<script type=\"text/javascript\">ebook(\'2902\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "spore-producing structure",
				false,
				"No. The leafy gametophyte is the prevalent generation in the bryophyte life cycle, in contrast with the life cycle of other plants.");
			
				p.addAnswer(2, "sporophyte generation",
				false,
				"No. The leafy gametophyte is the prevalent generation in the bryophyte life cycle, in contrast with the life cycle of other plants.");
			
				p.addAnswer(3, "gametophyte generation",
				true,
				"Correct. The leafy gametophyte is the prevalent generation in the bryophyte life cycle, in contrast with the life cycle of other plants.");
			
				p.addAnswer(4, "structure where meiosis occurs",
				false,
				"No. The leafy gametophyte is the prevalent generation in the bryophyte life cycle. Meiosis occurs in the sporophyte.");
			
				p.addAnswer(5, "structure that results directly from a fertilized egg",
				false,
				"No. The leafy gametophyte is the prevalent generation in the bryophyte life cycle. A fertilized egg develops into a sporophyte.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335760;


		
		

		
			
			p.question = "Rhizoids _____. (<script type=\"text/javascript\">ebook(\'2902\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "are found in liverworts and hornworts, but not in mosses",
				false,
				"No. Although their structures vary, rhizoids are found in all types of bryophytes.");
			
				p.addAnswer(2, "play a primary role in water and mineral absorption",
				false,
				"No. This is the main role of roots in vascular plants.");
			
				p.addAnswer(3, "contain specialized conducting cells",
				false,
				"No. This is true of roots in vascular plants.");
			
				p.addAnswer(4, "anchor the gametophytes of bryophytes",
				true,
				"Correct. Bryophyte gametophytes are anchored by delicate rhizoids&#151;long tubular single cells in liverworts and hornworts or filaments of cells in mosses.");
			
				p.addAnswer(5, "have tissues in their centers that allow some mosses to grow up to 2 m tall",
				false,
				"No. This is true of \"stems\" in some types of mosses.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335761;


		
		

		
			
			p.question = "Which of the following produce eggs and sperm? (<script type=\"text/javascript\">ebook(\'2902\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "megaphylls",
				false,
				"No. Megaphylls are leaves with a highly branched vascular system.");
			
				p.addAnswer(2, "fern sporophytes",
				false,
				"No. They produce spores.");
			
				p.addAnswer(3, "moss gametophytes",
				true,
				"Correct. They produce gametes: eggs and/or sperm.");
			
				p.addAnswer(4, "megaspores",
				false,
				"No. Megaspores are spores that develop into female gametophytes.");
			
				p.addAnswer(5, "moss sporangia",
				false,
				"No. They produce spores.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335762;


		
		

		
			
			p.question = "Fertilization in moss occurs when sperm swim from a(n) _____ and down the neck of a(n) _____. (<script type=\"text/javascript\">ebook(\'2902\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "antheridium; sporangium",
				false,
				"No. However, this choice is partially correct.");
			
				p.addAnswer(2, "sporangium; antheridium",
				false,
				"No. Sporangia produce spores.");
			
				p.addAnswer(3, "antheridium; archegonium",
				true,
				"Correct. A sperm, produced in the antheridium, swims through a film of moisture to an archegonium and fertilizes the egg.");
			
				p.addAnswer(4, "archegonium; antheridium",
				false,
				"No. A sperm, produced in the antheridium, swims through a film of moisture to an archegonium and fertilizes the egg.");
			
				p.addAnswer(5, "sporangium; archegonium",
				false,
				"No. However, this choice is partially correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335763;


		
		

		
			
			p.question = "The gametophyte generation of a moss _____. (<script type=\"text/javascript\">ebook(\'2902\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "produces spores",
				false,
				"No. Spores are produced by the sporophyte generation.");
			
				p.addAnswer(2, "is dependent on the sporophyte",
				false,
				"No. In mosses the sporophyte is dependent on the gametophyte.");
			
				p.addAnswer(3, "has tracheids, but no vessel elements",
				false,
				"No. Mosses do not have either of these features.");
			
				p.addAnswer(4, "is haploid",
				true,
				"Correct. The leafy haploid gametophyte is the prevalent generation in the bryophyte (moss) life cycle, in contrast with the life cycle of other plants.");
			
				p.addAnswer(5, "is rarely encountered, compared with the sporophyte",
				false,
				"No. The sporophyte generation is the prominent generation in a bryophyte life cycle. Sporophytes are dependent on gametophytes.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335764;


		
		

		
			
			p.question = "How are gametes produced by bryophytes? (<script type=\"text/javascript\">ebook(\'2902\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "by mitosis of gametophyte cells",
				true,
				"Correct. The haploid gametophyte produces gametes by mitosis.");
			
				p.addAnswer(2, "by meiosis of gametophyte cells",
				false,
				"No. Gametophytes are haploid.");
			
				p.addAnswer(3, "by meiosis of sporophyte cells",
				false,
				"No. This results in the production of spores.");
			
				p.addAnswer(4, "by mitosis of spores",
				false,
				"No. The haploid gametophyte produces gametes by mitosis.");
			
				p.addAnswer(5, "by meiosis of spores",
				false,
				"No. The haploid gametophyte produces gametes by mitosis.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335765;


		
		

		
			
			p.question = "In mosses, haploid _____ directly produce buds that grow into gametophores. (<script type=\"text/javascript\">ebook(\'2902\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "archegonia",
				false,
				"No. Archegonia produce eggs.");
			
				p.addAnswer(2, "antheridia",
				false,
				"No. Antheridia produce sperm.");
			
				p.addAnswer(3, "spores",
				false,
				"No. Spores germinate by mitotic division, forming small, green, threadlike protonemata that eventually form buds.");
			
				p.addAnswer(4, "protonemata",
				true,
				"Correct. Spores germinate by mitotic division, forming small, green, threadlike haploid protonemata that eventually form buds that become gametophores.");
			
				p.addAnswer(5, "gametophores",
				false,
				"No. Together, a protonema and gametophore make up the body of a moss gametophyte.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335766;


		
		

		
			
			p.question = "Which structure of a bryophyte sporophyte is specialized for gradual spore discharge? (<script type=\"text/javascript\">ebook(\'2902\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "seta",
				false,
				"No. The seta conducts nutrients to the sporangium for the production of spores.");
			
				p.addAnswer(2, "calyptra",
				false,
				"No. This is a cap of protective tissue found on an immature capsule.");
			
				p.addAnswer(3, "peristome",
				true,
				"Correct. In most moss species, the upper part of the capsule has a ring of teeth known as the peristome, which is specialized for gradual spore discharge.");
			
				p.addAnswer(4, "stomata",
				false,
				"No. Stomata are pores found in leaves that allow for gas exchange.");
			
				p.addAnswer(5, "foot",
				false,
				"No. A foot is embedded in the archegonium and absorbs nutrients from the gametophyte.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335767;


		
		

		
			
			p.question = "Which structure of a bryophyte sporophyte serves as a protective cap on an immature capsule? (<script type=\"text/javascript\">ebook(\'2902\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "seta",
				false,
				"No. The seta conducts nutrients to the sporangium for the production of spores.");
			
				p.addAnswer(2, "calyptra",
				true,
				"Correct. The calyptra is a cap of protective tissue found on an immature capsule. The cap is shed when the capsule is ready to release spores.");
			
				p.addAnswer(3, "peristome",
				false,
				"No. The upper part of the capsule has a ring of teeth known as the peristome, which is specialized for gradual spore discharge.");
			
				p.addAnswer(4, "stomata",
				false,
				"No. Stomata are pores found in leaves that allow for gas exchange.");
			
				p.addAnswer(5, "foot",
				false,
				"No. A foot is embedded in the archegonium and absorbs nutrients from the gametophyte.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335768;


		
		

		
			
			p.question = "What structures allow plants to readily take up carbon dioxide from the atmosphere? (<script type=\"text/javascript\">ebook(\'2902\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "stomata",
				true,
				"Correct. Because plants are covered with a waxy cuticle, diffusion of carbon dioxide into the leaf interior must be facilitated through stomata, tiny pores that allow for gas exchange.");
			
				p.addAnswer(2, "cuticles",
				false,
				"No. Cuticles are a waterproof layer.");
			
				p.addAnswer(3, "gametangia",
				false,
				"No. Gametangia produce gametes.");
			
				p.addAnswer(4, "mitochondria",
				false,
				"No. Mitochondria produce carbon dioxide as a waste product of cellular respiration.");
			
				p.addAnswer(5, "capsules",
				false,
				"No. This is another term for sporangium, where spores are produced by meiosis.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335769;


		
		

		
			
			p.question = "<i>Sphagnum</i> is a _____ that forms extensive deposits of undecayed organic material. (<script type=\"text/javascript\">ebook(\'2902\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "liverwort",
				false,
				"No. However, it is a bryophyte.");
			
				p.addAnswer(2, "club moss",
				false,
				"No. <i>Sphagnum</i> is nonvascular.");
			
				p.addAnswer(3, "moss",
				true,
				"Correct. Deposits of undecayed organic material are known as peat.");
			
				p.addAnswer(4, "quillwort",
				false,
				"No. <i>Sphagnum</i> is nonvascular.");
			
				p.addAnswer(5, "lycophyte",
				false,
				"No. <i>Sphagnum</i> is nonvascular.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335770;


		
		

		
			
			p.question = "In the life cycle of a fern, the multicellular male gametangium (the sex organ that produces sperm cells) is called a(n) _____. (<script type=\"text/javascript\">ebook(\'2903\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "antheridium",
				true,
				"Correct. The male gametangium (the sex organ that produces male gametes, or sperm) is called an antheridium.");
			
				p.addAnswer(2, "archegonium",
				false,
				"No. An archegonium is a female structure.");
			
				p.addAnswer(3, "frond",
				false,
				"No. Fern leaves are called fronds.");
			
				p.addAnswer(4, "rhizome",
				false,
				"No. A rhizome is an underground structure.");
			
				p.addAnswer(5, "sporangium",
				false,
				"No. A sporangium produces spores.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335771;


		
		

		
			
			p.question = "In the life cycle of ferns, the multicellular female gametangium (the sex organ that contains an egg) is a(n) _____. (<script type=\"text/javascript\">ebook(\'2903\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "antheridium",
				false,
				"No. The antheridium is a male structure.");
			
				p.addAnswer(2, "archegonium",
				true,
				"Correct. The female gametangium (the sex organ that produces female gametes, or eggs) is called an archegonium.");
			
				p.addAnswer(3, "frond",
				false,
				"No. Fern leaves are called fronds.");
			
				p.addAnswer(4, "rhizome",
				false,
				"No. A rhizome is an underground structure.");
			
				p.addAnswer(5, "sporangium",
				false,
				"No. A sporangium produces spores.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335772;


		
		

		
			
			p.question = "Ferns and mosses are limited mostly to moist environments because _____. (<script type=\"text/javascript\">ebook(\'2903\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "their pollen is carried by water",
				false,
				"No. They do not produce pollen.");
			
				p.addAnswer(2, "they lack cuticles and stomata",
				false,
				"No. Many have those structures.");
			
				p.addAnswer(3, "they lack vascular tissue",
				false,
				"No. Although mosses lack vascular tissue, ferns do have vascular tissue.");
			
				p.addAnswer(4, "they have swimming sperm",
				true,
				"Correct. Both types of plants have flagellated sperm.");
			
				p.addAnswer(5, "their seeds do not store water",
				false,
				"No. Neither type of plant produces seeds.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335773;


		
		

		
			
			p.question = "What is the evolutionary significance of megaphylls? (<script type=\"text/javascript\">ebook(\'2903\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "They increase the surface area for photosynthesis.",
				true,
				"Correct. Megaphylls are leaves. They provide a large surface area to maximize photosynthesis.");
			
				p.addAnswer(2, "They are modified leaves that have sporangia.",
				false,
				"No. Sporophylls are modified leaves that have sporangia.");
			
				p.addAnswer(3, "They allow plants to grow taller.",
				false,
				"No. Lignified vascular tissue allows plants to grow taller.");
			
				p.addAnswer(4, "They provide a way to transport water and nutrients throughout the plant\'s body.",
				false,
				"No. Vascular tissue provides transport of water and nutrients throughout a plant\'s body.");
			
				p.addAnswer(5, "They increase the surface area for absorption of nutrients.",
				false,
				"No. Roots are used for absorption of nutrients.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335774;


		
		

		
			
			p.question = "The \"dots\" on the underside of a fern frond are spore cases; therefore, what is true of the plant to which the frond belongs? (<script type=\"text/javascript\">ebook(\'2903\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "It is a spore.",
				false,
				"No. Plants produce spores.");
			
				p.addAnswer(2, "It is a gamete.",
				false,
				"No. Plants produce gametes.");
			
				p.addAnswer(3, "It is a sporophyte.",
				true,
				"Correct. The spots on the underside of reproductive leaves are sori, which release spores, indicating the parent plant is a sporophyte, or spore-producing organism.");
			
				p.addAnswer(4, "It is a gametophyte.",
				false,
				"No. Gametophytes produce gametes.");
			
				p.addAnswer(5, "It is a spermatophyte.",
				false,
				"No. The spots on the underside of reproductive leaves are sori, which release spores, indicating the parent plant is a sporophyte, or spore-producing organism.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335775;


		
		

		
			
			p.question = "Where would you find a fern gametophyte? (<script type=\"text/javascript\">ebook(\'2903\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "on the underside of the leaf (frond)",
				false,
				"No. This is where you would find sori.");
			
				p.addAnswer(2, "attached to the underground stem (rhizoids)",
				false,
				"No. Rhizoids are found in bryophytes.");
			
				p.addAnswer(3, "in a freshwater stream",
				false,
				"No. The small heart-shaped gametophytes grow on or just below the soil level in moist areas.");
			
				p.addAnswer(4, "on moist soil",
				true,
				"Correct. Fern sperm use flagella to swim through moisture to fertilize the egg. The small heart-shaped gametophyte grows on or just below the soil level in moist areas.");
			
				p.addAnswer(5, "inside a dissected seed",
				false,
				"No. Ferns are seedless plants. The small heart-shaped gametophyte grows on or just below the soil level in moist areas.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335776;


		
		

		
			
			p.question = "Fern gametophytes are _____. (<script type=\"text/javascript\">ebook(\'2903\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "photosynthetic diploid organisms",
				false,
				"No. Gametophytes are haploid.");
			
				p.addAnswer(2, "produced from haploid gametes",
				false,
				"No. Gametophytes produce gametes.");
			
				p.addAnswer(3, "part of the asexual life cycle",
				false,
				"No. Gametophytes are involved in sexual reproduction.");
			
				p.addAnswer(4, "free-living, multicellular organisms",
				true,
				"Correct. Ferns produce small heart-shaped gametophytes that sustain themselves by photosynthesis and produce haploid gametes.");
			
				p.addAnswer(5, "found on the underside of fern leaves (fronds)",
				false,
				"No. This is where sori are found.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335777;


		
		

		
			
			p.question = "To examine meiosis in ferns, you would study _____. (<script type=\"text/javascript\">ebook(\'2903\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the antheridia",
				false,
				"No. Antheridia produce sperm.");
			
				p.addAnswer(2, "the archegonia",
				false,
				"No. Archegonia produce eggs.");
			
				p.addAnswer(3, "the sporangia",
				true,
				"Correct. The mature diploid sporophyte produces haploid spores by meiosis. These spores are encased in sporangia.");
			
				p.addAnswer(4, "both the antheridia and the archegonia",
				false,
				"No. The mature diploid sporophyte produces haploid spores by meiosis. These spores are encased in sporangia.");
			
				p.addAnswer(5, "both the archegonia and the sporangia",
				false,
				"No. The mature diploid sporophyte produces haploid spores by meiosis. These spores are encased in sporangia.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335778;


		
		

		
			
			p.question = "Vascular tissues of plants include _____. (<script type=\"text/javascript\">ebook(\'2903\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "xylem for conducting water and minerals, and phloem for conducting dissolved organic molecules",
				true,
				"Correct. Vascular tissues include xylem for conducting water and minerals, and phloem for conducting organic molecules like sugars. Lignin is a strengthening polymer found in the walls of cells that support and conduct.");
			
				p.addAnswer(2, "xylem for conducting organic molecules, and phloem for conducting water and minerals",
				false,
				"No. You are right about the tissues but wrong about the functions of each tissue.");
			
				p.addAnswer(3, "lignin for conducting organic molecules, and phloem for conducting sugars",
				false,
				"No. Although phloem does conduct sugars, lignin plays a role in structural support.");
			
				p.addAnswer(4, "phloem for conducting water and minerals, and lignin for conducting organic molecules",
				false,
				"No. Xylem conducts water and minerals. Lignin is involved in structural support.");
			
				p.addAnswer(5, "cuticles for conducting water, and phloem for conducting organic molecules",
				false,
				"No. Cuticles protect against water loss; they are not vascular.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335779;


		
		

		
			
			p.question = "Heterosporous plants produce _____. (<script type=\"text/javascript\">ebook(\'2903\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "megaspores that develop into female gametophytes and microspores that develop into male gametophytes",
				true,
				"Correct. Notice that the female is larger than the male.");
			
				p.addAnswer(2, "megaspores that develop into male gametophytes and microspores that develop into female gametophytes",
				false,
				"No. Heterosporous plants do produce megaspores and microspores, but megaspores develop into female gametophytes and microspores develop into male gametophytes.");
			
				p.addAnswer(3, "megaspores that bear antheridia and microspores that bear archegonia",
				false,
				"No. Megaspores bear archegonia, and microspores bear antheridia.");
			
				p.addAnswer(4, "spores that produce both archegonia and antheridia",
				false,
				"No. Such plants are homosporous.");
			
				p.addAnswer(5, "seeds",
				false,
				"No. Heterosporous plants include the seedless lycophytes. Some lycophytes are heterosporous.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335780;


		
		

		
			
			p.question = "Sori can be found in which of the following? (<script type=\"text/javascript\">ebook(\'2903\',\'quiz\')</script>)";
			p.incorrect_any_expl = "No. Sori are the small structures under leaf fronds from which spores are released.";
			p.incorrect_any_expl_flag = 1;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "mosses",
				false,
				"");
			
				p.addAnswer(2, "liverworts",
				false,
				"");
			
				p.addAnswer(3, "hornworts",
				false,
				"");
			
				p.addAnswer(4, "pterophytes",
				true,
				"Correct. Sori are the small structures under leaf fronds from which spores are released.");
			
				p.addAnswer(5, "charophyceans",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335781;


		
		

		
			
			p.question = "In sporophyte ferns, the leaves are _____. (<script type=\"text/javascript\">ebook(\'2903\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "megaphylls",
				true,
				"Correct. Many ferns have leaves, commonly called fronds, that are subdivided into leaflets.");
			
				p.addAnswer(2, "microphylls",
				false,
				"No. The leaves of sporophyte ferns are megaphylls.");
			
				p.addAnswer(3, "thalli",
				false,
				"No. The photosynthetic portion of a fern gametophyte is a thallus.");
			
				p.addAnswer(4, "sporangia",
				false,
				"No. Sporangia produce spores.");
			
				p.addAnswer(5, "blades",
				false,
				"No. Kelps have photosynthetic organs known as blades.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335782;


		
		

		
			
			p.question = "The first large forests formed in the Carboniferous Period. The drawdown of CO<sub>2</sub> levels by all of these plants caused _______. (<script type=\"text/javascript\">ebook(\'2903\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "global warming",
				false,
				"No. Removing CO<sub>2</sub> from the atmosphere would lessen the greenhouse effect and cool the atmosphere.");
			
				p.addAnswer(2, "A lack of CO<sub>2</sub> for photosynthesis.",
				false,
				"No. Although there is evidence that CO<sub>2</sub> levels were decreased significantly, there was still enough CO<sub>2</sub> for effective photosynthesis to continue.");
			
				p.addAnswer(3, "global cooling",
				true,
				"Correct. The drawdown of CO<sub>2</sub> by plants during the Carboniferous is believed to have been the cause of an ice age.");
			
				p.addAnswer(4, "the formation of fewer stomata in plant leaves",
				false,
				"No. A decrease in CO<sub>2</sub> levels would cause an increase in the number of stomata in plant leaves.");
			
				p.addAnswer(5, "seed plants to become the dominant types of plants on Earth",
				false,
				"No. There is no evidence that the drop in CO<sub>2</sub> levels caused seed plants to rise in prominence.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

