

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "Investigation Quiz > What Tells Desert Seeds When to Germinate?";
	ak.quiz_loc_with_commas = "Investigation Quiz, What Tells Desert Seeds When to Germinate?";
	ak.quiz_title = "What Tells Desert Seeds When to Germinate?";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 10;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 10;
	ak.non_essay_total = 0;
	ak.scored_item_total = 0;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337786;


		
		

		
			p.question = "List two possible environmental events that might have triggered seed germination and growth into wildflowers.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337787;


		
		

		
			p.question = "In a few brief sentences, summarize what you learned from the old man.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337788;


		
		

		
			p.question = "What did you learn from the herbarium about your yellow-flowered plant?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337789;


		
		

		
			p.question = "If temperature is a signal that causes <i>Pectis</i> seeds to germinate, what temperature treatments will make the seeds germinate in the laboratory? Give your reasoning.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337790;


		
		

		
			p.question = "From the rain graph and the old man\'s comments, explain why it\'s clear that rainfall alone won\'t tell <i>Pectis</i> to germinate, and name another signal that may be involved. If necessary, use the \"Return to Resources\" button to review the old man\'s words.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337791;


		
		

		
			p.question = "(a) What do you conclude from the shower experiment? (b) Does the shower experiment support that idea that <i>Pectis</i> measures only the <u>amount</u> of rainfall delivered, and not how long it remains? Explain. (c) Why might drainage be necessary?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337792;


		
		

		
			p.question = "(a) You\'ve read that rain might cause seeds to make a germination promoter. Write an alternative idea of your own. (b) Show how each of the ideas can explain the effect of drainage on germination.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337793;


		
		

		
			p.question = "(a) Write a detailed plan for an experiment that uses wash water from one set of seeds to tell how rainfall causes another set of seeds to germinate. Think carefully, for your plan must eliminate one of the two rival hypotheses. (b) Explain how your experiment will eliminate one of the two hypotheses.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337794;


		
		

		
			p.question = "(a) Does the wash-water experiment favor the idea that rain washes inhibitors out of the seeds or soil? Why or why not? (b) Does the experiment favor the idea that rain causes seeds to make promoters? Why or why not? (c) Why did some seeds sprout in the pot that got wash water? Offer one possibility.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337795;


		
		

		
			p.question = "What benefit might <i>Pectis</i> gain by germinating and flowering in the hottest part of summer, instead of waiting until the cooler days of winter?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

