

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "10: Photosynthesis > Activities Quiz";
	ak.quiz_loc_with_commas = "10: Photosynthesis, Activities Quiz";
	ak.quiz_title = "Activities Quiz";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 19;
	ak.non_essay_total = 19;
	ak.scored_item_total = 19;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334598;


		
		

		
			
			p.question = "Identify the chloroplast. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?10&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Sites of Photosynthesis</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/1001q.jpg\" ALT=\"Question #1\" BORDER=\"1\" >";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A",
				true,
				"This is a chloroplast.");
			
				p.addAnswer(2, "B",
				false,
				"This is the cytoplasm.");
			
				p.addAnswer(3, "C",
				false,
				"This is the nucleus.");
			
				p.addAnswer(4, "D",
				false,
				"This is the plasma membrane.");
			
				p.addAnswer(5, "E",
				false,
				"This is the cell wall.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334599;


		
		

		
			
			p.question = "Identify the stroma. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?10&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Sites of Photosynthesis</a>)<br><br><IMG SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/1002q.jpg\" ALT=\"Question #2\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A",
				false,
				"This is the chloroplast\'s outer membrane.");
			
				p.addAnswer(2, "B",
				false,
				"This is the chloroplast\'s inner membrane.");
			
				p.addAnswer(3, "C",
				false,
				"This is a granum.");
			
				p.addAnswer(4, "D",
				false,
				"This is a thylakoid.");
			
				p.addAnswer(5, "E",
				true,
				"This is the stroma.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334600;


		
		

		
			
			p.question = "Identify a thylakoid. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?10&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Sites of Photosynthesis</a>)<br><br><IMG SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/1003q.jpg\" ALT=\"Question #3\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A",
				false,
				"This is the chloroplast\'s outer membrane.");
			
				p.addAnswer(2, "B",
				false,
				"This is the chloroplast\'s inner membrane.");
			
				p.addAnswer(3, "C",
				false,
				"This is a granum.");
			
				p.addAnswer(4, "D",
				true,
				"This is a thylakoid.");
			
				p.addAnswer(5, "E",
				false,
				"This is the stroma.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334601;


		
		

		
			
			p.question = "Which of these equations best summarizes photosynthesis? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?10&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Overview of Photosynthesis</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "C<sub>6</sub>H<sub>12</sub>O<sub>6</sub> + 6 O<sub>2</sub> &rarr; 6 CO<sub>2</sub> + 12 H<sub>2</sub>O",
				false,
				"This is not a balanced equation.");
			
				p.addAnswer(2, "C<sub>6</sub>H<sub>12</sub>O<sub>6</sub> + 6 O<sub>2</sub> &rarr; 6 CO<sub>2</sub> + 6 H<sub>2</sub>O + Energy",
				false,
				"This summarizes the breakdown (cellular respiration) of glucose.");
			
				p.addAnswer(3, "6 CO<sub>2</sub> + 6 O<sub>2</sub> &rarr; C<sub>6</sub>H<sub>12</sub>O<sub>6</sub> + 6 H<sub>2</sub>O",
				false,
				"This equation does not make sense.");
			
				p.addAnswer(4, "6 CO<sub>2</sub> + 6 H<sub>2</sub>O &rarr; C<sub>6</sub>H<sub>12</sub>O<sub>6</sub> + 6 O<sub>2</sub>",
				true,
				"This is the equation that summarizes the reactions of photosynthesis.");
			
				p.addAnswer(5, "H<sub>2</sub>O &rarr; 2 H<sup>+</sup> + 1/2 O<sub>2</sub> + 2<i>e<sup>-</sup><i>",
				false,
				"This describes the photolysis of water.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334602;


		
		

		
			
			p.question = "Where does the Calvin cycle occur?  (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?10&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Overview of Photosynthesis</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/1005q.jpg\" ALT=\"Question #5\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A",
				false,
				"The Calvin cycle does not occur on a chloroplast\'s outer membrane.");
			
				p.addAnswer(2, "B",
				false,
				"The Calvin cycle does not occur on a chloroplast\'s inner membrane.");
			
				p.addAnswer(3, "C",
				false,
				"The Calvin cycle does not occur on grana.");
			
				p.addAnswer(4, "D",
				false,
				"The Calvin cycle does not occur in thylakoids.");
			
				p.addAnswer(5, "E",
				true,
				"The Calvin cycle occurs in the stroma.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334603;


		
		

		
			
			p.question = "The light reactions of photosynthesis use _____ and produce _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?10&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Overview of Photosynthesis</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "NADPH ... NADP<sup>+</sup>",
				false,
				"The light reactions use NADP<sup>+</sup>.");
			
				p.addAnswer(2, "water ... NADPH",
				true,
				"NADPH is a reactant in the Calvin cycle.");
			
				p.addAnswer(3, "carbon dioxide ... oxygen",
				false,
				"This answer is partially correct.");
			
				p.addAnswer(4, "carbon dioxide ... sugar",
				false,
				"The Calvin cycle uses carbon dioxide and produces sugar.");
			
				p.addAnswer(5, "NADPH ... oxygen",
				false,
				"This answer is partially correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334604;


		
		

		
			
			p.question = "_____ has a longer wavelength than _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?10&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Light Energy and Pigments</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Red ... green",
				true,
				"Red has a longer wavelength than green.");
			
				p.addAnswer(2, "Violet ... blue",
				false,
				"Blue has the longer wavelength.");
			
				p.addAnswer(3, "Yellow ... red",
				false,
				"Red has the longer wavelength.");
			
				p.addAnswer(4, "Green ... yellow",
				false,
				"Yellow has the longer wavelength.");
			
				p.addAnswer(5, "Blue ... green",
				false,
				"Green has the longer wavelength.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334605;


		
		

		
			
			p.question = "Which of these phosphorylates ADP to make ATP?  (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?10&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Light Reactions</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/1008q.jpg\" ALT=\"Question #8\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A",
				false,
				"This is photosystem II.");
			
				p.addAnswer(2, "B",
				false,
				"This is an electron transport chain.");
			
				p.addAnswer(3, "C",
				false,
				"This is photosystem I.");
			
				p.addAnswer(4, "D",
				false,
				"This is the thylakoid compartment.");
			
				p.addAnswer(5, "E",
				true,
				"ATP synthase phosphorylates ADP.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334606;


		
		

		
			
			p.question = "_____ releases energy that is used to pump hydrogen ions from the stroma into the thylakoid compartment. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?10&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Light Reactions</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/1009q.jpg\" ALT=\"Question #9\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A",
				false,
				"This is photosystem II.");
			
				p.addAnswer(2, "B",
				true,
				"The energy released as electrons are passed along the electron transport chain is used to pump protons into the thylakoid compartment.");
			
				p.addAnswer(3, "C",
				false,
				"This is photosystem I.");
			
				p.addAnswer(4, "D",
				false,
				"This is the thylakoid compartment.");
			
				p.addAnswer(5, "E",
				false,
				"This is ATP synthase.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334607;


		
		

		
			
			p.question = "_____ splits water into 1/2 O<sub>2</sub>, H<sup>+</sup>, and <i>e<sup>-</sup></i>. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?10&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Light Reactions</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/1010q.jpg\" ALT=\"Question #10\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A",
				true,
				"Photosystem II splits water into 1/2 O<sup>2</sup>, H<sup>+</sup>, and <i>e<sup>-</sup></i>.");
			
				p.addAnswer(2, "B",
				false,
				"This is an electron transport chain.");
			
				p.addAnswer(3, "C",
				false,
				"This is photosystem I.");
			
				p.addAnswer(4, "D",
				false,
				"This is the thylakoid compartment.");
			
				p.addAnswer(5, "E",
				false,
				"This is ATP synthase.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334608;


		
		

		
			
			p.question = "Energized electrons from ____ enter an electron transport chain and are then used to reduce NADP<sup>+</sup>. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?10&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Light Reactions</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/1011q.jpg\" ALT=\"Question #11\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A",
				false,
				"This is photosystem II.");
			
				p.addAnswer(2, "B",
				false,
				"This is an electron transport chain.");
			
				p.addAnswer(3, "C",
				true,
				"Energized electrons from photosystem I are used to reduce NADP<sup>+</sup>.");
			
				p.addAnswer(4, "D",
				false,
				"This is the thylakoid compartment.");
			
				p.addAnswer(5, "E",
				false,
				"This is ATP synthase.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334609;


		
		

		
			
			p.question = "Chlorophyll can be found in _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?10&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Light Reactions</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/1012q.jpg\" ALT=\"Question #12\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "B and D",
				false,
				"Chlorophyll is associated with neither the electron transport chain nor the thylakoid compartment.");
			
				p.addAnswer(2, "A and B",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(3, "A and C",
				true,
				"The photosystems contain chlorophyll.");
			
				p.addAnswer(4, "B and C",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(5, "B and E",
				false,
				"Chlorophyll is associated with neither the electron transport chain nor ATP synthase");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334610;


		
		

		
			
			p.question = "Carbon fixation involves the addition of carbon dioxide to _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?10&E','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Calvin Cycle</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Rubisco",
				false,
				"Rubisco catalyzes carbon fixation.");
			
				p.addAnswer(2, "RuBP",
				true,
				"In the Calvin cycle, carbon dioxide is added to RuBP.");
			
				p.addAnswer(3, "G3P",
				false,
				"G3P is formed when NADPH is oxidized.");
			
				p.addAnswer(4, "3-PGA",
				false,
				"However, 3-PGA is formed as a result of carbon fixation.");
			
				p.addAnswer(5, "NADPH",
				false,
				"No, that is incorrect.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334611;


		
		

		
			
			p.question = "After 3-PGA is phosphorylated, it is reduced by _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?10&E','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Calvin Cycle</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "NADP<sup>+</sup>",
				false,
				"NADP<sup>+</sup> is already oxidized.");
			
				p.addAnswer(2, "ADP",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(3, "CO<sub>2</sub>",
				false,
				"3-PGA is formed by the addition of carbon dioxide to RuBP.");
			
				p.addAnswer(4, "NADPH",
				true,
				"NADPH supplies the electrons that reduce the phosphorylated 3-PGA.");
			
				p.addAnswer(5, "ATP",
				false,
				"ATP phosphorylated 3-PGA.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334612;


		
		

		
			
			p.question = "How many carbon dioxide molecules must be added to RuBP to make a single molecule of glucose? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?10&E','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Calvin Cycle</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "2",
				false,
				"Consider how many carbon dioxide molecules are required to produce a single molecule of 3-PGA.");
			
				p.addAnswer(2, "4",
				false,
				"Consider how many carbon dioxide molecules are required to produce a single molecule of G3P.");
			
				p.addAnswer(3, "6",
				true,
				"Six carbon dioxide molecules are required to produce two G3P molecules, which can be combined to make one glucose molecule.");
			
				p.addAnswer(4, "8",
				false,
				"Consider how many carbon dioxide molecules are required to produce a single molecule of G3P.");
			
				p.addAnswer(5, "10",
				false,
				"Consider how many carbon dioxide molecules are required to produce a single molecule of 3-PGA.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334613;


		
		

		
			
			p.question = "In the Calvin cycle, how many ATP molecules are required to regenerate RuBP from five G3P molecules? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?10&E','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Calvin Cycle</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "1",
				false,
				"More.");
			
				p.addAnswer(2, "2",
				false,
				"More.");
			
				p.addAnswer(3, "3",
				true,
				"Correct.");
			
				p.addAnswer(4, "4",
				false,
				"Less.");
			
				p.addAnswer(5, "5",
				false,
				"Less.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334614;


		
		

		
			
			p.question = "In C<sub>3</sub> plants the conservation of water promotes _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?10&F','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Photosynthesis in Dry Climates</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "photorespiration",
				true,
				"Conserving water simultaneously reduces the amount of carbon dioxide available to the plant.");
			
				p.addAnswer(2, "the light reactions",
				false,
				"The consequence of water conservation is inhibition of the light reactions.");
			
				p.addAnswer(3, "a shift to C<sub>4</sub> photosynthesis",
				false,
				"C<sub>3</sub> plants cannot shift to C<sub>4</sub> photosynthesis.");
			
				p.addAnswer(4, "the opening of stomata",
				false,
				"Plants lose water via open stomata.");
			
				p.addAnswer(5, "photosynthesis",
				false,
				"The conservation of water results in a reduction in the rate of photosynthesis.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334615;


		
		

		
			
			p.question = "In C<sub>4</sub> and CAM plants carbon dioxide is fixed in the _____ of mesophyll cells. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?10&F','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Photosynthesis in Dry Climates</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "stoma",
				false,
				"Carbon dioxide enters the leaves via stomata.");
			
				p.addAnswer(2, "cytoplasm",
				true,
				"In C<sub>4</sub> and CAM plants carbon dioxide fixation occurs in the cytoplasm.");
			
				p.addAnswer(3, "thylakoids",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(4, "stroma",
				false,
				"In C<sub>3</sub> plants carbon dioxide fixation occurs in the stroma.");
			
				p.addAnswer(5, "grana",
				false,
				"No, that is incorrect.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334616;


		
		

		
			
			p.question = "C<sub>4</sub> plants differ from C<sub>3</sub> and CAM plants in that C<sub>4</sub> plants _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?10&F','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Photosynthesis in Dry Climates</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "open their stomata only at night",
				false,
				"In CAM plants stomata are open at night and closed during the day.");
			
				p.addAnswer(2, "are better adapted to wet conditions",
				false,
				"C<sub>4</sub> plants are better adapted to arid conditions than are C<sub>3</sub> plants.");
			
				p.addAnswer(3, "transfer fixed carbon dioxide to cells in which the Calvin cycle occurs",
				true,
				"In C<sub>3</sub> and CAM plants carbon dioxide fixation and the Calvin cycle occur in the same cells.");
			
				p.addAnswer(4, "use malic acid to transfer carbon dioxide to the Calvin cycle",
				false,
				"So do CAM plants.");
			
				p.addAnswer(5, "use PEP carboxylase to fix carbon dioxide",
				false,
				"CAM plants also use PEP carboxylase to fix carbon dioxide.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

