

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "GraphIt! Quiz > GraphIt! Quiz > Global Soil Degradation";
	ak.quiz_loc_with_commas = "GraphIt! Quiz, GraphIt! Quiz, Global Soil Degradation";
	ak.quiz_title = "Global Soil Degradation";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 6;
	ak.non_essay_total = 6;
	ak.scored_item_total = 6;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337508;


		
		

		
			
			p.question = "How big is the range of soil degradation observed between continents?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "about 7%",
				false,
				"");
			
				p.addAnswer(2, "about 15%",
				true,
				"");
			
				p.addAnswer(3, "about 22%",
				false,
				"");
			
				p.addAnswer(4, "about 50%",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337509;


		
		

		
			
			p.question = "Which continent likely represents the largest absolute land area experiencing degradation?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "South America",
				false,
				"");
			
				p.addAnswer(2, "Africa",
				false,
				"");
			
				p.addAnswer(3, "Asia",
				true,
				"");
			
				p.addAnswer(4, "North America",
				false,
				"");
			
				p.addAnswer(5, "Europe",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337510;


		
		

		
			
			p.question = "For which continents is land degradation having the least impact on global grain production?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Africa and South America",
				true,
				"");
			
				p.addAnswer(2, "Africa and Asia",
				false,
				"");
			
				p.addAnswer(3, "Asia and Europe",
				false,
				"");
			
				p.addAnswer(4, "Europe and North America",
				false,
				"");
			
				p.addAnswer(5, "North and South America",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337511;


		
		

		
			
			p.question = "Assume you are advising the UN on global soil conservation projects. If you had to select one continent, where would you recommend the UN concentrate its efforts based on the information in this graph?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Asia",
				true,
				"");
			
				p.addAnswer(2, "Africa",
				false,
				"");
			
				p.addAnswer(3, "North America",
				false,
				"");
			
				p.addAnswer(4, "Europe",
				false,
				"");
			
				p.addAnswer(5, "South America",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337512;


		
		

		
			
			p.question = "Which continent has the largest proportion of land with more than moderate degradation?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Europe",
				false,
				"");
			
				p.addAnswer(2, "North America",
				false,
				"");
			
				p.addAnswer(3, "Africa",
				true,
				"");
			
				p.addAnswer(4, "Asia",
				false,
				"");
			
				p.addAnswer(5, "South America",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337513;


		
		

		
			
			p.question = "Assume that these categories represent a progression of degradation through time. In other words, if left unchecked, lightly degraded soil progresses into moderately degraded soil and so forth. Which continent poses the greatest concern for future loss of agricultural productivity?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "South America",
				false,
				"");
			
				p.addAnswer(2, "Africa",
				false,
				"");
			
				p.addAnswer(3, "Europe",
				true,
				"");
			
				p.addAnswer(4, "North America",
				false,
				"");
			
				p.addAnswer(5, "Asia",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

