

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "Investigation Quiz > What Can Fruit Flies Reveal About Inheritance?";
	ak.quiz_loc_with_commas = "Investigation Quiz, What Can Fruit Flies Reveal About Inheritance?";
	ak.quiz_title = "What Can Fruit Flies Reveal About Inheritance?";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 8;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 8;
	ak.non_essay_total = 0;
	ak.scored_item_total = 0;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337635;


		
		

		
			p.question = "Why is it important to remove the adults in the parental generation?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337636;


		
		

		
			p.question = "What generation will their offspring be?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337637;


		
		

		
			p.question = "Based on the data obtained, is the cross in Case 1 monohybrid or dihybrid? Explain.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337638;


		
		

		
			p.question = "Is the cross in Case 1 sex-linked or autosomal? Explain.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337639;


		
		

		
			p.question = "Based on the data obtained, is the most likely mode of inheritance in Case 2 autosomal or sex-linked? Explain.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337640;


		
		

		
			p.question = "From the data presented, what is the genotype of the parental (before the F1 generation; not shown here) generation?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337641;


		
		

		
			p.question = "Determine the degrees of freedom. This is the number of categories (red eyes or sepia eyes) minus one. For the data in Case 1, what is the number of degrees of freedom?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337642;


		
		

		
			p.question = "Find the probability (p) value for 1 degree of freedom in the 0.05 row. Compare this with the chi-square value you calculated in your Lab Notebook. What can you say about the null hypothesis?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

