

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "Investigation Quiz > How Do Environmental Changes Affect a Population?";
	ak.quiz_loc_with_commas = "Investigation Quiz, How Do Environmental Changes Affect a Population?";
	ak.quiz_title = "How Do Environmental Changes Affect a Population?";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 10;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 10;
	ak.non_essay_total = 0;
	ak.scored_item_total = 0;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337516;


		
		

		
			p.question = "What role does genetics play in the variation seen in this leafhopper population?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337517;


		
		

		
			p.question = "Note the results from the 20th generation under global warming conditions. Before continuing with the 30th generation, predict the population composition of the 30th generation.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337518;


		
		

		
			p.question = "What happened to the proportion of each type of leafhopper in subsequent generations under global warming conditions? Suggest a reason why the traits of the 30th generation make this population better adapted to its altered environment.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337519;


		
		

		
			p.question = "Why would you expect a change in predators to cause a difference in the types of leafhoppers being selected?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337520;


		
		

		
			p.question = "Note the differences between the parental, 10th and 20th generations when the predator changed from a bird to a snake. What evidence supports the view that leafhopper size is not affected by a change in predators?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337521;


		
		

		
			p.question = "What happened to the proportion of each type of leafhopper in subsequent generations when the predator changed from a bird to a snake? Suggest a reason why the traits predominant in the 30th generation make this population better adapted to the change in predators.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337522;


		
		

		
			p.question = "Describe some human activities around your school that could have influenced the natural vegetation in the area.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337523;


		
		

		
			p.question = "Note the differences between the parental and the 30th generations. What happened to the proportion of each type of leafhopper when the vegetation changed? Suggest a reason why the traits of the 30th generation make this population better adapted to its altered environment.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337524;


		
		

		
			p.question = "Identify some major sources of pesticides in your area.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337525;


		
		

		
			p.question = "What happened to the proportions of leafhoppers in each subsequent generation when pesticides were added to the environment? Explain why all the leafhoppers were not killed by the pesticide application.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

