

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "GraphIt! Quiz > GraphIt! Quiz > Atmospheric CO2 and Temperature Changes";
	ak.quiz_loc_with_commas = "GraphIt! Quiz, GraphIt! Quiz, Atmospheric CO2 and Temperature Changes";
	ak.quiz_title = "Atmospheric CO2 and Temperature Changes";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 7;
	ak.non_essay_total = 7;
	ak.scored_item_total = 7;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337461;


		
		

		
			
			p.question = "Which of the following is the best statement regarding the graph of atmospheric CO<sub>2</sub> concentrations?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "There has been a catastrophic increase in atmospheric CO<sub>2</sub> concentrations over the past 50 years.",
				false,
				"");
			
				p.addAnswer(2, "Atmospheric CO<sub>2</sub> concentrations have increased by more than 100% over the past 50 years.",
				false,
				"");
			
				p.addAnswer(3, "There has been negligible change in atmospheric CO<sub>2</sub> concentrations over the past 50 years.",
				false,
				"");
			
				p.addAnswer(4, "Atmospheric CO<sub>2</sub> concentrations have increased by more than 10% over the past 50 years.",
				true,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337462;


		
		

		
			
			p.question = "Which of the following is the best statement regarding the graph of atmospheric CO<sub>2</sub> and surface temperature changes over the past 50 years?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The data demonstrates that, in spite of increases in CO<sub>2</sub> concentrations, there has only been a minimal rise in average surface temperatures.",
				false,
				"");
			
				p.addAnswer(2, "This data set is meaningless because CO<sub>2</sub> concentrations and surface temperatures are constantly fluctuating over geologic time scales.",
				false,
				"");
			
				p.addAnswer(3, "This data set represents the strongest evidence available for anthropogenic global warming.",
				false,
				"");
			
				p.addAnswer(4, "This data is consistent with the hypothesis that increased atmospheric concentrations of CO<sub>2</sub> may be causing an increase in average surface temperatures.",
				true,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337463;


		
		

		
			
			p.question = "Assume that you wanted to give the impression that, although CO<sub>2</sub> levels have indeed increased over the past 50 years, they have not had a significant impact on average surface temperatures. Which of the scales shown in Step 3 would be the best choice?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "scale 1",
				false,
				"");
			
				p.addAnswer(2, "scale 2",
				false,
				"");
			
				p.addAnswer(3, "scale 3",
				true,
				"");
			
				p.addAnswer(4, "scale 4",
				false,
				"");
			
				p.addAnswer(5, "none of the available scales",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337464;


		
		

		
			
			p.question = "For which of the scales shown in Step 3 is the increase in CO<sub>2</sub> concentrations less than 10%?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "scale 1",
				false,
				"");
			
				p.addAnswer(2, "scale 2",
				false,
				"");
			
				p.addAnswer(3, "scale 3",
				false,
				"");
			
				p.addAnswer(4, "scale 4",
				false,
				"");
			
				p.addAnswer(5, "all of the scales",
				false,
				"");
			
				p.addAnswer(6, "none of the scales",
				true,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337465;


		
		

		
			
			p.question = "Choose the list of predicted trajectories for CO<sub>2</sub> concentration that matches them in order with the aggressive, moderate, and minimal control scenarios.";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "C, B, A",
				true,
				"");
			
				p.addAnswer(2, "A, B, C",
				false,
				"");
			
				p.addAnswer(3, "C, A, B",
				false,
				"");
			
				p.addAnswer(4, "B, A, C",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337466;


		
		

		
			
			p.question = "Assuming that increasing CO<sub>2</sub> concentrations are directly linked to increased surface temperatures, which scenario should result in a reduction of temperatures to below their 1960-1990 averages by 2040?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "aggressive control",
				false,
				"");
			
				p.addAnswer(2, "moderate control",
				false,
				"");
			
				p.addAnswer(3, "minimal control",
				false,
				"");
			
				p.addAnswer(4, "all of the scenarios",
				false,
				"");
			
				p.addAnswer(5, "none of the scenarios",
				true,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337467;


		
		

		
			
			p.question = "Which of the following arguments could be made for NOT adopting an aggressive control strategy worldwide?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "It would limit the ability of developing nations to achieve the standard of living already enjoyed by developed nations.",
				false,
				"");
			
				p.addAnswer(2, "It is impossible to predict the future, and therefore we cannot know the actual impact of global climate changes.",
				false,
				"");
			
				p.addAnswer(3, "The economic costs would be too high.",
				false,
				"");
			
				p.addAnswer(4, "None of the above.",
				false,
				"");
			
				p.addAnswer(5, "All of the above.",
				true,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

