

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "34: Vertebrates and Other Chordates > Activities Quiz";
	ak.quiz_loc_with_commas = "34: Vertebrates and Other Chordates, Activities Quiz";
	ak.quiz_title = "Activities Quiz";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 11;
	ak.non_essay_total = 11;
	ak.scored_item_total = 11;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335983;


		
		

		
			
			p.question = "This phylogenetic tree indicates that mammals are most closely related to _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?34&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Characteristics of Chordates</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/3401q.jpg\" ALT=\"Question #1\" BORDER=\"1\" >";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "sharks, rays, and chimaeras",
				false,
				"This is not the group to which birds are most closely related.");
			
				p.addAnswer(2, "ray-finned fishes",
				false,
				"Take another look at the branching pattern of the phylogenetic tree.");
			
				p.addAnswer(3, "tunicates",
				false,
				"This is not the group to which birds are most closely related.");
			
				p.addAnswer(4, "reptiles",
				true,
				"The branching pattern of the phylogenetic tree clearly indicates that mammal are most closely related to reptiles.");
			
				p.addAnswer(5, "amphibians",
				false,
				"Take another look at the branching pattern of the phylogenetic tree.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335984;


		
		

		
			
			p.question = "According to this phylogenetic tree, the animals most closely related to reptiles and mammals are _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?34&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Characteristics of Chordates</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/3402q.jpg\" ALT=\"Question #2\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "sharks, rays, and chimaeras",
				false,
				"Take another look at the branching pattern of the phylogenetic tree.");
			
				p.addAnswer(2, "amphibians",
				true,
				"The branching pattern of the phylogenetic tree makes it clear that amphibians are most closely related to reptiles  and mammals.");
			
				p.addAnswer(3, "lampreys",
				false,
				"Take another look at the branching pattern of the phylogenetic tree.");
			
				p.addAnswer(4, "ray-finned  fishes",
				false,
				"Take another look at the branching pattern of the phylogenetic tree.");
			
				p.addAnswer(5, "lancelets",
				false,
				"Take another look at the branching pattern of the phylogenetic tree.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335985;


		
		

		
			
			p.question = "Which one of these chordate groups lacks a post-anal tail and a notochord as adults? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?34&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Characteristics of Chordates</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "lancelets",
				false,
				"Lancelet adults have a post-anal tail and a notochord.");
			
				p.addAnswer(2, "tunicates",
				true,
				"While larval tunicates have a post-anal tail and a notochord, adult tunicates do not.");
			
				p.addAnswer(3, "amphibians",
				false,
				"Adult amphibians have a post-anal tail and a notochord.");
			
				p.addAnswer(4, "mammals",
				false,
				"Even you have a post-anal tail.");
			
				p.addAnswer(5, "reptiles",
				false,
				"Adult reptiles have a post-anal tail and a notochord.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335986;


		
		

		
			
			p.question = "The common ancestor of all these chordate groups EXCEPT the _____ probably had paired appendages. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?34&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Characteristics of Chordates</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "mammals",
				false,
				"Mammals have paired appendages.");
			
				p.addAnswer(2, "amphibians",
				false,
				"Amphibians have paired appendages.");
			
				p.addAnswer(3, "lampreys",
				true,
				"Lampreys lack paired appendages.");
			
				p.addAnswer(4, "ray-finned fishes",
				false,
				"Ray-finned fishes have paired appendages.");
			
				p.addAnswer(5, "reptiles",
				false,
				"Reptiles  have paired appendages..");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335987;


		
		

		
			
			p.question = "Which of these is the only chordate group that has hair? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?34&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Characteristics of Chordates</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "tunicates",
				false,
				"Tunicates do not have hair.");
			
				p.addAnswer(2, "ray-finned fishes",
				false,
				"Ray-finned fishes do not have hair.");
			
				p.addAnswer(3, "mammals",
				true,
				"Hair is one of the defining characteristics of mammals.");
			
				p.addAnswer(4, "amphibians",
				false,
				"Amphibians do not have hair.");
			
				p.addAnswer(5, "sharks, rays, and chimaeras",
				false,
				"Sharks, rays, and chimaeras do not have hair.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335988;


		
		

		
			
			p.question = "Which of these primate groups is most closely related to hominids? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?34&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Primate Diversity</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "apes",
				true,
				"Apes, such as chimpanzees, are the primates most closely related to humans.");
			
				p.addAnswer(2, "Old World monkeys",
				false,
				"Another group is more closely related to humans.");
			
				p.addAnswer(3, "lorises",
				false,
				"Lorises are prosimians.");
			
				p.addAnswer(4, "prosimians",
				false,
				"Of the primates listed here, prosimians are the most distantly related to humans.");
			
				p.addAnswer(5, "New World monkeys",
				false,
				"Another group is more closely related to humans.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335989;


		
		

		
			
			p.question = "_____ are the oldest known primate group. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?34&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Primate Diversity</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Apes",
				false,
				"Another primate group evolved earlier than apes.");
			
				p.addAnswer(2, "Prosimians",
				true,
				"Prosimian fossils date back to the end of the dinosaurs.");
			
				p.addAnswer(3, "Anthropoids",
				false,
				"Another primate group evolved earlier than anthropoids.");
			
				p.addAnswer(4, "Hominids",
				false,
				"Hominids are the most recently evolved primate group.");
			
				p.addAnswer(5, "Monkeys",
				false,
				"Another primate group evolved earlier than monkeys.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335990;


		
		

		
			
			p.question = "The primates that spend the most time walking upright are the _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?34&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Primate Diversity</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "apes",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(2, "prosimians",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(3, "New World monkeys",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(4, "hominids",
				true,
				"Humans are hominids.");
			
				p.addAnswer(5, "Old World monkeys",
				false,
				"No, that is incorrect.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335991;


		
		

		
			
			p.question = "Which of these anthropoid groups consists of primates who are mostly tree dwellers and whose forelimbs and hind limbs are about equal in length? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?34&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Primate Diversity</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "monkeys",
				true,
				"In addition to these characteristics many monkeys have tails.");
			
				p.addAnswer(2, "hominids",
				false,
				"Hominids are not tree dwellers.");
			
				p.addAnswer(3, "prosimians",
				false,
				"Prosimians are not anthropoids.");
			
				p.addAnswer(4, "primates",
				false,
				"Not all primates are anthropoids.");
			
				p.addAnswer(5, "apes",
				false,
				"Apes have forelimbs that are longer than their hind limbs.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335992;


		
		

		
			
			p.question = "Which of these primate groups lives in trees in Central and South America and have nostrils that are wide open and far apart? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?34&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Primate Diversity</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "hominids",
				false,
				"Hominids are not tree dwellers.");
			
				p.addAnswer(2, "apes",
				false,
				"Apes are not tree dwellers.");
			
				p.addAnswer(3, "New World monkeys",
				true,
				"You might recall that the Western Hemisphere is also referred to as the New World.");
			
				p.addAnswer(4, "anthropoids",
				false,
				"Which group of anthropoids would be the correct answer to the question?");
			
				p.addAnswer(5, "Old World monkeys",
				false,
				"Central and South America are not a part of the Old World.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335993;


		
		

		
			
			p.question = "Humans are _______. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?34&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Human Evolution</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "<i>Australopithecus</i>",
				false,
				"<i>Australopithecus</i> is extinct.");
			
				p.addAnswer(2, "<i>Homo erectus</i>",
				false,
				"<i>Homo erectus</i> is extinct.");
			
				p.addAnswer(3, "<i>Ardipithecus</i>",
				false,
				"<i>Ardipithecus</i> is extinct.");
			
				p.addAnswer(4, "<i>Homo sapiens</i>",
				true,
				"Humans are classified as <i>Homo sapiens.</i>");
			
				p.addAnswer(5, "<i>Homo habilis</i>",
				false,
				"<i>Homo habilis</i> is extinct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

