

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "13: Meiosis and Sexual Life Cycles > Practice Test";
	ak.quiz_loc_with_commas = "13: Meiosis and Sexual Life Cycles, Practice Test";
	ak.quiz_title = "Practice Test";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 46;
	ak.non_essay_total = 46;
	ak.scored_item_total = 46;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334809;


		
		

		
			
			p.question = "How many genes are present in the human genome? (<script type=\"text/javascript\">ebook(\'1301\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "23",
				false,
				"No. The answer is much higher.");
			
				p.addAnswer(2, "46",
				false,
				"No. The answer is much higher.");
			
				p.addAnswer(3, "hundreds",
				false,
				"No. There may be thousands on a single chromosome. The answer is much higher.");
			
				p.addAnswer(4, "tens of thousands",
				true,
				"Correct. Each chromosome has hundreds or thousands of genes; the entire human genome has on the order of 20,000 to 25,000 genes.");
			
				p.addAnswer(5, "a virtually infinite number",
				false,
				"No. Although the precise number of genes in the genome is not yet known, it has been estimated by many scientists, and is certainly finite.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334810;


		
		

		
			
			p.question = "What is a locus?\n (<script type=\"text/javascript\">ebook(\'1301\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the precise location of a gene on a chromosome",
				true,
				"Correct. The location of a gene within the genome, including the identity of the particular chromosome that it maps to and its specific position on that chromosome, is called its <i>locus</i>.");
			
				p.addAnswer(2, "a structure that appears during prophase I and consists of two paired genes",
				false,
				"No. A locus is not a physical structure.");
			
				p.addAnswer(3, "the precise DNA sequence of a gene",
				false,
				"No. A locus does not refer to a DNA sequence.");
			
				p.addAnswer(4, "a type of spore made only by fungi",
				false,
				"No. A locus is a property of a gene.");
			
				p.addAnswer(5, "a cell with two chromosome sets",
				false,
				"No. This describes a diploid cell.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334811;


		
		

		
			
			p.question = "Sexual and asexual reproduction are alike in that _____.\n (<script type=\"text/javascript\">ebook(\'1301\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "they both give rise to genetically distinct offspring",
				false,
				"No. Sexual reproduction produces genetically distinct offspring, but asexual reproduction produces genetically identical offspring.");
			
				p.addAnswer(2, "they both involve two parents",
				false,
				"No. Sexual reproduction involves two parents, whereas asexual reproduction only requires one.");
			
				p.addAnswer(3, "they both require meiosis to complete the reproductive cycle",
				false,
				"No. Sexual reproduction depends on meiosis, but asexual reproduction only involves mitosis.");
			
				p.addAnswer(4, "they can both occur in multicellular organisms",
				true,
				"Correct. Examples of both sexual and asexual reproduction have been observed in multicellular organisms.");
			
				p.addAnswer(5, "in both cases, every parent transmits all of its genes to its progeny",
				false,
				"No. Although this is true of asexual reproduction, in sexual reproduction each parent only transmits half of its genes.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334812;


		
		

		
			
			p.question = "A clone is the product of _____. \n (<script type=\"text/javascript\">ebook(\'1301\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "asexual reproduction",
				false,
				"No. This answer is partially correct, but there is a better answer.");
			
				p.addAnswer(2, "sexual reproduction",
				false,
				"No. Sexual reproduction produces zygotes, not clones.");
			
				p.addAnswer(3, "mitosis",
				false,
				"No. This answer is partially correct, but there is a better answer.");
			
				p.addAnswer(4, "meiosis",
				false,
				"No. Meiosis results in gametes, which fuse to produce zygotes during sexual reproduction.");
			
				p.addAnswer(5, "The first and third answers are correct.",
				true,
				"Correct. In asexual reproduction, an organism produces genetically identical progeny, or <i>clones</i>, by mitosis.");
			
				p.addAnswer(6, "The second and fourth answers are correct.",
				false,
				"No. Neither of these is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334813;


		
		

		
			
			p.question = "Unless the chromosomes were stained to show band patterns, a karyotype would be least likely to show which of the following?\n (<script type=\"text/javascript\">ebook(\'1302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "an extra chromosome",
				false,
				"No. An extra chromosome can be detected by counting the number of chromosomes displayed.");
			
				p.addAnswer(2, "a large part of a chromosome duplicated",
				false,
				"No. By noting the size of the chromosomes you could see if extra genetic material is present.");
			
				p.addAnswer(3, "a missing chromosome",
				false,
				"No. A missing chromosome can be detected by counting the number of chromosomes.");
			
				p.addAnswer(4, "part of a chromosome turned around",
				true,
				"Correct. An inversion, which affects neither the number of chromosomes nor the length of a chromosome, is generally difficult to detect without staining to show chromosomal bands.");
			
				p.addAnswer(5, "the attachment of a large part of a chromosome to another chromosome",
				false,
				"No. This could be detected by looking at chromosomal length.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334814;


		
		

		
			
			p.question = "A karyotype is _____.\n (<script type=\"text/javascript\">ebook(\'1302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the physical traits a person has",
				false,
				"No. An individual\'s physical traits are a component of their phenotype.");
			
				p.addAnswer(2, "a method of identifying crossover events",
				false,
				"No. Karyotypes cannot be used to identify crossover events.");
			
				p.addAnswer(3, "all the possible gametes a person could produce",
				false,
				"No. This is not the purpose of producing a karyotype.");
			
				p.addAnswer(4, "a photograph of all of an individual\'s chromosomes",
				true,
				"Correct. Karyotypes, ordered displays of an individual\'s chromosomes, are useful in identifying chromosomal abnormalities.");
			
				p.addAnswer(5, "a list of all the genes a person carries",
				false,
				"No. This does not describe a karyotype.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334815;


		
		

		
			
			p.question = "Fertilization produces ___________.\n (<script type=\"text/javascript\">ebook(\'1302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a haploid zygote in some life cycles and a diploid zygote in others",
				false,
				"No. Fertilization always involves the fusion of gametes and produces a diploid zygote.");
			
				p.addAnswer(2, "a haploid zygote",
				false,
				"No. Zygotes are always diploid.");
			
				p.addAnswer(3, "a diploid zygote",
				true,
				"Correct. Fertilization always involves the fusion of gametes and produces a diploid zygote.");
			
				p.addAnswer(4, "a diploid zygote except during the gametophyte stage of alternation of generations",
				false,
				"No. The gametophyte phase culminates in the production of gametes that fuse during fertilization to produce a diploid gamete.");
			
				p.addAnswer(5, "a multicellular haploid organism in the alternation of generations life cycle",
				false,
				"No. The multicellular haploid organism that is part of the alternation of generations life cycle is a gametophyte, not a zygote.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334816;


		
		

		
			
			p.question = "Which one, if any, of the following statements is <b>true</b>?\n (<script type=\"text/javascript\">ebook(\'1302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Diploid cells can divide by mitosis.",
				false,
				"No. Diploid cells <b>can</b> undergo mitosis, but there is a better answer.");
			
				p.addAnswer(2, "Diploid cells can divide by meiosis.",
				false,
				"No. Diploid cells <b>can</b> undergo meiosis, but there is a better answer.");
			
				p.addAnswer(3, "Haploid cells can divide by mitosis.",
				false,
				"No. Haploid cells <b>can</b> undergo mitosis, but there is a better answer.");
			
				p.addAnswer(4, "Haploid cells cannot divide by meiosis.",
				false,
				"No. Haploid cells <b>cannot</b> undergo meiosis, but there is a better answer");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct. Diploid cells can divide by either mitosis or meiosis, but haploid cells can only divide by mitosis.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334817;


		
		

		
			
			p.question = "Which of the following is part of the life cycle called alternation of generations?\n (<script type=\"text/javascript\">ebook(\'1302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "multicellular haploid stage (gametophyte)",
				false,
				"No. This answer is correct, but there is a better answer.");
			
				p.addAnswer(2, "multicellular diploid stage (sporophyte)",
				false,
				"No. This answer is correct, but there is a better answer.");
			
				p.addAnswer(3, "zygote",
				false,
				"No. This answer is correct, but there is a better answer.");
			
				p.addAnswer(4, "spores",
				false,
				"No. This answer is correct, but there is a better answer.");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct. In alternation of generations, zygotes give rise to multicellular, diploid sporophytes, and spores give rise to multicellular, haploid gametophytes.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334818;


		
		

		
			
			p.question = "The sexual cycle of the multicellular algal genus <i>Fucus</i> involves _____.\n (<script type=\"text/javascript\">ebook(\'1302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "mitosis only",
				false,
				"No. <i>Fucus</i> is not limited to mitosis.");
			
				p.addAnswer(2, "both mitosis and meiosis but not fertilization",
				false,
				"No. This answer is correct, but there is a better response.");
			
				p.addAnswer(3, "both mitosis and fertilization but not meiosis",
				false,
				"No. <i>Fucus</i> is not limited to these two processes.");
			
				p.addAnswer(4, "only meiosis and fertilization",
				false,
				"No. <i>Fucus</i> is not limited to these two processes.");
			
				p.addAnswer(5, "mitosis, meiosis, and fertilization",
				true,
				"Correct. All multicellular organisms undergo mitosis, and all diploid, sexually reproducing organisms undergo meiosis and fertilization, which are complementary processes.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334819;


		
		

		
			
			p.question = "A life cycle in which the only multicellular form is haploid is most typical of _____. \n (<script type=\"text/javascript\">ebook(\'1302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "primates",
				false,
				"No. Primates, like all animals, represent a multicellular diploid form.");
			
				p.addAnswer(2, "plants",
				false,
				"No. Plants follow the life cycle called \"alternation of generations.\"");
			
				p.addAnswer(3, "fungi",
				true,
				"Correct. In most fungi, the multicellular form is haploid, and fertilization (and creation of a zygote) is immediately followed by meiosis.");
			
				p.addAnswer(4, "protists",
				false,
				"No. Protists are unicellular.");
			
				p.addAnswer(5, "fish",
				false,
				"No. Fish, like all animals, represent a multicellular diploid form.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334820;


		
		

		
			
			p.question = "Which of the following results in cells that contain half the parental chromosome number?\n (<script type=\"text/javascript\">ebook(\'1302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "cytokinesis",
				false,
				"No. Cytokinesis is division of the cytoplasm; it takes place in both mitosis and meiosis, and is not directly involved in any changes in chromosome number.");
			
				p.addAnswer(2, "mitosis",
				false,
				"No. Mitosis results in the production of daughter nuclei that contain the same number of chromosomes as the parental nucleus.");
			
				p.addAnswer(3, "meiosis",
				true,
				"Correct. The two cell divisions of meiosis, I and II, produce four haploid daughter cells.");
			
				p.addAnswer(4, "interphase",
				false,
				"No. Interphase is the period between rounds of mitosis; DNA is replicated during interphase, but the chromosome number remains the same.");
			
				p.addAnswer(5, "metaphase",
				false,
				"No. This is the phase of mitosis during which chromosomes align along the cell\'s equator.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334821;


		
		

		
			
			p.question = "In sexually reproducing species, the chromosome number remains stable over time because _____ and _____ always alternate.\n (<script type=\"text/javascript\">ebook(\'1302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "meiosis; fertilization",
				true,
				"Correct. Meiosis reduces the number of chromosomes by half, and fertilization restores the number to the diploid state.");
			
				p.addAnswer(2, "meiosis; mitosis",
				false,
				"No. Meiosis reduces the number of chromosomes, but mitosis has no effect on chromosome number.");
			
				p.addAnswer(3, "mitosis; fertilization",
				false,
				"No. Fertilization doubles the chromosome number, but mitosis has no effect on it.");
			
				p.addAnswer(4, "meiosis; interphase",
				false,
				"No. Meiosis reduces the number of chromosomes, but interphase, which precedes meiosis, has no effect on it.");
			
				p.addAnswer(5, "meiosis I; meiosis II",
				false,
				"No. Meiosis II follows meiosis I; together the two phases of meiosis produce a net reduction in chromosome number.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334822;


		
		

		
			
			p.question = "The egg (ovum) of a rabbit contains 22 chromosomes. How many chromosomes are in the somatic (body) cells of a rabbit?\n (<script type=\"text/javascript\">ebook(\'1302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "11",
				false,
				"No. Ova are haploid.");
			
				p.addAnswer(2, "22",
				false,
				"No. Consider how ova are produced.");
			
				p.addAnswer(3, "44",
				true,
				"Correct. Haploid sex cells contain half as many chromosomes as diploid somatic cells.");
			
				p.addAnswer(4, "88",
				false,
				"No. Consider how ova are produced.");
			
				p.addAnswer(5, "132",
				false,
				"No. Consider how ova are produced.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334823;


		
		

		
			
			p.question = "In a diploid cell containing 10 chromosomes, meiosis results in the formation of daughter cells containing _____ chromosomes.\n (<script type=\"text/javascript\">ebook(\'1302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "5",
				true,
				"Correct. Haploid sex cells contain half as many chromosomes as diploid somatic cells.");
			
				p.addAnswer(2, "10",
				false,
				"No. This would result if the cell undergoes mitosis.");
			
				p.addAnswer(3, "20",
				false,
				"No. Haploid sex cells contain half as many chromosomes as diploid somatic cells.");
			
				p.addAnswer(4, "40",
				false,
				"No. Haploid sex cells contain half as many chromosomes as diploid somatic cells.");
			
				p.addAnswer(5, "0",
				false,
				"No. Haploid sex cells contain half as many chromosomes as diploid somatic cells.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334824;


		
		

		
			
			p.question = "How many pairs of autosomes do humans have?\n (<script type=\"text/javascript\">ebook(\'1302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "23",
				false,
				"No. However, humans have 23 pairs of chromosomes.");
			
				p.addAnswer(2, "22",
				true,
				"Correct. Humans have 22 pairs of autosomes and one pair of sex chromosomes.");
			
				p.addAnswer(3, "2",
				false,
				"No. However, humans have 2 sex chromosomes.");
			
				p.addAnswer(4, "1",
				false,
				"No. However, humans have a single pair of sex chromosomes.");
			
				p.addAnswer(5, "It depends on the sex of the individual.",
				false,
				"No. Both sexes have the same number of autosomal pairs.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334825;


		
		

		
			
			p.question = "Sister chromatids ___________.\n (<script type=\"text/javascript\">ebook(\'1302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "are only involved in mitosis",
				false,
				"No. Sister chromatids are involved in any type of cell division. They are formed during DNA synthesis.");
			
				p.addAnswer(2, "are pairs of chromosomes, one of which comes from the father and one of which comes from the mother",
				false,
				"No. Homologous chromosomes are pairs of chromosomes, including a maternal and a paternal chromosome.");
			
				p.addAnswer(3, "are identical copies of each other formed during DNA synthesis",
				true,
				"Correct. Sister chromatids are identical and participate in both mitosis and meiosis.");
			
				p.addAnswer(4, "have the same gene loci but may have different alleles of some genes",
				false,
				"No. This is a description of homologous chromosomes.");
			
				p.addAnswer(5, "are only involved in meiosis",
				false,
				"No. Sister chromatids are involved in any type of cell division. They are formed during DNA synthesis.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334826;


		
		

		
			
			p.question = "Which of the following statements about homologous chromosomes is correct?\n (<script type=\"text/javascript\">ebook(\'1302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "They are found in animal cells but not in plant cells.",
				false,
				"No. Both plant and animal cells contain homologous chromosomes.");
			
				p.addAnswer(2, "They have genes for the same traits at the same loci.",
				true,
				"Correct. The chromosomes that make up a pair are called homologous chromosomes, and they carry genes controlling the same inherited characters.");
			
				p.addAnswer(3, "They pair up in prophase II.",
				false,
				"No. Cells in prophase II are haploid; homologous chromosomes pair up in prophase I.");
			
				p.addAnswer(4, "They are found in haploid cells.",
				false,
				"No. Haploid cells have only one of each homologous pair.");
			
				p.addAnswer(5, "They are found in the cells of human females but not in human males.",
				false,
				"No. The cells of both males and females contain homologous chromosomes.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334827;


		
		

		
			
			p.question = "Humans have 46 chromosomes. This number of chromosomes will be found in _____.\n (<script type=\"text/javascript\">ebook(\'1302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "all cells in anaphase of mitosis",
				false,
				"No. At this point in the cell cycle a cell would contain 92 chromosomes.");
			
				p.addAnswer(2, "all the egg and sperm cells",
				false,
				"No. Gametes are haploid.");
			
				p.addAnswer(3, "all gamete-producing cells after meiosis I",
				false,
				"No. Cells are haploid at the end of meiosis I.");
			
				p.addAnswer(4, "liver cells",
				true,
				"Correct. Liver cells are somatic cells, and they contain the characteristic diploid chromosome number.");
			
				p.addAnswer(5, "all the cells of the body",
				false,
				"No. This is not true for gametes.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334828;


		
		

		
			
			p.question = "When we say that an organism is haploid, we mean that _____.\n (<script type=\"text/javascript\">ebook(\'1302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "its cells each have one chromosome",
				false,
				"No. Although this may be the genetic complement of a haploid organism, it is not what is meant by the term.");
			
				p.addAnswer(2, "it has one half of a chromosome",
				false,
				"No. The term does not refer to an abnormality.");
			
				p.addAnswer(3, "its cells have a single set of chromosomes",
				true,
				"Correct. Many fungi and some protists exist as haploid organisms, and plants and some algae also have a haploid stage (called a gametophyte) as part of the life cycle called alternation of generations.");
			
				p.addAnswer(4, "its cells have two sets of chromosomes",
				false,
				"No. Such an organism would be diploid.");
			
				p.addAnswer(5, "its cells have half of one set of chromosomes",
				false,
				"No. It has one entire set.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334829;


		
		

		
			
			p.question = "Which one of the following is a function of mitosis in humans? \n (<script type=\"text/javascript\">ebook(\'1302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "production of eggs",
				false,
				"No. Mitosis keeps the same number of chromosomes, so it does not produce gametes.");
			
				p.addAnswer(2, "production of sperm",
				false,
				"No. Mitosis keeps the same number of chromosomes, so it does not produce gametes.");
			
				p.addAnswer(3, "decreasing the number of chromosomes",
				false,
				"No. Mitosis distributes a copy of all of the chromosomes to the two new daughter cells, keeping the chromosome number constant.");
			
				p.addAnswer(4, "multiplication of body cells",
				true,
				"Correct. This is a function of mitosis in humans. It is mitosis that enables a multicellular adult to form from a fertilized egg and produces cells for growth and tissue repair.");
			
				p.addAnswer(5, "increasing genetic variability",
				false,
				"No. Since mitosis produces two identical copies of the chromosomes, it does not contribute to genetic variability.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334830;


		
		

		
			
			p.question = "Somatic cells in humans contain _____ set(s) of chromosomes and are therefore termed _____. \n (<script type=\"text/javascript\">ebook(\'1302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "one; diploid",
				false,
				"No. This answer is partially correct.");
			
				p.addAnswer(2, "two; haploid",
				false,
				"No. This answer is partially correct.");
			
				p.addAnswer(3, "one; haploid",
				false,
				"No. Haploid gametes contain one chromosomal set.");
			
				p.addAnswer(4, "two; diploid",
				true,
				"Correct. Somatic cells in interphase contain the characteristic diploid chromosome number.");
			
				p.addAnswer(5, "three; triploid",
				false,
				"No. Usually, human cells are not triploid.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334831;


		
		

		
			
			p.question = "Nearly all life cycles have both haploid and diploid phases. Usually, the transition from haploid to diploid takes place _____. \n (<script type=\"text/javascript\">ebook(\'1302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "during crossing over in meiosis",
				false,
				"No. This process does not affect chromosome number.");
			
				p.addAnswer(2, "when DNA is replicated during the S phase of the cell cycle",
				false,
				"No. DNA replication doubles the amount of genetic material in the cell, but it does not change the chromosome number.");
			
				p.addAnswer(3, "when mitotic cytokinesis occurs",
				false,
				"No. This is the last stage of a process that results in the formation of two diploid daughter cells from a diploid parental cell.");
			
				p.addAnswer(4, "at fertilization, when gametes fuse",
				true,
				"Correct. The union of haploid gametes at fertilization produces the zygote, or fertilized egg, which marks the beginning of the diploid phase of the life cycle.");
			
				p.addAnswer(5, "during gastrulation",
				false,
				"No. Gastrulation occurs during prenatal development.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334832;


		
		

		
			
			p.question = "Spores and gametes are different in that _____.\n (<script type=\"text/javascript\">ebook(\'1302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "gametes never resemble spores morphologically",
				false,
				"No. This is not the basis of the distinction between the two.");
			
				p.addAnswer(2, "gametes are always haploid while spores are diploid",
				false,
				"No. Spores can be haploid.");
			
				p.addAnswer(3, "gametes can fuse to form a zygote, but spores can develop into independent organisms without first forming a zygote",
				true,
				"Correct. Unlike a gamete, a spore gives rise to a multicellular organism without fusing with another cell.");
			
				p.addAnswer(4, "only the formation of gametes contributes to genetic variation",
				false,
				"No. Each cycle of chromosome halving and doubling contributes to genetic variation among offspring.");
			
				p.addAnswer(5, "gametes are derived directly from sporophytes to form gametophytes",
				false,
				"No. Sporophytes make spores by undergoing meiosis, and the spores divide by mitosis to form multicellular gametophytes. The gametophytes then make gametes by mitosis.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334833;


		
		

		
			
			p.question = "At the end of telophase I of meiosis and the first cytokinesis, there are _____.\n (<script type=\"text/javascript\">ebook(\'1303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "four haploid cells",
				false,
				"No. Four haploid cells are present at the end of telophase II and cytokinesis.");
			
				p.addAnswer(2, "two diploid cells",
				false,
				"No. Two diploid cells are the result of the completion of the mitotic cell cycle.");
			
				p.addAnswer(3, "four diploid cells",
				false,
				"No. Neither the mitotic cell cycle nor meiosis and cytokinesis directly produce four diploid cells.");
			
				p.addAnswer(4, "one haploid ovum and three polar bodies",
				false,
				"No. This is a final result of oogenesis (egg production) in mammals.");
			
				p.addAnswer(5, "two haploid cells",
				true,
				"Correct. Each of these cells carries a haploid set of chromosomes, each consisting of two chromatids.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334834;


		
		

		
			
			p.question = "What is the result when a diploid cell undergoes meiosis? \n (<script type=\"text/javascript\">ebook(\'1303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "two diploid cells",
				false,
				"No. This would be the result of a diploid cell undergoing mitosis.");
			
				p.addAnswer(2, "two haploid cells",
				false,
				"No. This is possible but not typical.");
			
				p.addAnswer(3, "four diploid cells",
				false,
				"No. Consider what happens to the number of chromosomal sets when a cell undergoes meiosis.");
			
				p.addAnswer(4, "four haploid cells",
				true,
				"Correct. The two cell divisions of meiosis, I and II, produce four haploid daughter cells, which are not genetically identical to the diploid parent cell.");
			
				p.addAnswer(5, "two haploid cells and two diploid cells",
				false,
				"No. Four cells are produced, but two of them are not diploid.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334835;


		
		

		
			
			p.question = "Synapsis occurs during _____.\n (<script type=\"text/javascript\">ebook(\'1303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "anaphase I",
				false,
				"No. During anaphase I, homologous chromosomes separate and migrate toward opposite poles.");
			
				p.addAnswer(2, "prophase I",
				true,
				"Correct. Synapsis is the pairing of homologous chromosomes during prophase I.");
			
				p.addAnswer(3, "cytokinesis",
				false,
				"No. Cytokinesis is the division of one cell into two cells.");
			
				p.addAnswer(4, "prophase II",
				false,
				"No. Synapsis does not occur during prophase II.");
			
				p.addAnswer(5, "metaphase I",
				false,
				"No. During metaphase I, tetrads align along the metaphase plate.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334836;


		
		

		
			
			p.question = "Which of the following occurs during anaphase II?\n (<script type=\"text/javascript\">ebook(\'1303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Homologs separate and migrate toward opposite poles.",
				false,
				"No. This occurs during anaphase I.");
			
				p.addAnswer(2, "Sister chromatids separate and migrate toward opposite poles.",
				true,
				"Correct. This occurs during anaphase II.");
			
				p.addAnswer(3, "Nuclei re-form.",
				false,
				"No. This may occur during telophase I and does occur during telophase II.");
			
				p.addAnswer(4, "Chromosomes line up in one plane.",
				false,
				"No. This happens on the metaphase plate during metaphase I and II.");
			
				p.addAnswer(5, "The synaptonemal complex disappears.",
				false,
				"No. The synaptonemal complex appears and disappears during prophase I.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334837;


		
		

		
			
			p.question = "Which of the following occurs during anaphase I?\n (<script type=\"text/javascript\">ebook(\'1303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Homologs separate and migrate toward opposite poles.",
				true,
				"Correct. This occurs during anaphase I.");
			
				p.addAnswer(2, "Sister chromatids separate and migrate toward opposite poles.",
				false,
				"No. This occurs during anaphase II.");
			
				p.addAnswer(3, "Nuclei re-form.",
				false,
				"No. This may occur during telophase I and does occur during telophase II.");
			
				p.addAnswer(4, "Chromosomes line up in one plane.",
				false,
				"No. This happens on the metaphase plate during metaphase I and II.");
			
				p.addAnswer(5, "The cell is haploid.",
				false,
				"No. The cell is diploid until the end of meiosis I and cytokinesis.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334838;


		
		

		
			
			p.question = "Cytokinesis is the _____.\n (<script type=\"text/javascript\">ebook(\'1303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "exchange of homologous regions of nonsister chromatids",
				false,
				"No. This is crossing over.");
			
				p.addAnswer(2, "formation of tetrads",
				false,
				"No. Tetrads are formed by synapsis.");
			
				p.addAnswer(3, "independent assortment of chromosomes",
				false,
				"No. Independent assortment occurs as a result of the positioning of homologous chromosomes during metaphase I.");
			
				p.addAnswer(4, "lining up of tetrads at the metaphase plate",
				false,
				"No. This occurs during metaphase I.");
			
				p.addAnswer(5, "division of one cell into two",
				true,
				"Correct. Cytokinesis normally accompanies both telophase I and telophase II, as well as the telophase of mitosis.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334839;


		
		

		
			
			p.question = "What is the function of meiosis?\n (<script type=\"text/javascript\">ebook(\'1303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "to make exact copies of the parent cell",
				false,
				"No. This is the function of mitosis.");
			
				p.addAnswer(2, "to make one cell with twice the number of chromosomes as the parent pairs",
				false,
				"No. Although chromosomes do replicate during meiosis, the function of meiosis is not to make one cell with twice the number of chromosomes as the parent pairs.");
			
				p.addAnswer(3, "to make four cells with the same chromosome number as the parent",
				false,
				"No. Four cells are made, but with a different chromosome number than the parent.");
			
				p.addAnswer(4, "to make cells with a haploid (half that of the parents) number of chromosomes",
				true,
				"Correct. The two cell divisions of meiosis, I and II, produce four haploid daughter cells, which are not genetically identical to the diploid parent cell.");
			
				p.addAnswer(5, "to make diploid spores",
				false,
				"No. Meiosis produces haploid cells.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334840;


		
		

		
			
			p.question = "Crossing over occurs during _____.\n (<script type=\"text/javascript\">ebook(\'1303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "cytokinesis",
				false,
				"No. This is the division of the cell.");
			
				p.addAnswer(2, "metaphase I",
				false,
				"No. During metaphase I, homologues align on the metaphase plate.");
			
				p.addAnswer(3, "prophase II",
				false,
				"No. This phase is very similar to mitotic prophase.");
			
				p.addAnswer(4, "metaphase II",
				false,
				"No. During this phase chromosomes align on the metaphase plate.");
			
				p.addAnswer(5, "prophase I",
				true,
				"Correct. Crossing over resulting in genetic recombination occurs during this phase.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334841;


		
		

		
			
			p.question = "Regions of chromosomes where nonsister chromatids cross over are called _____.\n (<script type=\"text/javascript\">ebook(\'1303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "inversions",
				false,
				"No. An inversion is a type of alteration of chromosome structure.");
			
				p.addAnswer(2, "homologs",
				false,
				"No. However, the recombining nonsister chromatids belong to homologous chromosomes.");
			
				p.addAnswer(3, "kinetochores",
				false,
				"No. These are the structures at centromeres where the spindle fibers attach to the chromosome.");
			
				p.addAnswer(4, "chiasmata",
				true,
				"Correct. Chiasmata are regions where crossing over has occurred.");
			
				p.addAnswer(5, "tetrads",
				false,
				"No. However, crossing over occurs within tetrads, which consist of a pair of replicated homologous chromosomes.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334842;


		
		

		
			
			p.question = "The synaptonemal complex _____. \n (<script type=\"text/javascript\">ebook(\'1303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "physically connects homologous chromosomes during prophase I",
				true,
				"Correct. The synaptonemal complex helps to line homologous chromosomes up gene by gene.");
			
				p.addAnswer(2, "physically connects homologous chromosomes during mitosis",
				false,
				"No. Synapsis does not occur during mitosis.");
			
				p.addAnswer(3, "is broken down by enzymes during anaphase II",
				false,
				"No. The synaptonemal complex is broken down late in prophase I.");
			
				p.addAnswer(4, "is another name for chiasmata",
				false,
				"No. Chiasmata persist after the synaptonemal complex has been broken down.");
			
				p.addAnswer(5, "is formed by a protein called shugoshin",
				false,
				"No. Shugoshin protects proteins involved in sister chromatid cohesion from being broken down.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334843;


		
		

		
			
			p.question = "In the experiment by Yoshinori Watanabe and colleagues regarding the role of the protein shugoshin, their hypothesis was that __________.\n (<script type=\"text/javascript\">ebook(\'1303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "fluorescent labels aid in tracing chromosomal movements",
				false,
				"No. Fluorescent labeling is a technique used in the experiment to test their hypothesis.");
			
				p.addAnswer(2, "one yeast strain would not produce the shugoshin protein while the other would",
				false,
				"No. This describes part of their experimental control.");
			
				p.addAnswer(3, "chromosomes in cells that did not produce shugoshin would separate randomly during meiosis II",
				false,
				"No. This is a prediction based on their hypothesis. A prediction is specific to an experiment, while a hypothesis is a broader statement.");
			
				p.addAnswer(4, "during the transition between metaphase I and anaphase I, the protein shugoshin is present only around centromeres",
				false,
				"No. This is an observation that led to the formulation of their hypothesis.");
			
				p.addAnswer(5, "the protein shugoshin protects cohesins from being degraded",
				true,
				"Correct. This hypothesis might be tested in many ways with different predictions and different controls.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334844;


		
		

		
			
			p.question = "An organism has a haploid chromosome number <i>n</i> = 4. How many tetrads will form during meiosis?\n (<script type=\"text/javascript\">ebook(\'1303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "2",
				false,
				"No. Each tetrad consists of two chromosomes.");
			
				p.addAnswer(2, "3",
				false,
				"No. Each tetrad consists of two chromosomes.");
			
				p.addAnswer(3, "4",
				true,
				"Correct. Because of the synapsis of homologous chromosomes, the number of tetrads in meiosis I will be the same as the haploid number of chromosomes.");
			
				p.addAnswer(4, "8",
				false,
				"No. This is the diploid chromosome number.");
			
				p.addAnswer(5, "16",
				false,
				"No. Collectively, such tetrads would consist of 16 chromatids.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334845;


		
		

		
			
			p.question = "Which event occurs only during prophase I of the first meiotic division?\n (<script type=\"text/javascript\">ebook(\'1303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Homologous chromosomes line up at the center of the cell.",
				false,
				"No. Pairs of homologous chromosomes line up during metaphase I, not prophase I.");
			
				p.addAnswer(2, "Synapsis of homologous pairs occurs.",
				true,
				"Correct. Synapsis of homologous chromosomes occurs at prophase of meiosis I.");
			
				p.addAnswer(3, "The nuclear membrane breaks down.",
				false,
				"No. This also occurs during prophase II.");
			
				p.addAnswer(4, "Replication of DNA takes place.",
				false,
				"No. DNA replicates during interphase.");
			
				p.addAnswer(5, "A spindle of microtubules forms.",
				false,
				"No. A spindle of microtubules forms during both prophase I and prophase II.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334846;


		
		

		
			
			p.question = "In a male mammal, every cell that undergoes meiosis gives rise to _____ sperm. \n (<script type=\"text/javascript\">ebook(\'1303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "one",
				false,
				"No. In females, every cell that undergoes meiosis gives rise to one ovum.");
			
				p.addAnswer(2, "two",
				false,
				"No. The cell cycle produces two daughter cells from one parental cell.");
			
				p.addAnswer(3, "four",
				true,
				"Correct. One diploid parent cell gives rise to four haploid sex cells at the completion of the two meiotic divisions.");
			
				p.addAnswer(4, "no set number",
				false,
				"No. One diploid parent cell gives rise to four haploid sex cells at the completion of the two meiotic divisions.");
			
				p.addAnswer(5, "zero",
				false,
				"No. One diploid parent cell gives rise to four haploid sex cells at the completion of the two meiotic divisions.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334847;


		
		

		
			
			p.question = "Which one of the following occurs in meiosis, but not mitosis?\n (<script type=\"text/javascript\">ebook(\'1303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The cells formed have the same combination of genes as found in the initial cell.",
				false,
				"No. Remember that independent assortment and crossing over occur during meiosis.");
			
				p.addAnswer(2, "Homologous chromosomes separate.",
				true,
				"Correct. Homologous chromosomes separate during anaphase I. This event follows synapsis, an event unique to prophase I.");
			
				p.addAnswer(3, "The nuclear envelope disappears.",
				false,
				"No. This occurs during both mitosis and meiosis.");
			
				p.addAnswer(4, "Sister chromatids undergo disjunction.",
				false,
				"No. This occurs during both mitosis and meiosis.");
			
				p.addAnswer(5, "A spindle apparatus forms.",
				false,
				"No. This occurs during both mitosis and meiosis.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334848;


		
		

		
			
			p.question = "Which function makes meiosis lengthier and more complex than mitosis? \n (<script type=\"text/javascript\">ebook(\'1303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "decreasing the chromosome number to haploid",
				false,
				"No. This answer is correct, but there is a better response.");
			
				p.addAnswer(2, "introducing genetic variation among the daughter cells",
				false,
				"No. This answer is correct, but there is a better response.");
			
				p.addAnswer(3, "ensuring that each daughter cell gets a single, complete set of chromosomes",
				false,
				"No. This answer is correct, but there is a better response.");
			
				p.addAnswer(4, "undergoing two rounds of cytokinesis",
				false,
				"No. This answer is correct, but there is a better response.");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct. Meiosis involves two divisions that typically result in four daughter cells (instead of two). Each cell has half the number of chromosomes of the original parent cell, and is, of course, not genetically identical to the parent cell.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334849;


		
		

		
			
			p.question = "Ignoring crossover, how many kinds of gametes can be produced by an organism with a diploid number of 8?\n (<script type=\"text/javascript\">ebook(\'1304\',\'quiz\')</script>)";
			p.incorrect_any_expl = "No. The number of combinations possible when chromosomes assort independently into gametes during meiosis is 2<sup><i>n</i></sup>, where <i>n</i> is the haploid number of chromosomes.";
			p.incorrect_any_expl_flag = 1;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "2",
				false,
				"");
			
				p.addAnswer(2, "4",
				false,
				"");
			
				p.addAnswer(3, "8",
				false,
				"");
			
				p.addAnswer(4, "16",
				true,
				"Correct. The number of combinations possible when chromosomes assort independently into gametes during meiosis is 2<sup><i>n</i></sup>, where <i>n</i> is the haploid number of chromosomes.");
			
				p.addAnswer(5, "32",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334850;


		
		

		
			
			p.question = "Which of the following contributes to genetic variation in sexually reproducing species?\n (<script type=\"text/javascript\">ebook(\'1304\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "crossing over, internal fertilization, independent assortment",
				false,
				"No. Internal fertilization does not contribute to genetic variation. It is simply one way of getting gametes close to each other.");
			
				p.addAnswer(2, "independent assortment, spindle formation, random fertilization",
				false,
				"No. Spindle formation occurs in mitosis as well as meiosis, so it is not necessarily involved in increasing genetic variation.");
			
				p.addAnswer(3, "random fertilization, DNA synthesis, independent assortment",
				false,
				"No. DNA synthesis occurs before both mitotic and meiotic division and does not directly increase genetic variation.");
			
				p.addAnswer(4, "random fertilization, independent assortment, crossing over",
				true,
				"Correct. These three aspects of sexual reproduction increase genetic variation.");
			
				p.addAnswer(5, "internal fertilization, spindle formation, crossing over",
				false,
				"No. Internal fertilization and spindle formation do not increase genetic variation.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334851;


		
		

		
			
			p.question = "In humans, the haploid number of chromosomes is 23. Independent assortment has the possibility of producing _____ different types of gametes.\n (<script type=\"text/javascript\">ebook(\'1304\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "23<sup>2</sup>",
				false,
				"No. For each chromosome there are only two choices, the maternal or the paternal chromosome.");
			
				p.addAnswer(2, "1 million",
				false,
				"No. The answer is higher and more specific.");
			
				p.addAnswer(3, "2<sup>23</sup>",
				true,
				"Correct. For each gamete there are two possibilities for each chromosome (the paternal or the maternal chromosome), and there are 23 different chromosomes per gamete.");
			
				p.addAnswer(4, "24",
				false,
				"No. There are many more possible combinations than this.");
			
				p.addAnswer(5, "100,000",
				false,
				"No. The answer is much higher and more specific.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334852;


		
		

		
			
			p.question = "The diploid number of chromosomes in a certain animal is 8 (2<i>n</i> = 8). How do the four pairs of homologous chromosomes align and separate during meiosis?\n (<script type=\"text/javascript\">ebook(\'1304\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "All of the maternal chromosomes always move to one pole, and all the paternal chromosomes always move to the other pole.",
				false,
				"No. Although the maternal and paternal chromosomes may segregate in this way, it represents only one of many possible outcomes.");
			
				p.addAnswer(2, "All 16 chromatids move together.",
				false,
				"No. This would fail to produce haploid gametes.");
			
				p.addAnswer(3, "Exactly two maternal and two paternal chromosomes always move to each of the two poles.",
				false,
				"No. Although the maternal and paternal chromosomes may segregate in this way, it represents only one of many possible outcomes.");
			
				p.addAnswer(4, "The first to move influences all the others.",
				false,
				"No. This would violate independent assortment.");
			
				p.addAnswer(5, "They align and assort independently to form any of 16 different combinations.",
				true,
				"Correct. Because each pair of homologous chromosomes is positioned independently in metaphase I, the first meiotic division results in the independent assortment of paternal and maternal chromosomes into daughter cells. In a case in which 2<i>n</i> = 8, 16 combinations of chromosomes are possible for gametes.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334853;


		
		

		
			
			p.question = "In a diploid set of chromosomes, one member of each pair of homologous chromosomes is derived from the father (paternal), and the other comes from the mother (maternal). If 2<i>n</i> = 6, what is the probability of obtaining a gamete in which all the chromosomes are paternal ones?\n (<script type=\"text/javascript\">ebook(\'1304\',\'quiz\')</script>)";
			p.incorrect_any_expl = "No. The chance of any one paternal chromosome ending up in a particular gamete is 1/2, so the chance that all three would be of paternal origin would be (1/2)<sup><i>n</i></sup>, where <i>n</i> = 3.";
			p.incorrect_any_expl_flag = 1;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "1/4",
				false,
				"");
			
				p.addAnswer(2, "1/8",
				true,
				"Correct. The chance of any one paternal chromosome ending up in a particular gamete is 1/2, so the chance that all three would be of paternal origin would be (1/2)<sup><i>n</i></sup>, where <i>n</i> = 3.");
			
				p.addAnswer(3, "1/16",
				false,
				"");
			
				p.addAnswer(4, "1/32",
				false,
				"");
			
				p.addAnswer(5, "cannot be determined from these data",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334854;


		
		

		
			
			p.question = "The major contribution of sex to evolution is that _____.\n (<script type=\"text/javascript\">ebook(\'1304\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "it is the only mechanism for species to reproduce",
				false,
				"No. There are asexual species.");
			
				p.addAnswer(2, "it provides a method to increase genetic variation",
				true,
				"Correct. Sexual life cycles produce enormous genetic variation among offspring.");
			
				p.addAnswer(3, "it provides a way in which somatic mutations can be inherited",
				false,
				"No. Sex does not allow for the inheritance of somatic mutations.");
			
				p.addAnswer(4, "The first and second answers are correct.",
				false,
				"No. There is only one correct answer.");
			
				p.addAnswer(5, "The second and third answers are correct.",
				false,
				"No. There is only one correct answer.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

