

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "45: Hormones and the Endocrine System > Activities Quiz";
	ak.quiz_loc_with_commas = "45: Hormones and the Endocrine System, Activities Quiz";
	ak.quiz_title = "Activities Quiz";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 15;
	ak.non_essay_total = 15;
	ak.scored_item_total = 15;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336591;


		
		

		
			
			p.question = "Which of these is the second of the three stages of cell signaling? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?11&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Overview of Cell Signaling</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "gene activation",
				false,
				"Gene activation is a cellular response considered part of the third stage of cell signaling.");
			
				p.addAnswer(2, "reception",
				false,
				"Reception is the first of the three stages of cell signaling.");
			
				p.addAnswer(3, "binding of a neurotransmitter to a plasma membrane receptor",
				false,
				"This is a type of reception, the first stage of a signal transduction pathway.");
			
				p.addAnswer(4, "transduction",
				true,
				"Transduction is the second of the three stages of cell signaling.");
			
				p.addAnswer(5, "cell response",
				false,
				"Cell response follows reception and signal transduction.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336592;


		
		

		
			
			p.question = "Receptors for nonsteroid hormones are located in _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?45&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Peptide Hormone Action</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the extracellular fluid",
				false,
				"Receptors are found in association with the target cell.");
			
				p.addAnswer(2, "the cytoplasm",
				false,
				"Receptors for steroid hormones may be found in the cytoplasm.");
			
				p.addAnswer(3, "the nucleus",
				false,
				"Receptors for steroid hormones may be found in the nucleus.");
			
				p.addAnswer(4, "the cytosol",
				false,
				"Receptors for steroid hormones are located in the cytosol.");
			
				p.addAnswer(5, "association with a cell\'s plasma membrane",
				true,
				"Since nonsteroid hormones do not cross a cell\'s plasma membrane, their receptors are located in association with the plasma membrane.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336593;


		
		

		
			
			p.question = "Which of these is a nonsteroid hormone? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?45&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Peptide Hormone Action</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "estrogen",
				false,
				"Estrogen is a steroid hormone.");
			
				p.addAnswer(2, "testosterone",
				false,
				"Testosterone is a steroid hormone.");
			
				p.addAnswer(3, "both estrogen and testosterone",
				false,
				"Both estrogen and testosterone are steroid hormones.");
			
				p.addAnswer(4, "oxytocin",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(5, "epinephrine and oxytocin",
				true,
				"Both epinephrine and oxytocin are nonsteroid hormones.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336594;


		
		

		
			
			p.question = "How do nonsteroid hormones differ from steroid hormones? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?45&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Peptide Hormone Action</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "nonsteroid hormones bind to a cell\'s DNA; steroid hormones do not bind to a cell\'s DNA",
				false,
				"Since nonsteroid hormones do not enter a cell, they cannot bind to a cell\'s DNA.");
			
				p.addAnswer(2, "nonsteroid hormones act via signal transduction pathways; steroid hormones do not act via signal transduction pathways",
				true,
				"Since they do not enter the cell, nonsteroid hormones act via signal transduction pathways.");
			
				p.addAnswer(3, "the action of nonsteroid hormones never affects gene expression; the action of steroid hormones always affects gene expression",
				false,
				"Nonsteroid hormones can have an effect on gene expression.");
			
				p.addAnswer(4, "nonsteroid hormones bind to cytoplasmic receptors; steroid hormones bind to plasma membrane receptors",
				false,
				"Nonsteroid hormones bind to plasma membrane receptors; steroid hormones may bind to cytoplasmic receptors.");
			
				p.addAnswer(5, "nonsteroid hormones are fat-soluble; steroid hormones are water-soluble",
				false,
				"Nonsteroid hormones, such as those derived from amino acids, are water-soluble; as lipids, steroid hormones are fat-soluble.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336595;


		
		

		
			
			p.question = "Which of these extracellular signal molecules could diffuse through a plasma membrane and bind to an intracellular receptor? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?45&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Steroid Hormone Action</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "estrogen",
				true,
				"Steroid hormones such as estrogen can diffuse through the plasma membrane and bind to intracellular receptors.");
			
				p.addAnswer(2, "epinephrine",
				false,
				"Epinephrine is a nonsteroid hormone; nonsteroid hormones bind to plasma membrane receptors.");
			
				p.addAnswer(3, "cellulose",
				false,
				"Cellulose is too large to diffuse through a plasma membrane.");
			
				p.addAnswer(4, "oxytocin",
				false,
				"Oxytocin is a nonsteroid hormone; nonsteroid hormones bind to plasma membrane receptors.");
			
				p.addAnswer(5, "starch",
				false,
				"Starch is too large to diffuse through a plasma membrane.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336596;


		
		

		
			
			p.question = "The primary reason steroid hormones usually act slowly is that _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?45&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Steroid Hormone Action</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "they are produced at very low concentrations",
				false,
				"Low hormone concentrations do not necessarily correlate with a slow cellular response.");
			
				p.addAnswer(2, "acting via a signal transduction pathway makes for slower responses than does directly interacting with a cell\'s DNA",
				false,
				"Nonsteroid hormones, not steroid hormones, act via signal transduction pathways; steroid hormone-receptor complexes interact directly with DNA.");
			
				p.addAnswer(3, "they are too large to enter a cell and therefore must first bind to a plasma membrane receptor before having an effect on a cell",
				false,
				"Steroid hormones diffuse across plasma membranes; they do not bind to plasma membrane receptors.");
			
				p.addAnswer(4, "target cells tend to ignore steroid hormones in favor of nonsteroid hormones",
				false,
				"Cells do not ignore any hormone for which they have functional receptors.");
			
				p.addAnswer(5, "they turn genes on or off and it takes time for gene products to build up or become depleted",
				true,
				"This is the primary reason that steroid hormones usually act slowly.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336597;


		
		

		
			
			p.question = "Steroid hormone-receptor complexes act in _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?45&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Steroid Hormone Action</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the nucleus",
				true,
				"Steroid hormone-receptor complexes bind to DNA, where they affect transcription.");
			
				p.addAnswer(2, "lysosomes",
				false,
				"You need to consider that steroid hormones affect gene expression.");
			
				p.addAnswer(3, "vesicles",
				false,
				"You need to consider that steroid hormones affect gene expression.");
			
				p.addAnswer(4, "the cytoplasm",
				false,
				"However, steroid hormone-receptor complexes may form in the cytoplasm.");
			
				p.addAnswer(5, "the plasma membrane",
				false,
				"Steroid hormone receptors are found within the cell, not in association with the plasma membrane.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336598;


		
		

		
			
			p.question = "Which of these glands secretes releasing hormones? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?45&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Human Endocrine Glands and Hormones</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "hypothalamus",
				true,
				"The hypothalamus secretes both releasing and inhibiting hormones.");
			
				p.addAnswer(2, "adrenal cortex",
				false,
				"The adrenal cortex secretes hormones in response to secretions of the anterior pituitary.");
			
				p.addAnswer(3, "thymus",
				false,
				"The thymus secretes hormones in response to secretions of the anterior pituitary.");
			
				p.addAnswer(4, "ovaries",
				false,
				"Ovaries secrete hormones in response to secretions of the anterior pituitary.");
			
				p.addAnswer(5, "testes",
				false,
				"Testes secrete hormones in response to secretions of the anterior pituitary.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336599;


		
		

		
			
			p.question = "Which of these hormones are responsible for the \"fight or flight\" response to danger? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?45&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Human Endocrine Glands and Hormones</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "insulin and glucagon",
				false,
				"These hormones are involved in the regulation of blood sugar levels.");
			
				p.addAnswer(2, "thyroxine and calcitonin",
				false,
				"Thyroxine is involved in the regulation of metabolic rate; calcitonin is involved in the regulation of blood calcium levels.");
			
				p.addAnswer(3, "androgens and estrogens",
				false,
				"Androgens and estrogens are sex hormones.");
			
				p.addAnswer(4, "antidiuretic hormone (ADH) and oxytocin",
				false,
				"ADH stimulates the kidneys to conserve water; oxytocin plays a role in the labor of pregnancy and milk let-down in lactating women.");
			
				p.addAnswer(5, "epinephrine and norepinephrine",
				true,
				"These hormones, secreted by the adrenal medulla, are responsible for the \"fight or flight\" response.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336600;


		
		

		
			
			p.question = "Adrenocorticotropic hormone (ACTH) triggers the release of _____ in response to stress. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?45&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Human Endocrine Glands and Hormones</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "melatonin",
				false,
				"Melatonin is secreted by the pineal gland; ACTH acts on the adrenal cortex.");
			
				p.addAnswer(2, "insulin",
				false,
				"The pancreas secretes insulin; ACTH acts on the adrenal cortex.");
			
				p.addAnswer(3, "glucocorticoids",
				true,
				"In response to stress, ACTH stimulates the adrenal cortex to secrete glucocorticoids.");
			
				p.addAnswer(4, "thymosin",
				false,
				"Thymosin is secreted by the thymus; ACTH acts on the adrenal cortex.");
			
				p.addAnswer(5, "parathyroid hormone",
				false,
				"Parathyroid hormone is secreted by the parathyroid gland; ACTH acts on the adrenal cortex.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336601;


		
		

		
			
			p.question = "_____ are the main male hormones. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?45&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Human Endocrine Glands and Hormones</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Progesterones",
				false,
				"Progesterone is a female sex hormone.");
			
				p.addAnswer(2, "Mineralocorticoids",
				false,
				"Mineralocorticoids, such as aldosterone, act primarily on the kidney.");
			
				p.addAnswer(3, "Androgens",
				true,
				"Androgens, such as testosterone, are the main male hormones.");
			
				p.addAnswer(4, "Luteinizing hormones",
				false,
				"Luteinizing hormone acts on both ovaries and testes.");
			
				p.addAnswer(5, "Estrogens",
				false,
				"Estrogens are the main female hormones.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336602;


		
		

		
			
			p.question = "What hormone promotes water retention by the kidneys? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?45&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Human Endocrine Glands and Hormones</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "follicle-stimulating hormone (FSH)",
				false,
				"FSH acts on the gonads (ovaries and testes).");
			
				p.addAnswer(2, "prolactin",
				false,
				"Prolactin stimulates the mammary glands to produce milk.");
			
				p.addAnswer(3, "antidiuretic hormone (ADH)",
				true,
				"A diuretic promotes water loss; thus it makes sense that ADH (secreted by the anterior pituitary) promotes water conservation.");
			
				p.addAnswer(4, "melatonin",
				false,
				"Melatonin plays a role in the regulation of the body\'s biological clock.");
			
				p.addAnswer(5, "glucagon",
				false,
				"Glucagon plays a role in the regulation of blood sugar levels.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336603;


		
		

		
			
			p.question = "Which hormone opposes the action of parathyroid hormone? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?45&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Human Endocrine Glands and Hormones</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "calcitonin",
				true,
				"Parathyroid hormone increases blood calcium levels; calcitonin lowers blood calcium levels.");
			
				p.addAnswer(2, "insulin",
				false,
				"Parathyroid hormone increases blood calcium levels; insulin lowers blood sugar levels.");
			
				p.addAnswer(3, "thyroxine",
				false,
				"Parathyroid hormone increases blood calcium levels, thyroxine increases the metabolic rate.");
			
				p.addAnswer(4, "thymosin",
				false,
				"Parathyroid hormone increases blood calcium levels; thymosin plays a role in the maturation of T cells.");
			
				p.addAnswer(5, "glucagon",
				false,
				"Parathyroid hormone increases blood calcium levels; glucagon raises blood sugar levels");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336604;


		
		

		
			
			p.question = "Which hormone stimulates hormone production by the ovaries and testes? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?45&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Human Endocrine Glands and Hormones</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "progesterone",
				false,
				"Progesterone is an ovarian secretion.");
			
				p.addAnswer(2, "testosterone",
				false,
				"Testosterone is secreted by the testes.");
			
				p.addAnswer(3, "glucocorticoids",
				false,
				"Glucocorticoids are secreted by the adrenal cortex, not by the gonads.");
			
				p.addAnswer(4, "luteinizing hormone (LH)",
				true,
				"LH stimulates hormone production by both the ovaries and testes.");
			
				p.addAnswer(5, "estrogens",
				false,
				"Estrogens are hormones produced by the ovaries.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336605;


		
		

		
			
			p.question = "Which hormone stimulates milk production? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?45&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Human Endocrine Glands and Hormones</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "parathyroid hormone",
				false,
				"Parathyroid hormone plays a role in the regulation of blood calcium levels.");
			
				p.addAnswer(2, "mineralocorticoids",
				false,
				"Mineralocorticoids primarily affect kidney function; they do not act on the mammary glands.");
			
				p.addAnswer(3, "prolactin",
				true,
				"Prolactin, secreted by the anterior pituitary, stimulates milk production by the mammary glands.");
			
				p.addAnswer(4, "thyroid-stimulating hormone (TSH)",
				false,
				"TSH acts on the thyroid gland, not on the mammary glands.");
			
				p.addAnswer(5, "thymosin",
				false,
				"Thymosin is involved in the regulation of T cell function.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

