

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "Investigation Quiz > How Much Time Do Cells Spend in Each Phase of Mitosis?";
	ak.quiz_loc_with_commas = "Investigation Quiz, How Much Time Do Cells Spend in Each Phase of Mitosis?";
	ak.quiz_title = "How Much Time Do Cells Spend in Each Phase of Mitosis?";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 5;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 5;
	ak.non_essay_total = 0;
	ak.scored_item_total = 0;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337605;


		
		

		
			p.question = "In this specimen of onion root cells, what is the amount of time, in minutes, spent in interphase?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337606;


		
		

		
			p.question = "In this specimen of onion root cells, what is the amount of time, in minutes, spent in prophase?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337607;


		
		

		
			p.question = "In this specimen of onion root cells, what is the amount of time, in minutes, spent in metaphase?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337608;


		
		

		
			p.question = "In this specimen of onion root cells, what is the amount of time, in minutes, spent in anaphase?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337609;


		
		

		
			p.question = "In this specimen of onion root cells, what is the amount of time, in minutes, spent in telophase?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

