

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "9: Cellular Respiration: Harvesting Chemical Energy > Activities Quiz";
	ak.quiz_loc_with_commas = "9: Cellular Respiration: Harvesting Chemical Energy, Activities Quiz";
	ak.quiz_title = "Activities Quiz";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 25;
	ak.non_essay_total = 25;
	ak.scored_item_total = 25;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334522;


		
		

		
			
			p.question = "What process occurs in structure H? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?9&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Build a Chemical Cycling System</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0901q.jpg\" ALT=\"Question #1\" BORDER=\"1\" >";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "cellular respiration",
				false,
				"The organelle is not a mitochondrion.");
			
				p.addAnswer(2, "intracellular digestion",
				false,
				"The structure is not a lysosome.");
			
				p.addAnswer(3, "protein synthesis",
				false,
				"The structure is not a ribosome.");
			
				p.addAnswer(4, "ribosome synthesis",
				false,
				"The structure is not a nucleolus.");
			
				p.addAnswer(5, "photosynthesis",
				true,
				"Chloroplasts are the sites of photosynthesis.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334523;


		
		

		
			
			p.question = "What molecules belong in space A and B? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?9&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Build a Chemical Cycling System</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0902q.jpg\" ALT=\"Question #2\" BORDER=\"1\" >";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "glucose and carbon dioxide",
				false,
				"Photosynthesis does not release carbon dioxide into the atmosphere.");
			
				p.addAnswer(2, "carbon dioxide and water",
				false,
				"Photosynthesis does not produce carbon dioxide and water.");
			
				p.addAnswer(3, "oxygen and water",
				false,
				"This answer is partially correct.");
			
				p.addAnswer(4, "glucose and oxygen",
				true,
				"Photosynthesis produces glucose and releases oxygen into the atmosphere.");
			
				p.addAnswer(5, "carbon dioxide and oxygen",
				false,
				"Photosynthesis does not release carbon dioxide.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334524;


		
		

		
			
			p.question = "What organelle is indicated by the letter C? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?9&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Build a Chemical Cycling System</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0903q.jpg\" ALT=\"Question #3\" BORDER=\"1\" >";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "mitochondrion",
				true,
				"Mitochondria are the sites of cellular respiration.");
			
				p.addAnswer(2, "Golgi apparatus",
				false,
				"The indicated organelle does not modify, store, or package proteins.");
			
				p.addAnswer(3, "lysosome",
				false,
				"The indicated organelle is not responsible for intracellular digestion.");
			
				p.addAnswer(4, "chloroplast",
				false,
				"The indicated organelle is not the site of photosynthesis.");
			
				p.addAnswer(5, "peroxisome",
				false,
				"The indicated organelle does not produce and degrade hydrogen peroxide.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334525;


		
		

		
			
			p.question = "What molecules belong in spaces E and F? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?9&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Build a Chemical Cycling System</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0904q.jpg\" ALT=\"Question #4\" BORDER=\"1\" >";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "glucose, water, carbon dioxide, and oxygen",
				false,
				"Try to narrow it down a bit.");
			
				p.addAnswer(2, "glucose and oxygen",
				false,
				"These are produced by photosynthesis.");
			
				p.addAnswer(3, "carbon dioxide and oxygen",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(4, "oxygen and water",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(5, "carbon dioxide and water",
				true,
				"Carbon dioxide and water are by-products of cellular respiration.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334526;


		
		

		
			
			p.question = "What process occurs in Box A? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?9&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Overview of Cellular Respiration</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0905q.jpg\" ALT=\"Question #5\" BORDER=\"1\" >";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "glycolysis",
				true,
				"Glycolysis occurs in the cytosol.");
			
				p.addAnswer(2, "the citric acid cycle",
				false,
				"The citric acid cycle occurs within the mitochondrion.");
			
				p.addAnswer(3, "electron transport",
				false,
				"Electron transport occurs within the mitochondrion.");
			
				p.addAnswer(4, "oxidative phosphorylation",
				false,
				"Oxidative phosphorylation occurs within the mitochondrion.");
			
				p.addAnswer(5, "electron transport and oxidative phosphorylation",
				false,
				"These processes occur within the mitochondrion.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334527;


		
		

		
			
			p.question = "What process occurs within Box B? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?9&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Overview of Cellular Respiration</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0906q.jpg\" ALT=\"Question #6\" BORDER=\"1\" >";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "glycolysis",
				false,
				"Glycolysis occurs in the cytosol.");
			
				p.addAnswer(2, "the citric acid cycle",
				true,
				"The citric acid cycle transfers electrons to NADH and FADH<sub>2</sub>.");
			
				p.addAnswer(3, "electron transport",
				false,
				"Electron transport accepts NADH and FADH<sub>2</sub>.");
			
				p.addAnswer(4, "oxidative phosphorylation",
				false,
				"Oxidative phosphorylation occurs in the same box as electron transport.");
			
				p.addAnswer(5, "photophosphorylation",
				false,
				"Light is not directly involved.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334528;


		
		

		
			
			p.question = "What molecule is indicated by the letter D? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?9&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Overview of Cellular Respiration</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0907q.jpg\" ALT=\"Question #7\" BORDER=\"1\" >";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "glucose",
				false,
				"Glucose is a reactant in glycolysis.");
			
				p.addAnswer(2, "ATP",
				false,
				"ATP is a product of the process.");
			
				p.addAnswer(3, "oxygen",
				true,
				"Oxygen is the final electron acceptor of cellular respiration.");
			
				p.addAnswer(4, "pyruvate",
				false,
				"Pyruvate is a product of glycolysis.");
			
				p.addAnswer(5, "water",
				false,
				"Water is a by-product of cellular respiration.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334529;


		
		

		
			
			p.question = "How many NADH are produced by glycolysis? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?9&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Glycolysis</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "1",
				false,
				"More.");
			
				p.addAnswer(2, "2",
				true,
				"Two NADH molecules are produced by glycolysis.");
			
				p.addAnswer(3, "3",
				false,
				"Less.");
			
				p.addAnswer(4, "4",
				false,
				"Less.");
			
				p.addAnswer(5, "5",
				false,
				"Less.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334530;


		
		

		
			
			p.question = "In glycolysis, ATP molecules are produced by _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?9&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Glycolysis</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "photophosphorylation",
				false,
				"Light is not directly involved in glycolysis.");
			
				p.addAnswer(2, "substrate-level phosphorylation",
				true,
				"A phosphate group is transferred from glyceraldehyde phosphate to ADP.");
			
				p.addAnswer(3, "cellular respiration",
				false,
				"You need to be more specific.");
			
				p.addAnswer(4, "oxidative phosphorylation",
				false,
				"This process utilizes energy released by electron transport.");
			
				p.addAnswer(5, "photosynthesis",
				false,
				"Photosynthesis is not a component of glycolysis.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334531;


		
		

		
			
			p.question = "Which of these is NOT a product of glycolysis? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?9&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Glycolysis</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "water",
				false,
				"Water is a product of glycolysis.");
			
				p.addAnswer(2, "NADH + H<sup>+</sup>",
				false,
				"NADH + H<sup>+</sup> is a product of glycolysis.");
			
				p.addAnswer(3, "ATP",
				false,
				"ATP is a product of glycolysis.");
			
				p.addAnswer(4, "FADH<sub>2</sub>",
				true,
				"FADH<sub>2</sub> is a product of the citric acid cycle.");
			
				p.addAnswer(5, "pyruvate",
				false,
				"Pyruvate is a product of glycolysis.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334532;


		
		

		
			
			p.question = "In glycolysis, what starts the process of glucose oxidation? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?9&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Glycolysis</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "hexokinase",
				false,
				"This is the enzyme that catalyzes the phosphorylation of glucose.");
			
				p.addAnswer(2, "NADPH",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(3, "ADP",
				false,
				"ADP is produced as a result of the phosphorylation of glucose.");
			
				p.addAnswer(4, "ATP",
				true,
				"Some ATP energy is used to start the process of glucose oxidation.");
			
				p.addAnswer(5, "FADH<sub>2</sub>",
				false,
				"FADH<sub>2</sub> is a product of the citric acid cycle");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334533;


		
		

		
			
			p.question = "In glycolysis there is a net gain of _____ ATP. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?9&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Glycolysis</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "1",
				false,
				"More.");
			
				p.addAnswer(2, "2",
				true,
				"It takes 2 ATP to produce 4 ATP");
			
				p.addAnswer(3, "3",
				false,
				"Less.");
			
				p.addAnswer(4, "4",
				false,
				"This is the total number of ATP produced by glycolysis.");
			
				p.addAnswer(5, "5",
				false,
				"Less.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334534;


		
		

		
			
			p.question = "Which of these enters the citric acid cycle? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?9&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Citric Acid Cycle</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "NADH + H<sup>+</sup>",
				false,
				"NADH + H<sup>+</sup> is a product of the citric acid cycle.");
			
				p.addAnswer(2, "acetyl CoA",
				true,
				"Acetyl CoA is a reactant in the citric acid cycle.");
			
				p.addAnswer(3, "G3P",
				false,
				"G3P is an intermediary in glycolysis.");
			
				p.addAnswer(4, "pyruvate",
				false,
				"Pyruvate must be converted to another compound that will then enter the citric acid cycle.");
			
				p.addAnswer(5, "glucose",
				false,
				"Glucose enters glycolysis.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334535;


		
		

		
			
			p.question = "How does pyruvate enter a mitochondrion? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?9&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Citric Acid Cycle</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "osmosis",
				false,
				"Osmosis is the diffusion of water.");
			
				p.addAnswer(2, "phagocytosis",
				false,
				"Refer to the Chapter 7 activity on exocytosis and endocytosis.");
			
				p.addAnswer(3, "pinocytosis",
				false,
				"Refer to the Chapter 7 activity on exocytosis and endocytosis.");
			
				p.addAnswer(4, "exocytosis",
				false,
				"Refer to the Chapter 7 activity on exocytosis and endocytosis.");
			
				p.addAnswer(5, "diffusion",
				true,
				"Pyruvate diffuses from the cytosol into a mitochondrion.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334536;


		
		

		
			
			p.question = "In the citric acid cycle, ATP molecules are produced by _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?9&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Citric Acid Cycle</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "photophosphorylation",
				false,
				"Light is not directly involved in the citric acid cycle.");
			
				p.addAnswer(2, "substrate-level phosphorylation",
				true,
				"A phosphate group is transferred from GTP to ADP.");
			
				p.addAnswer(3, "cellular respiration",
				false,
				"You need to be more specific.");
			
				p.addAnswer(4, "oxidative phosphorylation",
				false,
				"This process utilizes energy released by electron transport.");
			
				p.addAnswer(5, "photosynthesis",
				false,
				"Photosynthesis is not a component of the citric acid cycle.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334537;


		
		

		
			
			p.question = "Which of these is NOT a product of the citric acid cycle? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?9&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Citric Acid Cycle</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "ATP",
				false,
				"The citric acid cycle produces ATP.");
			
				p.addAnswer(2, "NADH + H<sup>+</sup>",
				false,
				"The citric acid  cycle produces NADH + H<sup>+</sup>.");
			
				p.addAnswer(3, "FADH<sub>2</sub>",
				false,
				"The citric acid cycle produces FADH<sub>2</sub>.");
			
				p.addAnswer(4, "CO<sub>2</sub>",
				false,
				"The citric acid cycle releases CO<sub>2</sub>.");
			
				p.addAnswer(5, "acetyl CO<sub>2</sub>",
				true,
				"Acetyl CoA enters the citric acid cycle.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334538;


		
		

		
			
			p.question = "For each glucose that enters glycolysis, _____ acetyl CoA enter the citric acid cycle. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?9&E','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Electron Transport</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "0",
				false,
				"Acetyl CoA is a reactant in the citric acid cycle.");
			
				p.addAnswer(2, "1",
				false,
				"Consider how many pyruvate molecules are produced per glucose.");
			
				p.addAnswer(3, "2",
				true,
				"Each glucose produces two pyruvates, each of which is converted into acetyl CoA.");
			
				p.addAnswer(4, "4",
				false,
				"Consider how many pyruvate molecules are produced per glucose.");
			
				p.addAnswer(5, "5",
				false,
				"Consider how many pyruvate molecules are produced per glucose.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334539;


		
		

		
			
			p.question = "For each glucose that enters glycolysis, _____ NADH + H<sup>+</sup> are produced by the citric acid cycle. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?9&E','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Electron Transport</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "0",
				false,
				"NADH + H<sup>+</sup> is produced by the citric acid cycle.");
			
				p.addAnswer(2, "2",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(3, "3",
				false,
				"Per glucose, not per turn of the citric acid cycle.");
			
				p.addAnswer(4, "6",
				true,
				"3 NADH + H<sup>+</sup> are produced per each acetyl CoA that enters the citric acid cycle.");
			
				p.addAnswer(5, "3 to 6",
				false,
				"Pick one.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334540;


		
		

		
			
			p.question = "In cellular respiration, most ATP molecules are produced by _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?9&E','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Electron Transport</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "photophosphorylation",
				false,
				"Light is not directly involved in cellular respiration.");
			
				p.addAnswer(2, "substrate-level phosphorylation",
				false,
				"This is how ATP is produced in both glycolysis and the citric acid cycle.");
			
				p.addAnswer(3, "cellular respiration",
				false,
				"You need to be more specific.");
			
				p.addAnswer(4, "oxidative phosphorylation",
				true,
				"This process utilizes energy released by electron transport.");
			
				p.addAnswer(5, "photosynthesis",
				false,
				"Photosynthesis is not a component of cellular respiration.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334541;


		
		

		
			
			p.question = "The final electron acceptor of cellular respiration is _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?9&E','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Electron Transport</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "water",
				false,
				"You\'re close; No, that is incorrect.");
			
				p.addAnswer(2, "oxygen",
				true,
				"Oxygen is combined with electrons and hydrogen to form water.");
			
				p.addAnswer(3, "FADH<sub>2</sub>",
				false,
				"FADH<sub>2</sub> is an electron acceptor but not the final one.");
			
				p.addAnswer(4, "CO<sub>2</sub>",
				false,
				"CO<sub>2</sub> is not the final electron acceptor of cellular respiration.");
			
				p.addAnswer(5, "NADH",
				false,
				"NADH is an electron acceptor but not the final one.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334542;


		
		

		
			
			p.question = "During electron transport, energy from _____ is used to pump hydrogen ions into the _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?9&E','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Electron Transport</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "NADH and FADH<sub>2</sub> ... intermembrane space",
				true,
				"The energy released as electrons, which have been donated by NADH and FADH<sub>2</sub>, is passed along the electron transport chain and used to pump hydrogen ions into the intermembrane space.");
			
				p.addAnswer(2, "NADH and FADH<sub>2</sub> ... mitochondrial matrix",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(3, "NADH ... intermembrane space",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(4, "NADH ... mitochondrial matrix",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(5, "acetyl CoA ... intermembrane space",
				false,
				"This choice is partially correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334543;


		
		

		
			
			p.question = "Structure A is _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?9&E','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Electron Transport</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0922q.jpg\" ALT=\"Question #22\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "an electron donor",
				false,
				"Consider the structure of this protein.");
			
				p.addAnswer(2, "ATP synthase",
				true,
				"ATP synthase phosphorylates ADP.");
			
				p.addAnswer(3, "phospholipid",
				false,
				"However, this protein is embedded in a phospholipid membrane.");
			
				p.addAnswer(4, "sensory protein",
				false,
				"Consider the structure of this protein..");
			
				p.addAnswer(5, "an electron acceptor",
				false,
				"Consider the structure of this protein.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334544;


		
		

		
			
			p.question = "The proximate (immediate) source of energy for oxidative phosphorylation is _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?9&E','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Electron Transport</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "kinetic energy that is released as hydrogen ions diffuse down their concentration gradient",
				true,
				"Concentration gradients are a form of potential energy.");
			
				p.addAnswer(2, "substrate-level phosphorylation",
				false,
				"However, like oxidative phosphorylation, substrate-level phosphorylation produces ATP.");
			
				p.addAnswer(3, "NADH and FADH<sub>2</sub>",
				false,
				"These molecules provide high-energy electrons to the electron transport chain.");
			
				p.addAnswer(4, "ATP synthase",
				false,
				"ATP synthase is an enzyme.");
			
				p.addAnswer(5, "ATP",
				false,
				"ATP molecules are produced by oxidative phosphorylation.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334545;


		
		

		
			
			p.question = "In muscle cells, fermentation produces _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?9&F','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Fermentation</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "pyruvate",
				false,
				"Pyruvate is a reactant in fermentation.");
			
				p.addAnswer(2, "carbon dioxide, ethanol, NAD<sup>+</sup>, and ATP",
				false,
				"These are the products of fermentation as it occurs in yeast cells.");
			
				p.addAnswer(3, "carbon dioxide, ethanol, NADH, and ATP",
				false,
				"Fermentation oxidizes NADH.");
			
				p.addAnswer(4, "carbon dioxide, lactate, NAD<sup>+</sup>, and ATP",
				true,
				"These are the products of fermentation as it occurs in muscle cells.");
			
				p.addAnswer(5, "carbon dioxide, lactate, NADH, and ATP",
				false,
				"Fermentation oxidizes NADH.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334546;


		
		

		
			
			p.question = "In fermentation _____ is reduced and _____ is oxidized. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?9&F','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Fermentation</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "lactate ... NADH",
				false,
				"Fermentation does not reduce lactate.");
			
				p.addAnswer(2, "NAD<sup>+</sup> ... pyruvate",
				false,
				"Fermentation does not oxidize pyruvate.");
			
				p.addAnswer(3, "pyruvate ... NADH",
				true,
				"The pyruvate from glycolysis is reduced to either lactate or ethanol, and NADH is oxidized to NAD<sup>+</sup>.");
			
				p.addAnswer(4, "lactate ... ethanol",
				false,
				"Fermentation does not reduce lactate.");
			
				p.addAnswer(5, "NADH ... lactate",
				false,
				"Fermentation does not reduce NADH.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

