

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "Investigation Quiz > How Do You Diagnose a Genetic Disorder?";
	ak.quiz_loc_with_commas = "Investigation Quiz, How Do You Diagnose a Genetic Disorder?";
	ak.quiz_title = "How Do You Diagnose a Genetic Disorder?";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 9;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 9;
	ak.non_essay_total = 0;
	ak.scored_item_total = 0;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337625;


		
		

		
			p.question = "Draw some general conclusions about what you think might be happening to Mrs. B. Which of her organs might be affected, causing the behavior you observed?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337626;


		
		

		
			p.question = "Is Mrs. B\'s condition dominant or recessive? Support your conclusion with evidence.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337627;


		
		

		
			p.question = "Based on the anatomical information available to you, how might you explain the symptoms of Mrs. B.\'s condition, Huntington\'s disease?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337628;


		
		

		
			p.question = "What properties of these chromosomes have geneticists used to put the chromosomes in order?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337629;


		
		

		
			p.question = "How might the mutation causing HD change the structure of the huntingtin protein? Write a possible hypothesis.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337630;


		
		

		
			p.question = "How is the amino acid sequence of the protein changed in a person with this condition?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337631;


		
		

		
			p.question = "Using everything you\'ve learned throughout this activity, what is the most fundamental difference between people who do and don\'t have this disease?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337632;


		
		

		
			p.question = "Compare the numbers of base pairs between the two cut sites on the normal HD gene and the mutant gene.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337633;


		
		

		
			p.question = "Hypothesize about how you could use this information to diagnose HD.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

