

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "41: Animal Nutrition > Practice Test";
	ak.quiz_loc_with_commas = "41: Animal Nutrition, Practice Test";
	ak.quiz_title = "Practice Test";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 42;
	ak.non_essay_total = 42;
	ak.scored_item_total = 42;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336373;


		
		

		
			
			p.question = "Which food items are typical of an herbivorous diet? (<script type=\"text/javascript\">ebook(\'41OV\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "eggs, insects, fruit",
				false,
				"No. Eggs and insects are not plants.");
			
				p.addAnswer(2, "nuts, leaves, berries",
				true,
				"Correct. An herbivore is a vegetarian, eating plants or plant parts.");
			
				p.addAnswer(3, "insects, worms, beetles",
				false,
				"No. These represent a diet of invertebrates, not of plants.");
			
				p.addAnswer(4, "mice, snakes, birds",
				false,
				"No. This is the diet of a predatory animal that feasts on other animals.");
			
				p.addAnswer(5, "decomposed dung, rotted vegetation, soil bacteria",
				false,
				"No. These do not qualify as part of an herbivorous diet, but some animals do eat them.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336374;


		
		

		
			
			p.question = "Which one of the following is acquired outside of an animal\'s diet? (<script type=\"text/javascript\">ebook(\'4101\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "oxygen",
				true,
				"Correct. Although oxygen is essential to all animals, it is not obtained in the diet.");
			
				p.addAnswer(2, "organic molecules",
				false,
				"No. These are required in the diet.");
			
				p.addAnswer(3, "chemical energy",
				false,
				"No. This is required in the diet.");
			
				p.addAnswer(4, "essential nutrients",
				false,
				"No. These are required in the diet.");
			
				p.addAnswer(5, "All the choices are needs that must be supplied through diet.",
				false,
				"No. One of the choices is not obtained in the diet.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336375;


		
		

		
			
			p.question = "Animals need two types of organic precursors from their food. These are _____ and _____. (<script type=\"text/javascript\">ebook(\'4101\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "organic carbon and organic nitrogen",
				true,
				"Correct.");
			
				p.addAnswer(2, "organic hydrogen and organic oxygen",
				false,
				"No. Neither of these is correct.");
			
				p.addAnswer(3, "organic carbon and organic hydrogen",
				false,
				"No. One of these is correct.");
			
				p.addAnswer(4, "organic carbon and organic oxygen",
				false,
				"No. One of these is correct.");
			
				p.addAnswer(5, "organic nitrogen and organic oxygen",
				false,
				"No. One of these is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336376;


		
		

		
			
			p.question = "A breakfast cereal advertises that it contains essential vitamins and minerals. In this context, the word \"essential\" means _____. (<script type=\"text/javascript\">ebook(\'4101\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "that it contains the essence of vegetables used to extract the nutrients",
				false,
				"No. The word \"essential\" has another meaning.");
			
				p.addAnswer(2, "that they can be made in the body but it is important to eat food containing these nutrients so that we do not waste essential energy in making them",
				false,
				"No. This is not the definition of an essential nutrient.");
			
				p.addAnswer(3, "that the nutrients must be supplied in the diet and cannot be made in the body",
				true,
				"Correct. Essential nutrients are materials that must be obtained in preassembled form because the animal\'s cells cannot make them from raw materials.");
			
				p.addAnswer(4, "that it is important that you believe what is stated on the package and buy the product",
				false,
				"No. Hopefully, the nutritional information on the package is accurate. However, that does not mean that any particular food item is the only way you can meet your essential nutrient needs.");
			
				p.addAnswer(5, "nothing: this is just a gimmick",
				false,
				"No. It has a significant meaning.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336377;


		
		

		
			
			p.question = "Which of the following are considered essential nutrients? (1) certain carbohydrates, (2) certain fatty acids, (3) certain amino acids, (4) cholesterol (<script type=\"text/javascript\">ebook(\'4101\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "1, 2, 3, and 4",
				false,
				"No. There are no essential carbohydrates.<b> </b>Cholesterol is not an essential nutrient.");
			
				p.addAnswer(2, "1, 2, and 3",
				false,
				"No. There are no essential carbohydrates.");
			
				p.addAnswer(3, "2, 3, and 4",
				false,
				"No. Cholesterol is not an essential nutrient.");
			
				p.addAnswer(4, "2 and 3",
				true,
				"Correct. There are four classes of essential nutrients: essential amino acids, essential fatty acids, vitamins, and minerals.");
			
				p.addAnswer(5, "3",
				false,
				"No. Although this is correct, there is a better choice.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336378;


		
		

		
			
			p.question = "In general, B vitamins function in your body as _____. (<script type=\"text/javascript\">ebook(\'4101\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a source of energy",
				false,
				"No. Vitamins are not a source of energy.");
			
				p.addAnswer(2, "structural components of cell membranes",
				false,
				"No. Other molecules form cell membranes.");
			
				p.addAnswer(3, "a source of minerals",
				false,
				"No. B vitamins are not broken down into something else.");
			
				p.addAnswer(4, "coenzymes",
				true,
				"Correct. Vitamins are organic molecules required in the diet in small amounts and often function as coenzymes in key metabolic processes.");
			
				p.addAnswer(5, "antioxidants",
				false,
				"No. However, other vitamins have antioxidant properties.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336379;


		
		

		
			
			p.question = "Why is it important to consume B vitamins every day, but not A vitamins? (<script type=\"text/javascript\">ebook(\'4101\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "B vitamins are an essential nutrient, and vitamin A is not.",
				false,
				"No. Both vitamins are essential.");
			
				p.addAnswer(2, "Vitamin A can be stored by the body, but B vitamins cannot.",
				true,
				"Correct. B vitamins are water-soluble vitamins. They are rapidly excreted through the kidneys and should be replenished daily.");
			
				p.addAnswer(3, "The body needs much larger amounts of B vitamins than vitamin A.",
				false,
				"No. Both are needed in only small amounts.");
			
				p.addAnswer(4, "The body requires B vitamins, but vitamin A is just an \"extra.\"",
				false,
				"No. A deficiency of vitamin A will result in a variety of problems, such as impaired vision.");
			
				p.addAnswer(5, "Vitamin A is water-soluble, and B vitamins are fat-soluble.",
				false,
				"No. Just the opposite is true. Why would fat solubility or water solubility be important?");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336380;


		
		

		
			
			p.question = "The fat-soluble vitamins include _____. (<script type=\"text/javascript\">ebook(\'4101\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "vitamins A, D, E, and K",
				true,
				"Correct. Fat-soluble vitamins are A, D, E, and K.");
			
				p.addAnswer(2, "vitamin A and the B group",
				false,
				"No. B vitamins are water-soluble.");
			
				p.addAnswer(3, "the B vitamins and vitamin C",
				false,
				"No. The B vitamins and vitamin C are water-soluble.");
			
				p.addAnswer(4, "vitamins C, D, E, and K",
				false,
				"No. Vitamin C is water-soluble.");
			
				p.addAnswer(5, "riboflavin and niacin",
				false,
				"No. Both of these are B vitamins, which are water-soluble.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336381;


		
		

		
			
			p.question = "_____ are needed in the diet as components of teeth and bone, as parts of certain enzymes, for normal muscle and nerve function, and for water balance. (<script type=\"text/javascript\">ebook(\'4101\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Starches",
				false,
				"No. Starch is the form in which plants store their carbohydrates. It is not a component of teeth, bones, enzymes, and so on.");
			
				p.addAnswer(2, "Fats",
				false,
				"No. Fats are used to cushion, insulate, store energy, and construct membranes.");
			
				p.addAnswer(3, "Minerals",
				true,
				"Correct. Minerals are also necessary for some hormones, for oxygen transport, and in nucleic acids and ATP.");
			
				p.addAnswer(4, "Nucleic acids",
				false,
				"No. Nucleic acids are needed for DNA and RNA. These molecules carry genetic information and participate in the synthesis of proteins.");
			
				p.addAnswer(5, "Vitamins",
				false,
				"No. Vitamins generally function as cofactors, as do some minerals, but they do not function as structural components in bone or teeth.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336382;


		
		

		
			
			p.question = "An insufficient supply of chemical energy in the diet results in _____ while a shortage of one or more essential nutrients results in _____. (<script type=\"text/javascript\">ebook(\'4101\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "malnourishment; undernourishment",
				false,
				"No. Correct terms but reversed order.");
			
				p.addAnswer(2, "undernourishment; malnourishment",
				true,
				"Correct.");
			
				p.addAnswer(3, "mesonourishment; ectonourishment",
				false,
				"No. Neither is correct.");
			
				p.addAnswer(4, "hypernourishment; hyponourishment",
				false,
				"No. Neither is correct.");
			
				p.addAnswer(5, "hyponourishment; hypernourishment",
				false,
				"No. Neither is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336383;


		
		

		
			
			p.question = "Despite long days grazing on tall grasses, the cattle released into a new pasture do not grow well. Several have oddly shaped or broken legs and often lay down. These cattle might be suffering from _______. (<script type=\"text/javascript\">ebook(\'4101\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "undernourishment, not getting enough carbohydrates in their diet",
				false,
				"No. A shortage of carbohydrates would not likely affect bone structure in this way. Further, the grasses in the pasture probably provide good amounts of carbohydrates.");
			
				p.addAnswer(2, "undernourishment, not getting enough protein in their diet",
				false,
				"No. A shortage of protein would not likely affect bone structure in this way. Further, the grasses in the pasture probably provide good amounts of protein.");
			
				p.addAnswer(3, "undernourishment, not getting enough fat in their diet",
				false,
				"No. A shortage of fat would not likely affect bone structure.");
			
				p.addAnswer(4, "malnourishment, not getting enough phosphorus in their diet",
				true,
				"Correct.");
			
				p.addAnswer(5, "malnourishment, not getting enough vitamin A in their diet",
				false,
				"No. Vitamin A would likely lead to problems with vision.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336384;


		
		

		
			
			p.question = "Which one of the following statements about nutrition and digestion is <b>true</b>? (<script type=\"text/javascript\">ebook(\'4102\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "\"Feeding\" and \"digestion\" are synonyms.",
				false,
				"No. \"Feeding\" refers to the act of eating or ingestion, whereas \"digestion\" means breaking down food into molecules small enough to be absorbed by the body.");
			
				p.addAnswer(2, "Chemical digestion typically precedes physical digestion in wolves.",
				false,
				"No. \"Physical digestion\" means breaking down food into smaller chunks by chewing or grinding. Wolves tear up their food before it is chemically digested.");
			
				p.addAnswer(3, "During absorption, small molecules such as amino acids and simple sugars are absorbed.",
				true,
				"Correct. Food substances that have been chemically broken down into their smaller components move through the intestinal walls into the blood. This is absorption.");
			
				p.addAnswer(4, "Elimination rids the body of excessive nutrients.",
				false,
				"No. Elimination rids the body of undigestible food residues. Excessive nutrients such as fats and sugars are often stored in the body.");
			
				p.addAnswer(5, "Small sugars are joined by enzymatic hydrolysis to form large carbohydrates.",
				false,
				"No. The reverse is true. Large carbohydrates are split by enzymatic hydrolysis to form small sugars.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336385;


		
		

		
			
			p.question = "Which one of the following statements is true? (<script type=\"text/javascript\">ebook(\'4102\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The last stage of food processing is absorption.",
				false,
				"No. The last stage of food processing is elimination.");
			
				p.addAnswer(2, "Ingestion breaks down food into molecules small enough for the body to absorb.",
				false,
				"No. Digestion breaks down food into molecules small enough for the body to absorb.");
			
				p.addAnswer(3, "Absorption breaks bonds using enzymatic hydrolysis.",
				false,
				"No. Digestion breaks bonds using enzymatic hydrolysis.");
			
				p.addAnswer(4, "Ingestion is the act of eating.",
				true,
				"Correct.");
			
				p.addAnswer(5, "Undigested materials pass out of the alimentary canal by absorption.",
				false,
				"No. Undigested materials pass out of the alimentary canal by elimination.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336386;


		
		

		
			
			p.question = " Which of the following animals have a one-way digestive tract? (<script type=\"text/javascript\">ebook(\'4102\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "earthworm",
				true,
				"Correct. These animals have a complete digestive tract in which food moves only in one direction.");
			
				p.addAnswer(2, "sponges",
				false,
				"No. Sponges have no digestive tract. Sponges digest their food entirely through intracellular mechanisms.");
			
				p.addAnswer(3, "jellyfish",
				false,
				"No. These animals have a gastrovascular cavity with only a single opening. Food moves into and out of the cavity through the same opening.");
			
				p.addAnswer(4, "sea anemones",
				false,
				"No. These animals have a gastrovascular cavity with only a single opening. Food moves into and out of the cavity through the same opening.");
			
				p.addAnswer(5, "flatworms",
				false,
				"No. These animals have a gastrovascular cavity with only a single opening. Food moves into and out of the cavity through the same opening.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336387;


		
		

		
			
			p.question = "Which of the following animals uses only intracellular digestion? (<script type=\"text/javascript\">ebook(\'4102\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "earthworm",
				false,
				"No. These animals have a complete digestive tract that permits extracellular digestion.");
			
				p.addAnswer(2, "sponges",
				true,
				"Correct. Sponges have no digestive tract. Sponges digest their food entirely through intracellular mechanisms.");
			
				p.addAnswer(3, "jellyfish",
				false,
				"No. These animals have a gastrovascular cavity that permits extracellular digestion.");
			
				p.addAnswer(4, "sea anemones",
				false,
				"No. These animals have a gastrovascular cavity that permits extracellular digestion.");
			
				p.addAnswer(5, "flatworms",
				false,
				"No. These animals have a gastrovascular cavity that permits extracellular digestion.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336388;


		
		

		
			
			p.question = "In vertebrates, food is moved along the length of the digestive system by _____. (<script type=\"text/javascript\">ebook(\'4103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "active transport across cell membranes",
				false,
				"No. This is how some nutrients are absorbed.");
			
				p.addAnswer(2, "peristalsis",
				true,
				"Correct. Peristalsis, rhythmic waves of contraction by smooth muscles in the wall of the alimentary canal, pushes food along the tract.");
			
				p.addAnswer(3, "diffusion and osmosis",
				false,
				"No. This is how some nutrients are absorbed.");
			
				p.addAnswer(4, "sequential contraction of bands of skeletal muscles",
				false,
				"No. The digestive tract is lined by smooth muscle.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. Only one of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336389;


		
		

		
			
			p.question = "Chemical digestion of carbohydrates begins in the _____ with the action of _____. (<script type=\"text/javascript\">ebook(\'4103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "mouth; salivary amylase",
				true,
				"Correct. Saliva contains salivary amylase, a digestive enzyme that hydrolyzes starch and glycogen.");
			
				p.addAnswer(2, "stomach; hydrochloric acid",
				false,
				"No. Carbohydrate digestion begins before the food enters the stomach.");
			
				p.addAnswer(3, "small intestine; lipase",
				false,
				"No. Carbohydrate digestion begins before the food enters the small intestine, and lipase is not responsible for carbohydrate digestion.");
			
				p.addAnswer(4, "small intestine; pancreatic amylase",
				false,
				"No. Carbohydrate digestion begins before the food enters the small intestine.");
			
				p.addAnswer(5, "large intestine; salivary amylase",
				false,
				"No. This is not where carbohydrate digestion begins.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336390;


		
		

		
			
			p.question = "The tongue does all of the following <b>except</b> _____. (<script type=\"text/javascript\">ebook(\'4103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "taste food",
				false,
				"No. Taste buds are located on the tongue.");
			
				p.addAnswer(2, "manipulate food within the mouth",
				false,
				"No. The tongue does this.");
			
				p.addAnswer(3, "shape food into a bolus",
				false,
				"No. The tongue does this.");
			
				p.addAnswer(4, "secrete saliva",
				true,
				"Correct. The tongue tastes food, manipulates it during chewing, and helps shape it into a ball called a bolus, but the tongue does not contain salivary ducts.");
			
				p.addAnswer(5, "push food into the pharynx to begin swallowing",
				false,
				"No. The tongue does this.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336391;


		
		

		
			
			p.question = "How is the stomach lining protected from the strongly acidic pH of its contents? (<script type=\"text/javascript\">ebook(\'4103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "It releases a hormone called gastrin, which stops gastric juice secretion.",
				false,
				"No. Gastrin stimulates gastric juice production, decreasing the pH.");
			
				p.addAnswer(2, "Mucous cells secrete a protective lubricant into the stomach.",
				true,
				"Correct. The mucus protects the stomach lining from pepsin and acid.");
			
				p.addAnswer(3, "Bile neutralizes the acid soon after it enters the stomach.",
				false,
				"No. Bile is not released into the stomach. It is released into the small intestine. In addition, bile would do little to neutralize stomach acids.");
			
				p.addAnswer(4, "Parietal cells secrete a protective buffer to neutralize hydrochloric acid.",
				false,
				"No. Parietal cells actually secrete HCl into the stomach.");
			
				p.addAnswer(5, "The acid is neutralized quickly when it combines with pepsinogen to make pepsin.",
				false,
				"No. The presence of HCl converts pepsinogen into its active form, pepsin, but the HCl is not neutralized.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336392;


		
		

		
			
			p.question = "Which one of the following statements regarding protein digestion is true? (<script type=\"text/javascript\">ebook(\'4103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Protein digestion begins in the small intestine.",
				false,
				"No. Protein digestion begins in the stomach.");
			
				p.addAnswer(2, "Active pepsin is formed in the lumen of the stomach, where it helps to break down proteins.",
				true,
				"Correct.");
			
				p.addAnswer(3, "Protein digestion is dependent on amylase from parietal cells of the stomach.",
				false,
				"No. Protein digestion is dependent on HCl from parietal cells of the stomach.");
			
				p.addAnswer(4, "Protein digestion occurs at a pH of about 7.0.",
				false,
				"No. Protein digestion occurs at a pH of about 2.0.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the statements is true.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336393;


		
		

		
			
			p.question = "Which of the following might make the most effective anti-ulcer medication? (<script type=\"text/javascript\">ebook(\'4103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a chemical that stimulates the parietal cells of the gastric pits",
				false,
				"No. Parietal cells produce HCl, which both activates pepsin and directly attacks the epithelial layer of the stomach.");
			
				p.addAnswer(2, "a chemical that kills bacteria in the stomach",
				true,
				"Correct. Most gastric ulcers result from damage to the stomach lining caused by the acid-tolerant bacterium <i>Helicobacter pylori</i>.");
			
				p.addAnswer(3, "a chemical that inhibits epithelial cells in the stomach that produce mucus",
				false,
				"No. Mucus is an important way that the stomach lining is protected from the actions of pepsin and HCl.");
			
				p.addAnswer(4, "a chemical that stimulates the secretion of bile",
				false,
				"No. There is no evidence that bile kills <i>Helicobacter pylori</i>, and even if there were such evidence, bile is released into the small intestine, not the stomach.");
			
				p.addAnswer(5, "a chemical that stimulates the chief cells of the gastric pits",
				false,
				"No. Chief cells produce pepsinogen. When activated by HCl, pepsinogen becomes pepsin, a potent hydrolytic enzyme. Much of the damage caused by an ulcer is related to the action of pepsin on the stomach lining.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336394;


		
		

		
			
			p.question = "Acid chyme _____. (<script type=\"text/javascript\">ebook(\'4103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "contains digested fat",
				false,
				"No. Fat is not digested until acid chyme is neutralized in the duodenum.");
			
				p.addAnswer(2, "is a mush made from boluses and hydrolytic enzymes secreted by the pancreas and duodenum",
				false,
				"No. The chyme is not acid, but neutralized, when it encounters these enzymes in the small intestine.");
			
				p.addAnswer(3, "contains food and gastric juice and moves through the pyloric sphincter",
				true,
				"Correct. This is acid chyme as it leaves the stomach.");
			
				p.addAnswer(4, "causes gastric ulcers",
				false,
				"No. A bacterium is thought to be the cause of stomach ulcers, which are subsequently irritated by acid chyme.");
			
				p.addAnswer(5, "passes into the large intestine, where water is removed",
				false,
				"No. By the time undigested food reaches this point, it is called feces.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336395;


		
		

		
			
			p.question = "Which of the following is properly matched with its product? (<script type=\"text/javascript\">ebook(\'4103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "peristalsis; heartburn",
				false,
				"No. Acid reflux is responsible for heartburn.");
			
				p.addAnswer(2, "mucous cells; pepsinogen",
				false,
				"No. Mucous cells in the glands of the stomach wall produce mucus.");
			
				p.addAnswer(3, "parietal cells; gastrin",
				false,
				"No. Parietal cells in the glands of the stomach wall produce hydrochloric acid.");
			
				p.addAnswer(4, "chief cells; vomiting",
				false,
				"No. Chief cells in the glands of the stomach wall produce pepsinogen.");
			
				p.addAnswer(5, "acid chyme backflow; heartburn",
				true,
				"Correct. Acid chyme backflow into the lower esophagus makes the feeling we call heartburn, which is actually \"esophagusburn.\"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336396;


		
		

		
			
			p.question = "In humans, most nutrient molecules are absorbed by the _____. (<script type=\"text/javascript\">ebook(\'4103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "stomach",
				false,
				"No. Some molecules, such as ethanol, are absorbed in the stomach, but certainly not most. The stomach plays a role in protein digestion.");
			
				p.addAnswer(2, "liver",
				false,
				"No. The liver is not directly connected with the alimentary canal.");
			
				p.addAnswer(3, "small intestine",
				true,
				"Correct. The small intestine has a tremendous amount of surface area, by virtue of the intestinal villi, which greatly improves the absorption of molecules.");
			
				p.addAnswer(4, "large intestine",
				false,
				"No. The large intestine is the site of some water absorption, but not much nutrient absorption.");
			
				p.addAnswer(5, "pancreas",
				false,
				"No. The pancreas is not directly connected with the alimentary canal except through the pancreatic duct. Pancreatic enzymes and sodium bicarbonate enter the small intestine at this location.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336397;


		
		

		
			
			p.question = "The liver and pancreas add their secretions to the partially digested food produced in the stomach, in the _____ of the small intestine. (<script type=\"text/javascript\">ebook(\'4103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "sphincter",
				false,
				"No. The pyloric sphincter helps regulate the passage of chyme into the small intestine.");
			
				p.addAnswer(2, "duodenum",
				true,
				"Correct. The pancreas, liver, and gallbladder add their secretions to the duodenum, the first 25 cm or so of the human small intestine.");
			
				p.addAnswer(3, "jejunum",
				false,
				"No. This is the middle region of the small intestine. This section functions mainly in the absorption of nutrients and water.");
			
				p.addAnswer(4, "ileum",
				false,
				"No. This is the last region of the small intestine. This section functions mainly in the absorption of nutrients and water.");
			
				p.addAnswer(5, "colon",
				false,
				"No. This is another term for the large intestine.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336398;


		
		

		
			
			p.question = "Most digestive enzymes function in the _____. (<script type=\"text/javascript\">ebook(\'4103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "large intestine",
				false,
				"No. A function of the large intestine is to recover the water used as a solvent for the various digestive juices.");
			
				p.addAnswer(2, "oral cavity",
				false,
				"No. However, the salivary amylase enzyme is a component of saliva.");
			
				p.addAnswer(3, "stomach",
				false,
				"No. Although a limited amount of enzymatic activity occurs here, most chemical digestion occurs elsewhere.");
			
				p.addAnswer(4, "gallbladder",
				false,
				"No. The gallbladder stores bile produced in the liver, but bile is not an enzyme, and it is discharged into the alimentary canal.");
			
				p.addAnswer(5, "small intestine",
				true,
				"Correct. Enzymes primarily from the pancreas complete the digestion of almost all foods within the small intestine.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336399;


		
		

		
			
			p.question = "The natural antacid that protects the intestines against stomach acid is produced by the ______. (<script type=\"text/javascript\">ebook(\'4103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "stomach",
				false,
				"No. The stomach is a highly acidic environment.");
			
				p.addAnswer(2, "liver",
				false,
				"No. The liver secretes bile.");
			
				p.addAnswer(3, "esophagus",
				false,
				"No. The esophagus does not secrete substances that play a role in the digestive process.");
			
				p.addAnswer(4, "pancreas",
				true,
				"Correct. The pancreas produces several hydrolytic enzymes and an alkaline solution rich in bicarbonate that offset the acidity of chyme from the stomach.");
			
				p.addAnswer(5, "small intestine",
				false,
				"No. But this is where the natural antacid is added.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336400;


		
		

		
			
			p.question = "Pepsin is an enzyme produced in the stomach that attacks proteins to break them down into smaller peptide molecules. Which one of the following statements about this enzyme is true? (<script type=\"text/javascript\">ebook(\'4103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The activity of pepsin will speed up in the small intestine because the pH becomes less acidic.",
				false,
				"No. Pepsinogen is secreted by, and pepsin acts in, the stomach.");
			
				p.addAnswer(2, "Pepsin will continue to work at the same rate as it moves through the intestines until all the protein is broken down.",
				false,
				"No. Pepsin works best at a low pH. The pH of the small intestine is much higher.");
			
				p.addAnswer(3, "Pepsin will cease to function in the small intestine as basic secretions from the pancreas neutralize the pH.",
				true,
				"Correct. Pepsin is one of the few enzymes that work best in a strongly acidic environment.");
			
				p.addAnswer(4, "Salivary amylase activates pepsin, converting it to a functioning form in the stomach.",
				false,
				"No. Salivary amylase plays no such role.");
			
				p.addAnswer(5, "The activity of pepsin will speed up in the small intestine because the pH becomes less acidic, and pepsin will continue to work at the same rate as it moves through the intestines until all the protein is broken down.",
				false,
				"No. Pepsinogen is secreted by, and pepsin acts in, the stomach.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336401;


		
		

		
			
			p.question = "Gallstone surgery sometimes requires that the gallbladder be removed. Patients are then advised to avoid ingesting large amounts of fat because _____. (<script type=\"text/javascript\">ebook(\'4103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the gallbladder makes bile, which is necessary for fat emulsification",
				false,
				"No. Bile is produced in the liver. It is stored in the gallbladder.");
			
				p.addAnswer(2, "without the bile produced by the gallbladder, fats cannot be enzymatically hydrolyzed",
				false,
				"No. Bile is not an enzyme, nor is it produced by the gallbladder.");
			
				p.addAnswer(3, "the gallbladder produces the hormone enterogastrone, necessary to digest fats",
				false,
				"No. However, enterogastrone does slow the rate of movement through the small intestine, which is helpful for fat digestion. In addition, enterogastrone does not promote the chemical breakdown of fats.");
			
				p.addAnswer(4, "the gallbladder stores large quantities of bile, releasing it when fats reach the small intestine",
				true,
				"Correct. Made continuously by the liver and stored by the gallbladder, large amounts of bile can be delivered when fatty chyme is present.");
			
				p.addAnswer(5, "chylomicrons first enter the gallbladder before moving to the liver",
				false,
				"No. Chylomicrons are initially transported by the lymphatic system.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336402;


		
		

		
			
			p.question = "The lungs consist of many small air sacs and blood vessels, which greatly increase surface area and improve the transfer of substances through their walls. The structures in the digestive system similar in function to these air sacs and capillaries are the _____. (<script type=\"text/javascript\">ebook(\'4103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "villi and microvilli",
				true,
				"Correct. The villi and microvilli greatly increase the surface area of the small intestine. Because diffusion is directly proportional to area, this strategy works well in both the respiratory and digestive systems.");
			
				p.addAnswer(2, "esophagus",
				false,
				"No. The structure of the esophagus is not well adapted for absorption or increased surface area.");
			
				p.addAnswer(3, "gastric glands",
				false,
				"No. Gastric glands are the specialized areas within the stomach lining where hydrochloric acid and pepsinogen are produced.");
			
				p.addAnswer(4, "high-density lipoproteins",
				false,
				"No. Think again about the surface area of the lungs and the digestive system.");
			
				p.addAnswer(5, "sphincters",
				false,
				"No. Sphincters are rings of muscle that constrict or relax to regulate the movement of chyme or a bolus through the digestive system.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336403;


		
		

		
			
			p.question = "Which of the following is the actual absorptive surface within the lumen of the small intestine? (<script type=\"text/javascript\">ebook(\'4103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "circular folds",
				false,
				"No. These serve to expand the intestine\'s surface area by providing more space for villi.");
			
				p.addAnswer(2, "blood capillaries",
				false,
				"No. These are within the wall of the microvilli and pick up nutrients that have been absorbed.");
			
				p.addAnswer(3, "liver",
				false,
				"No. The liver receives nutrients from blood vessels, but it is exterior to the small intestine.");
			
				p.addAnswer(4, "fingerlike villi",
				false,
				"No. The villi are covered with an epithelium that bears the true absorptive surface.");
			
				p.addAnswer(5, "microvilli",
				true,
				"Correct. Microvilli are the tiny absorptive projections of the epithelial cells that actually absorb nutrients from the lumen.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336404;


		
		

		
			
			p.question = "Researchers provided radioactively labeled food to a dog and traced the movement of absorbed molecules. Which type of molecule moved along a path different from all the others? (<script type=\"text/javascript\">ebook(\'4103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "carbohydrates",
				false,
				"No. After absorption, carbohydrates move into the hepatic portal vessel, which leads to the liver.");
			
				p.addAnswer(2, "proteins",
				false,
				"No. After absorption, amino acids move into the hepatic portal vessel, which leads to the liver.");
			
				p.addAnswer(3, "nucleic acids",
				false,
				"No. After absorption, nucleotides move into the hepatic portal vessel, which leads to the liver.");
			
				p.addAnswer(4, "fats",
				true,
				"Correct. After absorption, fats mix with cholesterol to form chylomicrons, which enter lacteals and eventually enter the lymphatic system.");
			
				p.addAnswer(5, "All followed the same pathway.",
				false,
				"No. One type of molecule follows a path that does not go directly to the liver.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336405;


		
		

		
			
			p.question = "The lymphatic vessels in the villi absorb and transport _____. (<script type=\"text/javascript\">ebook(\'4103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "chylomicrons",
				true,
				"Correct. A small vessel of the lymphatic system, the lacteal, absorbs fats.");
			
				p.addAnswer(2, "nucleotides",
				false,
				"No. Nucleotides are water-soluble.");
			
				p.addAnswer(3, "monosaccharides",
				false,
				"No. Monosaccharides are water-soluble.");
			
				p.addAnswer(4, "amino acids",
				false,
				"No. Amino acids are water-soluble.");
			
				p.addAnswer(5, "peptides",
				false,
				"No. Peptides are water-soluble.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336406;


		
		

		
			
			p.question = "During some types of antibiotic treatments, patients often experience diarrhea because _____. (<script type=\"text/javascript\">ebook(\'4103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "antibiotics are toxic to the colon\'s epithelium and to bacteria",
				false,
				"No. If antibiotics were toxic, they would be taken as a medicine of last resort.");
			
				p.addAnswer(2, "the bacterial flora of the large intestine that normally break down undigested organic material are killed by the antibiotics",
				true,
				"Correct. Normally, as bacteria digest and assimilate previously undigested organic molecules, the osmotic pressure within the large intestine is reduced, favoring water reabsorption.");
			
				p.addAnswer(3, "antibiotics interfere with the vitamin absorption normally occurring within the large intestine",
				false,
				"No. Although some vitamins are absorbed in the large intestine, the problem is related to water balance.");
			
				p.addAnswer(4, "after intestinal bacteria have been killed, an unusually large amount of water is reabsorbed",
				false,
				"No. If this were true, constipation would become the problem rather than diarrhea.");
			
				p.addAnswer(5, "antibiotics affect the hormones that control intestinal peristalsis",
				false,
				"No. This is not known to be the cause of diarrhea.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336407;


		
		

		
			
			p.question = "Symbiotic bacteria living in our large intestines provide us with _____. (<script type=\"text/javascript\">ebook(\'4103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "carbohydrates",
				false,
				"No. Symbiotic microorganisms help nourish many vertebrates by providing substances such as vitamins.");
			
				p.addAnswer(2, "vitamins",
				true,
				"Correct. Symbiotic microorganisms help nourish many vertebrates by providing substances such as vitamins.");
			
				p.addAnswer(3, "minerals",
				false,
				"No. Symbiotic microorganisms help nourish many vertebrates by providing substances such as vitamins.");
			
				p.addAnswer(4, "calories",
				false,
				"No. Symbiotic microorganisms help nourish many vertebrates by providing substances such as vitamins.");
			
				p.addAnswer(5, "disease resistance",
				false,
				"No. Symbiotic microorganisms help nourish many vertebrates by providing substances such as vitamins.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336408;


		
		

		
			
			p.question = "What relation do indigestible plant fibers, prokaryotes, and vitamins have with the digestive system? (<script type=\"text/javascript\">ebook(\'4103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "They are washed out of the body in the 7 liters of water that daily pass into the digestive system.",
				false,
				"No. Most (90%) of this water does not leave the body and so does not \"cleanse\" the digestive system of its contents.");
			
				p.addAnswer(2, "In the presence of certain vitamins, prokaryotes are able to digest plant fibers.",
				false,
				"No. The vitamins do not make plant fibers more digestible.");
			
				p.addAnswer(3, "The bacteria cause rapid peristalsis, resulting in constipation, which retains plant fibers and vitamins in the lower intestine.",
				false,
				"No. Rapid peristalsis results in diarrhea, not constipation");
			
				p.addAnswer(4, "They are the contents of the large intestine.",
				true,
				"Correct. Indigestible fibers are voided, as are some prokaryotes, and the vitamins produced by the prokaryotes are absorbed into the body.");
			
				p.addAnswer(5, "They move through the terminal portion of the colon together and are voided as feces.",
				false,
				"No. The vitamins are absorbed in the large intestine.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336409;


		
		

		
			
			p.question = "Which one of the following is an adaptation to a carnivorous diet? (<script type=\"text/javascript\">ebook(\'4104\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "sharp, pointed teeth",
				true,
				"Correct. The teeth of carnivores tend to be more pointed and sharper than the teeth of herbivores.");
			
				p.addAnswer(2, "reingestion of feces",
				false,
				"No. This is an adaptation to an herbivorous diet.");
			
				p.addAnswer(3, "longer intestines",
				false,
				"No. This is an adaptation to an herbivorous diet.");
			
				p.addAnswer(4, "a rumen",
				false,
				"No. This is an adaptation to an herbivorous diet.");
			
				p.addAnswer(5, "large populations of symbiotic bacteria and protists in special fermentation chambers in the alimentary canal",
				false,
				"No. This is an adaptation to an herbivorous diet.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336410;


		
		

		
			
			p.question = "How would you expect the digestive system of a hawk to compare with that of a seed-eating sparrow? (<script type=\"text/javascript\">ebook(\'4104\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The hawk would have a larger gastrovascular cavity.",
				false,
				"No. Neither the hawk nor the sparrow would have a gastrovascular cavity. This structure is found in primitive aquatic organisms such as hydra.");
			
				p.addAnswer(2, "The sparrow\'s digestive system would be longer.",
				true,
				"Correct. Plant material is more difficult to digest than animal tissue, so herbivores typically have longer digestive systems than carnivores.");
			
				p.addAnswer(3, "The hawk would have a gizzard, but the sparrow would not.",
				false,
				"No. A gizzard is a specialized area for grinding food; both birds would have a gizzard.");
			
				p.addAnswer(4, "The hawk\'s digestive system would be longer.",
				false,
				"No. The length of the digestive system is related to the digestibility of the food. Plant matter is more difficult to digest.");
			
				p.addAnswer(5, "The hawk would lack a rumen.",
				false,
				"No. Birds do not have rumens; these structures are seen in cattle and sheep. Birds that feed on plant material typically select only the most nutritious parts, such as fruit, nectar, or seeds.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336411;


		
		

		
			
			p.question = "Which of the following animals rely upon symbiotic relationships with bacteria to obtain nutrients? (<script type=\"text/javascript\">ebook(\'4104\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "termites",
				false,
				"No. Although this is correct, there is a better answer.");
			
				p.addAnswer(2, "giant tubeworms",
				false,
				"No. Although this is correct, there is a better answer.");
			
				p.addAnswer(3, "rabbits",
				false,
				"No. Although this is correct, there is a better answer.");
			
				p.addAnswer(4, "sheep",
				false,
				"No. Although this is correct, there is a better answer.");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct. All of these organisms rely upon symbiotic relationships with bacteria to obtain nutrients.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336412;


		
		

		
			
			p.question = "Leptin, an appetite regulator, is produced in _____ and at high levels can lead to _____. (<script type=\"text/javascript\">ebook(\'4105\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "adipose tissue; suppressed appetite",
				true,
				"Correct. Conversely, low blood levels of leptin are expected to lead to increased hunger.");
			
				p.addAnswer(2, "the brain; periods of undernourishment",
				false,
				"No. Leptin is produced by adipose tissue. High blood levels of leptin should cue the brain to suppress appetite.");
			
				p.addAnswer(3, "the stomach; the churning motion you feel when you are hungry",
				false,
				"No. Leptin is produced by adipose tissue. High blood levels of leptin should cue the brain to suppress appetite.");
			
				p.addAnswer(4, "the liver; the breakdown of glycogen stores",
				false,
				"No. Leptin is produced by adipose tissue. High blood levels of leptin should cue the brain to suppress appetite.");
			
				p.addAnswer(5, "adipose tissue; the breakdown of adipose tissue",
				false,
				"No. High levels of leptin normally suppress appetite. High levels of leptin are a signal to the brain that there is plenty of fat stored in the body.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336413;


		
		

		
			
			p.question = "Overnourishment can lead to _____. (<script type=\"text/javascript\">ebook(\'4105\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "diabetes",
				false,
				"No. Although this is true, there is a better answer.");
			
				p.addAnswer(2, "cardiovascular disease",
				false,
				"No. Although this is true, there is a better answer.");
			
				p.addAnswer(3, "breast cancer",
				false,
				"No. Although this is true, there is a better answer.");
			
				p.addAnswer(4, "colon cancer",
				false,
				"No. Although this is true, there is a better answer.");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct. All of the answers are possible consequences of overeating.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336414;


		
		

		
			
			p.question = "Several days after a long holiday weekend including much overeating, you try to cut back on your calories. The first day that you reduce your calorie intake to below the levels that you need, your body will respond by using _____. (<script type=\"text/javascript\">ebook(\'4105\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "glycogen from the liver",
				true,
				"Correct.");
			
				p.addAnswer(2, "fat from all over the body",
				false,
				"No. Fat is not the first source of calories used.");
			
				p.addAnswer(3, "fat from around skeletal muscles",
				false,
				"No. Fat is not the first source of calories used.");
			
				p.addAnswer(4, "protein from muscles",
				false,
				"No. Most animals use proteins for energy only after exhausting their supply of carbohydrates and fats.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. Only one of the choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

