

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "51: Animal Behavior > Practice Test";
	ak.quiz_loc_with_commas = "51: Animal Behavior, Practice Test";
	ak.quiz_title = "Practice Test";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 30;
	ak.non_essay_total = 30;
	ak.scored_item_total = 30;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336913;


		
		

		
			
			p.question = "Pheasants do not feed their chicks. Immediately after hatching, a pheasant chick starts pecking at seeds and insects on the ground. How might a behavioral ecologist explain the ultimate cause of this behavior? (<script type=\"text/javascript\">ebook(\'5101\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Pecking is a fixed action pattern (FAP).",
				false,
				"No. Although this may be true, a FAP describes the type of behavior and the proximate cause of the behavior.");
			
				p.addAnswer(2, "Pheasants learned to peck, and their offspring inherited this behavior.",
				false,
				"No. Inheritance of acquired characteristics does not occur.");
			
				p.addAnswer(3, "Pheasants that pecked survived and reproduced best.",
				true,
				"Correct. Selection favors those traits that increase fitness (reproductive success).");
			
				p.addAnswer(4, "Pecking is the result of imprinting during a critical period.",
				false,
				"No. Imprinting relates to the proximate, not ultimate, causes of a behavior.");
			
				p.addAnswer(5, "Pecking is an example of habituation.",
				false,
				"No. This would mean that after a period of time pheasants would stop pecking at food.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336914;


		
		

		
			
			p.question = "Ants carry dead ants out of an anthill and dump them on a \"trash\" pile. If a chemical from a dead ant is applied to a live ant, other ants will carry it, kicking and struggling, from the anthill, until the substance wears off. Which of the following explains this behavior? (<script type=\"text/javascript\">ebook(\'5101\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The chemical is a sign stimulus for a fixed action pattern.",
				true,
				"Correct. The chemical is a trigger for a stereotyped behavior that is rarely interrupted once it has begun.");
			
				p.addAnswer(2, "The ants have become imprinted on the chemical.",
				false,
				"No. The behavior exhibited by the ants is not a learned behavior.");
			
				p.addAnswer(3, "The ants continue the behavior until they become habituated.",
				false,
				"No. The ants do not become less responsive to the chemical.");
			
				p.addAnswer(4, "The ants can only learn by operant conditioning.",
				false,
				"No. This behavior exhibited by the ants is innate and does not involve learning.");
			
				p.addAnswer(5, "The chemical triggers negative taxis.",
				false,
				"No. If this were negative taxis, the ants would respond by moving away from the chemical stimulus.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336915;


		
		

		
			
			p.question = "Which of the following is a fixed action pattern? (<script type=\"text/javascript\">ebook(\'5101\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A stickleback fish attacks a wood block with a red bottom.",
				true,
				"Correct. A red underside is a sign stimulus that provokes aggressive behavior in sticklebacks.");
			
				p.addAnswer(2, "A hamster becomes active at the same time each evening.",
				false,
				"No. The stimulus for this relates to time of day.");
			
				p.addAnswer(3, "A wolf tracks its prey.",
				false,
				"No. The stimulus for this behavior is hunger.");
			
				p.addAnswer(4, "A robin eats a distasteful bug, spits it out, and never eats a bug that looks like that again.",
				false,
				"No. This is associative learning, in which the robin learns to associate a particular type of bug with an unpleasant experience.");
			
				p.addAnswer(5, "A blackback gull returns to the same island breeding grounds each year.",
				false,
				"No. This type of movement is attributable to the blackback gull\'s cognitive map.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336916;


		
		

		
			
			p.question = "A kinesis differs from a taxis in that a kinesis is _____ whereas a taxis is _____. (<script type=\"text/javascript\">ebook(\'5101\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "innate; learned",
				false,
				"No. Kinesis and taxis refer to types of movement.");
			
				p.addAnswer(2, "a change in activity; a directional response to stimulus",
				true,
				"Correct. Kinesis refers to a change in activity or turning rates, whereas a taxis is a response that takes the organism toward or away from the stimulus.");
			
				p.addAnswer(3, "a response to chemicals; a response to light",
				false,
				"No. Kineses and taxes can be prompted by a wide variety of stimuli");
			
				p.addAnswer(4, "proximate; ultimate",
				false,
				"No. These words refer to immediate stimuli and mechanisms associated with a behavior and the evolutionary significance of the behavior, respectively.");
			
				p.addAnswer(5, "stimulus dependent; stimulus independent",
				false,
				"No. Both responses are prompted by stimuli.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336917;


		
		

		
			
			p.question = "Watching squirrels in the park, you start to wonder why they act so oddly. One squirrel bit the tail of another. Which one of the following is a question about the proximate cause of this behavior? (<script type=\"text/javascript\">ebook(\'5101\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Does the presence of a tail close by cause a squirrel to bite?",
				true,
				"Correct. This question asks about the stimulus that elicits the behavior.");
			
				p.addAnswer(2, "Does biting help keep other squirrels from stealing food?",
				false,
				"No. This is an ultimate question about how the behavior helps these squirrels survive.");
			
				p.addAnswer(3, "Was the squirrel defending a mate from an intruder?",
				false,
				"No. This is an ultimate question about how the behavior helps these squirrels reproduce.");
			
				p.addAnswer(4, "Is this biting behavior a form of courtship?",
				false,
				"No. This is an ultimate question about how the behavior helps these squirrels reproduce.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336918;


		
		

		
			
			p.question = "Which one of the following is an example of a circannual rhythm. (<script type=\"text/javascript\">ebook(\'5101\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Every spring robins gather in the park to build nests and reproduce.",
				true,
				"Correct. This event occurs on an annual cycle.");
			
				p.addAnswer(2, "Mosquitoes are most active at dawn and dusk.",
				false,
				"No. This circadian rhythm occurs on a daily cycle.");
			
				p.addAnswer(3, "Just as the sun sets, the bats leave the cave in large swarms.",
				false,
				"No. This circadian rhythm occurs on a daily cycle.");
			
				p.addAnswer(4, "It seems that about every afternoon I get sleepy while working at my desk.",
				false,
				"No. This circadian rhythm occurs on a daily cycle.");
			
				p.addAnswer(5, "In the heat of the day, most of the mammals at the zoo were resting in the shade.",
				false,
				"No. This circadian rhythm occurs on a daily cycle.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336919;


		
		

		
			
			p.question = "What signals might be best employed by a nocturnal forest animal seeking to identify its territory? (<script type=\"text/javascript\">ebook(\'5101\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "visual and olfactory",
				false,
				"No. Visual signals would not work in the dark, especially in a forest.");
			
				p.addAnswer(2, "auditory and olfactory",
				true,
				"Correct. These two modes are not impeded by darkness or vegetation.");
			
				p.addAnswer(3, "tactile and olfactory",
				false,
				"No. Tactile signals require closer proximity than territorial animals prefer, and trees can be an obstruction.");
			
				p.addAnswer(4, "visual and auditory",
				false,
				"No. Visual signals cannot be received well in the dark.");
			
				p.addAnswer(5, "tactile and auditory",
				false,
				"No. Tactile signals require close proximity, without interference from other objects. Neither condition works well for terrestrial forest-dwellers.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336920;


		
		

		
			
			p.question = "Pheromones are examples of _____. (<script type=\"text/javascript\">ebook(\'5101\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "hormones",
				false,
				"No. Hormones relay chemical signals within an individual; pheromones are involved in communications among individuals.");
			
				p.addAnswer(2, "chemical signals",
				true,
				"Correct. Chemical signals called pheromones are used in communications among members of a species.");
			
				p.addAnswer(3, "visual signals",
				false,
				"No. Pheromones can be smelled.");
			
				p.addAnswer(4, "instinctive behavior",
				false,
				"No. Pheromones are not a behavior, but they can provoke a behavior by another individual.");
			
				p.addAnswer(5, "developmental homeostasis",
				false,
				"No. Chemical signals called pheromones are used in communications among members of a species.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336921;


		
		

		
			
			p.question = "Graylag geese learn to follow their mothers. This is an example of _____. (<script type=\"text/javascript\">ebook(\'5102\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "habituation",
				false,
				"No. This is a type of learning that results in a failure to respond to a particular stimulus.");
			
				p.addAnswer(2, "operant conditioning",
				false,
				"No. This involves learning to associate a particular behavior of one\'s own with a particular reward or punishment.");
			
				p.addAnswer(3, "altruism",
				false,
				"No. This is a type of behavior that reduces the altruistic individual\'s fitness while increasing the fitness of another individual.");
			
				p.addAnswer(4, "imprinting",
				true,
				"Correct. During the critical period, graylag geese respond by following any object moving away from them.");
			
				p.addAnswer(5, "agonistic behavior",
				false,
				"No. This relates to submissive and threatening behavior.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336922;


		
		

		
			
			p.question = "An aquaculture facility hatched salmon eggs and released young fish into a river leading to the ocean. The fish fed and grew in the ocean, and in a few years they returned to the facility. Because the number of returning fish was low, a scientist suggested adding a chemical to the river that would _____. (<script type=\"text/javascript\">ebook(\'5102\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "decrease their agonistic behavior",
				false,
				"No. This type of behavior involves interaction among individuals and does not relate to migratory behavior.");
			
				p.addAnswer(2, "enable them to imprint on the facility",
				true,
				"Correct. During the critical period, the fish will learn to recognize the river by its chemical signature.");
			
				p.addAnswer(3, "stimulate habituation in the fish",
				false,
				"No. If this were to occur, the fish would not respond to the added chemical.");
			
				p.addAnswer(4, "improve the search image of the salmon",
				false,
				"No. Fish use chemical, not visual, cues to recognize the rivers where they hatched.");
			
				p.addAnswer(5, "promote optimal foraging",
				false,
				"No. This migratory behavior directly relates to reproduction, not to feeding behavior.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336923;


		
		

		
			
			p.question = "A blackcap warbler from a captive migratory population is mated with another blackcap warbler from a captive nonmigratory population. The lab-reared offspring exhibit a modest amount of migratory restlessness. This behavior, which is intermediate between that of the two parents, could be interpreted as evidence that _____. (<script type=\"text/javascript\">ebook(\'5102\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "migratory behavior is determined exclusively by environmental factors",
				false,
				"No. If this were so, you would expect both captive parental populations to exhibit the same degree of migratory restlessness.");
			
				p.addAnswer(2, "the differences in migratory behavior between populations are influenced by genetic differences among the populations",
				true,
				"Correct. As in the case of the warblers, hybrid offspring exhibit an intermediate expression of behaviors under some genetic control.");
			
				p.addAnswer(3, "birds must learn how to migrate",
				false,
				"No. This does not explain why the hybrid exhibits an intermediate behavior.");
			
				p.addAnswer(4, "migratory behavior cannot evolve by natural selection",
				false,
				"No. Actually, the study indicates that migratory behavior can evolve.");
			
				p.addAnswer(5, "sexual selection is important in the evolution of migratory behavior",
				false,
				"No. This study does not examine sexual selection.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336924;


		
		

		
			
			p.question = "When <i>Drosophila</i> were exposed to a particular odor and electric shock at the same time, they started to avoid the odor. This is an example of _____. (<script type=\"text/javascript\">ebook(\'5102\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "classical conditioning",
				true,
				"Correct. A type of associative learning called classical conditioning is learning to associate an arbitrary stimulus with reward or punishment.");
			
				p.addAnswer(2, "operant conditioning",
				false,
				"No. Operant conditioning occurs when an animal learns to associate one of its behaviors with reward or punishment.");
			
				p.addAnswer(3, "reasoning",
				false,
				"No. A type of associative learning called classical conditioning is learning to associate an arbitrary stimulus with reward or punishment.");
			
				p.addAnswer(4, "imprinting",
				false,
				"No. A type of associative learning called classical conditioning is learning to associate an arbitrary stimulus with reward or punishment.");
			
				p.addAnswer(5, "habituation",
				false,
				"No. In this experiment, there was no loss of response to a stimulus.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336925;


		
		

		
			
			p.question = "In _____, an animal learns to associate one of its behaviors with reward or punishment. (<script type=\"text/javascript\">ebook(\'5102\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "classical conditioning",
				false,
				"No. This is learning to associate an arbitrary stimulus with a particular outcome.");
			
				p.addAnswer(2, "operant conditioning",
				true,
				"Correct. This is the definition of operant conditioning.");
			
				p.addAnswer(3, "fixed-action-pattern (FAP) learning",
				false,
				"No. FAP is a response to an external stimulus that does not involve learning.");
			
				p.addAnswer(4, "habituation",
				false,
				"No. This type of learning results in a decreased response to an external stimulus.");
			
				p.addAnswer(5, "imprinting",
				false,
				"No. This type of learning relates to an external stimulus during a critical period.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336926;


		
		

		
			
			p.question = "Male prairie voles are monogamous. They are attentive to young, and aggressive toward intruders. This appears to be related to _____. (<script type=\"text/javascript\">ebook(\'5103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the prevalence of monogamy among rodent species",
				false,
				"No. Most male rodents are not monogamous.");
			
				p.addAnswer(2, "the heavy investment most male mammals place in parental care",
				false,
				"No. Most male mammals do not invest heavily in parental care.");
			
				p.addAnswer(3, "an unusual tendency for prairie voles to produce litters of same-sex offspring. In the case of males, this promotes monogamy and aggression.",
				false,
				"No. Prairie voles do not produce such litters.");
			
				p.addAnswer(4, "special chemicals in female vole urine that promote such behavior in males",
				false,
				"No. Female vole urine is not known to contain such chemicals.");
			
				p.addAnswer(5, "the distribution of certain neuropeptide receptors in the brain of the voles",
				true,
				"Correct. When the genes for these receptors were placed in laboratory mice, they developed the same traits.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336927;


		
		

		
			
			p.question = "In cross-fostering experiments, offspring of two species are switched early in development and reared by the opposite species. They are then compared with similar offspring reared by their own species. What is the point of this experimental design? (<script type=\"text/javascript\">ebook(\'5103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "This experimental design demonstrates that maternal care is universal, no matter what offspring are receiving care.",
				false,
				"No. Maternal care can vary among species.");
			
				p.addAnswer(2, "This experimental design separates the effects of genetics and environment.",
				true,
				"Correct. Any differences between the cross-fostered animals and their conspecifics that have been reared by the parent species can be attributed to the environment.");
			
				p.addAnswer(3, "This experimental design reveals the source of aggression.",
				false,
				"No. This design can be used to investigate a wide variety of traits, not just aggression.");
			
				p.addAnswer(4, "Animals that are cross-fostered will be easier to tame because they will have been exposed to a wide variety of species.",
				false,
				"No. Cross-fostering does not induce tameness.");
			
				p.addAnswer(5, "This method can generate animals that behave as if they were a different species, the parental one.",
				false,
				"No. Cross-fostered animals rarely take on all attributes of the parental species, and that is not the purpose of the experiment.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336928;


		
		

		
			
			p.question = "One way to determine whether or not food preferences have a genetic basis is to _____. (<script type=\"text/javascript\">ebook(\'5103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "compare the food preferences of two different wild populations",
				false,
				"No. This may simply demonstrate that animals in two places prefer different food. They may have learned this, or it may reflect abundance.");
			
				p.addAnswer(2, "give animals from two different populations the same food and see if they eat it",
				false,
				"No. This demonstrates whether the animals will eat the same food; there is no reason to invoke genetics.");
			
				p.addAnswer(3, "rear the offspring of animals from two different populations with different food preferences under identical conditions in the lab, and see whether or not their food preferences reflect parental ones",
				true,
				"Correct. By doing this, you have removed environmental influences on the animals; any remaining differences are likely to be genetic.");
			
				p.addAnswer(4, "bring animals from two populations into the lab and observe whether they have different food preferences",
				false,
				"No. This would demonstrate whether they have different food preferences, but this behavior could be learned.");
			
				p.addAnswer(5, "demonstrate that there is no variation in food preference within a wild population",
				false,
				"No. The presence or absence of variation does not prove that there is a genetic basis for food preference.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336929;


		
		

		
			
			p.question = "Animal behavior is governed by complex interactions between _____. (<script type=\"text/javascript\">ebook(\'5103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "genetic and environmental factors",
				true,
				"Correct.");
			
				p.addAnswer(2, "genetic factors and diet",
				false,
				"No. This is not the best choice. Diet is just one example of another category of important factors.");
			
				p.addAnswer(3, "genetic factors and the behavior of the parents",
				false,
				"No. This is not the best choice. Parental behavior is just one example of another category of important factors.");
			
				p.addAnswer(4, "the parents and their offspring",
				false,
				"No. The two major influences are the genetic and environmental factors.");
			
				p.addAnswer(5, "an individual and its environment",
				false,
				"No. The two major influences are the genetic and environmental factors.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336930;


		
		

		
			
			p.question = "Which of the following best illustrates optimal foraging? (<script type=\"text/javascript\">ebook(\'5104\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A robin will repeatedly attack any red object near its territory.",
				false,
				"No. Foraging behavior does not relate to such a fixed action pattern.");
			
				p.addAnswer(2, "Musk oxen will form a circle to fend off a wolf attack.",
				false,
				"No. Foraging behavior does not relate to behavior under threat.");
			
				p.addAnswer(3, "Bats emerge to feed at about the same time each night.",
				false,
				"No. Although this does relate to foraging behavior, it is more related to daily rhythms.");
			
				p.addAnswer(4, "A blackbird will warn others in the flock if it senses danger.",
				false,
				"No. This is not an example of feeding behavior but of reciprocal altruism.");
			
				p.addAnswer(5, "A sunbird will defend more fiercely flowers that produce more food.",
				true,
				"Correct. The energy cost of defending this high-energy food source is less than the energy required to find another food source that may provide less energy.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336931;


		
		

		
			
			p.question = "Animals that exhibit which type of mating behavior are often so morphologically similar that it is difficult to distinguish the sexes based on external characteristics? (<script type=\"text/javascript\">ebook(\'5104\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "agonistic",
				false,
				"No. Agonistic behavior is aggression; it is not a mating behavior.");
			
				p.addAnswer(2, "promiscuous",
				false,
				"No. This is not correct.  Think of a mating behavior where animals form longer-term relationships.");
			
				p.addAnswer(3, "monogamous",
				true,
				"Correct.  The sexes of monogamous species are often hard to distinguish based on external characteristics.");
			
				p.addAnswer(4, "polygamous",
				false,
				"No. Polygamous species are often dimorphic, with one sex being \"showier\" than the other.");
			
				p.addAnswer(5, "polygynous",
				false,
				"No. Polygamous species are often dimorphic with one sex being \"showier\" than the other. In the case of polygynous species, the male is usually showier.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336932;


		
		

		
			
			p.question = "When animals engage in _____, they often perform displays that make them look as large and dangerous as possible. (<script type=\"text/javascript\">ebook(\'5104\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "courtship rituals",
				false,
				"No. These displays play a role in reproduction; they are meant to attract individuals of the opposite sex.");
			
				p.addAnswer(2, "altruism",
				false,
				"No. In this behavior, an individual reduces its own fitness while increasing the fitness of another individual.");
			
				p.addAnswer(3, "kin selection",
				false,
				"No. This is a type of selection whereby an individual\'s fitness is reduced but the fitness of closely related individuals is increased.");
			
				p.addAnswer(4, "kineses",
				false,
				"No. Kineses relate to changes in activity levels in response to a stimulus.");
			
				p.addAnswer(5, "agonistic behavior",
				true,
				"Correct. Agonistic behavior relates to competitive behavior among individuals of the same species and to the establishment of dominance.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336933;


		
		

		
			
			p.question = "Which problem below could be best explained by applying game theory? (<script type=\"text/javascript\">ebook(\'5104\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the reason that animals practice play behavior",
				false,
				"No. Game theory gives behavioral ecologists a way to think about complex evolutionary problems in which relative performance, not absolute performance, is the key to understanding.");
			
				p.addAnswer(2, "the reason that some species are monogamous and others are polygamous",
				false,
				"No. Game theory gives behavioral ecologists a way to think about complex evolutionary problems in which relative performance, not absolute performance, is the key to understanding.");
			
				p.addAnswer(3, "how a species with three different phenotypes of various aggression levels can survive in the same population",
				true,
				"Correct. Game theory gives behavioral ecologists a way to think about complex evolutionary problems in which relative performance, not absolute performance, is the key to understanding.");
			
				p.addAnswer(4, "how female robins build their nests",
				false,
				"No. Game theory gives behavioral ecologists a way to think about complex evolutionary problems in which relative performance, not absolute performance, is the key to understanding.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. Only one of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336934;


		
		

		
			
			p.question = "Off in the distance, on the side of a mountain, you spot four female deer and a single male deer. If this reflects the mating system of this species, it would be an example of _____. (<script type=\"text/javascript\">ebook(\'5104\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "polygyny",
				true,
				"Correct.  Polygyny is one male mating with more than one female.");
			
				p.addAnswer(2, "polyandry",
				false,
				"No. Polyandry is one female mating with more than one male.");
			
				p.addAnswer(3, "monogamy",
				false,
				"No. Monogamy involves one male and one female.");
			
				p.addAnswer(4, "monogyny",
				false,
				"No. This is not an appropriate term.");
			
				p.addAnswer(5, "monandry",
				false,
				"No. This is not an appropriate term.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336935;


		
		

		
			
			p.question = "Altruistic behavior _____. (<script type=\"text/javascript\">ebook(\'5105\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "never occurs in natural populations",
				false,
				"No. It does, as for example when a wolf offers food to another, unrelated wolf.");
			
				p.addAnswer(2, "is expected when the species as a whole benefits from it",
				false,
				"No. Altruistic behaviors are acts that occur between individuals.");
			
				p.addAnswer(3, "occurs only when closely related individuals benefit from it",
				false,
				"No. As well as occurring between closely related individuals, altruistic behavior also occurs between unrelated individuals.");
			
				p.addAnswer(4, "is expected when it increases the long-term inclusive fitness of the altruists",
				true,
				"Correct. On occasion, animals behave in ways that reduce their individual fitness and increase the fitness of the recipient of the behavior, a phenomenon called altruism. Sometimes, this altruistic behavior extends to close relatives. Selection can result in an animal\'s increasing its genetic representation to the next generation by altruistically helping close relatives other than its own offspring.");
			
				p.addAnswer(5, "is expected when there are plentiful resources to share",
				false,
				"No. At least initially, altruistic behavior reduces the fitness of the altruist. When resources are plentiful, sharing is less likely to have a negative impact on fitness of the altruist.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336936;


		
		

		
			
			p.question = "Which one of the following statements best defines an altruistic act? (<script type=\"text/javascript\">ebook(\'5105\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "It immediately benefits both the performer and another individual.",
				false,
				"No. Only one of the individuals experiences an immediate benefit.");
			
				p.addAnswer(2, "It immediately benefits another individual at some cost to the performer.",
				true,
				"Correct. On occasion, animals behave in ways that reduce their individual fitness and increase the fitness of the recipient of the behavior, a phenomenon called altruism.");
			
				p.addAnswer(3, "It immediately benefits the performer and imposes a cost on another individual.",
				false,
				"No. This choice has it exactly backward.");
			
				p.addAnswer(4, "It imposes a cost on the performer and the other individual.",
				false,
				"No. One of the two individuals experiences an immediate benefit.");
			
				p.addAnswer(5, "It imposes a cost on the performer without benefiting another individual.",
				false,
				"No. One of the two individuals experiences an immediate benefit.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336937;


		
		

		
			
			p.question = "The coefficient of relatedness between two brothers _____. (<script type=\"text/javascript\">ebook(\'5105\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "is 0.75",
				false,
				"No. Too high.");
			
				p.addAnswer(2, "is the same as the coefficient of relatedness between mother and daughter",
				true,
				"Correct. Siblings have half their genes in common, the same coefficient of relatedness as parent and offspring.");
			
				p.addAnswer(3, "is 0.25",
				false,
				"No. This is the coefficient of relatedness between, for example, grandparent and grandchild.");
			
				p.addAnswer(4, "is less than the coefficient of relatedness between father and son",
				false,
				"No. The coefficient of relatedness between brothers is the same as that between father and son.");
			
				p.addAnswer(5, "is 1.5",
				false,
				"No. The coefficient of relatedness between two individuals cannot exceed 1.0.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336938;


		
		

		
			
			p.question = "Altruistic behaviors can be understood, in part, by considering the coefficient of relatedness (<i>r</i>) between the individuals involved. Assume that an individual mammal has the option to raise its own offspring, other genetic relatives, or a combination of offspring and other genetic relatives. From a genetic point of view, which one of the following represents the <b>least</b> successful option? (<script type=\"text/javascript\">ebook(\'5105\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "two offspring",
				false,
				"No. The coefficient of relatedness between parent and offspring is 0.5. The total coefficient of relatedness would be 0.5 + 0.5 = 1.0, a total that is not the lowest of the choices.");
			
				p.addAnswer(2, "two offspring and two first cousins",
				false,
				"No. The coefficient of relatedness between siblings is 0.5, and the coefficient of relatedness between first cousins is 0.125. The total coefficient of relatedness would be 0.5 + 0.5 + 0.125 + 0.125 = 1.25, a total that is not the lowest of the choices.");
			
				p.addAnswer(3, "four grandchildren",
				false,
				"No. The coefficient of relatedness between grandparent and grandchild is 0.25. The total coefficient of relatedness would be 4 x 0.25 = 1.0, a total that is not the lowest of the choices.");
			
				p.addAnswer(4, "one sibling and three nephews",
				false,
				"No. The coefficient of relatedness between siblings is 0.5, and the coefficient of relatedness between an individual and a nephew is 0.25. The total coefficient of relatedness would be 0.5 + (3 x 0.25) = 1.25, a total that is not the lowest of the choices.");
			
				p.addAnswer(5, "seven first cousins",
				true,
				"Correct. First cousins have a coefficient of relatedness of 0.125. The total coefficient of relatedness would be 7 x 0.125 = 0.875, a total lower than any of the other choices.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336939;


		
		

		
			
			p.question = "The survival, through apparently altruistic behavior, of related individuals with common alleles is referred to as _____. (<script type=\"text/javascript\">ebook(\'5105\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the founder effect",
				false,
				"No. The founder effect is a type of genetic drift in which a colony is formed by a small number of individuals who have split off from a larger parental population.");
			
				p.addAnswer(2, "kin selection",
				true,
				"Correct. An individual\'s altruism can result in more genes identical to its own in the next generation if it aids a sibling or other relative. This mechanism of increasing inclusive fitness is called kin selection.");
			
				p.addAnswer(3, "competitive exclusion",
				false,
				"No. Competitive exclusion is a type of interaction between two species in which competition drives one of the two to local extinction.");
			
				p.addAnswer(4, "adaptive radiation",
				false,
				"No. Adaptive radiation is a rapid spurt of speciation that occurs when a population is presented with a diversity of new opportunities and challenges.");
			
				p.addAnswer(5, "convergent evolution",
				false,
				"No. Convergent evolution occurs when unrelated species evolve similar solutions to similar environmental challenges.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336940;


		
		

		
			
			p.question = "Imagine a population of birds in which first-year birds can either (1) find a mate and raise an average of three offspring or (2) stay in their parents\' territory and help the parents raise two more offspring than the parents would have been able to raise without any help. Based on the theory of kin selection, we would expect that ______. (<script type=\"text/javascript\">ebook(\'5105\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "most territories would have young birds helping at the nest",
				false,
				"No. Given the conditions posed in this question, such behavior would not maximize a young bird\'s genetic contribution to future generations.");
			
				p.addAnswer(2, "altruistic behavior would be common in this population",
				false,
				"No. Given the conditions posed in this question, such altruistic behavior would not maximize a young bird\'s genetic contribution to future generations.");
			
				p.addAnswer(3, "the behavior of helping at the nest would not evolve in this population",
				true,
				"Correct. If the first-year birds raise three offspring of their own, they will share one-half their genes with each of these three offspring. If they help raise two additional siblings, they will share half their genes with these birds. They will contribute more genetic material to the next generation by raising their own families, so altruistic behavior would not be expected to evolve in this population.");
			
				p.addAnswer(4, "most first-year birds would choose to forgo breeding",
				false,
				"No. Given the conditions posed in this question, forgoing breeding would not maximize a young bird\'s genetic contribution to future generations.");
			
				p.addAnswer(5, "nutrient cycles would be disrupted",
				false,
				"No. The only thing that needs to be considered is how the young bird\'s genetic contribution to future generations is affected.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336941;


		
		

		
			
			p.question = "The main premise of sociobiology is that _____. (<script type=\"text/javascript\">ebook(\'5105\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "certain behaviors are the expression of genes that have been favored by evolution",
				true,
				"Correct.");
			
				p.addAnswer(2, "altruism is rare and usually not adaptive",
				false,
				"No. Sociobiology helps to understand aspects of altruism.");
			
				p.addAnswer(3, "behavior is a product of the environment and not the genetic basis of the organism",
				false,
				"No.  Sociobiology examines behavior through an evolutionary lens.");
			
				p.addAnswer(4, "behavior is based upon the genetics of the organism and not the product of the environment",
				false,
				"No.  Environmental factors can also have an effect.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336942;


		
		

		
			
			p.question = "Which of the following sayings best summarizes the idea of reciprocal altruism? (<script type=\"text/javascript\">ebook(\'5105\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A rolling stone gathers no moss.",
				false,
				"No. Maybe we can figure out a way for this saying to apply to migratory behavior.");
			
				p.addAnswer(2, "You scratch my back, and I\'ll scratch yours.",
				true,
				"Correct. Reciprocal altruism is increasing the fitness of an unrelated individual at the risk of a reduction of the altruist\'s fitness. However, if the behavior did not ultimately increase the fitness of the altruist, it would be selected against.");
			
				p.addAnswer(3, "A penny saved is a penny earned.",
				false,
				"No. Do you think we can apply this saying to the behavior of a squirrel storing food for the winter?");
			
				p.addAnswer(4, "A bird in the hand is worth two in the bush.",
				false,
				"No. Perhaps we can apply this saying to animal behavior by creating a scenario in which an animal that has an established territory will not risk losing it for the opportunity of establishing a better territory.");
			
				p.addAnswer(5, "Beauty is in the eye of the beholder.",
				false,
				"No. This saying would apply best to courtship rituals.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

