

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "40: Basic Principles of Animal Form and Function > Activities Quiz";
	ak.quiz_loc_with_commas = "40: Basic Principles of Animal Form and Function, Activities Quiz";
	ak.quiz_title = "Activities Quiz";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 15;
	ak.non_essay_total = 15;
	ak.scored_item_total = 15;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336291;


		
		

		
			
			p.question = "Which of these is NOT one of the four major categories of tissue? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?40&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Overview of Animal Tissues</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "muscle",
				false,
				"Muscle tissue IS one of the four major tissue types.");
			
				p.addAnswer(2, "epithelial",
				false,
				"Epithelial tissue IS one of the four major tissue types.");
			
				p.addAnswer(3, "connective",
				false,
				"Connective tissue IS one of the four major tissue types.");
			
				p.addAnswer(4, "blood",
				true,
				"Blood is a type of connective tissue.");
			
				p.addAnswer(5, "nervous",
				false,
				"Nervous tissue IS one of the four major tissue types.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336292;


		
		

		
			
			p.question = "What type of epithelium would you expect to find covering a surface subject to physical forces? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?40&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Epithelial Tissue</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "simple epithelium",
				false,
				"In this instance \"simple\" refers to a single layer, which would not provide a protective barrier to physical damage.");
			
				p.addAnswer(2, "squamous epithelium",
				false,
				"Many epithelial tissues that form a protective barrier are composed of squamous cells. However, it is not the shape of the cell that provides a protective barrier.");
			
				p.addAnswer(3, "stratified epithelium",
				true,
				"Stratified epithelium consists of multiple layers; this thickness provides a protective barrier.");
			
				p.addAnswer(4, "simple cuboidal cells",
				false,
				"Some epithelial tissues that form a protective barrier are composed of cuboidal cells. However, it is not the shape of the cell that provides a protective barrier.");
			
				p.addAnswer(5, "columnar epithelium",
				false,
				"Some epithelial tissues that form a protective barrier are composed of columnar cells. However, it is not the shape of the cell that provides a protective barrier.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336293;


		
		

		
			
			p.question = "What type of epithelial tissue, found in the intestines, absorbs nutrients? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?40&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Epithelial Tissue</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "stratified cuboidal epithelium",
				false,
				"Stratified epithelium is too thick for the efficient absorption of nutrients; stratified tissue is specialized for protection.");
			
				p.addAnswer(2, "simple cuboidal cells",
				false,
				"Simple cuboidal cells, such as are found lining kidney tubules, are specialized for secretion and absorption.");
			
				p.addAnswer(3, "simple columnar epithelium",
				true,
				"Simple columnar epithelium, such as that found lining the intestines, is specialized for absorption and secretion.");
			
				p.addAnswer(4, "stratified columnar epithelium",
				false,
				"While stratified columnar epithelium is capable of absorption, it is not the type of epithelium found lining the intestines.");
			
				p.addAnswer(5, "stratified squamous epithelium",
				false,
				"Stratified epithelium is too thick for the efficient absorption of nutrients; stratified tissue is specialized for protection.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336294;


		
		

		
			
			p.question = "Which of these tissues, found in the lungs, permits gas exchange by diffusion? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?40&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Epithelial Tissue</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "stratified squamous epithelium",
				false,
				"Stratified epithelium is too thick for efficient diffusion; stratified tissue is specialized for protection.");
			
				p.addAnswer(2, "simple cuboidal cells",
				false,
				"While this tissue is but a single layer, simple cuboidal cells are specialized for secretion and absorption.");
			
				p.addAnswer(3, "stratified cuboidal epithelium",
				false,
				"Stratified epithelium is too thick for efficient diffusion; stratified tissue is specialized for protection.");
			
				p.addAnswer(4, "simple squamous epithelium",
				true,
				"This is a thin single layer of cells that allows for diffusion.");
			
				p.addAnswer(5, "simple columnar epithelium",
				false,
				"While this tissue is but a single layer, simple columnar epithelium is specialized for absorption and secretion.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336295;


		
		

		
			
			p.question = "What type of epithelial tissue lines kidney tubules? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?40&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Epithelial Tissue</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "stratified squamous epithelium",
				false,
				"Substances must pass across the walls of kidney tubules; stratified tissue is too thick to allow for such movement to be efficient.");
			
				p.addAnswer(2, "stratified cuboidal epithelium",
				false,
				"Substances must pass across the walls of kidney tubules; stratified tissue is too thick to allow for such movement to be efficient.");
			
				p.addAnswer(3, "simple squamous epithelium",
				false,
				"However, like the epithelium of kidney tubules, simple squamous epithelium allows for the passage of material.");
			
				p.addAnswer(4, "simple cuboidal cells",
				true,
				"The simple cuboidal cells of kidney tubules allow for both secretion and absorption.");
			
				p.addAnswer(5, "stratified transitional epithelium",
				false,
				"Stratified transitional epithelium is a type of epithelium that allows for distension; it is found lining the interior of structures such as the urinary bladder.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336296;


		
		

		
			
			p.question = "How does connective tissue differ from the other three major tissue types? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?40&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Connective Tissue</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Connective tissue often consists of relatively few cells embedded in an extracellular matrix.",
				true,
				"This describes many connective tissues, such as loose connective tissue.");
			
				p.addAnswer(2, "Connective tissue consists of contractile proteins.",
				false,
				"This describes muscle tissue.");
			
				p.addAnswer(3, "Connective tissue consists of cells capable of transmitting electrical impulses.",
				false,
				"This describes nervous tissue.");
			
				p.addAnswer(4, "There are three types of connective tissue.",
				false,
				"There are more than three types of connective tissue.");
			
				p.addAnswer(5, "Connective tissue is found lining body surfaces.",
				false,
				"This describes epithelium tissues.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336297;


		
		

		
			
			p.question = "Which of these describes loose connective tissue? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?40&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Connective Tissue</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "It is a loose weave of fibers that functions as a packing material.",
				true,
				"Loose connective tissue is a packing material that serves, for example, to hold organs in place.");
			
				p.addAnswer(2, "It is composed of many fibers that connect bone to bone and muscle to bone.",
				false,
				"This describes fibrous connective tissue.");
			
				p.addAnswer(3, "It is a rigid material that provides structural support.",
				false,
				"This describes bone.");
			
				p.addAnswer(4, "It transports nutrients and gases from one part of the body to another.",
				false,
				"This describes blood.");
			
				p.addAnswer(5, "It plays a role in padding, insulation, and energy storage.",
				false,
				"This describes adipose tissue.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336298;


		
		

		
			
			p.question = "Cartilage is found _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?40&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Connective Tissue</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "surrounding organs such as the kidneys",
				false,
				"Loose connective tissue forms a packing material that holds organs in place.");
			
				p.addAnswer(2, "in the heart",
				false,
				"While somewhat flexible, cartilage is not flexible enough to accommodate heart function.");
			
				p.addAnswer(3, "at the ends of bones such as the femur",
				true,
				"The ends of long bones, such as the femur, have a cartilage cap.");
			
				p.addAnswer(4, "covering the surface of your body",
				false,
				"Epithelial tissues cover body surfaces.");
			
				p.addAnswer(5, "connecting one bone to another",
				false,
				"Ligaments, a type of fibrous connective tissue, connect bones.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336299;


		
		

		
			
			p.question = "_____ is the connective tissue specialized for transport. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?40&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Connective Tissue</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Bone",
				false,
				"Bone is specialized for physical support.");
			
				p.addAnswer(2, "Blood",
				true,
				"Blood is specialized for the transport of substances such as nutrients, wastes, and gases.");
			
				p.addAnswer(3, "Adipose tissue",
				false,
				"Adipose tissue stores fat (energy) and pads and insulates the body.");
			
				p.addAnswer(4, "Muscle tissue",
				false,
				"Muscle tissue is not a connective tissue.");
			
				p.addAnswer(5, "Cartilage",
				false,
				"Cartilage is a flexible component of the skeleton.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336300;


		
		

		
			
			p.question = "A neuron consists of _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?40&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Nervous Tissue</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a cell body only",
				false,
				"However, neurons do have a cell body.");
			
				p.addAnswer(2, "dendrites only",
				false,
				"However, neurons do have dendrites.");
			
				p.addAnswer(3, "axons only",
				false,
				"However, neurons do have axons.");
			
				p.addAnswer(4, "dendrites, a cell body, and axons",
				true,
				"These are the three regions of a neuron.");
			
				p.addAnswer(5, "striations",
				false,
				"Striations are typical of skeletal and cardiac muscle.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336301;


		
		

		
			
			p.question = "Nervous tissue functions _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?40&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Nervous Tissue</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "as a physical barrier to the invasion of pathogens",
				false,
				"This is a function of epithelial tissue.");
			
				p.addAnswer(2, "to physically move the body",
				false,
				"Muscle physically moves the body in response to signals received from nervous tissue.");
			
				p.addAnswer(3, "to sense stimuli",
				true,
				"This is one of the functions of nervous tissue.");
			
				p.addAnswer(4, "to physically support the body",
				false,
				"This is the function of bone tissue.");
			
				p.addAnswer(5, "in the absorption of nutrients",
				false,
				"This is the function of simple columnar epithelium.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336302;


		
		

		
			
			p.question = "What type of muscle is responsible for contractions of the digestive tract and arteries? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?40&E','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Muscle Tissue</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "smooth muscle",
				true,
				"Smooth muscle is responsible for the involuntary contractions of the digestive tract, arteries, and bladder.");
			
				p.addAnswer(2, "skeletal muscle",
				false,
				"Skeletal muscle is responsible for voluntary movements, such as the movement of bones.");
			
				p.addAnswer(3, "striated muscle",
				false,
				"This is another name for skeletal muscle, even though cardiac muscle is also striated.");
			
				p.addAnswer(4, "voluntary muscle",
				false,
				"This is another name for skeletal muscle.");
			
				p.addAnswer(5, "cardiac muscle",
				false,
				"Cardiac muscle is heart muscle.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336303;


		
		

		
			
			p.question = "Cardiac muscle is the only muscle composed of _____ fibers. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?40&E','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Muscle Tissue</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "branched",
				true,
				"Cardiac muscle fibers are branched.");
			
				p.addAnswer(2, "unstriated",
				false,
				"Smooth muscle fibers are not striated; hence they are referred to as \"smooth.\" Cardiac muscle is striated.");
			
				p.addAnswer(3, "unbranched and cylindrical",
				false,
				"This describes the shape of skeletal muscle fibers.");
			
				p.addAnswer(4, "spindle shaped",
				false,
				"The cells of smooth muscle are spindle shaped.");
			
				p.addAnswer(5, "striated",
				false,
				"While cardiac muscle fibers are striated, so are skeletal muscle fibers.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336304;


		
		

		
			
			p.question = "_____ muscle is attached to bones. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?40&E','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Muscle Tissue</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Smooth",
				false,
				"Smooth muscle is found associated with organs.");
			
				p.addAnswer(2, "Involuntary",
				false,
				"The muscle attached to bone is voluntary muscle.");
			
				p.addAnswer(3, "Cardiac",
				false,
				"Cardiac muscle is the muscle of the heart.");
			
				p.addAnswer(4, "Branched",
				false,
				"Branched muscle fibers are characteristic of cardiac muscle.");
			
				p.addAnswer(5, "Skeletal",
				true,
				"Skeletal muscle is attached to bones.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336305;


		
		

		
			
			p.question = "Which of these is an example of negative feedback? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?1&E','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Regulation: Negative and Positive Feedback</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "As a blood clot begins to form, the process of its formation gets faster and faster.",
				false,
				"This is an example of positive feedback.");
			
				p.addAnswer(2, "After you eat, glucagon stimulates an increase in blood sugar levels.",
				false,
				"After you eat, blood sugar levels increase; therefore, promoting an even greater increase in the blood sugar level would be an example of positive feedback.");
			
				p.addAnswer(3, "After you eat, insulin stimulates the lowering of blood sugar levels.",
				true,
				"Eating raises blood sugar levels; insulin stimulates the lowering of blood sugar level. In this example the response to the stimulus (increased blood sugar levels) opposes that stimulus (by lowering blood sugar levels).");
			
				p.addAnswer(4, "The digestive enzyme pepsinogen is converted to pepsin by the action of hydrochloric acid; pepsin itself can then convert pepsinogen into pepsin.",
				false,
				"The more pepsin there is, the faster pepsinogen is converted into pepsin; therefore, this is an example of positive feedback.");
			
				p.addAnswer(5, "Once labor begins, contractions increase in frequency and intensity.",
				false,
				"This is an example of positive feedback.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

