

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "GraphIt! Quiz > GraphIt! Quiz > Age Pyramids and Population Growth";
	ak.quiz_loc_with_commas = "GraphIt! Quiz, GraphIt! Quiz, Age Pyramids and Population Growth";
	ak.quiz_title = "Age Pyramids and Population Growth";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 11;
	ak.non_essay_total = 11;
	ak.scored_item_total = 11;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337435;


		
		

		
			
			p.question = "The population of Greece is currently _______.";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "expanding",
				false,
				"");
			
				p.addAnswer(2, "stable",
				false,
				"");
			
				p.addAnswer(3, "declining",
				true,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- truefalse ------------
		//
		
			p = new Problem("truefalse");
		
		p.id = 337436;


		
		

		
			
			p.question = "Assuming the current trend continues, in 30 years Greece will have more children than reproductive-age individuals.";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			
				
				p.addAnswer(1, "True", false, "");
				
			
				
				p.addAnswer(2, "False", true, "");
				
				

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- truefalse ------------
		//
		
			p = new Problem("truefalse");
		
		p.id = 337437;


		
		

		
			
			p.question = "Assuming the current trend continues, in 30 years Greece will have more children than elderly members of the population.";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			
				
				p.addAnswer(1, "True", false, "");
				
			
				
				p.addAnswer(2, "False", true, "");
				
				

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- truefalse ------------
		//
		
			p = new Problem("truefalse");
		
		p.id = 337438;


		
		

		
			
			p.question = "Assuming the current trend continues, in 30 years Greece will have more reproductive-age individuals than children.";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			
				
				p.addAnswer(1, "True", true, "");
				
			
				
				p.addAnswer(2, "False", false, "");
				
				

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- truefalse ------------
		//
		
			p = new Problem("truefalse");
		
		p.id = 337439;


		
		

		
			
			p.question = "Assuming the current trend continues, in 30 years Greece will have more elderly than reproductive-age individuals.";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			
				
				p.addAnswer(1, "True", true, "");
				
			
				
				p.addAnswer(2, "False", false, "");
				
				

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337440;


		
		

		
			
			p.question = "Greece had more females than males in 2000. Which of the following is the most likely explanation for this?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Females generally have a shorter life span than males.",
				false,
				"");
			
				p.addAnswer(2, "Males generally have a shorter life span than females.",
				true,
				"");
			
				p.addAnswer(3, "There should be an equal number of males and females in every age group, so this is likely an error in the 2000 census for Greece.",
				false,
				"");
			
				p.addAnswer(4, "More females are born than males, and this difference remains throughout all age groups.",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337441;


		
		

		
			
			p.question = "The population of Colombia is currently _______.";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "expanding",
				true,
				"");
			
				p.addAnswer(2, "stable",
				false,
				"");
			
				p.addAnswer(3, "declining",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- truefalse ------------
		//
		
			p = new Problem("truefalse");
		
		p.id = 337442;


		
		

		
			
			p.question = "Assuming the current trend continues, in 30 years Colombia will have more children than reproductive-age individuals.";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			
				
				p.addAnswer(1, "True", true, "");
				
			
				
				p.addAnswer(2, "False", false, "");
				
				

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- truefalse ------------
		//
		
			p = new Problem("truefalse");
		
		p.id = 337443;


		
		

		
			
			p.question = "Assuming the current trend continues, in 30 years Colombia will have more children than elderly members of the population.";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			
				
				p.addAnswer(1, "True", true, "");
				
			
				
				p.addAnswer(2, "False", false, "");
				
				

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- truefalse ------------
		//
		
			p = new Problem("truefalse");
		
		p.id = 337444;


		
		

		
			
			p.question = "Assuming the current trend continues, in 30 years Colombia will have more reproductive-age individuals than children.";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			
				
				p.addAnswer(1, "True", false, "");
				
			
				
				p.addAnswer(2, "False", true, "");
				
				

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- truefalse ------------
		//
		
			p = new Problem("truefalse");
		
		p.id = 337445;


		
		

		
			
			p.question = "Assuming the current trend continues, in 30 years Colombia will have more elderly than reproductive-age individuals.";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			
				
				p.addAnswer(1, "True", false, "");
				
			
				
				p.addAnswer(2, "False", true, "");
				
				

		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

