

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "26: Phylogeny and The Tree of Life > Practice Test";
	ak.quiz_loc_with_commas = "26: Phylogeny and The Tree of Life, Practice Test";
	ak.quiz_title = "Practice Test";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 30;
	ak.non_essay_total = 30;
	ak.scored_item_total = 30;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335593;


		
		

		
			
			p.question = "The analytical approach to understanding the diversity and relatedness of both extant and extinct organisms is called _____. (<script type=\"text/javascript\">ebook(\'26OV\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "systematics",
				true,
				"Correct. Systematists study morphological and behavioral resemblances as well as molecular similarities and differences to devise theories about relationships.");
			
				p.addAnswer(2, "evolution",
				false,
				"No. Evolution can be defined as descent with modification.");
			
				p.addAnswer(3, "taxonomy",
				false,
				"No. Taxonomy is the naming of organisms.");
			
				p.addAnswer(4, "binomial nomenclature",
				false,
				"No. This refers to a convention that calls for every species name to consist of two parts.");
			
				p.addAnswer(5, "phylogeny",
				false,
				"No. Phylogeny is the evolutionary history of a species or group of related species.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335594;


		
		

		
			
			p.question = "What is the focus of the branch of biology called taxonomy? (<script type=\"text/javascript\">ebook(\'2601\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "evolution",
				false,
				"No. Although taxonomic observations serve as a basis for evolutionary theory, taxonomy is based primarily on observed relationships.");
			
				p.addAnswer(2, "the classification of life-forms by their similarities and differences",
				true,
				"Correct. This is exactly what the study of taxonomy seeks to accomplish.");
			
				p.addAnswer(3, "genetics",
				false,
				"No. The science of taxonomy predates the understanding of genetics.");
			
				p.addAnswer(4, "the history of the field of biology",
				false,
				"No. Taxonomy is not a historical study.");
			
				p.addAnswer(5, "the environment",
				false,
				"No. The study of environmental biology is referred to as ecology.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335595;


		
		

		
			
			p.question = "The binomial system assigns to each organism a unique name that describes its _____. (<script type=\"text/javascript\">ebook(\'2601\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "order and family",
				false,
				"No. Each species is assigned a two-part Latin name, or binomial. The first word is the genus and the second word is the species. Species that are very similar are grouped into the same genus.");
			
				p.addAnswer(2, "body plan and habitat",
				false,
				"No. Each species is assigned a two-part Latin name, or binomial. The first word is the genus and the second word is the species. Species that are very similar are grouped into the same genus.");
			
				p.addAnswer(3, "genus and species",
				true,
				"Correct. Each species is assigned a two-part Latin name, or binomial. The first word is the genus and the second word is the species. Species that are very similar are grouped into the same genus.");
			
				p.addAnswer(4, "family and species",
				false,
				"No. Each species is assigned a two-part Latin name, or binomial. The first word is the genus and the second word is the species. Species that are very similar are grouped into the same genus.");
			
				p.addAnswer(5, "evolutionary history",
				false,
				"No. Each species is assigned a two-part Latin name, or binomial. The first word is the genus and the second word is the species. Species that are very similar are grouped into the same genus.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335596;


		
		

		
			
			p.question = "The two-part format of the scientific name, referred to as binomial, ensures that _____. (<script type=\"text/javascript\">ebook(\'2601\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "each species is assigned a unique name",
				false,
				"No. This is true, but there is a better response.");
			
				p.addAnswer(2, "each species has a name that is understandable regardless of language barriers among scientists",
				false,
				"No. This is true, but there is a better response.");
			
				p.addAnswer(3, "systematists can easily specify the closest relatives of any species",
				false,
				"No. This is true, but there is a better response.");
			
				p.addAnswer(4, "all of the above",
				true,
				"Correct. Scientific names avoid ambiguity.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335597;


		
		

		
			
			p.question = "All the members of which one of the following groups have the greatest number of characteristics in common? (<script type=\"text/javascript\">ebook(\'2601\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "class",
				false,
				"No. Of the choices, this is not the least inclusive level of classification.");
			
				p.addAnswer(2, "genus",
				false,
				"No. Of the choices, this is not the least inclusive level of classification.");
			
				p.addAnswer(3, "kingdom",
				false,
				"No. Of the choices, this is not the least inclusive level of classification. In fact, with the exception of domain, this is the most inclusive.");
			
				p.addAnswer(4, "phylum",
				false,
				"No. Of the choices, this is not the least inclusive level of classification.");
			
				p.addAnswer(5, "species",
				true,
				"Correct. The taxonomic hierarchy is reflective of the relationships among groups. The further down the taxonomic hierarchy, the closer are the relationships. (That is, individuals of the same species are more closely related than are individuals of the same genus that belong to different species within that genus.)");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335598;


		
		

		
			
			p.question = "A taxon _____. (<script type=\"text/javascript\">ebook(\'2601\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "is a formal grouping at any given level",
				true,
				"Correct. A taxon is a formal grouping of organisms at any given level, such as species, genus, or phylum.");
			
				p.addAnswer(2, "is a formal grouping in any level from phylum to species",
				false,
				"No. A taxon is a formal grouping at any given level.");
			
				p.addAnswer(3, "is a clade",
				false,
				"No. Possibly, but not necessarily.");
			
				p.addAnswer(4, "is a species",
				false,
				"No. A taxon is a formal grouping at any given level.");
			
				p.addAnswer(5, "of one type of organism at one level is comparable to another type of organism at the same level.",
				false,
				"No. Most likely not. For example, an order of snails would not be compared morphologically to an order of mammals.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335599;


		
		

		
			
			p.question = "Two worms in the same class must also be grouped in the same _____. (<script type=\"text/javascript\">ebook(\'2601\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "order",
				false,
				"No. Order is less inclusive than class; thus, they could be in the same class and different orders.");
			
				p.addAnswer(2, "phylum",
				true,
				"Correct. Class is less inclusive than phylum; organisms that are in the same class are also in the same phylum.");
			
				p.addAnswer(3, "genus",
				false,
				"No. Genus is less inclusive than class; thus, they could be in the same class and different genera.");
			
				p.addAnswer(4, "family",
				false,
				"No. Family is less inclusive than class; thus, they could be in the same class and different families.");
			
				p.addAnswer(5, "species",
				false,
				"No. Species is less inclusive than class; thus, they could be in the same class and be different species.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335600;


		
		

		
			
			p.question = "Species A and species B are in the same phylum. Species A and species C, but not species B, are in the same order. From this information you can conclude that _____. (<script type=\"text/javascript\">ebook(\'2601\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "species C could be in the same class as species A and B",
				true,
				"Correct. If species A and species C are in the same order, then they must also be in the same class. Since you know that species A and species B are in the same phylum, it is possible that they are in the same class, but different orders.");
			
				p.addAnswer(2, "species A and species B are in the same family",
				false,
				"No. If they are not in the same order, then they cannot be in the same family.");
			
				p.addAnswer(3, "species B and species C share a less recent ancestor than do species A and B",
				false,
				"No. You cannot make this conclusion from the given information.");
			
				p.addAnswer(4, "all three species are members of the same genus",
				false,
				"No. This is not possible because all three species are not even members of the same order.");
			
				p.addAnswer(5, "all three species are not members of the same phylum",
				false,
				"No. All three species are members of the same phylum.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335601;


		
		

		
			
			p.question = "What does a branch point in a phylogenetic tree represent? (<script type=\"text/javascript\">ebook(\'2601\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A branch point represents a split between two phyla.",
				false,
				"No. A branch point does not have a set rank on a phylogenetic tree. It is a point at which two evolutionary lineages diverge from a common ancestor.");
			
				p.addAnswer(2, "A branch point represents a gene duplication event.",
				false,
				"No. A gene duplication event does not necessarily cause two lineages to split from a common ancestor.");
			
				p.addAnswer(3, "A branch point represents a place where one species branches off from another.",
				false,
				"No. A branch point does not have a set rank on a phylogenetic tree. It is a point at which two evolutionary lineages diverge from a common ancestor.");
			
				p.addAnswer(4, "A branch point represents the absolute time at which two evolutionary lineages split from a common ancestor.",
				false,
				"No. Without evidence from the fossil record and radiometric dating, it is not possible to put an absolute date on branch points.");
			
				p.addAnswer(5, "A branch point represents a point at which two evolutionary lineages split from a common ancestor.",
				true,
				"Correct. A branch point shows evolutionary relationships as a dichotomy.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335602;


		
		

		
			
			p.question = "Which one of the following methods to establish phylogenetic relationships among organisms has been developed most recently? (<script type=\"text/javascript\">ebook(\'2602\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "comparing morphology (shape and structure)",
				false,
				"No. Didn\'t Darwin use this method?");
			
				p.addAnswer(2, "comparing physiology (the functioning of structures and systems)",
				false,
				"No. This is a method of observation and could be performed to some extent without the technology we have available today.");
			
				p.addAnswer(3, "comparing the component sequences of proteins and nucleic acids",
				true,
				"Correct. The comparison of nucleic acids and proteins has become a powerful addition to the other comparative methods that systematists use to measure evolutionary relationships among species.");
			
				p.addAnswer(4, "comparing behavioral patterns",
				false,
				"No. This is a method of observation and could be performed to some extent without the technology we have available today.");
			
				p.addAnswer(5, "comparing embryonic development",
				false,
				"No. This is a method of observation and could be performed to some extent without the technology we have available today.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335603;


		
		

		
			
			p.question = "The wings of a hummingbird and a bee are _____. (<script type=\"text/javascript\">ebook(\'2602\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "homologous",
				false,
				"No. This refers to structures that are similar due to common ancestry.");
			
				p.addAnswer(2, "phylogenetic",
				false,
				"No. \"Phylogeny\" refers to the evolutionary history of a lineage.");
			
				p.addAnswer(3, "analogous",
				true,
				"Correct. Structures that are similar as a result of convergent evolution are referred to as analogous structures.");
			
				p.addAnswer(4, "binomial",
				false,
				"No. An organism\'s scientific name is a binomial consisting of the genus and the specific epithet.");
			
				p.addAnswer(5, "taxonomic",
				false,
				"No. Taxonomy is the naming and classifying of organisms.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335604;


		
		

		
			
			p.question = "Which of the following would be the least useful in determining the relationships among various species? (<script type=\"text/javascript\">ebook(\'2602\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a comparison of DNA base sequences",
				false,
				"No. The more similar the DNA base sequences, the closer the relationship.");
			
				p.addAnswer(2, "homologous structures",
				false,
				"No. Homology is indicative of a common ancestry.");
			
				p.addAnswer(3, "fossils",
				false,
				"No. Ancestral-descendant sequences can be traced through the fossil record.");
			
				p.addAnswer(4, "amino acid sequences of proteins",
				false,
				"No. The more similar the amino acid sequences, the closer the relationship.");
			
				p.addAnswer(5, "analogous structures",
				true,
				"Correct. Analogous structures are the result of convergent evolution and may not reflect the relationships among the species that share them.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335605;


		
		

		
			
			p.question = "Researchers can use molecular homologies to _____. (<script type=\"text/javascript\">ebook(\'2602\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "estimate how long ago the common ancestor lived",
				false,
				"No. This is not the best answer. The fact that molecules have diverged between species does not in itself tell us how long ago their common ancestor lived.");
			
				p.addAnswer(2, "reveal the amount of mutations in a particular sequence that have occurred between the species since they diverged from a common ancestor",
				true,
				"Correct. Over long periods of time, insertions and deletions accumulate.");
			
				p.addAnswer(3, "hypothesize about the morphological structures of a common ancestor",
				false,
				"No. The fossil record is much more useful for this purpose.");
			
				p.addAnswer(4, "hypothesize about the behavior of a common ancestor",
				false,
				"No. This information would not be discernible from studying molecular homologies.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. Only one of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335606;


		
		

		
			
			p.question = "A phylogenetic tree of bird families constructed by cladistic analysis would be a hypothesis about which of the following? (<script type=\"text/javascript\">ebook(\'2603\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "characteristics shared by all bird families",
				false,
				"No. Characteristics shared by all bird families would not allow for a determination of the relationships among bird families.");
			
				p.addAnswer(2, "evolutionary relationships among bird families",
				true,
				"Correct. Phylogenetic trees are constructed to reflect the evolutionary relationships among organisms.");
			
				p.addAnswer(3, "families that look most alike",
				false,
				"No. Phylogeny does not necessarily match similarity of appearance.");
			
				p.addAnswer(4, "analogous structures shared by various species",
				false,
				"No. Analogous structures are excluded from cladistic analysis.");
			
				p.addAnswer(5, "relative ages of living species of birds",
				false,
				"No. Such information is not necessarily found on a phylogenetic tree.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335607;


		
		

		
			
			p.question = "Looking at the table and phylogenetic tree in Figure 26.11, which of the following is a true statement? (<script type=\"text/javascript\">ebook(\'2603\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Four walking legs is a shared ancestral character in salamanders and a shared derived character in turtles.",
				false,
				"No. Just the opposite is true.");
			
				p.addAnswer(2, "Four walking legs is a shared derived character in salamanders and a shared ancestral character in turtles.",
				true,
				"Correct. Four walking legs first appears in amphibians and was then inherited by reptiles.");
			
				p.addAnswer(3, "Hinged jaws are derived from lampreys.",
				false,
				"No. Hinged jaws are not present in lampreys, and there is not enough information here to state that hinged jaws developed in the lamprey\'s lineage.");
			
				p.addAnswer(4, "Four walking legs is a shared derived character in leopards.",
				false,
				"No. Since four legs appear in salamanders and turtles, they constitute a shared ancestral character.");
			
				p.addAnswer(5, "The amniotic egg is a shared derived character in salamanders.",
				false,
				"No. Salamanders do not have amniotic eggs.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335608;


		
		

		
			
			p.question = "Many researchers who study the kingdom Protista argue that all of these organisms should <b>not</b> be placed in the same kingdom, because these organisms could not have evolved from a common ancestor. In other words, they argue that the kingdom Protista is _____. (<script type=\"text/javascript\">ebook(\'2603\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "polyphyletic",
				true,
				"Correct. A taxon is polyphyletic if its members are derived from ancestors that are not common to all members.");
			
				p.addAnswer(2, "paraphyletic",
				false,
				"No. The members of paraphyletic clades share a common ancestor.");
			
				p.addAnswer(3, "monophyletic",
				false,
				"No. The members of a monophyletic clade share a common ancestor. However, unlike a paraphyletic group, all of the individuals derived from the most recent common ancestor are included.");
			
				p.addAnswer(4, "heterophyletic",
				false,
				"No. The taxon in question would be described as polyphyletic because its members are derived from ancestors that are not common to all members.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335609;


		
		

		
			
			p.question = "Using cladistic analysis, a taxonomist wishes to construct a phylogenetic tree showing the relationships among various species of mammals. Which of the following would be the <b>least</b> useful for this purpose? (<script type=\"text/javascript\">ebook(\'2603\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "descriptions of various types of limbs (wings, legs, flippers, etc.)",
				false,
				"No. Such information would be useful in identifying shared primitive characters and shared derived characters.");
			
				p.addAnswer(2, "the fact that all mammals have hair",
				true,
				"Correct. As a shared derived character, hair cannot be used to determine the phylogeny of mammals.");
			
				p.addAnswer(3, "data about skull bones",
				false,
				"No. These data might contain information regarding shared primitive characters and shared derived characters.");
			
				p.addAnswer(4, "the fact that teeth vary among types of mammals",
				false,
				"No. Variation among the teeth of different types of mammals may be used to distinguish among shared primitive and shared derived characteristics.");
			
				p.addAnswer(5, "DNA base sequences",
				false,
				"No. Similarities and differences among DNA-based sequences play an important role in the construction of phylogenetic trees.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335610;


		
		

		
			
			p.question = "Which statement below is true about an outgroup? (<script type=\"text/javascript\">ebook(\'2603\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Outgroup comparison is based on the assumption that homologies present in both the outgroup and ingroup must be derived characters.",
				false,
				"No. They must be primitive characters that predate the ancestor common to the outgroup and ingroup.");
			
				p.addAnswer(2, "The outgroup would be found at one of the highest branches of a phylogenetic tree.",
				false,
				"No. The outgroup should be found at the base of the tree.");
			
				p.addAnswer(3, "The outgroup and ingroup display a mixture of shared and derived characters.",
				false,
				"No. This is only true of the ingroup.");
			
				p.addAnswer(4, "The outgroup should be less closely related to any members of the ingroup than they are to each other.",
				true,
				"Correct. The outgroup should be known to be less closely related than any ingroup members are to each other based on other evidence such as paleontology, embryonic development, and gene sequences.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the statements is true.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335611;


		
		

		
			
			p.question = "Phylogenetic trees with branch lengths proportional to time can be used to _____. (<script type=\"text/javascript\">ebook(\'2603\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "estimate the amount of time since two groups diverged from a common ancestor",
				false,
				"No. This type of tree can be used to <i>represent</i> the amount of time since two groups diverged from a common ancestor.");
			
				p.addAnswer(2, "represent the chronological time that has passed since two groups diverged from a common ancestor",
				true,
				"Correct. In this type of tree, called an ultrametric tree, the branching pattern is the same as in a normal phylogenetic tree, but all the branches that can be traced from the common ancestor to the present are of equal length.");
			
				p.addAnswer(3, "reflect the number of evolutionary changes that have taken place in a lineage",
				false,
				"No. This is true of regular phylogenetic trees.");
			
				p.addAnswer(4, "reflect the rate of evolutionary change",
				false,
				"No. This is true of regular phylogenetic trees.");
			
				p.addAnswer(5, "tie polyphyletic clades to a common ancestor",
				false,
				"No. A phylogenetic tree with polyphyletic clades requires further reconstruction to uncover species that tie together these groupings into monophyletic clades. This is not the purpose of using an ultrametric tree to represent a hypothesis of evolutionary relationships.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335612;


		
		

		
			
			p.question = "Which statement below is true of parsimonious trees? (<script type=\"text/javascript\">ebook(\'2603\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The best tree requires the fewest evolutionary events to have occurred in the form of shared derived characters.",
				true,
				"Correct. This statement is true regarding trees based on morphological characters. For phylograms based on DNA, the most parsimonious tree requires the smallest number of base changes in DNA.");
			
				p.addAnswer(2, "The best tree requires the fewest evolutionary events to have occurred in the form of shared ancestral characters.",
				false,
				"No. You may want to review the definitions of shared ancestral and derived characters.");
			
				p.addAnswer(3, "Given the rules of how morphological traits change over time, a tree can be found that reflects the most likely sequence of evolutionary events.",
				false,
				"No. There are no true rules about how morphological traits change over time. There are certain rules regarding how DNA changes; however, this statement is more related to the principle of maximum likelihood.");
			
				p.addAnswer(4, "Given the rules of how DNA changes over time, a tree can be found that reflects the most likely sequence of evolutionary events.",
				false,
				"No. This statement is true, but it applies more to the principle of maximum likelihood than it does to maximum parsimony.");
			
				p.addAnswer(5, "Trees can be constructed that are parsimonious or the most likely, but not both at the same time.",
				false,
				"No. Although this is a difficult task, especially when working with a large data set, many computerized tools have been devised to search for trees that are the most parsimonious and the most likely.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335613;


		
		

		
			
			p.question = "Birds and mammals have a four-chambered heart, but reptiles have a three-chambered heart. How does this fact affect the construction of phylogenetic trees for these groups? (<script type=\"text/javascript\">ebook(\'2603\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "It shows that the common ancestor of birds and mammals must have had a four-chambered heart.",
				false,
				"No. This would be the most parsimonious assumption. Abundant evidence, however, suggests that birds are more closely related to reptiles than they are to mammals. Thus, the common ancestor of birds and mammals could not have had a four-chambered heart.");
			
				p.addAnswer(2, "This represents a problem with the principle of parsimony, rather than a problem with the analogy-homology issue.",
				false,
				"No. Just the opposite is true. A four-chambered heart must have developed independently in birds and mammals. To be the most accurate, a phylogenetic tree should represent several different characters to overcome problems with analogy and homology.");
			
				p.addAnswer(3, "The most likely tree is always the most parsimonious.",
				false,
				"No. Often this is true. But in this situation, evidence shows that birds diverged from reptiles before mammals did; therefore, there is no common ancestor of birds and mammals that had a four-chambered heart. This character must have evolved twice.");
			
				p.addAnswer(4, "The most likely tree is not always the most parsimonious.",
				true,
				"Correct. Evidence shows that birds diverged from reptiles before mammals; therefore, there is no common ancestor of birds and mammals that had a four-chambered heart. This character must have evolved twice.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335614;


		
		

		
			
			p.question = "If you wanted to determine the lineage of plants that have evolved on a relatively young archipelago&mdash;approximately 15,000 years old&mdash;what type of nucleic acid should you compare? (<script type=\"text/javascript\">ebook(\'2604\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "mRNA",
				false,
				"No. Messenger RNA would not be the most likely choice.");
			
				p.addAnswer(2, "rRNA",
				false,
				"No. Ribosomal RNA changes relatively slowly. In 15,000 years there may not be enough changes to draw any conclusions.");
			
				p.addAnswer(3, "mtDNA",
				true,
				"Correct. Mitochondrial DNA (mtDNA) evolves rapidly and can be used to explore more recent evolutionary events.");
			
				p.addAnswer(4, "tRNA",
				false,
				"No. Transfer RNA would not be the most likely choice.");
			
				p.addAnswer(5, "miRNA",
				false,
				"No. Micro-RNA would not be the most likely choice.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335615;


		
		

		
			
			p.question = "Paralogous genes _____. (<script type=\"text/javascript\">ebook(\'2604\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "are passed from generation to generation in a straight line",
				false,
				"No. This is true of orthologous genes.");
			
				p.addAnswer(2, "result from gene duplication",
				true,
				"Correct. Paralogous genes are found in more than one copy in the same genome. An example is the olfactory receptor genes in vertebrates, which have undergone many gene duplications.");
			
				p.addAnswer(3, "can only diverge after speciation has taken place",
				false,
				"No. This is true of orthologous genes.");
			
				p.addAnswer(4, "are responsible for the differences in beta hemoglobin in humans and mice",
				false,
				"No. Beta hemoglobin genes are orthologous.");
			
				p.addAnswer(5, "cannot diverge in the same gene pool",
				false,
				"No. Unlike orthologous genes, paralogous genes can diverge in the same gene pool.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335616;


		
		

		
			
			p.question = "What is the evolutionary significance of paralogous genes? (<script type=\"text/javascript\">ebook(\'2604\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "They increase the size of the genome and provide more opportunity for the evolution of novel characteristics.",
				true,
				"Correct. Because paralogous genes result from gene duplication, they provide extra copies of genes. These extra copies may be free to evolve, eventually providing evolutionary novelty.");
			
				p.addAnswer(2, "They give the absolute time that the gene duplication occurred.",
				false,
				"No. It is possible to make some estimate of the time of gene duplication using molecular clock principles, but it is very difficult to get an accurate date with only one gene.");
			
				p.addAnswer(3, "They give the absolute time that two species diverged.",
				false,
				"No. Because paralogous genes result from gene duplication, the duplicated genes can diverge from each other without speciation occurring. Paralogous genes are not very useful in looking at when species diverge.");
			
				p.addAnswer(4, "The fact that many paralogous genes are found in vastly different organisms emphasizes the many biochemical and developmental pathways shared by all organisms.",
				false,
				"No. This is true of orthologous genes.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the answers is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335617;


		
		

		
			
			p.question = "What is the evolutionary significance of orthologous genes? (<script type=\"text/javascript\">ebook(\'2604\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "They increase the size of the genome and provide more opportunity for the evolution of novel characteristics.",
				false,
				"No. This is true of paralogous genes.");
			
				p.addAnswer(2, "They are passed from generation to generation in a straight line, and as such they change very little.",
				false,
				"No. Although it is true that orthologous genes are passed in a straight line, they may change significantly.");
			
				p.addAnswer(3, "The high percentage of orthologous genes found in vastly different organisms emphasizes the many biochemical and developmental pathways shared by all organisms.",
				true,
				"Correct. The prevalence of orthologous genes supports the idea of descent with modification.");
			
				p.addAnswer(4, "They always provide the evolutionary explanation with the maximum parsimony.",
				false,
				"No. It is not always the case that straight line inheritance provides the most parsimonious explanation for observed phylogenetic trends.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. Only one of the answers is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335618;


		
		

		
			
			p.question = "Which is an assumption of the neutral theory? (<script type=\"text/javascript\">ebook(\'2605\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Much evolutionary change in genes and proteins has no effect on fitness and therefore is not influenced by Darwinian selection.",
				true,
				"Correct.  This theory states that these changes are mostly neutral-neither adaptive nor detrimental.");
			
				p.addAnswer(2, "Most harmful mutations are removed from a population quickly.",
				false,
				"No. This is an assumption of the neutral theory, but there is a better answer.");
			
				p.addAnswer(3, "Differences in the rate of the clock in different genes are a function of how important each gene is.",
				false,
				"No. This is an assumption of the neutral theory, but there is a better answer.");
			
				p.addAnswer(4, "If a particular sequence of amino acids is critical for survival, most new mutations will be harmful and fewer will be neutral. These genes will change slowly over time.",
				false,
				"No. This is an assumption of the neutral theory, but there is a better answer.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No.  Only one answer is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335619;


		
		

		
			
			p.question = "The idea of using molecules as clocks to time evolutionary events is very attractive, but there are many problems in actually applying the technique. What seems to be the best way to get reliable results? (<script type=\"text/javascript\">ebook(\'2605\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "It is important to use a gene that has been affected by natural selection to ensure that evolution will be observed.",
				false,
				"No. Genes that have been affected by natural selection are unlikely to have constant rates of change, so they are not good candidates for molecular clocks.");
			
				p.addAnswer(2, "It is important to use as many genes as possible. With this approach, fluctuations in evolutionary rate will tend to average out.",
				true,
				"Correct. It is almost impossible to find a gene that has been unaffected by natural selection during its entire existence. Using many genes has been shown to give dates that match the fossil record fairly closely.");
			
				p.addAnswer(3, "It is important to use one gene in which the changes are clearly neutral.",
				false,
				"No. It is difficult to determine whether all the changes in a gene are neutral; therefore, it is better to use several genes so that directional changes may average out.");
			
				p.addAnswer(4, "It is best to use a gene that is essential to survival because they change more slowly.",
				false,
				"No. The choice of gene will determine the timeframe that can be examined, but an essential gene will still be prone to evolving at different speeds.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. Only one of the answers is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335620;


		
		

		
			
			p.question = "By applying a molecular clock, researchers at Los Alamos National Laboratory have proposed that the first HIV-1 M invasion into humans occurred in the _____. (<script type=\"text/javascript\">ebook(\'2605\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "1830s",
				false,
				"No. They hypothesize that the invasion happened after the 1830s.");
			
				p.addAnswer(2, "1890s",
				false,
				"No. They hypothesize that the invasion happened somewhat after the 1890s.");
			
				p.addAnswer(3, "1930s",
				true,
				"Correct. This is the point in time when some scientists estimate that HIV jumped from simians to humans.");
			
				p.addAnswer(4, "1950s",
				false,
				"No. They hypothesize that the invasion happened before the 1950s.");
			
				p.addAnswer(5, "1980s",
				false,
				"No. HIV infection was certainly occurring in epidemic proportions by the 1980s. They hypothesize that the invasion happened somewhat before the 1980s.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335621;


		
		

		
			
			p.question = "To which domain is the domain Eukarya (the domain to which humans belong) most closely related? (<script type=\"text/javascript\">ebook(\'2606\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Bacteria",
				false,
				"No. According to analyses of rRNA genes, eukaryotes appear to be more closely related to the archaea than they are to bacteria.");
			
				p.addAnswer(2, "Fungi",
				false,
				"No. Fungi are a kingdom, not a domain.");
			
				p.addAnswer(3, "Archaea",
				false,
				"No. Although rRNA genes indicate that eukaryotes and archaea are more closely related, genes that influence metabolism indicate a closer relationship between eukaryotes and bacteria.");
			
				p.addAnswer(4, "Protista",
				false,
				"No. Protista is a kingdom, not a domain, and it is in the process of being extensively revised.");
			
				p.addAnswer(5, "It is not clear whether eukaryotes are more closely related to bacteria or archaea.",
				true,
				"Correct. Studies of rRNA genes indicate that eukaryotes and archaea are more closely related, but genes that influence metabolism indicate a closer relationship between eukaryotes and bacteria. Horizontal gene transfer has likely been at work here.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335622;


		
		

		
			
			p.question = "Universal phylogenetic trees built from different genes sometimes give inconsistent results. What basic assumption on which phylogenetic trees are based has probably been violated during the history of life? (<script type=\"text/javascript\">ebook(\'2606\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Analogous traits come about because of convergent evolution.",
				false,
				"No. This assumption still appears to be valid.");
			
				p.addAnswer(2, "Homologous traits come about because of common ancestry.",
				false,
				"No. This assumption still appears to be valid.");
			
				p.addAnswer(3, "The greater the difference in gene sequences, the longer two species have diverged.",
				false,
				"No. This assumption appears to be valid overall.");
			
				p.addAnswer(4, "Genes are often passed from one organism to another without the occurrence of reproduction.",
				false,
				"No. This is not one of the assumptions on which phylogenetic trees are based..");
			
				p.addAnswer(5, "Genes are passed vertically from one generation to the next.",
				true,
				"Correct. Phylogenetic trees assume vertical gene transfer, but many organisms also use horizontal gene transfer. Many scientists postulate that horizontal gene transfer was far more prevalent during the early history of life.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

