

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "55: Ecosystems > Activities Quiz";
	ak.quiz_loc_with_commas = "55: Ecosystems, Activities Quiz";
	ak.quiz_title = "Activities Quiz";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 15;
	ak.non_essay_total = 15;
	ak.scored_item_total = 15;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337097;


		
		

		
			
			p.question = "_____ are secondary consumers. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?54&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Pyramids of Production</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Producers",
				false,
				"Secondary consumers consume primary consumers that consume producers.");
			
				p.addAnswer(2, "Herbivores",
				false,
				"Herbivores, animals that eat plants, are primary consumers.");
			
				p.addAnswer(3, "Plants",
				false,
				"Plants are producers.");
			
				p.addAnswer(4, "Cows",
				false,
				"Cows are primary consumers.");
			
				p.addAnswer(5, "Carnivores",
				true,
				"Secondary consumers are animals that eat other animals; thus, they are carnivores.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337098;


		
		

		
			
			p.question = "Approximately _____% of the energy at one trophic level is passed on to the next highest trophic level. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?54&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Pyramids of Production</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "0&#150;5",
				false,
				"Higher.");
			
				p.addAnswer(2, "5&#150;10",
				true,
				"Approximately 5&#8211;10% of the energy at one trophic level is passed on to the next highest trophic level.");
			
				p.addAnswer(3, "10&#150;15",
				false,
				"Lower.");
			
				p.addAnswer(4, "15&#150;20",
				false,
				"Lower.");
			
				p.addAnswer(5, "90&#150;100",
				false,
				"You might want to review the laws of thermodynamics.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337099;


		
		

		
			
			p.question = "10,000 kcal of producer could support approximately _____ kcal of tertiary consumer. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?54&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Pyramids of Production</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "1,000",
				false,
				"This is the number of kcal of primary consumer that could be supported.");
			
				p.addAnswer(2, "100",
				false,
				"This is the number of kcal of secondary consumer that could be supported.");
			
				p.addAnswer(3, "10",
				true,
				"This is the number of kcal of tertiary consumer that could be supported.");
			
				p.addAnswer(4, "1",
				false,
				"This is the number of kcal of quaternary consumer that could be supported.");
			
				p.addAnswer(5, "0",
				false,
				"You might want to try doing the math again.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337100;


		
		

		
			
			p.question = "Where do plants get the energy to make organic molecules? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?1&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Energy Flow and Chemical Cycling</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "minerals",
				false,
				"Consider that \"photosynthesis\" is the name given to the process by which plants make organic molecules.");
			
				p.addAnswer(2, "glucose",
				false,
				"Glucose is an organic molecule made by plants.");
			
				p.addAnswer(3, "vitamins",
				false,
				"Consider that \"photosynthesis\" is the name given to the process by which plants make organic molecules.");
			
				p.addAnswer(4, "light",
				true,
				"In photosynthesis, plants use the energy of light to make organic molecules.");
			
				p.addAnswer(5, "water",
				false,
				"Consider that \"photosynthesis\" is the name given to the process by which plants make organic molecules.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337101;


		
		

		
			
			p.question = "Which of these is NOT an organic molecule? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?1&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Energy Flow and Chemical Cycling</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "carbohydrates",
				false,
				"Carbohydrates are organic molecules.");
			
				p.addAnswer(2, "minerals",
				true,
				"Minerals are inorganic.");
			
				p.addAnswer(3, "proteins",
				false,
				"Proteins are organic molecules.");
			
				p.addAnswer(4, "glucose",
				false,
				"Glucose, a carbohydrate, is an organic compound.");
			
				p.addAnswer(5, "lipids",
				false,
				"Lipids are organic molecules.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337102;


		
		

		
			
			p.question = "Where do plants get the carbon they use to make organic molecules? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?1&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Energy Flow and Chemical Cycling</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "glucose",
				false,
				"Glucose is an organic molecule made by plants.");
			
				p.addAnswer(2, "oxygen",
				false,
				"Oxygen, O<sub>2</sub>, does not contain carbon.");
			
				p.addAnswer(3, "water",
				false,
				"Water, H<sub>2</sub>O, does not contain carbon.");
			
				p.addAnswer(4, "starch",
				false,
				"Starch is an organic molecule made by plants.");
			
				p.addAnswer(5, "carbon dioxide",
				true,
				"Plants use the carbon in atmospheric carbon dioxide to make organic molecules.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337103;


		
		

		
			
			p.question = "What name is given to the process by which detritivores return carbon to the atmosphere? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?54&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Carbon Cycle</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "burning",
				false,
				"Detritivores do not burn molecules.");
			
				p.addAnswer(2, "predation",
				false,
				"By predation carbon is transferred from one living organism to another.");
			
				p.addAnswer(3, "photosynthesis",
				false,
				"Photosynthesis removes carbon from the atmosphere.");
			
				p.addAnswer(4, "predation and photosynthesis",
				false,
				"Neither of these processes returns carbon dioxide to the atmosphere.");
			
				p.addAnswer(5, "decomposition",
				true,
				"Decomposition, the conversion of organic molecules into inorganic molecules, results in the release of carbon dioxide into the atmosphere.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337104;


		
		

		
			
			p.question = "Which of these removes carbon from the atmosphere? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?54&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Carbon Cycle</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "logging trees",
				false,
				"Logging results in an addition of carbon to the atmosphere.");
			
				p.addAnswer(2, "rabbits",
				false,
				"Animals, such as rabbits, add carbon dioxide to the atmosphere.");
			
				p.addAnswer(3, "burning fossil fuels, such as oil",
				false,
				"The burning of fossil fuels adds carbon to the atmosphere.");
			
				p.addAnswer(4, "bobcats",
				false,
				"Animals, such as bobcats, add carbon dioxide to the atmosphere.");
			
				p.addAnswer(5, "algae",
				true,
				"Photosynthetic organisms, such as algae, remove carbon from the atmosphere.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337105;


		
		

		
			
			p.question = "Detritus is composed of _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?54&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Carbon Cycle</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "detritivores",
				false,
				"Detritivores consume detritus.");
			
				p.addAnswer(2, "dead organic matter",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(3, "inorganic minerals",
				false,
				"Some organisms convert detritus into inorganic minerals.");
			
				p.addAnswer(4, "excreted wastes",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(5, "dead organic matter and excreted wastes",
				true,
				"Detritus is composed of dead organic matter and excreted wastes.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337106;


		
		

		
			
			p.question = "Nitrifying bacteria convert _____ to _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?37&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Nitrogen Cycle</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "nitrogen gas ... ammonium",
				false,
				"This conversion is accomplished by nitrogen-fixing bacteria.");
			
				p.addAnswer(2, "nitrogen gas ... nitrates",
				false,
				"Lightning converts nitrogen gas to nitrates.");
			
				p.addAnswer(3, "ammonium ... nitrites",
				true,
				"Nitrifying bacteria convert ammonium to nitrites.");
			
				p.addAnswer(4, "nitrates ... nitrogen gas",
				false,
				"Denitrifying bacteria convert nitrates to nitrogen gas.");
			
				p.addAnswer(5, "ammonium ... nitrogen gas",
				false,
				"Such a conversion is not accomplished by nitrifying bacteria.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337107;


		
		

		
			
			p.question = "_____ removes nitrogen from the atmosphere. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?37&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Nitrogen Cycle</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Denitrification",
				false,
				"Denitrification adds nitrogen gas to the atmosphere.");
			
				p.addAnswer(2, "Nitrification",
				false,
				"Nitrification is the conversion of the nitrogen in organic compounds to nitrates or nitrites.");
			
				p.addAnswer(3, "Mineralization",
				false,
				"Mineralization is the conversion of the nitrogen in organic compounds to ammonium.");
			
				p.addAnswer(4, "Nitrogen fixation",
				true,
				"Nitrogen fixation is the conversion of nitrogen gas to a form that can be used by plants (and other organisms).");
			
				p.addAnswer(5, "Assimilation",
				false,
				"Assimilation is the uptake of nutrients into an organism.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337108;


		
		

		
			
			p.question = "Which of these are the two major sources of nitrate pollution in rivers? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?54&E','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Water Pollution from Nitrates</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the burning of fossil fuels by factories and cars",
				false,
				"While these are sources of nitrate pollution, they are not the two major sources.");
			
				p.addAnswer(2, "animal wastes and the burning of fossil fuels by cars",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(3, "animal wastes and fertilizers",
				true,
				"According to an EPA study, animal wastes and fertilizer runoff are the two major sources of nitrate pollution.");
			
				p.addAnswer(4, "fertilizer runoff and the burning of fossil fuels by cars",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(5, "animal wastes and the burning of fossil fuels by factories",
				false,
				"This choice is partially correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337109;


		
		

		
			
			p.question = "Aquatic nitrate pollution can result in _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?54&E','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Water Pollution from Nitrates</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "algal bloom",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(2, "oxygen depletion",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(3, "fish kills",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(4, "hypoxia",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(5, "an algal bloom that, when the algae die and are decomposed by bacteria, leads to hypoxia and the death of fish",
				true,
				"This describes some of the consequences of aquatic nitrate pollution.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337110;


		
		

		
			
			p.question = "Which of these would NOT contribute to a global increase in temperature? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?54&F','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Greenhouse Effect</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "deforestation",
				false,
				"Trees remove more carbon dioxide from the atmosphere than they release into the atmosphere. Furthermore, dead trees decompose, releasing carbon dioxide into the atmosphere. Therefore, deforestation would result in an increase in atmospheric carbon dioxide, which would increase the greenhouse effect and WOULD INCREASE the global temperature.");
			
				p.addAnswer(2, "increasing the use of gasoline-burning vehicles",
				false,
				"Gasoline in a derived from oil, a fossil fuel. The burning fossil fuels release carbon dioxide into the atmosphere. The increase in atmospheric carbon dioxide would increase the greenhouse effect and thus WOULD INCREASE global temperature.");
			
				p.addAnswer(3, "increasing the industrial release of carbon dioxide",
				false,
				"Increased atmospheric carbon dioxide would increase the greenhouse effect and thus WOULD INCREASE global temperature.");
			
				p.addAnswer(4, "planting trees",
				true,
				"Trees remove more carbon dioxide from the atmosphere than they release into the atmosphere. By removing carbon dioxide, they reduce the greenhouse effect and this would contribute to a reduction in global temperature.");
			
				p.addAnswer(5, "increasing the amount of animal life on Earth",
				false,
				"This would increase the amount of cellular respiration taking place, which means that more carbon dioxide would be released into the atmosphere. Increased atmospheric carbon dioxide would increase the greenhouse effect and thus WOULD INCREASE global temperature.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337111;


		
		

		
			
			p.question = "Switching from fossil fuels to _____ energy would significantly decrease the release of carbon dioxide into the atmosphere. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?54&F','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Greenhouse Effect</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "solar",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(2, "nuclear",
				false,
				"While the use of nuclear energy would decrease the release of carbon dioxide into the atmosphere, its use is associated with other problems.");
			
				p.addAnswer(3, "geothermal",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(4, "solar and geothermal",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(5, "solar, nuclear, and geothermal",
				true,
				"All of these energy sources would decrease the release of carbon dioxide into the atmosphere. However, the use of nuclear reactors is associated with other problems.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

