

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "7: Membrane Structure and Function > Practice Test";
	ak.quiz_loc_with_commas = "7: Membrane Structure and Function, Practice Test";
	ak.quiz_title = "Practice Test";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 37;
	ak.non_essay_total = 37;
	ak.scored_item_total = 37;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334408;


		
		

		
			
			p.question = "Which one of the following cell structures exhibits selective permeability between a cell and its external environment? (<script type=\"text/javascript\">ebook(\'07OV\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the plasma membrane",
				true,
				"Correct. The plasma membrane allows some substances to cross into a cell more easily than others.");
			
				p.addAnswer(2, "mitochondria",
				false,
				"No. Although mitochondria have membranes, their membranes do not form the surface of a cell.");
			
				p.addAnswer(3, "chloroplasts",
				false,
				"No. Although chloroplasts have membranes, their membranes do not form the surface of a cell.");
			
				p.addAnswer(4, "endoplasmic reticulum",
				false,
				"No. Although the endoplasmic reticulum has membranes, its membranes do not form the surface of a cell.");
			
				p.addAnswer(5, "lysosomes",
				false,
				"No. Although lysosomes have membranes, their membranes do not form the surface of a cell.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334409;


		
		

		
			
			p.question = "Which of the following statements about the role of phospholipids in forming membranes is correct? (<script type=\"text/javascript\">ebook(\'0701\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Phospholipids are completely insoluble in water.",
				false,
				"No. Phospholipids have a polar, hydrophilic head and a nonpolar, hydrophobic tail.");
			
				p.addAnswer(2, "Phospholipids form a single sheet in water.",
				false,
				"No. In water, phospholipids form a two-layered bilayer structure.");
			
				p.addAnswer(3, "Phospholipids form a structure in which the hydrophobic portion faces outward.",
				false,
				"No. In water, the hydrophilic heads face outward and the hydrophobic tails meet inside the bilayer.");
			
				p.addAnswer(4, "Phospholipids form a selectively permeable structure.",
				true,
				"Correct. Their structure allows some substances to penetrate easily and blocks others.");
			
				p.addAnswer(5, "They are triacylglycerols, which are commonly available in foods.",
				false,
				"No. Phospholipids are diglycerides, with two fatty acids attached to glycerol. Triacylglycerols (fats and oils) have three fatty acids attached to glycerol.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334410;


		
		

		
			
			p.question = "The plasma membrane is referred to as a \"fluid mosaic\" structure. Which of the following statements about that model is true? (<script type=\"text/javascript\">ebook(\'0701\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The fluid component of the membrane is composed of phospholipids, and the mosaic part is composed of carbohydrates.",
				false,
				"No. The fluid is phospholipid, but the mosaic is not carbohydrate.");
			
				p.addAnswer(2, "The fluid aspect of the membrane describes its structure at normal temperatures, and the mosaic aspect describes the membrane as the temperature is lowered.",
				false,
				"No. The fluid mosaic model describes membrane structure at normal temperatures where some components are more fluid and some are less fluid and form mosaic structures.");
			
				p.addAnswer(3, "The mosaic comprises the carbohydrate chains on the inner surface of the membrane.",
				false,
				"No. The carbohydrate chains are on the outer surface of the membrane and are not the reason that the plasma membrane is referred to as fluid mosaic.");
			
				p.addAnswer(4, "The fluid component of the membrane is phospholipid, and the mosaic is protein.",
				true,
				"Correct. This is what the term \"fluid mosaic\" refers to.");
			
				p.addAnswer(5, "Only phospholipids are capable of moving in the membrane.",
				false,
				"No. Proteins can also move in the membrane, but they are far less mobile than phospholipids.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334411;


		
		

		
			
			p.question = "Which of the following types of information is (are) most likely to be derived from freeze-fracture of biological samples? (<script type=\"text/javascript\">ebook(\'0701\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the coded information in DNA",
				false,
				"No. A freeze-fracture does not sequence DNA nucleotides.");
			
				p.addAnswer(2, "thin sections (slices) of fixed and embedded cells",
				false,
				"No. Freeze-fracture does not produce thin sections of cells.");
			
				p.addAnswer(3, "proteins embedded in membrane bilayers",
				true,
				"Correct. The freeze-fracture method proved to be a particularly useful technique for revealing integral membrane proteins, as this procedure can separate a membrane along the middle of the phospholipid bilayer.");
			
				p.addAnswer(4, "patterns of movement in living cells",
				false,
				"No. A freeze-fractured cell is dead.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334412;


		
		

		
			
			p.question = "Consider the currently accepted fluid mosaic model of the plasma membrane. Where in the plasma membrane would cholesterol most likely be found? (<script type=\"text/javascript\">ebook(\'0701\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "on the outside (external) surface of the membrane",
				false,
				"No. The outside surface of the plasma membrane is associated with an aqueous solution.");
			
				p.addAnswer(2, "in the interior of the membrane",
				true,
				"Correct. The steroid cholesterol, wedged between phospholipid molecules in the plasma membranes of animals, helps stabilize the membrane.");
			
				p.addAnswer(3, "on the inside (cytoplasmic) surface",
				false,
				"No. The inside surface of the plasma membrane is associated with an aqueous solution.");
			
				p.addAnswer(4, "in the interior and on the inside surface, but not on the outside surface",
				false,
				"No. The inside surface of the plasma membrane is associated with an aqueous solution.");
			
				p.addAnswer(5, "on either surface of the membrane, but not in the interior of the membrane",
				false,
				"No. Cholesterol is hydrophobic and will be found in the interior of the bilayer membrane.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334413;


		
		

		
			
			p.question = "Which of the following functional processes result(s) from the presence of proteins in or on the plasma membrane? (<script type=\"text/javascript\">ebook(\'0701\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "enzymatic activity",
				false,
				"No. This choice is correct, but there is a better response.");
			
				p.addAnswer(2, "cell-cell recognition",
				false,
				"No. This choice is correct, but there is a better response.");
			
				p.addAnswer(3, "intercellular joining",
				false,
				"No. This choice is correct, but there is a better response.");
			
				p.addAnswer(4, "cell-cell communication",
				false,
				"No. This choice is correct, but there is a better response.");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct. In addition to the functions mentioned above, proteins also participate in transport and cytoskeletal attachment.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334414;


		
		

		
			
			p.question = "Which of the following is/are a function of membrane proteins? (<script type=\"text/javascript\">ebook(\'0701\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Membrane proteins attach the membrane to the cytoskeleton.",
				false,
				"No. This choice is correct, but there is a better response.");
			
				p.addAnswer(2, "Membrane proteins provide receptors for chemical messengers.",
				false,
				"No. This choice is correct, but there is a better response.");
			
				p.addAnswer(3, "Membrane proteins form channels, which move substances across the membrane.",
				false,
				"No. This choice is correct, but there is a better response.");
			
				p.addAnswer(4, "Membrane proteins with short sugar chains form identification tags that are recognized by other cells.",
				false,
				"No. This choice is correct, but there is a better response.");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct. Different proteins in membranes accomplish all of the above activities.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334415;


		
		

		
			
			p.question = "Which one of the following statement concerning carbohydrates associated with the plasma membrane is correct? (<script type=\"text/javascript\">ebook(\'0701\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Carbohydrates are only found associated with the membranes of prokaryotic cells.",
				false,
				"No. Although carbohydrate is an important component of bacterial cell walls, carbohydrate is also found in the membranes of eukaryotic cells.");
			
				p.addAnswer(2, "The carbohydrate composition of most eukaryotic plasma membranes is quite similar.",
				false,
				"No. Variation in carbohydrate composition of the plasma membrane is critical in cellular recognition.");
			
				p.addAnswer(3, "Carbohydrates on the plasma membrane are typically short chains of 2&ndash;5 monosaccharides.",
				false,
				"No. The carbohydrates on cell surfaces are generally branched chains of fewer than 15 sugars.");
			
				p.addAnswer(4, "Membrane carbohydrates function primarily in cell-cell recognition.",
				true,
				"Correct. Variations in carbohydrate structure distinguish one species from another, one individual from another, and even one cell type from another.");
			
				p.addAnswer(5, "Carbohydrates associated with the plasma membrane are located on both surfaces of the membrane.",
				false,
				"No. The primary location of carbohydrates is on the outer surface of the plasma membrane where they can contribute to cell-cell recognition.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334416;


		
		

		
			
			p.question = "Consider the currently accepted fluid mosaic model of the plasma membrane. Where in the membrane would carbohydrates most likely be found? (<script type=\"text/javascript\">ebook(\'0701\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "on the outside (external) surface of the membrane",
				true,
				"Correct. Membrane carbohydrates are covalently bonded to lipids or proteins and extend out from the external side of the plasma membrane as a means of cell identification.");
			
				p.addAnswer(2, "in the interior of the membrane",
				false,
				"No. The interior of the plasma membrane is hydrophobic.");
			
				p.addAnswer(3, "on the inside (cytoplasmic) surface of the membrane",
				false,
				"No. Although this surface is hydrophilic, carbohydrates<b> </b>are not attached here.");
			
				p.addAnswer(4, "on both hydrophilic surfaces of the membrane but not in the hydrophobic interior",
				false,
				"No. Carbohydrates<b> </b>are found on the external surface of the plasma membrane as a means of identifying cell types.");
			
				p.addAnswer(5, "Carbohydrates<b> </b>are rarely associated with plasma membranes.",
				false,
				"No. Carbohydrates<b> </b>are almost always associated with the outer surfaces of the plasma membrane as a means of cell identification.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334417;


		
		

		
			
			p.question = "Which statement(s) about the sidedness of the plasma membrane is (are) correct? (<script type=\"text/javascript\">ebook(\'0701\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Parts of proteins that are exposed on the cytoplasmic side of the endoplasmic reticulum are also exposed on the cytoplasmic side of the plasma membrane.",
				false,
				"No. This choice is correct, but there is a better response.");
			
				p.addAnswer(2, "The asymmetrical distribution of membrane proteins, lipids, and carbohydrates across the plasma membrane is determined as the membrane is being constructed.",
				false,
				"No. This choice is correct, but there is a better response.");
			
				p.addAnswer(3, "Every integral membrane protein has a specific orientation in the plasma membrane.",
				false,
				"No. This choice is correct, but there is a better response.");
			
				p.addAnswer(4, "The two lipid layers may differ in specific lipid composition.",
				false,
				"No. This choice is correct, but there is a better response.");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct. All of the above are aspects of the sidedness of the plasma membrane.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334418;


		
		

		
			
			p.question = "Which one of the following molecules is most likely to diffuse freely across the lipid bilayer of the plasma membrane without the involvement of a transport protein? (<script type=\"text/javascript\">ebook(\'0702\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "carbon dioxide",
				true,
				"Correct. Hydrophobic molecules, such as hydrocarbons, carbon dioxide, and oxygen, can dissolve in the membrane and cross it with ease.");
			
				p.addAnswer(2, "glucose",
				false,
				"No. Glucose is a polar molecule that is much larger than water&mdash;it requires a transport protein to cross a membrane.");
			
				p.addAnswer(3, "sodium ion",
				false,
				"No. Sodium has a positive charge and cannot cross a membrane without a transport protein.");
			
				p.addAnswer(4, "DNA",
				false,
				"No. DNA is a large molecule and cannot cross a membrane under normal circumstances.");
			
				p.addAnswer(5, "hemoglobin",
				false,
				"No. Hemoglobin is a large protein molecule and does not cross membranes under normal circumstances.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334419;


		
		

		
			
			p.question = "Which of the following would be <b>least</b> likely to diffuse through a plasma membrane without the help of a transport protein? (<script type=\"text/javascript\">ebook(\'0702\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a large polar molecule",
				true,
				"Correct. Large polar substances cannot dissolve in the hydrophobic component of the membrane and are too large to avoid the region.");
			
				p.addAnswer(2, "a large nonpolar molecule",
				false,
				"No. Nonpolar molecules often avoid the hydrophilic phospholipid heads and dissolve through the hydrophobic regions.");
			
				p.addAnswer(3, "dissolved gases such as oxygen or carbon dioxide",
				false,
				"No. Dissolved gases like oxygen and carbon dioxide can cross membranes with ease.");
			
				p.addAnswer(4, "a small nonpolar molecule",
				false,
				"No. Small nonpolar molecules, particularly water, can cross the bilayer membrane.");
			
				p.addAnswer(5, "Any of the above would easily diffuse through the membrane.",
				false,
				"No. There is definitely a category of molecule in the choices above that cannot easily diffuse across a membrane.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334420;


		
		

		
			
			p.question = "Which of the following structures is most consistent with the selective permeability property of biological membranes? (<script type=\"text/javascript\">ebook(\'0702\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "proteins sandwiched between two layers of phospholipid",
				false,
				"No. This type of structure would not permit polar solutes to cross the membrane.");
			
				p.addAnswer(2, "proteins embedded in two layers of phospholipid",
				true,
				"Correct. With the proteins embedded, the cell retains its general restriction for polar molecules crossing the membrane, while the proteins provide for selective transport functions.");
			
				p.addAnswer(3, "a layer of protein coating a layer of phospholipid",
				false,
				"No. This type of structure would prevent almost all polar molecules from crossing the membrane.");
			
				p.addAnswer(4, "phospholipids sandwiched between two layers of protein",
				false,
				"No. This type of structure would prevent almost all polar molecules from entering the cell.");
			
				p.addAnswer(5, "a phospholipid bilayer with proteins scattered on the surfaces of the membranes",
				false,
				"No. This type of structure would not permit polar solutes to cross the membrane.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334421;


		
		

		
			
			p.question = "Which of the following statements about passive transport is correct? (<script type=\"text/javascript\">ebook(\'0703\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Passive transport operates independently of diffusion.",
				false,
				"No. Passive transport is the diffusion of a substance across a biological membrane.");
			
				p.addAnswer(2, "Passive transport operates independently of the concentrations of the substance being transported.",
				false,
				"No. Passive transport must occur down a concentration gradient.");
			
				p.addAnswer(3, "In passive transport, all movement of the transported molecule stops when its concentration is the same on both sides of the membrane.",
				false,
				"No. When the concentration is the same on both sides of the membrane, passive transport continues, but the rate of transport is the same in both directions.");
			
				p.addAnswer(4, "Passive transport does not occur in the human body.",
				false,
				"No. Many substances such as oxygen, water, and carbon dioxide cross membranes by passive transport.");
			
				p.addAnswer(5, "Passive transport permits the transported molecule to move in either direction, but the majority of transport occurs down the concentration gradient of the molecule.",
				true,
				"Correct. Passive transport can occur in either direction, but the direction of net diffusion is down the concentration gradient of the transported molecule.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334422;


		
		

		
			
			p.question = "Cells A and B are the same size, shape, and temperature, but cell A is metabolically quiet and cell B is actively consuming oxygen. Oxygen will diffuse more quickly into cell _____ because _____. (<script type=\"text/javascript\">ebook(\'0703\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A; the diffusion gradient there is shallower",
				false,
				"No. Cell A is using less oxygen and thus will have a smaller difference in oxygen between the inside and outside of the cell compared to cell B.");
			
				p.addAnswer(2, "A; its membrane transport proteins will not be saturated",
				false,
				"No. The diffusion of oxygen does not require membrane transport proteins.");
			
				p.addAnswer(3, "B; the diffusion gradient in cell B is steeper",
				true,
				"Correct. As long as a metabolically active cell consumes oxygen as it enters, diffusion into the cell will continue because the concentration gradient favors movement in that direction.");
			
				p.addAnswer(4, "B; the oxygen molecules inside cell B have a higher kinetic energy",
				false,
				"No. Higher kinetic energy will make diffusion occur faster, but the higher metabolic rate in cell B does not give the oxygen higher kinetic energy.");
			
				p.addAnswer(5, "B; the gradient of oxygen is oriented in the opposite direction compared to cell A",
				false,
				"No. Oxygen is being consumed in both cells so that the gradient is from outside to inside in both cells.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334423;


		
		

		
			
			p.question = "Which one of the following statements about diffusion is true? (<script type=\"text/javascript\">ebook(\'0703\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "It is very rapid over long distances.",
				false,
				"No. Diffusion occurs slowly over long distances.");
			
				p.addAnswer(2, "It requires expenditure of energy by the cell.",
				false,
				"No. By definition, diffusion does not require the cell to expend energy.");
			
				p.addAnswer(3, "It is a passive process.",
				true,
				"Correct. Diffusion is the tendency of molecules to spread out in the available space. A substance will diffuse from an area of higher concentration to an area of lower concentration without energy input.");
			
				p.addAnswer(4, "It occurs when molecules move from a region of lower concentration to a region of higher concentration.",
				false,
				"No. This would require the cell to expend energy.");
			
				p.addAnswer(5, "It always requires integral proteins of the cell membrane.",
				false,
				"No. Facilitated diffusion requires integral proteins, but passive diffusion does not.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334424;


		
		

		
			
			p.question = "The internal solute concentration of a plant cell is about 0.8 <i>M</i>. To demonstrate plasmolysis, it would be necessary to suspend the cell in what solution? (<script type=\"text/javascript\">ebook(\'0703\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "distilled water",
				false,
				"No. Distilled water is hypotonic to the plant; thus, water will enter the plant cell and make the cell more turgid.");
			
				p.addAnswer(2, "0.4 <i>M</i>",
				false,
				"No. 0.4 <i>M</i> is still hypotonic to the plant cell. Water will enter osmotically and make the cell more turgid.");
			
				p.addAnswer(3, "0.8 <i>M</i>",
				false,
				"No. 0.8 <i>M</i> is isotonic to the plant cell. The cell will become flaccid.");
			
				p.addAnswer(4, "1.0 <i>M</i>",
				true,
				"Correct. 1.0 <i>M</i> is hypertonic to the plant cell. Water will leave the cell, and eventually the plasma membrane will pull away from the cell wall, resulting in plasmolysis.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334425;


		
		

		
			
			p.question = "A single plant cell is placed in an isotonic solution. Salt is then added to the solution. Which of the following would occur as a result of the salt addition? (<script type=\"text/javascript\">ebook(\'0703\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The added salt would enter the cell, causing the cell to take up water and swell.",
				false,
				"No. The permeability of the plasma membrane is greater to water than salt. Water will cross the membrane before salt does.");
			
				p.addAnswer(2, "Water would enter the cell by osmosis, and the cell would swell.",
				false,
				"No. The added salt makes the solution hypertonic compared to the cell. Water will leave the cell by osmosis.");
			
				p.addAnswer(3, "Water would leave the cell by osmosis, causing the volume of the cytoplasm to decrease.",
				true,
				"Correct. The added salt makes the solution hypertonic compared to the cell. Water will leave the cell by osmosis.");
			
				p.addAnswer(4, "There would be no osmotic movement of water in response to the added salt.",
				false,
				"No. The added salt makes the solution hypertonic compared to the cell. Water will leave the cell by osmosis.");
			
				p.addAnswer(5, "The added salt makes the solution hypotonic compared to the cell. Water will enter the cell by osmosis.",
				false,
				"No. The added salt makes the solution hypertonic compared to the cell. Water will leave the cell by osmosis.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334426;


		
		

		
			
			p.question = "If a red blood cell and a plant cell were placed in seawater, what would happen to the two types of cells? (<script type=\"text/javascript\">ebook(\'0703\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The red blood cell would burst, and the plant cell would shrink.",
				false,
				"No. Seawater is hypertonic to both cells. Both cells would lose water by osmosis.");
			
				p.addAnswer(2, "Both cells would lose water; the red blood cell would shrivel, and the plant plasma membrane would pull away from the cell wall.",
				true,
				"Correct. Seawater is hypertonic to both cells and will cause the cells to lose water.");
			
				p.addAnswer(3, "Seawater is isotonic to both cells. There will be no change in water content of the cells.",
				false,
				"No. Seawater is hypertonic to both cells, not isotonic.");
			
				p.addAnswer(4, "Both cells would gain water by osmosis; the red blood cell would burst, and the plant cell would increase in turgor pressure.",
				false,
				"No. Seawater is hypertonic to both cells. Both cells would lose water by osmosis.");
			
				p.addAnswer(5, "The red blood cell would shrink, and the plant cell would gain water.",
				false,
				"No. Seawater is hypertonic to both cells. Both cells would lose water by osmosis.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334427;


		
		

		
			
			p.question = "Which of these statements describes some aspect of facilitated diffusion? (<script type=\"text/javascript\">ebook(\'0703\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Facilitated diffusion is another name for osmosis.",
				false,
				"No. Osmosis is the movement of water across a membrane; facilitated diffusion moves a solute.");
			
				p.addAnswer(2, "Facilitated diffusion of solutes occurs through phospholipid pores in the membrane.",
				false,
				"No. Facilitated diffusion occurs through integral membrane transport proteins.");
			
				p.addAnswer(3, "Facilitated diffusion requires energy to drive a concentration gradient.",
				false,
				"No. Facilitated diffusion is driven by a concentration gradient, so it does not require energy.");
			
				p.addAnswer(4, "Facilitated diffusion of solutes may occur through protein pores in the membrane.",
				true,
				"Correct. The passageways for facilitated diffusion may be either protein pores or carrier proteins.");
			
				p.addAnswer(5, "There is only one kind of protein pore for facilitated diffusion.",
				false,
				"No. Each molecule or group of molecules requires its own specific pore.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334428;


		
		

		
			
			p.question = "Which of the following is (are) true about facilitated diffusion? (<script type=\"text/javascript\">ebook(\'0703\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Facilitated diffusion requires a concentration gradient.",
				false,
				"No. Although correct, there is a better choice.");
			
				p.addAnswer(2, "Facilitated diffusion requires a membrane.",
				false,
				"No. Although correct, there is a better choice.");
			
				p.addAnswer(3, "Facilitated diffusion involves proteins.",
				false,
				"No. Although correct, there is a better choice.");
			
				p.addAnswer(4, "Facilitated diffusion does not involve an outside energy source.",
				false,
				"No. Although correct, there is a better choice.");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct. All of the statements are true.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334429;


		
		

		
			
			p.question = "Imagine two solutions separated by a selectively permeable membrane that allows water to pass, but not sucrose or glucose. The membrane separates a 0.2-molar sucrose solution from a 0.2-molar glucose solution. With time, how will the solutions change? (<script type=\"text/javascript\">ebook(\'0703\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Nothing happens because the two solutions are isotonic to one another.",
				true,
				"Correct. Osmotic pressure is produced by the quantity of dissolved substances. The individual size of the molecule does not affect osmotic pressure.");
			
				p.addAnswer(2, "Water enters the sucrose solution because the sucrose molecule is a disaccharide and thus larger than the monosaccharide glucose.",
				false,
				"No. The individual size of the molecule does not affect osmotic pressure.");
			
				p.addAnswer(3, "Water leaves the sucrose solution because the sucrose molecule is a disaccharide and thus larger than the monosaccharide glucose.",
				false,
				"No. The individual size of the molecule does not affect osmotic pressure.");
			
				p.addAnswer(4, "The sucrose solution is hypertonic and will gain water because the total mass of sucrose is greater than that of glucose.",
				false,
				"No. The mass of the molecule does not affect osmotic pressure. Each solution has the same number of particles, so they are isotonic.");
			
				p.addAnswer(5, "After the sucrose dissociates to two monosaccharides, water will be osmotically drawn to that side of the membrane.",
				false,
				"No. Disaccharides do not dissociate spontaneously.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334430;


		
		

		
			
			p.question = "The concentration of solutes in a red blood cell is about 2%, but red blood cells contain almost no sucrose or urea. Sucrose cannot pass through the membrane, but water and urea can. Osmosis would cause red blood cells to shrink the most when immersed in which of the following solutions? (<script type=\"text/javascript\">ebook(\'0703\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a hypertonic sucrose solution",
				true,
				"Correct. When a cell is placed in a hypertonic environment, water will leave the cell, causing it to shrink.");
			
				p.addAnswer(2, "a hypotonic sucrose solution",
				false,
				"No. If the cell were in a hypotonic solution, you would expect water to enter the cell.");
			
				p.addAnswer(3, "a hypertonic urea solution",
				false,
				"No. If the membrane is permeable to urea, then urea will simply diffuse through the membrane until it reaches equilibrium. This increases the solute concentration inside the cell relative to outside, and water will enter osmotically.");
			
				p.addAnswer(4, "a hypotonic urea solution",
				false,
				"No. If the outside of the cell were hypotonic, you would expect water to enter the cell. Furthermore, if the membrane is permeable to urea, then urea will quickly diffuse through the membrane, causing more water to enter the cell.");
			
				p.addAnswer(5, "pure water",
				false,
				"No. Pure water is the most hypotonic environment possible. Water will enter any cell placed in a hypotonic solution.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334431;


		
		

		
			
			p.question = "Green olives may be preserved in brine, which is a 30% salt solution. How does this method of preservation prevent contamination by microorganisms? (<script type=\"text/javascript\">ebook(\'0703\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Bacterial cells shrivel up in high salt solutions, causing the cell to burst.",
				false,
				"No. A shriveled cell does not burst.");
			
				p.addAnswer(2, "High salt concentration lowers the pH, thus inhibiting bacterial metabolism.",
				false,
				"No. High salt concentration does not directly affect the pH of a solution.");
			
				p.addAnswer(3, "High salt concentration raises the pH, thus inhibiting bacterial metabolism.",
				false,
				"No. High salt concentration does not directly affect the pH of a solution.");
			
				p.addAnswer(4, "A 30% salt solution is hypotonic to the bacteria, so they gain too much water and burst.",
				false,
				"No. 20&ndash;30% is a rather high concentration of salt.");
			
				p.addAnswer(5, "A 30% salt solution is hypertonic to the bacteria, so they lose too much water and cannot survive.",
				true,
				"Correct. If a cell is placed in a hypertonic solution, it will lose water to its environment, shrivel, and probably die.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334432;


		
		

		
			
			p.question = "Active transport requires a cell to expend energy. Which of the following statements is true? (<script type=\"text/javascript\">ebook(\'0704\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Active transport often involves an ATP-powered ion pump and a cotransport protein.",
				false,
				"No. Although this is true, there is a better choice.");
			
				p.addAnswer(2, "Active transport usually uses ATP as its energy source.",
				false,
				"No. Although this is true, there is a better choice.");
			
				p.addAnswer(3, "Active transport moves solutes against the concentration gradient.",
				false,
				"No. Although this is true, there is a better choice.");
			
				p.addAnswer(4, "Active transport requires a protein carrier.",
				false,
				"No. Although this is true, there is a better choice.");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct. All of the statements are true.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334433;


		
		

		
			
			p.question = "Glucose is a six-carbon sugar that diffuses slowly through artificial membranes. The cells lining the small intestine, however, rapidly move glucose from the gut into their cytoplasm. This occurs whether the gut concentrations of glucose are higher or lower than the glucose concentrations in intestinal cell cytoplasm. Using this information, which transport mechanism is most likely responsible for the glucose transport in intestinal cells? (<script type=\"text/javascript\">ebook(\'0704\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "simple diffusion",
				false,
				"No. Any type of diffusion only occurs from an area of higher concentration to an area of lower concentration.");
			
				p.addAnswer(2, "phagocytosis",
				false,
				"No. Glucose is a solute. Phagocytosis takes up large insoluble particles.");
			
				p.addAnswer(3, "active transport",
				true,
				"Correct. Some transport proteins can move molecules against their concentration gradients in a process called active transport.");
			
				p.addAnswer(4, "exocytosis",
				false,
				"No. This would move glucose out of the cells.");
			
				p.addAnswer(5, "facilitated diffusion",
				false,
				"No. Any type of diffusion can only be movement from an area of higher concentration to an area of lower concentration.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334434;


		
		

		
			
			p.question = "Which of the following is a correct difference between active transport and facilitated diffusion? (<script type=\"text/javascript\">ebook(\'0704\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Active transport involves transport proteins, and facilitated diffusion does not.",
				false,
				"No. Active transport and facilitated diffusion both use transport proteins.");
			
				p.addAnswer(2, "Facilitated diffusion can move solutes against a concentration gradient, and active transport cannot.",
				false,
				"No. The reverse is true. Active transport can move solutes against a concentration gradient, and facilitated diffusion cannot.");
			
				p.addAnswer(3, "Active transport can move solutes in either direction across a membrane, but facilitated diffusion can only move in one direction.",
				false,
				"No. It is just the opposite. Facilitated diffusion can go in either direction depending on the direction of the concentration gradient. In active transport, the direction of transport is fixed by the properties of the proteins involved.");
			
				p.addAnswer(4, "Facilitated diffusion involves transport proteins, and active transport does not.",
				false,
				"No. Both systems depend on specific membrane transport proteins.");
			
				p.addAnswer(5, "Active transport requires energy from ATP, and facilitated diffusion does not.",
				true,
				"Correct. Active transport can move substances against the concentration gradient, but it requires energy in the form of ATP.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334435;


		
		

		
			
			p.question = "Which one of the following statements about the sodium-potassium pump is correct? (<script type=\"text/javascript\">ebook(\'0704\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The sodium-potassium pump transports Na<sup>+</sup> and K<sup>+</sup> ions across the plasma membrane in the same direction at the expense of ATP hydrolysis.",
				false,
				"No. The sodium-potassium pump transports Na<sup>+</sup> and K<sup>+</sup> ions across the plasma membrane in opposite directions at the expense of ATP hydrolysis.");
			
				p.addAnswer(2, "The sodium-potassium pump creates a hydrogen gradient.",
				false,
				"No. The sodium-potassium pump creates an electrochemical gradient.");
			
				p.addAnswer(3, "The sodium-potassium pump is electrogenic.",
				true,
				"Correct. This is a true statement. An electrogenic pump creates a net movement of charge across a membrane. The sodium-potassium pump moves three Na<sup>+</sup> out and two K<sup>+</sup> in for a net transport of one positive charge out of the cell.");
			
				p.addAnswer(4, "The sodium-potassium pump causes a pH gradient across the plasma membrane.",
				false,
				"No. The sodium-potassium pump does not transport protons, and therefore does not influence the pH gradient.");
			
				p.addAnswer(5, "The sodium-potassium pump creates concentration gradients of O<sup>+</sup> and Cl<sup>-</sup> across the plasma membrane.",
				false,
				"No. The sodium-potassium pump creates concentration gradients of both Na<sup>+</sup> and K<sup>+</sup> across the plasma membrane.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334436;


		
		

		
			
			p.question = "A cell has a membrane potential of -100 mV (more negative inside than outside) and has 1,000 times more calcium ions outside the cell than inside. Which of the following best describes a mechanism by which Ca<sup>2+</sup> enters the cell? (<script type=\"text/javascript\">ebook(\'0704\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "movement of Ca<sup>2+</sup> into the cell through an ion channel down its concentration gradient",
				false,
				"No. A channel protein will permit facilitated diffusion of Ca<sup>2+</sup>, but the chemical (concentration) gradient is not the only thing contributing to the movement of Ca<sup>2+</sup>.");
			
				p.addAnswer(2, "passive diffusion of Ca<sup>2+</sup> into the cell down its electrochemical gradient",
				false,
				"No. Ca<sup>2+</sup> ions cannot cross a membrane by passive diffusion&mdash;it requires a transport protein (channel or carrier).");
			
				p.addAnswer(3, "cotransport of Ca<sup>2+</sup> into the cell with Cl<sup>-</sup> ions",
				false,
				"No. This would not be a good way to get Ca<sup>2+</sup> into the cell because it would be coupled to movement of Cl<sup>-</sup> <b>against</b> the electrical gradient.");
			
				p.addAnswer(4, "movement of Ca<sup>2+</sup> into the cell through a carrier protein down its electrical gradient",
				false,
				"No. A carrier protein will permit facilitated diffusion of Ca<sup>2+</sup>, but the electrical gradient is not the only thing contributing to the movement of Ca<sup>2+</sup>.");
			
				p.addAnswer(5, "facilitated diffusion of Ca<sup>2+</sup> into the cell down its electrochemical gradient",
				true,
				"Correct. Both the electrical and chemical (concentration) gradients contribute the energy to move Ca<sup>2+</sup> into the cells by facilitated diffusion as long as there is a channel or carrier that is specific for Ca<sup>2+</sup>.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334437;


		
		

		
			
			p.question = "Which of the following correctly describes a general property of all electrogenic pumps? (<script type=\"text/javascript\">ebook(\'0704\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "pumps sodium out of the cell and potassium into the cell",
				false,
				"No. This describes the electrogenic pump in animal cells, but the electrogenic pump in plants, fungi, and bacteria pumps protons out of the cell.");
			
				p.addAnswer(2, "creates a voltage difference across the membrane",
				true,
				"Correct. An electrogenic pump creates a net charge difference across a membrane (a membrane potential).");
			
				p.addAnswer(3, "can pump a large variety of solutes across a membrane against their concentration gradient",
				false,
				"No. Electrogenic pumps are limited to a few solutes, primarily protons in plants, bacteria, and fungi, and sodium/potassium in animal cells.");
			
				p.addAnswer(4, "a cell with an interior that is positively charged relative to the outside of the cell",
				false,
				"No. In cells, the membrane potential that develops is always negative on the inside, positive on the outside.");
			
				p.addAnswer(5, "a cell with a high internal concentration of protons",
				false,
				"No. Proton pumps, the electrogenic pump found in plants, fungi, and bacteria, move protons out of the cell.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334438;


		
		

		
			
			p.question = "Which of the following statements about cotransport of solutes across a membrane is correct? (<script type=\"text/javascript\">ebook(\'0704\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Cotransport involves the hydrolysis of ATP by the transporting protein.",
				false,
				"No. Cotransport proteins do not hydrolyze ATP; rather, they use the energy of gradients created by the ATP-dependent pumps.");
			
				p.addAnswer(2, "A cotransport protein is most commonly an ion channel.",
				false,
				"No. Cotransport proteins are always carrier proteins.");
			
				p.addAnswer(3, "Cotransport proteins allow a single ATP-powered pump to drive the active transport of many different solutes.",
				true,
				"Correct. The electrochemical gradient created by a single ATP-dependent pump can drive the transport of many different solutes using cotransport proteins.");
			
				p.addAnswer(4, "The sodium-potassium pump is an example of a cotransport protein.",
				false,
				"No. The sodium-potassium pump is an example of an ATP-dependent ion pump, not a cotransport protein.");
			
				p.addAnswer(5, "In cotransport, both solutes that are being transported are moving down their chemical gradients.",
				false,
				"No. In cotransport, one solute is moving down its electrochemical gradient and this energy is used to move the second solute against its electrochemical gradient.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334439;


		
		

		
			
			p.question = "Consider the transport of protons and sucrose into a plant cell by the sucrose-proton cotransport protein. Plant cells continuously produce a proton gradient by using the energy of ATP hydrolysis to pump protons out of the cell. Why, in the absence of sucrose, don\'t protons move back into the cell through the sucrose-proton cotransport protein? (<script type=\"text/javascript\">ebook(\'0704\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Protons cannot move through membrane transport proteins.",
				false,
				"No. The movement of protons down their electrochemical gradient through cotransport proteins is the energy that drives active transport of most solutes in plants and bacteria.");
			
				p.addAnswer(2, "Protons are freely permeable through the phospholipid bilayer, so no transport protein is needed for protons.",
				false,
				"No. Protons are charged and do not move passively through phospholipid bilayers.");
			
				p.addAnswer(3, "The movement of protons through the cotransport protein cannot occur unless sucrose also moves at the same time.",
				true,
				"Correct. The obligate coupling of proton movement to sucrose movement prevents the energy of the proton gradient from being lost if sucrose is not present.");
			
				p.addAnswer(4, "In the absence of sucrose, the ATP-powered proton pump does not function, so there is no proton gradient.",
				false,
				"No. The ATP-dependent proton pump is always on in plant cells to power the active transport of many compounds.");
			
				p.addAnswer(5, "Protons, unlike other substances, do not diffuse down their concentration gradient.",
				false,
				"No. Diffusion of protons down their electrochemical gradient is the energy that powers all cotransport systems in plants and bacteria.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334440;


		
		

		
			
			p.question = "Which of the following enables a cell to pick up and concentrate a specific kind of molecule? (<script type=\"text/javascript\">ebook(\'0705\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "passive transport",
				false,
				"No. Passive transport allows molecules to move through the lipid bilayer and only down their concentration gradient.");
			
				p.addAnswer(2, "facilitated diffusion",
				false,
				"No. Facilitated diffusion provides low-resistance pathways for molecules to cross the membrane, but only allows molecules to move down their concentration gradient.");
			
				p.addAnswer(3, "osmosis",
				false,
				"No. Osmosis is a special case of passive or facilitated diffusion involving water.");
			
				p.addAnswer(4, "receptor-mediated endocytosis",
				true,
				"Correct. In receptor-mediated endocytosis, only a specific molecule, called a ligand, can bind to the receptor. Without receptor binding occurring first, endocytosis does not proceed.");
			
				p.addAnswer(5, "channel proteins",
				false,
				"No. Channels are one type of protein that permits facilitated diffusion. This method does not allow for concentrating molecules in the cell.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334441;


		
		

		
			
			p.question = "Which of the following processes, normally associated with membrane transport, must occur to account for an increase in the surface area of a cell? (<script type=\"text/javascript\">ebook(\'0705\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "endocytosis",
				false,
				"No. Endocytosis is a process that removes phospholipids from the plasma membrane by budding off of small vesicles.");
			
				p.addAnswer(2, "active transport",
				false,
				"No. Active transport is important in most cellular processes, but it does not add new phospholipids to the plasma membrane.");
			
				p.addAnswer(3, "receptor-mediated endocytosis",
				false,
				"No. Receptor-mediated endocytosis is a special form of endocytosis, but it still results in the loss of phospholipids from the plasma membrane.");
			
				p.addAnswer(4, "exocytosis",
				true,
				"Correct. In exocytosis, vesicles derived from the endomembrane system fuse with the plasma membrane, thus increasing the number of phospholipids in the plasma membrane and increasing its surface area.");
			
				p.addAnswer(5, "flip-flop of phospholipids from one side of the plasma membrane to the other",
				false,
				"No. Flip-flop of phospholipids between sides of a membrane normally does not occur, and could not increase the area of the membrane if it did occur.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334442;


		
		

		
			
			p.question = "A nursing infant is able to obtain disease-fighting antibodies, which are large protein molecules, from its mother\'s milk. These molecules probably enter the cells lining the baby\'s digestive tract via which process? (<script type=\"text/javascript\">ebook(\'0705\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "osmosis",
				false,
				"No. Osmosis is a special case of passive transport involving the movement of water across a membrane.");
			
				p.addAnswer(2, "passive transport",
				false,
				"No. Passive transport involves small molecules that require no special assistance in crossing the membrane.");
			
				p.addAnswer(3, "exocytosis",
				false,
				"No. Cells use exocytosis to move products out of the cell.");
			
				p.addAnswer(4, "active transport",
				false,
				"No. Active transport is used to move small molecules against the concentration gradient. In this case, antibody molecules are concentrated in the digestive tract, so movement into the cells would be along the gradient.");
			
				p.addAnswer(5, "endocytosis",
				true,
				"Correct. Endocytosis is the procedure that cells use to import large molecules across their plasma membrane.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334443;


		
		

		
			
			p.question = "The transmission of nerve impulses between adjacent nerve cells requires the release of a neurotransmitter (a molecule or small peptide) by exocytosis. Which of the following would best reverse the process that resulted in the release of neurotransmitter, returning the cell to its original state? (<script type=\"text/javascript\">ebook(\'0705\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "endocytosis",
				false,
				"No. Although it is true that endocytosis is likely to follow the release of neurotransmitter by endocytosis to maintain a constant plasma membrane area, there is a better answer.");
			
				p.addAnswer(2, "pinocytosis",
				false,
				"No. Although it is true that pinocytosis would also remove membrane added to the plasma membrane during the release of neurotransmitter, there is a better answer.");
			
				p.addAnswer(3, "active transport of the neurotransmitter back into the cell",
				false,
				"No. Although it is true that this process would allow the cell to recover its neurotransmitter for sending subsequent signals, it does not remove the added phospholipids from the plasma membrane.");
			
				p.addAnswer(4, "passive transport (by facilitated diffusion) of the neurotransmitter back into the cell",
				false,
				"No. Even if there was a transport protein for the neurotransmitter, passive transport could only equalize the concentration inside and outside the cell. This process could not remove the added phospholipids from the plasma membrane.");
			
				p.addAnswer(5, "receptor-mediated endocytosis",
				true,
				"Correct. This is the best answer because it accomplishes two tasks. It recovers the neurotransmitter back into vesicles in the cell (by specific binding to receptors), and it removes the phospholipids added to the plasma membrane when the transmitter was released.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334444;


		
		

		
			
			p.question = "Which one of the following pairs correctly matches a membrane transport process to its primary function? (<script type=\"text/javascript\">ebook(\'0705\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "phagocytosis; secretion of large particles from the cell by fusion of vesicles with the plasma membrane",
				false,
				"No. In phagocytosis (cellular eating), a type of endocytosis, a cell engulfs a particle by wrapping pseudopodia around it and packaging it within a membrane-enclosed sac large enough to be classified as a food vacuole.");
			
				p.addAnswer(2, "exocytosis; the movement of water and solutes out of the cell by vesicle fusion with the plasma membrane",
				false,
				"No. Exocytosis does move water and solutes out of the cell, but its primary function is moving larger, insoluble particles out of cells.");
			
				p.addAnswer(3, "pinocytosis; the uptake of water and small solutes into the cell by formation of vesicles at the plasma membrane.",
				true,
				"Correct. Pinocytosis is the uptake of liquid and the solutes dissolved in the liquid.");
			
				p.addAnswer(4, "osmosis; passive diffusion of water and small solutes across a membrane",
				false,
				"No. Osmosis is the diffusion of water across a membrane, but it does not include the diffusion of other solutes.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

