

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "32: An Introduction to Animal Diversity > Practice Test";
	ak.quiz_loc_with_commas = "32: An Introduction to Animal Diversity, Practice Test";
	ak.quiz_title = "Practice Test";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 25;
	ak.non_essay_total = 25;
	ak.scored_item_total = 25;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335898;


		
		

		
			
			p.question = "Which characteristic below is shared by plants, fungi, and animals? (<script type=\"text/javascript\">ebook(\'3201\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "They all have cell walls.",
				false,
				"No. Animals do not have cell walls.");
			
				p.addAnswer(2, "All are multicellular eukaryotes.",
				true,
				"Correct. All three groups are multicellular eukaryotes.");
			
				p.addAnswer(3, "All are held together by structural proteins.",
				false,
				"No. This is true of animals, which lack cell walls.");
			
				p.addAnswer(4, "All are autotrophs.",
				false,
				"No. Plants are autotrophs, but animals and fungi are heterotrophs.");
			
				p.addAnswer(5, "All release enzymes to the outside of the body to aid in digestion.",
				false,
				"No. This is generally true of fungi but not most animals and plants.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335899;


		
		

		
			
			p.question = "Animals probably evolved from colonial protists. How do animals differ from these protist ancestors? (<script type=\"text/javascript\">ebook(\'3201\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The protists were prokaryotic.",
				false,
				"No. Both animals and protists are eukaryotic.");
			
				p.addAnswer(2, "Animals have more specialized cells.",
				true,
				"Correct. Animals are multicellular and have many specialized cells.");
			
				p.addAnswer(3, "The protists were heterotrophic.",
				false,
				"No. Animals are heterotrophic as well.");
			
				p.addAnswer(4, "The protists were autotrophic.",
				false,
				"No. The protists from which animals evolved were heterotrophic.");
			
				p.addAnswer(5, "Animals are able to reproduce.",
				false,
				"No. Reproduction is one of the characteristics common to all life.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335900;


		
		

		
			
			p.question = "During the development of most animals, cleavage leads to _____. (<script type=\"text/javascript\">ebook(\'3201\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the formation of a zygote",
				false,
				"No. A zygote is formed during fertilization, and the zygote undergoes cleavage.");
			
				p.addAnswer(2, "a multicelled blastula",
				true,
				"Correct. The blastula is a multicellular stage, which in many animals takes the form of a hollow ball.");
			
				p.addAnswer(3, "the formation of a gastrula",
				false,
				"No. Cleavage leads to the blastula stage, which leads to gastrulation and the formation of a gastrula.");
			
				p.addAnswer(4, "fertilization",
				false,
				"No. Fertilization occurs before cleavage.");
			
				p.addAnswer(5, "metamorphosis",
				false,
				"No. Metamorphosis is a resurgence of development that transforms an animal from a larva into an adult. There are many developmental stages between cleavage and metamorphosis.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335901;


		
		

		
			
			p.question = "Which trait below is a common feature of all animals? (<script type=\"text/javascript\">ebook(\'3201\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a homeobox-containing family of genes called <i>Hox</i> genes",
				true,
				"Correct. Animals share a unique homeobox-containing family of genes, known as <i>Hox</i> genes, suggesting that this gene family evolved in the eukaryote lineage that gave rise to the animals.");
			
				p.addAnswer(2, "bilateral symmetry",
				false,
				"No. Sponges and jellies are two groups of animals that do not exhibit bilateral symmetry.");
			
				p.addAnswer(3, "true tissues",
				false,
				"No. Sponges are an example of animals that do not possess true tissues.");
			
				p.addAnswer(4, "a true coelom",
				false,
				"No. Some animals do not have a coelom at all, and others have pseudocoeloms.");
			
				p.addAnswer(5, "only sexual reproduction",
				false,
				"No. Some animals reproduce asexually, as in the budding of <i>Hydra</i>, or the parthenogenesis seen among rotifers and certain species of lizards.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335902;


		
		

		
			
			p.question = "Many young animals are _____, a sexually immature form that is morphologically distinct from the adult stage. These young animals undergo _____ to become _____, which resemble adults but are not yet sexually mature. (<script type=\"text/javascript\">ebook(\'3201\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "larvae; metamorphosis; juveniles",
				true,
				"Correct.  Larvae go through metamorphosis to become juveniles.");
			
				p.addAnswer(2, "larvae; metamorphosis; adults",
				false,
				"No. Metamorphosis produces juveniles, which are sexually immature.");
			
				p.addAnswer(3, "juvenile; metamorphosis; adults",
				false,
				"No. Larvae are usually the first stage that undergoes metamorphosis. In addition, metamorphosis produces juveniles, which are sexually immature.");
			
				p.addAnswer(4, "juvenile; gastrulation; adults",
				false,
				"No. Larvae are usually the first stage that undergoes metamorphosis. Gastrulation is an embryonic process that helps establish the basic body plan. In addition, metamorphosis produces juveniles, which are sexually immature.");
			
				p.addAnswer(5, "larvae; gastrulation; juveniles",
				false,
				"No. Gastrulation is an embryonic process that helps establish the basic body plan.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335903;


		
		

		
			
			p.question = "Which of the following correctly lists the embryonic stages in the order that they develop? (<script type=\"text/javascript\">ebook(\'3201\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "zygote, blastula, gastrula, larva",
				true,
				"Correct.  A zygote is the first embryonic stage, and the final stage is the larva.");
			
				p.addAnswer(2, "blastula, zygote, gastrula, larva",
				false,
				"No. The zygote occurs before the blastula.");
			
				p.addAnswer(3, "zygote, larva, gastrula, blastula",
				false,
				"No. The blastula stage occurs before the gastrula stage, which leads to the larval stage.");
			
				p.addAnswer(4, "zygote, gastrula, blastula, larva",
				false,
				"No. The blastula occurs before the gastrula.");
			
				p.addAnswer(5, "zygote, blastula, larva, gastrula",
				false,
				"No. The gastrula occurs before the larva.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335904;


		
		

		
			
			p.question = "Which example below is a current hypothesis regarding the Cambrian explosion? (<script type=\"text/javascript\">ebook(\'3202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "An increase in atmospheric CO<sub>2</sub> led to an explosion of plants and life-forms that fed on plants.",
				false,
				"No. This is not a theory posed to explain the Cambrian explosion, which involved an \"explosion\" of animal diversity.");
			
				p.addAnswer(2, "Predator-prey relationships decreased diversity through natural selection.",
				false,
				"No. Predator-prey relationships led to increased diversity through natural selection.");
			
				p.addAnswer(3, "A rise in atmospheric nitrogen led to success of large animals with higher metabolic rates.",
				false,
				"No. A rise in atmospheric oxygen led to success of large animals with high metabolic rates.");
			
				p.addAnswer(4, "Evolution of the <i>Hox</i> gene complex provided developmental flexibility.",
				true,
				"Correct. This is a proposed theory to explain the Cambrian explosion.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. Only one choice is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335905;


		
		

		
			
			p.question = "Which of the following occurred during the Mesozoic era? (<script type=\"text/javascript\">ebook(\'3202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Marine reptiles disappeared.",
				false,
				"No. During the Mesozoic, some reptiles returned to the water and succeeded as large aquatic predators. Their decline occurred in the Cenozoic.");
			
				p.addAnswer(2, "Large mammalian herbivores and carnivores arose.",
				false,
				"No. This occurred during the Cenozoic.");
			
				p.addAnswer(3, "Flight evolved in pterosaurs and birds.",
				true,
				"Correct. This was the era in which flight evolved.");
			
				p.addAnswer(4, "Fishes emerged as top predators in marine food webs.",
				false,
				"No. This occurred during the Silurian and Devonian periods.");
			
				p.addAnswer(5, "A great diversity of new body plans emerged among animals.",
				false,
				"No. No fundamentally new body plans emerged during the Mesozoic era.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335906;


		
		

		
			
			p.question = "Symmetry is one of the most basic characteristics of animals. The group that has a different symmetry from the other four groups listed here is the _____. (<script type=\"text/javascript\">ebook(\'3203\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "arthropods",
				false,
				"No. Arthropods exhibit bilateral symmetry.");
			
				p.addAnswer(2, "chordates",
				false,
				"No. Chordates exhibit bilateral symmetry.");
			
				p.addAnswer(3, "molluscs",
				false,
				"No. Molluscs exhibit bilateral symmetry.");
			
				p.addAnswer(4, "jellies",
				true,
				"Correct. Individuals in the phylum Cnidaria represent an early branch of the animal kingdom. While the other groups mentioned in this question exhibit bilateral symmetry, jellies exhibit radial symmetry.");
			
				p.addAnswer(5, "annelids",
				false,
				"No. Annelids exhibit bilateral symmetry.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335907;


		
		

		
			
			p.question = "Which of the following is associated with bilateral symmetry? (<script type=\"text/javascript\">ebook(\'3203\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a sessile lifestyle",
				false,
				"No. Such a lifestyle is usually associated with radial symmetry.");
			
				p.addAnswer(2, "a lack of true tissues",
				false,
				"No. All bilaterally symmetrical animals have true tissues.");
			
				p.addAnswer(3, "sponges",
				false,
				"No. Sponges do not typically show bilateral symmetry.");
			
				p.addAnswer(4, "no mesoderm",
				false,
				"No. Animals with radial symmetry typically lack mesoderm.");
			
				p.addAnswer(5, "cephalization",
				true,
				"Correct. Bilateral animals generally have a concentration of sensory receptors at the anterior end.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335908;


		
		

		
			
			p.question = "\"Cephalization\" refers to having _____. (<script type=\"text/javascript\">ebook(\'3203\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "radial symmetry",
				false,
				"No. Animals with radial symmetry do not exhibit cephalization.");
			
				p.addAnswer(2, "a right and a left side",
				false,
				"No. This is a characteristic of bilateral symmetry, with which cephalization is associated.");
			
				p.addAnswer(3, "a head",
				true,
				"Correct. Cephalization is the evolutionary trend toward the concentration of sensory receptors in the anterior end.");
			
				p.addAnswer(4, "a dorsal and a ventral surface",
				false,
				"No. Having dorsal and ventral surfaces is not limited to lineages with a trend toward cephalization.");
			
				p.addAnswer(5, "ectoderm",
				false,
				"No. The ectoderm is the outermost germ (embryonic tissue) layer and is found in all eumetazoan embryos.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335909;


		
		

		
			
			p.question = "Unlike other animals, sponges _____. (<script type=\"text/javascript\">ebook(\'3203\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "are unicellular",
				false,
				"No. Sponges, like all other animals, are multicellular.");
			
				p.addAnswer(2, "possess cell walls",
				false,
				"No. Sponge cells do not have cell walls.");
			
				p.addAnswer(3, "lack true tissues",
				true,
				"Correct. Sponges diverged from the other animals early in their history.");
			
				p.addAnswer(4, "exhibit bilateral symmetry",
				false,
				"No. Sponges, like many other animals, do not exhibit bilateral symmetry.");
			
				p.addAnswer(5, "are prokaryotic",
				false,
				"No. All animals, including sponges, are eukaryotic.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335910;


		
		

		
			
			p.question = "Which of the following is a characteristic of cnidarians? (<script type=\"text/javascript\">ebook(\'3203\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "triploblastic bodies",
				false,
				"No. Cnidarians are diploblasts.");
			
				p.addAnswer(2, "mesoderm",
				false,
				"No. Cnidarians do not typically have a mesoderm layer.");
			
				p.addAnswer(3, "ectoderm and endoderm",
				true,
				"Correct. Cnidarians are diploblastic.");
			
				p.addAnswer(4, "a lack of true tissues",
				false,
				"No. Cnidarians have true tissues.");
			
				p.addAnswer(5, "bilateral symmetry",
				false,
				"No. Cnidarians do exhibit radial symmetry.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335911;


		
		

		
			
			p.question = "In the embryo of shark, ectoderm gives rise to _____; mesoderm gives rise to _____; endoderm gives rise to _____. (<script type=\"text/javascript\">ebook(\'3203\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "muscle; the outer covering of the animal; the central nervous system",
				false,
				"No. None of these are associated with the germ layer that gives rise to it.");
			
				p.addAnswer(2, "the lining of the digestive tract; muscle; the outer covering of the animal",
				false,
				"No. Two of these are not associated with the germ layers that give rise to them.");
			
				p.addAnswer(3, "the central nervous system; the outer covering of the animal; the lining of the digestive tube",
				false,
				"No. One of these is not associated with the germ layer that gives rise to it.");
			
				p.addAnswer(4, "muscle; the outer covering of the animal; the lining of the digestive tube",
				false,
				"No. Two of these are not associated with the germ layers that give rise to them.");
			
				p.addAnswer(5, "the central nervous system; muscle; the lining of the digestive tube",
				true,
				"Correct. Each of these is associated with the germ layer that gives rise to it.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335912;


		
		

		
			
			p.question = "All animals with bilateral symmetry have _____ germ layer(s). (<script type=\"text/javascript\">ebook(\'3203\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "one",
				false,
				"No. All animals have more than one germ layer.");
			
				p.addAnswer(2, "two",
				false,
				"No. Animals with radial symmetry have two germ layers.");
			
				p.addAnswer(3, "three",
				true,
				"Correct. All bilaterally symmetrical animals have three germ layers.");
			
				p.addAnswer(4, "four",
				false,
				"No. There are no animals with four germ layers.");
			
				p.addAnswer(5, "five",
				false,
				"No. There are no animals with five germ layers.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335913;


		
		

		
			
			p.question = "A true coelom is _____. (<script type=\"text/javascript\">ebook(\'3203\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a body cavity lined with tissues derived from the endoderm",
				false,
				"No. A true coelom is a body cavity lined with tissues derived from the mesoderm.");
			
				p.addAnswer(2, "a body cavity lined with endoderm and mesoderm",
				false,
				"No. This does not describe a true coelom but, rather, a pseudocoelom.");
			
				p.addAnswer(3, "a body cavity lined with mesoderm",
				true,
				"Correct. A true coelom is a fluid-filled body cavity lined with tissue derived from mesoderm.");
			
				p.addAnswer(4, "a thoracic body cavity",
				false,
				"No. A true coelom is a fluid-filled body cavity lined with tissue derived from mesoderm.");
			
				p.addAnswer(5, "an abdominal body cavity",
				false,
				"No. A true coelom is a fluid-filled body cavity lined with tissue derived from mesoderm.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335914;


		
		

		
			
			p.question = "One of the primary developmental/anatomical characteristics distinguishing the major animal phyla is the condition of the body cavity. A pseudocoelomate animal is one in which the body cavity is _____. (<script type=\"text/javascript\">ebook(\'3203\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "bounded completely by mesoderm",
				false,
				"No. This describes a coelomate.");
			
				p.addAnswer(2, "filled by a solid mass of mesoderm",
				false,
				"No. Then there would be no cavity (acoelomate).");
			
				p.addAnswer(3, "bounded completely by endoderm",
				false,
				"No. This condition does not exist in the animal kingdom. The food tube is not, technically speaking, a body cavity.");
			
				p.addAnswer(4, "bounded partly by ectoderm",
				false,
				"No. Ectoderm gives rise to the central nervous system.");
			
				p.addAnswer(5, "formed from mesoderm and endoderm",
				true,
				"Correct. If the cavity is not completely lined by tissue derived from mesoderm, it is termed a pseudocoelom.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335915;


		
		

		
			
			p.question = "The presence of a coelom is advantageous because _____. (<script type=\"text/javascript\">ebook(\'3203\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "it allows for a third embryonic germ layer",
				false,
				"No. Some triploblastic phyla lack a body cavity.");
			
				p.addAnswer(2, "it permits the development of an open circulatory system",
				false,
				"No. Many animals with a true coelom have closed circulatory systems.");
			
				p.addAnswer(3, "it allows room for the development and movement of internal organs",
				true,
				"Correct. A body cavity enables the internal organs to grow and move independently of the outer body wall.");
			
				p.addAnswer(4, "it is necessary for a complete digestive tract",
				false,
				"No. Animals that do not have a true coelom may still have a complete digestive tract.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. Only one of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335916;


		
		

		
			
			p.question = "Indeterminate cleavage is a process that produces embryonic cells that _____. (<script type=\"text/javascript\">ebook(\'3203\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "retain the capacity to develop into a complete embryo",
				true,
				"Correct.");
			
				p.addAnswer(2, "form eggs or sperm",
				false,
				"No. Eggs and sperm are made by meiosis.");
			
				p.addAnswer(3, "engage in photosynthesis",
				false,
				"No. This is not something that animal cells can do.");
			
				p.addAnswer(4, "form ectoderm but not endoderm or mesoderm",
				false,
				"No. Embryonic cells produced by indeterminate cleavage can develop into a complete embryo.");
			
				p.addAnswer(5, "form mesoderm but not endoderm or ectoderm",
				false,
				"No. Embryonic cells produced by indeterminate cleavage can develop into a complete embryo.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335917;


		
		

		
			
			p.question = "The zygotes of many protostomes undergo _____ cleavage and _____ cleavage. (<script type=\"text/javascript\">ebook(\'3203\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "spiral; radial",
				false,
				"No. Zygotes undergo either spiral or radial cleavage, but not both.");
			
				p.addAnswer(2, "determinate; indeterminate",
				false,
				"No. Zygotes undergo either determinate or indeterminate cleavage, but not both.");
			
				p.addAnswer(3, "radial; indeterminate",
				false,
				"No. This is characteristic of deuterostomes.");
			
				p.addAnswer(4, "radial; determinate",
				false,
				"No. One of these is not true of protostomes.");
			
				p.addAnswer(5, "determinate; spiral",
				true,
				"Correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335918;


		
		

		
			
			p.question = "An animal with a true coelom that has _____ cleavage must be a _____. (<script type=\"text/javascript\">ebook(\'3203\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "radial; protostome",
				false,
				"No. Protostomes exhibit spiral cleavage.");
			
				p.addAnswer(2, "radial; deuterostome",
				true,
				"Correct. A true coelom is a fluid-filled body cavity lined with mesoderm. Deuterostomes are characterized by radial cleavage.");
			
				p.addAnswer(3, "spiral; deuterostome",
				false,
				"No. Deuterostomes exhibit radial cleavage.");
			
				p.addAnswer(4, "spiral; endostome",
				false,
				"No. Endostome is not an appropriate name.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335919;


		
		

		
			
			p.question = "Which of the following is a trait shared by protostomes and deuterostomes? (<script type=\"text/javascript\">ebook(\'3203\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a body cavity",
				true,
				"Correct. Protostomes and deuterostomes have a body cavity, although the way that it forms is different.");
			
				p.addAnswer(2, "spiral cleavage",
				false,
				"No. Spiral cleavage is characteristic of protostomes but not deuterostomes.");
			
				p.addAnswer(3, "determinate cleavage",
				false,
				"No. Determinate cleavage is characteristic of protostomes but not deuterostomes.");
			
				p.addAnswer(4, "radial cleavage",
				false,
				"No. Radial cleavage is characteristic of deuterostomes but not protostomes.");
			
				p.addAnswer(5, "indeterminate cleavage",
				false,
				"No. Indeterminate cleavage is characteristic of deuterostomes but not protostomes.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335920;


		
		

		
			
			p.question = "Which one of the following is characteristic of protostomes? (<script type=\"text/javascript\">ebook(\'3203\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The blastopore forms the anus.",
				false,
				"No. This occurs in deuterostomes.");
			
				p.addAnswer(2, "Ectoderm forms the muscles.",
				false,
				"No. Mesoderm forms muscle.");
			
				p.addAnswer(3, "The digestive tract is incomplete.",
				false,
				"No. Protostomes generally have a complete digestive tract.");
			
				p.addAnswer(4, "Cell fate is determined early during embryonic development.",
				true,
				"Correct. This is known as determinate development and is characteristic of protostomes.");
			
				p.addAnswer(5, "Mesoderm forms appendages.",
				false,
				"No. Mesoderm does not form all parts of appendages. Besides, many protostomes do not have appendages.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335921;


		
		

		
			
			p.question = "The text describes two phylogenetic hypotheses regarding the relationships of the animal phyla. The tree that is based on molecular evidence differs from the tree based on morphological evidence in that it _____. (<script type=\"text/javascript\">ebook(\'3204\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "depicts sponges as basal animals",
				false,
				"No. Both trees do this.");
			
				p.addAnswer(2, "depicts cnidarians as basal eumetazoans",
				false,
				"No. Both trees do this.");
			
				p.addAnswer(3, "suggests that the animal clade is polyphyletic",
				false,
				"No. Both trees suggest that the animal clade is monophyletic.");
			
				p.addAnswer(4, "divides protostomes into two taxa",
				true,
				"Correct. Molecular studies generally divide the protostomes into ecdysozoans and lophotrochozoans.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. Just one of the choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335922;


		
		

		
			
			p.question = "Which of the following is the defining characteristic of the clade Ecdysozoa for which this group is named? (<script type=\"text/javascript\">ebook(\'3204\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a horseshoe-shaped crown of ciliated tentacles",
				false,
				"No. This is a characteristic of Lophotrochozoa.");
			
				p.addAnswer(2, "a trochophore larva",
				false,
				"No. This is a characteristic of Lophotrochozoa.");
			
				p.addAnswer(3, "the secretion of stiff external skeletons that must be shed to permit growth",
				true,
				"Correct. Though named for this characteristic, the clade is actually defined mainly by molecular evidence supporting common ancestry.");
			
				p.addAnswer(4, "segmented bodies",
				false,
				"No. Segmented bodies are found in many other clades.");
			
				p.addAnswer(5, "lack of true tissues",
				false,
				"No. Sponges are the only animal group that lacks true tissues.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

