

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "52: An Introduction to Ecology and the Biosphere 52: An Introduction to Ecology and the Biosphere > Activities Quiz";
	ak.quiz_loc_with_commas = "52: An Introduction to Ecology and the Biosphere 52: An Introduction to Ecology and the Biosphere, Activities Quiz";
	ak.quiz_title = "Activities Quiz";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 15;
	ak.non_essay_total = 15;
	ak.scored_item_total = 15;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336946;


		
		

		
			
			p.question = "In animal populations, DDT causes _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?1&H','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Science, Technology, and Society: DDT</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "birth defects",
				true,
				"In animals, long-term exposure to DDT can cause death or severe birth defects.");
			
				p.addAnswer(2, "tuberculosis",
				false,
				"Tuberculosis is caused by a bacterium, not by DDT.");
			
				p.addAnswer(3, "sleeping sickness",
				false,
				"In Africa, DDT has significantly reduced the incidence of sleeping sickness.");
			
				p.addAnswer(4, "the flu",
				false,
				"Influenza is caused by viruses, not by DDT.");
			
				p.addAnswer(5, "malaria",
				false,
				"An Africa, DDT has significantly reduced the incidence of malaria.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336947;


		
		

		
			
			p.question = "DDT is _____-soluble so it accumulates in _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?1&H','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Science, Technology, and Society: DDT</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "fat ... milk",
				true,
				"Fat-soluble DDT accumulates in the fats of milk and from there can be transferred to children.");
			
				p.addAnswer(2, "water ... milk",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(3, "water ... streams",
				false,
				"DDT is not water-soluble.");
			
				p.addAnswer(4, "fat ... streams",
				false,
				"Streams are composed of water and DDT will therefore not accumulate in them. However, DDT can accumulate in the tissues of animals living in streams.");
			
				p.addAnswer(5, "water ... oceans",
				false,
				"DDT is not water-soluble.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336948;


		
		

		
			
			p.question = "Which of these is a biotic component of an environment? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?50&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Adaptations to Biotic and Abiotic Factors</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "bacteria on the surface of your skin",
				true,
				"\"Biotic\" refers to the bacteria and other living components of an environment.");
			
				p.addAnswer(2, "light",
				false,
				"Light is not alive, and the term \"biotic\" refers to that which is living.");
			
				p.addAnswer(3, "the availability of water",
				false,
				"Water is not alive, and the term \"biotic\" refers to that which is living.");
			
				p.addAnswer(4, "the mineral supplements you consume",
				false,
				"Minerals are not alive, and the term \"biotic\" refers to that which is living.");
			
				p.addAnswer(5, "the temperature where you live",
				false,
				"Temperature is not alive, and the term \"biotic\" refers to that which is living.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336949;


		
		

		
			
			p.question = "Desert owls are inactive during the day and active at night. They also have small bodies. This describes _____ adaptation to the hot and dry desert. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?50&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Adaptations to Biotic and Abiotic Factors</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "anatomical",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(2, "behavioral",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(3, "physiological",
				false,
				"The question does not mention any physiological adaptations.");
			
				p.addAnswer(4, "anatomical and behavioral",
				true,
				"The small body size of the desert owl promotes heat loss, and being inactive during the day allows the desert owl to avoid the worst of the desert heat.");
			
				p.addAnswer(5, "anatomical, behavioral, and physiological",
				false,
				"The question does not mention any physiological adaptations.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336950;


		
		

		
			
			p.question = "Horned lizards are desert animals that are active during the day. Their skin and kidneys are efficient at conserving water; when they get hot, they move to the shade so they can cool off. This describes _____ adaptation to the hot and dry desert. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?50&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Adaptations to Biotic and Abiotic Factors</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "anatomical",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(2, "behavioral",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(3, "physiological",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(4, "behavioral and physiological",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(5, "anatomical, behavioral, and physiological",
				true,
				"The skin and kidneys of horned lizards exhibit anatomical and physiological adaptations to the hot and dry desert environment. Moving to the shade when they get too hot is a behavioral adaptation.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336951;


		
		

		
			
			p.question = "Cacti are desert plants with C<sub>4</sub> metabolism. In addition, cacti bloom at night. This describes _____ adaptation to the hot and dry desert. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?50&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Adaptations to Biotic and Abiotic Factors</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "anatomical",
				false,
				"While cacti do have anatomical adaptations to a desert environment, none are described in this question.");
			
				p.addAnswer(2, "behavioral",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(3, "physiological",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(4, "behavioral and physiological",
				true,
				"Blooming at night is a behavioral adaptation that allows cacti to exploit pollinators that are active only at night. C<sub>4</sub> metabolism is a physiological adaptation related to carbon dioxide uptake and water conservation.");
			
				p.addAnswer(5, "anatomical, behavioral, and physiological",
				false,
				"The question does not mention any anatomical adaptations.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336952;


		
		

		
			
			p.question = "Which of these is characteristic of the photic zone of a freshwater biome? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?50&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Terrestrial Biomes</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the presence of algae",
				true,
				"\"Photic\" means light, and light encourages the growth of photosynthetic organisms.");
			
				p.addAnswer(2, "relatively cool water",
				false,
				"Relatively cool water is more characteristic of the aphotic zone than of the photic zone.");
			
				p.addAnswer(3, "relatively stable water temperature",
				false,
				"Relatively stable water temperature is more characteristic of the aphotic zone than of the photic zone.");
			
				p.addAnswer(4, "dead organic matter",
				false,
				"Dead organic matter is a major energy source for animals living in the aphotic zone.");
			
				p.addAnswer(5, "low oxygen level",
				false,
				"A low oxygen level is more characteristic of the aphotic zone than of the photic zone.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336953;


		
		

		
			
			p.question = "The benthic zone of aquatic environments is defined as the _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?50&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Terrestrial Biomes</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "region that receives abundant sunlight",
				false,
				"The region that receives abundant sunlight is the photic zone. Whether or not the benthic zone receives sunlight depends on the depth and clarity of the body of water.");
			
				p.addAnswer(2, "region where phytoplankton are found",
				false,
				"phytoplankton require light, so they are generally found in the photic zone.");
			
				p.addAnswer(3, "region that receives little or no light",
				false,
				"The region that receives little or no light is the aphotic zone. Whether or not the benthic zone receives sunlight depends on the depth and clarity of the body of water.");
			
				p.addAnswer(4, "substrate at the bottom of the body of water",
				true,
				"This is the definition of the benthic zone.");
			
				p.addAnswer(5, "region that is flooded at high tide and not covered by water at low tide",
				false,
				"The intertidal zone is flooded at high tide and not covered by water at low tide.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336954;


		
		

		
			
			p.question = "The _____ biome is the largest of Earth\'s biomes. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?50&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Terrestrial Biomes</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "marine",
				true,
				"The marine biome is the largest of Earth\'s biomes.");
			
				p.addAnswer(2, "grassland",
				false,
				"This is not the largest of Earth\'s biomes.");
			
				p.addAnswer(3, "freshwater",
				false,
				"This is not the largest of Earth\'s biomes.");
			
				p.addAnswer(4, "rain forest",
				false,
				"This is not the largest of Earth\'s biomes.");
			
				p.addAnswer(5, "desert",
				false,
				"This is not the largest of Earth\'s biomes.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336955;


		
		

		
			
			p.question = "A(n) _____ is a region where fresh water and salt water mix. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?50&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Terrestrial Biomes</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "benthic zone",
				false,
				"This is the substrate at the bottom of a body of water.");
			
				p.addAnswer(2, "intertidal zone",
				false,
				"This is the region covered with water at high tide and not covered with water at low tide.");
			
				p.addAnswer(3, "aphotic zone",
				false,
				"The aphotic zone is characterized by a lack of significant light.");
			
				p.addAnswer(4, "estuary",
				true,
				"Estuaries are regions where fresh water and salty marine water mix.");
			
				p.addAnswer(5, "photic zone",
				false,
				"The photic zone is the region of a body of water that is well-lighted.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336956;


		
		

		
			
			p.question = "What are the two major factors determining the distribution of terrestrial biomes? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?50&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Terrestrial Biomes</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "temperature and light",
				false,
				"While light is a significant factor, it is not one of the two major factors.");
			
				p.addAnswer(2, "temperature and rainfall",
				true,
				"These are the two major factors that determine the distribution of terrestrial biomes.");
			
				p.addAnswer(3, "light and rainfall",
				false,
				"While light is a significant factor, it is not one of the two major factors.");
			
				p.addAnswer(4, "plants and animals",
				false,
				"Abiotic factors determine the distribution of plant and animal life.");
			
				p.addAnswer(5, "temperature and plants",
				false,
				"This choice is partially correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336957;


		
		

		
			
			p.question = "Which of these biomes is characterized by little rainfall? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?50&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Terrestrial Biomes</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "temperate broadleaf forest",
				false,
				"Temperate broadleaf forests get sufficient rainfall to support trees.");
			
				p.addAnswer(2, "coniferous forest",
				false,
				"Coniferous forests get sufficient rainfall to support trees.");
			
				p.addAnswer(3, "desert",
				true,
				"Deserts are characterized by levels of rainfall less than 30 cm per year.");
			
				p.addAnswer(4, "temperate grassland",
				false,
				"While they do experience seasonal drought, temperate grasslands receive more rainfall than another of the biomes listed here.");
			
				p.addAnswer(5, "tropical rain forest",
				false,
				"Tropical rain forests get sufficient rainfall to support trees.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336958;


		
		

		
			
			p.question = "Which of these is the largest terrestrial biome on Earth? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?50&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Terrestrial Biomes</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "tundra",
				false,
				"While covering an extensive area, tundra is not the largest of the terrestrial biomes.");
			
				p.addAnswer(2, "coniferous forest",
				true,
				"Coniferous forests are the largest terrestrial biome on Earth. However, as a result of logging, they are disappearing at a very rapid rate.");
			
				p.addAnswer(3, "temperate broadleaf forest",
				false,
				"This is not the largest terrestrial biome.");
			
				p.addAnswer(4, "temperate grassland",
				false,
				"This is not the largest terrestrial biome. Furthermore most North American temperate grassland (known as prairie) has been converted to farmland.");
			
				p.addAnswer(5, "desert",
				false,
				"This is not the largest terrestrial biome.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336959;


		
		

		
			
			p.question = "Which biome is characterized by an extensive canopy that allows little light to penetrate to the ground and by the presence of epiphytes? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?50&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Terrestrial Biomes</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "temperate grassland",
				false,
				"Canopies are characteristic of biomes dominated by trees; grasslands are dominated by grasses.");
			
				p.addAnswer(2, "coniferous forest",
				false,
				"Another biome listed here has a more extensive canopy than that seen in coniferous forests.");
			
				p.addAnswer(3, "tropical rain forest",
				true,
				"Two of the characteristics of a tropical rain forest are the presence of epiphytes and an extensive canopy that allows little light to penetrate to the ground.");
			
				p.addAnswer(4, "desert",
				false,
				"Canopies are not characteristic of desert biomes.");
			
				p.addAnswer(5, "tundra",
				false,
				"Canopies are characteristic of biomes dominated by trees; tundra lacks trees and other tall plants.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336960;


		
		

		
			
			p.question = "Which biome is characterized by the presence of permafrost? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?50&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Terrestrial Biomes</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "taiga",
				false,
				"Taiga, northern coniferous forest, is not characterized by the presence of permanently frozen subsoil.");
			
				p.addAnswer(2, "tropical forest",
				false,
				"The tropical forest biome is not characterized by the presence of permanently frozen subsoil.");
			
				p.addAnswer(3, "tundra",
				true,
				"Permafrost, permanently frozen subsoil, is a characteristic of tundra.");
			
				p.addAnswer(4, "coniferous forest",
				false,
				"The coniferous forest biome is not characterized by the presence of permanently frozen subsoil.");
			
				p.addAnswer(5, "desert",
				false,
				"The desert biome is not characterized by the presence of permanently frozen subsoil.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

