

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "10: Photosynthesis > Practice Test";
	ak.quiz_loc_with_commas = "10: Photosynthesis, Practice Test";
	ak.quiz_title = "Practice Test";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 35;
	ak.non_essay_total = 35;
	ak.scored_item_total = 35;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334618;


		
		

		
			
			p.question = "In photosynthesis, plants use carbon from _____ to make sugar and other organic molecules. (<script type=\"text/javascript\">ebook(\'10OV\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "water",
				false,
				"No. Water does not contain carbon.");
			
				p.addAnswer(2, "carbon dioxide",
				true,
				"Correct. Less than 1% of the atmosphere is CO<sub>2</sub>, but it is enough to support photosynthesis.");
			
				p.addAnswer(3, "chlorophyll",
				false,
				"No. Although a chlorophyll molecule does contain carbon, chlorophyll is not the source of the carbon used to synthesize sugars.");
			
				p.addAnswer(4, "the sun",
				false,
				"No. The sun produces electromagnetic energy.");
			
				p.addAnswer(5, "soil",
				false,
				"No. Plants do obtain many trace elements and water from the soil.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334619;


		
		

		
			
			p.question = "Which of the following groups of organisms contain only heterotrophs? (<script type=\"text/javascript\">ebook(\'10OV\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "bacteria",
				false,
				"No. Though some bacteria are heterotrophic, there are many species of photosynthetic bacteria.");
			
				p.addAnswer(2, "pine trees",
				false,
				"No. Plants are the dominant autotrophs on land.");
			
				p.addAnswer(3, "mushrooms",
				true,
				"Correct. A mushroom is a fungus; fungi obtain their nutrients by absorption, not photosynthesis.");
			
				p.addAnswer(4, "seaweed",
				false,
				"No. Seaweeds, more properly termed multicellular algae, can photosynthesize.");
			
				p.addAnswer(5, "algae",
				false,
				"No. Algae are autotrophs.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334620;


		
		

		
			
			p.question = "How does carbon dioxide enter the leaf? (<script type=\"text/javascript\">ebook(\'1001\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "through the chloroplasts",
				false,
				"No. The chloroplasts are generally within the leaf.");
			
				p.addAnswer(2, "through the mesophyll",
				false,
				"No. The mesophyll is the middle of the leaf.");
			
				p.addAnswer(3, "through the thylakoids",
				false,
				"No. These are part of the chloroplasts.");
			
				p.addAnswer(4, "through the stomata",
				true,
				"Correct. These are the openings in the leaf for gas exchange.");
			
				p.addAnswer(5, "through the vascular system",
				false,
				"No. This is the system of tubes that carries liquid through the plant.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334621;


		
		

		
			
			p.question = "In a rosebush, chlorophyll is located in _____. (<script type=\"text/javascript\">ebook(\'1001\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "chloroplasts, which are in mesophyll cells in the thylakoids of a leaf",
				false,
				"No. A thylakoid is a cellular structure, not a type of leaf tissue.");
			
				p.addAnswer(2, "mesophyll cells, found within the thylakoids of a leaf\'s chloroplasts",
				false,
				"No. Chloroplasts are larger than thylakoids, and mesophyll cells are larger than chloroplasts.");
			
				p.addAnswer(3, "thylakoids, which are in mesophyll cells in the chloroplasts of a leaf",
				false,
				"No. A chloroplast is a cellular organelle.");
			
				p.addAnswer(4, "chloroplasts, which are in thylakoids in the mesophyll cells of a leaf",
				false,
				"No. Thylakoids are smaller structures than chloroplasts.");
			
				p.addAnswer(5, "thylakoids, which are in chloroplasts in the mesophyll cells of a leaf",
				true,
				"Correct. Thylakoids are arranged in stacks within the 30&ndash;40 chloroplasts per typical mesophyll cell.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334622;


		
		

		
			
			p.question = "Chlorophyll molecules are in which part of the chloroplast? (<script type=\"text/javascript\">ebook(\'1001\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "thylakoid",
				true,
				"Correct. The chlorophyll molecules are embedded in the thylakoid membranes of the chloroplasts.");
			
				p.addAnswer(2, "stroma",
				false,
				"No. The stroma is around the grana.");
			
				p.addAnswer(3, "stomata",
				false,
				"No. These are the openings for gas exchange.");
			
				p.addAnswer(4, "plasma membrane",
				false,
				"No. These are around the cell and do not have chloroplasts.");
			
				p.addAnswer(5, "Golgi apparatus",
				false,
				"No. These prepare proteins for export from the cell and are not involved in photosynthesis.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334623;


		
		

		
			
			p.question = "The source of the oxygen produced by photosynthesis has been identified through experiments using radioactive tracers. The oxygen comes from _____. (<script type=\"text/javascript\">ebook(\'1001\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "carbon dioxide",
				false,
				"No. This is not a source of the oxygen produced; the oxygen molecules in carbon dioxide become part of glucose.");
			
				p.addAnswer(2, "glucose",
				false,
				"No. The product of photosynthesis is glucose, so it is not a source.");
			
				p.addAnswer(3, "radioisotopes",
				false,
				"No. These are just tracers used to find the molecular source of the oxygen.");
			
				p.addAnswer(4, "water",
				true,
				"Correct. The oxygen produced by photosynthesis comes from the splitting of water.");
			
				p.addAnswer(5, "light",
				false,
				"No. Light is not a source of atoms.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334624;


		
		

		
			
			p.question = "In photosynthesis, what is the fate of the oxygen atoms present in CO<sub>2</sub>? They end up ______. (<script type=\"text/javascript\">ebook(\'1001\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "as molecular oxygen",
				false,
				"No. The splitting of water produces O<sub>2</sub>.");
			
				p.addAnswer(2, "in sugar molecules",
				false,
				"No. However, this answer is partially correct.");
			
				p.addAnswer(3, "in water",
				false,
				"No. However, this answer is partially correct.");
			
				p.addAnswer(4, "as molecular oxygen and in sugar molecules",
				false,
				"No. The splitting of water produces O<sub>2</sub>.");
			
				p.addAnswer(5, "in sugar molecules and in water",
				true,
				"Correct. The oxygen atoms present in carbon dioxide appear in sugar and water.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334625;


		
		

		
			
			p.question = "Molecular oxygen is produced during _____. (<script type=\"text/javascript\">ebook(\'1001\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "glycolysis",
				false,
				"No. Glycolysis does not produce O<sub>2</sub>.");
			
				p.addAnswer(2, "the light reactions of photosynthesis",
				true,
				"Correct. The light reactions of photosynthesis generate molecular oxygen when water is split.");
			
				p.addAnswer(3, "the Calvin cycle",
				false,
				"No. The Calvin cycle does not produce O<sub>2</sub>.");
			
				p.addAnswer(4, "aerobic respiration",
				false,
				"No. Aerobic respiration uses O<sub>2</sub>.");
			
				p.addAnswer(5, "the electron transport chain",
				false,
				"No. The light reactions of photosynthesis generate molecular oxygen when water is split.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334626;


		
		

		
			
			p.question = "The reactions of the Calvin cycle are not directly dependent on light, but they usually do not occur at night. Why? (<script type=\"text/javascript\">ebook(\'1001\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "It is often too cold at night for these reactions to take place.",
				false,
				"No. Although it is true that metabolic reactions are slower when the temperature is lower, this is not the best answer.");
			
				p.addAnswer(2, "Carbon dioxide concentrations decrease at night.",
				false,
				"No. In the dark, stomata can open without danger of losing water and so adequate CO<sub>2</sub> is available.");
			
				p.addAnswer(3, "The Calvin cycle depends on products of the light reactions.",
				true,
				"Correct. The ATP and NADPH produced during the light reactions are necessary for the Calvin cycle.");
			
				p.addAnswer(4, "Plants usually open their stomata at night.",
				false,
				"No. Because the Calvin cycle utilizes CO<sub>2</sub>, which enters through the stomata, having the stomata open would be beneficial, but nonetheless, the Calvin cycle usually does not occur at night.");
			
				p.addAnswer(5, "At night, plants cannot produce the water needed for the Calvin cycle.",
				false,
				"No. Water is not necessary for the Calvin cycle and plants do not produce enough water for photosynthesis. (Some water is produced during respiration.) Water molecules are split during the light reactions.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334627;


		
		

		
			
			p.question = "The photosynthetic event known as the Calvin cycle occurs in the _____. (<script type=\"text/javascript\">ebook(\'1001\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "thylakoid membrane",
				false,
				"No. Photosynthetic pigments are associated with the thylakoid membrane.");
			
				p.addAnswer(2, "(inner) thylakoid space",
				false,
				"No. The thylakoids of the chloroplast are the sites of the light reactions, while the Calvin cycle occurs in the stroma.");
			
				p.addAnswer(3, "stroma",
				true,
				"Correct. The thylakoids of the chloroplast are the sites of the light reactions, while the Calvin cycle occurs in the stroma.");
			
				p.addAnswer(4, "stomata",
				false,
				"No. Stomata, found on the leaf surface, allow for gas exchange with the external environment.");
			
				p.addAnswer(5, "matrix",
				false,
				"No. This is a mitochondrial region.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334628;


		
		

		
			
			p.question = "A photon of which of these colors would carry the most energy? (<script type=\"text/javascript\">ebook(\'1002\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "green",
				false,
				"No. Green is not the shortest wavelength.");
			
				p.addAnswer(2, "yellow",
				false,
				"No. Yellow is not the shortest wavelength.");
			
				p.addAnswer(3, "blue",
				true,
				"Correct. The shorter the wavelength, the greater the energy content.");
			
				p.addAnswer(4, "orange",
				false,
				"No. Orange is not the shortest wavelength.");
			
				p.addAnswer(5, "red",
				false,
				"No. Red is not the shortest wavelength.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334629;


		
		

		
			
			p.question = "The most important role of pigments in photosynthesis is to _____. (<script type=\"text/javascript\">ebook(\'1002\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "capture light energy",
				true,
				"Correct. The wavelengths most effectively absorbed by pigments are the colors most useful as energy for the light reactions.");
			
				p.addAnswer(2, "screen out harmful ultraviolet rays",
				false,
				"No. Pigments absorb light. The wavelengths most effectively absorbed by pigments are the colors most useful as energy for the light reactions.");
			
				p.addAnswer(3, "store energy in glucose molecules",
				false,
				"No. Photosynthetic pigments do not store glucose.");
			
				p.addAnswer(4, "release energy from glucose molecules",
				false,
				"No. Glucose is a product of photosynthesis.");
			
				p.addAnswer(5, "store energy in ATP",
				false,
				"No. Consider the source of the energy used to manufacture ATP.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334630;


		
		

		
			
			p.question = "The wavelengths of light absorbed by pigments in the granum are mainly in which range? (<script type=\"text/javascript\">ebook(\'1002\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "green, which is why plants are green",
				false,
				"No. Plants are green because they are not absorbing the green light.");
			
				p.addAnswer(2, "blue-violet and red-orange",
				true,
				"Correct. These are the wavelengths of light that plant pigments absorb.");
			
				p.addAnswer(3, "the entire spectrum of white light",
				false,
				"No. Plants are more selective than this.");
			
				p.addAnswer(4, "the infrared",
				false,
				"No. Plants absorb light in the visible range.");
			
				p.addAnswer(5, "the range absorbed by carotenoids",
				false,
				"No. Carotenoids are accessory pigments, absorbing light in only one area of the spectrum.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334631;


		
		

		
			
			p.question = "Based on the work of Engelmann, the wavelengths of light most effective in driving photosynthesis are referred to as _____. (<script type=\"text/javascript\">ebook(\'1002\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "an effective spectrum",
				false,
				"No. There is no such thing as an effective spectrum in reference to photosynthesis.");
			
				p.addAnswer(2, "an absorption spectrum",
				false,
				"No. These are the wavelengths that are absorbed, not all of which are used for photosynthesis.");
			
				p.addAnswer(3, "an electromagnetic spectrum",
				false,
				"No. Light is a form of electromagnetic energy.");
			
				p.addAnswer(4, "a visible light spectrum",
				false,
				"No. This encompasses many wavelengths, not all of which are effective at promoting photosynthesis.");
			
				p.addAnswer(5, "an action spectrum",
				true,
				"Correct. An action spectrum profiles the effectiveness of different wavelengths of light in driving photosynthesis.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334632;


		
		

		
			
			p.question = "When chloroplast pigments absorb light, _____. (<script type=\"text/javascript\">ebook(\'1002\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "they become reduced",
				false,
				"No. In fact, if a photosystem is present, just the opposite will happen&mdash;the pigments become oxidized.");
			
				p.addAnswer(2, "they lose potential energy",
				false,
				"No. The absorbed light increases the potential energy of the pigments.");
			
				p.addAnswer(3, "their electrons become excited",
				true,
				"Correct. When a molecule absorbs a photon of light, one of the molecule\'s electrons is elevated to an orbital where it has more potential energy.");
			
				p.addAnswer(4, "the Calvin cycle is triggered",
				false,
				"No. The Calvin cycle is a separate, non-light-dependent pathway.");
			
				p.addAnswer(5, "their photons become excited",
				false,
				"No. Photons come from the sun, not from a chloroplast.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334633;


		
		

		
			
			p.question = "The reaction center, light-harvesting complexes, and primary electron acceptors that cluster in the thylakoid membrane form what? (<script type=\"text/javascript\">ebook(\'1002\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the fluorescence center",
				false,
				"No. There is no specific fluorescence center.");
			
				p.addAnswer(2, "the photosystem",
				true,
				"Correct. The above combination describes the photosystem.");
			
				p.addAnswer(3, "the electron transport chain",
				false,
				"No. This is not a description of an electron transport chain.");
			
				p.addAnswer(4, "the carbon-fixation unit",
				false,
				"No. Carbon fixation occurs in the Calvin cycle.");
			
				p.addAnswer(5, "the electromagnetic spectrum",
				false,
				"No. This is part of the spectrum and not part of the plant.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334634;


		
		

		
			
			p.question = "Where do the electrons needed by photosystem II originate? (<script type=\"text/javascript\">ebook(\'1002\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "other chlorophyll molecules",
				false,
				"No. Ultimately these must be replaced.");
			
				p.addAnswer(2, "ATP",
				false,
				"No. This is not a source of electrons, but rather a product of photosystem activity.");
			
				p.addAnswer(3, "the electron transport chain",
				false,
				"No. This carries electrons, but is not their source.");
			
				p.addAnswer(4, "light",
				false,
				"No. Light provides photons, not electrons.");
			
				p.addAnswer(5, "water",
				true,
				"Correct. The splitting of water molecules provides the source of electrons for photosystem II.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334635;


		
		

		
			
			p.question = "During photosynthesis in chloroplasts, O<sub>2</sub> is produced from ______ via a series of reactions associated with ______. (<script type=\"text/javascript\">ebook(\'1002\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "CO<sub>2</sub>; photosystem II",
				false,
				"No. CO<sub>2</sub> is not the source of O<sub>2</sub>.");
			
				p.addAnswer(2, "H<sub>2</sub>O; photosystem II",
				true,
				"Correct. When photosystem II absorbs light, the electron that is excited to a higher energy level in the chlorophyll leaves a \"hole\" that is filled when an enzyme extracts electrons from the hydrogen of water, releasing oxygen.");
			
				p.addAnswer(3, "CO<sub>2</sub>; the Calvin cycle",
				false,
				"No. CO<sub>2</sub> is not the source of O<sub>2</sub>.");
			
				p.addAnswer(4, "H<sub>2</sub>O; photosystem I",
				false,
				"No. This choice is partially correct.");
			
				p.addAnswer(5, "CO<sub>2</sub>; both photosystem I and the Calvin cycle",
				false,
				"No. CO<sub>2</sub> is not the source of O<sub>2</sub>.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334636;


		
		

		
			
			p.question = "During photosynthesis, an electron transport chain is used to _____. (<script type=\"text/javascript\">ebook(\'1002\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "transport NADPH from the light reactions to the Calvin cycle",
				false,
				"No. Consider what an electron transport chain transports.");
			
				p.addAnswer(2, "transport excited electrons from P700 to an electron acceptor",
				false,
				"No. Each photoexcited electron passes from the primary electron acceptor of photosystem II to photosystem I via an electron transport chain.");
			
				p.addAnswer(3, "transport excited electrons from P680 to an electron acceptor",
				false,
				"No. Each photoexcited electron passes from the primary electron acceptor of photosystem II to photosystem I via an electron transport chain.");
			
				p.addAnswer(4, "transport electrons from photosystem II to photosystem I",
				true,
				"Correct. Each photoexcited electron passes from the primary electron acceptor of photosystem II to photosystem I via an electron transport chain.");
			
				p.addAnswer(5, "transport excited electrons from P700 to an electron acceptor and transport excited electrons from P680 to an electron acceptor",
				false,
				"No. Each photoexcited electron passes from the primary electron acceptor of photosystem II to photosystem I via an electron transport chain.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334637;


		
		

		
			
			p.question = "Which one of the following is cycled in the cyclic part of light reactions? (<script type=\"text/javascript\">ebook(\'1002\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "electrons",
				true,
				"Correct. During the light reactions of photosynthesis, there are two possible routes for electron flow: cyclic and noncyclic.");
			
				p.addAnswer(2, "ATP",
				false,
				"No. ATP is used by the Calvin cycle.");
			
				p.addAnswer(3, "NADPH",
				false,
				"No. NADPH is sent to the Calvin cycle.");
			
				p.addAnswer(4, "DPGA",
				false,
				"No. Electrons are cycled. During the light reactions of photosynthesis, there are two possible routes for electron flow: cyclic and noncyclic.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334638;


		
		

		
			
			p.question = "Both mitochondria and chloroplasts _____. (<script type=\"text/javascript\">ebook(\'1002\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "use a hydrogen ion (proton) gradient to produce ATP",
				true,
				"Correct. Chloroplasts and mitochondria both generate ATP by chemiosmosis. An electron transport chain in the membrane pumps protons across the membrane as electrons are passed through a series of carriers that are progressively more electronegative. Built into the same membrane is an ATP synthase that couples the diffusion of hydrogen ions down their gradient to the phosphorylation of ADP.");
			
				p.addAnswer(2, "obtain electrons from water",
				false,
				"No. Mitochondria do not do this.");
			
				p.addAnswer(3, "reduce NAD<sup>+</sup>, forming NADP",
				false,
				"No. Chloroplasts and mitochondria both generate ATP by chemiosmosis. An electron transport chain in the membrane pumps protons across the membrane as electrons are passed through a series of carriers that are progressively more electronegative. Built into the same membrane is an ATP synthase that couples the diffusion of hydrogen ions down their gradient to the phosphorylation of ADP.");
			
				p.addAnswer(4, "release oxygen as a by-product",
				false,
				"No. Oxygen is not a by-product of cellular respiration.");
			
				p.addAnswer(5, "are surrounded by a single membrane",
				false,
				"No. Both are surrounded by two membranes.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334639;


		
		

		
			
			p.question = "You could distinguish a granum from a crista because the granum, but not the crista, would _____. (<script type=\"text/javascript\">ebook(\'1002\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "be inside a mitochondrion",
				false,
				"No. Grana are found within chloroplasts.");
			
				p.addAnswer(2, "function in energy transformation",
				false,
				"No. Both grana and cristae play a role in energy transformation.");
			
				p.addAnswer(3, "have photosynthetic pigments",
				true,
				"Correct. The photosynthetic pigment chlorophyll is anchored in the thylakoid membrane.");
			
				p.addAnswer(4, "contain protein but not lipids",
				false,
				"No. Both contain both proteins and lipids.");
			
				p.addAnswer(5, "None of the above.",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334640;


		
		

		
			
			p.question = "During photosynthesis in a eukaryotic cell, a high proton concentration accumulates or is formed in the ______. (<script type=\"text/javascript\">ebook(\'1002\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "thylakoid membrane",
				false,
				"No. However, you are in the correct area of the chloroplast.");
			
				p.addAnswer(2, "(inner) thylakoid space",
				true,
				"Correct. In chloroplasts, the thylakoid membrane pumps protons from the stroma into the thylakoid space.");
			
				p.addAnswer(3, "stroma",
				false,
				"No. This is where the Calvin cycle takes place.");
			
				p.addAnswer(4, "stomata",
				false,
				"No. These are openings on the surface of a leaf.");
			
				p.addAnswer(5, "matrix",
				false,
				"No. The matrix is a mitochondrial region.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334641;


		
		

		
			
			p.question = "The light reactions of photosynthesis generate high-energy electrons, which end up in ____. The light reactions also produce ____ and ____. (<script type=\"text/javascript\">ebook(\'1002\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "ATP ... NADPH ... oxygen",
				false,
				"No. The formation of ATP results from chemiosmosis, not a reduction involving the transfer of electrons.");
			
				p.addAnswer(2, "oxygen ... sugar ... ATP",
				false,
				"No. Electrons do not end up in oxygen, and sugar is not a product of the light reactions.");
			
				p.addAnswer(3, "chlorophyll ... ATP ... NADPH",
				false,
				"No. The high-energy electrons are removed from chlorophyll, not added to it.");
			
				p.addAnswer(4, "water ... sugar ... oxygen",
				false,
				"No. Water is split during the light reactions, and sugar is not a product of the light reactions.");
			
				p.addAnswer(5, "NADPH ... ATP ... oxygen",
				true,
				"Correct. The electrons are transferred to NADP<sup>+</sup>, forming NADPH. ATP is formed via photophosphorylation, and oxygen is produced when water molecules are split.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334642;


		
		

		
			
			p.question = "The energy used to produce ATP in the light reactions of photosynthesis comes from _____. (<script type=\"text/javascript\">ebook(\'1002\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the burning of sugar molecules",
				false,
				"No. The production of ATP occurs during the light reactions before any sugar has been synthesized.");
			
				p.addAnswer(2, "splitting water",
				false,
				"No. Termed \"chemiosmosis,\" the diffusion of hydrogen ions through the thylakoid membrane provides the energy to produce ATP.");
			
				p.addAnswer(3, "movement of H<sup>+</sup> through a membrane",
				true,
				"Correct. Termed \"chemiosmosis,\" the diffusion of hydrogen ions through the thylakoid membrane provides the energy to produce ATP.");
			
				p.addAnswer(4, "carbon fixation",
				false,
				"No. This is an endergonic process.");
			
				p.addAnswer(5, "fluorescence",
				false,
				"No. Fluorescence occurs when the chlorophyll molecule does not pass its excited electron to a photosystem. The electron falls back to its ground state, releasing its energy as light.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334643;


		
		

		
			
			p.question = "What is the role of NADP<sup>+</sup> in photosynthesis? (<script type=\"text/javascript\">ebook(\'1002\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "It assists chlorophyll in capturing light.",
				false,
				"No. The reaction of light and chlorophyll requires no assistance. Even isolated chlorophyll will continue to react with light.");
			
				p.addAnswer(2, "It acts as the primary electron acceptor for the photosystems.",
				false,
				"No. P680 and P700 are the electron acceptors associated with the two photosystems.");
			
				p.addAnswer(3, "As part of the electron transport chain, it manufactures ATP.",
				false,
				"No. Although NADP<sup>+</sup> is the terminal component of the electron transport system in the thylakoid membrane, it does not participate in ATP synthesis.");
			
				p.addAnswer(4, "It assists photosystem II in the splitting of water.",
				false,
				"No. NADP<sup>+</sup> receives electrons from photosystem I rather than photosystem II.");
			
				p.addAnswer(5, "It is reduced and then carries electrons to the Calvin cycle.",
				true,
				"Correct. Electrons received from photosystem I reduce NADP<sup>+</sup> to NADPH, which then carries them to the Calvin cycle.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334644;


		
		

		
			
			p.question = "Of the following, which occurs during the Calvin cycle? (<script type=\"text/javascript\">ebook(\'1003\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Light energy is converted to chemical energy.",
				false,
				"No. This is associated with the light reactions.");
			
				p.addAnswer(2, "ATP and NADPH are synthesized.",
				false,
				"No. This is associated with the light reactions.");
			
				p.addAnswer(3, "CO<sub>2</sub> is reduced.",
				true,
				"Correct. This is associated with the Calvin cycle.");
			
				p.addAnswer(4, "Excited electrons are conveyed from chlorophyll to an electron acceptor.",
				false,
				"No. This is associated with the light reactions.");
			
				p.addAnswer(5, "Photons are absorbed.",
				false,
				"No. This is associated with the light reactions.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334645;


		
		

		
			
			p.question = "Rubisco is _____. (<script type=\"text/javascript\">ebook(\'1003\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the enzyme in plants that first captures CO<sub>2</sub> to begin the Calvin cycle",
				true,
				"Correct. The enzyme that catalyzes the first step of the Calvin cycle (incorporation of a molecule of carbon dioxide by attaching it to a 5-carbon sugar, named ribulose biphosphate, or RuBP) is RuBP carboxylase, or rubisco.");
			
				p.addAnswer(2, "the enzyme responsible for splitting H<sub>2</sub>O to produce O<sub>2</sub> in photosynthesis",
				false,
				"No. This occurs in conjunction with photosystem II.");
			
				p.addAnswer(3, "the enzyme that forms a 4-carbon compound in CAM metabolism",
				false,
				"No. The enzyme that catalyzes the first step of the Calvin cycle (in C<sub>3</sub> plants) is RuBP carboxylase, or rubisco.");
			
				p.addAnswer(4, "the first stable intermediate in CAM metabolism",
				false,
				"No. Rubisco is an enzyme.");
			
				p.addAnswer(5, "the 5-carbon sugar molecule that reacts with CO<sub>2</sub> to begin the Calvin cycle",
				false,
				"No. Rubisco is an enzyme.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334646;


		
		

		
			
			p.question = "In the Calvin cycle, CO<sub>2</sub> is combined _____. (<script type=\"text/javascript\">ebook(\'1003\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "with a 2-carbon compound to form a 3-carbon compound",
				false,
				"No. Rubisco catalyzes the first step of the Calvin cycle&mdash;the incorporation of a molecule of carbon dioxide with a 5-carbon sugar. The 6-carbon product is so unstable that it decomposes immediately into two 3-carbon phosphoglycerates.");
			
				p.addAnswer(2, "with a 5-carbon compound to form an unstable 6-carbon compound, which decomposes into two 3-carbon compounds",
				true,
				"Correct. Rubisco catalyzes the first step of the Calvin cycle&mdash;the incorporation of a molecule of carbon dioxide with a 5-carbon sugar. The 6-carbon product is so unstable that it decomposes immediately into two 3-carbon phosphoglycerates.");
			
				p.addAnswer(3, "with a 7-carbon compound to form two 4-carbon compounds",
				false,
				"No. Rubisco catalyzes the first step of the Calvin cycle&mdash;the incorporation of a molecule of carbon dioxide with a 5-carbon sugar. The 6-carbon product is so unstable that it decomposes immediately into two 3-carbon phosphoglycerates.");
			
				p.addAnswer(4, "with a 5-carbon compound to form a stable 6-carbon compound that can be converted directly to glucose",
				false,
				"No. Rubisco catalyzes the first step of the Calvin cycle&mdash;the incorporation of a molecule of carbon dioxide with a 5-carbon sugar. The 6-carbon product is so unstable that it decomposes immediately into two 3-carbon phosphoglycerates.");
			
				p.addAnswer(5, "with two 2-carbon compounds to form a 5-carbon compound",
				false,
				"No. Rubisco catalyzes the first step of the Calvin cycle&mdash;the incorporation of a molecule of carbon dioxide with a 5-carbon sugar. The 6-carbon product is so unstable that it decomposes immediately into two 3-carbon phosphoglycerates.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334647;


		
		

		
			
			p.question = "Glyceraldehyde-3-phosphate (G3P) is produced in the stroma of chloroplasts. Which of the following statements is true about this compound? (<script type=\"text/javascript\">ebook(\'1003\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "It is produced from glucose during glycolysis.",
				false,
				"No. This is correct, but there is a better response.");
			
				p.addAnswer(2, "It is a 3-carbon sugar.",
				false,
				"No. This is correct, but there is a better response");
			
				p.addAnswer(3, "For every three molecules of CO<sub>2</sub>, six molecules of G3P are formed but only one molecule exits the cycle to be used by the plant cell.",
				false,
				"No. This is correct, but there is a better response.");
			
				p.addAnswer(4, "For every three molecules of CO<sub>2</sub>, six molecules of G3P are formed but five molecules must be recycled to regenerate three molecules of RuBP",
				false,
				"No. This is correct, but there is a better response.");
			
				p.addAnswer(5, "All of the above.",
				true,
				"Correct. All of the above statements are true of glyceraldehyde-3-phosphate.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334648;


		
		

		
			
			p.question = "Which of the following statements correctly describes the relationship between the light reactions and the Calvin cycle? (<script type=\"text/javascript\">ebook(\'1003\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The light reactions produce carbon dioxide, ATP, NADPH, all of which are used in the Calvin cycle.",
				false,
				"No, but part of this answer is correct.");
			
				p.addAnswer(2, "The light reactions produce ATP and NADPH, both of which are used in the Calvin cycle.",
				true,
				"Correct. NADPH provides reducing power by donating electrons and ATP provides energy when it is converted to ADP.");
			
				p.addAnswer(3, "The light reactions produce ADP and NADP<sup>+</sup>, both of which are used in the Calvin cycle.",
				false,
				"No. ADP and NADP<sup>+</sup> are used to make ATP and NADPH, respectively, during the light reactions and are byproducts of the Calvin cycle.");
			
				p.addAnswer(4, "The light reactions produce water, ATP, NADPH, all of which are used in the Calvin cycle.",
				false,
				"No, but part of this answer is correct.");
			
				p.addAnswer(5, "The light reactions produce carbon dioxide and water all of which are used in the Calvin cycle.",
				false,
				"No. Re-examine which compounds are produced by the light reactions and used by the Calvin cycle.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334649;


		
		

		
			
			p.question = "What is the role of NADP<sup>+</sup> in photosynthesis? (<script type=\"text/javascript\">ebook(\'1003\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "It helps produce ATP from the light reactions.",
				false,
				"No. ATP is produced by other electron acceptors in the electron transport chain.");
			
				p.addAnswer(2, "It absorbs light energy.",
				false,
				"No. The electrons in the chlorophyll absorb the light energy.");
			
				p.addAnswer(3, "It forms part of photosystem II.",
				false,
				"No. It is not defined as part of the photosystem.");
			
				p.addAnswer(4, "It is the primary electron acceptor.",
				false,
				"No. The primary electron acceptor passes on electrons ultimately to NADP<sup>+</sup>.");
			
				p.addAnswer(5, "It forms NADPH to be used in the Calvin cycle.",
				true,
				"Correct. It is the source of NADPH for the Calvin cycle.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334650;


		
		

		
			
			p.question = "The use of non-C<sub>3</sub> and non-CAM plants as crops may be limited in some regions because on hot, dry days, they close their stomata. What happens as a result of closing their stomata? (<script type=\"text/javascript\">ebook(\'1004\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "It reduces water loss.",
				false,
				"No. This is true, but there is a better response.");
			
				p.addAnswer(2, "It prevents carbon dioxide from entering the leaf.",
				false,
				"No. This is true, but there is a better response.");
			
				p.addAnswer(3, "In a process called photorespiration, rubisco binds oxygen instead of carbon dioxide.",
				false,
				"No. This is true, but there is a better response.");
			
				p.addAnswer(4, "It builds up oxygen from the light reactions in the leaf.",
				false,
				"No. This is true, but there is a better response.");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct. All of the above reactions happen in C<sub>3</sub> plants on hot, dry days.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334651;


		
		

		
			
			p.question = "Why are C<sub>4</sub> plants more suited to hot climates than C<sub>3</sub> plants? (<script type=\"text/javascript\">ebook(\'1004\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "They do not close their stomata in hot, dry weather.",
				false,
				"No. They close their stomata under these conditions for protection against water loss.");
			
				p.addAnswer(2, "Unlike C<sub>3</sub> plants, they keep fixing carbon dioxide even when the concentration of carbon dioxide in the leaf is low.",
				true,
				"Correct. They continue to fix carbon dioxide under low concentrations of the gas. Photosynthesis can continue even if the stomata are closed and the concentration of carbon dioxide diminishes.");
			
				p.addAnswer(3, "They evolved in cold weather but migrated to the tropics where they were more suitable.",
				false,
				"No. Almost definitely, they evolved in a hot climate.");
			
				p.addAnswer(4, "They suspend photosynthesis in the heat.",
				false,
				"No. Their advantage is that they can continue photosynthesis despite the adaptations they make against water loss.");
			
				p.addAnswer(5, "The same cells that bind carbon dioxide perform the Calvin cycle.",
				false,
				"No. They move the fixed carbon dioxide to cells in the inner part of the leaf, where the Calvin cycle enzymes are located.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334652;


		
		

		
			
			p.question = "You have a large, healthy philodendron that you carelessly leave in total darkness while you are away on vacation. You are surprised to find that it is still alive when you return. What has the plant been using for an energy source while in the dark? (<script type=\"text/javascript\">ebook(\'1004\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Even though it can\'t carry out the light reactions, the plant can still produce sugars because the Calvin cycle doesn\'t require light.",
				false,
				"No. The Calvin cycle is dependent on the products of the light reactions.");
			
				p.addAnswer(2, "While it did have access to light, the plant stored energy in the form of sugars or starch, and it was able to derive energy from the stored molecules during your vacation.",
				true,
				"Correct. Because plants make more organic material each day than they need to use as respiratory fuel and precursors for biosynthesis, the extra sugar is stockpiled as starch stored in chloroplasts, as well as in roots, tubers, seeds, and fruits.");
			
				p.addAnswer(3, "Even though the plant received no visible light, it was able to use the short-wave part of the electromagnetic spectrum (gamma rays and X-rays) to carry out photosynthesis.",
				false,
				"No. Short-wave radiation is not a part of the action spectrum of photosynthesis.");
			
				p.addAnswer(4, "When light energy is not available, plants can derive energy from inorganic molecules.",
				false,
				"No. Plants are not chemoautotrophs.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

