

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "47: Animal Development > Activities Quiz";
	ak.quiz_loc_with_commas = "47: Animal Development, Activities Quiz";
	ak.quiz_title = "Activities Quiz";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 15;
	ak.non_essay_total = 15;
	ak.scored_item_total = 15;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336711;


		
		

		
			
			p.question = "In sea urchins, the process of fertilization produces a(n) _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?47&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Sea Urchin Development</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "archenteron",
				false,
				"The archenteron, a primitive gut, is formed as a result of gastrulation.");
			
				p.addAnswer(2, "morula",
				false,
				"The morula is a solid ball of cells that forms as a result of cleavage, which follows fertilization.");
			
				p.addAnswer(3, "gastrula",
				false,
				"The gastrula is formed when the blastula undergoes gastrulation.");
			
				p.addAnswer(4, "gamete",
				false,
				"Gametes contribute the haploid sets of chromosomes that join together in the process of fertilization.");
			
				p.addAnswer(5, "zygote",
				true,
				"Fertilization, the combination of haploid sets of chromosomes, results in the formation of a diploid zygote.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336712;


		
		

		
			
			p.question = "What is the cortical reaction? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?47&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Sea Urchin Development</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the formation of a fertilization envelope that bars additional sperm from entry into the egg",
				true,
				"This is the cortical reaction.");
			
				p.addAnswer(2, "the release of hydrolytic enzymes from the sperm cell",
				false,
				"This describes the acrosomal reaction.");
			
				p.addAnswer(3, "a depolarization of the eggs\' plasma membrane so that only one sperm cell can fuse with it",
				false,
				"This describes the fast block to polyspermy.");
			
				p.addAnswer(4, "a series of rapid mitotic divisions that follow fertilization",
				false,
				"This describes cleavage.");
			
				p.addAnswer(5, "the process that forms a three-layered embryo",
				false,
				"Gastrulation is the process that forms a three-layered embryo.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336713;


		
		

		
			
			p.question = "As cleavage continues, a zygote forms into a solid multicellular ball called a(n) _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?47&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Sea Urchin Development</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "endometrium",
				false,
				"The endometrium is the layer of the uterus where implantation takes place.");
			
				p.addAnswer(2, "morula",
				true,
				"The morula is a solid ball of cells produced when the zygote undergoes cleavage.");
			
				p.addAnswer(3, "trophoblast",
				false,
				"The trophoblast is a layer of cells surrounding the blastula.");
			
				p.addAnswer(4, "gastrula",
				false,
				"The gastrula is formed when the blastula undergoes gastrulation.");
			
				p.addAnswer(5, "blastula",
				false,
				"The blastula is a hollow ball of cells formed after the solid ball of cells.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336714;


		
		

		
			
			p.question = "Several hours after fertilization, cleavage results in the formation of a hollow ball of cells called a _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?47&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Sea Urchin Development</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "blastomere",
				false,
				"Blastomeres are the cells of which the blastula is composed.");
			
				p.addAnswer(2, "morula",
				false,
				"The morula is a solid ball of cells produced prior to the formation of the hollow ball of cells.");
			
				p.addAnswer(3, "trophoblast",
				false,
				"The trophoblast is a layer of cells surrounding the blastula.");
			
				p.addAnswer(4, "gastrula",
				false,
				"The gastrula is formed when the blastula undergoes gastrulation.");
			
				p.addAnswer(5, "blastula",
				true,
				"The blastula is a hollow ball of cells formed as the result of cleavage.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336715;


		
		

		
			
			p.question = "The three-layered embryo is the _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?47&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Sea Urchin Development</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "archenteron",
				false,
				"However, the three-layered embryo does contain an archenteron.");
			
				p.addAnswer(2, "morula",
				false,
				"The morula is a solid ball of cells.");
			
				p.addAnswer(3, "trophoblast",
				false,
				"The trophoblast is a layer of cells surrounding the blastula.");
			
				p.addAnswer(4, "gastrula",
				true,
				"The gastrula, formed when the blastula undergoes gastrulation, is a ball of cells that consists of the three primary germ layers.");
			
				p.addAnswer(5, "blastula",
				false,
				"The blastula is a hollow ball of cells; it is not a three-layered embryo.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336716;


		
		

		
			
			p.question = "The _____ eventually develops into the sea urchin\'s digestive tract. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?47&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Sea Urchin Development</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "blastocoel",
				false,
				"The blastocoel is the hollow cavity of the blastula; it does not develop into the sea urchin\'s digestive tract.");
			
				p.addAnswer(2, "archenteron",
				true,
				"The archenteron, formed as a result of gastrulation, develops into the sea urchin\'s digestive tract.");
			
				p.addAnswer(3, "blastomere",
				false,
				"Blastomeres are cells that make up the blastula.");
			
				p.addAnswer(4, "ectoderm",
				false,
				"The ectoderm is the germ layer that, in vertebrates, gives rise to the outer layer of skin and the nervous system.");
			
				p.addAnswer(5, "blastopore",
				false,
				"The blastopore will become the sea urchin\'s anus.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336717;


		
		

		
			
			p.question = "During gastrulation, invagination occurs at the _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?47&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Sea Urchin Development</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "archenteron",
				false,
				"The archenteron, formed as a result of gastrulation, develops into the sea urchin\'s digestive tract.");
			
				p.addAnswer(2, "blastocoel",
				false,
				"The blastocoel is the hollow cavity of the blastula; it does not develop into the sea urchin\'s digestive tract.");
			
				p.addAnswer(3, "endometrium",
				false,
				"The endometrium is the layer of the uterus where implantation takes place.");
			
				p.addAnswer(4, "blastopore",
				true,
				"During gastrulation, invagination occurs at the blastopore, which develops into the sea urchin\'s anus.");
			
				p.addAnswer(5, "trophoblast",
				false,
				"The trophoblast is a layer of cells surrounding the blastula.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336718;


		
		

		
			
			p.question = "In vertebrates, the ectoderm gives rise to the _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?47&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Sea Urchin Development</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "skeleton",
				false,
				"The mesoderm gives rise to the skeleton.");
			
				p.addAnswer(2, "circulatory system",
				false,
				"The mesoderm gives rise to the circulatory system.");
			
				p.addAnswer(3, "outer layer of skin",
				true,
				"The ectoderm gives rise to the outer layer of skin and the nervous system");
			
				p.addAnswer(4, "lining of the digestive tract",
				false,
				"The endoderm gives rise to the lining of the digestive tract.");
			
				p.addAnswer(5, "pancreas",
				false,
				"The endoderm gives rise to the pancreas.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336719;


		
		

		
			
			p.question = "During gastrulation in frogs, a rod of mesoderm under the dorsal surface forms the _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?47&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Frog Development</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "notochord",
				true,
				"This rod of mesoderm forms the notochord, a physically supportive structure.");
			
				p.addAnswer(2, "ectoderm",
				false,
				"Gastrulation forms the three germ layers (ectoderm, mesoderm, and endoderm); none of the layers forms any of the other layers.");
			
				p.addAnswer(3, "endoderm",
				false,
				"Gastrulation forms the three germ layers (ectoderm, mesoderm, and endoderm); none of the layers forms any of the other layers.");
			
				p.addAnswer(4, "archenteron",
				false,
				"The archenteron, a hollow tube that develops into the frog\'s digestive tract, forms as a result of gastrulation.");
			
				p.addAnswer(5, "blastopore",
				false,
				"During gastrulation, the blastopore is the site of invagination; later it develops into the frog\'s anus.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336720;


		
		

		
			
			p.question = "During gastrulation in frogs, cells from the animal pole spread over the embryo and form the _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?47&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Frog Development</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "endoderm",
				false,
				"Cells from the vegetal pole form the endoderm.");
			
				p.addAnswer(2, "ectoderm",
				true,
				"Cells from the animal pole form the ectoderm.");
			
				p.addAnswer(3, "archenteron",
				false,
				"The archenteron, a hollow tube that develops into the frog\'s digestive tract, is lined with endoderm, which originates with cells from the vegetal pole.");
			
				p.addAnswer(4, "blastopore",
				false,
				"During gastrulation, the blastopore is the site of invagination; later it develops into the frog\'s anus.");
			
				p.addAnswer(5, "blastula",
				false,
				"Gastrulation converts the blastula to the gastrula.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336721;


		
		

		
			
			p.question = "The notochord functions as a core around which mesodermal cells form the frog\'s _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?47&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Frog Development</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "backbone",
				true,
				"In vertebrates, the notochord functions as a core around which mesodermal cells form the frog\'s backbone.");
			
				p.addAnswer(2, "blastopore",
				false,
				"During gastrulation, the blastopore is the site of invagination; later it develops into the frog\'s anus.");
			
				p.addAnswer(3, "endometrium",
				false,
				"The endometrium is the inner lining of the uterus; frogs lack uteri.");
			
				p.addAnswer(4, "nervous system",
				false,
				"The nervous system forms from ectoderm.");
			
				p.addAnswer(5, "archenteron",
				false,
				"The archenteron, a hollow tube that develops into the frog\'s digestive tract, forms as a result of gastrulation.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336722;


		
		

		
			
			p.question = "An ectodermal thickening above the frog\'s notochord forms a _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?47&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Frog Development</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "pancreas",
				false,
				"The pancreas is mesodermal in origin.");
			
				p.addAnswer(2, "neural plate",
				true,
				"The ectodermal thickening above the frog\'s notochord forms the neural plate.");
			
				p.addAnswer(3, "skeleton",
				false,
				"The skeleton is mesodermal in origin.");
			
				p.addAnswer(4, "liver",
				false,
				"The liver is endodermal in origin.");
			
				p.addAnswer(5, "lining of the stomach",
				false,
				"The lining of the stomach is endodermal in origin.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336723;


		
		

		
			
			p.question = "The _____ is(are) formed when the neural folds join and a portion of the neural plate sinks beneath the embryo\'s surface. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?47&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Frog Development</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "archenteron",
				false,
				"The archenteron, a hollow tube that develops into the frog\'s digestive tract, forms as a result of gastrulation.");
			
				p.addAnswer(2, "anus",
				false,
				"In frogs the anus forms from the blastopore, the point at which invagination occurs during gastrulation.");
			
				p.addAnswer(3, "back muscles",
				false,
				"Back muscles are mesodermal in origin; the neural fold in ectodermal in origin.");
			
				p.addAnswer(4, "neural tube",
				true,
				"The question describes the formation of the neural tube.");
			
				p.addAnswer(5, "digestive system",
				false,
				"The digestive system forms from the archenteron.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336724;


		
		

		
			
			p.question = "The enlarged anterior portion of the neural tube will develop into a frog\'s _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?47&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Frog Development</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "spinal cord",
				false,
				"The posterior end of the neural tube develops into the spinal cord.");
			
				p.addAnswer(2, "tongue",
				false,
				"The tongue is a muscle and as such is mesodermal in origin; the neural tube is ectodermal in origin.");
			
				p.addAnswer(3, "reproductive system",
				false,
				"The reproductive system is endodermal in origin; the neural tube is ectodermal in origin.");
			
				p.addAnswer(4, "outer layer of skin",
				false,
				"Although, like the neural tube, the outer layer of skin is ectodermal in origin, the neural tube does not develop into the outer layer of skin.");
			
				p.addAnswer(5, "brain",
				true,
				"The anterior end of the neural tube develops into the brain.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336725;


		
		

		
			
			p.question = "The posterior portion of the neural tube will develop into the frog\'s _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?47&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Frog Development</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "spinal cord",
				true,
				"The posterior portion of the neural tube develops into the spinal cord.");
			
				p.addAnswer(2, "brain",
				false,
				"The anterior portion of the neural tube develops into the brain.");
			
				p.addAnswer(3, "blastocoel",
				false,
				"The blastocoel is the hollow cavity of the blastula. The neural tube forms during organogenesis (organ formation), which occurs after the formation of a gastrula from a blastula.");
			
				p.addAnswer(4, "digestive tract",
				false,
				"The archenteron develops into the digestive tract.");
			
				p.addAnswer(5, "anus",
				false,
				"The blastopore develops into the frog\'s anus.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

