

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "31: Fungi > Activities Quiz";
	ak.quiz_loc_with_commas = "31: Fungi, Activities Quiz";
	ak.quiz_title = "Activities Quiz";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 15;
	ak.non_essay_total = 15;
	ak.scored_item_total = 15;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335838;


		
		

		
			
			p.question = "As a group, fungi are _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?31&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Fungal Reproduction and Nutrition</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "photoautotrophs",
				false,
				"Fungi do not make direct use of light as an energy source.");
			
				p.addAnswer(2, "decomposers",
				true,
				"Fungi obtain nutrients from nonliving organic matter.");
			
				p.addAnswer(3, "herbivores",
				false,
				"There is a better answer.");
			
				p.addAnswer(4, "carnivores",
				false,
				"There is a better answer.");
			
				p.addAnswer(5, "chemoautotrophs",
				false,
				"Fungi do not synthesize their own organic compounds from inorganic compounds.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335839;


		
		

		
			
			p.question = "Fungi release digestive enzymes into their _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?31&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Fungal Reproduction and Nutrition</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "surroundings",
				true,
				"Fungi then absorb the digested nutrients.");
			
				p.addAnswer(2, "gastrovascular cavity",
				false,
				"Fungi do not have a gastrovascular cavity.");
			
				p.addAnswer(3, "stomach",
				false,
				"Fungi do not have a stomach.");
			
				p.addAnswer(4, "hyphae",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(5, "mycelia",
				false,
				"A mycelium is the body of a fungus.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335840;


		
		

		
			
			p.question = "Basidia produce spores by a process known as _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?31&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Fungal Reproduction and Nutrition</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "decomposition",
				false,
				"Nutritionally, fungi are decomposers.");
			
				p.addAnswer(2, "mitosis",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(3, "meiosis",
				true,
				"Basidia produce spores by meiosis.");
			
				p.addAnswer(4, "hyphae",
				false,
				"Hyphae are a fungal structure.");
			
				p.addAnswer(5, "binary fission",
				false,
				"Bacteria reproduce by binary fission.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335841;


		
		

		
			
			p.question = "Fungi produce _____ spores. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?31&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Fungal Life Cycles</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "dikaryotic",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(2, "heterokaryotic",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(3, "haploid",
				true,
				"Fungal spores are haploid.");
			
				p.addAnswer(4, "diploid",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(5, "triploid",
				false,
				"No, that is incorrect.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335842;


		
		

		
			
			p.question = "Karyogamy produces a _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?31&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Fungal Life Cycles</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "diploid zygote",
				true,
				"Karyogamy is the fusion of nuclei.");
			
				p.addAnswer(2, "haploid zygote",
				false,
				"Fungal zygotes are diploid.");
			
				p.addAnswer(3, "spores",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(4, "mycelium",
				false,
				"Mycelia are produced when spores germinate.");
			
				p.addAnswer(5, "hypha",
				false,
				"Hyphae are produced when spores germinate.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335843;


		
		

		
			
			p.question = "Plasmogamy is indicated by the letter _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?31&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Fungal Life Cycles</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/3106q.jpg\" ALT=\"Question #6\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A",
				false,
				"This is germination.");
			
				p.addAnswer(2, "B",
				true,
				"Plasmogamy is the fusion of hyphae.");
			
				p.addAnswer(3, "C",
				false,
				"Karyogamy is the fusion of nuclei.");
			
				p.addAnswer(4, "D",
				false,
				"Zygotes produce spores by meiosis.");
			
				p.addAnswer(5, "E",
				false,
				"The germination of a spore produces a mycelium.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335844;


		
		

		
			
			p.question = "Which of these contains two haploid nuclei? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?31&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Fungal Life Cycles</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the heterokaryotic stage of the fungal life cycle",
				true,
				"The heterokaryotic stage is produced by plasmogamy.");
			
				p.addAnswer(2, "zygote",
				false,
				"Each cell of a zygote is diploid.");
			
				p.addAnswer(3, "spore-producing structures",
				false,
				"The cells of spore-producing structures each contain a single haploid nucleus.");
			
				p.addAnswer(4, "mycelium",
				false,
				"Mycelial cells contain a single haploid nucleus.");
			
				p.addAnswer(5, "hypha",
				false,
				"Hyphal cells contain a single haploid nucleus.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335845;


		
		

		
			
			p.question = "Zygosporangia are _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?31&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Fungal Life Cycles</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "diploid",
				false,
				"Zygotes are produced by karyogamy.");
			
				p.addAnswer(2, "haploid",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(3, "heterokaryotic",
				true,
				"Zygosporangia are produced by plasmogamy.");
			
				p.addAnswer(4, "haplodiploid",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(5, "either haploid or diploid, depending on the type of fungus",
				false,
				"Fungi that belong to the phylum Zygomycota produce zygosporangia.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335846;


		
		

		
			
			p.question = "The process indicated by the letter _____ produces a diploid structure. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?31&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Fungal Life Cycles</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/3109q.jpg\" ALT=\"Question #9\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A",
				false,
				"Spores germinate to produce mycelia.");
			
				p.addAnswer(2, "B",
				false,
				"Plasmogamy produces a heterokaryotic structure.");
			
				p.addAnswer(3, "C",
				true,
				"Karyogamy produces a diploid zygote.");
			
				p.addAnswer(4, "D",
				false,
				"Zygotes produce haploid sporangia.");
			
				p.addAnswer(5, "E",
				false,
				"Spores germinate to produce mycelia.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335847;


		
		

		
			
			p.question = "Cup fungi are in the phylum _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?31&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Fungal Life Cycles</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Zygomycota",
				false,
				"Cup fungi are not classified as zygote fungi.");
			
				p.addAnswer(2, "Chytridomycota",
				false,
				"These are flagellated, mainly aquatic, fungi.");
			
				p.addAnswer(3, "Ascomycota",
				true,
				"Cup fungi are a type of sac fungus.");
			
				p.addAnswer(4, "Chordata",
				false,
				"You are a chordate.");
			
				p.addAnswer(5, "Basidiomycota",
				false,
				"Basidiomycota are club fungi.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335848;


		
		

		
			
			p.question = "Which of these structures bears asci? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?31&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Fungal Life Cycles</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/3111q.jpg\" ALT=\"Question #11\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A",
				false,
				"This is a mycelium.");
			
				p.addAnswer(2, "B",
				false,
				"This is an ascogonium.");
			
				p.addAnswer(3, "C",
				false,
				"This is an antheridium.");
			
				p.addAnswer(4, "D",
				true,
				"Ascocarps bear asci.");
			
				p.addAnswer(5, "E",
				false,
				"This is an ascus.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335849;


		
		

		
			
			p.question = "In sac fungi, karyogamy and meiosis occur in _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?31&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Fungal Life Cycles</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "ascospores",
				false,
				"Ascospores are produced when karyogamy is followed by meiosis.");
			
				p.addAnswer(2, "antheridia",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(3, "asci",
				true,
				"Karyogamy and meiosis in asci produce ascospores.");
			
				p.addAnswer(4, "ascogonia",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(5, "basidia",
				false,
				"Sac fungi do not bear basidia.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335850;


		
		

		
			
			p.question = "A nucleus within an ascus undergoes meiosis, producing four haploid spores, which then undergo mitosis, producing eight haploid ascospores. These haploid ascospores contain a maximum of _____ different genetic types. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?31&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Fungal Life Cycles</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "one",
				false,
				"You need to review the processes of mitosis and meiosis.");
			
				p.addAnswer(2, "two",
				false,
				"You need to review the processes of meiosis and mitosis.");
			
				p.addAnswer(3, "three",
				false,
				"You need to review the processes of mitosis and meiosis.");
			
				p.addAnswer(4, "four",
				true,
				"Meiosis of a diploid cell produces four genetically different cells. A cell that undergoes mitosis produces two genetically identical daughter cells.");
			
				p.addAnswer(5, "five",
				false,
				"You need to review the processes of meiosis and mitosis.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335851;


		
		

		
			
			p.question = "Which of these is a basidiocarp? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?31&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Fungal Life Cycles</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/3114q.jpg\" ALT=\"Question #14\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A",
				false,
				"This is a basidium.");
			
				p.addAnswer(2, "B",
				false,
				"These are mycelia.");
			
				p.addAnswer(3, "C",
				false,
				"This is a dikaryotic mycelium.");
			
				p.addAnswer(4, "D",
				true,
				"A mushroom is a basidiocarp.");
			
				p.addAnswer(5, "E",
				false,
				"These nuclei are diploid; basidiocarps are dikaryotic.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335852;


		
		

		
			
			p.question = "In club fungi, karyogamy and meiosis occur in _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?31&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Fungal Life Cycles</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "basidiospores",
				false,
				"Karyogamy and meiosis produce basidiospores.");
			
				p.addAnswer(2, "basidia",
				true,
				"Karyogamy and meiosis in basidia produce basidiospores.");
			
				p.addAnswer(3, "ovule",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(4, "asci",
				false,
				"Club fungi do not bear asci.");
			
				p.addAnswer(5, "zygotes",
				false,
				"Club fungi are not in the phylum Zygomycota.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

