

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "3: Water and the Fitness of the Environment > Practice Test";
	ak.quiz_loc_with_commas = "3: Water and the Fitness of the Environment, Practice Test";
	ak.quiz_title = "Practice Test";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 40;
	ak.non_essay_total = 40;
	ak.scored_item_total = 40;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334134;


		
		

		
			
			p.question = "Cells are surrounded by water, and cells themselves consist of about 70% to 95% water. As a result _____. (<script type=\"text/javascript\">ebook(\'0301\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the temperature of living things tends to change relatively slowly",
				false,
				"No. The above statement is correct, but it is not the only true statement.");
			
				p.addAnswer(2, "a variety of nutrient molecules are readily available as dissolved solutes",
				false,
				"No. The above statement is correct, but it is not the only true statement.");
			
				p.addAnswer(3, "waste products produced by cell metabolism can be easily removed",
				false,
				"No. The above statement is correct, but it is not the only true statement.");
			
				p.addAnswer(4, "dissolved substances can be easily transported within a cell or between cells in multicellular organisms",
				false,
				"No. The above statement is correct, but it is not the only true statement.");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct. All of the above result from the extraordinary characteristics of water.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334135;


		
		

		
			
			p.question = "Water is a polar molecule. This means that _____. (<script type=\"text/javascript\">ebook(\'0301\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the opposite ends of the molecule have opposite electrical charges",
				true,
				"Correct. In the case of water, the oxygen is slightly negative and the hydrogen atoms are slightly positive.");
			
				p.addAnswer(2, "water molecules are linear, like a pole",
				false,
				"No. Remember that water molecules are shaped somewhat like a wide V.");
			
				p.addAnswer(3, "water is one of the many hydrophobic molecules",
				false,
				"No. Hydrophobic molecules are nonpolar and do not mix with water.");
			
				p.addAnswer(4, "the atoms in water have equal electronegativities",
				false,
				"No. When equally electronegative atoms bond, the electrons are shared equally between them, forming a nonpolar bond.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. There is one correct answer.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334136;


		
		

		
			
			p.question = "The partial charges on a water molecule occur because of _____. (<script type=\"text/javascript\">ebook(\'0301\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the unequal sharing of electrons between the hydrogen and the oxygen atoms of a water molecule",
				true,
				"Correct. Because oxygen is more electronegative than hydrogen, electrons of the polar bond spend more time closer to the oxygen atom, resulting in a slight negative charge on the oxygen atom and slight positive charges on the hydrogen atoms.");
			
				p.addAnswer(2, "the achievement of a stable configuration by one atom of a bond but not by the other partner",
				false,
				"No. The entire water molecule is stabilized by covalent bonds joining the oxygen to the two hydrogens. However, the bonds are polar covalent, resulting in a polar molecule.");
			
				p.addAnswer(3, "covalent bonding",
				false,
				"No. Consider the nature of the covalent bonds found within a water molecule.");
			
				p.addAnswer(4, "widespread ionization",
				false,
				"No. However, the partial charges on a water molecule contribute to its ability to dissociate.");
			
				p.addAnswer(5, "the high electronegativity of hydrogen",
				false,
				"No. Hydrogen is not highly electronegative, and it is less electronegative than oxygen.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334137;


		
		

		
			
			p.question = "In a group of water molecules, hydrogen bonds form between _____. (<script type=\"text/javascript\">ebook(\'0301\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "two hydrogen atoms in different water molecules",
				false,
				"No. Two hydrogen atoms would have the same electronegativity.");
			
				p.addAnswer(2, "the oxygen atoms in different water molecules",
				false,
				"No. Two oxygen atoms would have the same electronegativity.");
			
				p.addAnswer(3, "the oxygen atom in one water molecule and a hydrogen atom in another water molecule",
				true,
				"Correct. The slightly negatively charged region of an oxygen atom of one water molecule is attracted to the slightly positively charged region of a hydrogen atom of another water molecule.");
			
				p.addAnswer(4, "the hydrogen atoms in a single water molecule",
				false,
				"No. Two hydrogen atoms would have the same electronegativity.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334138;


		
		

		
			
			p.question = "The tendency of water molecules to stay close to each other as a result of hydrogen bonding _____. (<script type=\"text/javascript\">ebook(\'0302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "provides the surface tension that allows leaves to float on water",
				false,
				"No. This is correct because the cohesiveness of water creates a filmlike surface that supports leaves, but it is not the only correct answer.");
			
				p.addAnswer(2, "is called cohesion",
				false,
				"No. This answer is correct because cohesion is the right term, but it is not the only correct answer.");
			
				p.addAnswer(3, "keeps water moving through the vessels in a tree trunk",
				false,
				"No. This is correct because hydrogen bonding is instrumental in the movement of water through a tree\'s vessels, but it is not the only correct answer.");
			
				p.addAnswer(4, "acts to moderate temperature",
				false,
				"No. This is correct because temperatures are moderated by the amount of heat needed to evaporate water, but it is not the only correct answer.");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct. All of the choices reflect results of the cohesiveness of water molecules.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334139;


		
		

		
			
			p.question = "What do cohesion, surface tension, and adhesion have in common with reference to water? (<script type=\"text/javascript\">ebook(\'0302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "All are results of the structure of the hydrogen atom.",
				false,
				"No. However, the nature of hydrogen is relevant to the answer.");
			
				p.addAnswer(2, "All are produced by covalent bonding.",
				false,
				"No. It is true that the atoms of a water molecule are bonded together by covalent bonds. However, the properties in question refer to the electrical attraction between something and a water molecule or between water molecules.");
			
				p.addAnswer(3, "All are properties related to hydrogen bonding.",
				true,
				"Correct. The extraordinary qualities of water are emergent properties resulting from hydrogen bonding.");
			
				p.addAnswer(4, "All have to do with ionic interactions.",
				false,
				"No. A water molecule is not an ion.");
			
				p.addAnswer(5, "All are aspects of a crystalline structure.",
				false,
				"No. These properties are not aspects of a crystalline structure. The properties in question refer to the electrical attraction between something and a water molecule or between water molecules.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334140;


		
		

		
			
			p.question = "Most of water\'s unique features (for example, its versatility as a solvent, ability to moderate temperature, and cohesive behavior) result from the fact that _____. (<script type=\"text/javascript\">ebook(\'0302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "hydrogen is the only element without any neutrons",
				false,
				"No. Other features of water need to be considered.");
			
				p.addAnswer(2, "oxygen attracts electrons more than hydrogen does",
				true,
				"Correct. Because oxygen is more electronegative than hydrogen, water molecules are polar and form hydrogen bonds that give water its extraordinary properties.");
			
				p.addAnswer(3, "oxygen has only one stable isotope, but hydrogen has three",
				false,
				"No. This does not relate to water\'s unique features.");
			
				p.addAnswer(4, "oxygen has two unfilled electron shells",
				false,
				"No. This is not a correct statement.");
			
				p.addAnswer(5, "More than one of the above is correct.",
				false,
				"No. There is only one correct answer.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334141;


		
		

		
			
			p.question = "The ability of water molecules to form hydrogen bonds with other water molecules and water\'s ability to dissolve substances that have charges or partial charges are _____. (<script type=\"text/javascript\">ebook(\'0302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "both caused by water\'s ability to form covalent bonds with hydrophobic substances",
				false,
				"No. Water does not form covalent bonds with hydrophobic substances.");
			
				p.addAnswer(2, "due to water\'s partial charges and low molecular mass, respectively",
				false,
				"No. This answer is only partially correct.");
			
				p.addAnswer(3, "both caused by water\'s partial charges",
				true,
				"Correct. Two molecules of water are held together by a hydrogen bond formed between the slight positive charge of the hydrogen and the slight negative charge of the oxygen. Water is a very versatile solvent, a quality traced to the polarity of the water molecule.");
			
				p.addAnswer(4, "both caused by water\'s two electron shells and the opposite spins of those shells",
				false,
				"No. Electron shells are a property of atoms.");
			
				p.addAnswer(5, "both due to water\'s low molecular mass",
				false,
				"No. Neither property of water can be attributed to its molecular mass.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334142;


		
		

		
			
			p.question = "The phenomenon responsible for the maintenance of a column of water as it moves upward through a vessel is _____. (<script type=\"text/javascript\">ebook(\'0302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "cohesion",
				true,
				"Correct. Cohesion is a consequence of hydrogen bonding between water molecules.");
			
				p.addAnswer(2, "adhesion",
				false,
				"No. Adhesion describes the attraction of different types of molecules to one another.");
			
				p.addAnswer(3, "surface tension",
				false,
				"No. But surface tension is related to the correct phenomenon. Surface tension is a measure of how difficult it is to stretch or break the surface of a liquid.");
			
				p.addAnswer(4, "evaporation",
				false,
				"No. Evaporation is the transformation from a liquid to a gas.");
			
				p.addAnswer(5, "heat of vaporization",
				false,
				"No. Heat of vaporization is the quantity of heat a liquid must absorb for 1 g of it to be converted from the liquid to the gaseous state.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334143;


		
		

		
			
			p.question = "Adhesion is best described as _____. (<script type=\"text/javascript\">ebook(\'0302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a property of water that helps moderate Earth\'s temperature",
				false,
				"No. This describes water\'s high heat of vaporization.");
			
				p.addAnswer(2, "the process by which a crystalline lattice forms",
				false,
				"No. A crystalline lattice forms when temperatures reach 0&#176;C and water freezes.");
			
				p.addAnswer(3, "the process that contributes to the transport of water and dissolved nutrients in plants by causing water molecules to tug on other water molecules",
				false,
				"No. This answer refers to cohesion.");
			
				p.addAnswer(4, "the clinging of one substance to another substance",
				true,
				"Correct. Adhesion is the attraction of one substance to another.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. There is one correct answer.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334144;


		
		

		
			
			p.question = "You can fill a glass of water to just slightly above the rim without it spilling over the glass. What property of water best explains this phenomenon? (<script type=\"text/javascript\">ebook(\'0302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "surface tension",
				true,
				"Correct. Water has a greater surface tension, a measure of how difficult it is to break the surface of a liquid, than most other liquids.");
			
				p.addAnswer(2, "adhesion",
				false,
				"No. This is the attraction of unlike substances.");
			
				p.addAnswer(3, "its polarity",
				false,
				"No. Although the property that is responsible for this phenomenon is a result of the polarity of water molecules, there is a better answer.");
			
				p.addAnswer(4, "evaporative cooling",
				false,
				"No. Evaporative cooling is the cooling of a liquid\'s surface as some of the liquid evaporates.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334145;


		
		

		
			
			p.question = "Which action would involve the greatest transfer of heat? (<script type=\"text/javascript\">ebook(\'0302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "changing the temperature of 1 g of water from 10&#176;C to 90&#176;C",
				false,
				"No. This would require only 80 calories.");
			
				p.addAnswer(2, "cooling 10 g of water from 80&#176;C to 40&#176;C",
				false,
				"No. This would release 400 calories.");
			
				p.addAnswer(3, "evaporating 1 g of water at 25&#176;C",
				false,
				"No. Evaporating 1 g of water requires about 580 calories.");
			
				p.addAnswer(4, "condensing 5 g of steam to liquid water",
				true,
				"Correct. This would release about 2,900 calories (580 calories/gram x 5 grams).");
			
				p.addAnswer(5, "raising the temperature of 10 g of ethyl alcohol by 25&#176;C",
				false,
				"No. The specific heat of alcohol is only 0.6 cal/g/&#176;C. This would require only 150 calories (0.6 cal/g/&#176;C x 10 g x 25&#176;C).");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334146;


		
		

		
			
			p.question = "Imagine that organisms consisted of 70-95% alcohol instead of 70-95% water. Alcohol\'s specific heat is about half that of water. How would living things be different? (<script type=\"text/javascript\">ebook(\'0302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Organisms would be able to live in a much wider range of temperatures.",
				false,
				"No. The high specific heat of water helps organisms resist changes in temperature, enabling them to live in a fairly wide range of temperature conditions. Fluids with a lower specific heat would restrict habitable temperature ranges.");
			
				p.addAnswer(2, "Systems for temperature regulation would have to be much more efficient.",
				true,
				"Correct. In order for living things to inhabit a wide range of environments, temperature regulation would need to be more efficient for a fluid with a lower specific heat.");
			
				p.addAnswer(3, "Living organisms would have to be much smaller.",
				false,
				"No. The opposite would probably be true. Larger size leads to a decrease in the ratio of surface area to volume, which would help conserve heat.");
			
				p.addAnswer(4, "Warm-blooded organisms would require less insulation such as fur or feathers.",
				false,
				"No. The opposite would be true. Temperature regulation systems such as insulation would need to be more efficient in order to make up for the low specific heat of alcohol.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. There is one correct answer.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334147;


		
		

		
			
			p.question = "The amount of heat required to change the temperature of 1 g of any substance by &#176;C is defined as _____. (<script type=\"text/javascript\">ebook(\'0302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the specific heat of that substance",
				true,
				"Correct. The specific heat of a substance is defined as the amount of heat that must be absorbed or lost to change the temperature of 1 g of that substance by <b>&#176;</b>C.");
			
				p.addAnswer(2, "1 calorie",
				false,
				"No. This answer applies specifically to water and is the amount of energy it takes to raise the temperature of 1 g of water by &#176;C.");
			
				p.addAnswer(3, "the heat of vaporization of that substance",
				false,
				"No. This is the amount of energy required to convert 1 g of a liquid to the gaseous state.");
			
				p.addAnswer(4, "1 kilocalorie",
				false,
				"No. This answer applies specifically to water and is the amount of energy it takes to raise the temperature of 1,000 g of water by &#176;C.");
			
				p.addAnswer(5, "molecular cohesion",
				false,
				"No. This refers to the tendency of like substances to stick together, not to an amount of energy.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334148;


		
		

		
			
			p.question = "The amount of heat required to convert 1 g of any substance from the liquid to the gaseous state is defined as _____. (<script type=\"text/javascript\">ebook(\'0302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the specific heat of that substance",
				false,
				"No. The specific heat of a substance is defined as the amount of heat required to change the temperature of 1 g of that substance by <b>&#176;</b>C.");
			
				p.addAnswer(2, "1 calorie",
				false,
				"No. This applies specifically to water and is the amount of energy it takes to raise the temperature of 1 g of water by &#176;C.");
			
				p.addAnswer(3, "the heat of vaporization of that substance",
				true,
				"Correct. Heat of vaporization is the quantity of heat a liquid must absorb for 1 g of it to be converted from the liquid to the gaseous state.");
			
				p.addAnswer(4, "the heat of fusion of that substance",
				false,
				"No. Heat of fusion is the heat required to convert a solid into a liquid with no temperature change. This topic was not covered in Chapter 3.");
			
				p.addAnswer(5, "molecular cohesion",
				false,
				"No. This refers to the tendency of like substances to stick together, not to an amount of energy.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334149;


		
		

		
			
			p.question = "The reason that coastal climates are more moderate than inland climates is due primarily to water\'s high _____. (<script type=\"text/javascript\">ebook(\'0302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "heat of fusion",
				false,
				"No. Heat of fusion is the heat required to convert a solid into a liquid with no temperature change. This topic was not covered in Chapter 3.");
			
				p.addAnswer(2, "surface tension",
				false,
				"No. This relates to water\'s cohesion.");
			
				p.addAnswer(3, "heat of vaporization",
				false,
				"No. Heat of vaporization is the quantity of heat a liquid must absorb for 1 g of it to be converted from the liquid to the gaseous state.");
			
				p.addAnswer(4, "specific heat",
				true,
				"Correct. Because of its high specific heat, water\'s temperature will change less when it absorbs or loses a given amount of heat. Thus, the oceans can absorb and store a huge amount of heat and release it later when the temperature of the air has dropped.");
			
				p.addAnswer(5, "density",
				false,
				"No. Water\'s density is not related to this property of water.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334150;


		
		

		
			
			p.question = "Sweating has a cooling effect because of water\'s high _____. (<script type=\"text/javascript\">ebook(\'0302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Buffering capacity",
				false,
				"No. Buffers resist changes in pH but do not have an effect on water\'s cooling capacity.");
			
				p.addAnswer(2, "surface tension",
				false,
				"No. This relates to water\'s cohesion.");
			
				p.addAnswer(3, "heat of vaporization",
				true,
				"Correct. Water\'s high heat of vaporization results in evaporative cooling because when water evaporates, the surface of the water cools down.");
			
				p.addAnswer(4, "specific heat",
				false,
				"No. The specific heat of a substance is defined as the amount of heat required to change the temperature of 1 g of that substance by 1&#176;C.");
			
				p.addAnswer(5, "density",
				false,
				"No. Water\'s density is not related to this property of water.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334151;


		
		

		
			
			p.question = "Water molecules have _____ than molecules of similar size, such as ammonia and methane. (<script type=\"text/javascript\">ebook(\'0302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "lower specific heat",
				false,
				"No. Water has a high specific heat.");
			
				p.addAnswer(2, "a higher boiling point",
				true,
				"Correct. More heat is needed to vaporize 1 g of water than most other liquids.");
			
				p.addAnswer(3, "a lower melting point",
				false,
				"No. This is not an emergent property of water discussed in Chapter 3.");
			
				p.addAnswer(4, "a lower capacity for forming hydrogen bonds",
				false,
				"No. Water is a polar molecule and thus has a high capacity for forming hydrogen bonds.");
			
				p.addAnswer(5, "less surface tension",
				false,
				"No. Water molecules are very cohesive.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334152;


		
		

		
			
			p.question = "Because molecules of water are farther apart in ice than in liquid water, _____. (<script type=\"text/javascript\">ebook(\'0302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "ice floats",
				true,
				"Correct. Because water molecules in ice are farther apart than in liquid water, ice is less dense, and therefore, it floats.");
			
				p.addAnswer(2, "ice is denser than liquid water",
				false,
				"No. If the molecules are farther apart, the ice is less dense than liquid water.");
			
				p.addAnswer(3, "ice expands when it melts",
				false,
				"No. Water expands when it freezes into ice, because the molecules are farther apart.");
			
				p.addAnswer(4, "ice vaporizes before liquid water does",
				false,
				"No. It takes heat to go from solid ice to liquid water and then to vaporization.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. One of the above is a correct response.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334153;


		
		

		
			
			p.question = "Water is a very versatile solvent because water molecules are_____. (<script type=\"text/javascript\">ebook(\'0302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "polar",
				true,
				"Correct. Because molecules of polar solvents have a positive and a negative pole, polar solvents are excellent solvents for ions and for other polar materials.");
			
				p.addAnswer(2, "nonpolar",
				false,
				"No. Most of the solutions we encounter are aqueous solutions.");
			
				p.addAnswer(3, "ionic",
				false,
				"No. Ions exist only in solution.");
			
				p.addAnswer(4, "hydrophobic",
				false,
				"No. Hydrophobic molecules have a prevalence of nonpolar covalent bonds; thus, they are nonpolar molecules.");
			
				p.addAnswer(5, "volatile",
				false,
				"No. This would have no bearing on solubilization.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334154;


		
		

		
			
			p.question = "How does the polarity of water contribute to its ability to dissolve so many substances? (<script type=\"text/javascript\">ebook(\'0302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Water\'s polarity allows it to form covalent bonds with many substances",
				false,
				"No. Covalent bonding is not involved in solubility.");
			
				p.addAnswer(2, "Natural water has a pH of approximately 5.6, which is slightly acidic. Acids can dissolve more substances than bases.",
				false,
				"No. The pH affects the types of substances that water can effectively dissolve, but it does not explain the role of water\'s polarity.");
			
				p.addAnswer(3, "Because it is polar, water\'s oppositely charge ends are attracted to positively and negatively charged ions and molecules. Water molecules form a hydration shell around oppositely charged particles.",
				true,
				"Correct. Polar water molecules surround the individual ions or charged molecules, separating and shielding the ions or molecules from one another.");
			
				p.addAnswer(4, "Because it is polar, water forms ionic bonds with the ions in substances such as NaCl (salt).",
				false,
				"No. Water\'s polarity leads to the formation of hydrogen bonds, not ionic bonds.");
			
				p.addAnswer(5, "Because it is polar, water is able to interact with and dissolve hydrophobic substances.",
				false,
				"No. Hydrophobic substances are nonpolar and do not interact with or dissolve in water.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334155;


		
		

		
			
			p.question = "Nonpolar molecules that cluster away from water molecules are called _____ molecules. (<script type=\"text/javascript\">ebook(\'0302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "ionic",
				false,
				"No. Ions are attracted to water.");
			
				p.addAnswer(2, "hydrophilic",
				false,
				"No. The suffix \"-philic\" means \"loving.\"");
			
				p.addAnswer(3, "hydrophobic",
				true,
				"Correct. Substances that are non-ionic and nonpolar repel water.");
			
				p.addAnswer(4, "saponified",
				false,
				"No. When something is saponified, it is converted into a soap.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334156;


		
		

		
			
			p.question = "A molecule that has all nonpolar covalent bonds would be _____. (<script type=\"text/javascript\">ebook(\'0302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "hydrophobic",
				true,
				"Correct. For example, the hydrophobic behavior of oil molecules results from a prevalence of nonpolar covalent bonds. Nonpolar molecules do not have an affinity for water or other polar molecules.");
			
				p.addAnswer(2, "hydrophilic",
				false,
				"No. Hydrophilic substances have an affinity for water. They are polar molecules as a result of an unequal sharing of electrons, or they are electrically charged ions resulting from the gain or loss of an electron(s). A molecule with all nonpolar bonds would not have an affinity for water and therefore would not be hydrophilic.");
			
				p.addAnswer(3, "acidic",
				false,
				"No. Acidic refers to the hydrogen ion concentration of a solution, not to the affinity or lack of affinity a substance has for water. Polar and ionic substances have an affinity for water; nonpolar substances tend to repel water.");
			
				p.addAnswer(4, "basic (alkaline)",
				false,
				"No. Basic refers to the hydrogen ion concentration of a solution, not to the affinity or lack of affinity a substance has for water. Polar and ionic substances have an affinity for water; nonpolar substances tend to repel water.");
			
				p.addAnswer(5, "ionic",
				false,
				"No. Ionic refers to the positive or negative charge of a substance due to the loss or gain of an electron(s). A molecule with all nonpolar bonds would tend to repel a polar molecule such as water.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334157;


		
		

		
			
			p.question = "Hydrophobic molecules are _____ water. (<script type=\"text/javascript\">ebook(\'0302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "attracted to",
				false,
				"No. Hydrophilic substances are attracted to water.");
			
				p.addAnswer(2, "absorbed by",
				false,
				"No. The term \"absorbed\" is not appropriate to this situation.");
			
				p.addAnswer(3, "repelled by",
				true,
				"Correct. Substances that are non-ionic and nonpolar repel water and are termed hydrophobic.");
			
				p.addAnswer(4, "neutralized by",
				false,
				"No. Hydrophobic substances are not easily mixed with hydrophilic substances.");
			
				p.addAnswer(5, "polarized by",
				false,
				"No. Hydrophobic substances are nonpolar.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334158;


		
		

		
			
			p.question = "Why are cell membranes composed primarily of hydrophobic molecules? (<script type=\"text/javascript\">ebook(\'0302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "In order to perform their function of separating the aqueous solutions outside of cells from the aqueous solutions inside of cells, cell membranes cannot be soluble in water.",
				true,
				"Correct. If cell membranes were hydrophilic, they would break down and dissolve in the presence of water, rendering them useless as a barrier.");
			
				p.addAnswer(2, "Cell membranes must be composed of polar molecules in order to interact with the aqueous solutions inside of cells.",
				false,
				"No. Hydrophobic molecules are nonpolar. They should not be able to interact strongly with aqueous solutions inside the cell because the cell membrane would break down.");
			
				p.addAnswer(3, "In order to maintain a proper pH, cell membranes must be hydrophobic.",
				false,
				"No. The hydrophobicity of the molecules does not affect pH.");
			
				p.addAnswer(4, "Cell membranes must be hydrophobic in order to form colloids.",
				false,
				"No. Colloids are formed when large, polar molecules are suspended in water.");
			
				p.addAnswer(5, "Cell membranes must be composed of nonpolar molecules in order to form a hydration shell around the cell.",
				false,
				"No. Hydration shells form when ionic substances dissolve in water, which is a polar molecule.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334159;


		
		

		
			
			p.question = "Hydrophilic substances, but not hydrophobic substances, _____. (<script type=\"text/javascript\">ebook(\'0302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "have charges and partial charges to which water molecules can adhere",
				true,
				"Correct. Hydrophilic substances are water loving and have an affinity for water. There is an unequal sharing of electrons resulting in a polar molecule, or there is the gain or loss of an electron(s) resulting in the formation of negatively and positively charged ions.");
			
				p.addAnswer(2, "have a higher bond energy than water",
				false,
				"No. The terms do not relate to energy, but rather to the solubility of a substance in water. In hydrophilic substances there is an unequal sharing of electrons resulting in a polar molecule, or there is the gain or loss of an electron(s) resulting in the formation of negatively and positively charged ions. Polar and ionic substances have an affinity for water; nonpolar substances tend to repel water.");
			
				p.addAnswer(3, "give up electrons to solvents",
				false,
				"No. There is no loss of electrons to the solvent. In hydrophilic substances there is an unequal sharing of electrons resulting in a polar molecule, or there is the gain or loss of an electron(s) resulting in the formation of negatively and positively charged ions. Polar and ionic substances have an affinity for water; nonpolar substances tend to repel water.");
			
				p.addAnswer(4, "accept electrons from solvents",
				false,
				"No. There is no gain of electrons to the solvent. In hydrophilic substances there is an unequal sharing of electrons resulting in a polar molecule, or there is the gain or loss of an electron(s) resulting in the formation of negatively and positively charged ions. Polar and ionic substances have an affinity for water; nonpolar substances tend to repel water.");
			
				p.addAnswer(5, "are repelled by water",
				false,
				"No. In hydrophilic substances there is an unequal sharing of electrons resulting in a polar molecule, or there is the gain or loss of an electron(s) resulting in the formation of negatively and positively charged ions. Polar and ionic substances have an affinity for water; nonpolar substances tend to repel water.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334160;


		
		

		
			
			p.question = "Some substances, such as oil and gasoline, will not dissolve in water because _____. (<script type=\"text/javascript\">ebook(\'0302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "their molecules are so large",
				false,
				"No. Some large molecules can dissolve in water.");
			
				p.addAnswer(2, "their molecules have no charges or partial charges to which water molecules can adhere",
				true,
				"Correct. The hydrophobic behavior of oil and gasoline molecules results from a prevalence of nonpolar covalent bonds between carbon and hydrogen.");
			
				p.addAnswer(3, "they do not ionize",
				false,
				"No. Consider the type of chemical bonding within oil and gasoline molecules.");
			
				p.addAnswer(4, "their electrons are so stable that they do not exchange atoms with water molecules",
				false,
				"No. A substance does not exchange atoms with water when it dissolves.");
			
				p.addAnswer(5, "oil and gasoline are organic compounds",
				false,
				"No. Glucose and sucrose are also organic substances, and they do dissolve in water.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334161;


		
		

		
			
			p.question = "Sucrose has a molecular mass of 342 daltons. To make a 2-molar (2 <i>M</i>) solution of sucrose, _____. (<script type=\"text/javascript\">ebook(\'0302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "stir 342 g of sucrose in water to dissolve the sugar, and then add enough water to bring the total volume of the solution to 1 L",
				false,
				"No. This would produce a 1-molar (1 <i>M</i>) solution.");
			
				p.addAnswer(2, "stir 684 g of sucrose in water to dissolve the sugar, and then add enough water to bring the total volume of the solution up to 2 L",
				false,
				"No. This would produce a 1-molar (1 <i>M</i>) solution.");
			
				p.addAnswer(3, "stir 684 g of sucrose in water to dissolve the sugar, and then add enough water to bring the total volume of the solution up to 0.5 L",
				false,
				"No. This would produce a 4-molar (4 <i>M</i>) solution.");
			
				p.addAnswer(4, "stir 342 g of sucrose in water to dissolve the sugar, and then add enough water to bring the total volume of the solution up to 2 L",
				false,
				"No. This would produce a 0.5-molar (0.5 <i>M</i>) solution.");
			
				p.addAnswer(5, "stir 342 g of sucrose in water to dissolve the sugar, and then add enough water to bring the total volume of the solution up to 0.5 L",
				true,
				"Correct. Or you could stir 684 g of sucrose in water to dissolve the sugar, and then add enough water to bring the total volume of the solution up to 1 L.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334162;


		
		

		
			
			p.question = "A mole of ethyl alcohol weighs 46 g. How many grams of ethyl alcohol are needed to produce 1 L of a 2-millimolar (2 <i>mM</i>) solution? (<script type=\"text/javascript\">ebook(\'0302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "92 g",
				false,
				"No. This would produce a 2 <i>M</i> or a 2,000 <i>mM</i> solution. Remember that \"milli-\" means thousandth.");
			
				p.addAnswer(2, "9.2 g",
				false,
				"No. This would produce a 0.2 <i>M</i> or a 200 <i>mM</i> solution.");
			
				p.addAnswer(3, "0.92 g",
				false,
				"No. This would produce a 0.02 <i>M</i> or a 20 <i>mM</i> solution.");
			
				p.addAnswer(4, "0.092 g",
				true,
				"Correct. This would produce a 0.002 <i>M</i> or a 2 <i>mM</i> solution.");
			
				p.addAnswer(5, "0.0092 g",
				false,
				"No. This would produce a 0.0002 <i>M</i> or a 0.2 <i>mM</i> solution.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334163;


		
		

		
			
			p.question = "An acid is _____. (<script type=\"text/javascript\">ebook(\'0303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "any compound with a pH",
				false,
				"No. pH can be measured in all liquids.");
			
				p.addAnswer(2, "any compound that accepts hydrogen ions",
				false,
				"No. A base accepts hydrogen ions.");
			
				p.addAnswer(3, "a material that resists changes in the pH of a solution",
				false,
				"No. A buffer resists pH changes.");
			
				p.addAnswer(4, "a compound that donates hydrogen ions to a solution",
				true,
				"Correct. An acid donates hydrogen ions to a solution.");
			
				p.addAnswer(5, "a solution with a pH between 7 and 14",
				false,
				"No. Acid solutions have a pH between 0 and 7.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334164;


		
		

		
			
			p.question = "Adding acid tends to ____ of a solution. (<script type=\"text/javascript\">ebook(\'0303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "increase the hydrogen ion concentration and raise the pH",
				false,
				"No. As the hydrogen ion concentration increases, the pH decreases.");
			
				p.addAnswer(2, "increase the hydrogen ion concentration and lower the pH",
				true,
				"Correct. Because pH is a negative log, its value is inversely proportional to the hydrogen ion concentration.");
			
				p.addAnswer(3, "decrease the hydrogen ion concentration and raise the pH",
				false,
				"No. Acids increase the hydrogen ion concentration; they do not lower it. Adding a base would produce the results indicated in this choice.");
			
				p.addAnswer(4, "decrease the hydrogen ion concentration and lower the pH",
				false,
				"No. Acids increase the hydrogen ion concentration.");
			
				p.addAnswer(5, "either increase or decrease the pH, depending on the original acidity",
				false,
				"No. Adding acid always increases the hydrogen ion concentration, decreasing the pH.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334165;


		
		

		
			
			p.question = "Which of the following dissociations is that of an acid? (<script type=\"text/javascript\">ebook(\'0303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "H<sub>2</sub>O &#8594; H<sup>+</sup> + OH<sup>-</sup>",
				false,
				"No. Although hydrogen ions are produced, hydroxyl ions are also produced in equal numbers.");
			
				p.addAnswer(2, "NaOH &#8594; Na<sup>+</sup> + OH<sup>-</sup>",
				false,
				"No. In this reaction no free hydrogen ion has been produced.");
			
				p.addAnswer(3, "HF &#8594; H<sup>+</sup> + F<sup>-</sup>",
				true,
				"Correct. Hydrofluoric acid (HF) dissociates into a hydrogen ion and a fluoride ion.");
			
				p.addAnswer(4, "NH<sub>3</sub> + H<sup>+</sup> &#8594; NH<sub>4</sub><sup>+</sup>",
				false,
				"No. This reaction reduces the concentration of hydrogen ions.");
			
				p.addAnswer(5, "KOH &#8594; K<sup>+</sup> + OH<sup>-</sup>",
				false,
				"No. In this reaction no free hydrogen ion has been produced.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334166;


		
		

		
			
			p.question = "A glass of grapefruit juice, at pH 3, contains _____ H<sup>+</sup> as a glass of tomato juice, at pH 4. (<script type=\"text/javascript\">ebook(\'0303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "one-tenth as much",
				false,
				"No. The pH scale is a base-10 logarithmic scale. Each unit represents a tenfold increase or decrease in the hydrogen ion concentration.");
			
				p.addAnswer(2, "half as much",
				false,
				"No. The pH scale is a base-10 logarithmic scale. Each unit represents a tenfold increase or decrease in the hydrogen ion concentration.");
			
				p.addAnswer(3, "twice as much",
				false,
				"No. The pH scale is a base-10 logarithmic scale. Each unit represents a tenfold increase or decrease in the hydrogen ion concentration.");
			
				p.addAnswer(4, "three times as much",
				false,
				"No. The pH scale is a base-10 logarithmic scale. Each unit represents a tenfold increase or decrease in the hydrogen ion concentration.");
			
				p.addAnswer(5, "ten times as much",
				true,
				"Correct. The pH scale is a base-10 logarithmic scale. The change from any pH value to the next smaller value represents a tenfold increase in the hydrogen ion concentration.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334167;


		
		

		
			
			p.question = "A solution at pH 6 contains ____ than the same amount of solution at pH 8. (<script type=\"text/javascript\">ebook(\'0303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "2 times more H<sup>+</sup>",
				false,
				"No. Remember that the pH scale is logarithmic.");
			
				p.addAnswer(2, "4 times more H<sup>+</sup>",
				false,
				"No. Remember that the pH scale is logarithmic.");
			
				p.addAnswer(3, "100 times more H<sup>+</sup>",
				true,
				"Correct. Each pH unit change represents a tenfold difference in the hydrogen ion concentration; thus 10 x 10 = 100.");
			
				p.addAnswer(4, "4 times less H<sup>+</sup>",
				false,
				"No. Remember that the pH scale is logarithmic.");
			
				p.addAnswer(5, "100 times less H<sup>+</sup>\n",
				false,
				"No. The pH value is inversely related to the hydrogen ion concentration.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334168;


		
		

		
			
			p.question = "Adding a base tends to _____ of a solution. (<script type=\"text/javascript\">ebook(\'0303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "lower the hydrogen ion concentration and lower the pH",
				false,
				"No. A lower pH means a higher hydrogen ion concentration.");
			
				p.addAnswer(2, "lower the hydrogen ion concentration and increase the pH",
				true,
				"Correct. A substance that reduces the hydrogen ion concentration is a base. Reducing the hydrogen ion concentration increases the pH.");
			
				p.addAnswer(3, "increase the hydrogen ion concentration and lower the pH",
				false,
				"No. This describes the result of adding an acid.");
			
				p.addAnswer(4, "increase the hydrogen ion concentration and increase the pH",
				false,
				"No. A higher pH means a lower hydrogen ion concentration.");
			
				p.addAnswer(5, "lower the hydroxide ion concentration and lower the pH",
				false,
				"No. An acid would lower the pH of a solution.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334169;


		
		

		
			
			p.question = "When the pH of a solution shifts from 7 to 3, how has the hydrogen ion concentration changed? (<script type=\"text/javascript\">ebook(\'0303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "It has increased by 4 times.",
				false,
				"No. Consider the logarithmic nature of the pH scale.");
			
				p.addAnswer(2, "It has decreased by 4 times.",
				false,
				"No. Consider the logarithmic nature of the pH scale. The lower the pH, the greater the hydrogen ion concentration of the solution.");
			
				p.addAnswer(3, "It has increased by 10,000 times.",
				true,
				"Correct. Because the pH number is the negative log of the hydrogen ion concentration, a change from a pH of 7 to a pH of 3 increases the hydrogen ion concentration by 10,000 times. (7 - 3 = 4; 10<sup>4</sup> = 10,000.)");
			
				p.addAnswer(4, "It has decreased by 10,000 times.",
				false,
				"No. pH is inversely related to the hydrogen ion concentration of a solution.");
			
				p.addAnswer(5, "It has not changed.",
				false,
				"No. pH changes with changes in hydrogen ion concentration.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334170;


		
		

		
			
			p.question = "Pure water has a pH of 7. Why does uncontaminated rainwater have a pH of 5.6? (<script type=\"text/javascript\">ebook(\'0303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "formation of carbonic acid from carbon dioxide and water",
				true,
				"Correct. The presence of carbonic acid in rain water causes it to have a lower pH than pure water.");
			
				p.addAnswer(2, "presence of sulfuric acid",
				false,
				"No. The presence of sulfur oxides may lower the pH even further than 5.6.");
			
				p.addAnswer(3, "presence of nitric acid",
				false,
				"No. The presence of nitrogen oxides may lower the pH even further than 5.6.");
			
				p.addAnswer(4, "burning of fossil fuels",
				false,
				"No. The burning of fossil fuels leads to an accumulation of sulfur and nitrogen oxides in the atmosphere, which contribute to the formation of acid rain rather than uncontaminated rain.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. There is one correct answer.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334171;


		
		

		
			
			p.question = "A substance that minimizes changes in the concentration of H<sup>+</sup> and OH<sup>-</sup> in a solution is a(n) ______. (<script type=\"text/javascript\">ebook(\'0303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "hydrocarbon",
				false,
				"No. Hydrocarbons are not soluble in aqueous solution. They cannot donate or accept hydrogen ions or hydroxide ions from solution; hence, hydrocarbons cannot maintain a relatively constant pH.");
			
				p.addAnswer(2, "buffer",
				true,
				"Correct. Buffers are substances that minimize changes in the concentration of hydrogen ions and hydroxide ions in a solution; therefore, buffers maintain a relatively constant pH.");
			
				p.addAnswer(3, "NaCl",
				false,
				"No. NaCl (salt) dissociates in water, but the sodium cation and chloride anion cannot accept or donate hydrogen ions or hydroxide ions to the solution and, therefore, cannot maintain a relatively constant pH.");
			
				p.addAnswer(4, "strong acid",
				false,
				"No. Strong acids dissociate almost completely in water and increase the H<sup>+ </sup>concentration of the resulting solution; therefore, they reduce the pH.");
			
				p.addAnswer(5, "strong base",
				false,
				"No. Strong bases dissociate almost completely in water and increase the OH<sup>-</sup> concentration of the resulting solution; therefore, they increase the pH.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334172;


		
		

		
			
			p.question = "Why is the increasing amount of carbon dioxide being taken up by the oceans a cause for concern? (<script type=\"text/javascript\">ebook(\'0303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The buffering action of carbonic acid (H<sub>2</sub>CO<sub>3</sub>) causes the pH of seawater to rise.",
				false,
				"No. Carbonic acid will lower the pH.");
			
				p.addAnswer(2, "More carbon dioxide causes an increase in carbonic acid (H<sub>2</sub>CO<sub>3</sub>) which leads to an increase in the concentration of carbonate ion (CO<sub>3</sub><sup>2-</sup>).",
				false,
				"No. The increase in carbon dioxide does cause an increase in carbonic acid. However, the increase in carbonic acid causes a decrease in the concentration of carbonate ion.");
			
				p.addAnswer(3, "More carbon dioxide causes an increase in carbonic acid (H<sub>2</sub>CO<sub>3</sub>) which leads to a decrease in the concentration of carbonate ion (CO<sub>3</sub><sup>2-</sup>).",
				true,
				"Correct. As seawater becomes more acidic, carbonate ion concentration decreases. The decrease in the availability of carbonate ion makes it more difficult for marine organisms to secrete calcium carbonate shells.");
			
				p.addAnswer(4, "There is no cause for concern. Carbonic acid (H<sub>2</sub>CO<sub>3</sub>) is an excellent buffer and will help keep the pH of seawater constant.",
				false,
				"No. When carbonic acid is present in equilibrium with bicarbonate ion, a buffer system exists. However, if carbonic acid is continually added to the system, the system is not in equilibrium.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the answers is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334173;


		
		

		
			
			p.question = "Which of the following statements is true about acid precipitation? (<script type=\"text/javascript\">ebook(\'0303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "It harms aquatic life, but has little effect on terrestrial life.",
				false,
				"No. Acid rain has negative effects on both land and water life.");
			
				p.addAnswer(2, "It washes away some minerals that are plant nutrients, while causing some toxic minerals to accumulate.",
				true,
				"Correct. Important plant nutrients such as calcium and magnesium may be washed away from the soil, while aluminum may build up to dangerous levels.");
			
				p.addAnswer(3, "Automobile use is the leading contributor to acid rain.",
				false,
				"No. Electrical power plants that burn coal produce more of these pollutants than any other single source.");
			
				p.addAnswer(4, "Industrial areas are hit hardest by acid rain.",
				false,
				"No. Winds carry the pollutants away, and acid rain may fall thousands of miles away from industrial centers.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

