

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "26: Phylogeny and The Tree of Life > Activities Quiz";
	ak.quiz_loc_with_commas = "26: Phylogeny and The Tree of Life, Activities Quiz";
	ak.quiz_title = "Activities Quiz";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 5;
	ak.non_essay_total = 5;
	ak.scored_item_total = 5;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335587;


		
		

		
			
			p.question = "A human is classified in domain _____ and kingdom _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?1&F','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Classification Schemes</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Eukarya ... Fungi",
				false,
				"Humans are not fungi.");
			
				p.addAnswer(2, "Eukarya ... Protista",
				false,
				"Humans are multicellular and are not algae.");
			
				p.addAnswer(3, "Eukarya ... Plantae",
				false,
				"Humans are not plants.");
			
				p.addAnswer(4, "Eukarya ... Animalia",
				true,
				"Humans are animals, and animals are eukaryotes.");
			
				p.addAnswer(5, "Bacteria ... Archaea",
				false,
				"Humans are not prokaryotes.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335588;


		
		

		
			
			p.question = "A rose bush is classified in domain _____ and kingdom _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?1&F','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Classification Schemes</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Eukarya ... Fungi",
				false,
				"A rose bush is not a type of fungus.");
			
				p.addAnswer(2, "Eukarya ... Protista",
				false,
				"Rose bushes are multicellular and are not algae.");
			
				p.addAnswer(3, "Eukarya ... Plantae",
				true,
				"Rose bushes are plants.");
			
				p.addAnswer(4, "Eukarya ... Animalia",
				false,
				"Rose bushes are not animals.");
			
				p.addAnswer(5, "Bacteria ... Archaea",
				false,
				"Rose bushes are not prokaryotes.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335589;


		
		

		
			
			p.question = "In the five-kingdom system, which kingdom consists primarily of unicellular eukaryotes? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?1&F','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Classification Schemes</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Fungi",
				false,
				"While some fungi are unicellular, most are multicellular.");
			
				p.addAnswer(2, "Protista",
				true,
				"Protists are mostly unicellular eukaryotes, though they also include multicellular algae.");
			
				p.addAnswer(3, "Plantae",
				false,
				"Plants are multicellular.");
			
				p.addAnswer(4, "Animalia",
				false,
				"Animals are multicellular.");
			
				p.addAnswer(5, "Monera",
				false,
				"Monerans are prokaryotes.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335590;


		
		

		
			
			p.question = "In the two-kingdom system, why were fungi classified in the kingdom Plantae? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?1&F','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Classification Schemes</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "They are sedentary.",
				true,
				"This is why fungi were placed in the same kingdom as plants.");
			
				p.addAnswer(2, "They are heterotrophs.",
				false,
				"Photosynthetic organisms were placed in the kingdom Plantae.");
			
				p.addAnswer(3, "They lack cell walls.",
				false,
				"Fungi have cell walls.");
			
				p.addAnswer(4, "They are unicellular.",
				false,
				"Some fungi are unicellular, and some are multicellular.");
			
				p.addAnswer(5, "They are autotrophs.",
				false,
				"Fungi are heterotrophs.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335591;


		
		

		
			
			p.question = "There is(are) _____ eukaryotic domain(s). (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?1&F','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Classification Schemes</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "one",
				true,
				"The only eukaryotic domain is the domain Eukarya.");
			
				p.addAnswer(2, "two",
				false,
				"Fewer.");
			
				p.addAnswer(3, "three",
				false,
				"Fewer.");
			
				p.addAnswer(4, "four",
				false,
				"Fewer.");
			
				p.addAnswer(5, "five",
				false,
				"Fewer.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

