

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "31: Fungi > Practice Test";
	ak.quiz_loc_with_commas = "31: Fungi, Practice Test";
	ak.quiz_title = "Practice Test";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 30;
	ak.non_essay_total = 30;
	ak.scored_item_total = 30;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335854;


		
		

		
			
			p.question = "Fungi are _________ organisms. (<script type=\"text/javascript\">ebook(\'3101\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "chemoautotrophic",
				false,
				"No. Chemoautotrophs get their energy from the breakdown of inorganic chemical compounds.");
			
				p.addAnswer(2, "photoautotrophic",
				false,
				"No. Photoautotrophs use sunlight as their energy source.");
			
				p.addAnswer(3, "mixotrophic",
				false,
				"No. Mixotrophs can use both photosynthesis and heterotrophy to obtain energy.");
			
				p.addAnswer(4, "chemoheterotrophic",
				true,
				"Correct. Like animals, fungi are chemoheterotrophs. They must get both their energy and carbon skeletons by absorbing pre-digested nutrients from the environment.");
			
				p.addAnswer(5, "photoheterotrophic",
				false,
				"No. Photoheterotrophs use light as an energy source but must obtain carbon from organic carbon compounds in the environment.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335855;


		
		

		
			
			p.question = "Parasitic fungi are responsible for about 80% of diseases that affect _______. (<script type=\"text/javascript\">ebook(\'3101\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "mammals",
				false,
				"No. Mammals are susceptible to fungal infections, but fungi do not produce 80% of diseases in mammals.");
			
				p.addAnswer(2, "plants",
				true,
				"Correct. Plants are particularly susceptible to fungal infections.");
			
				p.addAnswer(3, "protists",
				false,
				"No. Diseases in protists are not primarily caused by fungi.");
			
				p.addAnswer(4, "amphibians",
				false,
				"No. Diseases in amphibians are not primarily caused by fungi.");
			
				p.addAnswer(5, "humans",
				false,
				"No. Mammals are susceptible to fungal infections, but fungi do not produce 80% of diseases in mammals.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335856;


		
		

		
			
			p.question = "There is a fungus in Oregon that covers 890 hectares! The bulk of this fungus is most likely _____. (<script type=\"text/javascript\">ebook(\'3101\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "reproductive structures",
				false,
				"No. Reproductive structures do not make up the bulk of a fungus.");
			
				p.addAnswer(2, "haustoria",
				false,
				"No. These are specialized hyphae that enable parasitic fungi to penetrate the tissue of their hosts.");
			
				p.addAnswer(3, "pathogenic",
				false,
				"No. Pathogenic fungi are usually considerably smaller than this.");
			
				p.addAnswer(4, "mycelium",
				true,
				"Correct. Fungal mycelia can be huge, although they usually escape our notice because they are subterranean.");
			
				p.addAnswer(5, "sporangia",
				false,
				"No. Sporangia are typically above-ground structures, and comprise a minor portion of the fungal mass.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335857;


		
		

		
			
			p.question = "In fungi, the function of the mycelium is _____. (<script type=\"text/javascript\">ebook(\'3101\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "dispersal to distant habitats",
				false,
				"No. The mycelium is the feeding network of a fungus.");
			
				p.addAnswer(2, "defense",
				false,
				"No. The mycelium is the feeding network of a fungus.");
			
				p.addAnswer(3, "obtaining food",
				true,
				"Correct. The hyphae form an interwoven mat called a mycelium, the feeding network of a fungus.");
			
				p.addAnswer(4, "surviving a period of food shortage",
				false,
				"No. The mycelium is the feeding network of a fungus, but it does not store nutrients.");
			
				p.addAnswer(5, "movement",
				false,
				"No. Fungi \"move\" to another location through growth of hyphae. But the \"movement\" is for feeding, which is the specific role of the mycelium.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335858;


		
		

		
			
			p.question = "Fungi that consist of a continuous mass containing hundreds or thousands of nuclei are known as _____. (<script type=\"text/javascript\">ebook(\'3101\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "septic",
				false,
				"No. These fungi, known as coenocytic, lack septa. Septa divide hyphae into cells.");
			
				p.addAnswer(2, "coenocytic",
				true,
				"Correct. The coenocytic condition results from the repeated division of nuclei without cytoplasmic division.");
			
				p.addAnswer(3, "dikaryon",
				false,
				"No. This term describes a mycelium that contains two coexisting, genetically different nuclei.");
			
				p.addAnswer(4, "imperfect fungi",
				false,
				"No. This is a term used for fungal species that do not have an identifiable sexual stage.");
			
				p.addAnswer(5, "chytrids",
				false,
				"No. This does not describe chytrids, which are known for their zoospores (flagellated spores).");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335859;


		
		

		
			
			p.question = "The hyphae of parasitic fungi that are modified to penetrate and absorb nutrients from host tissue are called _____. (<script type=\"text/javascript\">ebook(\'3101\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "haustoria",
				true,
				"Correct. Haustoria are the modified hyphae of parasitic fungi.");
			
				p.addAnswer(2, "asci",
				false,
				"No. Fungi of the phylum Ascomycota produce asexual spores within asci.");
			
				p.addAnswer(3, "mycorrhizae",
				false,
				"No. These are structures of fungi and plant roots in a mutualistic relationship. Mycorrhizae are a specialized form of this type of hyphae.");
			
				p.addAnswer(4, "septa",
				false,
				"No. Septa divide hyphae into cells.");
			
				p.addAnswer(5, "basidiocarps",
				false,
				"No. Basidiocarps are fruiting bodies formed by fungi of the phylum Basidiomycota.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335860;


		
		

		
			
			p.question = "You can buy micorrhizal fungus to add to soil when you plant trees and other plants. Why would you want to do this? (<script type=\"text/javascript\">ebook(\'3101\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Mycorrhizal fungi prey on nematodes in the soil.",
				false,
				"No. There are parasitic fungi that prey on nematodes, but they are not mycorrhizal fungi.");
			
				p.addAnswer(2, "Mycorrhizal fungi produce carbohydrates needed by plants.",
				false,
				"No. In fact the plants supply mycorrhizal fungi with carbohydrates as part of their mutualistic relationship.");
			
				p.addAnswer(3, "Mycorrhizal fungi prevent transposons from accumulating in plant cells.",
				false,
				"No. There is some evidence that some bread molds have genomic defense systems that prevent transposons from accumulating, but this is not part of fungi\'s mycorrhizal relationship with plants.");
			
				p.addAnswer(4, "Mycorrhizal fungi assist plants in the absorption of essential nutrients.",
				true,
				"Correct. Mycorrhizal fungi are very important to the overall health of over 90% of the plants on the planet.");
			
				p.addAnswer(5, "Mycorrhizal fungi live in plant leaves and produce toxins that discourage herbivores.",
				false,
				"No. Endophytes are fungi that perform this function.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335861;


		
		

		
			
			p.question = "Which choice below generally represents the correct order of events in fungal sexual reproduction? (<script type=\"text/javascript\">ebook(\'3102\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "karyogamy, meiosis, plasmogamy, germination",
				false,
				"No. Study Figure 31.5. The correct order of events is plasmogamy, karyogamy, meiosis, germination.");
			
				p.addAnswer(2, "meiosis, plasmogamy, karyogamy, germination",
				false,
				"No. Study Figure 31.5. The correct order of events is plasmogamy, karyogamy, meiosis, germination.");
			
				p.addAnswer(3, "germination, meiosis, karyogamy, plasmogamy",
				false,
				"No. Study Figure 31.5. The correct order of events is plasmogamy, karyogamy, meiosis, germination.");
			
				p.addAnswer(4, "plasmogamy, meiosis, germination, karyogamy",
				false,
				"No. Study Figure 31.5. The correct order of events is plasmogamy, karyogamy, meiosis, germination.");
			
				p.addAnswer(5, "plasmogamy, karyogamy, meiosis, germination",
				true,
				"Correct. This order of events characterizes a generalized life cycle of fungi.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335862;


		
		

		
			
			p.question = "Which of the following statements about fungi is true? (<script type=\"text/javascript\">ebook(\'3102\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The dominant stage of the life cycle is usually haploid.",
				false,
				"No. This is a true statement, but there is a better answer.");
			
				p.addAnswer(2, "The haploid nuclei of dikaryotic hyphal cells fuse to form a diploid zygote.",
				false,
				"No. This is a true statement, but there is a better answer.");
			
				p.addAnswer(3, "Many species obtain their nutrients from decaying organic matter.",
				false,
				"No. This is a true statement, but there is a better answer.");
			
				p.addAnswer(4, "Spores germinate and then mitotically divide to form a mycelium.",
				false,
				"No. This is a true statement, but there is a better answer.");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct. All of these statements are true.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335863;


		
		

		
			
			p.question = "What role do pheromones play in fungal sexual reproduction? (<script type=\"text/javascript\">ebook(\'3102\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Fungi use these chemical signals to determine whether a potential sexual partner is of a suitable mating type.",
				true,
				"Correct. The pheromones from one potential partner bind to receptors on the surface of the other.");
			
				p.addAnswer(2, "Pheromones allow the hyphae of two distinct mycelia to follow each other as they grow.",
				false,
				"No. This may be true of certain pheromones released by ants, but not those of fungi. Being competitors, it would probably be of greater advantage <b>not</b> to follow each other.");
			
				p.addAnswer(3, "After plasmogamy, pheromones cause the haploid nuclei from each parent to exchange genes.",
				false,
				"No. The role of pheromones is related to the initiation of sexual reproduction.");
			
				p.addAnswer(4, "Pheromones initiate zygotes to form during karyogamy.",
				false,
				"No. The role of pheromones is related to the initiation of sexual reproduction.");
			
				p.addAnswer(5, "Pheromones initiate the production of spores in molds.",
				false,
				"No. The role of pheromones is related to the initiation of sexual reproduction. Spores are produced from molds during asexual reproduction.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335864;


		
		

		
			
			p.question = "Hyphae with two nuclei per cell are called _____. (<script type=\"text/javascript\">ebook(\'3102\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "diploid",
				false,
				"No. The prefix \"di-\" does mean \"two,\" but \"diploid\" refers to having two sets of chromosomes.");
			
				p.addAnswer(2, "multicellular",
				false,
				"No. \"Multicellular\" means having many cells.");
			
				p.addAnswer(3, "dikaryotic",
				true,
				"Correct. In many fungi, after plasmogamy, the nuclei from each parent pair up but do not fuse, forming a dikaryon (a cell with two nuclei).");
			
				p.addAnswer(4, "asci (plural of ascus)",
				false,
				"No. An ascus is a sac.");
			
				p.addAnswer(5, "prokaryotic",
				false,
				"No. Prokaryotes are organisms that lack a true nucleus.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335865;


		
		

		
			
			p.question = "During what stage of fungal reproduction are diploid cells produced? (<script type=\"text/javascript\">ebook(\'3102\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "karyogamy",
				true,
				"Correct. This is the only time in the life cycle of a fungus that diploid cells exist.");
			
				p.addAnswer(2, "meiosis",
				false,
				"No. Meiosis restores the haploid state.");
			
				p.addAnswer(3, "dikaryotic stage",
				false,
				"No. During the dikaryotic stage there are two distinct haploid nuclei in each cell, but the cells are not actually diploid.");
			
				p.addAnswer(4, "plasmogamy",
				false,
				"No. Plasmogamy refers to the fusing of the cytoplasm of two parent mycelia, but fusion of their nuclei to form a diploid zygote does not occur until later.");
			
				p.addAnswer(5, "binary fission",
				false,
				"No. Although some fungi do reproduce asexually by simple cell division, they remain haploid.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335866;


		
		

		
			
			p.question = "Fungal species are classified in a particular phylum based on _____. (<script type=\"text/javascript\">ebook(\'3102\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "their mode of nutrition",
				false,
				"No. All fungi are heterotrophs that feed by absorption.");
			
				p.addAnswer(2, "their type of motility",
				false,
				"No. All fungi are non-motile.");
			
				p.addAnswer(3, "whether they produce sexually or asexually",
				false,
				"No. The method of classification is related to reproduction, but it not defined by whether the organisms produce sexually or asexually.");
			
				p.addAnswer(4, "the type of sexual structure they form",
				true,
				"Correct. Whenever a sexual stage of a so-called deuteromycete is discovered, the species is classified in a particular phylum, depending on the type of sexual structures it forms.");
			
				p.addAnswer(5, "whether they are mutualistic or parasitic",
				false,
				"No. These characteristics are not used to classify fungi at the phylum level.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335867;


		
		

		
			
			p.question = "Molecular evidence suggests that fungi _____. (<script type=\"text/javascript\">ebook(\'3103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "are a polyphyletic group",
				false,
				"No. Fungi are a monophyletic group.");
			
				p.addAnswer(2, "and animals have a common ancestor",
				true,
				"Correct. There is evidence that both fungi and animals evolved from aquatic flagellated protists.");
			
				p.addAnswer(3, "evolved from a multicellular protist",
				false,
				"No. There is evidence that both fungi and animals evolved from single-celled, aquatic, flagellated protists.");
			
				p.addAnswer(4, "evolved from plants",
				false,
				"No. Note that plants have cellulose in their cell walls and fungi have chitin.");
			
				p.addAnswer(5, "were once photosynthetic",
				false,
				"No. The evidence does not support this.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335868;


		
		

		
			
			p.question = "In contrast to plants, the cell walls of fungi are composed of _____. (<script type=\"text/javascript\">ebook(\'3103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "lignin",
				false,
				"No. Lignin is a phytochemical.");
			
				p.addAnswer(2, "cellulose",
				false,
				"No. Cellulose is found in the cell walls of plants.");
			
				p.addAnswer(3, "peptidoglycan",
				false,
				"No. Peptidoglycan is unique to the cell walls of bacteria.");
			
				p.addAnswer(4, "pectin",
				false,
				"No. Pectin is a polysaccharide found mostly in the middle lamella of the cell walls of vascular plants.");
			
				p.addAnswer(5, "chitin",
				true,
				"Correct. The chitin found in fungal cell walls is identical to the chitin found in the exoskeleton of arthropods.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335869;


		
		

		
			
			p.question = "Evidence that mycorrhizae, the mutualistic relationship between plants and fungi, existed from the beginning of the colonization of land comes from _________. (<script type=\"text/javascript\">ebook(\'3103\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "molecular clock studies",
				false,
				"No. The evidence comes from fossils.");
			
				p.addAnswer(2, "comparisons of DNA sequences",
				false,
				"No. The evidence comes from fossils.");
			
				p.addAnswer(3, "fossils",
				true,
				"Correct. Fossils from the late Silurian indicate that mycorrhizae existed in conjunction with some of the earliest vascular plants.");
			
				p.addAnswer(4, "phylogenetics",
				false,
				"No. The evidence comes from fossils.");
			
				p.addAnswer(5, "microsporidia",
				false,
				"No. The evidence comes from fossils.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335870;


		
		

		
			
			p.question = "Which feature below is unique to chytrids? (<script type=\"text/javascript\">ebook(\'3104\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "asci (spore-producing sacs)",
				false,
				"No. These are a feature of ascomycetes.");
			
				p.addAnswer(2, "zoospores (flagellated spores)",
				true,
				"Correct. Chytrids are thought to be members of the earliest fungal lineage. Their zoospores are evidence that fungi evolved from flagellated protists.");
			
				p.addAnswer(3, "cell walls made of chitin",
				false,
				"No. All fungi share this feature.");
			
				p.addAnswer(4, "conidia (asexual spores)",
				false,
				"No. These spores are produced at the tips of specialized hyphae (conidiaphores) in ascomycetes.");
			
				p.addAnswer(5, "soredia",
				false,
				"No. These are small clusters of hyphae with embedded algae found in lichens, and are lichens\' means of asexual reproduction.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335871;


		
		

		
			
			p.question = "Which statement below about zygosporangia is true? (<script type=\"text/javascript\">ebook(\'3104\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "They are metabolically inactive.",
				false,
				"No. This is a true statement, but there is a better answer.");
			
				p.addAnswer(2, "They are resistant to freezing and drying.",
				false,
				"No. This is a true statement, but there is a better answer.");
			
				p.addAnswer(3, "They are multinucleate formations.",
				false,
				"No. This is a true statement, but there is a better answer.");
			
				p.addAnswer(4, "They are produced through plasmogamy.",
				false,
				"No. This is a true statement, but there is a better answer.");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct. These are all true statements.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335872;


		
		

		
			
			p.question = "What is the major feature of glomeromycetes? (<script type=\"text/javascript\">ebook(\'3104\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "mycorrhizae",
				false,
				"No. Although nearly all glomeromycetes do form mycorrhizae, there is a more specific answer.");
			
				p.addAnswer(2, "arbuscules",
				true,
				"Correct. Arbuscules are the tiny tips of glomeromycete hyphae that invade plant roots and branch into tree-like structures within root cells, forming arbuscular mycorrhizae.");
			
				p.addAnswer(3, "ascocarps",
				false,
				"No. These are the fruiting bodies of ascomycetes.");
			
				p.addAnswer(4, "the containment of millions of photosynthetic microorganisms in their hyphae",
				false,
				"No. This describes lichens.");
			
				p.addAnswer(5, "soredia",
				false,
				"No. These are small clusters of hyphae with embedded algae found in lichens.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335873;


		
		

		
			
			p.question = "An ascus is _____. (<script type=\"text/javascript\">ebook(\'3104\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a saclike structure containing spores",
				true,
				"Correct. In Ascomycota, the fruiting bodies, or ascocarps, contain the sexual spores in saclike asci.");
			
				p.addAnswer(2, "an asexual spore-producing structure on a stalk",
				false,
				"No. Asci are involved in sexual reproduction.");
			
				p.addAnswer(3, "a club-shaped cell with spores on its outer surface",
				false,
				"No. Such a structure is a basidium.");
			
				p.addAnswer(4, "a cup-shaped structure containing many spore-producing cells on the gill of a mushroom",
				false,
				"No. Asci are characteristic of Ascomycota.");
			
				p.addAnswer(5, "the sexual structure of chytrids",
				false,
				"No. It is the sexual structure of ascomycetes.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335874;


		
		

		
			
			p.question = "The asexual spores produced by members of the phylum Ascomycota are called _____. (<script type=\"text/javascript\">ebook(\'3104\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "conidia",
				true,
				"Correct. These spores are not formed within sporangia.");
			
				p.addAnswer(2, "lichens",
				false,
				"No. Lichens are symbiotic associations of algae and fungi.");
			
				p.addAnswer(3, "mushrooms",
				false,
				"No. Mushrooms are a type of basidiocarp. Basidiocarps are produced by members of the phylum Basidiomycota.");
			
				p.addAnswer(4, "mycorrhizae",
				false,
				"No. These are mutualistic associations of fungi and plants.");
			
				p.addAnswer(5, "asci",
				false,
				"No. Sexual spores are produced within asci.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335875;


		
		

		
			
			p.question = "The mushroom in a basidiomycete life cycle serves the same function as the _____ in the ascomycete life cycle, which is to _____. (<script type=\"text/javascript\">ebook(\'3104\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "plasmodium; form gametes",
				false,
				"No. Plasmodial slime molds are not fungi.");
			
				p.addAnswer(2, "dikaryon; store a food reserve",
				false,
				"No. Mushrooms disperse spores.");
			
				p.addAnswer(3, "ascocarp; scatter sexually produced spores",
				true,
				"Correct. A mushroom is an example of a basidiocarp, the source of sexual spores in Basidiomycota. In Ascomycota, the fruiting bodies, or ascocarps, contain the sexual spores in saclike asci.");
			
				p.addAnswer(4, "conidium; supply the rest of the fungus with chitin monomers",
				false,
				"No. Mushrooms disperse spores.");
			
				p.addAnswer(5, "zygosporangium; produce sexual spores",
				false,
				"No. Zygosporangia produce sexual spores in zygomycetes.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335876;


		
		

		
			
			p.question = "While hiking through a forest, you discover a fungus growing on the remains of a decaying tree trunk. You hypothesize that it is a basidiomycete fungus because it resembles a mushroom in shape and size. If your logic is correct, microscopic analysis of the tissue found in the stalk of this fungus will reveal the presence of _____. (<script type=\"text/javascript\">ebook(\'3104\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "monokaryotic cells with a haploid nucleus",
				false,
				"No. Basidiocarps are not monokaryotic.");
			
				p.addAnswer(2, "dikaryotic cells with haploid nuclei",
				true,
				"Correct. Environmental cues, such as rain and temperature changes, induce the dikaryotic mycelium (containing two haploid nuclei) to form compact masses that develop into basidiocarps, or mushrooms.");
			
				p.addAnswer(3, "monokaryotic cells with diploid nuclei",
				false,
				"No. Basidiocarps are not monokaryotic.");
			
				p.addAnswer(4, "dikaryotic cells with diploid nuclei",
				false,
				"No. Basidiocarps are not diploid.");
			
				p.addAnswer(5, "more than one of these cell types",
				false,
				"No. One of the above choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335877;


		
		

		
			
			p.question = "Fungi in the phylum Basidiomycota are the most important decomposers of wood because of their ability to break down _________. (<script type=\"text/javascript\">ebook(\'3104\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "mycorrhizae",
				false,
				"No. Mycorrhizae are mutualistic associations between fungi and plant roots.");
			
				p.addAnswer(2, "opisthokonts",
				false,
				"No. Opisthokonts form a clade including fungi, animals, and certain protists.");
			
				p.addAnswer(3, "cellulose",
				false,
				"No. Basidiomycetes are particularly good at breaking down lignin.");
			
				p.addAnswer(4, "lignin",
				true,
				"Correct. Members of the phylum Basidiomycota are best at breaking down lignin, one of the main components of wood.");
			
				p.addAnswer(5, "jet fuel",
				false,
				"No. Some fungi can break down jet fuel, but jet fuel is not a major component of wood.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335878;


		
		

		
			
			p.question = "What is the importance of the extended dikaryotic stage in the life cycles of basidiomycetes and ascomycetes? (<script type=\"text/javascript\">ebook(\'3104\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "It keeps transposons from accumulating in fungal cells.",
				false,
				"No. There is some evidence that some fungi have genome defense mechanisms, but these are not related to the dikaryotic stage.");
			
				p.addAnswer(2, "It allows for the formation of more hyphae.",
				false,
				"No. Hyphae can grow very quickly, but they are not particularly affected by the dikaryotic stage of reproduction.");
			
				p.addAnswer(3, "It allows for many genetic recombinations to occur.",
				true,
				"Correct. During the long dikaryotic stage in basidiomycetes and ascomycetes, the two nuclei may fuse repeatedly, exchanging genetic material and producing many genetically different spores.");
			
				p.addAnswer(4, "It allows for the formation of more conidia.",
				false,
				"No. Basidiomycetes do not produce conidia. Conidia are the result of asexual reproduction in ascomycetes.");
			
				p.addAnswer(5, "It increases the surface area for the production of basidiospores.",
				false,
				"No. The dikaryotic stage does not increase surface area.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335879;


		
		

		
			
			p.question = "Where and when does fertilization occur in the mushroom life cycle? (<script type=\"text/javascript\">ebook(\'3104\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "underground, as a mycelium begins to spread",
				false,
				"No. In mushroom-forming basidiomycetes, fertilization occurs above the ground.");
			
				p.addAnswer(2, "on the surface of the ground, when a basidiospore germinates",
				false,
				"No. The germination of a basidiospore results in the development of a haploid mycelium.");
			
				p.addAnswer(3, "in a mushroom, when the nuclei of a dikaryotic cell fuse",
				true,
				"Correct. Karyogamy within the basidia of the basidiocarp produces diploid nuclei.");
			
				p.addAnswer(4, "underground, when the hyphae of different mating types fuse",
				false,
				"No. Plasmogamy (the fusion of cytoplasms) without karyogamy (the fusion of nuclei) produces a dikaryon (a structure with two nuclei).");
			
				p.addAnswer(5, "in a mushroom, when eggs and sperm meet",
				false,
				"No. Karyogamy within the basidia of the basidiocarp produces diploid nuclei.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335880;


		
		

		
			
			p.question = "Lichens are _____. (<script type=\"text/javascript\">ebook(\'3105\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "mutualistic associations of fungi and plant roots",
				false,
				"No. This describes mycorrhizae.");
			
				p.addAnswer(2, "predatory fungi",
				false,
				"No. Lichens do not consume other organisms.");
			
				p.addAnswer(3, "the sexual stage of deuteromycetes",
				false,
				"No. Deuteromycetes are the imperfect fungi, those with no known sexual stage.");
			
				p.addAnswer(4, "symbiotic associations of photosynthesizers and fungi",
				true,
				"Correct. The fungus provides minerals to and retains water for the alga. The alga provides food to the fungus.");
			
				p.addAnswer(5, "used to produce blue cheese",
				false,
				"No. A type of mold is used to produce blue cheese through fermentation.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335881;


		
		

		
			
			p.question = "Lichens are important pioneers in areas that have been burned by fires or destroyed by lava flows because _____. (<script type=\"text/javascript\">ebook(\'3105\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "they are important in the initial stages of soil formation",
				true,
				"Correct. Many processes of lichens make it possible for a succession of plants to grow.");
			
				p.addAnswer(2, "they release chemicals that maintain the surfaces of the underlying substratum",
				false,
				"No. Actually, they release chemicals that dissolve the surfaces of things such as rock.");
			
				p.addAnswer(3, "they take up excess nitrogen",
				false,
				"No. Some lichens release nitrogen into new soil, supporting successions of plants.");
			
				p.addAnswer(4, "they thrive on acid rain",
				false,
				"No. Lichens are tough, but they are not tough enough to withstand high levels of sulfuric acid. The death of lichens is often a sign of deteriorating air quality.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335882;


		
		

		
			
			p.question = "A dramatic example of the pathogenicity of certain fungi is the virtual elimination of the American elm by _____. (<script type=\"text/javascript\">ebook(\'3105\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "ergots",
				false,
				"No. Ergots are found on rye. Substances produced by ergots have adverse effects on the human nervous system.");
			
				p.addAnswer(2, "truffles",
				false,
				"No. Truffles can be eaten; the only adverse effect is the impact on your economic condition.");
			
				p.addAnswer(3, "an ascomycete",
				true,
				"Correct. The disease, Dutch elm disease, is caused by an introduced ascomycete.");
			
				p.addAnswer(4, "a shelf fungus",
				false,
				"No. However, shelf fungi do parasitize weakened and damaged trees.");
			
				p.addAnswer(5, "a rust",
				false,
				"No. However, rust is a destructive plant parasite.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335883;


		
		

		
			
			p.question = "Two of the most common mycoses (fungal infections) in humans are _________. (<script type=\"text/javascript\">ebook(\'3105\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "ergots and rusts",
				false,
				"No. Ergots are found on rye, but they can cause serious symptoms if the rye is consumed by humans. Rusts, however, only infect plants.");
			
				p.addAnswer(2, "indoor molds and <i>Aspergillus</i>",
				false,
				"No. Indoor molds have been implicated as the cause of several diseases, but a direct link has not been definitively shown. <i>Aspergillus</i> can produce carcinogenic aflotoxins in grains and peanuts, but neither of these is very widespread.");
			
				p.addAnswer(3, "rusts and white rot fungi",
				false,
				"No. Rusts infect plants and white rot fungi digest wood.");
			
				p.addAnswer(4, "<i>Saccharomyces cerevisiae</i> and <i> Penicillium</i>",
				false,
				"No. These are both beneficial fungi.");
			
				p.addAnswer(5, "athlete\'s foot and yeast infections",
				true,
				"Correct. Both athlete\'s foot and yeast infections are so common that there are over-the-counter medications for both.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

