

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "Investigation Quiz > What Factors Determine the Effectiveness of Drugs?";
	ak.quiz_loc_with_commas = "Investigation Quiz, What Factors Determine the Effectiveness of Drugs?";
	ak.quiz_title = "What Factors Determine the Effectiveness of Drugs?";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 9;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 9;
	ak.non_essay_total = 0;
	ak.scored_item_total = 0;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337542;


		
		

		
			p.question = "Many medicines can only be stored for a certain period of time, and then they must be disposed. Hypothesize why aging can affect a drug\'s ability to work.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337543;


		
		

		
			p.question = "Hypothesize why many drugs lose their effectiveness quicker if a person drinks lots of coffee, tea, or water while taking a drug.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337544;


		
		

		
			p.question = "The dosages for certain drugs given to epileptic patients are different for females and males. Propose an explanation for this medical practice.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337545;


		
		

		
			p.question = "What general observation can you make about the effect of the drug produced by the plant?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337546;


		
		

		
			p.question = "What general observation can you make about the effect of the drug produced by the genetically engineered yeast?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337547;


		
		

		
			p.question = "What general observation can you make about the results for group C?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337548;


		
		

		
			p.question = "What general observation can you make about the results for group D?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337549;


		
		

		
			p.question = "How might the differences in the enantiomers of reboxetine help explain the different results for groups A, B, and C?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337550;


		
		

		
			p.question = "What factors might explain the different responses within each trial group?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

