

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "55: Ecosystems > Practice Test";
	ak.quiz_loc_with_commas = "55: Ecosystems, Practice Test";
	ak.quiz_title = "Practice Test";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 38;
	ak.non_essay_total = 38;
	ak.scored_item_total = 38;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337113;


		
		

		
			
			p.question = "The biggest difference between the flow of energy and the flow of chemical nutrients in an ecosystem is that _____. (<script type=\"text/javascript\">ebook(\'5501\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the amount of energy is much greater than the amount of nutrients",
				false,
				"No. Energy and nutrients are not directly comparable in this fashion.");
			
				p.addAnswer(2, "energy is recycled, but nutrients are not",
				false,
				"No. Think about the laws of thermodynamics.");
			
				p.addAnswer(3, "organisms always need nutrients, but they don\'t always need energy",
				false,
				"No. Organisms always need both.");
			
				p.addAnswer(4, "nutrients are recycled, but energy is not",
				true,
				"Correct. Chemical nutrients can be recycled within ecosystems through biogeochemical cycles. Energy is lost from an ecosystem as a result of respiration.");
			
				p.addAnswer(5, "organisms always need energy, but they don\'t always need nutrients",
				false,
				"No. Organisms always need both.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337114;


		
		

		
			
			p.question = "In an ecosystem, all incoming energy will eventually be _____. (<script type=\"text/javascript\">ebook(\'5501\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "transferred from one trophic level to the next",
				false,
				"No. Energy transfers are not 100% efficient.");
			
				p.addAnswer(2, "transferred to the decomposers",
				false,
				"No. Energy transfers are not 100% efficient.");
			
				p.addAnswer(3, "dissipated into space as heat",
				true,
				"Correct. While solar radiation is the ultimate energy source for most ecosystems, respiratory heat loss is the ultimate sink.");
			
				p.addAnswer(4, "used in photosynthesis",
				false,
				"No. Photosynthesis is not 100% efficient.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337115;


		
		

		
			
			p.question = "Based on the law of conservation of energy, ecosystem ecologists can make which of the following assertions? (<script type=\"text/javascript\">ebook(\'5501\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The total amount of energy stored in organic molecules plus the amounts reflected and dissipated as heat must equal the total solar energy intercepted by the Earth.",
				true,
				"Correct. Although the total energy budget of the Earth is a very difficult thing to measure, this assertion is true according to the law of conservation of energy.");
			
				p.addAnswer(2, "Photosynthetic organisms can convert approximately 1% of the solar energy they receive into organic molecules.",
				false,
				"No. This describes the efficiency of photosynthesis, but it does not follow from the law of conservation of energy.");
			
				p.addAnswer(3, "Approximately 10% of energy is transferred from one trophic level to the next.",
				false,
				"No. This describes the efficiency of energy transfer, but it does not follow from the law of conservation of energy.");
			
				p.addAnswer(4, "Elements are not lost on a global scale.",
				false,
				"No. While this is correct, it does not follow from the law of conservation of energy.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. Only one of the choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337116;


		
		

		
			
			p.question = "Which of the following is a primary producer? (<script type=\"text/javascript\">ebook(\'5501\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "detritivores",
				false,
				"No. Detritivores are a type of heterotroph.");
			
				p.addAnswer(2, "shrimp",
				false,
				"No. Shrimp are primary consumers.");
			
				p.addAnswer(3, "poison ivy",
				true,
				"Correct. Primary producers are autotrophs.");
			
				p.addAnswer(4, "lions",
				false,
				"No. Lions are consumers.");
			
				p.addAnswer(5, "humans",
				false,
				"No. Humans are omnivores.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337117;


		
		

		
			
			p.question = "Photosynthetic organisms are called _____. (<script type=\"text/javascript\">ebook(\'5501\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "autotrophs",
				true,
				"Correct. Autotrophs are generally photosynthetic organisms that use light energy to synthesize sugars and other organic compounds.");
			
				p.addAnswer(2, "heterotrophs",
				false,
				"No. Heterotrophs are consumers.");
			
				p.addAnswer(3, "herbivores",
				false,
				"No. Herbivores are consumers.");
			
				p.addAnswer(4, "carnivores",
				false,
				"No. Carnivores are consumers.");
			
				p.addAnswer(5, "consumers",
				false,
				"No. Consumers are heterotrophs.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337118;


		
		

		
			
			p.question = "When you eat an apple, you are a _____. (<script type=\"text/javascript\">ebook(\'5501\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "primary consumer",
				true,
				"Correct. Apple trees are primary producers.");
			
				p.addAnswer(2, "carnivore",
				false,
				"No. A carnivore consumes animal matter.");
			
				p.addAnswer(3, "primary producer",
				false,
				"No. Primary producers manufacture their own organic compounds.");
			
				p.addAnswer(4, "secondary consumer",
				false,
				"No. Apple trees are primary producers.");
			
				p.addAnswer(5, "tertiary consumer",
				false,
				"No. Apple trees are primary producers.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337119;


		
		

		
			
			p.question = "The main decomposers in an ecosystem are _____. (<script type=\"text/javascript\">ebook(\'5501\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "plants and animals",
				false,
				"No. Plants are primary producers, and animals are consumers.");
			
				p.addAnswer(2, "prokaryotes and animals",
				false,
				"No. Prokaryotes are decomposers, but animals usually are not.");
			
				p.addAnswer(3, "fungi and prokaryotes",
				true,
				"Correct. Fungi and prokaryotes are the groups most involved in the conversion of organic compounds to inorganic nutrients.");
			
				p.addAnswer(4, "prokaryotes and plants",
				false,
				"No. Prokaryotes are decomposers, but plants usually are not.");
			
				p.addAnswer(5, "plants and fungi",
				false,
				"No. Fungi are decomposers, but plants usually are not.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337120;


		
		

		
			
			p.question = "Most of the solar energy that reaches Earth _____. (<script type=\"text/javascript\">ebook(\'5502\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "is used by plants for photosynthesis",
				false,
				"No. Photosynthesis is not 100% efficient, and Earth is not completely blanketed by photosynthesizing organisms.");
			
				p.addAnswer(2, "is not captured for use by living things",
				true,
				"Correct. Most solar radiation that reaches Earth\'s surface lands on bare ground and bodies of water that absorb or reflect the incoming energy.");
			
				p.addAnswer(3, "is continually recycled by ecosystems",
				false,
				"No. Energy cannot be recycled.");
			
				p.addAnswer(4, "is trapped by greenhouse gases",
				false,
				"No. Some of the energy is trapped by greenhouse gases, but certainly not most of it.");
			
				p.addAnswer(5, "is used by algae for photosynthesis",
				false,
				"No. Photosynthesis is not 100% efficient, and Earth is not completely blanketed by photosynthesizing organisms.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337121;


		
		

		
			
			p.question = "The rate at which producers convert solar energy to the chemical energy of organic compounds, minus the energy used during respiration, is called _____. (<script type=\"text/javascript\">ebook(\'5502\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "biomass",
				false,
				"No. However, this rate can be expressed in terms of biomass.");
			
				p.addAnswer(2, "standing crop",
				false,
				"No. However, this rate can be expressed in terms of standing crop.");
			
				p.addAnswer(3, "biomagnification",
				false,
				"No. \"Biological magnification\" refers to a process by which substances become more concentrated as they pass through a food chain.");
			
				p.addAnswer(4, "net productivity",
				true,
				"Correct. Primary productivity is the amount of light converted to chemical energy by the autotrophs of an ecosystem during a given time period. Net primary productivity is equal to the gross primary productivity minus the energy used by the producers for respiration (NPP = GPP - R).");
			
				p.addAnswer(5, "gross primary productivity",
				false,
				"No. Gross primary productivity (GPP) is the rate at which solar energy is converted to the chemical energy of organic compounds. GPP does not consider respiration.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337122;


		
		

		
			
			p.question = "A study of metabolic rates in a terrestrial community showed that the energy released by respiration exceeded the energy captured in photosynthesis. Which one of the following situations is most likely? (<script type=\"text/javascript\">ebook(\'5502\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Community biomass is increasing.",
				false,
				"No. The system is losing more energy than it is retaining.");
			
				p.addAnswer(2, "Community biomass is decreasing.",
				true,
				"Correct. Net primary productivity is the difference between the yield of photosynthesis and the consumption of organic fuel in respiration. Primary productivity can be expressed as the biomass of vegetation added to an area of the ecosystem per unit of time. If the energy released by respiration exceeds the energy captured in photosynthesis, biomass decreases.");
			
				p.addAnswer(3, "A climax community has been reached.",
				false,
				"No. A climax community would be considered stable; the community described in the equation is losing more energy than it is retaining.");
			
				p.addAnswer(4, "The first law of thermodynamics (energy is conserved) in not in effect.",
				false,
				"No. The laws of thermodynamics are in effect.");
			
				p.addAnswer(5, "The second law of thermodynamics (in a closed system, there is a general tendency toward disorder) is not in effect.",
				false,
				"No. The laws of thermodynamics are in effect.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337123;


		
		

		
			
			p.question = "What are the major factors that control primary production in terrestrial ecosystems? (<script type=\"text/javascript\">ebook(\'5502\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "light and nutrients",
				false,
				"No. These are the factors that control primary production in aquatic ecosystems.");
			
				p.addAnswer(2, "light and moisture",
				false,
				"No. Generally speaking, light is not a limiting factor in terrestrial ecosystems.");
			
				p.addAnswer(3, "temperature and moisture",
				true,
				"Correct. The areas with the least primary production are usually very cold and/or very dry.");
			
				p.addAnswer(4, "temperature and nutrients",
				false,
				"No. Nutrients are usually available in terrestrial ecosystems.");
			
				p.addAnswer(5, "temperature and light",
				false,
				"No. Generally speaking, light is not a limiting factor in terrestrial ecosystems.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337124;


		
		

		
			
			p.question = "Which statement below about primary production and ecosystems is correct? (<script type=\"text/javascript\">ebook(\'5502\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Overall, terrestrial ecosystems contribute two-thirds of global net primary production, and marine ecosystems contribute about one-third.",
				true,
				"Correct. The open ocean contributes more primary production than any other single ecosystem; however, this is only because it is so large. Production per unit area is relatively low.");
			
				p.addAnswer(2, "Overall, marine ecosystems contribute about two-thirds of global net primary production, and terrestrial ecosystems contribute about one-third.",
				false,
				"No. The open ocean contributes more primary production than any other single ecosystem; however, this is only because it is so large. Production per unit area is relatively low.");
			
				p.addAnswer(3, "Satellite images reveal how unproductive terrestrial ecosystems are on a per-unit-area basis.",
				false,
				"No. This is true of the open ocean.");
			
				p.addAnswer(4, "The primary production per unit area of the open ocean is greater than that of any other single ecosystem.",
				false,
				"No. The open ocean does contribute more primary production than any other single ecosystem, but not on a per-unit-area basis.");
			
				p.addAnswer(5, "A forest with large trees is apt to have more primary production than most grassland, which tends to lack large vegetation.",
				false,
				"No. This is not necessarily true. Grassland adds a lot of new biomass continually because the vegetation is rapidly consumed by grazing animals.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337125;


		
		

		
			
			p.question = "How do iron levels affect phytoplankton populations in a marine ecosystem? (<script type=\"text/javascript\">ebook(\'5502\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Without iron, eukaryotic phytoplankton populations fall because they cannot convert atmospheric N<sub>2</sub> to nitrogenous minerals.",
				false,
				"No. <b>Eukaryotic</b> phytoplankton do not have this capability with or without iron.");
			
				p.addAnswer(2, "In the presence of too much iron, eukaryotic phytoplankton populations fall because they cannot convert atmospheric N<sub>2</sub> to nitrogenous minerals.",
				false,
				"No. <b>Eukaryotic </b>phytoplankton do not have this capability with or without iron.");
			
				p.addAnswer(3, "Iron stimulates the growth of cyanobacteria, which convert atmospheric N<sub>2</sub> to nitrogenous minerals, stimulating the growth of phytoplankton.",
				true,
				"Correct. This explains why marine waters lacking iron are very clear. Without cyanobacteria to convert nitrogen to usable forms, phytoplankton populations are likely to be low.");
			
				p.addAnswer(4, "Iron halts the growth of cyanobacteria, which convert atmospheric N<sub>2</sub> to nitrogenous minerals; therefore, phytoplankton populations are limited.",
				false,
				"No. The opposite is true. Iron stimulates the growth of cyanobacteria, leading to an increased phytoplankton population.");
			
				p.addAnswer(5, "Nitrogen and phosphorus are the only known limiting nutrients in marine ecosystems.",
				false,
				"No. Nitrogen is generally the limiting nutrient in marine ecosystems, but there are some anomalies.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337126;


		
		

		
			
			p.question = "Eutrophication in lakes is frequently the direct result of _____. (<script type=\"text/javascript\">ebook(\'5502\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a diminished supply of nitrates and phosphates",
				false,
				"No. Quite the opposite is true. This state would inhibit algal growth.");
			
				p.addAnswer(2, "industrial poisons",
				false,
				"No. This would most likely kill algae, not promote their growth.");
			
				p.addAnswer(3, "nutrient enrichment such as nitrate and phosphate runoffs from land",
				true,
				"Correct. Sewage and factory wastes, runoffs of animal waste from pastures and stockyards, and the leaching of fertilizer from agricultural, recreational, and urban areas have overloaded many streams, lakes, and rivers with inorganic nutrients. This enrichment can result in an explosive increase in the density of photosynthetic organisms.");
			
				p.addAnswer(4, "an increase in predators",
				false,
				"No. The lack of oxygen brought on by eutrophication would result in the death of predators.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337127;


		
		

		
			
			p.question = "The amount of chemical energy in a consumer\'s food that is converted to its own new biomass over a period of time is called _____. (<script type=\"text/javascript\">ebook(\'5503\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "primary production",
				false,
				"No. This refers to the new biomass created in primary producers.");
			
				p.addAnswer(2, "secondary production",
				true,
				"Correct. After a consumer feeds, only a portion of the food it consumes is converted to the organism\'s own biomass.");
			
				p.addAnswer(3, "production efficiency",
				false,
				"No. This refers to the fraction of food energy that is not used for respiration.");
			
				p.addAnswer(4, "assimilation of primary production",
				false,
				"No. Assimilation consists of the total energy taken in and used for growth, reproduction, and respiration.");
			
				p.addAnswer(5, "This question cannot be answered without knowing at which trophic level the organism feeds.",
				false,
				"No. The question can be answered without this information.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337128;


		
		

		
			
			p.question = "In the transition from each trophic level of the food chain to the next trophic level, there is about a _____. (<script type=\"text/javascript\">ebook(\'5503\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "90% gain of energy",
				false,
				"No. There is a net loss of energy as it is transferred from one trophic level to the next.");
			
				p.addAnswer(2, "2% gain of energy",
				false,
				"No. There is a net loss of energy as it is transferred from one trophic level to the next.");
			
				p.addAnswer(3, "90% loss of energy",
				true,
				"Correct. Ecological efficiencies vary greatly among organisms, but they are estimated to be about 5&#150;20%, meaning that 80&#150;95% of the energy in one level is not available to the next.");
			
				p.addAnswer(4, "2% loss of energy",
				false,
				"No. However, you are correct that there is a loss of energy.");
			
				p.addAnswer(5, "5% loss of energy",
				false,
				"No. However, you are correct that there is a loss of energy.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337129;


		
		

		
			
			p.question = "Which one of the following best describes the base of a pyramid of net production? (<script type=\"text/javascript\">ebook(\'5503\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Its size depends on the energy available from detritivores.",
				false,
				"No. Autotrophs are found at the base of such a pyramid.");
			
				p.addAnswer(2, "It contains the energy left after the producers have died.",
				false,
				"No. The base of a pyramid of net production consists of living autotrophs.");
			
				p.addAnswer(3, "It represents the energy available to secondary consumers.",
				false,
				"No. Primary consumers are found between the base of a pyramid of net production and secondary consumers.");
			
				p.addAnswer(4, "It contains the energy captured by photosynthesis.",
				true,
				"Correct. The trophic level that ultimately supports all others in an ecosystem consists of primary producers, which use light energy to synthesize organic molecules in photosynthesis.");
			
				p.addAnswer(5, "It receives energy from the primary, secondary, and tertiary consumers.",
				false,
				"No. In most instances, light is the source of energy for organisms occupying the base of a pyramid of net production.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337130;


		
		

		
			
			p.question = "In general, the biomass in an ecosystem will be greatest at the trophic level comprising _____. (<script type=\"text/javascript\">ebook(\'5503\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "producers",
				true,
				"Correct. Biomass pyramids generally narrow sharply from producers at the base to top-level carnivores at the apex because energy transfers between trophic levels are so inefficient.");
			
				p.addAnswer(2, "herbivores",
				false,
				"No. Herbivores are a step removed from the ultimate source of energy (the sun). Recall that energy transfers are not 100% efficient.");
			
				p.addAnswer(3, "primary consumers",
				false,
				"No. You need to consider the laws of thermodynamics as they relate to the transfer of energy from one trophic level to the next.");
			
				p.addAnswer(4, "tertiary consumers",
				false,
				"No. You need to consider the laws of thermodynamics as they relate to the transfer of energy from one trophic level to the next.");
			
				p.addAnswer(5, "secondary consumers",
				false,
				"No. You need to consider the laws of thermodynamics as they relate to the transfer of energy from one trophic level to the next.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337131;


		
		

		
			
			p.question = "In ecosystems, organisms at the highest trophic levels usually contain less collective biomass than the organisms at lower trophic levels because _____. (<script type=\"text/javascript\">ebook(\'5503\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "organisms are inefficient at converting the energy they consume into biomass",
				true,
				"Correct. Ecological efficiencies vary greatly among organisms, but they are estimated to be about 5&#150;20%, meaning that 80&#150;95% of the energy in one level is not available to the next.");
			
				p.addAnswer(2, "biomass shrinks as it rises",
				false,
				"No. Biomass does not shrink.");
			
				p.addAnswer(3, "top-level predators use so much energy to catch their food",
				false,
				"No. However, you must consider energy when answering the question.");
			
				p.addAnswer(4, "producers (for example, plants) tend to be heavier than consumers (for example, birds)",
				false,
				"No. You need to consider the question in terms of energetics.");
			
				p.addAnswer(5, "most of the solar energy hitting Earth is reflected or re-radiated into space",
				false,
				"No. Although this is a correct statement, you need to answer the question in terms of the laws of thermodynamics.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337132;


		
		

		
			
			p.question = "Which of the following is proposed by the green world hypothesis as a factor that keeps herbivores in check? (<script type=\"text/javascript\">ebook(\'5503\',\'quiz\')</script>)";
			p.incorrect_any_expl = "No. This is proposed by the green world hypothesis, but there is a better answer.";
			p.incorrect_any_expl_flag = 1;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Plants have defenses against herbivores.",
				false,
				"");
			
				p.addAnswer(2, "Intraspecific competition can limit herbivore numbers.",
				false,
				"");
			
				p.addAnswer(3, "Abiotic factors limit herbivores.",
				false,
				"");
			
				p.addAnswer(4, "Interspecific interactions check herbivore densities.",
				false,
				"");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct. All of these factors are thought to keep the Earth green by keeping herbivores in check.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337133;


		
		

		
			
			p.question = "What is the main abiotic reservoir for elements involved in local biogeochemical cycles such as calcium and phosphorus? (<script type=\"text/javascript\">ebook(\'5504\',\'quiz\')</script>)";
			p.incorrect_any_expl = "No. Soil is the main abiotic reservoir for these elements, which are absorbed by plants and then released back into soil by decomposers.";
			p.incorrect_any_expl_flag = 1;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "oceans",
				false,
				"");
			
				p.addAnswer(2, "rivers",
				false,
				"");
			
				p.addAnswer(3, "soil",
				true,
				"Correct. Soil is the main abiotic reservoir for these elements, which are absorbed by plants and then released back into soil by decomposers.");
			
				p.addAnswer(4, "wind",
				false,
				"");
			
				p.addAnswer(5, "the atmosphere",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337134;


		
		

		
			
			p.question = "Which of the following statements is correct? (<script type=\"text/javascript\">ebook(\'5504\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Over land, evaporation exceeds transpiration and precipitation.",
				false,
				"No. Transpiration is evaporative water loss from plants.");
			
				p.addAnswer(2, "Over land, evaporation and transpiration exceed precipitation.",
				false,
				"No. Over land, water gain by precipitation exceeds water loss by evaporation and transpiration.");
			
				p.addAnswer(3, "Over oceans, transpiration exceeds precipitation.",
				false,
				"No. Transpiration is evaporative water loss from terrestrial plants.");
			
				p.addAnswer(4, "Over oceans, evaporation exceeds precipitation.",
				true,
				"Correct. Runoff and groundwater flows to the oceans are responsible for balancing the water lost by evaporation.");
			
				p.addAnswer(5, "Most of Earth\'s water can be found in living systems.",
				false,
				"No. Only a small proportion of Earth\'s water is found in living systems.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337135;


		
		

		
			
			p.question = "The global hydrologic cycle supports a net flow of atmospheric water vapor ______. (<script type=\"text/javascript\">ebook(\'5504\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "from the oceans to land",
				true,
				"Correct. A net movement of water vapor is formed by evaporation from the sea to the land.");
			
				p.addAnswer(2, "from land to the oceans",
				false,
				"No. Consider that the oceans contain more water than land does.");
			
				p.addAnswer(3, "from polar to tropical regions",
				false,
				"No. You need to consider the largest bodies of water.");
			
				p.addAnswer(4, "from tropical to polar regions",
				false,
				"No. You need to consider the largest bodies of water.");
			
				p.addAnswer(5, "from unforested to forested biomes",
				false,
				"No. Evapotranspiration, the release of water to the atmosphere, is higher in forested than in unforested biomes.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337136;


		
		

		
			
			p.question = "Local conditions such as heavy rainfall or the removal of plants may limit the amount of nitrogen, phosphorus, or calcium available to a particular ecosystem, but the amount of carbon available to the system is seldom a problem. Why? (<script type=\"text/javascript\">ebook(\'5504\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Organisms do not need very much carbon.",
				false,
				"No. Life on Earth is based on carbon.");
			
				p.addAnswer(2, "Plants can make their own carbon using water and sunlight.",
				false,
				"No. As an element, carbon cannot be manufactured.");
			
				p.addAnswer(3, "Plants are much better at absorbing carbon from the soil.",
				false,
				"No. Plants do not acquire carbon from the soil.");
			
				p.addAnswer(4, "Many nutrients come from the soil, but carbon comes from the air.",
				true,
				"Correct. Nutrients in the soil are subject to runoff; atmospheric CO<sub>2</sub> is not.");
			
				p.addAnswer(5, "Symbiotic bacteria help plants capture carbon.",
				false,
				"No. Symbiotic bacteria play a major role in helping plants acquire nitrogen.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337137;


		
		

		
			
			p.question = "Which of the following is a key part of the carbon cycle? (<script type=\"text/javascript\">ebook(\'5504\',\'quiz\')</script>)";
			p.incorrect_any_expl = "No. This is a key part of the carbon cycle, but there is a better answer.";
			p.incorrect_any_expl_flag = 1;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "return of CO<sub>2</sub> to the atmosphere by microbial respiration in soils",
				false,
				"");
			
				p.addAnswer(2, "assimilation of atmospheric CO<sub>2</sub> by plant photosynthesis",
				false,
				"");
			
				p.addAnswer(3, "return of CO<sub>2</sub> to the atmosphere by animal and plant respiration",
				false,
				"");
			
				p.addAnswer(4, "breakdown by decomposers of carbon-containing dead plants and animals",
				false,
				"");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct. Carbon dioxide is released into the atmosphere by cellular respiration in all aerobic organisms and removed by photosynthesis.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337138;


		
		

		
			
			p.question = "By which process is carbon dioxide released from plants back to the atmosphere? (<script type=\"text/javascript\">ebook(\'5504\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "photosynthesis",
				false,
				"No. Photosynthesis uses atmospheric carbon dioxide.");
			
				p.addAnswer(2, "respiration",
				true,
				"Correct. Cellular respiration releases carbon dioxide back to the atmosphere.");
			
				p.addAnswer(3, "ammonification",
				false,
				"No. Ammonification is a component of the nitrogen cycle.");
			
				p.addAnswer(4, "phosphorylation",
				false,
				"No. Phosphorylation involves phosphorus.");
			
				p.addAnswer(5, "evaporation",
				false,
				"No. Evaporation is a component of the water cycle.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337139;


		
		

		
			
			p.question = "Bacteria are especially important in making _____ available to plants. (<script type=\"text/javascript\">ebook(\'5504\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "water",
				false,
				"No. Bacteria do not play a major role in the water cycle.");
			
				p.addAnswer(2, "nitrogen",
				true,
				"Correct. Nitrogen fixation by prokaryotes makes nitrogen available to plants.");
			
				p.addAnswer(3, "carbon",
				false,
				"No. Carbon, in the form of CO<sub>2</sub>, is made available by several processes, including respiration and the burning of fossil fuels.");
			
				p.addAnswer(4, "phosphorus",
				false,
				"No. Plants can utilize phosphorus in an inorganic form (PO<sub>4</sub><sup>3-</sup>).");
			
				p.addAnswer(5, "energy",
				false,
				"No. Plants obtain their energy from the sun.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337140;


		
		

		
			
			p.question = "The direct product of nitrogen fixation is _____. (<script type=\"text/javascript\">ebook(\'5504\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "NH<sub>4</sub><sup>+</sup>",
				false,
				"No. However, this is a form of nitrogen that plants can use.");
			
				p.addAnswer(2, "NO<sub>2</sub><sup>-</sup>",
				false,
				"No. The process of nitrification produces nitrite.");
			
				p.addAnswer(3, "NO<sub>3</sub><sup>-</sup>",
				false,
				"No. Nitrite is converted to nitrate (NO<sub>3</sub><sup>-</sup>) by nitrifying bacteria.");
			
				p.addAnswer(4, "NH<sub>3</sub>",
				true,
				"Correct. Ammonia is produced by nitrogen fixation. However, in the soil it is usually converted to ammonium (NH<sub>4</sub><sup>+</sup>) before being taken up by plants.");
			
				p.addAnswer(5, "N<sub>2</sub>",
				false,
				"No. Nitrogen fixation is a process that makes nitrogen available to plants.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337141;


		
		

		
			
			p.question = "Which one of the following is true of the nitrogen cycle? (<script type=\"text/javascript\">ebook(\'5504\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Bacteria are not involved in the process.",
				false,
				"No. The only organisms on Earth capable of fixing nitrogen are prokaryotes.");
			
				p.addAnswer(2, "Plants can take in and use atmospheric nitrogen through their leaves.",
				false,
				"No. Though nearly 80% of Earth\'s atmosphere is nitrogen, most of it is in the form of nitrogen gas, which is not available to plants.");
			
				p.addAnswer(3, "Some animals can use inorganic forms of nitrogen such as ammonium.",
				false,
				"No. Animals can only use nitrogen in organic form such as amino acids.");
			
				p.addAnswer(4, "When plants and animals die, the nitrogen within their bodies becomes unavailable.",
				false,
				"No. Decomposers break down the bodies of dead organisms, making nitrogen compounds available for use by other organisms.");
			
				p.addAnswer(5, "Nitrite is converted to nitrate (NO<sub>3</sub><sup>-</sup>) by nitrifying bacteria.",
				true,
				"Correct. This is one of the key processes in the nitrogen cycle.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337142;


		
		

		
			
			p.question = "The phosphorus cycle lacks a(n) _____ component. (<script type=\"text/javascript\">ebook(\'5504\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "atmospheric",
				true,
				"Correct. Gaseous phosphorus is insignificant.");
			
				p.addAnswer(2, "organic",
				false,
				"No. Living organisms are a part of the phosphorus cycle.");
			
				p.addAnswer(3, "mineral",
				false,
				"No. The inorganic form of phosphorus (PO<sub>4</sub><sup>3-</sup>) is the form absorbed by plants.");
			
				p.addAnswer(4, "aquatic",
				false,
				"No. Phosphorus is found in water.");
			
				p.addAnswer(5, "organic and gaseous",
				false,
				"No. Living organisms are a part of the phosphorus cycle, although gaseous phosphorus is insignificant.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337143;


		
		

		
			
			p.question = "When researchers at Hubbard Brook Experimental Forest cut down trees and measured subsequent mineral levels in the soil, they found that _____. (<script type=\"text/javascript\">ebook(\'5504\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the mineral levels were unaffected as long as the tree remains were not removed",
				false,
				"No. They discovered that the amount of nutrients leaving an intact forest is controlled by plants.");
			
				p.addAnswer(2, "primary production was not affected as long as Ca<sup>2+</sup> was added to the soil",
				false,
				"No. In a separate experiment, Hubbard Brook researchers tested the possibility of growth limitation due to inadequate supplies of calcium.");
			
				p.addAnswer(3, "the forest was able to grow back before mineral levels changed significantly",
				false,
				"No. The researchers sprayed the land with herbicides to prevent the forest from growing back.");
			
				p.addAnswer(4, "the amount of nutrients leaving an intact forest ecosystem is controlled by the plants",
				true,
				"Correct. Without plants to absorb water and dissolved minerals from the soil, the minerals were washed away in runoff.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337144;


		
		

		
			
			p.question = "How have human activities increased the supply of fixed nitrogen available to primary producers? (<script type=\"text/javascript\">ebook(\'5505\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "use of nitrogen fertilizers",
				false,
				"No. This answer is correct, but there is a better response.");
			
				p.addAnswer(2, "increased cultivation of legumes",
				false,
				"No. This answer is correct, but there is a better response.");
			
				p.addAnswer(3, "deliberate burning of fields",
				false,
				"No. This answer is correct, but there is a better response.");
			
				p.addAnswer(4, "both a and c",
				false,
				"No. This answer is correct, but there is a better response.");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct. These tactics help agriculture, but they may hurt the environment in other ways. For example, dentrifying bacteria release nitrogen oxides into the air, which contribute to atmospheric warming, depletion of atmospheric ozone, and sometimes to acid rain.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337145;


		
		

		
			
			p.question = "Why are freshwater ecosystems in North America and northern Europe particularly sensitive to the effects of acid rain? (<script type=\"text/javascript\">ebook(\'5505\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The water in these areas is acidic to begin with.",
				false,
				"No. The lakes are sensitive to acid rain because they have relatively poor buffering capacity due to low levels of bicarbonate.");
			
				p.addAnswer(2, "The lakes tend to have relatively poor buffering capacity.",
				true,
				"Correct. Remember from Chapter 3 that buffering capacity allows a solution to accept more hydrogen ions before pH level is affected.");
			
				p.addAnswer(3, "The wildlife in these areas tends to be more sensitive to change in pH.",
				false,
				"No. There is no evidence that the wildlife is these areas is any more sensitive to pH change than in other areas.");
			
				p.addAnswer(4, "Other types of industrial pollution tend to magnify the effects of acid rain.",
				false,
				"No. The lakes are sensitive to acid rain because they have relatively poor buffering capacity due to low levels of bicarbonate.");
			
				p.addAnswer(5, "Environmental regulations have not reduced the levels of sulfur dioxide emissions in these areas.",
				false,
				"No. At least in the United States, sulfur dioxide emissions have dropped by approximately 30% during the last decade.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337146;


		
		

		
			
			p.question = "_____ are the most affected by toxic compounds in the environment because _____. (<script type=\"text/javascript\">ebook(\'5505\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Cyanobacteria; many of these compounds prevent nitrogen fixation",
				false,
				"No. Cyanobacteria are not the most affected");
			
				p.addAnswer(2, "Phytoplankton; many of these compounds halt photosynthesis",
				false,
				"No. Phytoplankton are not the most affected.");
			
				p.addAnswer(3, "Primary consumers; they consume primary producers containing the compounds",
				false,
				"No. Primary consumers are not the most affected.");
			
				p.addAnswer(4, "Top-level carnivores; the biomass at any given trophic level is produced from a larger biomass ingested at the level below",
				true,
				"Correct. Through the process of biomagnification, the concentration of these toxic compounds increases in each subsequent trophic level.");
			
				p.addAnswer(5, "Herbivores; plants tend to store these toxic compounds in large quantities.",
				false,
				"No. It is really the top-level carnivores that are most affected.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337147;


		
		

		
			
			p.question = "Which of the following is thought to be a possible consequence of rising CO<sub>2</sub> levels? (<script type=\"text/javascript\">ebook(\'5505\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "C<sub>3</sub> crops, such as wheat and soybeans being replaced by more C<sub>4</sub> plants such as corn.",
				false,
				"No. Rising CO<sub>2</sub> levels would tend to favor C<sub>3</sub> crops rather than C<sub>4</sub> crops.");
			
				p.addAnswer(2, "falling global temperature",
				false,
				"No. Although this possibility has been portrayed in movies, it is not considered a very likely scenario.");
			
				p.addAnswer(3, "increased breakdown of atmospheric ozone",
				false,
				"No. Rising carbon dioxide levels do not affect the ozone layer. CFCs break down ozone.");
			
				p.addAnswer(4, "increased vegetative productivity",
				true,
				"Correct. This is a possible consequence. With more carbon dioxide and adequate supplies of water and sunlight, plants can build more biomass although other nutrients may limit production.");
			
				p.addAnswer(5, "More rapid warming at the equator than at the poles",
				false,
				"No. The effects of global warming are more noticeable at the poles because the loss of ice and snow increases the amount of solar energy absorbed by the land and water, creating a feedback effect that speeds warming in those areas.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337148;


		
		

		
			
			p.question = "How do climatologists estimate past atmospheric CO<sub>2</sub> concentrations? (<script type=\"text/javascript\">ebook(\'5505\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "They extrapolate back through time based on the current rise in CO<sub>2</sub> levels.",
				false,
				"No. The current rate of increase is considered to be very high compared to that in the past. Also, data show that CO<sub>2</sub> levels have fluctuated greatly in the past. Extrapolation would probably be very inaccurate.");
			
				p.addAnswer(2, "They measure the CO<sub>2</sub> concentrations in air bubbles trapped in glacial ice.",
				true,
				"Correct. Bubbles trapped in glacial ice give a \"snapshot\" of the atmosphere at the time they were incorporated into the ice.");
			
				p.addAnswer(3, "They measure radioactive isotopes in shark teeth.",
				false,
				"No. This is not a method currently used to measure ancient CO<sub>2</sub> levels.");
			
				p.addAnswer(4, "They analyze fossils of ancient vegetation.",
				false,
				"No. Analyzing ancient plant fossils can give us an idea of the temperature and climate, but they are not a good way of directly measuring CO<sub>2</sub> levels.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. Only one of the above answers is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337149;


		
		

		
			
			p.question = "Ozone is _____. (<script type=\"text/javascript\">ebook(\'5505\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "harmful in the upper atmosphere",
				false,
				"No. Ozone, in the upper atmosphere, filters out UV radiation.");
			
				p.addAnswer(2, "beneficial in the upper atmosphere",
				true,
				"Correct. Ozone protects Earth by absorbing UV radiation. The consequences of ozone depletion for life on Earth may be quite severe.");
			
				p.addAnswer(3, "beneficial in the lower atmosphere",
				false,
				"No. Ozone has harmful effects on lung function, for example.");
			
				p.addAnswer(4, "harmful in the upper atmosphere and beneficial in the lower atmosphere",
				false,
				"No. In the lower atmosphere, ozone has adverse effects on lung function.");
			
				p.addAnswer(5, "beneficial in both the upper atmosphere and the lower atmosphere",
				false,
				"No. In the lower atmosphere, ozone has adverse effects on lung function.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337150;


		
		

		
			
			p.question = "The destruction of the ozone layer is most directly linked to _____. (<script type=\"text/javascript\">ebook(\'5505\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "increasing levels of CO<sub>2</sub> in the atmosphere",
				false,
				"No. Increasing carbon dioxide levels contribute to the greenhouse effect.");
			
				p.addAnswer(2, "destruction of tropical rain forests",
				false,
				"No. Among other environmental problems, the destruction of tropical rain forests contributes to the greenhouse effect.");
			
				p.addAnswer(3, "release of chlorofluorocarbons (CFCs) into the atmosphere",
				true,
				"Correct. The destruction of atmospheric ozone probably results from the accumulation of CFCs.");
			
				p.addAnswer(4, "decrease in the production of ozone precursors by chemical production plants",
				false,
				"No. The question asks about ozone destruction, not ozone production.");
			
				p.addAnswer(5, "global warming",
				false,
				"No. Increasing carbon dioxide levels contribute to the greenhouse effect and global warming.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

