

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "43: The Immune System > Practice Test";
	ak.quiz_loc_with_commas = "43: The Immune System, Practice Test";
	ak.quiz_title = "Practice Test";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 39;
	ak.non_essay_total = 39;
	ak.scored_item_total = 39;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336496;


		
		

		
			
			p.question = "Which of the following is a characteristic of acquired immunity? (<script type=\"text/javascript\">ebook(\'43OV\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "It is found only in invertebrates.",
				false,
				"No. Acquired immunity is found only in vertebrates.");
			
				p.addAnswer(2, "Responses are the same whether or not the pathogen has been encountered previously.",
				false,
				"No. This is characteristic of innate immunity.");
			
				p.addAnswer(3, "Responses are active immediately upon infection.",
				false,
				"No. This is characteristic of innate immunity.");
			
				p.addAnswer(4, "It is common to all animals.",
				false,
				"No. This is characteristic of innate immunity.");
			
				p.addAnswer(5, "It has the ability to detect pathogens with tremendous specificity.",
				true,
				"Correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336497;


		
		

		
			
			p.question = "In humans, the first line of defense against infection is _____. (<script type=\"text/javascript\">ebook(\'43OV\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the skin and mucous membranes",
				true,
				"Correct. The skin and mucous membranes provide first-line barriers to infection.");
			
				p.addAnswer(2, "the inflammatory response",
				false,
				"No. The inflammatory response occurs after an infection has already occurred.");
			
				p.addAnswer(3, "the immune system",
				false,
				"No. The immune system is activated when innate barriers fail.");
			
				p.addAnswer(4, "antibiotics",
				false,
				"No. Antibiotics are given to treat bacterial infections that have already crossed the first lines of defense.");
			
				p.addAnswer(5, "disinfectants",
				false,
				"No. These are chemical agents that are designed to kill microorganisms before they can come in contact with your immune system.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336498;


		
		

		
			
			p.question = "Phagocytosis is best defined as _____. (<script type=\"text/javascript\">ebook(\'4301\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the ingestion and digestion of bacteria and other foreign substances",
				true,
				"Correct.");
			
				p.addAnswer(2, "the process by which a cell engulfs and takes up a liquid",
				false,
				"No. This is pinocytosis.");
			
				p.addAnswer(3, "the movement of cytoplasm into an extended pseudopodium",
				false,
				"No. Cyclosis is cytoplasmic streaming.");
			
				p.addAnswer(4, "the fusion of an intracellular vesicle with the plasma membrane of a cell",
				false,
				"No. Exocytosis occurs when a vacuole fuses with the plasma membrane and the contents are released to the exterior.");
			
				p.addAnswer(5, "the process of activating memory T cells",
				false,
				"No. Memory T cells are activated by the presentation of antigens by antigen-presenting cells.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336499;


		
		

		
			
			p.question = "Insects rely on _____ as a first line of defense against infection. (<script type=\"text/javascript\">ebook(\'4301\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "their exoskeleton",
				true,
				"Correct.");
			
				p.addAnswer(2, "lysozymes",
				false,
				"No. These enzymes are found within the digestive system");
			
				p.addAnswer(3, "hemocytes that engage in phagocytosis",
				false,
				"No. Hemocytes attack pathogens that have breached an insect\'s barrier defenses.");
			
				p.addAnswer(4, "the production of chemicals that kill microbes",
				false,
				"No. Such chemicals are produced by hemocytes that attack pathogens that have breached an insect\'s barrier defenses.");
			
				p.addAnswer(5, "the production of a distinct class of antimicrobial peptides",
				false,
				"No. Such chemicals are produced by immune response cells that attack pathogens that have breached an insect\'s barrier defenses.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336500;


		
		

		
			
			p.question = "What do macrophages and neutrophils have in common? (<script type=\"text/javascript\">ebook(\'4301\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "They punch a hole in the plasma membrane of the pathogen, causing the cell to burst.",
				false,
				"No. This is accomplished by complement proteins.");
			
				p.addAnswer(2, "They phagocytize pathogens.",
				true,
				"Correct. Neutrophils are phagocytic cells that constitute 60&#150;70% of all white blood cells. Macrophages, which develop from monocytes, are long-lived phagocytes.");
			
				p.addAnswer(3, "They secrete lysozyme.",
				false,
				"No. Lysozyme is found in saliva, tears, and mucous secretions.");
			
				p.addAnswer(4, "They stimulate antibody production.",
				false,
				"No. Helper T cells stimulate antibody production by plasma cells.");
			
				p.addAnswer(5, "They attack virus-infected body cells.",
				false,
				"No. Cytotoxic T cells attack infected body cells.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336501;


		
		

		
			
			p.question = "Which of the following cells are part of the innate, second line of defense? (<script type=\"text/javascript\">ebook(\'4301\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "cytotoxic T cells",
				false,
				"No. T cells play a role in acquired immunity.");
			
				p.addAnswer(2, "B cells",
				false,
				"No. B cells play a role in acquired immunity.");
			
				p.addAnswer(3, "prostaglandins",
				false,
				"No. Prostaglandins are a class of hormone.");
			
				p.addAnswer(4, "macrophages",
				true,
				"Correct. The second line of defense includes phagocytic white blood cells, such as macrophages, antimicrobial proteins, and the inflammatory response.");
			
				p.addAnswer(5, "platelets",
				false,
				"No. Platelets play a role in blood clotting.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336502;


		
		

		
			
			p.question = "Which statement describes what would most likely happen to microbes in the blood? (<script type=\"text/javascript\">ebook(\'4301\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "They are phagocytosed by eosinophils.",
				false,
				"No. Eosinophils can engulf pathogens, but generally they attack larger parasites by discharging destructive enzymes that damage them. There is a better answer.");
			
				p.addAnswer(2, "They are phagocytosed by macrophages that reside in the lymph nodes.",
				false,
				"No. This is one possible fate of microbes in interstitial fluid.");
			
				p.addAnswer(3, "They are phagocytosed by macrophages that reside in the spleen.",
				true,
				"Correct. Microbes are trapped in the netlike architecture of the spleen and then are attacked by macrophages.");
			
				p.addAnswer(4, "They are phagocytosed by neutrophils.",
				false,
				"No. Neutrophils engulf and destroy microbes in infected tissues.");
			
				p.addAnswer(5, "They are phagocytosed by monocytes.",
				false,
				"No. Macrophages develop from monocytes.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336503;


		
		

		
			
			p.question = "Chemicals produced by virus-infected cells that alert neighboring cells to prepare a defense are called _____. (<script type=\"text/javascript\">ebook(\'4301\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "antibodies",
				false,
				"No. Antibody production by plasma cells is an aspect of acquired immunity.");
			
				p.addAnswer(2, "interferons",
				true,
				"Correct. Interferon is a chemical messenger of the immune system, produced by virus-infected cells and capable of helping other cells resist the infection.");
			
				p.addAnswer(3, "cytokines",
				false,
				"No. Cytokines play a role in acquired immunity.");
			
				p.addAnswer(4, "antigens",
				false,
				"No. Antibodies are produced in response to antigens.");
			
				p.addAnswer(5, "complement proteins",
				false,
				"No. Although this is an aspect of innate immunity, this is a group of proteins that circulate in the blood.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336504;


		
		

		
			
			p.question = "If microorganisms penetrate the innate defenses, an inflammatory response may be initiated by the _____. (<script type=\"text/javascript\">ebook(\'4301\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "accumulation of phagocytes in an injured area",
				false,
				"No. The movement of phagocytes via chemotaxis is an aspect of the inflammatory response.");
			
				p.addAnswer(2, "release of interferon by infected cells",
				false,
				"No. Interferon, which is released when cells are infected with a virus, interferes with protein synthesis in uninfected cells.");
			
				p.addAnswer(3, "increased blood flow to an infected or injured area",
				false,
				"No. It\'s correct that during an inflammatory response, blood flow to an injured area will increase, but changes in blood flow do not initiate the inflammation.");
			
				p.addAnswer(4, "ensuing fever",
				false,
				"No. A fever, one type of systemic response to infection, is considered a component of inflammation.");
			
				p.addAnswer(5, "release of chemicals such as histamine by mast cells",
				true,
				"Correct. Histamine and prostaglandins are among the most commonly released chemicals.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336505;


		
		

		
			
			p.question = "Local swelling, increased blood flow, and fever are all parts of _____. (<script type=\"text/javascript\">ebook(\'4301\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "active immunity",
				false,
				"No. This is a component of acquired immunity.");
			
				p.addAnswer(2, "an inflammatory response",
				true,
				"Correct. This line of defense includes phagocytic white blood cells, antimicrobial proteins, and the inflammatory response.");
			
				p.addAnswer(3, "passive immunity",
				false,
				"No. Passive immunity is acquired when antibodies are passed from one individual to another or when an individual is given an injection of antiserum.");
			
				p.addAnswer(4, "cell-mediated immunity",
				false,
				"No. This is a component of acquired immunity.");
			
				p.addAnswer(5, "humoral immunity",
				false,
				"No. This is a component of acquired immunity.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336506;


		
		

		
			
			p.question = "Which one of the following is part of the inflammatory response? (<script type=\"text/javascript\">ebook(\'4301\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "constriction of the arterioles",
				false,
				"No. Blood flow carries white blood cells to the injured site.");
			
				p.addAnswer(2, "clonal selection of B and T lymphocytes followed by the production of effector cells",
				false,
				"No. B and T cells are involved in acquired immunity.");
			
				p.addAnswer(3, "dilation of the capillaries",
				true,
				"Correct. Histamine triggers the dilation and increased permeability of nearby capillaries.");
			
				p.addAnswer(4, "production of antibodies",
				false,
				"No. Antibody production is an aspect of acquired immunity.");
			
				p.addAnswer(5, "production of memory cells",
				false,
				"No. Memory cell production is an aspect of acquired immunity.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336507;


		
		

		
			
			p.question = "Which of the following is an immediate function of histamine? (<script type=\"text/javascript\">ebook(\'4301\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "causing local arterioles to constrict",
				false,
				"No. Histamine causes local arterioles to dilate.");
			
				p.addAnswer(2, "decreasing the permeability of local capillaries",
				false,
				"No. Histamine causes an increase in the permeability of local capillaries.");
			
				p.addAnswer(3, "increasing the systemic blood pressure",
				false,
				"No. Histamine triggers the dilation and increased permeability of nearby capillaries. Redness and swelling accompany the entry of phagocytic cells into the area.");
			
				p.addAnswer(4, "causing local swelling of the tissue",
				true,
				"Correct. This is a result of histamine function.");
			
				p.addAnswer(5, "decreasing local reddening of the tissue",
				false,
				"No. Histamine causes local reddening of the tissue.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336508;


		
		

		
			
			p.question = "Which of the following is a benefit of local inflammation? (<script type=\"text/javascript\">ebook(\'4301\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "decreased blood flow and decreased vessel permeability",
				false,
				"No. Inflamation causes increased blood flow and increased vessel permeability, which allows more neutrophils to move from the blood to injured tissues.");
			
				p.addAnswer(2, "Vascular changes decrease the volume of clotting factors in the area.",
				false,
				"No. Vascular changes increase the volume of clotting factors in the area.");
			
				p.addAnswer(3, "Chemokines promote the release of histamine and attract more phagocytes to the area.",
				false,
				"No. Complement proteins promote the release of histamine and attract more phagocytes to the area. Chemokines direct the migration of phagocytes to the site of inflammation and signal them to increase production of microbe-killing compounds.");
			
				p.addAnswer(4, "all of the above",
				false,
				"No. None of the above are benefits of local inflammation.");
			
				p.addAnswer(5, "none of the above",
				true,
				"Correct. None of the responses correctly describes the benefits of local inflammation.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336509;


		
		

		
			
			p.question = "Which type of cell is responsible for causing apoptosis in cancer cells and virus-infected cells? (<script type=\"text/javascript\">ebook(\'4301\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "dendritic cells",
				false,
				"No. These are cells that ingest microbes by phagocytosis. Their primary role is to stimulate the development of acquired immunity.");
			
				p.addAnswer(2, "natural killer cells",
				true,
				"Correct. Once natural killer cells are attached to a virus-infected cell or cancer cell they release chemicals that lead to the programmed death of the cell.");
			
				p.addAnswer(3, "helper T cells",
				false,
				"No. Helper T cells secrete cytokines that stimulate other lymphocytes.");
			
				p.addAnswer(4, "plasma cells",
				false,
				"No. Plasma cells secrete antibodies.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336510;


		
		

		
			
			p.question = "Which choice below describes a function of white blood cells that helps them carry out defensive functions more effectively? (<script type=\"text/javascript\">ebook(\'4302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "synthesis of hemoglobin",
				false,
				"No. Hemoglobin is synthesized during the production of red blood cells.");
			
				p.addAnswer(2, "release of cytokines",
				true,
				"Correct. Cytokines help recruit and activate lymphocytes.");
			
				p.addAnswer(3, "restriction of their movements to regions within the bone marrow or lymph glands",
				false,
				"No. Phagocytic white blood cells move from the circulatory system to the site of injury. Some macrophages migrate throughout the body.");
			
				p.addAnswer(4, "release of clotting factors",
				false,
				"No. Clotting factors are not produced by white blood cells.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the answers is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336511;


		
		

		
			
			p.question = "An immune response is initiated by the presence of which molecules? (<script type=\"text/javascript\">ebook(\'4302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "complement",
				false,
				"No. Complement proteins play a role in innate immunity.");
			
				p.addAnswer(2, "interferon",
				false,
				"No. Interferons play a role in innate immunity.");
			
				p.addAnswer(3, "histamine",
				false,
				"No. Injured cells produce histamines.");
			
				p.addAnswer(4, "antibody",
				false,
				"No. Antibodies are a component of the immune response referred to in the question.");
			
				p.addAnswer(5, "antigen",
				true,
				"Correct. A foreign molecule that elicits a specific response by a lymphocyte is called an antigen.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336512;


		
		

		
			
			p.question = "The body produces antibodies complementary to foreign antigens. The process by which the body comes up with the correct antibodies to a specific invader is most like _____. (<script type=\"text/javascript\">ebook(\'4302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "going to a tailor and having a suit made to fit you",
				false,
				"No. In this example, the suit is specifically modified to fit you after you have arrived at the tailor\'s shop. Are antibody molecules modified once synthesized?");
			
				p.addAnswer(2, "ordering the lunch special at a restaurant without looking at the menu",
				false,
				"No. Selecting an antibody randomly has an extremely low probability of success. Think about the basis for antibody-antigen binding.");
			
				p.addAnswer(3, "going to a shoe store and trying on shoes until you find a pair that fits",
				true,
				"Correct. Unless an immune cell with the appropriate surface receptor exists prior to the infection, no immune response will be possible.");
			
				p.addAnswer(4, "picking out a video that you have not seen",
				false,
				"No. Selecting an antibody randomly has an extremely low probability of success. Think about the basis for antibody-antigen binding.");
			
				p.addAnswer(5, "selecting a lottery prize winner by means of a random drawing",
				false,
				"No. Selecting an antibody randomly has an extremely low probability of success. Think about the basis for antibody-antigen binding.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336513;


		
		

		
			
			p.question = "The antigen-binding sites of an antibody molecule are formed from the molecule\'s variable regions. Why are these regions called variable? (<script type=\"text/javascript\">ebook(\'4302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "They can change their shapes to fit different antigens.",
				false,
				"No. The shape of the binding area is constant throughout the life of the antibody.");
			
				p.addAnswer(2, "They change their shapes when they bind to an antigen.",
				false,
				"No. However, there is a slight conformational change upon antigen binding.");
			
				p.addAnswer(3, "Their specific shapes are unimportant.",
				false,
				"No. Just the opposite is true. The shape of the binding site is critically important; the shape determines what antigen the antibody can bind to.");
			
				p.addAnswer(4, "They can be different shapes on different antibody molecules.",
				true,
				"Correct. The amino acid sequence for these regions varies extensively from one B cell to another.");
			
				p.addAnswer(5, "Their sizes vary considerably from one antibody to another.",
				false,
				"No. The binding sites are quite similar in size.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336514;


		
		

		
			
			p.question = "Antibodies are in which class of proteins? (<script type=\"text/javascript\">ebook(\'4302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "structural",
				false,
				"No. Antibodies do not provide structure to either the body or cells.");
			
				p.addAnswer(2, "enzymatic",
				false,
				"No. Antibodies are not enzymes.");
			
				p.addAnswer(3, "transport",
				false,
				"No. Antibodies are not transport proteins.");
			
				p.addAnswer(4, "immunoglobulin",
				true,
				"Correct. An antibody is an antigen-binding immunoglobulin, produced by B cells, which functions as the effector in the immune response.");
			
				p.addAnswer(5, "receptor",
				false,
				"No. Antibodies bind to antigens, but they are not considered to be receptor proteins.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336515;


		
		

		
			
			p.question = "Once you have been exposed to an antigen, you develop immunity against the same antigen because _____. (<script type=\"text/javascript\">ebook(\'4302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "antibodies against the disease are constantly circulating in your blood",
				false,
				"No. While some antibodies may remain from an initial exposure to an antigen, immunity is related more to the ability to produce antibodies quickly.");
			
				p.addAnswer(2, "certain lymphocytes are able to make the proper antibodies quickly",
				true,
				"Correct. These lymphocytes are called memory cells. On later exposure to the antigen, a rapid response occurs and effector cells are quickly produced.");
			
				p.addAnswer(3, "your innate defenses are strengthened",
				false,
				"No. Immunity is always associated with a specific disease.");
			
				p.addAnswer(4, "B cells are stimulated to quickly engulf invaders",
				false,
				"No. Although B cells are phagocytic, their more important action is related to antibody production.");
			
				p.addAnswer(5, "antigens are altered so that the invaders can no longer attack your tissues",
				false,
				"No. Some pathogens alter their surface antigens, which does prevent memory cells from recognizing them, but this is not the best answer.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336516;


		
		

		
			
			p.question = "In a series of immune system experiments, the thymus glands were removed from baby mice. Which of the following would you predict as a likely result? (<script type=\"text/javascript\">ebook(\'4302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The mice suffered from numerous allergies.",
				false,
				"No. You would expect just the opposite.");
			
				p.addAnswer(2, "The mice never developed cancerous tumors.",
				false,
				"No. It is more likely that the mice would have a higher incidence of cancers than the control mice, whose thymus glands were not removed.");
			
				p.addAnswer(3, "The mice suffered from autoimmune diseases.",
				false,
				"No. It is unlikely that the mice would suffer from any autoimmune disease.");
			
				p.addAnswer(4, "The mice readily accepted tissue transplants.",
				true,
				"Correct. The thymus is necessary for the proper maturation of T cells. Without helper and cytotoxic T cells, there would no effective immune response.");
			
				p.addAnswer(5, "The mice were unable to produce an inflammatory response.",
				false,
				"No. Inflammation is a result of the release of locally active chemicals, such as histamine. The response does not depend on components of the acquired immune system.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336517;


		
		

		
			
			p.question = "The proliferation of the B lymphocyte to which a specific antigen binds is referred to as _____.  (<script type=\"text/javascript\">ebook(\'4302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "No. When an antigen binds to a B cell or a T cell, the cell proliferates, forming clones of effector cells with the same specificity. This process is called clonal selection.";
			p.incorrect_any_expl_flag = 1;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "an activation sequence",
				false,
				"");
			
				p.addAnswer(2, "a cascade mechanism",
				false,
				"");
			
				p.addAnswer(3, "antigenic determination",
				false,
				"");
			
				p.addAnswer(4, "an autoimmune response",
				false,
				"");
			
				p.addAnswer(5, "clonal selection",
				true,
				"Correct. When an antigen binds to a B cell or a T cell, that cell proliferates, forming clones of effector cells with the same specificity.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336518;


		
		

		
			
			p.question = "B lymphocytes _____. (<script type=\"text/javascript\">ebook(\'4302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "attack cells that have been infected by viruses",
				false,
				"No. Cytotoxic T cells attack cells that have been infected by viruses.");
			
				p.addAnswer(2, "engulf and destroy bacteria and viruses",
				false,
				"No. Macrophages engulf and destroy bacteria and viruses.");
			
				p.addAnswer(3, "multiply and make antibodies that circulate in blood and lymph",
				true,
				"Correct. B lymphocytes that make antibodies are called plasma cells.");
			
				p.addAnswer(4, "stimulate other lymphocytes",
				false,
				"No. Helper T cells stimulate other lymphocytes.");
			
				p.addAnswer(5, "produce cytokines",
				false,
				"No. Helper T cells and antigen-presenting cells produce cytokines.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336519;


		
		

		
			
			p.question = "Which of the following types of cells initiate a secondary immune response? (<script type=\"text/javascript\">ebook(\'4302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "cytotoxic cells",
				false,
				"No. Cytotoxic cells are responsible for lysing virus-infected cells and cancerous body cells.");
			
				p.addAnswer(2, "natural killer cells",
				false,
				"No. Natural killer cells play a role in innate immunity.");
			
				p.addAnswer(3, "memory cells",
				true,
				"Correct. The secondary immune response, which depends on memory cells, provides long-term protection after exposure to a pathogen.");
			
				p.addAnswer(4, "effector cells",
				false,
				"No. Effector cells are produced following clonal selection of either B cells or T cells. They are short-lived.");
			
				p.addAnswer(5, "plasma cells",
				false,
				"No. Plasma cells produce antibodies.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336520;


		
		

		
			
			p.question = "Our immune system does not usually attack our own healthy tissues because such lymphocytes are _____. (<script type=\"text/javascript\">ebook(\'4302\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "destroyed or rendered nonfunctional",
				true,
				"Correct.");
			
				p.addAnswer(2, "never produced",
				false,
				"No. Lymphocytes that could attack healthy tissues are produced during development.");
			
				p.addAnswer(3, "converted into other cells of the immune system",
				false,
				"No. These cells are not converted into another cell type.");
			
				p.addAnswer(4, "all of the above",
				false,
				"No. Only one of the choices is correct.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336521;


		
		

		
			
			p.question = "Which of the following cell types is specifically responsible for humoral immunity? (<script type=\"text/javascript\">ebook(\'4303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "T cells",
				false,
				"No. T cells are responsible for cell-mediated immunity.");
			
				p.addAnswer(2, "B cells",
				true,
				"Correct. Humoral immunity involves B cell activation and the production of antibodies by plasma cells.");
			
				p.addAnswer(3, "leukocytes",
				false,
				"No. The answer is more specific.");
			
				p.addAnswer(4, "natural killer cells",
				false,
				"No. Natural killer cells play a role in innate immunity.");
			
				p.addAnswer(5, "lymphocytes",
				false,
				"No. The answer is more specific.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336522;


		
		

		
			
			p.question = "What is the role of dendritic cells in the primary immune response? (<script type=\"text/javascript\">ebook(\'4303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Dendritic cells present antigen via class II MHC molecules to young helper T cells.",
				true,
				"Correct. Dendritic cells capture antigens in infected tissues. Then the cells migrate to lymphoid tissues where they present the antigen to the helper T cells.");
			
				p.addAnswer(2, "Dendritic cells present antigen to memory helper T cells.",
				false,
				"No. This is a function of macrophages and initiates secondary immune response.");
			
				p.addAnswer(3, "Dendritic cells secrete cytokines to activate cytotoxic T cells.",
				false,
				"No. Helper T cells secrete cytokines to activate cytotoxic T cells.");
			
				p.addAnswer(4, "Dendritic cells take in foreign molecules by receptor-mediated endocytosis and present the specific antigen fragments to helper T cells.",
				false,
				"No. This describes an action of B cells.");
			
				p.addAnswer(5, "Dendritic cells discharge destructive enzymes that damage larger parasitic invaders.",
				false,
				"No. This describes the action of eosinophils.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336523;


		
		

		
			
			p.question = "A group of researchers tested many chemicals and found several that have potential for use in modifying the action of the immune system. Which of the following compounds has the most promise as a drug for inhibiting transplant rejection?  (<script type=\"text/javascript\">ebook(\'4303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "compound A13: acts like histamine",
				false,
				"No. Histamine is primarily responsible for tissue inflammation. It would be more desirable to suppress the action of histamine.");
			
				p.addAnswer(2, "compound Q6: stimulates cytotoxic T cells",
				false,
				"No. Cytotoxic T cells mediate cellular immunity and are responsible for transplant rejection. A substance that promotes the activity of cytotoxic T cells would only make transplant rejection more likely.");
			
				p.addAnswer(3, "compound N98: a potent allergen",
				false,
				"No. Allergens are nonpathogenic substances that stimulate the immune system.");
			
				p.addAnswer(4, "compound B55: suppresses specific cytotoxic T cells",
				true,
				"Correct. Since most transplant rejection occurs because of T cell attack, suppressing T cells would be most promising.");
			
				p.addAnswer(5, "compound M31: stimulates helper T cells",
				false,
				"No. You would not want to stimulate T cells; most transplant rejection occurs because of T cell attack.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336524;


		
		

		
			
			p.question = "Which one of the following classes of immunoglobins crosses the placenta and confers passive immunity to the fetus? (<script type=\"text/javascript\">ebook(\'4303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "IgM",
				false,
				"No. IgM is too large to cross the placenta.");
			
				p.addAnswer(2, "IgG",
				true,
				"Correct. It is the most abundant of circulatory antibodies and protects against microbes and toxins in the blood and lymph.");
			
				p.addAnswer(3, "IgA",
				false,
				"No. But this class is present in the first milk.");
			
				p.addAnswer(4, "IgD",
				false,
				"No. These antibodies are mostly found on the surface of B cells and do not cross the placenta.");
			
				p.addAnswer(5, "IgE",
				false,
				"No. These antibodies are responsible for allergic reactions.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336525;


		
		

		
			
			p.question = "A viral infection in a cell results in _____. (<script type=\"text/javascript\">ebook(\'4303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "activation of complement proteins",
				false,
				"No. The complement system is activated by antibody-antigen binding. Complement components assemble on the pathogen\'s plasma membrane and, when complete, puncture it.");
			
				p.addAnswer(2, "secretion of interferon",
				true,
				"Correct. Interferon is released by virus-infected cells. Taken up by uninfected cells, it induces them to produce molecules that inhibit viral replication.");
			
				p.addAnswer(3, "neutralization",
				false,
				"No. Neutralization is a result of antibody-antigen binding.");
			
				p.addAnswer(4, "agglutination",
				false,
				"No. Agglutination is a result of antibody-antigen binding.");
			
				p.addAnswer(5, "precipitation",
				false,
				"No. Precipitation is a result of antibodies binding to soluble antigens.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336526;


		
		

		
			
			p.question = "What do the antibodies secreted by plasma cells (the effector cells of humoral immunity) do to attack their targets? (<script type=\"text/javascript\">ebook(\'4303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "activate complement to form a pore in the membrane of the targets",
				false,
				"No. It is correct that once the antibody binds to the microorganism, a complement-binding site on the antibody molecule is exposed. But there is a better answer.");
			
				p.addAnswer(2, "clump cells together so that phagocytes can ingest them",
				false,
				"No. It is correct that antibodies can bind to more than one antigen, which leads to agglutination. But there is a better answer.");
			
				p.addAnswer(3, "cross-link soluble antigen molecules, forming immobile aggregates",
				false,
				"No. It is correct that antibodies may immobilize soluble antigen molecules so that phagocytes have better access to them. But there is a better answer.");
			
				p.addAnswer(4, "attach to antigens and block their activity",
				false,
				"No. It is correct that in the process of neutralization, antibodies bind to and block the activity of an antigen. But there is a better answer.");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct. Each of the above effects may occur once an antibody-antigen complex has formed.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336527;


		
		

		
			
			p.question = "How do antibodies to foreign blood groups come to exist in the body? (<script type=\"text/javascript\">ebook(\'4303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The antibodies form when a fetus is exposed to its mother\'s blood late in pregnancy.",
				false,
				"No. IgM antibodies, produced in response to an antigen, do not cross the placenta.");
			
				p.addAnswer(2, "The antibodies arise in response to bacterial inhabitants of the body that have epitopes very similar to blood groups and antigens.",
				true,
				"Correct. A person with type A blood will make antibodies against B-like bacterial epitopes. If type B blood is introduced into the person\'s system, the preexisting antibodies will cause an immediate and devastating reaction.");
			
				p.addAnswer(3, "This phenomenon cannot be explained.",
				false,
				"No. There is an explanation, and it is included in this list of possible responses.");
			
				p.addAnswer(4, "Even very limited exposure to the blood of another person can evoke the production of antibodies.",
				false,
				"No. There is another source of the antibodies.");
			
				p.addAnswer(5, "They are part of innate immunity and exist at birth.",
				false,
				"No. Antibodies are a characteristic of acquired immunity.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336528;


		
		

		
			
			p.question = "A type of cell that makes immunizations effective is the _____. (<script type=\"text/javascript\">ebook(\'4303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "red blood cell",
				false,
				"No. Red blood cells are not long-lived.");
			
				p.addAnswer(2, "killer T cell",
				false,
				"No. Cytotoxic T cells are not long-lived.");
			
				p.addAnswer(3, "killer B cell",
				false,
				"No. There is no such thing as a \"killer B cell.\"");
			
				p.addAnswer(4, "macrophage",
				false,
				"No. Macrophages play a role in innate immunity.");
			
				p.addAnswer(5, "memory B cell",
				true,
				"Correct. The secondary immune response, which is due to memory cells, provides long-term protection after exposure to a pathogen.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336529;


		
		

		
			
			p.question = "A vaccine may contain _____. (<script type=\"text/javascript\">ebook(\'4303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "white blood cells that fight infection",
				false,
				"No. White blood cells from a different individual would be rejected by the host\'s immune system.");
			
				p.addAnswer(2, "antibodies that recognize invading microbes",
				false,
				"No. The injection of antibodies provides passive immunity; however, since antibodies do not initiate a primary response, such an injection would not represent a vaccine.");
			
				p.addAnswer(3, "inactivated disease-causing microbes",
				true,
				"Correct. Inactivation may result from killing the organisms or by treatments that weaken or remove the disease-causing aspects while leaving antigens intact.");
			
				p.addAnswer(4, "a hormone that boosts immunity",
				false,
				"No. Acquired immunity depends on stimulating the immune system with the proper antigens rather than with hormones.");
			
				p.addAnswer(5, "lymphocyte antigens",
				false,
				"No. An antigen from a lymphocyte would be counterproductive; lymphocytes are the cellular agents that mediate an immune response.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336530;


		
		

		
			
			p.question = "The idea behind vaccination is to induce _____ without requiring the vaccinated individual to get sick. (<script type=\"text/javascript\">ebook(\'4303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "passive immunity",
				false,
				"No. Passive immunity occurs when an individual receives a functional antibody produced in another organism.");
			
				p.addAnswer(2, "the primary immune response",
				true,
				"Correct. Ideally, the vaccine will consist of the antigen with the disease-causing aspects of the microorganism removed.");
			
				p.addAnswer(3, "anaphylactic shock",
				false,
				"No. Anaphylactic shock is a life-threatening systemic response to an allergen.");
			
				p.addAnswer(4, "nonspecific defenses",
				false,
				"No. Vaccination is specific for a particular pathogen; it involves the specific defenses rather than the nonspecific defenses.");
			
				p.addAnswer(5, "inflammation",
				false,
				"No. Inflammation is a response that occurs after infection. The goal of vaccination is to prevent infection.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336531;


		
		

		
			
			p.question = "When searching for a donor for an organ transplant, doctors try to match the _____ of the donor and recipient as closely as possible. (<script type=\"text/javascript\">ebook(\'4303\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "antibodies",
				false,
				"No. Antibodies are produced in response to antigens.");
			
				p.addAnswer(2, "blood type",
				false,
				"No. Blood type is not unique to every individual. Matching blood type is more important when making a blood transfusion.");
			
				p.addAnswer(3, "MHC proteins",
				true,
				"Correct. The major histocompatibility complex is a large set of cell-surface antigens encoded by a family of genes. Foreign MHC markers trigger T cell responses that lead to the rejection of transplanted tissue.");
			
				p.addAnswer(4, "leukocytes",
				false,
				"No. Leukocytes are white blood cells.");
			
				p.addAnswer(5, "cytokines",
				false,
				"No. Cytokines are chemical signals released by activated antigen-presenting cells or activated helper T cells.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336532;


		
		

		
			
			p.question = "Besides helper T cells, what are two other types of cells that HIV infects? (<script type=\"text/javascript\">ebook(\'4304\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "macrophages and brain cells",
				true,
				"Correct. Macrophages and brain cells both contain low levels of CD4.");
			
				p.addAnswer(2, "B cells and liver cells",
				false,
				"No. Neither of these types of cells contains the receptors that are needed for HIV to infect the cell.");
			
				p.addAnswer(3, "plasma cells and neutrophils",
				false,
				"No. Neither of these types of cells contains the receptors that are needed for HIV to infect the cell.");
			
				p.addAnswer(4, "cytotoxic T cells and brain cells",
				false,
				"No. However, this answer is half right.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. Only one of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336533;


		
		

		
			
			p.question = "New flu shots are needed every year to protect against infection because of _____. (<script type=\"text/javascript\">ebook(\'4304\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "antigenic variation",
				true,
				"Correct. A pathogen can alter the way it appears to the immune system.");
			
				p.addAnswer(2, "latency",
				false,
				"No. This ability to avoid detection is not a major reason for new flu shots.");
			
				p.addAnswer(3, "expiration",
				false,
				"No.  Flu shots do not \"expire.\"");
			
				p.addAnswer(4, "direct attack on the immune system",
				false,
				"No. This is a serious result of infection with HIV, but not a reason for annual flu shots.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336534;


		
		

		
			
			p.question = "HIV is a dangerous pathogen because _____. (<script type=\"text/javascript\">ebook(\'4304\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "it mutates at a very high rate",
				false,
				"No. Although this is true, there is a better answer.");
			
				p.addAnswer(2, "the virus evolves within the body",
				false,
				"No. Although this is true, there is a better answer.");
			
				p.addAnswer(3, "the virus prevents recognition and elimination by the immune system",
				false,
				"No. Although this is true, there is a better answer.");
			
				p.addAnswer(4, "it leads to the loss of T cells",
				false,
				"No. Although this is true, there is a better answer.");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct. HIV has many effects.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

