

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "33: Invertebrates > Activities Quiz";
	ak.quiz_loc_with_commas = "33: Invertebrates, Activities Quiz";
	ak.quiz_title = "Activities Quiz";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 15;
	ak.non_essay_total = 15;
	ak.scored_item_total = 15;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335926;


		
		

		
			
			p.question = "Which of these statements is true of sponges? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?33&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Characteristics of Invertebrates</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "They have an open circulatory system.",
				false,
				"Sponges lack a circulatory system.");
			
				p.addAnswer(2, "They are segmented animals.",
				false,
				"Sponges are not segmented.");
			
				p.addAnswer(3, "They have no true tissues.",
				true,
				"Sponges lack true tissues.");
			
				p.addAnswer(4, "Food is digested within a gastrovascular cavity.",
				false,
				"Sponges are characterized by intracellular digestion.");
			
				p.addAnswer(5, "They are pseudocoelomates.",
				false,
				"Sponges do not have a body cavity.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335927;


		
		

		
			
			p.question = "Which of these statements is true of cnidarians? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?33&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Characteristics of Invertebrates</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "They have three tissue layers (they are triploblastic).",
				false,
				"Cnidarians have two tissue layers (they are diploblastic).");
			
				p.addAnswer(2, "They respire via book lungs.",
				false,
				"Cnidarians respire via their body surface.");
			
				p.addAnswer(3, "They have a nerve net.",
				true,
				"Cnidarians, such as jellies, have a nerve net.");
			
				p.addAnswer(4, "They are segmented.",
				false,
				"Cnidarians do not exhibit a segmented body plan.");
			
				p.addAnswer(5, "They have an exoskeleton composed of chitin.",
				false,
				"Cnidarians have a hydrostatic skeleton.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335928;


		
		

		
			
			p.question = "Of the phyla studied in this exercise, the simplest (most primitive) one to have three tissue layers is the phylum _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?33&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Characteristics of Invertebrates</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Cnidaria",
				false,
				"Cnidarians have two tissue layers (they are diploblastic).");
			
				p.addAnswer(2, "Arthropoda",
				false,
				"Arthropods are not the simplest animals to have three tissue layers.");
			
				p.addAnswer(3, "Platyhelminthes",
				true,
				"Of the phyla discussed in this activity, Platyhelminthes is the simplest one with three tissue layers (they are triploblastic).");
			
				p.addAnswer(4, "Chordata",
				false,
				"Chordates are not the simplest animals to have three tissue layers.");
			
				p.addAnswer(5, "Nematoda",
				false,
				"Nematodes are not the simplest animals to have three tissue layers.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335929;


		
		

		
			
			p.question = "Which of these statements is true of nematodes? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?33&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Characteristics of Invertebrates</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "They lack a nervous system.",
				false,
				"The nematode nervous system consists of nerve cords.");
			
				p.addAnswer(2, "They lack a body cavity.",
				false,
				"Nematodes are pseudocoelomates.");
			
				p.addAnswer(3, "They have a digestive system with two openings.",
				true,
				"Nematoda is the simplest phylum to be characterized by a digestive system with two openings.");
			
				p.addAnswer(4, "Their body plan has two main tissue layers.",
				false,
				"Nematodes have a three-tissue body plan.");
			
				p.addAnswer(5, "They are segmented.",
				false,
				"Nematodes do not have a segmented body plan.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335930;


		
		

		
			
			p.question = "Nematodes are most closely related to _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?33&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Characteristics of Invertebrates</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "flatworms",
				false,
				"Another phylum is more closely related to Nematoda than is Platyhelminthes.");
			
				p.addAnswer(2, "arthropods",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(3, "rotifers",
				true,
				"Rotifera is the phylum most closely related to the phylum Nematoda.");
			
				p.addAnswer(4, "annelids",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(5, "chordates",
				false,
				"Nematodes are not deuterostomes.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335931;


		
		

		
			
			p.question = "Earthworms are in the phylum _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?33&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Characteristics of Invertebrates</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Nematoda",
				false,
				"Earthworms are not roundworms.");
			
				p.addAnswer(2, "Annelida",
				true,
				"Earthworms are annelids.");
			
				p.addAnswer(3, "Chordata",
				false,
				"Earthworms are not chordates.");
			
				p.addAnswer(4, "Platyhelminthes",
				false,
				"Earthworms are not flatworms.");
			
				p.addAnswer(5, "Arthropoda",
				false,
				"This is the phylum most closely related to the phylum in which earthworms are found.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335932;


		
		

		
			
			p.question = "Which of these statements is true of earthworms? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?33&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Characteristics of Invertebrates</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "They lack an excretory system.",
				false,
				"The earthworm excretory system is composed of nephridia.");
			
				p.addAnswer(2, "They have a body cavity.",
				true,
				"Earthworms are coelomates.");
			
				p.addAnswer(3, "They have a bony endoskeleton.",
				false,
				"A hydrostatic skeleton supports the earthworm body.");
			
				p.addAnswer(4, "Their digestive system consists of a gastrovascular cavity.",
				false,
				"Earthworms have an alimentary canal.");
			
				p.addAnswer(5, "Their body plan consists of two tissue layers.",
				false,
				"The earthworm body plan has three tissue layers.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335933;


		
		

		
			
			p.question = "Snails are classified in the phylum _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?33&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Characteristics of Invertebrates</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Chordata",
				false,
				"Snails are not chordates.");
			
				p.addAnswer(2, "Mollusca",
				true,
				"Snails are mollusks.");
			
				p.addAnswer(3, "Cnidaria",
				false,
				"Snails are not cnidarians.");
			
				p.addAnswer(4, "Arthropoda",
				false,
				"Snails are not arthropods.");
			
				p.addAnswer(5, "Echinodermata",
				false,
				"Snails are not echinoderms.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335934;


		
		

		
			
			p.question = "Which of these characteristics is common to both snails and earthworms? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?33&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Characteristics of Invertebrates</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a closed circulatory system",
				false,
				"Earthworms have a closed circulatory system; snails have an open circulatory system.");
			
				p.addAnswer(2, "segmentation",
				false,
				"Earthworms are segmented; snails are not segmented.");
			
				p.addAnswer(3, "two tissue layers",
				false,
				"Both snails and earthworms have three tissue layers.");
			
				p.addAnswer(4, "an alimentary system with two openings",
				true,
				"This is a characteristic common to snails and earthworms.");
			
				p.addAnswer(5, "an exoskeleton",
				false,
				"Snails have an exoskeleton; earthworms have a hydrostatic skeleton.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335935;


		
		

		
			
			p.question = "Grasshoppers respire via _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?33&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Characteristics of Invertebrates</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "their skin",
				false,
				"Grasshoppers are covered by a tough exoskeleton.");
			
				p.addAnswer(2, "nephridia",
				false,
				"Nephridia are excretory structures found in, for example, earthworms.");
			
				p.addAnswer(3, "book lungs",
				false,
				"Most spiders respire via book lungs.");
			
				p.addAnswer(4, "spiracles and tracheae",
				true,
				"These are the components of the grasshopper respiratory system.");
			
				p.addAnswer(5, "Malpighian tubules",
				false,
				"The grasshopper excretory system is composed of Malpighian tubules.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335936;


		
		

		
			
			p.question = "Grasshoppers are classified in the phylum _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?33&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Characteristics of Invertebrates</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Annelida",
				false,
				"Grasshoppers are not in the same phylum as earthworms.");
			
				p.addAnswer(2, "Mollusca",
				false,
				"Grasshoppers are not in the same phylum as snails.");
			
				p.addAnswer(3, "Nematoda",
				false,
				"Grasshoppers are not roundworms.");
			
				p.addAnswer(4, "Arthropoda",
				true,
				"Grasshoppers are arthropods.");
			
				p.addAnswer(5, "Echinodermata",
				false,
				"Grasshoppers are not in the same phylum as sea stars.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335937;


		
		

		
			
			p.question = "As adults, sea stars _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?33&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Characteristics of Invertebrates</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "exhibit bilateral symmetry",
				false,
				"Larval sea stars exhibit bilateral symmetry.");
			
				p.addAnswer(2, "exhibit radial symmetry",
				true,
				"However, larval sea stars exhibit bilateral symmetry.");
			
				p.addAnswer(3, "are asymmetrical",
				false,
				"Adult sea stars are not asymmetrical.");
			
				p.addAnswer(4, "exhibit no symmetry",
				false,
				"Adult sea stars do exhibit a type of symmetry.");
			
				p.addAnswer(5, "lack a digestive system",
				false,
				"As adults, sea stars have an alimentary canal.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335938;


		
		

		
			
			p.question = "Which of these is a characteristic of sea stars? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?33&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Characteristics of Invertebrates</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a closed circulatory system",
				false,
				"The sea star circulatory system consists of fluid in a body cavity.");
			
				p.addAnswer(2, "nephridia",
				false,
				"Sea stars lack an excretory system.");
			
				p.addAnswer(3, "a brain",
				false,
				"Sea stars do not have a brain.");
			
				p.addAnswer(4, "two tissue layers",
				false,
				"Sea stars have three tissue layers.");
			
				p.addAnswer(5, "tube feet",
				true,
				"Tube feet are characteristic of sea stars.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335939;


		
		

		
			
			p.question = "Which of these characteristics is shared by both dogs and sea stars? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?33&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Characteristics of Invertebrates</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "an endoskeleton",
				true,
				"Both dogs and sea stars have an endoskeleton.");
			
				p.addAnswer(2, "a closed circulatory system",
				false,
				"Sea stars do not have a closed circulatory system.");
			
				p.addAnswer(3, "no excretory system",
				false,
				"While sea stars lack an excretory system, dogs have kidneys.");
			
				p.addAnswer(4, "a brain",
				false,
				"Sea stars do not have a brain.");
			
				p.addAnswer(5, "lungs",
				false,
				"Sea stars respire via gills and tube feet.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335940;


		
		

		
			
			p.question = "Dogs are classified in the phylum _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?33&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Characteristics of Invertebrates</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Echinodermata",
				false,
				"Dogs are not in the same phylum as sea stars.");
			
				p.addAnswer(2, "Cnidaria",
				false,
				"Dogs are not in the same phylum as jellies.");
			
				p.addAnswer(3, "Arthropoda",
				false,
				"Dogs have an endoskeleton, not an exoskeleton.");
			
				p.addAnswer(4, "Mollusca",
				false,
				"Dogs are not in the same phylum as snails.");
			
				p.addAnswer(5, "Chordata",
				true,
				"Like you, dogs are chordates.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

