

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "35: Plant Structure, Growth, and Development > Practice Test";
	ak.quiz_loc_with_commas = "35: Plant Structure, Growth, and Development, Practice Test";
	ak.quiz_title = "Practice Test";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 43;
	ak.non_essay_total = 43;
	ak.scored_item_total = 43;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336045;


		
		

		
			
			p.question = "In the hierarchy of biological organization, the shoot is _____. (<script type=\"text/javascript\">ebook(\'3501\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "an organ",
				false,
				"No. Leaves and stems are organs.");
			
				p.addAnswer(2, "a system",
				true,
				"Correct. The shoot system consists of leaves and stems, including flowers.");
			
				p.addAnswer(3, "a tissue",
				false,
				"No. Tissues are at a lower level of organization.");
			
				p.addAnswer(4, "a tissue system",
				false,
				"No. Plants have dermal, vascular, and ground tissue systems.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336046;


		
		

		
			
			p.question = "A root hair is _____. (<script type=\"text/javascript\">ebook(\'3501\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a multicellular extension of the root epidermis",
				false,
				"No. Root hairs are extensions of individual cells.");
			
				p.addAnswer(2, "an extension of the endodermis of roots",
				false,
				"No. Root hairs are epidermal.");
			
				p.addAnswer(3, "an outgrowth of the pericycle",
				false,
				"No. Branch roots are outgrowths of the pericycle.");
			
				p.addAnswer(4, "a modified root that provides support and anchorage",
				false,
				"No. Root hairs are part of a root.");
			
				p.addAnswer(5, "an extension of an individual cell that absorbs water from soil",
				true,
				"Correct. Root hairs are extensions of individual epidermal cells on the root surface that increase the absorptive surface area of the root tremendously.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336047;


		
		

		
			
			p.question = "Leaves occur at intervals along the plant stem. The region where a leaf is attached to the stem is the _____. (<script type=\"text/javascript\">ebook(\'3501\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "internode",
				false,
				"No. This is the space on stems between nodes.");
			
				p.addAnswer(2, "axil",
				false,
				"No. This is the angle between a stem and a leaf.");
			
				p.addAnswer(3, "node",
				true,
				"Correct. Nodes are regions of a stem where leaves are attached.");
			
				p.addAnswer(4, "shoot apex",
				false,
				"No. This area contains developing leaves and a compact series of nodes.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336048;


		
		

		
			
			p.question = "Leaves consist of _____. (<script type=\"text/javascript\">ebook(\'3501\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a blade and a petiole",
				true,
				"Correct. Leaves are the main photosynthetic organs of most plants and consist of a flattened blade and a stalk, the petiole, which joins the leaf to a node of the stem.");
			
				p.addAnswer(2, "a bud and a node",
				false,
				"No. A node is a location on a stem.");
			
				p.addAnswer(3, "a node and an internode",
				false,
				"No. These are regions found on stems.");
			
				p.addAnswer(4, "a bud and a blade",
				false,
				"No. Leaves consist of blades, but buds are embryonic shoots.");
			
				p.addAnswer(5, "an axillary bud and a terminal bud",
				false,
				"No. A bud is an embryonic shoot.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336049;


		
		

		
			
			p.question = "The shoot system of a beavertail cactus consists of broad paddle-like structures covered with clusters of spines. The spines are modified leaves, so the clusters must be modified _____ and the flat green paddles must be modified _____. (<script type=\"text/javascript\">ebook(\'3501\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "buds; leaves",
				false,
				"No. The clusters are modified buds, but buds are arranged on a stem.");
			
				p.addAnswer(2, "buds; stems",
				true,
				"Correct. The clusters are modified axillary buds along a flattened stem.");
			
				p.addAnswer(3, "leaves; stems",
				false,
				"No. The spines of cacti are modified leaves that compose an axillary bud.");
			
				p.addAnswer(4, "stems; roots",
				false,
				"No. The root system is mostly below ground and is not part of the shoot system.");
			
				p.addAnswer(5, "stems; leaves",
				false,
				"No. Leaves branch off stems.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336050;


		
		

		
			
			p.question = "Why does pinching off the top of a plant make it bushier? (<script type=\"text/javascript\">ebook(\'3501\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Removing the apical meristem stimulates growth in the lateral meristem, thus making the plant bushier.",
				false,
				"No. The lateral meristem increases the girth of stems and roots. It does not make a plant bushier.");
			
				p.addAnswer(2, "Removal of a node stimulates the internodes to grow and make the plant bushier.",
				false,
				"No. Nodes are the places on the stems where leaves attach, and internodes are the stems between nodes. They are not the places where growth occurs.");
			
				p.addAnswer(3, "Removing the apical meristem stimulates growth in the axillary buds, thus making the plant bushier.",
				true,
				"Correct. Because of apical dominance, axillary buds remain dormant until removal of the apical bud or shading of the apical bud. Once the apical bud is removed, the axillary buds give rise to lateral shoots and make the plant bushier.");
			
				p.addAnswer(4, "Removing the apical meristem causes the plant to change from its vegetative phase to its reproductive phase. The reproductive phase is bushier.",
				false,
				"No. Removal of the apical meristem is not the signal that causes the plant to go from vegetative to reproductive growth. Also, reproductive growth is not necessarily bushier.");
			
				p.addAnswer(5, "Removing plant stems always leads to the plant producing more leaves.",
				false,
				"No. Plants grow vertically or horizontally due to very specific responses, and leaves need stems to grow from!");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336051;


		
		

		
			
			p.question = "What is the difference between the root epidermis and the shoot epidermis? (<script type=\"text/javascript\">ebook(\'3501\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The root epidermis has chloroplasts.",
				false,
				"No. In most plants, roots are underground and have no need for chloroplasts because there is no light for photosynthesis.");
			
				p.addAnswer(2, "Only the shoot epidermis gives rise to vascular tissues.",
				false,
				"No. Dermal and vascular tissues are two different tissue systems.");
			
				p.addAnswer(3, "Only the shoot epidermis is replaced by periderm in woody plants.",
				false,
				"No. Older regions of both the shoot epidermis and root epidermis are replaced by periderm.");
			
				p.addAnswer(4, "Only the shoot epidermis produces a waxy cuticle.",
				true,
				"Correct. The hairs that extend from the cells of the root epidermis are specialized for the absorption of water and minerals; the epidermal cells of the shoot secrete a waxy coating, called cuticle, that prevents dehydration.");
			
				p.addAnswer(5, "Only the root epidermis contains guard cells.",
				false,
				"No. The leaf epidermis contains guard cells.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336052;


		
		

		
			
			p.question = "The plant tissue system most analogous to our circulatory system is the _____. (<script type=\"text/javascript\">ebook(\'3501\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "dermal tissue",
				false,
				"No. Dermal tissue is an outer covering.");
			
				p.addAnswer(2, "sclerenchyma",
				false,
				"No. Sclerenchyma is a supportive tissue.");
			
				p.addAnswer(3, "vascular cambium",
				false,
				"No. This is a type of meristem.");
			
				p.addAnswer(4, "ground tissue",
				false,
				"No. Ground tissue is not conductive tissue.");
			
				p.addAnswer(5, "vascular tissue",
				true,
				"Correct. Vascular tissues transport material throughout the plant just as the circulatory system transports materials throughout our bodies.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336053;


		
		

		
			
			p.question = "Ground tissue is composed of undifferentiated cells with thin walls that are usually involved with storage. At the stage in an herbaceous (nonwoody) dicot plant\'s life when only primary growth has occurred, the inner portion of the ground tissue of a stem is called _____ and the outer portion is called _____. (<script type=\"text/javascript\">ebook(\'3501\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "cambium; cortex",
				false,
				"No. However, cortex is the outer portion.");
			
				p.addAnswer(2, "endodermis; pith",
				false,
				"No. Endodermis occurs in roots, and pith is the ground tissue in the center of the dicot stem.");
			
				p.addAnswer(3, "cork; cortex",
				false,
				"No. However, cortex is the outer portion.");
			
				p.addAnswer(4, "cambium; cork",
				false,
				"No. Cambium is a lateral meristem producing secondary growth, and cork is produced by the cork cambium.");
			
				p.addAnswer(5, "pith; cortex",
				true,
				"Correct. In a dicot stem, the ground tissue system consists of an inner pith and outer cortex surrounded by vascular bundles.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336054;


		
		

		
			
			p.question = "Which of the following cells are dead at maturity? (<script type=\"text/javascript\">ebook(\'3501\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "parenchyma and sclerenchyma cells",
				false,
				"No. Parenchyma cells are metabolically active.");
			
				p.addAnswer(2, "collenchyma and sclerenchyma cells",
				false,
				"No. Collenchyma cells are metabolically active.");
			
				p.addAnswer(3, "sieve-tube members and companion cells",
				false,
				"No. Sieve-tube members, a component of phloem, are living cells (even though they lack nuclei).");
			
				p.addAnswer(4, "tracheids and companion cells",
				false,
				"No. Companion cells are metabolically active.");
			
				p.addAnswer(5, "tracheids and vessel elements",
				true,
				"Correct. The water-conducting cells of the xylem are tracheids and vessel elements, both of which are dead at maturity.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336055;


		
		

		
			
			p.question = "Most of the photosynthesis in plants takes place in specialized _____ cells called the _____. (<script type=\"text/javascript\">ebook(\'3501\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "parenchyma; mesophyll",
				true,
				"Correct. Parenchyma cells carry on most of the plant\'s metabolic functions, such as photosynthesis.");
			
				p.addAnswer(2, "sclerenchyma; palisades",
				false,
				"No. Sclerenchyma cells are dead when mature.");
			
				p.addAnswer(3, "pith; parenchyma",
				false,
				"No. Photosynthesis does not occur in pith.");
			
				p.addAnswer(4, "dermal; mesophyll",
				false,
				"No. Dermal tissue forms an outer covering, and most epidermal cells (except guard cells) lack chloroplasts.");
			
				p.addAnswer(5, "vascular; collenchyma",
				false,
				"No. Vascular tissue is conductive tissue.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336056;


		
		

		
			
			p.question = "Collenchyma cells can be recognized by _____. (<script type=\"text/javascript\">ebook(\'3501\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "their unevenly thickened cell walls",
				true,
				"Correct. Collenchyma cells have thicker cell walls than parenchyma cells, though the walls are unevenly thickened.");
			
				p.addAnswer(2, "the presence of chloroplasts",
				false,
				"No. Chloroplasts characterize parenchyma cells.");
			
				p.addAnswer(3, "lignin in the cell walls",
				false,
				"No. Sclerenchyma cells have lignin in their cell walls.");
			
				p.addAnswer(4, "the lack of nuclei at maturity",
				false,
				"No. Collenchyma cells have nuclei and are alive at maturity.");
			
				p.addAnswer(5, "large central vacuoles",
				false,
				"No. Parenchyma cells also have large central vacuoles; therefore, this is not a distinguishing feature.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336057;


		
		

		
			
			p.question = "Artichoke hearts are tender and have a strong taste. The leaves have a strong taste too, but most of an artichoke leaf is fibrous and too difficult to chew. The leaves must contain lots of _____. (<script type=\"text/javascript\">ebook(\'3501\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "collenchyma cells",
				false,
				"No. Collenchyma may be chewy, but it does not contain lignified and hard fibers.");
			
				p.addAnswer(2, "phloem",
				false,
				"No. Phloem, the sugar-conducting tissue of plants, is not fibrous.");
			
				p.addAnswer(3, "meristematic tissue",
				false,
				"No. Meristematic tissue is embryonic tissue and is not fibrous.");
			
				p.addAnswer(4, "sclerenchyma cells",
				true,
				"Correct. One type of this cell is fibrous.");
			
				p.addAnswer(5, "epidermal cells",
				false,
				"No. Epidermal cells form a waxy outer layer.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336058;


		
		

		
			
			p.question = "Perennials die ______. (<script type=\"text/javascript\">ebook(\'3502\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "in a single year, after seed production",
				false,
				"No. Annuals complete their life cycle in a single year.");
			
				p.addAnswer(2, "after flowering in their second spring/summer",
				false,
				"No. Biennials generally live for two years.");
			
				p.addAnswer(3, "from old age",
				false,
				"No. Perennials usually die from another cause.");
			
				p.addAnswer(4, "usually from an infection or some sort of trauma",
				true,
				"Correct. Infection or environmental trauma such as fire or drought is usually what kills perennials.");
			
				p.addAnswer(5, "once they have grown to their maximum height",
				false,
				"No. Infection or environmental trauma such as fire or drought is usually what kills perennials.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336059;


		
		

		
			
			p.question = "A region of dividing cells in a plant is called a _____. (<script type=\"text/javascript\">ebook(\'3502\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "meristem",
				true,
				"Correct. A plant is capable of indeterminate growth because it has perpetually embryonic tissues called meristems, which divide to generate additional cells.");
			
				p.addAnswer(2, "cortex",
				false,
				"No. This is a region of ground tissue.");
			
				p.addAnswer(3, "ground tissue",
				false,
				"No. Ground tissue does not contribute to intermediate growth.");
			
				p.addAnswer(4, "cotyledon",
				false,
				"No. A cotyledon is an embryonic leaf.");
			
				p.addAnswer(5, "mycorrhizal zone",
				false,
				"No. Mycorrhizae are mutualistic associations.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336060;


		
		

		
			
			p.question = "Which example below is the site of primary growth? (<script type=\"text/javascript\">ebook(\'3502\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "apical meristems",
				true,
				"Correct. Primary growth occurs at apical meristems.");
			
				p.addAnswer(2, "axillary buds",
				false,
				"No. These are regions of secondary growth.");
			
				p.addAnswer(3, "bud scales",
				false,
				"No. Bud scales are protective structures.");
			
				p.addAnswer(4, "lateral meristems",
				false,
				"No. Lateral meristems play a role in secondary growth.");
			
				p.addAnswer(5, "nodes",
				false,
				"No. These are stem regions to which leaves are attached.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336061;


		
		

		
			
			p.question = "Which of the following are lateral meristems? (<script type=\"text/javascript\">ebook(\'3502\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "vascular cambium",
				false,
				"No. Vascular cambium is a type of lateral meristem, but there is a better answer.");
			
				p.addAnswer(2, "cork cambium",
				false,
				"No. Cork cambium is a type of lateral meristem, but there is a better answer.");
			
				p.addAnswer(3, "leaf primordia",
				false,
				"No. Leaf primordia are finger-like projections along the sides of apical meristems from which leaves develop.");
			
				p.addAnswer(4, "axillary buds",
				false,
				"No. Axillary buds form at leaf nodes. They are a type of dormant apical meristem.");
			
				p.addAnswer(5, "both a and b",
				true,
				"Correct. Vascular cambium and cork cambium are lateral meristems. Division of cells in these two locations adds girth to the plant.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336062;


		
		

		
			
			p.question = "Some plants grow by primary and secondary mechanisms. Choose the correct description of a mechanism and its result. (<script type=\"text/javascript\">ebook(\'3502\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Primary and secondary growth are required to produce woody plants.",
				true,
				"Correct. Primary growth increases the length of the root and stem, and plants that exhibit only primary growth are herbaceous plants. Secondary growth increases the girth of the root and stem and produces woody plants.");
			
				p.addAnswer(2, "Primary growth increases the girth of the plant.",
				false,
				"No. Primary growth increases the length of the plant.");
			
				p.addAnswer(3, "Stems that only experience primary growth are called woody plants.",
				false,
				"No. Secondary growth produces wood.");
			
				p.addAnswer(4, "Herbaceous plants have stems that exhibit only secondary growth.",
				false,
				"No. Secondary growth produces wood.");
			
				p.addAnswer(5, "Secondary growth, a feature of herbaceous plants, extends the length of the plant.",
				false,
				"No. Primary growth extends the length of the plant. Secondary growth is not a feature of herbaceous plants.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336063;


		
		

		
			
			p.question = "Which choice below describes the fate of derivatives? (<script type=\"text/javascript\">ebook(\'3502\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "They die once they produce a generation of new cells.",
				false,
				"No. Once displaced from the meristem, they divide until cells they produce specialize.");
			
				p.addAnswer(2, "They remain in vascular tissue as sources of new cells.",
				false,
				"No. These cells originate from the meristem.");
			
				p.addAnswer(3, "Once displaced from the meristem, they divide until cells they produce specialize.",
				true,
				"Correct. This choice describes the fate of derivatives.");
			
				p.addAnswer(4, "They remain in the meristematic tissue as a source of new cells.",
				false,
				"No. This describes the fate of initials.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. There is only one correct answer.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336064;


		
		

		
			
			p.question = "The layer that covers the apical meristem of a root is called the _____. (<script type=\"text/javascript\">ebook(\'3503\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "root cap",
				true,
				"Correct. The root cap covers the root apical meristem and is involved in sensing the direction of gravity so the root grows downward.");
			
				p.addAnswer(2, "root hair",
				false,
				"No. Root hairs are cell extensions that increase root surface area.");
			
				p.addAnswer(3, "taproot",
				false,
				"No. Taproots are a type of root, not a feature of roots.");
			
				p.addAnswer(4, "apoplast",
				false,
				"No. The apoplast is the continuum of cell walls.");
			
				p.addAnswer(5, "pericycle",
				false,
				"No. The pericycle is a layer of cells that gives rise to lateral roots.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336065;


		
		

		
			
			p.question = "Root tips are pushed further into the soil mainly by _____. (<script type=\"text/javascript\">ebook(\'3503\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "cell division in the meristem",
				false,
				"No. The meristem is the source of new cells.");
			
				p.addAnswer(2, "elongation of cells",
				true,
				"Correct. Roots elongate primarily because of elongation of cells in the zone of elongation.");
			
				p.addAnswer(3, "cell division in the vascular cambium",
				false,
				"No. Cell division in the vascular cambium, which produces secondary xylem and secondary phloem, causes an increase in the diameter of a stem.");
			
				p.addAnswer(4, "differentiation (specialization) of root cells",
				false,
				"No. Differentiation is the process by which cells become specialized to perform specific functions.");
			
				p.addAnswer(5, "pulling by root hairs",
				false,
				"No. Root hairs are structures that increase the surface area of a root, thereby increasing the rate of nutrient absorption.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336066;


		
		

		
			
			p.question = "A cross section of a plant part exposes epidermis, a thick cortex, and a central cylinder of xylem and phloem. This part is a _____. (<script type=\"text/javascript\">ebook(\'3503\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "fruit",
				false,
				"No. Only roots have a central cylinder of vascular tissue inside a cortex.");
			
				p.addAnswer(2, "seed",
				false,
				"No. Seeds are embryonic plants.");
			
				p.addAnswer(3, "stem",
				false,
				"No. In stems there are several vascular bundles.");
			
				p.addAnswer(4, "root",
				true,
				"Correct. This is a description of a root cross section.");
			
				p.addAnswer(5, "bud",
				false,
				"No. A section through a terminal bud would reveal meristematic tissues.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336067;


		
		

		
			
			p.question = "Which of the following is closest to the center of an orchid (monocot) root? (<script type=\"text/javascript\">ebook(\'3503\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the cortex",
				false,
				"No. The cortex is located between the stele and the epidermis.");
			
				p.addAnswer(2, "phloem",
				false,
				"No. Phloem and xylem form around the center of the stele.");
			
				p.addAnswer(3, "pith",
				true,
				"Correct. The stele of roots is a centrally located cylinder. In monocots, pith forms the central core of the stele.");
			
				p.addAnswer(4, "epidermis",
				false,
				"No. The epidermis is the outermost tissue layer.");
			
				p.addAnswer(5, "xylem",
				false,
				"No. Phloem and xylem form around the center of the stele.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336068;


		
		

		
			
			p.question = "Lateral roots in seed plants are initiated by cell divisions in the _____. (<script type=\"text/javascript\">ebook(\'3503\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "vascular cambium",
				false,
				"No. Vascular cambium gives rise to secondary xylem and secondary phloem.");
			
				p.addAnswer(2, "endodermis",
				false,
				"No. The endodermis separates vascular tissue from ground tissue.");
			
				p.addAnswer(3, "pericycle",
				true,
				"Correct. The pericycle is a layer of cells that may become meristematic and begin dividing again, giving rise to lateral roots.");
			
				p.addAnswer(4, "lateral meristems",
				false,
				"No. Lateral meristems play a role in secondary growth.");
			
				p.addAnswer(5, "cortex",
				false,
				"No. The cortex is a ground tissue region.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336069;


		
		

		
			
			p.question = "Which of the following correctly describes a feature unique to monocot stems? (<script type=\"text/javascript\">ebook(\'3503\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Vascular bundles are scattered throughout.",
				true,
				"Correct. In dicots, vascular bundles are arranged in a ring.");
			
				p.addAnswer(2, "Lateral shoots cannot originate near the surface.",
				false,
				"No. Lateral shoots can originate near the surface, because stems have vascular tissue that is close to the surface.");
			
				p.addAnswer(3, "Vascular tissue is located all in the center.",
				false,
				"No. This is true of roots, not stems.");
			
				p.addAnswer(4, "Vascular bundles are arranged in a ring.",
				false,
				"No. This is true of dicots, rather than monocots.");
			
				p.addAnswer(5, "Ground tissue consists mainly of parenchyma.",
				false,
				"No. This is a feature of monocots and dicots.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336070;


		
		

		
			
			p.question = "In most leaves, chloroplast-containing cells are most closely compacted in _____. (<script type=\"text/javascript\">ebook(\'3503\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the vein (vascular bundle)",
				false,
				"No. This is conductive tissue.");
			
				p.addAnswer(2, "the upper epidermis",
				false,
				"No. Chloroplasts are not found in the epidermis.");
			
				p.addAnswer(3, "the lower epidermis",
				false,
				"No. Chloroplasts are not found in the epidermis.");
			
				p.addAnswer(4, "the mesophyll",
				true,
				"Correct. The mesophyll consists mainly of parenchyma cells specialized for photosynthesis.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336071;


		
		

		
			
			p.question = "Guard cells _____. (<script type=\"text/javascript\">ebook(\'3504\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "are involved in controlling the evaporative loss of water from a plant",
				false,
				"No. This answer is correct, but there is a better response.");
			
				p.addAnswer(2, "are necessary for gas exchange during photosynthesis",
				false,
				"No. This answer is correct, but there is a better answer.");
			
				p.addAnswer(3, "protect the plant\'s roots from infection",
				false,
				"No. Guard cells are structures found in leaves.");
			
				p.addAnswer(4, "control water and solute intake by roots",
				false,
				"No. Guard cells are structures found in leaves.");
			
				p.addAnswer(5, "both a and b",
				true,
				"Correct. Guard cells are involved in transpiration (evaporative water loss) and gas exchange.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336072;


		
		

		
			
			p.question = "Which of the following is the correct arrangement of structures from the inside to the outside of a leaf blade? (<script type=\"text/javascript\">ebook(\'3504\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "vascular bundle, mesophyll, epidermis",
				true,
				"Correct. From inside to outside are found the vascular bundle, surrounded by mesophyll (palisade above and spongy below), and the epidermis (upper above and lower below).");
			
				p.addAnswer(2, "mesophyll, vascular bundle, epidermis",
				false,
				"No. The prefix \"meso-\" refers to \"middle.\"");
			
				p.addAnswer(3, "epidermis, mesophyll, vascular bundle",
				false,
				"No. The prefix \"epi-\" refers to \"upon.\"");
			
				p.addAnswer(4, "palisade mesophyll, spongy mesophyll, lower epidermis, upper epidermis, vascular bundle",
				false,
				"No. The prefix \"meso-\" refers to \"middle.\"");
			
				p.addAnswer(5, "vascular bundle, lower epidermis, upper epidermis, spongy mesophyll, palisade mesophyll",
				false,
				"No. The prefix \"epi-\" refers to \"upon.\"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336073;


		
		

		
			
			p.question = "If you pound a nail into a tree 1 meter off the ground and come back to find it in 20 years, it will be _____. (<script type=\"text/javascript\">ebook(\'3504\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "1 meter off the ground and more deeply embedded in the tree",
				true,
				"Correct. Apical meristems elongate shoots through primary growth; therefore, the tree grows from the top. Lateral meristems add girth to woody plants through secondary growth; therefore, the tree would increase in diameter but the nail would not be elevated.");
			
				p.addAnswer(2, "more than 1 meter off the ground and more deeply embedded in the tree",
				false,
				"No. Consider apical meristems.");
			
				p.addAnswer(3, "1 meter off the ground and the same depth in the tree",
				false,
				"No. Consider lateral meristems.");
			
				p.addAnswer(4, "more than 1 meter off the ground and the same depth in the tree",
				false,
				"No. You are not considering apical and lateral meristems.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336074;


		
		

		
			
			p.question = "Which of the following is closest to the center of a woody stem? (<script type=\"text/javascript\">ebook(\'3504\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "vascular cambium",
				false,
				"No. Vascular cambium is located between secondary xylem (to the inside) and secondary phloem (to the outside).");
			
				p.addAnswer(2, "young phloem",
				false,
				"No. Vascular cambium lays down phloem at its exterior; thus, young phloem is closer to the center than old phloem.");
			
				p.addAnswer(3, "old phloem",
				false,
				"No. Vascular cambium lays down phloem at its exterior; thus, old phloem is farther from the center than young phloem.");
			
				p.addAnswer(4, "young xylem",
				false,
				"No. Younger xylem is laid down at the interior of the vascular cambium, resulting in younger xylem being farther from the center.");
			
				p.addAnswer(5, "old xylem",
				true,
				"Correct. Vascular cambium lays down xylem at its interior, resulting in younger xylem being formed toward the exterior of the old xylem.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336075;


		
		

		
			
			p.question = "A vandal killed a historic oak tree on the village green by girdling it with a chain saw. He cut through the bark and into the sapwood all the way around the tree. Why did the tree die? (<script type=\"text/javascript\">ebook(\'3504\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The leaves could not get carbon dioxide.",
				false,
				"No. Gas exchange by leaves involves the opening and closing of stomata and does not involve the bark or sapwood.");
			
				p.addAnswer(2, "Oxygen could not get to the roots.",
				false,
				"No. Cutting through the bark and sapwood does not involve cutting the roots and does not affect their permeability.");
			
				p.addAnswer(3, "The roots could not get food.",
				true,
				"Correct. Cutting through the bark cuts through secondary phloem and secondary xylem, thus cutting off the flow of food to the roots and the flow of water to the leaves.");
			
				p.addAnswer(4, "The leaves could not get food.",
				false,
				"No. The leaves are photosynthetic and thus produce food.");
			
				p.addAnswer(5, "The roots could not absorb water.",
				false,
				"No. Cutting through the bark and sapwood does not involve cutting the roots and does not affect their permeability.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336076;


		
		

		
			
			p.question = "Which best describes a characteristic of tracheids? (<script type=\"text/javascript\">ebook(\'3504\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "They are only found in gymnosperms.",
				false,
				"No. Actually, they are found in gymnosperms and angiosperms.");
			
				p.addAnswer(2, "They are only produced early in the growing season.",
				false,
				"No. Tracheids are produced early in the growing season (early wood) and late in the growing season (late wood).");
			
				p.addAnswer(3, "They maximize delivery of water to new, expanding leaves.",
				true,
				"Correct. They have relatively large diameters and thin cell walls.");
			
				p.addAnswer(4, "They are also called vessel elements.",
				false,
				"No. Tracheids and vessel elements have similar functions in angiosperms, but they are not the same.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. There is one correct answer.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336077;


		
		

		
			
			p.question = "Annual rings in wood are evidence that in climates with a single annual growing season, the _____ divides actively when water is plentiful and temperatures are suitable for growth, and ceases to divide when water is scarce and the weather is cold. (<script type=\"text/javascript\">ebook(\'3504\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "apical meristem",
				false,
				"No. Apical meristem is responsible for primary growth.");
			
				p.addAnswer(2, "lateral meristem",
				false,
				"No. This answer is correct, but there is a more specific answer.");
			
				p.addAnswer(3, "cork cambium",
				false,
				"No. Cork cambium gives rise to cork.");
			
				p.addAnswer(4, "vascular cambium",
				true,
				"Correct. The annual growth rings evident in cross sections of most tree trunks in temperate regions result from the yearly activity of vascular cambium.");
			
				p.addAnswer(5, "marginal meristem",
				false,
				"No. The answer does involve meristematic tissue, but this is not correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336078;


		
		

		
			
			p.question = "Cell division would occur least frequently in which of these tissues? (<script type=\"text/javascript\">ebook(\'3504\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "apical meristem of a root",
				false,
				"No. The division of the cells of the apical meristem of a root provides the cells for primary growth.");
			
				p.addAnswer(2, "cork cambium",
				false,
				"No. Cork cambium is meristematic tissue that produces new cork by cell division and differentiation.");
			
				p.addAnswer(3, "epidermis",
				true,
				"Correct. The epidermis produced by primary growth dries and falls off the stem during secondary growth.");
			
				p.addAnswer(4, "vascular cambium",
				false,
				"No. Vascular cambium is meristematic tissue that produces new xylem and phloem by cell division and differentiation.");
			
				p.addAnswer(5, "apical meristem of a terminal bud",
				false,
				"No. The apical meristem consists of actively dividing cells found at the tip of a terminal bud.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336079;


		
		

		
			
			p.question = "Wood is composed primarily of _____. (<script type=\"text/javascript\">ebook(\'3504\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "primary xylem",
				false,
				"No. There is some primary xylem in the center of a woody root or next to the pith of a woody stem, but wood is composed of secondary xylem.");
			
				p.addAnswer(2, "primary phloem",
				false,
				"No. Primary phloem is eventually shed with the outer bark.");
			
				p.addAnswer(3, "secondary xylem",
				true,
				"Correct. Heartwood is older secondary xylem that no longer functions in transport; the lignified walls of its dead cells form a central column that supports the tree.");
			
				p.addAnswer(4, "secondary phloem",
				false,
				"No. Secondary phloem is eventually shed with the outer bark.");
			
				p.addAnswer(5, "plant fibers",
				false,
				"No. However, fibers are cells that contribute to the tissue of which wood is composed.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336080;


		
		

		
			
			p.question = "In what order would you pass through tissues when moving from the pith to the epidermis in a plant possessing secondary vascular tissue? (<script type=\"text/javascript\">ebook(\'3504\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "primary phloem, primary xylem, secondary phloem, secondary xylem",
				false,
				"No. Phloem is outside xylem.");
			
				p.addAnswer(2, "primary xylem, secondary xylem, vascular cambium, secondary phloem, primary phloem",
				true,
				"Correct. The pith is the innermost tissue, followed by primary xylem, then secondary xylem. Next is a layer of cambium cells, then secondary phloem, and finally primary phloem.");
			
				p.addAnswer(3, "primary phloem, secondary phloem, secondary xylem, primary xylem",
				false,
				"No. Phloem is outside xylem.");
			
				p.addAnswer(4, "secondary xylem, primary xylem, primary phloem, secondary phloem",
				false,
				"No. Consider the location of vascular cambium.");
			
				p.addAnswer(5, "secondary phloem, primary phloem, primary xylem, secondary xylem",
				false,
				"No. Phloem is outside xylem.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336081;


		
		

		
			
			p.question = "What accounts for about 90% of a plant cell\'s expansion? (<script type=\"text/javascript\">ebook(\'3505\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "additional organic material in a plant\'s cytoplasm",
				false,
				"No. This does account for some cell expansion, but not 90%.");
			
				p.addAnswer(2, "water uptake stored in various small vacuoles",
				false,
				"No. This is correct during some stage of cell expansion, but this is not the best answer.");
			
				p.addAnswer(3, "water uptake that is stored in a large central vacuole",
				true,
				"Correct. Water uptake accounts for 90% of expansion. Most of this water is packaged in the large central vacuole formed by the coalescence of many smaller vacuoles.");
			
				p.addAnswer(4, "additional organic material stored in vacuoles",
				false,
				"No. Additional organic material is not stored in the vacuoles.");
			
				p.addAnswer(5, "water stored in the nucleus",
				false,
				"No. Plants store most of the water taken up during cell expansion in a large central vacuole.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336082;


		
		

		
			
			p.question = "Preprophase bands_____. (<script type=\"text/javascript\">ebook(\'3505\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "determine the location where the cell plate will form during cell division",
				true,
				"Correct. The location of the microtubules predicts the plane of cell division.");
			
				p.addAnswer(2, "run parallel to the direction of elongation as a cell matures",
				false,
				"No. The preprophase bands run perpendicular to the axis of cell elongation following division of the cell.");
			
				p.addAnswer(3, "are present throughout the cell cycle",
				false,
				"No. The preprophase bands appear just prior to the beginning of cell division and disappear once mitosis begins.");
			
				p.addAnswer(4, "run perpendicular to the cellulose microfibrils in a dividing cell",
				false,
				"No. The cellulose microfibrils associated with eventual cell elongation are oriented in the same plane as the preprophase band.");
			
				p.addAnswer(5, "constrict the cell and \"pinch\" it in two during cell division",
				false,
				"No. Animal cells divide by constricting in two; plant cells form a cell plate.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336083;


		
		

		
			
			p.question = "In a young cell just produced by mitosis, the cellulose microfibrils are arranged in horizontal rings. Which of the following accurately explains how the cell will grow longer? (<script type=\"text/javascript\">ebook(\'3505\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The cell will expand horizontally, in the same direction that the microfibrils are oriented.",
				false,
				"No. Cell growth occurs in the plane perpendicular to the orientation of the cellulose microfibrils.");
			
				p.addAnswer(2, "Water will enter the cell only at the ends lacking cellulose microfibrils.",
				false,
				"No. Cellulose walls are permeable to water.");
			
				p.addAnswer(3, "Enlargement of the vacuole will force the cell to grow evenly in all directions.",
				false,
				"No. The cellulose microfibrils cannot stretch much, so cells expand perpendicular to the \"grain.\"");
			
				p.addAnswer(4, "The bands of microfibrils will resist expansion, so the cell will enlarge at right angles to the ring of microfibrils.",
				true,
				"Correct. The bands of microfibrils act like barrel staves to prevent expansion against them.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. The bands of microfibrils act like barrel staves to prevent expansion against them.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336084;


		
		

		
			
			p.question = "The <i>gnom</i> mutant of <i>Arabidopsis</i> causes the first cell division of the zygote to be symmetrical. As a result_____. (<script type=\"text/javascript\">ebook(\'3505\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "polarity is established for further growth of the embryo",
				false,
				"No. Polarity is established for further growth of the embryo by an asymmetric division of the zygote.");
			
				p.addAnswer(2, "the root axis develops at the same rate as the shoot axis",
				false,
				"No. Neither axis develops unless polarity is established by the asymmetric division of the zygote.");
			
				p.addAnswer(3, "the embryo forms paired cotyledons on either side of the shoot apical meristem",
				false,
				"No. Symmetry in the embryo does not develop unless polarity is established by the asymmetric division of the zygote.");
			
				p.addAnswer(4, "whorls of leaves are produced at intervals along the stem",
				false,
				"Symmetry in the embryo does not develop unless polarity is established by the asymmetric division of the zygote.");
			
				p.addAnswer(5, "no polarity is established in the plant and it remains ball-shaped and lacks leaves and roots",
				true,
				"Correct. Symmetry in the embryo does not develop unless polarity is established by the asymmetric division of the zygote.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336085;


		
		

		
			
			p.question = "The homeotic gene GLABRA-2 controls cellular differentiation in the root epidermis of <i>Arabidopsis</i>. Which of the following statements is correct? (<script type=\"text/javascript\">ebook(\'3505\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "If GLABRA-2 is \"turned on\" the cell produces a root hair.",
				false,
				"No. GLABRA-2 inhibits production of root hairs.");
			
				p.addAnswer(2, "If an epidermal cell borders two cortical cells, GLABRA-2 is not expressed and the cell produces a root hair.",
				true,
				"Correct. Cells in which GLABRA-2 is expressed do not produce root hairs.");
			
				p.addAnswer(3, "If an epidermal cell borders one cortical cell, GLABRA-2 is expressed and the cell produces a root hair.",
				false,
				"No. If an epidermal cell borders two cortical cells, GLABRA-2 is not expressed and the cell produces a root hair.");
			
				p.addAnswer(4, "If GLABRA-2 is not expressed, no root hairs are formed.",
				false,
				"No. If GLABRA-2 is expressed, no root hairs are formed.");
			
				p.addAnswer(5, "both a and b",
				false,
				"No. GLABRA-2 inhibits production of root hairs.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336086;


		
		

		
			
			p.question = "During normal development <i>Acacia koa</i> plants first produce compound juvenile leaves and later produce adult sickle-shaped leaves. Which of the following statements is correct? (<script type=\"text/javascript\">ebook(\'3505\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Existing compound leaves will change to sickle-shaped leaves as the plant matures.",
				false,
				"No. The developmental phase of a leaf is determined at the time it is initiated.");
			
				p.addAnswer(2, "Sickle-shaped leaves will revert to compound leaves if cuttings are made from them.",
				false,
				"No. Once a leaf is initiated, its developmental fate is determined.");
			
				p.addAnswer(3, "Existing compound leaves will stay compound as the plant ages.",
				true,
				"Correct. Once a leaf is initiated, its developmental fate is determined and it cannot be changed.");
			
				p.addAnswer(4, "The compound juvenile leaves and the adult sickle-shaped leaves are produced by two different apical meristems.",
				false,
				"No. A single apical meristem produces all the leaves along an axis. When the plant goes through a developmental phase shift from juvenile to adult, the apex begins to produce adult-form leaves.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. Once initiated, the developmental phase of a leaf is determined. A single apical meristem produces all the leaves along an axis. When the plant goes through a developmental phase shift from juvenile to adult, the apex begins to produce adult-form leaves.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336087;


		
		

		
			
			p.question = "The ABC model of flower formation suggests that _____. (<script type=\"text/javascript\">ebook(\'3505\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "flower development depends on a sequence of three genes turning on in the correct order",
				false,
				"No. The model suggests that different combinations of the genes are responsible for organ determination.");
			
				p.addAnswer(2, "the A gene turns on sepals, the B gene turns on petals, the C gene turns on stamens, and all three are necessary for carpels to form",
				false,
				"No. The model suggests that a combination of gene A and gene B is needed to form petals, and gene B and gene C are needed to form stamens.");
			
				p.addAnswer(3, "the A gene initiates the flower bud, the B gene initiates formation of the sterile parts, and the C gene initiates formation of the reproductive parts",
				false,
				"No. The ABC model refers to organ identity genes, not floral initiation.");
			
				p.addAnswer(4, "pairs of genes are required to form petals and stamens, but a single gene can initiate sepals or carpels",
				true,
				"Correct. The A gene is necessary for sepals, the A gene and B gene for petals, the B gene and C gene for stamens, and the C gene alone for carpels.");
			
				p.addAnswer(5, "three mutations must occur at the shoot apical meristem for it to begin forming flower parts instead of leaves",
				false,
				"No. The ABC model refers to organ identity genes, not phase change.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

