

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "41: Animal Nutrition > Activities Quiz";
	ak.quiz_loc_with_commas = "41: Animal Nutrition, Activities Quiz";
	ak.quiz_title = "Activities Quiz";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 15;
	ak.non_essay_total = 15;
	ak.scored_item_total = 15;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336357;


		
		

		
			
			p.question = "When digested, proteins are broken down into _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?41&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Digestive System Function</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "glycerol only",
				false,
				"Glycerol is a component of fats.");
			
				p.addAnswer(2, "fatty acids only",
				false,
				"Fatty acids are a component of fats.");
			
				p.addAnswer(3, "monosaccharides",
				false,
				"Carbohydrates are composed of monosaccharides.");
			
				p.addAnswer(4, "amino acids",
				true,
				"Proteins are composed of amino acids.");
			
				p.addAnswer(5, "both glycerol and fatty acids",
				false,
				"Fats are composed of glycerol and fatty acids.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336358;


		
		

		
			
			p.question = "When digested, fats are broken down into _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?41&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Digestive System Function</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "glycerol only",
				false,
				"Glycerol is a component of fats; but is it the only component?");
			
				p.addAnswer(2, "fatty acids only",
				false,
				"Fatty acids are a component of fats; but are they the only component?");
			
				p.addAnswer(3, "monosaccharides",
				false,
				"Carbohydrates are composed of monosaccharides.");
			
				p.addAnswer(4, "amino acids",
				false,
				"Proteins are composed of amino acids.");
			
				p.addAnswer(5, "both glycerol and fatty acids",
				true,
				"Fats are composed of glycerol and fatty acids.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336359;


		
		

		
			
			p.question = "Starch is a type of _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?41&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Digestive System Function</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "disaccharide",
				false,
				"Starch is more complex than disaccharides.");
			
				p.addAnswer(2, "nucleotide",
				false,
				"Nucleotides are components of nucleic acids; starch is a carbohydrate.");
			
				p.addAnswer(3, "polysaccharide",
				true,
				"Starch is a carbohydrate composed of many monomers (many monosaccharide units).");
			
				p.addAnswer(4, "fatty acid",
				false,
				"Glycerol and fatty acids make up fats; starch is a carbohydrate.");
			
				p.addAnswer(5, "monosaccharide",
				false,
				"Starch is composed of many monosaccharides linked together; thus starch is more complex than a single monosaccharide.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336360;


		
		

		
			
			p.question = "Your small intestine can absorb ____ without their being further digested. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?41&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Digestive System Function</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "starches",
				false,
				"Starch is a polysaccharide, which must be broken down before it can be absorbed.");
			
				p.addAnswer(2, "fats",
				false,
				"Fats must be broken down into simpler units before they are digested.");
			
				p.addAnswer(3, "proteins",
				false,
				"Proteins are broken down into amino acids, which are then absorbed.");
			
				p.addAnswer(4, "fructoses",
				true,
				"Fructose is a monosaccharide, and monosaccharides can be absorbed without having to be broken down into smaller units.");
			
				p.addAnswer(5, "nucleic acids",
				false,
				"Nucleic acids must be broken down into simpler units before they can be absorbed.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336361;


		
		

		
			
			p.question = "Which of these enzymes begins the breakdown of starch? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?41&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Digestive System Function</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "bile",
				false,
				"Bile plays a role in the digestion of fats.");
			
				p.addAnswer(2, "disaccharidases",
				false,
				"Disaccharidases break down disaccharides.");
			
				p.addAnswer(3, "lipase",
				false,
				"Lipases break down fats.");
			
				p.addAnswer(4, "amylase",
				true,
				"The digestion of starches, such as amylose, begins with the amylase secreted by the salivary glands.");
			
				p.addAnswer(5, "nucleases",
				false,
				"Nucleases break down nucleic acids.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336362;


		
		

		
			
			p.question = "Starch can be broken down into the disaccharide known as _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?41&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Digestive System Function</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "lactose",
				false,
				"Lactose is a disaccharide commonly found in milk; it is not the product of the breakdown of starch.");
			
				p.addAnswer(2, "glucose",
				false,
				"Glucose is a monosaccharide that contributes to the structure of starch.");
			
				p.addAnswer(3, "sucrose",
				false,
				"Sucrose, also known as table sugar, is not the product of the breakdown of starch.");
			
				p.addAnswer(4, "fructose",
				false,
				"Fructose is a monosaccharide that contributes to the structure of table sugar.");
			
				p.addAnswer(5, "maltose",
				true,
				"Starch is composed of many maltose units.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336363;


		
		

		
			
			p.question = "Protein digestion begins in the _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?41&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Digestive System Function</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "mouth",
				false,
				"Starch digestion begins in the mouth.");
			
				p.addAnswer(2, "esophagus",
				false,
				"The esophagus does not secrete any digestive enzymes.");
			
				p.addAnswer(3, "stomach",
				true,
				"The secretion of gastric juice by the stomach begins the digestion of proteins.");
			
				p.addAnswer(4, "small intestine",
				false,
				"While protein is digested in the small intestine, this is not where protein digestion begins.");
			
				p.addAnswer(5, "large intestine",
				false,
				"The large intestine is primarily involved in the absorption of water.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336364;


		
		

		
			
			p.question = "What is the main component of gastric juice? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?41&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Digestive System Function</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "inactive pepsin",
				false,
				"While present in gastric juice, inactive pepsin is not its primary component.");
			
				p.addAnswer(2, "amylase",
				false,
				"Salivary amylase is secreted by the salivary glands, and pancreatic amylase, secreted by the pancreas, is released into the small intestine.");
			
				p.addAnswer(3, "hydrochloric acid",
				false,
				"While present in gastric juice, hydrochloric acid is not its primary component.");
			
				p.addAnswer(4, "water",
				true,
				"Water is the primary component of many secretions, including gastric juice.");
			
				p.addAnswer(5, "bile",
				false,
				"Bile is neither secreted by, nor secreted into, the stomach. Bile is produced by the liver, stored in the gall bladder, and released into the small intestine.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336365;


		
		

		
			
			p.question = "_____ is secreted by the _____ and acts to emulsify _____ in the _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?41&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Digestive System Function</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Lipase ... small intestine ... fats ... small intestine",
				false,
				"Lipases digest fat; they do not emulsify fats.");
			
				p.addAnswer(2, "Trypsin ... pancreas ... fats ... small intestine",
				false,
				"Trypsin digests proteins; it does not emulsify fats.");
			
				p.addAnswer(3, "Nucleases ... pancreas ... nucleic acids ... stomach",
				false,
				"In the small intestine, nucleases digest nucleic acids.");
			
				p.addAnswer(4, "Amylase ... salivary glands ... starch ... stomach",
				false,
				"Salivary amylase, secreted by the salivary glands, digests starch in the mouth and esophagus.");
			
				p.addAnswer(5, "Bile ... liver ... fats ... small intestine",
				true,
				"Bile, produced by the liver and stored by the gall bladder, emulsifies fats in the small intestine. The smaller fat droplets present a greater surface area for the action of lipases.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336366;


		
		

		
			
			p.question = "What acid is responsible for stomach acidity? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?41&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Digestive System Function</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "hydrochloric acid",
				true,
				"Hydrochloric acid, secreted by the stomach, is responsible for the acidity of the stomach.");
			
				p.addAnswer(2, "carbonic acid",
				false,
				"Carbonic acid plays a role in buffering the pH of blood.");
			
				p.addAnswer(3, "sulfuric acid",
				false,
				"Your body does not produce sulfuric acid.");
			
				p.addAnswer(4, "acetic acid",
				false,
				"Acetic acid, which gives vinegar its sour taste, is not responsible for stomach acidity.");
			
				p.addAnswer(5, "sodium hydroxide",
				false,
				"Sodium hydroxide is a base.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336367;


		
		

		
			
			p.question = "Secretin stimulates the _____ to secrete _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?41&E','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Hormonal Control of Digestion</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "pancreas ... bicarbonate",
				true,
				"The acidity of the stomach contents triggers the small intestine to secrete secretin, which in turn stimulates the pancreas to secrete bicarbonate to neutralize this acidity.");
			
				p.addAnswer(2, "pancreas ... pancreatic enzymes",
				false,
				"Right organ, wrong secretion.");
			
				p.addAnswer(3, "small intestine ... disaccharidases",
				false,
				"While the small intestine does secrete disaccharidases, such secretion is not stimulated by secretin.");
			
				p.addAnswer(4, "stomach ... bicarbonate",
				false,
				"Right secretion, wrong organ.");
			
				p.addAnswer(5, "liver ... liver enzymes",
				false,
				"Secretin does not stimulate the liver to secrete enzymes.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336368;


		
		

		
			
			p.question = "Cholecystokinin (CCK) stimulates the _____ to secrete _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?41&E','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Hormonal Control of Digestion</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "pancreas ... bicarbonate",
				false,
				"Consider that fatty acids and amino acids trigger the secretion of CCK by the small intestine.");
			
				p.addAnswer(2, "pancreas ... pancreatic enzymes",
				true,
				"The presence of fatty acids and amino acids in the stomach contents triggers the small intestine to secrete CCK. CCK then stimulates the pancreas to secrete enzymes that play a role in the digestion of these nutrients.");
			
				p.addAnswer(3, "small intestine ... disaccharidases",
				false,
				"While the small intestine does secrete disaccharidases, such secretion is not stimulated by secretin.");
			
				p.addAnswer(4, "stomach ... bicarbonate",
				false,
				"The stomach does not secrete bicarbonate.");
			
				p.addAnswer(5, "liver ... liver enzymes",
				false,
				"CCK does not stimulate the liver to secrete enzymes.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336369;


		
		

		
			
			p.question = "The acidity of the stomach contents triggers the small intestine to secrete a hormone known as _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?41&E','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Hormonal Control of Digestion</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "cholecystokinin, or CCK",
				false,
				"The secretion of CCK is stimulated by the presence of fatty acids and amino acids.");
			
				p.addAnswer(2, "histones",
				false,
				"Histones are protein components of nucleosomes, structures that play a role in DNA packing.");
			
				p.addAnswer(3, "TSH",
				false,
				"TSH, thyroid-stimulating hormone, is secreted by the anterior pituitary.");
			
				p.addAnswer(4, "secretin",
				true,
				"The acidity of the stomach contents triggers the small intestine to secrete secretin; secretin then stimulates the pancreas to secrete bicarbonate to neutralize this acidity.");
			
				p.addAnswer(5, "pepsin",
				false,
				"Gastrin stimulates the secretion of pepsin, an enzyme that breaks down proteins.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336370;


		
		

		
			
			p.question = "The presence of fatty acids and amino acids in the stomach contents triggers the small intestine to secrete a hormone known as _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?41&E','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Hormonal Control of Digestion</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "cholecystokinin, or CCK",
				true,
				"The presence of fatty acids and amino acids in the stomach contents triggers the small intestine to secrete CCK. CCK then stimulates the gall bladder to release bile and the pancreas to secrete pancreatic enzymes.");
			
				p.addAnswer(2, "histones",
				false,
				"Histones are protein components of nucleosomes, structures that play a role in DNA packing.");
			
				p.addAnswer(3, "insulin",
				false,
				"Insulin secretion by the pancreas is stimulated by elevated blood sugar levels.");
			
				p.addAnswer(4, "secretin",
				false,
				"The acidity of the stomach contents triggers the small intestine to secrete secretin; secretin then stimulates the pancreas to secrete bicarbonate to neutralize this acidity.");
			
				p.addAnswer(5, "thyroxine",
				false,
				"The secretion of thyroxine, a thyroid hormone, is regulated by a feedback system that involves hypothalamic and pituitary secretions.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336371;


		
		

		
			
			p.question = "Bile is produced by the _____ and stored by the _____ until it is secreted into the small intestine. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?41&E','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Hormonal Control of Digestion</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "liver ... gall bladder",
				true,
				"Bile is continuously produced by the liver and is stored in the gall bladder until CCK triggers its release.");
			
				p.addAnswer(2, "pancreas ... gall bladder",
				false,
				"Wrong site of production, correct site of storage.");
			
				p.addAnswer(3, "liver ... pancreas",
				false,
				"Right site of production, wrong site of storage.");
			
				p.addAnswer(4, "gall bladder ... liver",
				false,
				"You are on the right track; you just have things backward.");
			
				p.addAnswer(5, "esophagus ... stomach",
				false,
				"The esophagus does not produce substances that play a role in the digestive process. The stomach does not store bile.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

