

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "Investigation Quiz > How Do Electrical Stimuli Affect Muscle Contraction?";
	ak.quiz_loc_with_commas = "Investigation Quiz, How Do Electrical Stimuli Affect Muscle Contraction?";
	ak.quiz_title = "How Do Electrical Stimuli Affect Muscle Contraction?";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 9;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 9;
	ak.non_essay_total = 0;
	ak.scored_item_total = 0;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337863;


		
		

		
			p.question = "What is the minimal or threshold stimulus?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337864;


		
		

		
			p.question = "What is the maximal stimulus?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337865;


		
		

		
			p.question = "How can you explain the increase in force that you observe?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337866;


		
		

		
			p.question = "What type of summation is this?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337867;


		
		

		
			p.question = "Is the peak force produced in the second contraction greater than that produced by the first stimulus?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337868;


		
		

		
			p.question = "Is the total force production even greater when multiple stimuli are applied in rapid succession?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337869;


		
		

		
			p.question = "Because there is a limit to how fast you can manually click the Single Stimulus button, what do you think would happen to the smoothness of the tracing if you could click even faster?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337870;


		
		

		
			p.question = "What happens if you use a lower voltage in rapid succession?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337871;


		
		

		
			p.question = "Explain how human skeletal muscles work to achieve smooth, steady contractions at all desired levels of force.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

