

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "32: An Introduction to Animal Diversity > Activities Quiz";
	ak.quiz_loc_with_commas = "32: An Introduction to Animal Diversity, Activities Quiz";
	ak.quiz_title = "Activities Quiz";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 10;
	ak.non_essay_total = 10;
	ak.scored_item_total = 10;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335887;


		
		

		
			
			p.question = "According to this phylogenetic tree, annelids are most closely related to _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?32&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Animal Phylogenetic Tree</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/3201q.jpg\" ALT=\"Question #1\" BORDER=\"1\" >";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "arthropods",
				true,
				"The branching pattern of the phylogenetic tree indicates that annelids are more closely related to arthropods than either is to any other phylum.");
			
				p.addAnswer(2, "molluscs",
				false,
				"While annelids are closely related to mollusks, there is another phylum to which they are even more closely related.");
			
				p.addAnswer(3, "nematodes",
				false,
				"Take another look at the branching pattern of the phylogenetic tree.");
			
				p.addAnswer(4, "cnidarians",
				false,
				"Take another look at the branching pattern of the phylogenetic tree.");
			
				p.addAnswer(5, "platyhelminths",
				false,
				"Take another look at the branching pattern of the phylogenetic tree.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335888;


		
		

		
			
			p.question = "According to this phylogenetic tree, the clade that includes echinoderms and chordates is most closely related to the clade that includes _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?32&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Animal Phylogenetic Tree</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/3202q.jpg\" ALT=\"Question #2\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "molluscs",
				true,
				"The branching pattern indicates that the clade that includes echinoderms and chordates is most closely related to the clade that includes mollusks, annelids, and arthropods.");
			
				p.addAnswer(2, "poriferans",
				false,
				"Take another look at the branching pattern of the phylogenetic tree.");
			
				p.addAnswer(3, "nematodes",
				false,
				"Take another look at the branching pattern of the phylogenetic tree.");
			
				p.addAnswer(4, "cnidarians",
				false,
				"Take another look at the branching pattern of the phylogenetic tree.");
			
				p.addAnswer(5, "nematodes",
				false,
				"Take another look at the branching pattern of the phylogenetic tree.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335889;


		
		

		
			
			p.question = "According to this phylogenetic tree, cnidarians are most closely related to _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?32&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Animal Phylogenetic Tree</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/3203q.jpg\" ALT=\"Question #3\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "nematodes",
				false,
				"Take another look at the branching pattern of the phylogenetic tree.");
			
				p.addAnswer(2, "annelids",
				false,
				"Take another look at the branching pattern of the phylogenetic tree.");
			
				p.addAnswer(3, "molluscs",
				false,
				"Take another look at the branching pattern of the phylogenetic tree.");
			
				p.addAnswer(4, "echinoderms",
				false,
				"Take another look at the branching pattern of the phylogenetic tree.");
			
				p.addAnswer(5, "platyhelminths",
				true,
				"Of the groups listed here cnidarians are most closely related to platyhelminths.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335890;


		
		

		
			
			p.question = "According to this phylogenetic tree, chordates are most closely related to _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?32&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Animal Phylogenetic Tree</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/3204q.jpg\" ALT=\"Question #4\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "arthropods",
				false,
				"Take another look at the branching pattern of the phylogenetic tree.");
			
				p.addAnswer(2, "molluscs",
				false,
				"Take another look at the branching pattern of the phylogenetic tree.");
			
				p.addAnswer(3, "poriferans",
				false,
				"Take another look at the branching pattern of the phylogenetic tree.");
			
				p.addAnswer(4, "echinoderms",
				true,
				"The phylogenetic tree indicates that echinoderms and chordates are more closely related to each other than either is to any other phylum.");
			
				p.addAnswer(5, "cnidarians",
				false,
				"Take another look at the branching pattern of the phylogenetic tree.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335891;


		
		

		
			
			p.question = "Cnidarians are in the _____ clade. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?32&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Animal Phylogenetic Tree</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "parazoan",
				false,
				"Cnidarians have true tissues.");
			
				p.addAnswer(2, "protostome",
				false,
				"Cnidarians do not have a body cavity.");
			
				p.addAnswer(3, "radiata",
				true,
				"Cnidarians exhibit radial symmetry.");
			
				p.addAnswer(4, "coelomate",
				false,
				"Cnidarians do not have a body cavity.");
			
				p.addAnswer(5, "bilateria",
				false,
				"Cnidarians do not exhibit bilateral symmetry.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335892;


		
		

		
			
			p.question = "Echinoderms are _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?32&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Animal Phylogenetic Tree</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "deuterostomes",
				true,
				"Echinoderms are deuterostomes.");
			
				p.addAnswer(2, "parazoans",
				false,
				"Echinoderms have true tissues.");
			
				p.addAnswer(3, "protostomes",
				false,
				"While echinoderms have a body cavity, they are not protostomes.");
			
				p.addAnswer(4, "radiata",
				false,
				"Despite their appearance echinoderms are bilateria.");
			
				p.addAnswer(5, "acoelomates",
				false,
				"Echinoderms have a body cavity.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335893;


		
		

		
			
			p.question = "Molluscs are _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?32&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Animal Phylogenetic Tree</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "protostomes",
				true,
				"The body cavity of mollusks is formed by the splitting of masses of mesoderm.");
			
				p.addAnswer(2, "acoelomates",
				false,
				"Mollusks have a body cavity.");
			
				p.addAnswer(3, "parazoans",
				false,
				"Mollusks have true tissues.");
			
				p.addAnswer(4, "deuterostomes",
				false,
				"However, mollusks are coelomates.");
			
				p.addAnswer(5, "radiata",
				false,
				"Mollusks exhibit bilateral symmetry.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335894;


		
		

		
			
			p.question = "Why are annelids, arthropods, and mollusks placed in the same clade? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?32&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Animal Phylogenetic Tree</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "They are triploblastic.",
				false,
				"So, for example, are platyhelminths, yet arthropods, annelids, and mollusks are placed in a clade that does not include platyhelminths.");
			
				p.addAnswer(2, "They are protostomes.",
				true,
				"Mollusks, annelids, and arthropods are protostomes.");
			
				p.addAnswer(3, "They are bilaterally symmetrical.",
				false,
				"So, for example, are nematodes, yet arthropods, annelids, and mollusks are placed in a clade that does not include nematodes.");
			
				p.addAnswer(4, "They are coelomates.",
				false,
				"So, for example, are echinoderms, yet arthropods, annelids, and mollusks are placed in a clade that does not include echinoderms.");
			
				p.addAnswer(5, "They are deuterostomes.",
				false,
				"No, they aren\'t.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335895;


		
		

		
			
			p.question = "Roundworms are classified in the phylum _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?32&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Animal Phylogenetic Tree</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Cnidaria",
				false,
				"Roundworms are not flatworms.");
			
				p.addAnswer(2, "Nematoda",
				true,
				"Roundworms are nematodes.");
			
				p.addAnswer(3, "Arthropoda",
				false,
				"Roundworms are not arthropods.");
			
				p.addAnswer(4, "Porifera",
				false,
				"Roundworms are not poriferans.");
			
				p.addAnswer(5, "Annelida",
				false,
				"While annelids are worms, they are not roundworms.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335896;


		
		

		
			
			p.question = "At the phylum level, you are most closely related to a(n) _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?32&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Animal Phylogenetic Tree</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "clam",
				false,
				"Phylum Mollusca is not the phylum most closely related to phylum Chordata.");
			
				p.addAnswer(2, "sea star",
				true,
				"The phylum most closely related to the Chordata (the phylum that includes humans) is the Echinodermata (the phylum that includes sea stars).");
			
				p.addAnswer(3, "earthworm",
				false,
				"Phylum Annelida is not the phylum most closely related to phylum Chordata.");
			
				p.addAnswer(4, "jelly",
				false,
				"Phylum Cnidaria is not the phylum most closely related to phylum Chordata.");
			
				p.addAnswer(5, "planarian",
				false,
				"Phylum Platyhelminthes is not the phylum most closely related to phylum Chordata.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

