

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "2: The Chemical Context of Life > Practice Test";
	ak.quiz_loc_with_commas = "2: The Chemical Context of Life, Practice Test";
	ak.quiz_title = "Practice Test";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 37;
	ak.non_essay_total = 37;
	ak.scored_item_total = 37;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334074;


		
		

		
			
			p.question = "Evaluate the following statement: Oxygen is not a greenhouse gas; therefore, gases containing oxygen, such as ozone, nitrous oxide, and carbon dioxide, are not greenhouse gases either. (<script type=\"text/javascript\">ebook(\'0201\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "True. It is impossible for a gas containing oxygen to be a greenhouse gas.",
				false,
				"No. We know that ozone, nitrous oxide, and carbon dioxide are greenhouse gases.");
			
				p.addAnswer(2, "True. Because oxygen is not a greenhouse gas, it is unlikely to combine with anything at a higher level of organization to form a greenhouse gas.",
				false,
				"No. The emergent properties of compounds are not always evident from the elements that make them up.");
			
				p.addAnswer(3, "False. Compounds can have emergent properties that are very different from the elements that form them.",
				true,
				"Correct. Emergent properties of compounds are more than simply the sum of their parts.");
			
				p.addAnswer(4, "True. Compounds display emergent properties that are very similar to the elements that form them.",
				false,
				"No. Emergent properties of compounds are more than simply the sum of their parts.");
			
				p.addAnswer(5, "False. Oxygen is a special case because of its reactivity and electronegativity.",
				false,
				"No. When it comes to emergent properties, oxygen is not a special case.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334075;


		
		

		
			
			p.question = "There are _____ naturally occurring elements. (<script type=\"text/javascript\">ebook(\'0201\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "4",
				false,
				"No. But 4 elements (carbon, hydrogen, oxygen, and nitrogen) do make up 96% of living matter.");
			
				p.addAnswer(2, "25",
				false,
				"No. There are more than 25 naturally occurring elements, but only 25 of them are known to be essential for life.");
			
				p.addAnswer(3, "92",
				true,
				"Correct. There are 92 naturally occurring elements, and about 25 of these are essential to life.");
			
				p.addAnswer(4, "108",
				false,
				"No. Think of naturally occurring elements.");
			
				p.addAnswer(5, "238",
				false,
				"No. Think of naturally occurring elements.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334076;


		
		

		
			
			p.question = "Which of the following is a trace element? (<script type=\"text/javascript\">ebook(\'0201\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "hydrogen",
				false,
				"No. Hydrogen plus three other elements account for about 96% of living matter.");
			
				p.addAnswer(2, "copper",
				true,
				"Correct. Copper (Cu) is a trace element. Copper accounts for less than 0.01% of living matter.");
			
				p.addAnswer(3, "oxygen",
				false,
				"No. Oxygen plus three other elements account for about 96% of living matter.");
			
				p.addAnswer(4, "nitrogen",
				false,
				"No. Nitrogen plus three other elements account for about 96% of living matter.");
			
				p.addAnswer(5, "carbon",
				false,
				"No. Carbon plus three other elements account for about 96% of living matter.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334077;


		
		

		
			
			p.question = "What are the four most abundant elements found in living systems? (<script type=\"text/javascript\">ebook(\'0201\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Hydrogen, oxygen, calcium, and nitrogen",
				false,
				"No. Calcium is not one of the four most abundant elements found in living systems.");
			
				p.addAnswer(2, "Nitrogen, carbon, sulfur, and oxygen",
				false,
				"No. Sulfur is not one of the four most abundant elements found in living systems.");
			
				p.addAnswer(3, "Hydrogen, oxygen, nitrogen, and carbon dioxide",
				false,
				"No. Carbon dioxide is not an element.");
			
				p.addAnswer(4, "Hydrogen, oxygen, nitrogen, and carbon",
				true,
				"Correct. These four elements make up about 96% of living matter.");
			
				p.addAnswer(5, "Magnesium, calcium, iron, and zinc",
				false,
				"No. These are all important minerals, but they are not the most abundant elements in living organisms.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334078;


		
		

		
			
			p.question = "Which one of the following has negligible mass? (<script type=\"text/javascript\">ebook(\'0202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "proton",
				false,
				"No. Protons are included in the calculation of atomic mass. A proton weighs about 1.7 x 10<sup>-24</sup> grams (atomic mass of about 1 dalton).");
			
				p.addAnswer(2, "neutron",
				false,
				"No. Neutrons are included in the calculation of atomic mass. A neutron weighs about 1.7 x 10<sup>-24</sup> grams (atomic mass of about 1 dalton).");
			
				p.addAnswer(3, "electron",
				true,
				"Correct. Because the mass of an electron is only about 1/2,000 that of a proton or neutron, electrons are not considered when computing atomic mass.");
			
				p.addAnswer(4, "atom",
				false,
				"No. Think subatomic. Atoms are composed of subatomic particles: protons, neutrons, and electrons.");
			
				p.addAnswer(5, "element",
				false,
				"No. Think subatomic. Atoms of an element are composed of subatomic particles: protons, neutrons, and electrons.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334079;


		
		

		
			
			p.question = "Which one of the following subatomic particles has appreciable mass and lacks a charge? (<script type=\"text/javascript\">ebook(\'0202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "proton",
				false,
				"No. A proton weighs about 1.7 x 10<sup>-24</sup> grams (has a mass close to 1 dalton), and it has a positive charge.");
			
				p.addAnswer(2, "neutron",
				true,
				"Correct. A neutron weighs about 1.7 x 10<sup>-24</sup> grams (has a mass close to 1 dalton), and it is electrically neutral.");
			
				p.addAnswer(3, "electron",
				false,
				"No. Electrons have a negative charge and a mass only about 1/2,000 that of a neutron or proton.");
			
				p.addAnswer(4, "element",
				false,
				"No. An element is not a subatomic particle. An atom of an element is composed of subatomic particles.");
			
				p.addAnswer(5, "molecule",
				false,
				"No. A molecule is not a subatomic particle. A molecule is composed of two or more atoms joined together by a covalent bond(s).");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334080;


		
		

		
			
			p.question = "The number of protons in an uncharged atom _____. (<script type=\"text/javascript\">ebook(\'0202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "equals the number of electrons",
				true,
				"Correct. An uncharged atom has an equal number of protons and electrons.");
			
				p.addAnswer(2, "equals the number of neutrons",
				false,
				"No. The number of neutrons can differ from the number of protons in a charged or uncharged atom. For example, the different isotopes of an element would have different numbers of neutrons, but each of the different isotopes would have the same number of protons and electrons.");
			
				p.addAnswer(3, "varies with the different isotopes",
				false,
				"No. The number of neutrons determines the isotope, not the number of protons. For example, the different isotopes of an element would have different numbers of neutrons, but each of the different isotopes would have the same number of protons and electrons.");
			
				p.addAnswer(4, "equals the number of electrons in the outer orbital of the atom",
				false,
				"No. It equals the total number of electrons. The electrons in the outer orbital determine the combining power (valence) of the atom.");
			
				p.addAnswer(5, "determines its mass number",
				false,
				"No. The number of protons determines the atomic number, not the mass number. The total of protons plus neutrons determines the mass number.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334081;


		
		

		
			
			p.question = "Consider a hypothetical atom with an atomic number of 4 and a net electronic charge of +1. How many neutrons does this atom have? (<script type=\"text/javascript\">ebook(\'0202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "1",
				false,
				"No. What specific quantity is required to answer this question?");
			
				p.addAnswer(2, "3",
				false,
				"No. What specific quantity is required to answer this question?");
			
				p.addAnswer(3, "4",
				false,
				"No. What specific quantity is required to answer this question?");
			
				p.addAnswer(4, "The answer cannot be determined from the information provided.",
				true,
				"Correct. All the atoms of an element have the same number of protons, but some atoms have different numbers of neutrons than other atoms of the same element; therefore, the atoms have different mass numbers. Without the mass number (number of protons + neutrons), it is not possible to determine the number of neutrons.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334082;


		
		

		
			
			p.question = "An element has 8 protons, 9 neutrons, and 8 electrons. Its atomic number and atomic mass, respectively, are _____. (<script type=\"text/javascript\">ebook(\'0202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "8 and 16",
				false,
				"No. Atomic mass does not consider the number of electrons in an atom.");
			
				p.addAnswer(2, "8 and 17",
				true,
				"Correct. The number of protons, 8, gives the atomic number. The atomic mass is the sum of the number of protons and neutrons; thus, 8 + 9 = 17.");
			
				p.addAnswer(3, "9 and 16",
				false,
				"No. Atomic mass does not consider the number of electrons.");
			
				p.addAnswer(4, "9 and 17",
				false,
				"No. Atomic number relates to the number of protons, not the number of neutrons.");
			
				p.addAnswer(5, "16 and 8",
				false,
				"No. Atomic mass must be equal to or greater than the atomic number.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334083;


		
		

		
			
			p.question = "An uncharged atom of nitrogen (atomic number = 7) has _____. (<script type=\"text/javascript\">ebook(\'0202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "7 neutrons",
				false,
				"No. The number of neutrons cannot be calculated from the provided information.");
			
				p.addAnswer(2, "7 protons and 7 neutrons",
				false,
				"No. The number of neutrons cannot be calculated from the provided information.");
			
				p.addAnswer(3, "7 neutrons and 7 electrons",
				false,
				"No. The number of neutrons cannot be calculated from the provided information.");
			
				p.addAnswer(4, "7 protons and 7 electrons",
				true,
				"Correct. The atomic number is the number of protons, and this equals the number of electrons in an electrically neutral (uncharged) atom.");
			
				p.addAnswer(5, "7 valence electrons",
				false,
				"No. Two electrons are found in the innermost shell, and 5 electrons are present in the valence shell of a nitrogen atom.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334084;


		
		

		
			
			p.question = "Isotopes of an element will always differ in _____. (<script type=\"text/javascript\">ebook(\'0202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "atomic number",
				false,
				"No. Atomic number refers to the number of protons in an atom. All isotopes of an element must have the same atomic number, hence the same number of protons.");
			
				p.addAnswer(2, "atomic mass",
				true,
				"Correct. Atomic mass refers to the number of protons and neutrons in an atom. Atomic forms of an element with the same number of protons (atomic number) but different numbers of neutrons are isotopes of that element.");
			
				p.addAnswer(3, "number of electrons",
				false,
				"No. This determines whether the atoms of an element are ions.");
			
				p.addAnswer(4, "number of protons",
				false,
				"No. All isotopes of an element must have the same atomic number, hence the same number of protons.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334085;


		
		

		
			
			p.question = "A particular carbon isotope has an atomic number of 6 and an atomic mass of 14. The respective number of neutrons, protons, and electrons that this carbon isotope has is _____. (<script type=\"text/javascript\">ebook(\'0202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "6, 8, and 6",
				false,
				"No. The atomic number is equal to the number of protons; therefore, the number of protons must be 6.");
			
				p.addAnswer(2, "6, 6, and 8",
				false,
				"No. This would result in an atomic mass of 12, rather than 14.");
			
				p.addAnswer(3, "8, 6, and 6",
				true,
				"Correct. The atomic number, 6, is equal to the number of protons. Therefore, the number of electrons in an electrically neutral atom would also be 6. The number of neutrons must be 8 because the atomic mass is 14 (14 - 6 = 8).");
			
				p.addAnswer(4, "8, 6, and 8",
				false,
				"No. This would result in an atom with a negative charge. The 8 negatively charged electrons and 6 positively charged protons would result in a net charge of -2 for the atom.");
			
				p.addAnswer(5, "8, 6, and 4",
				false,
				"No. This would result in an atom with a positive charge. The 4 negatively charged electrons and 6 positively charged protons would result in a net charge of +2 for the atom.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334086;


		
		

		
			
			p.question = "Phosphorus-32 (radioactive) has _____ than phosphorus-35 (normal). (<script type=\"text/javascript\">ebook(\'0202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "3 more neutrons",
				false,
				"No. The radioactive isotope has the lower atomic mass.");
			
				p.addAnswer(2, "3 more protons",
				false,
				"No. All isotopes of a given element have the same atomic number, hence the same number of protons.");
			
				p.addAnswer(3, "3 fewer neutrons",
				true,
				"Correct. The numbers 32 and 35 refer to mass number (number of protons plus neutrons). All the atoms of the same element have the same number of protons, but different isotopes of the same element have different numbers of neutrons. Since 35 - 32 = 3, P-32 has 3 fewer neutrons than P-35.");
			
				p.addAnswer(4, "3 fewer protons",
				false,
				"No. All isotopes of given element must have the same atomic number, hence the same number of protons.");
			
				p.addAnswer(5, "three more atoms",
				false,
				"No. Only a single atom of each isotope is being considered.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334087;


		
		

		
			
			p.question = "The most common form of calcium has 20 protons, 20 neutrons, and 20 electrons. Which of the following elements would be an isotope of calcium? (<script type=\"text/javascript\">ebook(\'0202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "an atom with 21 protons, 20 neutrons, and 21 electrons",
				false,
				"No. The number of protons must stay the same for the element to remain calcium.");
			
				p.addAnswer(2, "an atom with 20 protons, 20 neutrons, and 18 electrons",
				false,
				"No. A change in the number of electrons would create an ion of calcium.");
			
				p.addAnswer(3, "an atom with 20 protons, 21 neutrons, and 20 electrons",
				true,
				"Correct. Isotopes of an element have the same number of protons but different numbers of neutrons.");
			
				p.addAnswer(4, "an atom with 21 protons, 21 neutrons, and 21 electrons",
				false,
				"No. The number of protons must stay the same for the element to remain calcium.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. There is only one correct answer.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334088;


		
		

		
			
			p.question = "Radioactive isotopes are useful in scientific research because _______. (<script type=\"text/javascript\">ebook(\'0202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "They are not readily incorporated into biological reactions.",
				false,
				"No. Radioactive isotopes are used interchangeably with the stable isotope in living organisms.");
			
				p.addAnswer(2, "They are difficult to detect in small amounts, but living cells cannot distinguish them from the corresponding stable isotopes.",
				false,
				"No. While living cells cannot distinguish radioactive isotopes from stable isotopes, radioactive isotopes are easy to detect in small amounts.");
			
				p.addAnswer(3, "They can be used as tracers to follow particular atoms and molecules through metabolic pathways.",
				true,
				"Correct. Because they are detectable in very small amounts, a few labeled molecules can be traced through an organism\'s body to see how they are used.");
			
				p.addAnswer(4, "They decay spontaneously and give off energy and sub-atomic particles.",
				false,
				"No. This describes radioactive decay, but it does not explain the usefulness of radioactive isotopes in medicine.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. There is one correct answer.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334089;


		
		

		
			
			p.question = "Potassium (atomic number 19, mass number 40) and sodium (atomic number 11, mass number 23) have similar chemical properties and reactive behavior. This is because uncharged atoms of potassium and sodium _____. (<script type=\"text/javascript\">ebook(\'0202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "have different atomic numbers but the same number of electrons",
				false,
				"No. Potassium has 19 electrons and sodium has 11 electrons.");
			
				p.addAnswer(2, "have different atomic numbers and different numbers of electrons in their outermost electron shells",
				false,
				"No. They have the same number of electrons in their outermost electron shells.");
			
				p.addAnswer(3, "have the same atomic number and each has 1 electron in its outermost electron shell",
				false,
				"No. The atoms of different elements have atomic numbers that are unique to the different elements.");
			
				p.addAnswer(4, "have different mass numbers and each has 1 electron in its outermost electron shell",
				true,
				"Correct. Although potassium has 19 electrons and sodium has 11 electrons, each has only 1 electron in its outermost electron shell.");
			
				p.addAnswer(5, "have different atomic numbers, different mass numbers, and different numbers of electrons in their outermost electron shells",
				false,
				"No. Both potassium and sodium have the same number of electrons in their outermost electron shell.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334090;


		
		

		
			
			p.question = "Atomic chlorine has an atomic number of 17. It has _____ electrons in its third shell. (<script type=\"text/javascript\">ebook(\'0202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "2",
				false,
				"No. Remember that the innermost or first shell can only accommodate 2 electrons, but the second and third shells can each accommodate up to 8 electrons.");
			
				p.addAnswer(2, "7",
				true,
				"Correct. The first shell holds 2 electrons and is full; the second shell holds 8 electrons and is also full, which leaves 7 electrons to occupy the third shell.");
			
				p.addAnswer(3, "8",
				false,
				"No. Remember that the innermost or first shell can only accommodate 2 electrons, but the second and third shells can each accommodate up to 8 electrons. The inner shells must be filled before the third shell contains electrons.");
			
				p.addAnswer(4, "10",
				false,
				"No. Remember that the third shell can only accommodate a maximum of 8 electrons.");
			
				p.addAnswer(5, "17",
				false,
				"No. Remember that the third shell can only accommodate a maximum of 8 electrons.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334091;


		
		

		
			
			p.question = "The chemical characteristics or reactivity of an element depend mostly on the _____. (<script type=\"text/javascript\">ebook(\'0202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "number of electrons in its outermost shell",
				true,
				"Correct. Only electrons are directly involved in the interactions between atoms, and the number of electrons in the outermost shell determines the chemical behavior or reactivity of an atom.");
			
				p.addAnswer(2, "number of electron shells present in the atoms",
				false,
				"No. However, electrons play the major role in determining the chemical characteristics of an atom.");
			
				p.addAnswer(3, "mean energy level of its electrons",
				false,
				"No. However, electrons play the major role in determining the chemical characteristics of an atom.");
			
				p.addAnswer(4, "degree to which it has more or fewer electrons than protons",
				false,
				"No. However, electrons play the major role in determining the chemical characteristics of an atom.");
			
				p.addAnswer(5, "number of protons plus the number of neutrons",
				false,
				"No. This determines an atom\'s mass number.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334092;


		
		

		
			
			p.question = "Some groups of elements react chemically in similar ways. For example, the chemistry of sodium and the chemistry of lithium are similar. The chemistry of chlorine and the chemistry of iodine are also similar. These similarities in chemistry result when different elements have similar _____. (<script type=\"text/javascript\">ebook(\'0202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "atomic size",
				false,
				"No. An atom of iodine (atomic mass 130) is much larger than an atom of chlorine (atomic mass 35).");
			
				p.addAnswer(2, "numbers of outer-shell electrons",
				true,
				"Correct. Atoms with the same number of electrons in their valence shells exhibit similar chemical behavior or reactivity.");
			
				p.addAnswer(3, "total numbers of electrons",
				false,
				"No. But you have the right idea. How are electrons distributed in an atom?");
			
				p.addAnswer(4, "energy quanta per electron",
				false,
				"No. The energy content of an electron is related to its position in a particular electron shell. But there is a more specific answer.");
			
				p.addAnswer(5, "atomic number",
				false,
				"No. The atomic number is equal to the number of protons in an atom of a particular element and thus the number of electrons in an uncharged atom of the element. But there is a more specific answer.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334093;


		
		

		
			
			p.question = "How many electrons would be present in the valence shell of a sulfur atom (atomic number 16, mass number 32)? (<script type=\"text/javascript\">ebook(\'0202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "1 electron",
				false,
				"No. Consider the total number of electrons and their distribution in the electron shells.");
			
				p.addAnswer(2, "2 electrons",
				false,
				"No. Consider the total number of electrons and their distribution in the electron shells.");
			
				p.addAnswer(3, "4 electrons",
				false,
				"No. Consider the total number of electrons and their distribution in the electron shells.");
			
				p.addAnswer(4, "6 electrons",
				true,
				"Correct. An atom of sulfur would have 16 electrons, with 2 electrons in the innermost electron shell, 8 electrons in the next electron shell, and 6 electrons in the outermost or valence shell.");
			
				p.addAnswer(5, "8 electrons",
				false,
				"No. Consider the total number of electrons and their distribution in the electron shells.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334094;


		
		

		
			
			p.question = "For most atoms, a stable configuration of electrons is attained when the atom _____. (<script type=\"text/javascript\">ebook(\'0202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "has as many protons as neutrons",
				false,
				"No. An equal number of protons and neutrons is not related to electron configuration.");
			
				p.addAnswer(2, "has moved all its electrons to its outermost shell",
				false,
				"No. An outer shell may be unable to hold all of an atom\'s electrons.");
			
				p.addAnswer(3, "achieves a zero net charge",
				false,
				"No. Uncharged atoms can be reactive.");
			
				p.addAnswer(4, "has 8 electrons in its outermost shell",
				true,
				"Correct. An atom with a complete valence shell is unreactive.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334095;


		
		

		
			
			p.question = "An atom that normally has _____ in its outer shell would not tend to form chemical bonds with other atoms. (<script type=\"text/javascript\">ebook(\'0203\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "1 electron",
				false,
				"No. Atoms with a single valence electron may either become ions or covalently bond with other atoms.");
			
				p.addAnswer(2, "3 electrons",
				false,
				"No. Atoms with 3 valence electrons usually covalently bond with other atoms. Phosphorus is an example.");
			
				p.addAnswer(3, "4 electrons",
				false,
				"No. Atoms with 4 valence electrons covalently bond with other atoms. Carbon is an example.");
			
				p.addAnswer(4, "6 electrons",
				false,
				"No. Atoms with 6 valence electrons covalently bond with other atoms. Oxygen is an example.");
			
				p.addAnswer(5, "8 electrons",
				true,
				"Correct. Eight electrons will leave no unpaired electrons in the valence shell. In this configuration atoms are chemically unreactive or inert.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334096;


		
		

		
			
			p.question = "When one or more pairs of valence electrons are shared by two atoms, what type of bond is formed?\n (<script type=\"text/javascript\">ebook(\'0203\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "An ionic bond.",
				false,
				"No. Ionic bonds are formed between ions.");
			
				p.addAnswer(2, "A covalent bond.",
				true,
				"Correct. Covalent bonds are formed between atoms that share one or more pairs of valence electrons.");
			
				p.addAnswer(3, "A hydrogen bond.",
				false,
				"No. Hydrogen bonds are formed between the slightly positive end of a one polar molecule and the slightly negative end of another polar molecule.");
			
				p.addAnswer(4, "An electronegative bond.",
				false,
				"No. Although electronegativity plays a part in chemical bonding, there is no such thing as an electronegative bond.");
			
				p.addAnswer(5, "A neutral bond.",
				false,
				"No. There is no such thing as a neutral bond.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334097;


		
		

		
			
			p.question = "A polar covalent bond is a bond that _____. (<script type=\"text/javascript\">ebook(\'0203\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "is found only in H<sub>2</sub>O",
				false,
				"No. This is an example of a polar covalent compound, but many molecules contain polar covalent bonds.");
			
				p.addAnswer(2, "is found only in molecules containing oxygen",
				false,
				"No. Compounds not containing oxygen can also be polar. For example, certain nitrogen-containing molecules have polar covalent bonds.");
			
				p.addAnswer(3, "shares electrons equally between atoms",
				false,
				"No. Electrons are shared unequally, which is the source of the polarity of the molecule.");
			
				p.addAnswer(4, "ionizes",
				false,
				"No. The bonds are covalent, not ionic.");
			
				p.addAnswer(5, "has shared electrons pulled closer to the more electronegative atom",
				true,
				"Correct. Polar covalent bonds share electrons unequally, so that one part of the molecule has a partial negative region and one part a partial positive region.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334098;


		
		

		
			
			p.question = "A covalent bond is likely to be polar if _____. (<script type=\"text/javascript\">ebook(\'0203\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the two atoms sharing electrons are equally electronegative",
				false,
				"No. This would not result in a polar covalent bond.");
			
				p.addAnswer(2, "one of the atoms sharing electrons is much more electronegative",
				true,
				"Correct. If one atom is more electronegative than the other, electrons of the bond will not be shared equally, resulting in a polar covalent bond.");
			
				p.addAnswer(3, "it is between two atoms that are both very strong electron acceptors",
				false,
				"No. This would not necessarily result in a polar bond.");
			
				p.addAnswer(4, "the two atoms sharing electrons are of the same element",
				false,
				"No. In this instance the two atoms would have equal attraction for electrons.");
			
				p.addAnswer(5, "it is between two atoms that are both very strong electron donors",
				false,
				"No. This would not necessarily result in a polar bond.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334099;


		
		

		
			
			p.question = "When the proton number and electron number are unequal, the atom or molecule _____.\n (<script type=\"text/javascript\">ebook(\'0203\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "forms a covalent bond with another atom",
				false,
				"No. Covalent bonding does not result from an excess or deficiency of electrons, but rather a sharing of pairs of electrons.");
			
				p.addAnswer(2, "is an ion",
				true,
				"Correct. When the proton number and electron number are unequal, the atom or molecule has a net positive (cation) or negative charge (anion).");
			
				p.addAnswer(3, "becomes part of a molecule",
				false,
				"No. For an atom to become part of a molecule, it must be covalently bonded to another atom as a result of the sharing of one or more pairs of electrons.");
			
				p.addAnswer(4, "gains or loses a proton",
				false,
				"No. Gaining or losing a proton would cause the atom to become a different element.");
			
				p.addAnswer(5, "gains or loses a neutron",
				false,
				"No. Gaining or losing a neutron would only cause the atom to become a different isotopic form of the element.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334100;


		
		

		
			
			p.question = "A sodium atom has a mass number of 23. Its atomic number is 11. How many electrons does it have if it is not an ion?\n (<script type=\"text/javascript\">ebook(\'0203\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "11",
				true,
				"Correct. The number of electrons will equal the number of protons in an electrically neutral atom.");
			
				p.addAnswer(2, "12",
				false,
				"No. This configuration would provide 1 extra negative charge. Sodium anions do not exist.");
			
				p.addAnswer(3, "22",
				false,
				"No. This configuration would provide 11 extra negative charges. Review the discussion of atomic number in <script type=\"text/javascript\">ebook(\'0202\',\'quiz\')</script>.");
			
				p.addAnswer(4, "23",
				false,
				"No. The mass number is the sum of protons and neutrons. There should be one electron for each proton.");
			
				p.addAnswer(5, "34",
				false,
				"See <script type=\"text/javascript\">ebook(\'0202\',\'quiz\')</script> to review the definition of atomic number and mass number.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334101;


		
		

		
			
			p.question = "Copper has an atomic number of 29 and a mass number of 64. What would result if an uncharged copper atom lost two electrons? (<script type=\"text/javascript\">ebook(\'0203\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The atom would have a double negative charge and be an ion.",
				false,
				"No. Electrons carry a negative charge. If two electrons were lost the atom would become positively charged.");
			
				p.addAnswer(2, "The atomic number of the atom would remain 29, the mass number would be reduced to 62, and the atom would be an anion.",
				false,
				"No. The mass number is equal to the number of protons and neutrons in the atomic nucleus. The loss or gain of electrons does not enter into the calculation.");
			
				p.addAnswer(3, "The atomic number would remain 29, the mass number would increase to 66, and the atom would be a cation with a -2 charge.",
				false,
				"No. The mass number is equal to the number of protons and neutrons in the atomic nucleus. The loss or gain of electrons does not enter into the calculation.");
			
				p.addAnswer(4, "The atomic number would be reduced to 27, the mass number would remain 64, and the atom would be an anion with a +2 charge.",
				false,
				"No. The loss or gain of an electron(s) does not influence mass number, defined as the number of protons plus the number of neutrons in the nucleus of an atom.");
			
				p.addAnswer(5, "The atomic number would remain 29, the mass number would remain 64, and the atom would be a cation with a +2 charge.",
				true,
				"Correct. The loss or gain of an electron(s) does not influence the atomic number (number of protons) or the mass number (number of protons plus neutrons) of an atom.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334102;


		
		

		
			
			p.question = "The compound CaSO<sub>4</sub> ionizes into a calcium ion and a sulfate ion (SO<sub>4</sub>). Calcium has 2 electrons in its outer shell. Upon ionization, what would you expect the charge on the sulfate ion to be?\n (<script type=\"text/javascript\">ebook(\'0203\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "-4",
				false,
				"No. Calcium has 2 electrons in its outer shell, so the sulfate ion can only pick up 2 electrons, not 4.");
			
				p.addAnswer(2, "+2",
				false,
				"No. The sulfate ion picks up 2 electrons from calcium and hence must gain negative charges.");
			
				p.addAnswer(3, "+1",
				false,
				"No. The sulfate ion picks up 2 electrons from calcium and hence must gain 2 electrons and a negative charge.");
			
				p.addAnswer(4, "-1",
				false,
				"No. Calcium has 2 electrons in its outer shell, so the sulfate ion picks up 2 electrons, not 1.");
			
				p.addAnswer(5, "-2",
				true,
				"Correct. By gaining 2 electrons from calcium, the sulfate ion now has a charge of -2 and calcium has a charge of +2.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334103;


		
		

		
			
			p.question = "Ionic bonds form as a result of _____. (<script type=\"text/javascript\">ebook(\'0203\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "attraction between ions that have opposite charges",
				true,
				"Correct. Oppositely charged ions attract each other electrically, forming an ionic bond.");
			
				p.addAnswer(2, "attraction between hydrogen and other atoms that share electrons unequally",
				false,
				"No. This describes a hydrogen bond.");
			
				p.addAnswer(3, "sharing of electron pairs between atoms",
				false,
				"No. This describes a covalent bond.");
			
				p.addAnswer(4, "unequal sharing of electrons between atoms",
				false,
				"No. This describes a polar covalent bond.");
			
				p.addAnswer(5, "the asymmetric distribution of electrons in constant motion",
				false,
				"No. Attraction resulting from the motion of electrons describes van der Waals interactions.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334104;


		
		

		
			
			p.question = "A hydrogen bond _____. (<script type=\"text/javascript\">ebook(\'0203\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "is one in which two hydrogen atoms bond to each other",
				false,
				"No. This does not describe a hydrogen bond. Two hydrogen atoms would be bonded together by a nonpolar covalent bond to form a molecule of hydrogen gas (H<sub>2</sub> or H-H).");
			
				p.addAnswer(2, "is one in which hydrogen is strongly attracted to a positively charged atom",
				false,
				"No. In a hydrogen bond the hydrogen has a partial positive charge.");
			
				p.addAnswer(3, "is a function of hydrophobic interactions",
				false,
				"No. Hydrogen bonds involve polarity.");
			
				p.addAnswer(4, "is a weak chemical bond",
				true,
				"Correct. Hydrogen bonds are weak chemical bonds that are very important in the chemistry of life.");
			
				p.addAnswer(5, "is a strong chemical bond",
				false,
				"No. Covalent bonds and ionic bonds are strong bonds. Hydrogen bonds are relatively weak bonds.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334105;


		
		

		
			
			p.question = "Hydrogen bonds occur when _____. (<script type=\"text/javascript\">ebook(\'0203\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a molecule with partial charges contacts a molecule without partial charges",
				false,
				"No. In a hydrogen bond, both atoms have a partial charge, but of opposite sign.");
			
				p.addAnswer(2, "a molecule with a low molecular weight is bonded to a molecule with a high molecular weight",
				false,
				"No. Molecular weight is not relevant.");
			
				p.addAnswer(3, "two atoms achieve stable electron configurations by sharing electrons with each other",
				false,
				"No. Hydrogen bonding does not involve electron sharing. This would be a covalent bond.");
			
				p.addAnswer(4, "partial opposite charges on molecules come close enough to attract each other",
				true,
				"Correct. A hydrogen bond occurs when a hydrogen atom covalently bonded to an electronegative atom is attracted to another electronegative atom.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334106;


		
		

		
			
			p.question = "What is the role of Van der Waals interactions in biological molecules?\n (<script type=\"text/javascript\">ebook(\'0203\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Although they are weak bonds, Van der Waals interactions help to reinforce the 3-dimensional shapes of large molecules.",
				true,
				"Correct. Weak bonds are important in the 3-dimensional structure of most large biological molecules, and they play a role in molecular interactions.");
			
				p.addAnswer(2, "Van der Waals interactions are too weak to be significant.",
				false,
				"No. Weak bonds are important in the 3-dimensional structure of most large biological molecules, and they play a role in molecular interactions (consider a gecko).");
			
				p.addAnswer(3, "Van der Waals interactions are strong bonds that play a major structural role in holding proteins together.",
				false,
				"No. Van der Waals interactions are weak bonds, but they do play a role in holding proteins together.");
			
				p.addAnswer(4, "Van der Waals interactions are only important in water.",
				false,
				"No. Van der Waals interactions depend on molecules being close together, not on water.");
			
				p.addAnswer(5, "Although they are weak bonds, Van der Waals interactions involve the sharing of electrons.",
				false,
				"No. Covalent bonding involves the sharing of electrons.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334107;


		
		

		
			
			p.question = "Which of the following molecules has the shape of a completed tetrahedron? (<script type=\"text/javascript\">ebook(\'0203\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "water (H<sub>2</sub>O)",
				false,
				"No. The water molecule is shaped roughly like a V.");
			
				p.addAnswer(2, "hydrogen gas (H<sub>2</sub>)",
				false,
				"No. A molecule consisting of two atoms is always linear.");
			
				p.addAnswer(3, "oxygen gas (O<sub>2</sub>)",
				false,
				"No. A molecule consisting of two atoms is always linear.");
			
				p.addAnswer(4, "methane (CH<sub>4</sub>)",
				true,
				"Correct. The nucleus of the carbon atom is at the center of the tetrahedron, with its four covalent bonds radiating to the hydrogen nuclei at the corners of the tetrahedron.");
			
				p.addAnswer(5, "glucose (C<sub>6</sub>H<sub>12</sub>O<sub>6</sub>)",
				false,
				"No. Molecules containing multiple carbon atoms have more complex overall shapes.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334108;


		
		

		
			
			p.question = "Pharmaceutical researchers are often interested in blocking particular receptor proteins on cell surfaces. What chemical property of a molecule would be most important for this type of application?\n(<script type=\"text/javascript\">ebook(\'0203\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The atomic numbers of the atoms involved.",
				false,
				"No. Atomic number is not as important as how the atoms interact to form a particular shape.");
			
				p.addAnswer(2, "The molecule\'s shape.",
				true,
				"Correct. The molecule would have to have the correct shape to bind to the receptor protein and block it.");
			
				p.addAnswer(3, "The number of valence electrons.",
				false,
				"No. Valence electrons are important in putting molecules together by way of covalent bonds. Molecular shape is more important in determining how molecules interact.");
			
				p.addAnswer(4, "The type of bonding in the molecule.",
				false,
				"No. Although the type of bonding within the molecule does determine the shape of the molecule, there is a better answer.");
			
				p.addAnswer(5, "The number of double bonds in the molecule.",
				false,
				"No. Although double bonding within the molecule does play a role in determining the shape of the molecule, there is a better answer");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334109;


		
		

		
			
			p.question = "Which of the following statements is true about chemical reactions?\n (<script type=\"text/javascript\">ebook(\'0204\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "They represent the way matter is created and destroyed.",
				false,
				"No. Chemical reactions rearrange matter, but they cannot create or destroy matter under normal situations.");
			
				p.addAnswer(2, "They reach chemical equilibrium when there is the same amount of products and reactants.",
				false,
				"No. Chemical equilibrium is reached when the forward and reverse reaction rates are equal.");
			
				p.addAnswer(3, "They may have different numbers of a given atom on each side of the equation arrow.",
				false,
				"No. The equation for a chemical reaction must always balance.");
			
				p.addAnswer(4, "They involve the making and breaking of chemical bonds.",
				true,
				"Correct. This is how chemical changes occur.");
			
				p.addAnswer(5, "Only inorganic molecules can participate in chemical reactions.",
				false,
				"No. They can involve any chemicals that will react.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334110;


		
		

		
			
			p.question = "Which of the following statements describes a reversible reaction that has reached chemical equilibrium?\n (<script type=\"text/javascript\">ebook(\'0204\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The rate of the reverse reaction exceeds the rate of the forward reaction.",
				false,
				"No. This would occur if additional products were added prior to the attainment of chemical equilibrium.");
			
				p.addAnswer(2, "The rate of the reverse reaction equals the rate of the forward reaction.",
				true,
				"Correct. This is the definition of chemical equilibrium.");
			
				p.addAnswer(3, "The rate of the forward reaction exceeds the rate of the reverse reaction.",
				false,
				"No. This would be true for a reversible reaction prior to chemical equilibrium, but not after chemical equilibrium had been reached.");
			
				p.addAnswer(4, "The forward and the reverse reactions have stopped.",
				false,
				"No. The forward and reverse reactions do not stop and the relative concentrations of the reactants and products do not change when a reversible reaction is at chemical equilibrium.");
			
				p.addAnswer(5, "The concentration of the reactants is equal to the concentration of the products.",
				false,
				"No. Think about equal reaction rates, not equal concentrations of reactants and products.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

