

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "Investigation Quiz > How Does Acid Precipitation Affect Trees?";
	ak.quiz_loc_with_commas = "Investigation Quiz, How Does Acid Precipitation Affect Trees?";
	ak.quiz_title = "How Does Acid Precipitation Affect Trees?";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 10;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 10;
	ak.non_essay_total = 0;
	ak.scored_item_total = 0;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337527;


		
		

		
			p.question = "What are probable sources of acid precipitation in your community? What impact can this have on the environment in your region?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337528;


		
		

		
			p.question = "What factors apart from acid rain could be killing trees?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337529;


		
		

		
			p.question = "Limestone, an underlying material for many soils, dissolves and corrodes when exposed to high concentrations of hydrogen ions. How is this information important in understanding the effects of acid precipitation?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337530;


		
		

		
			p.question = "Acid precipitation is considered severe if it falls below pH 4. Considering the pH of rainwater, how easy would it be to convert the rainwater to acid precipitation?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337531;


		
		

		
			p.question = "Carbon dioxide forms a weak acid called carbonic acid when dissolved in water. How can this be a significant factor in the formation of acid rain?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337532;


		
		

		
			p.question = "Frogs are very sensitive to acid rain. How could this information be used to investigate your observation about the trees dying in the forest?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337533;


		
		

		
			p.question = "What events could have created the increase in acid precipitation between 1955 and 1990?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337534;


		
		

		
			p.question = "Why is the Canadian government particularly concerned about negotiating clean air agreements with the United States?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337535;


		
		

		
			p.question = "What is the average number of leaves per tree and the percentage of damaged leaves for both the experimental and control plants over the duration of the experiment?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337536;


		
		

		
			p.question = "What can you conclude from these results?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

