

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "29: Plant Diversity I: How Plants Colonized Land > Activities Quiz";
	ak.quiz_loc_with_commas = "29: Plant Diversity I: How Plants Colonized Land, Activities Quiz";
	ak.quiz_title = "Activities Quiz";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 15;
	ak.non_essay_total = 15;
	ak.scored_item_total = 15;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335730;


		
		

		
			
			p.question = "Angiosperms are most closely related to _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?29&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Highlights of Plant Phylogeny</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "green algae",
				false,
				"You need to take another look at the phylogenetic tree in the activity.");
			
				p.addAnswer(2, "charophyceans",
				false,
				"Angiosperms and charophyceans are at opposite ends of the phylogenetic tree in the activity.");
			
				p.addAnswer(3, "bryophytes",
				false,
				"You need to take another look at the phylogenetic tree in the activity.");
			
				p.addAnswer(4, "seedless vascular plants",
				false,
				"You need to take another look at the phylogenetic tree in the activity.");
			
				p.addAnswer(5, "gymnosperms",
				true,
				"The branching pattern of the phylogenetic tree in the activity indicates that angiosperms are most closely related to gymnosperms.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335731;


		
		

		
			
			p.question = "Which of these was the dominant plant group at the time that dinosaurs were the dominant animals? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?29&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Highlights of Plant Phylogeny</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "seedless vascular plants",
				false,
				"Ferns and other seedless vascular plants were dominant during the Paleozoic, dinosaurs during the Mesozoic.");
			
				p.addAnswer(2, "charophyceans",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(3, "gymnosperms",
				true,
				"Both gymnosperms and dinosaurs were dominant during the Mesozoic.");
			
				p.addAnswer(4, "angiosperms",
				false,
				"The appearance of angiosperms and the extinction of many dinosaur lineages both occurred during the Cretaceous.");
			
				p.addAnswer(5, "bryophytes",
				false,
				"No, that is incorrect.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335732;


		
		

		
			
			p.question = "This is an image of a(n) _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?29&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Highlights of Plant Phylogeny</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/2903q.jpg\" ALT=\"Question #3\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "bryophyte",
				false,
				"Bryophytes have gametangia.");
			
				p.addAnswer(2, "gymnosperm",
				false,
				"Conifers are gymnosperms.");
			
				p.addAnswer(3, "charophycean",
				true,
				"Charophyceans are the green algae most closely related to plants.");
			
				p.addAnswer(4, "angiosperm",
				false,
				"Angiosperms are flowering plants.");
			
				p.addAnswer(5, "seedless vascular plant",
				false,
				"Ferns are examples of seedless vascular plants.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335733;


		
		

		
			
			p.question = "Plants evolved from green algae approximately _____ million years ago. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?29&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Highlights of Plant Phylogeny</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "130",
				false,
				"The radiation of angiosperms began about 130 million years ago.");
			
				p.addAnswer(2, "400",
				false,
				"Vascular plants evolved about 400 million years ago.");
			
				p.addAnswer(3, "475",
				true,
				"Plants evolved from green algae about 475 million years ago.");
			
				p.addAnswer(4, "2,200",
				false,
				"Atmospheric levels of oxygen began to increase about 2,200 million years ago.");
			
				p.addAnswer(5, "3,500",
				false,
				"The oldest known fossils date to about 3,500 million years ago.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335734;


		
		

		
			
			p.question = "_____ are an example of seedless vascular plants. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?29&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Highlights of Plant Phylogeny</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Mosses",
				false,
				"Mosses are bryophytes.");
			
				p.addAnswer(2, "Lilacs",
				false,
				"Lilacs are angiosperms.");
			
				p.addAnswer(3, "Charophyceans",
				false,
				"Charophyceans are green algae.");
			
				p.addAnswer(4, "Ferns",
				true,
				"Ferns are seedless vascular plants.");
			
				p.addAnswer(5, "Pine trees",
				false,
				"Pine trees are gymnosperms.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335735;


		
		

		
			
			p.question = "The living plants that are most similar to the first plants to bear gametangia are the _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?29&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Highlights of Plant Phylogeny</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "bryophytes",
				true,
				"Bryophytes, such as mosses, are the extant plants that are most similar to the first plants to bear gametangia.");
			
				p.addAnswer(2, "charophyceans",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(3, "seedless vascular plants",
				false,
				"Another group is more similar to the first plants to bear gametangia.");
			
				p.addAnswer(4, "gymnosperms",
				false,
				"Another group is more similar to the first plants to bear gametangia.");
			
				p.addAnswer(5, "angiosperms",
				false,
				"Of the plant groups studied in this exercise, angiosperms are the most different from the first plants to bear gametangia.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335736;


		
		

		
			
			p.question = "Which of these characteristics is shared by algae and seed plants? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?29&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Terrestrial Adaptations of Plants</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "embryo development within gametangia",
				false,
				"This is a characteristic of seed plants not seen in algae.");
			
				p.addAnswer(2, "roots and shoots",
				false,
				"This is a characteristic of seed plants not seen in algae.");
			
				p.addAnswer(3, "vascular tissue",
				false,
				"This is a characteristic of seed plants not seen in algae.");
			
				p.addAnswer(4, "pollen",
				false,
				"This is a characteristic of seed plants not seen in algae.");
			
				p.addAnswer(5, "chloroplasts",
				true,
				"Both algae and seed plants have cells with chloroplasts.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335737;


		
		

		
			
			p.question = "Which of these represents the sporophyte generation of the moss life cycle? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?29&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Moss Life Cycle</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/2908q.jpg\" ALT=\"Question #8\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A",
				false,
				"This is the haploid protonema.");
			
				p.addAnswer(2, "B",
				false,
				"This is the developing haploid gametophyte.");
			
				p.addAnswer(3, "C",
				false,
				"This is the haploid male gametophyte.");
			
				p.addAnswer(4, "D",
				false,
				"This is the haploid female gametophyte.");
			
				p.addAnswer(5, "E",
				true,
				"This is the young diploid sporophyte.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335738;


		
		

		
			
			p.question = "In moss, _____ produce sperm. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?29&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Moss Life Cycle</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "sporangia",
				false,
				"Sporangia produce haploid spores.");
			
				p.addAnswer(2, "antheridia",
				true,
				"Moss antheridia, found on the tops of male gametophytes, produce sperm.");
			
				p.addAnswer(3, "embryos",
				false,
				"The diploid embryo develops in a diploid sporophyte.");
			
				p.addAnswer(4, "archegonia",
				false,
				"Archegonia, found at the tips of female gametophytes, produce eggs.");
			
				p.addAnswer(5, "protonemata",
				false,
				"A protonema eventually develops into a male or female gametophyte.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335739;


		
		

		
			
			p.question = "The sperm produced by mosses require _____ to reach an archegonium. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?29&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Moss Life Cycle</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "wind",
				false,
				"Moss sperm are not airborne.");
			
				p.addAnswer(2, "light",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(3, "moisture",
				true,
				"Moss sperm swim to archegonia.");
			
				p.addAnswer(4, "the development of a flower",
				false,
				"Mosses are bryophytes, not angiosperms.");
			
				p.addAnswer(5, "animals",
				false,
				"Animals do not transport the sperm of mosses.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335740;


		
		

		
			
			p.question = "In the moss life cycle _____ cells within a sporangium undergo _____ to produce _____ spores. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?29&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Moss Life Cycle</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "diploid ... meiosis ... haploid",
				true,
				"Diploid sporophytes develop from diploid embryos. Sporophytes bear a sporangium in which cells undergo meiosis to produce haploid spores.");
			
				p.addAnswer(2, "haploid ... mitosis ... haploid",
				false,
				"Sporangia are diploid.");
			
				p.addAnswer(3, "diploid ... mitosis ... diploid",
				false,
				"Spores are haploid.");
			
				p.addAnswer(4, "diploid ... mitosis ... haploid",
				false,
				"By mitosis a diploid cell produces diploid cells.");
			
				p.addAnswer(5, "haploid ... meiosis ... haploid",
				false,
				"Haploid cells do not undergo meiosis.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335741;


		
		

		
			
			p.question = "In mosses gametes are produced by _____; in ferns gametes are produced by _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?29&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Moss Life Cycle</a>, <a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?29&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Fern Life Cycle</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "binary fission ... mitosis",
				false,
				"Bacteria reproduce by binary fission.");
			
				p.addAnswer(2, "meiosis ... meiosis",
				false,
				"Consider where their gametes are produced.");
			
				p.addAnswer(3, "meiosis ... mitosis",
				false,
				"Consider where their gametes are produced.");
			
				p.addAnswer(4, "mitosis ... meiosis",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(5, "mitosis ... mitosis",
				true,
				"In both, gametes are produced by haploid gametophytes.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335742;


		
		

		
			
			p.question = "Which of these structures is diploid? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?29&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Fern Life Cycle</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/2913q.jpg\" ALT=\"Question #13\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A",
				false,
				"Fern spores are haploid.");
			
				p.addAnswer(2, "B",
				false,
				"Gametophytes are haploid.");
			
				p.addAnswer(3, "C",
				false,
				"Archegonia are haploid.");
			
				p.addAnswer(4, "D",
				true,
				"A diploid sporophyte develops from a zygote that was produced when a haploid sperm fertilized a haploid egg.");
			
				p.addAnswer(5, "E",
				false,
				"Gametophytes are haploid.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335743;


		
		

		
			
			p.question = "Where do fern antheridia develop? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?29&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Fern Life Cycle</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "on the underside of the gametophyte",
				true,
				"Haploid antheridia in ferns develop on the underside of mature haploid gametophytes.");
			
				p.addAnswer(2, "on the tip of the gametophyte",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(3, "on the tip of the sporophyte",
				false,
				"Antheridia produce sperm by mitosis, which occurs in the gametophyte.");
			
				p.addAnswer(4, "on the tip of the haploid protonema",
				false,
				"The protonema is a structure associated with mosses.");
			
				p.addAnswer(5, "on the underside of the sporophyte",
				false,
				"Haploid antheridia are produced by mitosis.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335744;


		
		

		
			
			p.question = "The conspicuous part of a fern plant is a _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?29&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Fern Life Cycle</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "haploid gametophyte",
				false,
				"Unlike mosses, the fern gametophyte is not the conspicuous portion of the life cycle.");
			
				p.addAnswer(2, "diploid gametophyte",
				false,
				"Gametophytes are always haploid.");
			
				p.addAnswer(3, "diploid sorus",
				false,
				"Sori are clusters of haploid cells.");
			
				p.addAnswer(4, "diploid sporophyte",
				true,
				"In ferns, while the gametophyte generation is independent, the diploid sporophyte is much larger.");
			
				p.addAnswer(5, "haploid sporophyte",
				false,
				"Sporophytes are diploid.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

