

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "28: Protists > Practice Test";
	ak.quiz_loc_with_commas = "28: Protists, Practice Test";
	ak.quiz_title = "Practice Test";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 32;
	ak.non_essay_total = 32;
	ak.scored_item_total = 32;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335695;


		
		

		
			
			p.question = "Why have protists been \"mixed in\" with plants, animals, and fungi in the hypothesis that groups eukaryotes into five supergroups? (<script type=\"text/javascript\">ebook(\'28OV\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Many protists are more closely related to plants, animals, or fungi then they are to each other.",
				false,
				"No. This is true, but there is a better answer.");
			
				p.addAnswer(2, "The discovery of very small protists, similar in size to prokaryotes, has made the former classification scheme obsolete.",
				false,
				"No. Although many surprisingly small protists have been discovered, this is not the reason for grouping protists with other eukaryotes in the five supergroup scheme.");
			
				p.addAnswer(3, "Recent evidence makes it clear that the former Kingdom Protista was paraphyletic.",
				false,
				"No. This is true but there is a better answer.");
			
				p.addAnswer(4, "The discovery that protists had organelles made it clear that they should be grouped with other eukaryotes.",
				false,
				"No. It has long been known that protists are eukaryotic organisms with organelles. This is not the reason for the change in classification.");
			
				p.addAnswer(5, "both a and c",
				true,
				"Correct. Molecular, morphological, and biochemical evidence has begun to elucidate the relationships among eukaryotes. The former Kingdom Protista has been abandoned.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335696;


		
		

		
			
			p.question = "The placement of all protists in one kingdom caused dissatisfaction among taxonomists mainly because _____. (<script type=\"text/javascript\">ebook(\'2801\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "some protists are autotrophic and others are heterotrophic",
				false,
				"No. This is true, but there is a more specific answer to explain their dissatisfaction.");
			
				p.addAnswer(2, "protist cells are more similar to prokaryotic cells than to eukaryotic cells",
				false,
				"No. Protists are eukaryotes.");
			
				p.addAnswer(3, "various pieces of evidence indicate that the kingdom Protista cannot be monophyletic",
				true,
				"Correct. Systematists working on the puzzle of eukaryotic relationships now consider the kingdom Protista and the five-kingdom system obsolete. Kingdom Protista is polyphyletic&mdash;its members are derived from two or more ancestral forms not common to all members.");
			
				p.addAnswer(4, "various pieces of evidence indicate that the Protista are not polyphyletic",
				false,
				"No. Evidence indicates that the Protista are polyphyletic.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. Only one of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335697;


		
		

		
			
			p.question = "What is one of the main weaknesses of the proposed classification scheme in which all eukaryotes are divided into five supergroups? (<script type=\"text/javascript\">ebook(\'2801\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "It does not account for \"amitochondriate\" protists.",
				false,
				"No. Protists with missing or reduced mitochondria can be classified using this scheme.");
			
				p.addAnswer(2, "It does not take into account the importance of endosymbiosis.",
				false,
				"No. In fact some organisms are grouped according to the hypothesis that they all descended from an organism that engulfed an endosymbiont.");
			
				p.addAnswer(3, "It shows all five supergroups diverging simultaneously from a common ancestor.",
				true,
				"Correct. Because the origin of eukaryotes is not yet known, it is impossible to accurately portray the branch points in eukaryotic lineages. Even though scientists know that this divergence is not simultaneous, it must be shown that way until more evidence is uncovered.");
			
				p.addAnswer(4, "It does not explain the extra membranes found in some plastids.",
				false,
				"No. The extra membranes found in some plastids are evidence for endosymbiosis, which is taken into account in this classification scheme.");
			
				p.addAnswer(5, "It postulates that photosynthetic protists arose by way of endosymbiosis.",
				false,
				"No. This is not a weakness of this hypothesis. There is abundant evidence that photosynthetic protists arose by endosymbiosis.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335698;


		
		

		
			
			p.question = "Organisms are classified as Excavata based on ______. (<script type=\"text/javascript\">ebook(\'2802\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "their origin by secondary endosymbiosis of a red alga",
				false,
				"No. Chromalveolates are grouped based on this characteristic.");
			
				p.addAnswer(2, "morphological studies of the cytoskeleton",
				true,
				"Correct. Cytoskeleton structure is the major characteristic for identifying excavates.");
			
				p.addAnswer(3, "their lack of true mitochondria",
				false,
				"No. Some members of this group have reduced mitochondria, but others have very pronounced mitochondria.");
			
				p.addAnswer(4, "the presence of pseudopodia",
				false,
				"No. This is not a characteristic of excavates.");
			
				p.addAnswer(5, "their mode of obtaining energy",
				false,
				"No. Excavates have many ways of obtaining energy, so this characteristic is not used as a defining one.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335699;


		
		

		
			
			p.question = "Which example below is a characteristic shared by diplomonads and parabasalids? (<script type=\"text/javascript\">ebook(\'2802\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Both lack plastids.",
				true,
				"Correct. This is a characteristic shared by both of these protists.");
			
				p.addAnswer(2, "Both are adapted to aerobic environments.",
				false,
				"No. Both, rather, are adapted to anaerobic environments.");
			
				p.addAnswer(3, "Both lack mitochondria.",
				false,
				"No. Their mitochondria, though very much reduced, are usually present in one form or another.");
			
				p.addAnswer(4, "Both have a single flagellum.",
				false,
				"No. Both, rather, have multiple flagella.");
			
				p.addAnswer(5, "Both have two nuclei.",
				false,
				"No. This is true only of the diplomonads.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335700;


		
		

		
			
			p.question = "Although controversial, chromalveolates are proposed as a clade whose common ancestor ______. (<script type=\"text/javascript\">ebook(\'2803\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "engulfed an alpha proteobacterium in a primary endosymbiosis event",
				false,
				"No. This scenario is proposed to explain the origin of mitochondria in general.");
			
				p.addAnswer(2, "was the first mixotroph",
				false,
				"No. It is not clear when mixotrophy arose.");
			
				p.addAnswer(3, "was a multinucleate mass",
				false,
				"No. This is not proposed as a common ancestor of chromalveolates.");
			
				p.addAnswer(4, "engulfed a photosynthetic red alga in a secondary endosymbiosis event",
				true,
				"Correct. The presence of plastids that appear to be derived from a red algal ancestor, or remnants of such a plastid in the genomes of many chromalveolates is the basis for placing organisms in this group.");
			
				p.addAnswer(5, "lost its mitochondria",
				false,
				"No. Chromalveolates have mitochondria.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335701;


		
		

		
			
			p.question = "How do trypanosomes withstand the attack of a host\'s immune system? (<script type=\"text/javascript\">ebook(\'2803\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "They reproduce so fast that they can compensate for the death rate caused by the immune system.",
				false,
				"No. They manage to evade the immune system.");
			
				p.addAnswer(2, "They live only in the cerebrospinal fluid, where the immune system can\'t reach them.",
				false,
				"No. They have other methods of evading the immune system.");
			
				p.addAnswer(3, "They specifically poison helper T cells.",
				false,
				"No. They have other methods of evading the immune system.");
			
				p.addAnswer(4, "The molecular composition of their surface changes continually.",
				true,
				"Correct. The immune system response is always lagging behind the frequent changes in the molecular composition of the trypanosome surface.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. Only one of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335702;


		
		

		
			
			p.question = "Apicomplexans are currently assigned to the chromalveolates because _______. (<script type=\"text/javascript\">ebook(\'2803\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "they have life cycles with both sexual and asexual stages",
				false,
				"No. Many protists from many groups have sexual and asexual stages.");
			
				p.addAnswer(2, "they have true roots, stems, and leaves",
				false,
				"No. That would make them plants.");
			
				p.addAnswer(3, "they are parasites",
				false,
				"No. Many protists in other groups are also parasitic.");
			
				p.addAnswer(4, "the apicoplast, a modified plastid, appears to be of red algal origin",
				true,
				"Correct. Chromalveolates are descendants of an organism that engulfed a red alga in a secondary endosymbiosis event. The presence of a plastid that seems to be of red algal origin would be grounds for classifying apicomplexans as chromalveolates.");
			
				p.addAnswer(5, "both a and c",
				false,
				"No. Apicomplexans are classified as chromalveolates on the basis of a plastid that appears to be of red algal origin.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335703;


		
		

		
			
			p.question = "Which of these groups includes photosynthetic unicellular organisms with flagella and contractile vacuoles? (<script type=\"text/javascript\">ebook(\'2803\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "diatoms",
				false,
				"No. Diatoms do not fit this description.");
			
				p.addAnswer(2, "dinoflagellates",
				false,
				"No. Dinoflagellates do not fit this description.");
			
				p.addAnswer(3, "euglenids",
				true,
				"Correct. <i>Euglena</i> has a long tinseled flagellum, a contractile vacuole, and chloroplasts for photosynthesis.");
			
				p.addAnswer(4, "ciliates",
				false,
				"No. Ciliates do not fit this description.");
			
				p.addAnswer(5, "apicomplexans",
				false,
				"No. Apicomplexans do not fit this description.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335704;


		
		

		
			
			p.question = "In many types of protist life cycles, the union of two gametes that results in a diploid zygote is called _______. (<script type=\"text/javascript\">ebook(\'2803\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "mixotrophy",
				false,
				"No. Mixotrophy is a way of getting energy.");
			
				p.addAnswer(2, "syngamy",
				true,
				"Correct. Syngamy is another word used for fertilization.");
			
				p.addAnswer(3, "endosymbiosis",
				false,
				"No. Endosymbiosis occurs when one organism engulfs another, but instead of being digested, the engulfed organism forms a mutualistic relationship with the host.");
			
				p.addAnswer(4, "multinucleate",
				false,
				"No. Multinucleate organisms have a single cell with many nuclei. These form by repeated mitosis with cytokinesis.");
			
				p.addAnswer(5, "alveoli",
				false,
				"No. These are small membrane-bound sacs found in many of the chromalveolates.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335705;


		
		

		
			
			p.question = "What do a carnivorous dinoflagellate, a parasitic apicomplexan, and a ciliate have in common? (<script type=\"text/javascript\">ebook(\'2803\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "All three are heterotrophic and autotrophic.",
				false,
				"No. This is not true.");
			
				p.addAnswer(2, "All three form colonies of cells.",
				false,
				"No. None of them form colonies of cells.");
			
				p.addAnswer(3, "All three are parasitic on other species of organisms.",
				false,
				"No. Only the apicomplexan is parasitic.");
			
				p.addAnswer(4, "All three have sacs known as alveoli just beneath their plasma membranes.",
				true,
				"Correct. This is one characteristic that unites these three distinct types of protists into a group called Chromalveolata.");
			
				p.addAnswer(5, "All three are photosynthetic.",
				false,
				"No. Only some dinoflagellates are photosynthetic.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335706;


		
		

		
			
			p.question = "Which organisms are capable of producing a \"red tide\"? (<script type=\"text/javascript\">ebook(\'2803\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "dinoflagellates",
				true,
				"Correct. Dinoflagellate blooms, episodes of explosive population growth, cause red tides in coastal waters.");
			
				p.addAnswer(2, "chrysophytes (diatoms)",
				false,
				"No. Diatoms are not responsible for red tides.");
			
				p.addAnswer(3, "sporozoans",
				false,
				"No. Sporozoans are not responsible for red tides.");
			
				p.addAnswer(4, "euglenids",
				false,
				"No. Euglenids are not responsible for red tides.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335707;


		
		

		
			
			p.question = "Which of these groups includes species that produce a substance that is toxic to humans? (<script type=\"text/javascript\">ebook(\'2803\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "diatoms",
				false,
				"No. Toxins produced by some red-tide organisms (dinoflagellates) have produced massive invertebrate kills and can be deadly to humans that consume contaminated seafood.");
			
				p.addAnswer(2, "dinoflagellates",
				true,
				"Correct. Toxins produced by some red-tide organisms (dinoflagellates) have produced massive invertebrate kills and can be deadly to humans that consume contaminated seafood.");
			
				p.addAnswer(3, "euglenids",
				false,
				"No. Toxins produced by some red-tide organisms (dinoflagellates) have produced massive invertebrate kills and can be deadly to humans that consume contaminated seafood.");
			
				p.addAnswer(4, "ciliates",
				false,
				"No. Toxins produced by some red-tide organisms (dinoflagellates) have produced massive invertebrate kills and can be deadly to humans that consume contaminated seafood.");
			
				p.addAnswer(5, "apicomplexans",
				false,
				"No. Toxins produced by some red-tide organisms (dinoflagellates) have produced massive invertebrate kills and can be deadly to humans that consume contaminated seafood.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335708;


		
		

		
			
			p.question = "Which of these groups includes parasitic unicellular organisms with a complex of organelles specialized for penetrating host cells and tissues? (<script type=\"text/javascript\">ebook(\'2803\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "diatoms",
				false,
				"No. Diatoms do not fit this description.");
			
				p.addAnswer(2, "dinoflagellates",
				false,
				"No. Dinoflagellates do not fit this description.");
			
				p.addAnswer(3, "euglenoids",
				false,
				"No. Euglenoids<b> </b>do not fit this description.");
			
				p.addAnswer(4, "ciliates",
				false,
				"No. Ciliates do not fit this description.");
			
				p.addAnswer(5, "apicomplexans",
				true,
				"Correct. Apicomplexans are parasites of animals. The apex of the sporozoite cell contains a complex of organelles specialized for penetrating host cells and tissues, thus the name \"Apicomplexa.\"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335709;


		
		

		
			
			p.question = "Which of these groups is characterized by cells that have more than one nucleus? (<script type=\"text/javascript\">ebook(\'2803\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "diatoms",
				false,
				"No. This is not characteristic of diatoms.");
			
				p.addAnswer(2, "dinoflagellates",
				false,
				"No. This is not characteristic of dinoflagellates.");
			
				p.addAnswer(3, "euglenids",
				false,
				"No. This is not characteristic of euglenids.");
			
				p.addAnswer(4, "ciliates",
				true,
				"Correct. A unique feature of ciliate genetics is the presence of two types of nuclei: a large macronucleus and usually several tiny micronuclei.");
			
				p.addAnswer(5, "apicomplexans",
				false,
				"No. This is not characteristic of apicomplexans.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335710;


		
		

		
			
			p.question = "How do ciliates generate genetic variation? (<script type=\"text/javascript\">ebook(\'2803\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "binary fission",
				false,
				"No. Although ciliates do reproduce by binary fission, this involves one cell elongating and splitting in two. Genetic variation is not a result of binary fission.");
			
				p.addAnswer(2, "asexual reproduction",
				false,
				"No. Asexual reproduction does not generally introduce genetic variation.");
			
				p.addAnswer(3, "conjugation",
				true,
				"Correct. Conjugation is a sexual process in which two individuals exchange haploid micronuclei.");
			
				p.addAnswer(4, "alternation of generations",
				false,
				"No. Genetic variation in ciliates is the result of conjugation.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335711;


		
		

		
			
			p.question = "Which protists were once categorized as fungi due to their multinucleate filaments that resemble hyphae? (<script type=\"text/javascript\">ebook(\'2803\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "dinoflagellates",
				false,
				"No. Dinoflagellates were not originally categorized as fungi.");
			
				p.addAnswer(2, "stramenopiles",
				false,
				"No. The correct answer is a member of the clade Stramenopila, but not all members of this clade were once categorized as fungi.");
			
				p.addAnswer(3, "golden algae",
				false,
				"No. Golden algae were not originally categorized as fungi.");
			
				p.addAnswer(4, "oomycetes",
				true,
				"Correct. Eventually, systematists concluded that the multinucleate filaments in oomycetes (water molds and their relatives) and fungi are an example of convergent evolution.");
			
				p.addAnswer(5, "parabasalids",
				false,
				"No. Parabasalids were not originally categorized as fungi.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335712;


		
		

		
			
			p.question = "_____ is a protist that causes late blight of potatoes and was responsible for the Irish potato famine of the 19th century. (<script type=\"text/javascript\">ebook(\'2803\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "<i>Phytophthora infestans</i>",
				true,
				"Correct. In recent years, scientists have discovered that the protist is showing resistance to pesticides. Efforts to place genes from wild potato plants that are resistant to infection into domestic potatoes have been successful.");
			
				p.addAnswer(2, "<i>Dinobryon</i>",
				false,
				"No. <i>Dinobryon </i>is an example of a colonial golden algae.");
			
				p.addAnswer(3, "<i>Laminaria</i>",
				false,
				"No. <i>Laminaria</i> is a brown alga, which in Japan is used in soups.");
			
				p.addAnswer(4, "<i>Entamoeba</i>",
				false,
				"No. <i>Entamoeba</i> is a parasite that infects all classes of vertebrates as well as some invertebrates.");
			
				p.addAnswer(5, "<i>Dictyostelium discoideum</i>",
				false,
				"No. <i>Dictyostelium discoideum</i> is a common cellular slime mold found on forest floors.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335713;


		
		

		
			
			p.question = "Which of these groups includes unicellular organisms that, due to the structure of their cell walls, can withstand pressures equal to the pressure under each leg of a table supporting an elephant? (<script type=\"text/javascript\">ebook(\'2803\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "diatoms",
				true,
				"Correct. Diatoms have unique glass-like walls that consist of hydrated silica embedded in an organic matrix. Each wall has two parts that overlap like a shoebox and lid.");
			
				p.addAnswer(2, "dinoflagellates",
				false,
				"No. Diatoms have unique glass-like walls that consist of hydrated silica embedded in an organic matrix. Each wall has two parts that overlap like a shoebox and lid.");
			
				p.addAnswer(3, "euglenids",
				false,
				"No. Diatoms have unique glass-like walls that consist of hydrated silica embedded in an organic matrix. Each wall has two parts that overlap like a shoebox and lid.");
			
				p.addAnswer(4, "ciliates",
				false,
				"No. Diatoms have unique glass-like walls that consist of hydrated silica embedded in an organic matrix. Each wall has two parts that overlap like a shoebox and lid.");
			
				p.addAnswer(5, "apicomplexans",
				false,
				"No. Diatoms have unique glass-like walls that consist of hydrated silica embedded in an organic matrix. Each wall has two parts that overlap like a shoebox and lid.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335714;


		
		

		
			
			p.question = "Which characteristic is shared by most diatoms, golden algae, and brown algae at least at some stage of their life cycles? (<script type=\"text/javascript\">ebook(\'2803\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "They all have flagella with numerous fine, hair-like projections.",
				false,
				"No. This is a true statement, but there is a better choice.");
			
				p.addAnswer(2, "All three store food reserves in the form of a glucose polymer called laminarin.",
				false,
				"No. This is a true statement, but there is a better choice.");
			
				p.addAnswer(3, "All are autotrophs.",
				false,
				"No. This is a true statement, but there is a better choice.");
			
				p.addAnswer(4, "all of the above",
				true,
				"Correct. Diatoms, golden algae, and brown algae are all part of the group Stramenopila, and they share the above characteristics.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. All of the above are shared characteristics.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335715;


		
		

		
			
			p.question = "The general term given to a plant-like body that lacks true stems, leaves, and roots and that shows little tissue differentiation is _____. (<script type=\"text/javascript\">ebook(\'2803\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "stipe",
				false,
				"No. The stipe is a stem-like structure.");
			
				p.addAnswer(2, "rhizoid",
				false,
				"No. Rhizoids are root-like structures.");
			
				p.addAnswer(3, "strobilus",
				false,
				"No. A strobilus is a reproductive structure.");
			
				p.addAnswer(4, "thallus",
				true,
				"Correct. The term \"thallus\" is used for a plant-like seaweed body that lacks true roots, stems, and leaves.");
			
				p.addAnswer(5, "gametophyte",
				false,
				"No. A gametophyte is a structure that produces haploid gametes.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335716;


		
		

		
			
			p.question = "What is the purpose of the \"floats\" in some brown algae? (<script type=\"text/javascript\">ebook(\'2803\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "anchoring the seaweed",
				false,
				"No. This is the purpose of holdfasts.");
			
				p.addAnswer(2, "protecting seaweed from crashing waves",
				false,
				"No. Their cell walls are composed of cellulose and gel-forming polysaccharides that help cushion the thalli against wave agitation and reduce drying when they are exposed.");
			
				p.addAnswer(3, "keeping the blades closer to the water\'s surface",
				true,
				"Correct. This function allows the blades to have more access to sunlight for photosynthesis.");
			
				p.addAnswer(4, "protecting the seaweed from drying out",
				false,
				"No. Their cell walls are composed of cellulose and gel-forming polysaccharides that help cushion the thalli against wave agitation and reduce drying when they are exposed.");
			
				p.addAnswer(5, "absorbing iodine and carbon dioxide from seawater",
				false,
				"No. All parts of seaweeds accomplish these functions.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335717;


		
		

		
			
			p.question = "Which of the following organisms are commercially harvested to extract algin from their cell walls? (<script type=\"text/javascript\">ebook(\'2803\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "dinoflagellates",
				false,
				"No. Dinoflagellates are infamous for red tides.");
			
				p.addAnswer(2, "golden algae",
				false,
				"No. The answer is a type of algae, but not golden algae.");
			
				p.addAnswer(3, "brown algae",
				true,
				"Correct. The gel-forming substance algin in the walls of brown algae is extracted in commercial operations.");
			
				p.addAnswer(4, "marine green algae, like <i>Ulva</i>",
				false,
				"No. The answer is a type of algae, but not green algae.");
			
				p.addAnswer(5, "diatoms",
				false,
				"No. Diatoms have cell walls composed of silica, and they do not contain algin.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335718;


		
		

		
			
			p.question = "What role do diatoms play in the global carbon balance affecting global warming? (<script type=\"text/javascript\">ebook(\'2803\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Diatoms release large amounts of methane, a greenhouse gas, into the atmosphere.",
				false,
				"No. Diatoms do not release methane.");
			
				p.addAnswer(2, "Diatoms release large amounts of carbon dioxide, a greenhouse gas, into the atmosphere.",
				false,
				"No. Diatoms do release some carbon dioxide during cellular respiration, but they also remove carbon dioxide from the atmosphere during photosynthesis.");
			
				p.addAnswer(3, "During a bloom, diatom populations increase rapidly, providing many more photosynthetic organisms to the plankton population.",
				false,
				"No. Although the increase in photosynthesizers will remove more carbon dioxide from the atmosphere, predator populations are likely to increase as well. When the predators eat the diatoms, they return around 90% of the carbon to the atmosphere as carbon dioxide.");
			
				p.addAnswer(4, "During a bloom, diatom populations may increase rapidly. If many diatoms die and sink to the bottom without being eaten, they effectively pump carbon dioxide out of the atmosphere.",
				true,
				"Correct. During photosynthesis the carbon from atmospheric carbon dioxide is incorporated into diatom bodies. If the diatoms are eaten, most of that carbon is returned to the atmosphere as carbon dioxide by the organism that eats them. If the diatoms sink to the bottom of the ocean, that carbon is effectively removed from the atmosphere for a longer period of time.");
			
				p.addAnswer(5, "Diatomaceous earth can be used to filter carbon dioxide from the atmosphere.",
				false,
				"No. Diatomaceous earth is an effective filter, but not of carbon dioxide.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335719;


		
		

		
			
			p.question = "On some areas of the seafloor, one could observe an \"ooze\" that is hundreds of meters thick. What creates this ooze? (<script type=\"text/javascript\">ebook(\'2804\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the tests of dead radiolarians",
				true,
				"Correct. After radiolarians die, their tests settle to the seafloor, where they have accumulated as an ooze that is hundreds of meters thick in some locations.");
			
				p.addAnswer(2, "the tests of dead diatoms",
				false,
				"No. Diatoms do not have tests.");
			
				p.addAnswer(3, "the decaying porous shells of forams",
				false,
				"No. The fossilized tests of forams do make up a large part of marine sediment, but they do not accumulate in an ooze.");
			
				p.addAnswer(4, "the gel-forming polysaccharides secreted by brown and red algae",
				false,
				"No. The tests of radiolarians make up this ooze.");
			
				p.addAnswer(5, "colonies of plasmodial slime molds",
				false,
				"No. Although plasmodial slime molds do form colonies, they would not be found on the seafloor.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335720;


		
		

		
			
			p.question = "Many species of red algae are adapted to deeper water due to the fact that _____. (<script type=\"text/javascript\">ebook(\'2805\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "their red pigments readily absorb red light",
				false,
				"No. Red pigments reflect red light.");
			
				p.addAnswer(2, "their cell walls are adapted to withstand bright light",
				false,
				"No. The deeper the water, the less the light.");
			
				p.addAnswer(3, "their photosynthetic pigments efficiently absorb blue and green light",
				true,
				"Correct. Red algae are most abundant in the warm coastal waters of tropical oceans. The accessory pigments they contain enable them to absorb filtered wavelengths (blues and greens) in deep water.");
			
				p.addAnswer(4, "they grow long stalks with floats on the ends to hold the blades near the surface",
				false,
				"No. The answer has to do with the type of light they can absorb.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. Only one of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335721;


		
		

		
			
			p.question = "The red algae are characterized by _____. (<script type=\"text/javascript\">ebook(\'2805\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "especially diverse life cycles",
				true,
				"Correct. Alternation of generations occurs in some species of red algae.");
			
				p.addAnswer(2, "flagellated gametes that do not require water for fertilization to occur",
				false,
				"No. Their gametes lack flagella and therefore require water currents to bring them together for fertilization.");
			
				p.addAnswer(3, "population explosions known as \"red tides\"",
				false,
				"No. Dinoflagellates cause red tides.");
			
				p.addAnswer(4, "multinucleated portions",
				false,
				"No. Red algae do not exhibit the multinucleated portions seen in some of the fungi.");
			
				p.addAnswer(5, "a red coloration in all its species",
				false,
				"No. Not all its species are red. The color of the organism depends on what depth it inhabits.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335722;


		
		

		
			
			p.question = "Which of the following groups of algae is (are) most closely related to land plants? (<script type=\"text/javascript\">ebook(\'2805\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "brown algae",
				false,
				"No. There are similarities between brown algae and land plants, but the similarities evolved independently (they are analogous).");
			
				p.addAnswer(2, "green algae",
				true,
				"Correct. Strong evidence supports the hypothesis that green algae, especially those known as charophyceans, and land plants are derived from a common ancestor.");
			
				p.addAnswer(3, "red algae",
				false,
				"No. Plants are not as closely related to red algae as they are to another type of algae.");
			
				p.addAnswer(4, "blue-green algae",
				false,
				"No. This is an obsolete term. The organisms formerly called \"blue-green algae\" are now known as the cyanobacteria, and they are much more distantly related to land plants than is a particular group of algae.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335723;


		
		

		
			
			p.question = "In lab class, a plasmodial slime mold is used as a demonstration organism. One of the students does not understand why this organism is not considered multicellular. How would you explain it to her? (<script type=\"text/javascript\">ebook(\'2806\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The plasmodium is undivided by membranes and contains many diploid nuclei; therefore, it is not technically multicellular.",
				true,
				"Correct. The plasmodium may be several centimeters in diameter, but it is made by a unicellular organism.");
			
				p.addAnswer(2, "The distinct cells that make up the plasmodium do not cooperate, so they do not represent a truly multicellular organism.",
				false,
				"No. Consider the characteristics of the membrane and nuclei to figure out the answer.");
			
				p.addAnswer(3, "Plasmodial slime molds are not able to reproduce sexually, so therefore they are not truly multicellular.",
				false,
				"No. Consider the characteristics of the membrane and nuclei to figure out the answer.");
			
				p.addAnswer(4, "Multicellular organisms are seen only in the kingdoms Animalia and Plantae.",
				false,
				"No. Fungi can be multicellular.");
			
				p.addAnswer(5, "The nuclei found in the plasmodium of a plasmodial slime mold are diploid.",
				false,
				"No. The ploidy of a nucleus does not, by itself, provide a sufficient basis for distinguishing between unicellular and multicellular organisms.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335724;


		
		

		
			
			p.question = "To which supergroup do amoebas belong? (<script type=\"text/javascript\">ebook(\'2806\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Unikonta",
				false,
				"No. Ameobas are not confined to any particular group.");
			
				p.addAnswer(2, "Rhizaria",
				false,
				"No. Ameobas are not confined to any particular group.");
			
				p.addAnswer(3, "Chromalveolates",
				false,
				"No. Ameobas are not confined to any particular group.");
			
				p.addAnswer(4, "Apicomplexans",
				false,
				"No. Ameobas are not confined to any particular group.");
			
				p.addAnswer(5, "none of the above",
				true,
				"Correct. Organisms that move by pseudopodia are found in more than one supergroup. They are not monophyletic.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335725;


		
		

		
			
			p.question = "It is estimated that protists perform up to what percentage of the world\'s photosynthesis? (<script type=\"text/javascript\">ebook(\'2807\',\'quiz\')</script>)";
			p.incorrect_any_expl = "No. Protists perform around 25% of photosynthesis.";
			p.incorrect_any_expl_flag = 1;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "50%",
				false,
				"");
			
				p.addAnswer(2, "10%",
				false,
				"");
			
				p.addAnswer(3, "40%",
				false,
				"");
			
				p.addAnswer(4, "25%",
				true,
				"Correct. Protists perform about 25% of the world\'s photosynthesis according to estimates.");
			
				p.addAnswer(5, "5%",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335726;


		
		

		
			
			p.question = "<i>Trichonympha agilis</i> is an important endosymbiont that lives in the guts of ________. (<script type=\"text/javascript\">ebook(\'2807\',\'quiz\')</script>)";
			p.incorrect_any_expl = "No. <i>Trichonympha agilis</i> lives in the guts of termites and makes it possible for them to digest wood.";
			p.incorrect_any_expl_flag = 1;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "cattle",
				false,
				"");
			
				p.addAnswer(2, "humans",
				false,
				"");
			
				p.addAnswer(3, "termites",
				true,
				"Correct. Without this endosymbiont, termites would be unable to digest wood, and the breakdown of trees would be greatly slowed.");
			
				p.addAnswer(4, "rabbits",
				false,
				"");
			
				p.addAnswer(5, "ants",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

