

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "24: The Origin of Species > Practice Test";
	ak.quiz_loc_with_commas = "24: The Origin of Species, Practice Test";
	ak.quiz_title = "Practice Test";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 30;
	ak.non_essay_total = 30;
	ak.scored_item_total = 30;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335497;


		
		

		
			
			p.question = "When gene flow between two populations ceases, the potential for _____ exists. (<script type=\"text/javascript\">ebook(\'2401\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "speciation",
				true,
				"Correct. Reproductive isolation (the cessation of gene flow) is necessary for speciation.");
			
				p.addAnswer(2, "hybridization",
				false,
				"No. Hybridization would mark the beginning of gene flow between two formerly isolated populations.");
			
				p.addAnswer(3, "sexual reproduction",
				false,
				"No. Sexual reproduction is one reproductive strategy. The cessation of gene flow might indicate a barrier of some kind to sexual reproduction.");
			
				p.addAnswer(4, "sexual selection",
				false,
				"No. Sexual selection can occur only among members of a population where gene flow is occurring.");
			
				p.addAnswer(5, "fusion",
				false,
				"No. Fusion refers to two or more populations re-establishing gene flow and forming one species.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335498;


		
		

		
			
			p.question = "Bird guides once listed the myrtle warbler and Audubon\'s warbler as distinct species that lived side by side in parts of their ranges. However, recent books show them as eastern and western forms of a single species, the yellow-rumped warbler. Apparently, the myrtle warbler and Audubon\'s warbler _____. (<script type=\"text/javascript\">ebook(\'2401\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "live in the same areas",
				false,
				"No. Living in the same area does not make them the same species.");
			
				p.addAnswer(2, "successfully interbreed and produce fertile offspring",
				true,
				"Correct. That is the definition of biological species.");
			
				p.addAnswer(3, "are almost identical in appearance",
				false,
				"No. Although very similar, they are different enough in appearance that they were once classified as two species.");
			
				p.addAnswer(4, "are merging to form a single species",
				false,
				"No. There is no evidence pointing to that possibility.");
			
				p.addAnswer(5, "have undergone coevolution",
				false,
				"No. They should never have been considered two species because they can interbreed and produce fertile offspring.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335499;


		
		

		
			
			p.question = "Imagine that part of a population of South American finches is blown by a storm onto an island far offshore and manages to survive and reproduce there for a period of 10,000 years. After that period, a climate change results in lower sea levels and the reconnection of the island with the mainland. Members of the formerly isolated island finch population can now interact freely with members of the original mainland population. Which of the following observations would, by itself, lead you to conclude unequivocally that the island finch population had evolved into a distinct species? (<script type=\"text/javascript\">ebook(\'2401\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The island birds all have red feathers, but the mainland birds have green feathers.",
				false,
				"No. Populations with different appearances are not necessarily different species.");
			
				p.addAnswer(2, "Individuals from the different populations sometimes mate with each other, but all of the resulting eggs are sterile.",
				true,
				"Correct. The biological species concept defines a species as a population whose members interbreed successfully to produce viable, fertile offspring but who cannot produce viable, fertile offspring with members of other species.");
			
				p.addAnswer(3, "The preferred food of the island birds is quite different from the diet of mainland birds.",
				false,
				"No. This difference does not necessarily make the birds different species.");
			
				p.addAnswer(4, "Individuals from the different populations frequently direct courtship behavior toward members of the other population.",
				false,
				"No. This suggests that speciation did not occur.");
			
				p.addAnswer(5, "Hybrid offspring of matings between individuals from the two populations do not look like either parent.",
				false,
				"No. This is not evidence of speciation.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335500;


		
		

		
			
			p.question = "Which one of the following conditions is necessary for speciation to occur? (<script type=\"text/javascript\">ebook(\'2401\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "reproductive isolation",
				true,
				"Correct. The biological species concept hinges on reproductive isolation.");
			
				p.addAnswer(2, "sympatric speciation",
				false,
				"No. This is a specific type of reproductive isolation, not a condition that leads to it.");
			
				p.addAnswer(3, "adaptive radiation",
				false,
				"No. This is a pattern of speciation.");
			
				p.addAnswer(4, "mass extinction",
				false,
				"No. However, rapid speciation often follows mass extinctions.");
			
				p.addAnswer(5, "interbreeding among neighboring populations",
				false,
				"No. This would inhibit speciation.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335501;


		
		

		
			
			p.question = "At which point in the adaptation of a population is it clear that speciation has occurred? (<script type=\"text/javascript\">ebook(\'2401\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Gene pool changes adapt a population to a local environment.",
				false,
				"No. This may or may not lead to speciation.");
			
				p.addAnswer(2, "Gene pool changes establish reproductive barriers between two populations.",
				true,
				"Correct. This is an example of separate species being created.");
			
				p.addAnswer(3, "An allopatric separation occurs.",
				false,
				"No. This may lead to speciation, but it may not have occurred yet.");
			
				p.addAnswer(4, "Viable, fertile hybrids occur.",
				false,
				"No. This is would be expected to prevent speciation from occurring.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. Only one of the answers represents the clear formation of separate species.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335502;


		
		

		
			
			p.question = "Prezygotic barriers _____. (<script type=\"text/javascript\">ebook(\'2401\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "prevent fertilization of gametes from members of closely related species",
				true,
				"Correct. These barriers hinder the fertilization of ova if members of sibling species attempt to mate.");
			
				p.addAnswer(2, "prevent a hybrid zygote from developing into a viable, fertile adult",
				false,
				"No. This would be an action of a postzygotic barrier.");
			
				p.addAnswer(3, "prevent fertilization from occurring between members of the same species with incompatible genes",
				false,
				"No. The term \"incompatible genes\" is scientifically ambiguous.");
			
				p.addAnswer(4, "prevent donkeys and horses from mating",
				false,
				"No. Donkeys and horses are capable of mating, but their offspring (mules and hinnies) are almost always sterile.");
			
				p.addAnswer(5, "only occur in asexual organisms",
				false,
				"No. They only occur in sexual organisms.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335503;


		
		

		
			
			p.question = "Three species of frogs, <i>Rana pipiens</i>, <i>Rana clamitans</i>, and <i>Rana sylvatica</i>, all mate in the same ponds, but they pair off correctly because they have different calls. This is a specific example of a _____ barrier, called _____. (<script type=\"text/javascript\">ebook(\'2401\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "prezygotic barrier; behavioral isolation",
				true,
				"Correct. It occurs before mating and is due to different behaviors.");
			
				p.addAnswer(2, "postzygotic; hybrid breakdown",
				false,
				"No. A zygote is not formed because fertilization does not even occur.");
			
				p.addAnswer(3, "prezygotic; temporal isolation",
				false,
				"No. It is a prezygotic barrier, but the frogs may mate at the same time.");
			
				p.addAnswer(4, "postzygotic; mechanical isolation",
				false,
				"No. There is no evidence of morphological differences in this scenario.");
			
				p.addAnswer(5, "prezygotic; gametic isolation",
				false,
				"No. Mating does not occur.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335504;


		
		

		
			
			p.question = "Which of the following reproductive barriers actually prevents individuals of closely related species from copulating successfully? (<script type=\"text/javascript\">ebook(\'2401\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "hybrid inviability",
				false,
				"No. Mating occurs, but the resulting hybrid is feeble.");
			
				p.addAnswer(2, "hybrid sterility",
				false,
				"No. Mating occurs, but the resulting hybrid is sterile.");
			
				p.addAnswer(3, "gametic isolation",
				false,
				"No. Mating occurs, but the gametes are not compatible.");
			
				p.addAnswer(4, "hybrid breakdown",
				false,
				"No. Mating occurs, but the second-generation hybrid is not viable.");
			
				p.addAnswer(5, "mechanical isolation",
				true,
				"Correct. Mating cannot occur successfully due to incompatibility of reproductive parts.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335505;


		
		

		
			
			p.question = "Two species of water lilies in the same pond do not interbreed because one blooms at night and the other during the day. The reproductive barrier between them is an example of _____. (<script type=\"text/javascript\">ebook(\'2401\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "temporal isolation",
				true,
				"Correct. The gametes of species that breed during different times of the day, different seasons, or different years do not mix.");
			
				p.addAnswer(2, "gametic isolation",
				false,
				"No. That refers to incompatible gametes.");
			
				p.addAnswer(3, "mechanical isolation",
				false,
				"No. This is an anatomical incompatibility that prevents mating.");
			
				p.addAnswer(4, "hybrid breakdown",
				false,
				"No. Mating occurs in hybrid breakdown, but the second-generation hybrid is not viable.");
			
				p.addAnswer(5, "ecological isolation",
				false,
				"No. In ecological isolation, organisms live in different parts of the same area (for example, in trees versus on the ground).");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335506;


		
		

		
			
			p.question = "Which of the following is an example of a postzygotic reproductive barrier? (<script type=\"text/javascript\">ebook(\'2401\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "One species of frog mates in April, but another mates in May.",
				false,
				"No. Because mating does not take place, this is a prezygotic barrier.");
			
				p.addAnswer(2, "Two fruit flies of different species produce sterile offspring.",
				true,
				"Correct. This is reduced hybrid fertility.");
			
				p.addAnswer(3, "The sperm of a marine worm can only penetrate eggs of the same species.",
				false,
				"No. This is gametic incompatibility.");
			
				p.addAnswer(4, "One species of flower grows in forested areas, another in meadows.",
				false,
				"No. This is a prezygotic barrier; no mating takes place.");
			
				p.addAnswer(5, "Two pheasant species perform different courtship dances.",
				false,
				"No. Behavioral isolation is a prezygotic barrier.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335507;


		
		

		
			
			p.question = "There are two groups of pine trees that appear to be very similar phenotypically and genotypically. However, one releases pollen in January, when the female structures of that group are receptive, and one in March. What kind of reproductive barrier is this? (<script type=\"text/javascript\">ebook(\'2401\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "temporal isolation",
				true,
				"Correct. Temporal isolation occurs when two similar species have sexual readiness at different times.");
			
				p.addAnswer(2, "gametic isolation",
				false,
				"No. This is isolation due to the inability of gametes to unite.");
			
				p.addAnswer(3, "mechanical isolation",
				false,
				"No. This is due to structural differences preventing mating or pollen transfer.");
			
				p.addAnswer(4, "hybrid inviability",
				false,
				"No. In this case, hybrid zygotes fail to develop.");
			
				p.addAnswer(5, "a geographic barrier",
				false,
				"No. A geographic barrier is a physical barrier preventing interbreeding.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335508;


		
		

		
			
			p.question = "The biological species concept emphasizes _____. (<script type=\"text/javascript\">ebook(\'2401\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "molecular differences",
				false,
				"No. Molecular differences are used more to differentiate species based on phylogeny.");
			
				p.addAnswer(2, "ecological niches",
				false,
				"No. The ecological species concept emphasizes ecological niches.");
			
				p.addAnswer(3, "the evolution of reproductive isolation",
				true,
				"Correct. The biological species concept defines a species as a population or group of populations whose members have the potential to interbreed with each other in nature and produce viable, fertile offspring. When barriers evolve that prevent the production of viable offspring, two populations are defined as different species.");
			
				p.addAnswer(4, "morphological and structural features",
				false,
				"No. The biological species concept emphasizes reproductive isolation.");
			
				p.addAnswer(5, "common ancestry",
				false,
				"No. The phylogenetic species concept emphasizes common ancestry.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335509;


		
		

		
			
			p.question = "Lake Victoria, in Africa, is home to a group of related fishes known as cichlids. Many of these fishes are similar in appearance but have different feeding habits. What is the best method for scientists to determine conclusively whether the fish are members of a population that has a lot of variation or members of entirely different species? (<script type=\"text/javascript\">ebook(\'2401\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Observe the fish in their natural environment for possible instances of interbreeding leading to several generations of fertile offspring.",
				true,
				"Correct. The biological species concept defines a species as a population whose members interbreed successfully to produce viable, fertile offspring but who cannot produce viable, fertile offspring with members of other species.");
			
				p.addAnswer(2, "Study the fossil record.",
				false,
				"No. There is an easier way to arrive at a conclusion.");
			
				p.addAnswer(3, "Compare DNA sequences, because the DNA of members of the same species should be identical.",
				false,
				"No. There is an easier way to arrive at a conclusion.");
			
				p.addAnswer(4, "Do studies on comparative anatomy, especially looking for homologous structures.",
				false,
				"No. There is an easier way to arrive at a conclusion.");
			
				p.addAnswer(5, "All of these must be done to determine whether a single population or different species are present.",
				false,
				"No. One of the other choices will suffice.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335510;


		
		

		
			
			p.question = "In practice, how do scientists distinguish most species? (<script type=\"text/javascript\">ebook(\'2401\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "by using the morphological species concept",
				true,
				"Correct. This concept is used to characterize a species in terms of body shape, size, and other distinct structural features.");
			
				p.addAnswer(2, "by using the paleontological species concept",
				false,
				"No. This refers to morphologically discrete species that are known only from the fossil record.");
			
				p.addAnswer(3, "by using the ecological species concept",
				false,
				"No. This concept views a species in terms of its ecological niche, its role in a biological community.");
			
				p.addAnswer(4, "by using the phylogenetic species concept",
				false,
				"No. This concept defines a species as a set of organisms with a unique genetic history.");
			
				p.addAnswer(5, "by using the biological species concept",
				false,
				"No. This is the classical definition that defines a species as a population or group of populations whose members have the potential to interbreed with one another in nature and to produce viable, fertile offspring, but cannot produce viable, fertile offspring with members of other populations.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335511;


		
		

		
			
			p.question = "Which species concept defines a species as a set of organisms with a unique genetic history? (<script type=\"text/javascript\">ebook(\'2401\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "morphological species concept",
				false,
				"No. This concept is used to characterize a species in terms of body shape, size, and other distinct structural features.");
			
				p.addAnswer(2, "paleontological species concept",
				false,
				"No. This refers to morphologically discrete species that are known only from the fossil record.");
			
				p.addAnswer(3, "ecological species concept",
				false,
				"No. This concept views a species in terms of its ecological niche, its role in a biological community.");
			
				p.addAnswer(4, "phylogenetic species concept",
				true,
				"Correct. Biologists compare an organism\'s physical characteristics or molecular sequences to the corresponding data for other species. This analysis can distinguish groups of individuals that are sufficiently different to be considered separate species.");
			
				p.addAnswer(5, "biological species concept",
				false,
				"No. This is the classical definition that defines a species as a population or group of populations whose members have the potential to interbreed with one another in nature and to produce viable, fertile offspring, but cannot produce viable, fertile offspring with members of other populations.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335512;


		
		

		
			
			p.question = "Sometimes two phenotypically different populations interbreed to a limited extent, so that it is difficult to determine whether they are clearly separate species. This is not a concern to scientists because this _____. (<script type=\"text/javascript\">ebook(\'2401\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "is quite rare",
				false,
				"No. In fact, it is not rare.");
			
				p.addAnswer(2, "is true for almost every species",
				false,
				"No. A specific process is occurring in the example above.");
			
				p.addAnswer(3, "supports the theory of punctuated equilibrium",
				false,
				"No. This question refers to the budding of a new species from a parent species.");
			
				p.addAnswer(4, "may indicate that the formation of a new species is in progress",
				true,
				"Correct. This could indicate that although a reproductive barrier is becoming established, it is not yet complete.");
			
				p.addAnswer(5, "happens only among plants, not among animals",
				false,
				"No. It can occur in both plants and animals.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335513;


		
		

		
			
			p.question = "Which of the following organisms are most likely to be subject to allopatric speciation? (<script type=\"text/javascript\">ebook(\'2402\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "whale populations of the same species located on opposite sides of the Atlantic Ocean",
				false,
				"No. Genetic mixing may occur between the two due to the mobility of whales through the ocean.");
			
				p.addAnswer(2, "pine trees in Alaska and pine trees on the island of Madagascar",
				true,
				"Correct. This is geographic isolation that could lead to allopatric speciation, for it is unlikely that pollen from one locale could get to the other locale.");
			
				p.addAnswer(3, "mountain lions in the canyons of Wyoming and in the canyons of Utah",
				false,
				"No. These represent one population because mountain lions recognize neither political barriers nor most topographical barriers.");
			
				p.addAnswer(4, "fruit flies on bananas and fruit flies on oranges",
				false,
				"No. This certainly does not represent a strong geographic barrier.");
			
				p.addAnswer(5, "bacteria in a hospital and bacteria in a nursery",
				false,
				"No. Although the bacteria don\'t travel, the people who carry them do.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335514;


		
		

		
			
			p.question = "According to the experiment of Diane Dodd, can adaptive divergence of allopatric fruit fly populations lead to reproductive isolation? (<script type=\"text/javascript\">ebook(\'2402\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "After several generations, the reproductive barrier (behavioral isolation) between the starch- and maltose-fed populations was complete.",
				false,
				"No. Some mating between the starch flies and maltose flies did occur.");
			
				p.addAnswer(2, "After several generations, the formation of a reproductive barrier (behavioral isolation) was evident, but not absolute.",
				true,
				"Correct. The starch flies were more apt to mate with other starch flies and the maltose flies were more apt to mate with other maltose flies, but some interbreeding still did occur.");
			
				p.addAnswer(3, "After several generations, the reproductive barrier (mechanical isolation) between the starch- and maltose-fed populations was complete.",
				false,
				"No. Some mating between the starch flies and maltose flies did occur. Also, this experiment was an example of behavioral isolation.<b> </b>");
			
				p.addAnswer(4, "After several generations, the formation of a reproductive barrier (mechanical isolation) was evident, but not absolute.",
				false,
				"No. This experiment was an example of behavioral isolation.");
			
				p.addAnswer(5, "Even after several generations, there was no evidence of a reproductive barrier forming between the populations.",
				false,
				"No. The starch flies were more apt to mate with other starch flies and the maltose flies were more apt to mate with other maltose flies, although some interbreeding still did occur.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335515;


		
		

		
			
			p.question = "In which of the following groups has sympatric speciation been most important? (<script type=\"text/javascript\">ebook(\'2402\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "animals",
				false,
				"No. Sympatric speciation does not seem to have been an important factor in animal speciation.");
			
				p.addAnswer(2, "plants",
				true,
				"Correct. Sympatric speciation has been very important in plant evolution, especially through polyploidy.");
			
				p.addAnswer(3, "bacteria",
				false,
				"No. Sympatric speciation has played a more important role in the speciation of plants.");
			
				p.addAnswer(4, "fungi",
				false,
				"No. Fungi are not nearly as influenced by sympatric speciation as are plants.");
			
				p.addAnswer(5, "protozoa",
				false,
				"No. Protozoan motility precludes much development by sympatric speciation.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335516;


		
		

		
			
			p.question = "If a new species of plant is to be produced by means of allopolyploidy from two parental species that are 2<i>n</i> = 4 and 2<i>n</i> = 8, how many chromosomes would you expect in the somatic cells of the new species? (<script type=\"text/javascript\">ebook(\'2402\',\'quiz\')</script>)";
			p.incorrect_any_expl = "No. The two gametes would be <i>n</i> = 2 and <i>n = </i>4. They would combine for a total of 6, which after doubling would be 12.";
			p.incorrect_any_expl_flag = 1;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "6",
				false,
				"");
			
				p.addAnswer(2, "12",
				true,
				"Correct. The two gametes would be <i>n</i> = 2 and <i>n</i> = 4. They would combine for a total of 6, which after doubling would be 12.");
			
				p.addAnswer(3, "24",
				false,
				"");
			
				p.addAnswer(4, "48",
				false,
				"");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335517;


		
		

		
			
			p.question = "A new species can arise in a single generation _____. (<script type=\"text/javascript\">ebook(\'2402\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "through geographic isolation",
				false,
				"No. It usually takes many generations for speciation to occur by geographic isolation.");
			
				p.addAnswer(2, "in a very large population spread over a large area",
				false,
				"No. It normally takes many generations for sexually reproducing organisms to speciate.");
			
				p.addAnswer(3, "if a change in chromosome number creates a reproductive barrier",
				true,
				"Correct. This most often happens in plants.");
			
				p.addAnswer(4, "if allopatric speciation occurs",
				false,
				"No. Allopatric speciation occurs by geographic isolation, and it takes several generations for speciation to occur in this manner.");
			
				p.addAnswer(5, "if adaptive radiation occurs",
				false,
				"No. This most likely will not lead to new species arising in a single generation.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335518;


		
		

		
			
			p.question = "The Gal&#225;pagos finches collected by Darwin are thought to have descended from a very small parent population. Different species of finches that are confined to only one or two islands most likely arose by _____. (<script type=\"text/javascript\">ebook(\'2402\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "sympatric speciation",
				false,
				"No. If they are geographically isolated from each other, it is unlikely that they arose by sympatric speciation.");
			
				p.addAnswer(2, "gene flow",
				false,
				"No. Gene flow would be more likely to prevent speciation.");
			
				p.addAnswer(3, "allopatric speciation",
				true,
				"Correct. As the finches spread out to different islands and became isolated from each other, gene flow between them ceased, and new species arose.");
			
				p.addAnswer(4, "polyploidy",
				false,
				"No. Polyploidy among animals is extremely rare. Also, molecular studies done on the Gal&#225;pagos finches have not indicated that polyploidy was a factor in their speciation.");
			
				p.addAnswer(5, "hybridization",
				false,
				"No. Hybridization tends to increase gene flow between previously isolated populations.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335519;


		
		

		
			
			p.question = "In the case of the Lake Victoria cichlids, sympatric speciation has been shown to be driven by ______. (<script type=\"text/javascript\">ebook(\'2402\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "polyploidy",
				false,
				"No. Polyploidy is extremely rare in animals, and no studies to date have detected polyploidy in cichlids.");
			
				p.addAnswer(2, "habitat differentiation",
				false,
				"No. Although habitat differentiation has been suggested as a possible mechanism for sympatric speciation in the lake, sexual selection has been shown to be a factor.");
			
				p.addAnswer(3, "mechanical isolation",
				false,
				"No. There is no evidence to suggest that males are not physically capable of fertilizing the eggs of females of different species.");
			
				p.addAnswer(4, "sexual selection",
				true,
				"Correct. Experiments have shown that females select mates on the basis of coloration. This behavioral isolation may have been a major factor in the speciation of cichlids.");
			
				p.addAnswer(5, "post-zygotic barriers",
				false,
				"No. Sexual selection, which is technically a pre-zygotic barrier, has been shown to be a factor in the speciation events in Lake Victoria cichlids.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335520;


		
		

		
			
			p.question = "In a hybrid zone which of the following would tend to lead to reinforcement? (<script type=\"text/javascript\">ebook(\'2403\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "reduced hybrid viability",
				false,
				"No. Reduced hybrid viability would tend to strengthen reproductive barriers, but there is a better answer.");
			
				p.addAnswer(2, "hybrid breakdown",
				false,
				"No. Hybrid breakdown would tend to strengthen reproductive barriers, but there is a better answer.");
			
				p.addAnswer(3, "reduced hybrid fertility",
				false,
				"No. Reduced hybrid fertility would tend to strengthen reproductive barriers, but there is a better answer.");
			
				p.addAnswer(4, "sexual selection",
				false,
				"No. Sexual selection has been shown to strengthen reproductive barriers in some cases, but there is a better answer.");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct. All of these factors can reinforce the reproductive barriers between populations.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335521;


		
		

		
			
			p.question = "In the Lake Victoria cichlids, what appears to be contributing to fusion of different species? (<script type=\"text/javascript\">ebook(\'2403\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Murky, polluted water is causing reduced hybrid viability.",
				false,
				"No. Reduced hybrid viability would contribute to reinforcement of reproductive barriers rather than fusion of species.");
			
				p.addAnswer(2, "overfishing",
				false,
				"No. There is no evidence that overfishing is contributing to fusion of species.");
			
				p.addAnswer(3, "Murky, polluted water is making it difficult for females to visually select for males of the same species.",
				true,
				"Correct. Researchers are finding that sexual selection, which had been reinforcing reproductive barriers between species, is less effective in the murky water of the present-day lake.");
			
				p.addAnswer(4, "Extinctions are being caused by the Nile perch, an introduced predator.",
				false,
				"No. Although the introduction of the Nile perch has led to the extinction of some cichlid species, it does not appear to be contributing to the observed fusion.");
			
				p.addAnswer(5, "Murky, polluted water is reducing the viability of cichlid eggs.",
				false,
				"No. Unless the pollution was directly selecting for or against hybrid eggs, such a situation would have no bearing on fusion of species in the lake.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335522;


		
		

		
			
			p.question = "According to the punctuated equilibrium model of evolution _____. (<script type=\"text/javascript\">ebook(\'2404\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the tempo of evolution consists of abrupt episodes of speciation among long periods of equilibrium",
				true,
				"Correct. This is the exact description of the punctuated equilibrium model of evolution.");
			
				p.addAnswer(2, "isolated species changing over a few thousand generations represent graduated equilibrium, not punctuated equilibrium",
				false,
				"No. A few thousand generations is a very short period in geological time, so this could appear as a punctuated equilibrium.");
			
				p.addAnswer(3, "polyploidy is not a mechanism of punctuated equilibrium",
				false,
				"No. Polyploidy represents one of the main mechanisms of punctuated equilibrium, especially in plants.");
			
				p.addAnswer(4, "Fossils of organisms that existed during periods of stasis should be as abundant as those of organisms that existed during periods of rapid change.",
				false,
				"No. In the model of punctuated equilibrium, periods of stasis are much more common than are periods of rapid change.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335523;


		
		

		
			
			p.question = "Comparison of human fossils with living humans seems to show that there have been no significant physical changes in <i>Homo sapiens</i> in 30,000 to 50,000 years. What might an advocate of punctuated equilibrium say about this? (<script type=\"text/javascript\">ebook(\'2404\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "It is about time for humans to undergo a burst of change.",
				false,
				"No. In punctuated equilibrium, new species change little after budding from their parent species.");
			
				p.addAnswer(2, "That is about how long we have been reproductively isolated.",
				false,
				"No. That is not addressed by punctuated equilibrium.");
			
				p.addAnswer(3, "It is impossible to see major internal changes by looking at fossils.",
				false,
				"No. That has nothing to do with the punctuated equilibrium theory.");
			
				p.addAnswer(4, "You would expect lots of changes in the skeleton in that time period.",
				false,
				"No. There would be few changes, according to proponents of punctuated equilibrium.");
			
				p.addAnswer(5, "Lack of change is consistent with the punctuated equilibrium model.",
				true,
				"Correct. In punctuated equilibrium, new species change little after budding from their parent species.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335524;


		
		

		
			
			p.question = "What is the first thing that must happen in order for speciation to occur? (<script type=\"text/javascript\">ebook(\'2404\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Gene flow between populations must be interrupted.",
				true,
				"Correct. Although several other factors come into play, as long as there is gene flow between populations, speciation is extremely unlikely.");
			
				p.addAnswer(2, "A catastrophic event must cause geographic separation of two populations.",
				false,
				"No. Geographic separation is not always necessary for speciation (remember sympatric speciation), and it may be gradual, not catastrophic.");
			
				p.addAnswer(3, "A hybrid zone must be established.",
				false,
				"No. A hybrid zone could not be established until gene flow had already been interrupted for some length of time. In addition, a hybrid zone might tend to slow or stop speciation.");
			
				p.addAnswer(4, "The populations must become reproductively isolated.",
				false,
				"No. Although reproductive isolation is necessary for speciation according to the biological species model, reproductive isolation is unlikely to occur until gene flow is interrupted and the populations have diverged genetically to some extent.");
			
				p.addAnswer(5, "One of the populations must become polyploid.",
				false,
				"No. While polyploidy can stop gene flow almost instantaneously, it is not very common, nor is it necessary for speciation to occur.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335525;


		
		

		
			
			p.question = "How many genes must change in order to form a new species? (<script type=\"text/javascript\">ebook(\'2404\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "1",
				false,
				"No. A single gene has been shown to cause a mechanical barrier to reproduction, but there is a better answer.");
			
				p.addAnswer(2, "26",
				false,
				"No. At least 26 chromosomal segments have been implicated in the speciation of certain sunflowers, but there is a better answer.");
			
				p.addAnswer(3, "4",
				false,
				"No. At least 4 gene loci are involved in a fruit fly speciation event, but there is a better answer.");
			
				p.addAnswer(4, "14",
				false,
				"No. Undoubtedly a speciation event has occurred based on changes in 14 genes, but there is a better answer.");
			
				p.addAnswer(5, "There is no set number of genes or loci that produces a new species. Genetic and environmental factors interact.",
				true,
				"Correct. Research has shown that genetic changes can be few or many. Other factors such as geographic isolation, catastrophic events, pollution, the establishment of hybrid zones, and so on, will affect speciation in different organisms.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335526;


		
		

		
			
			p.question = "The time interval between speciation events is typically _____ (<script type=\"text/javascript\">ebook(\'2404\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "6.5 million years",
				false,
				"No. A compilation of speciation times has given an average of 6.5 million years, but the range of times is huge. 6.5 million years cannot be labeled \"typical.\"");
			
				p.addAnswer(2, "4,000 years",
				false,
				"No. 4,000 years is a very short time for speciation, particularly among animals.");
			
				p.addAnswer(3, "40 million years",
				false,
				"No. Some speciation events have been shown to have taken approximately 40 million years, but there is no evidence that this is typical.");
			
				p.addAnswer(4, "500,000 years",
				false,
				"No. Some speciation events have been shown to have taken approximately 500,000 years, but there is no evidence that this is typical.");
			
				p.addAnswer(5, "Times between speciation events vary widely and depend on generation times, causes of speciation, environmental factors, and chance.",
				true,
				"Correct. Speciation may occur on many different time scales. Remember that mutations or meiosis, both of which are largely governed by chance, must first provide some traits that can lead to reproductive isolation.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

