

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "48: Nerves, Synapses, and Signaling > Practice Test";
	ak.quiz_loc_with_commas = "48: Nerves, Synapses, and Signaling, Practice Test";
	ak.quiz_title = "Practice Test";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 30;
	ak.non_essay_total = 30;
	ak.scored_item_total = 30;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336776;


		
		

		
			
			p.question = "Neurons communicate by _____. (<script type=\"text/javascript\">ebook(\'48OV\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "short-distance electrical signals",
				false,
				"No.<b> </b>Neurons communicate by short-distance chemical signals and long-distance electrical signals.");
			
				p.addAnswer(2, "long-distance chemical signals",
				false,
				"No. Neurons communicate by short-distance chemical signals and long-distance electrical signals.");
			
				p.addAnswer(3, "short-distance electrical signals and long-distance chemical signals",
				false,
				"No. Neurons communicate by short-distance chemical signals and long-distance electrical signals.");
			
				p.addAnswer(4, "short-distance chemical signals and long-distance electrical signals",
				true,
				"Correct.  These are the two types of signals that neurons use to communicate.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336777;


		
		

		
			
			p.question = "A cluster of nerve cell bodies is called a(n) _____. (<script type=\"text/javascript\">ebook(\'48OV\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "cranial nerve",
				false,
				"No. A cranial nerve consists of bundles of axons.");
			
				p.addAnswer(2, "nucleus",
				false,
				"No. With regard to the structure of the nervous system, a nucleus is an aggregation of nerve cell bodies within the central nervous system.");
			
				p.addAnswer(3, "association area",
				false,
				"No. Association areas consist of many interconnected neurons.");
			
				p.addAnswer(4, "ganglion",
				true,
				"Correct. A ganglion is a cluster of nerve cell bodies that carries out higher-order processing.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336778;


		
		

		
			
			p.question = "A neuron that transmits an impulse to the central nervous system after the neuron is stimulated by the environment is called a(n) _____. (<script type=\"text/javascript\">ebook(\'4801\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "sensory neuron",
				true,
				"Correct. Sensory neurons communicate information between sensory receptors and the central nervous system about the external and internal environments.");
			
				p.addAnswer(2, "motor neuron",
				false,
				"No. Motor neurons transmit impulses to effectors.");
			
				p.addAnswer(3, "interneuron",
				false,
				"No. Interneurons are found within the central nervous system; they do not relay information from the external environment to the central nervous system.");
			
				p.addAnswer(4, "autonomic neuron",
				false,
				"No. The autonomic nervous system innervates effectors.");
			
				p.addAnswer(5, "Schwann cell",
				false,
				"No. Schwann cells form the myelin sheath of peripheral nerves.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336779;


		
		

		
			
			p.question = "Which of the following is specifically a part or a function of the central nervous system? (<script type=\"text/javascript\">ebook(\'4801\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "sensory receptors",
				false,
				"No. These are the parts of the peripheral nervous system that detect changes in an animal\'s external environment.");
			
				p.addAnswer(2, "sensory input",
				false,
				"No. These parts of the peripheral nervous system relay messages from sensory receptors to the central nervous system.");
			
				p.addAnswer(3, "integration",
				true,
				"Correct. Integration is the interpretation of sensory signals and the formulation of responses.");
			
				p.addAnswer(4, "motor output",
				false,
				"No. Motor output may originate in the central nervous system, but it is transmitted through the peripheral nervous system.");
			
				p.addAnswer(5, "dendrites",
				false,
				"No. Dendrites are the numerous highly branched extensions that receive signals. Dendrites are found on neurons in the central and peripheral nervous system.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336780;


		
		

		
			
			p.question = "The part of a neuron that carries nerve impulses toward the cell body is called _____. (<script type=\"text/javascript\">ebook(\'4801\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a nerve",
				false,
				"No. The term \"nerve\" generally refers to a collection of neurons and the connective tissues that organize them.");
			
				p.addAnswer(2, "white matter",
				false,
				"No. \"White matter\" refers to those portions of the nervous system that are myelinated.");
			
				p.addAnswer(3, "a neurotransmitter",
				false,
				"No. A neurotransmitter is a molecule released by one neuron and received by another.");
			
				p.addAnswer(4, "a dendrite",
				true,
				"Correct. The dendrite is defined as the part of the neuron that carries an impulse toward the cell body.");
			
				p.addAnswer(5, "an axon",
				false,
				"No. The axon is defined as that portion of the neuron that carries an impulse away from the cell body.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336781;


		
		

		
			
			p.question = "Cells that provide metabolic and structural support to the neurons are called _____. (<script type=\"text/javascript\">ebook(\'4801\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "sensory and motor neurons",
				false,
				"No. These are neurons; they are not cells that support neurons.");
			
				p.addAnswer(2, "neurotransmitters",
				false,
				"No. Neurotransmitters are not cells.");
			
				p.addAnswer(3, "interneurons",
				false,
				"No. Interneurons are cells that integrate information the nervous system.");
			
				p.addAnswer(4, "dendrites",
				false,
				"No. Dendrites are components of neurons.");
			
				p.addAnswer(5, "glia",
				true,
				"Correct.  These cells support neurons in different ways (depending on type).");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336782;


		
		

		
			
			p.question = "If your fingers touch a hot stove and you suddenly pull back, you have experienced a reflex. What is the correct order of the information processing in this reflex? (<script type=\"text/javascript\">ebook(\'4801\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "sensory input, integration, motor output",
				true,
				"Correct.");
			
				p.addAnswer(2, "motor output, sensory input, integration",
				false,
				"No. Motor output is the last step.");
			
				p.addAnswer(3, "motor output, integration, sensory input",
				false,
				"No. Motor output is the last step.");
			
				p.addAnswer(4, "integration, motor output, sensory input",
				false,
				"No. Sensory input is first, followed by integration.");
			
				p.addAnswer(5, "integration, sensory input, motor output",
				false,
				"No. Sensory input is first, followed by integration.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336783;


		
		

		
			
			p.question = "Which of the following statements is correct? (<script type=\"text/javascript\">ebook(\'4801\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A neuron only has a single axon.",
				true,
				"Correct.  Neurons have a single axon-an extension that transmits signals to other cells.");
			
				p.addAnswer(2, "Dendrites branch off axons.",
				false,
				"No. Dendrites are numerous extensions connected directly to the cell body.");
			
				p.addAnswer(3, "Axons receive signals from other neurons.",
				false,
				"No. Dendrites receive signals from other neurons.");
			
				p.addAnswer(4, "The peripheral nervous system is most closely associated with interneurons.",
				false,
				"No. The central nervous system is most closely associated with interneurons.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336784;


		
		

		
			
			p.question = "In descriptions of synapse organization, the _____ cell is the transmitting neuron and the _____ is the neuron, muscle, or gland cell that receives the signal. (<script type=\"text/javascript\">ebook(\'4801\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "presynaptic; postsynaptic",
				true,
				"Correct.  Pre- and post-synaptic cells are named for their position around the synapse.");
			
				p.addAnswer(2, "postsynaptic; presynaptic",
				false,
				"No. The order is reversed.");
			
				p.addAnswer(3, "active; passive",
				false,
				"No. These are not terms used at a synapse.");
			
				p.addAnswer(4, "producer; consumer",
				false,
				"No. These are not terms used at a synapse.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336785;


		
		

		
			
			p.question = "Which of the following statements is correct? (<script type=\"text/javascript\">ebook(\'4801\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The nucleus of a neuron is located in the axon hillock.",
				false,
				"No.<b> </b>The nucleus of a neuron is located in the cell body.");
			
				p.addAnswer(2, "Synaptic cells nourish neurons, insulate the axons of neurons, and/or regulate the extracellular fluid surrounding the neurons.",
				false,
				"No. Glia nourish neurons, insulate the axons of neurons, and/or regulate the extracellular fluid surrounding the neurons.");
			
				p.addAnswer(3, "The vast majority of neurons in the brain are sensory neurons.",
				false,
				"No. The vast majority of neurons in the brain are interneurons.");
			
				p.addAnswer(4, "Sensory neurons transmit signals to muscle cells.",
				false,
				"No. Motor neurons transmit signals to muscle cells.");
			
				p.addAnswer(5, "none of the above",
				true,
				"Correct. None of the choices above is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336786;


		
		

		
			
			p.question = "Which one of the following statements about the resting potential is true? (<script type=\"text/javascript\">ebook(\'4802\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The neuron\'s plasma membrane is much more permeable to sodium than to potassium.",
				false,
				"No. The neuron\'s plasma membrane is much more permeable to potassium than to sodium.");
			
				p.addAnswer(2, "The concentration of sodium is much higher inside the cell than outside.",
				false,
				"No. The concentration of sodium is much higher outside the cell than inside.");
			
				p.addAnswer(3, "The chloride-hydrogen pump plays a role in maintaining the resting potential.",
				false,
				"No. The sodium-potassium pump does play a major role in maintaining the resting potential.");
			
				p.addAnswer(4, "Inside the cell, the concentration of potassium is much higher than the concentration of sodium.",
				true,
				"Correct. The concentration of potassium is much higher inside the cell.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. Only one of these statements is true.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336787;


		
		

		
			
			p.question = "The sodium-potassium pump _____. (<script type=\"text/javascript\">ebook(\'4802\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "expels sodium from the cell",
				true,
				"Correct. The sodium-potassium pump is a channel protein that expels sodium from the cell, exchanging it for potassium.");
			
				p.addAnswer(2, "expels sodium and potassium from the cell",
				false,
				"No. The sodium-potassium pump brings potassium into the cell.");
			
				p.addAnswer(3, "pumps sodium into the cell",
				false,
				"No. The sodium-potassium pump removes sodium from the cell.");
			
				p.addAnswer(4, "pumps sodium and potassium into the cell",
				false,
				"No. The sodium-potassium pump removes sodium from the cell.");
			
				p.addAnswer(5, "allows ions to move in either direction through the membrane",
				false,
				"No. Ion channels are pores that allow ions to pass through in either direction.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336788;


		
		

		
			
			p.question = "Which of the following statements is true? (<script type=\"text/javascript\">ebook(\'4802\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Ion channels only allow ions to diffuse up their concentration gradients.",
				false,
				"No. Ion channels allow ions to diffuse back and forth across a cell membrane.");
			
				p.addAnswer(2, "Ion channels are selectively permeable, permitting only certain ions to pass.",
				true,
				"Correct.  A potassium channel allows K<sup>+</sup> to diffuse freely across the membrane, but not other ions, such as Na<sup>+</sup>.");
			
				p.addAnswer(3, "All cells have an equilibrium potential, a difference in electrical charges across their plasma membrane.",
				false,
				"No. All cells have a membrane potential, a difference in electrical charges across their plasma membrane.");
			
				p.addAnswer(4, "Concentration gradients of proteins across the plasma membrane represent potential energy.",
				false,
				"No. Concentration gradients of ions across the plasma membrane represent potential energy.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336789;


		
		

		
			
			p.question = "An increase in the magnitude of the membrane potential is called _____. (<script type=\"text/javascript\">ebook(\'4803\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "hyperpolarization",
				true,
				"Correct.  Hyperpolarization results from any stimulus that increases either the outflow of positive ions or the inflow of negative ions.");
			
				p.addAnswer(2, "hypopolarization",
				false,
				"No. Hyperpolarization is an increase in the magnitude of the membrane potential.");
			
				p.addAnswer(3, "depolarization",
				false,
				"No. Depolarization is a decrease in the magnitude of the membrane potential.");
			
				p.addAnswer(4, "a refractory period",
				false,
				"No. A refractory period is the \"downtime\" following an action potential.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336790;


		
		

		
			
			p.question = "A drug that causes potassium to leak out of a neuron, increasing the positive charge on the outside, would _____. (<script type=\"text/javascript\">ebook(\'4803\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "make it easier to trigger action potentials in the neuron",
				false,
				"No. This condition would hyperpolarize the membrane and reduce the possibility of an action potential.");
			
				p.addAnswer(2, "cause the cell to release its neurotransmitter",
				false,
				"No. Neurotransmitter release occurs when voltage-gated calcium channels open near the end of the axon.");
			
				p.addAnswer(3, "speed up nerve signals traveling the length of the cell",
				false,
				"No. Only the presence of myelin and the diameter of the neuron influence the conduction speed.");
			
				p.addAnswer(4, "act as a stimulant",
				false,
				"No, just the opposite. The result of potassium leakage would be a hyperpolarization of the membrane.");
			
				p.addAnswer(5, "inhibit transmission of nerve signals by the neuron",
				true,
				"Correct. The additional positive charge to the outside of the neuron would cause a hyperpolarization of the membrane.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336791;


		
		

		
			
			p.question = "Threshold is of great significance in the physiology of neurons because if threshold is not reached, _____. (<script type=\"text/javascript\">ebook(\'4803\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the neuron cannot regain its resting potential",
				false,
				"No. The neuron will eventually revert to its resting potential.");
			
				p.addAnswer(2, "the action potential will be \"inversed,\" with a flux of sodium out of the cell rather than into it",
				false,
				"No. An action potential is not \"inversed\"; moreover, an action potential involves the influx of sodium ions.");
			
				p.addAnswer(3, "positive-feedback depolarization will not occur",
				true,
				"Correct. Stimuli that do not depolarize the membrane to the level of the threshold do not generate action potentials.");
			
				p.addAnswer(4, "an action potential will be reached",
				false,
				"No. Attainment of the threshold potential triggers an action potential.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336792;


		
		

		
			
			p.question = "Schwann cells make up the _____. (<script type=\"text/javascript\">ebook(\'4803\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "neurons",
				false,
				"No. Schwann cells cover the axons of certain neurons.");
			
				p.addAnswer(2, "nodes of Ranvier",
				false,
				"No. Nodes of Ranvier are gaps in the covering of a myelin sheath.");
			
				p.addAnswer(3, "myelin sheath",
				true,
				"Correct. In the peripheral nervous system, supporting cells called Schwann cells wrap many axons with an insulating myelin sheath.");
			
				p.addAnswer(4, "axons",
				false,
				"No. Axons are a part of neurons.");
			
				p.addAnswer(5, "neurotransmitter secretory vesicles",
				false,
				"No. Vesicles are membrane-bound structures found within axon terminals.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336793;


		
		

		
			
			p.question = "An action potential is _____. (<script type=\"text/javascript\">ebook(\'4803\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a traveling wave of depolarization in the neuron membrane",
				true,
				"Correct. An action potential is an all-or-none change in membrane potential that travels along the neuron.");
			
				p.addAnswer(2, "a brief neutralization of the charges on sodium and potassium ions",
				false,
				"No. An action potential involves a wave of depolarization followed by a wave of repolarization; the charges on sodium and potassium ions are not neutralized.");
			
				p.addAnswer(3, "a sudden increase in speed by the sodium-potassium pump",
				false,
				"No. The rate at which the sodium-potassium pump functions does not increase.");
			
				p.addAnswer(4, "a sudden reversal of the sodium-potassium pump",
				false,
				"No. The sodium-potassium pump does not run in reverse.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336794;


		
		

		
			
			p.question = "The period in which an axon membrane cannot act is called _____. (<script type=\"text/javascript\">ebook(\'4803\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the refractory period",
				true,
				"Correct. A membrane cannot act during the refractory period because its gates will not open.");
			
				p.addAnswer(2, "saltatory conduction",
				false,
				"No. Saltatory conduction is a type of impulse conduction that occurs along myelinated axons.");
			
				p.addAnswer(3, "depolarization",
				false,
				"No. Depolarization is a reduction in the magnitude of the membrane potential.");
			
				p.addAnswer(4, "the node of Ranvier",
				false,
				"No. Nodes of Ranvier are gaps in a myelin sheath.");
			
				p.addAnswer(5, "an action potential",
				false,
				"No. An action potential is a nerve impulse.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336795;


		
		

		
			
			p.question = "\"Saltatory conduction\" means that the membrane potential changes _____. (<script type=\"text/javascript\">ebook(\'4803\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "only where there is diffusion of sodium and potassium ions",
				false,
				"No. This is not a feature that distinguishes saltatory conduction from other types of impulse conduction.");
			
				p.addAnswer(2, "only at the nodes of Ranvier",
				true,
				"Correct. The action potential does not propagate over the length of the myelinated axon but jumps from node of Ranvier to node of Ranvier, skipping the myelinated regions of membrane between the nodes.");
			
				p.addAnswer(3, "along the entire length of the axon",
				false,
				"No. \"Saltatory conduction\" specifically refers to a type of conduction that does not involve changes in membrane potential along the entire length of the axon.");
			
				p.addAnswer(4, "in an all-or-none fashion",
				false,
				"No. This is not a feature that distinguishes saltatory conduction from other types of impulse conduction.");
			
				p.addAnswer(5, "from polarized to depolarized and back to polarized",
				false,
				"No. This is not a feature that distinguishes saltatory conduction from other types of impulse conduction.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336796;


		
		

		
			
			p.question = "Action potentials are generated along a neuron because _____. (<script type=\"text/javascript\">ebook(\'4803\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "of cytoplasmic streaming within the neuron",
				false,
				"No. An action potential involves the diffusion of ions.");
			
				p.addAnswer(2, "depolarization of the membrane at one point causes an increase of permeability to sodium at the next point",
				true,
				"Correct. An influx of sodium depolarizes the membrane and opens more sodium channels, causing still more depolarization; this is an example of positive feedback.");
			
				p.addAnswer(3, "they are pulled along by positive-negative attraction",
				false,
				"No. Action potentials are dependent on concentration gradients, not on the attraction of positive and negative charges.");
			
				p.addAnswer(4, "the neuron cytoskeleton conducts electricity as long as an ion gradient is maintained by the sodium-potassium pump",
				false,
				"No. An action potential involves the disruption of the ion gradient.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. Only one of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336797;


		
		

		
			
			p.question = "How are neurons structurally adapted to chemically transmit impulses to neighboring neurons? (<script type=\"text/javascript\">ebook(\'4804\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Axon terminals contain neurotransmitter substances within synaptic vesicles.",
				true,
				"Correct. Numerous sacs, called synaptic vesicles, located in the cytoplasm at the tip of the presynaptic axon release molecules of a neurotransmitter across the synaptic cleft, which bind to receptors imbedded in the membrane of the postsynaptic cell.");
			
				p.addAnswer(2, "They have numerous nodes of Ranvier.",
				false,
				"No. The node of Ranvier is the space between Schwann cells along the axon; it plays a role in the saltatory conduction of a nerve impulse.");
			
				p.addAnswer(3, "They have numerous dendrites.",
				false,
				"No. The dendrite, like a tree root, is for intake. In the case of the neuron, transmissions move through the dendrites into the cell body.");
			
				p.addAnswer(4, "They have Schwann cells that surround axons.",
				false,
				"No. Schwann cells form the myelin sheath, which plays a role in the transmission of an impulse along an axon.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336798;


		
		

		
			
			p.question = "Which one of the following statements about the transmission across a typical chemical synapse is true? (<script type=\"text/javascript\">ebook(\'4804\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Neurotransmitter molecules are stored in vesicles in the dendrites.",
				false,
				"No. Neurotransmitter molecules are stored in vesicles in the synaptic terminal.");
			
				p.addAnswer(2, "Action potentials trigger chemical changes that make the neurotransmitter vesicles fuse with the plasma membrane of the receiving cell.",
				false,
				"No. Action potentials do trigger chemical changes that make the neurotransmitter vesicles fuse with the plasma membrane of the transmitting cell.");
			
				p.addAnswer(3, "Vesicles containing neurotransmitter molecules diffuse to the receiving cell\'s plasma membrane.",
				false,
				"No. Numerous sacs, called synaptic vesicles, located in the cytoplasm at the tip of the presynaptic axon <i>release</i> molecules of a neurotransmitter across the synaptic cleft, but the vesicles themselves do not fuse with the receiving cell.");
			
				p.addAnswer(4, "Neurotransmitter molecules bind to receptors in the sending cell\'s plasma membrane.",
				false,
				"No. Neurotransmitter molecules do bind to receptors in the receiving cell\'s plasma membrane.");
			
				p.addAnswer(5, "The binding of neurotransmitter molecules to receptors transmits an impulse across a synapse.",
				true,
				"Correct. The binding of neurotransmitter molecules to receptors does transmit an impulse across a synapse.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336799;


		
		

		
			
			p.question = "Acetylcholinesterase is the enzyme that degrades acetylcholine. What effect on nerve transmission would occur following the administration of a chemical that inhibited acetylcholinesterase? (<script type=\"text/javascript\">ebook(\'4804\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "There would be no effect.",
				false,
				"No. If the enzyme was inhibited, acetylcholine molecules would not be degraded.");
			
				p.addAnswer(2, "Synaptic transmission would be prevented; muscle paralysis would occur.",
				false,
				"No. To produce paralysis, it would be necessary to block the acetylcholine receptor on the muscle cell.");
			
				p.addAnswer(3, "It would be identical to giving an anesthetic, but it would last permanently.",
				false,
				"No. To produce the effect of an anesthetic, it would be necessary to inhibit the postsynaptic receptor.");
			
				p.addAnswer(4, "Extra excitatory postsynaptic potentials would occur in the postsynaptic neuron.",
				true,
				"Correct. Because the neurotransmitter is not degraded, it continues to interact with the receptors on the postsynaptic membrane.");
			
				p.addAnswer(5, "The presynaptic neuron would be inactivated.",
				false,
				"No. Acetylcholine, like any other neurotransmitter, is active at the synapse between the pre- and postsynaptic neurons.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336800;


		
		

		
			
			p.question = "In humans, making more serotonin available to brain cells typically _____. (<script type=\"text/javascript\">ebook(\'4804\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "increases the stimulatory effects of caffeine",
				false,
				"No. Caffeine competes for receptors with adenosine (which, in the brain, functions as an inhibitory neurotransmitter); thus, caffeine acts as a stimulant by blocking the inhibitory effects of adenosine.");
			
				p.addAnswer(2, "produces an effect on mood",
				true,
				"Correct. Dopamine and serotonin are widespread in the brain and affect sleep, mood, attention, and learning.");
			
				p.addAnswer(3, "counteracts the effects of alcohol",
				false,
				"No. Serotonin does not counteract the effects of alcohol.");
			
				p.addAnswer(4, "causes the heart to beat faster",
				false,
				"No. Serotonin does not function as a stimulant.");
			
				p.addAnswer(5, "depresses the central nervous system",
				false,
				"No. Serotonin does not act as a depressant.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336801;


		
		

		
			
			p.question = "A natural pain reliever is _____. (<script type=\"text/javascript\">ebook(\'4804\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "epinephrine",
				false,
				"No. Epinephrine has sympathetic effects.");
			
				p.addAnswer(2, "acetylcholine",
				false,
				"No. Acetylcholine is active at neuromuscular junctions.");
			
				p.addAnswer(3, "endorphins",
				true,
				"Correct. Endorphins are neuropeptides that function as natural analgesics, decreasing the perception of pain by the CNS.");
			
				p.addAnswer(4, "dopamine",
				false,
				"No. However, dopamine affects sleep, mood, attention, and learning. Furthermore, Parkinson\'s disease is associated with a lack of dopamine.");
			
				p.addAnswer(5, "substance P",
				false,
				"No. Substance P is excitatory as it facilitates pain perception.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336802;


		
		

		
			
			p.question = "Which one of the following correctly pairs up a type of synapse and its characteristic? (<script type=\"text/javascript\">ebook(\'4804\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "electrical synapse; gap junctions",
				true,
				"Correct. Electrical synapses contain gap junctions.");
			
				p.addAnswer(2, "electrical synapse; neurotransmitters",
				false,
				"No. Chemical synapses involve neurotransmitters.");
			
				p.addAnswer(3, "junctional synapses; ligand-gated ion channels",
				false,
				"No. There are no such things as junctional synapses. Chemical synapses are associated with ligand-gated ion channels.");
			
				p.addAnswer(4, "chemical synapses; gap junctions",
				false,
				"No. Electrical synapses contain gap junctions.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the above is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336803;


		
		

		
			
			p.question = "Which one of the following neurotransmitters typically has inhibitory effects? (<script type=\"text/javascript\">ebook(\'4804\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "GABA",
				true,
				"Correct. GABA appears to be the neurotransmitter at most inhibitory synapses.");
			
				p.addAnswer(2, "glutamate",
				false,
				"No. Glutamate, the most common neurotransmitter in the brain, is always excitatory.");
			
				p.addAnswer(3, "norepinephrine",
				false,
				"No. Norepinephrine generates excitatory postsynaptic potentials.");
			
				p.addAnswer(4, "substance P",
				false,
				"No. Substance P is a key excitatory neurotransmitter that mediates our perception of pain.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the above typically has inhibitory effects.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336804;


		
		

		
			
			p.question = "Which of the following is a mechanism by which neurotransmitters can be rapidly cleared from the synaptic cleft? (<script type=\"text/javascript\">ebook(\'4804\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The neurotransmitters are actively transported back into the presynaptic cells to be repackaged into synaptic vesicles.",
				false,
				"No. Although this is a correct answer, there is a better choice.");
			
				p.addAnswer(2, "The neurotransmitters are actively transported into glia to be metabolized as fuel.",
				false,
				"No. Although this is a correct answer, there is a better choice.");
			
				p.addAnswer(3, "Neurotransmitters are removed by simple diffusion.",
				false,
				"No. Although this is a correct answer, there is a better choice.");
			
				p.addAnswer(4, "Neurotransmitters are removed by enzymes that catalyze hydrolysis of the neurotransmitter.",
				false,
				"No. Although this is a correct answer, there is a better choice.");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct. There is more than one way that neurotransmitters can be cleared from the synaptic cleft");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336805;


		
		

		
			
			p.question = "The interplay of multiple excitatory and inhibitory inputs most affects what part of a neuron? (<script type=\"text/javascript\">ebook(\'4804\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "axon hillock",
				true,
				"Correct. The axon hillock is the neuron\'s integrating center.");
			
				p.addAnswer(2, "dendrites",
				false,
				"No. Dendrites are not where the signals are integrated.");
			
				p.addAnswer(3, "the nucleus",
				false,
				"No. The nucleus is not where the signals are integrated.");
			
				p.addAnswer(4, "the neuron\'s cytoskeleton",
				false,
				"No. The cytoskeleton is not where the signals are integrated.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

