

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "GraphIt! Quiz > GraphIt! Quiz > Forestation Change";
	ak.quiz_loc_with_commas = "GraphIt! Quiz, GraphIt! Quiz, Forestation Change";
	ak.quiz_title = "Forestation Change";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 6;
	ak.non_essay_total = 6;
	ak.scored_item_total = 6;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337486;


		
		

		
			
			p.question = "How much more timber was removed from \"other private\" lands versus \"national forest\" land?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "twice as much",
				false,
				"");
			
				p.addAnswer(2, "about the same",
				false,
				"");
			
				p.addAnswer(3, "ten times as much",
				true,
				"");
			
				p.addAnswer(4, "one hundred times as much",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337487;


		
		

		
			
			p.question = "Which type of land lost the largest proportion of its timber in 1996?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "can\'t answer with the available information",
				true,
				"");
			
				p.addAnswer(2, "other public",
				false,
				"");
			
				p.addAnswer(3, "national forest",
				false,
				"");
			
				p.addAnswer(4, "forest industry",
				false,
				"");
			
				p.addAnswer(5, "other private",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337488;


		
		

		
			
			p.question = "For which type of land is the total volume of forest (in cubic feet) decreasing?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "other public",
				false,
				"");
			
				p.addAnswer(2, "forest industry",
				true,
				"");
			
				p.addAnswer(3, "national forest",
				false,
				"");
			
				p.addAnswer(4, "other private",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337489;


		
		

		
			
			p.question = "Which of the following are accurate statements based on the information in this graph?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "National forest land had the greatest growth relative to the amount of harvesting.",
				false,
				"");
			
				p.addAnswer(2, "Lands other than forest industry land appear to be managed to produce net forest growth.",
				false,
				"");
			
				p.addAnswer(3, "Overall, U.S. forest land is experiencing net growth as of 1996.",
				false,
				"");
			
				p.addAnswer(4, "All of the above.",
				true,
				"");
			
				p.addAnswer(5, "None of the above.",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337490;


		
		

		
			
			p.question = "Which world region experienced the largest change in forested land between 1990 and 2000?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "West Asia",
				false,
				"");
			
				p.addAnswer(2, "Europe",
				false,
				"");
			
				p.addAnswer(3, "Asia",
				false,
				"");
			
				p.addAnswer(4, "North America",
				false,
				"");
			
				p.addAnswer(5, "Africa",
				true,
				"");
			
				p.addAnswer(6, "South America",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337491;


		
		

		
			
			p.question = "Which of the following are accurate statements based on the information in this graph?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The information in this graph is consistent with the information in the graph of harvesting and growth in U.S. forests from Step 2.",
				false,
				"");
			
				p.addAnswer(2, "Loss of forested land appears to be greater in the developing world than in the developed world.",
				false,
				"");
			
				p.addAnswer(3, "The world overall is experiencing a net loss of forest.",
				false,
				"");
			
				p.addAnswer(4, "All of the above.",
				true,
				"");
			
				p.addAnswer(5, "None of the above.",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

