

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "Investigation Quiz > How Do Cells Communicate with Each Other?";
	ak.quiz_loc_with_commas = "Investigation Quiz, How Do Cells Communicate with Each Other?";
	ak.quiz_title = "How Do Cells Communicate with Each Other?";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 6;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 6;
	ak.non_essay_total = 0;
	ak.scored_item_total = 0;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337598;


		
		

		
			p.question = "Provide two reasons why communication is essential between cells in multicellular organisms.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337599;


		
		

		
			p.question = "Which environmental factor produced the strongest aggregation response? Explain why you believe this factor had the strongest effect.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337600;


		
		

		
			p.question = "What can you conclude about the chemical nature of the aggregation molecule?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337601;


		
		

		
			p.question = "What has this investigation told you about the aggregation molecule and what more do you need to know about the chemistry of the molecule?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337602;


		
		

		
			p.question = "From your data, which nucleotide best matches the aggregation molecule, and what needs to be done to confirm your answer?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337603;


		
		

		
			p.question = "What conclusion can you make from the information you gathered from the entire experiment?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

