

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "Investigation Quiz > How Does Bone Structure Shed Light on the Origin of Birds?";
	ak.quiz_loc_with_commas = "Investigation Quiz, How Does Bone Structure Shed Light on the Origin of Birds?";
	ak.quiz_title = "How Does Bone Structure Shed Light on the Origin of Birds?";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 9;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 9;
	ak.non_essay_total = 0;
	ak.scored_item_total = 0;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337766;


		
		

		
			p.question = "Compare the skeleton of the pigeon with the fossil impression of <i>Archaeopteryx</i>. Describe any similarities you see in skeletal structure, especially in the bones of the arm and \"hand\". Use the names of the bones as labeled in the bird skeleton.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337767;


		
		

		
			p.question = "Why do you think bipedalism is an important prerequisite in considering <i>Compsognathus</i> or <i>Bambiraptor</i> as possible close ancestors of <i>Archaeopteryx</i>?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337768;


		
		

		
			p.question = "In the <i>Longisquama</i> fossil, what part or parts of the plume-like appendages probably made some researchers believe that the plumes are feathers? Review feather structure in your textbook.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337769;


		
		

		
			p.question = "According to the phylogenetic tree of reptile evolution, what animals are the closest <i>living</i> relatives to modern birds?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337770;


		
		

		
			p.question = "What are the two major groups of dinosaurs? Approximately when did they diverge from one another?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337771;


		
		

		
			p.question = "Summarize your data by listing any common canaliculi patterns among the ornithischians, mammals, lizards, and coelurosaurs (ornithomimids and birds).";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337772;


		
		

		
			p.question = "Randomly organized canaliculi have been correlated with bone that grows very quickly. Fast growing bone is associated with a high metabolic rate and endothermy. What can you hypothesize about the temperature regulating abilities of the late ornithischians and saurischians? Does your bone data from the lizard fit what you know about modern reptile thermoregulation?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337773;


		
		

		
			p.question = "Do these data lend any support to the birds-from-dinosaurs theory or the birds from archosaurs theory? What if you were told that crocodile bones have also been analyzed and found to have directional canaliculi (this has actually been done with this result)?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337774;


		
		

		
			p.question = "You may be wondering why mammalian bones show directional canaliculi (suggestive of ectothermy) when mammals are in fact endothermic. Young mammals that are growing quickly do show randomly organized canaliculi, as do spots where bone has healed from a fracture. In looking at your data, is endothermy in birds and mammals a common homologous characteristic, derived from a common ancestor? What type of evolution is this?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

