

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "44: Osmoregulation and Excretion > Activities Quiz";
	ak.quiz_loc_with_commas = "44: Osmoregulation and Excretion, Activities Quiz";
	ak.quiz_title = "Activities Quiz";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 15;
	ak.non_essay_total = 15;
	ak.scored_item_total = 15;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336538;


		
		

		
			
			p.question = "The urethra is identified by the letter _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?44&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Structure of the Human Excretory System</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/4401q.jpg\" ALT=\"Question #1\" BORDER=\"1\" >";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A",
				false,
				"This is indicating a renal artery and vein.");
			
				p.addAnswer(2, "B",
				false,
				"This is the ureter.");
			
				p.addAnswer(3, "C",
				false,
				"This is the urinary bladder.");
			
				p.addAnswer(4, "D",
				false,
				"This is the kidney.");
			
				p.addAnswer(5, "E",
				true,
				"The urethra transports urine from the urinary bladder to the world outside the body.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336539;


		
		

		
			
			p.question = "Urine formed by a kidney collects in the _____ before being drained from the kidney by the _____ and transported to the _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?44&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Structure of the Human Excretory System</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "urethra ... urinary bladder ... ureter",
				false,
				"This sequence is transporting urine back toward the kidney.");
			
				p.addAnswer(2, "renal pelvis ... medulla ... cortex",
				false,
				"One of these three is in the correct position.");
			
				p.addAnswer(3, "renal pelvis ... ureter ...urinary bladder",
				true,
				"This is the appropriate sequence of the flow of urine.");
			
				p.addAnswer(4, "renal pelvis ... urethra ... urinary bladder",
				false,
				"The urethra transports urine away from the urinary bladder.");
			
				p.addAnswer(5, "ureter ... renal pelvis ... urinary bladder",
				false,
				"Right parts, wrong sequence.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336540;


		
		

		
			
			p.question = "Filtrate is formed as fluid is forced through the walls of the glomerulus and, initially, collects in the structure indicated by the letter (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?44&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Structure of the Human Excretory System</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/4403q.jpg\" ALT=\"Question #3\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A",
				false,
				"This is the glomerulus.");
			
				p.addAnswer(2, "B",
				true,
				"Fluid from the glomerulus first collects in Bowman\'s capsule.");
			
				p.addAnswer(3, "C",
				false,
				"This is the proximal tubule. Filtrate flows from Bowman\'s capsule to the proximal tubule.");
			
				p.addAnswer(4, "D",
				false,
				"This is the distal tubule. Filtrate flows from the loop of Henle to the distal tubule.");
			
				p.addAnswer(5, "E",
				false,
				"This is the loop of Henle. Filtrate flows from the proximal tubule to the loop of Henle.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336541;


		
		

		
			
			p.question = "The _____ are the major blood vessels transporting blood to the kidneys. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?44&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Structure of the Human Excretory System</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "pulmonary arteries",
				false,
				"Pulmonary arteries transport blood to the lungs.");
			
				p.addAnswer(2, "glomerulus",
				false,
				"Glomeruli are capillaries found within the kidneys.");
			
				p.addAnswer(3, "renal arteries",
				true,
				"The word \"renal\" refers to a kidney. Recall that arteries transport blood away from the heart. Renal arteries transport blood to the kidneys.");
			
				p.addAnswer(4, "renal veins",
				false,
				"While the word \"renal\" does refer to a kidney, recall that veins transport blood to the heart. Therefore, renal veins transport blood away from the kidneys.");
			
				p.addAnswer(5, "venae cavae",
				false,
				"The venae cavae are the major blood vessels transporting blood back to the heart.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336542;


		
		

		
			
			p.question = "The outer part of the kidney is the _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?44&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Structure of the Human Excretory System</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "medulla",
				false,
				"The term \"medulla\" refers to the center of a structure.");
			
				p.addAnswer(2, "nephron",
				false,
				"The nephron, the functional unit of the kidney, is not the outer part of the kidney.");
			
				p.addAnswer(3, "lacteal",
				false,
				"Lacteals, components of the lymphatic system, are associated with the gastrointestinal tract.");
			
				p.addAnswer(4, "cortex",
				true,
				"The cortex is the outer part of the kidney.");
			
				p.addAnswer(5, "Bowman\'s capsule",
				false,
				"Bowman\'s capsule, while found in the outer part of the kidney, is not the outer part of the kidney.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336543;


		
		

		
			
			p.question = "Which of these is the functional unit of a kidney? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?44&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Structure of the Human Excretory System</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "neuron",
				false,
				"Neurons are a component of the nervous system.");
			
				p.addAnswer(2, "villi",
				false,
				"Villi, found in the small intestine, play a role in nutrient absorption.");
			
				p.addAnswer(3, "nephron",
				true,
				"The nephron is the functional unit of a kidney.");
			
				p.addAnswer(4, "alveolus",
				false,
				"Alveoli are found in lungs; gas exchange occurs across the walls of alveoli.");
			
				p.addAnswer(5, "osteon",
				false,
				"Osteons are associated with the skeletal system.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336544;


		
		

		
			
			p.question = "The movement of substances out of the glomerulus and into Bowman\'s capsule is referred to as _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?44&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Nephron Function</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "secretion",
				false,
				"\"Secretion\" describes the movement of substances from the blood into the kidney tubules.");
			
				p.addAnswer(2, "reabsorption",
				false,
				"\"Reabsorption\" describes the movement of substances from the kidney tubules into the blood.");
			
				p.addAnswer(3, "active transport",
				false,
				"Active transport requires cells to expend energy; the energy for the process referred to in the question is supplied by blood pressure.");
			
				p.addAnswer(4, "ion pumping",
				false,
				"Ion pumping requires cells to expend energy; the energy for the process referred to in the question is supplied by blood pressure.");
			
				p.addAnswer(5, "filtration",
				true,
				"Blood pressure is the force behind the filtration of substances out of the glomerulus and into Bowman\'s capsule.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336545;


		
		

		
			
			p.question = "The movement of substances from the blood into the proximal tubule is known as _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?44&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Nephron Function</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "filtration",
				false,
				"Blood pressure forces the filtration of substances out of the glomerulus and into Bowman\'s capsule.");
			
				p.addAnswer(2, "dialysis",
				false,
				"Dialysis (as in kidney dialysis) is size-dependent diffusion.");
			
				p.addAnswer(3, "secretion",
				true,
				"Secretion is the movement of substances from the blood into the kidney tubules.");
			
				p.addAnswer(4, "reabsorption",
				false,
				"Reabsorption is the movement of substances from the kidney tubules into the blood.");
			
				p.addAnswer(5, "none of these",
				false,
				"One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336546;


		
		

		
			
			p.question = "Which of these is reabsorbed from filtrate? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?44&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Nephron Function</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "sodium chloride",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(2, "glucose",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(3, "water",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(4, "amino acids",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(5, "all of these",
				true,
				"All of these, as well as bicarbonate ions, are reabsorbed from the filtrate.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336547;


		
		

		
			
			p.question = "As filtrate moves down the loop of Henle, the surrounding interstitial fluid becomes _____ concentrated than the filtrate, so _____ leaves the filtrate. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?44&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Nephron Function</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "more ... urea",
				false,
				"As filtrate moves down the loop of Henle, urea is added to the filtrate.");
			
				p.addAnswer(2, "less ... urea",
				false,
				"Kidneys remove urea from body fluids.");
			
				p.addAnswer(3, "more ... water",
				true,
				"The increasing solute concentration of the interstitial fluid results in water leaving the filtrate by osmosis.");
			
				p.addAnswer(4, "less ... water",
				false,
				"Interstitial fluid that is less concentrated than filtrate would promote the movement of water into the filtrate.");
			
				p.addAnswer(5, "less ... water and urea",
				false,
				"Interstitial fluid that is less concentrated than filtrate would promote the movement of water into the filtrate.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336548;


		
		

		
			
			p.question = "The most abundant solute in urine is _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?44&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Nephron Function</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "glucose",
				false,
				"Most glucose has been reabsorbed.");
			
				p.addAnswer(2, "water",
				false,
				"Although urine is mostly water, recall that water is a solvent, not a solute.");
			
				p.addAnswer(3, "plasma proteins",
				false,
				"Plasma proteins are not normally found in urine.");
			
				p.addAnswer(4, "sodium chloride",
				false,
				"Much of the sodium chloride in filtrate (which becomes urine) is reabsorbed.");
			
				p.addAnswer(5, "urea (and other nitrogenous wastes)",
				true,
				"Nitrogenous wastes, such as urea, are the primary solute found in urine.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336549;


		
		

		
			
			p.question = "Which arrow indicates the direction of a gradient of increasing solute concentration in the interstitial fluid surrounding a nephron? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?44&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Nephron Function</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/4412q.jpg\" ALT=\"Question #12\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A only",
				true,
				"The solute concentration of the interstitial fluid increases along a gradient running from the exterior of the kidney to the center of the kidney.");
			
				p.addAnswer(2, "B only",
				false,
				"Consider that the distal tubule reabsorbs water and that the gradient indicated by B puts the distal tubule in a region of high solute concentration.");
			
				p.addAnswer(3, "B and C",
				false,
				"These gradients are not consistent with each other: Gradient B indicates a low solute concentration in the Bowman\'s capsule region; gradient C indicates a high solute concentration in the Bowman\'s capsule region.");
			
				p.addAnswer(4, "C and D",
				false,
				"These gradients are not consistent with each other: Gradient C indicates a high solute concentration in the proximal tubule region; gradient D indicates a low solute concentration in the proximal tubule region.");
			
				p.addAnswer(5, "A and D",
				false,
				"These gradients are not consistent with each other: Gradient A indicates a low solute concentration in the Bowman\'s capsule region; gradient D indicates a high solute concentration in the Bowman\'s capsule region.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336550;


		
		

		
			
			p.question = "Glucose is removed from filtrate by _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?44&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Nephron Function</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "secretion",
				false,
				"Secretion adds solutes to the filtrate.");
			
				p.addAnswer(2, "diffusion",
				false,
				"Glucose is not reabsorbed by diffusion.");
			
				p.addAnswer(3, "dialysis",
				false,
				"Glucose is not reabsorbed by dialysis.");
			
				p.addAnswer(4, "active transport",
				true,
				"The reabsorption of glucose requires the expenditure of energy.");
			
				p.addAnswer(5, "osmosis",
				false,
				"\"Osmosis\" refers to the movement of water.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336551;


		
		

		
			
			p.question = "Under the influence of antidiuretic hormone (ADH), _____ is produced. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?44&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Control of Water Reabsorption</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "urine containing more glucose",
				false,
				"Even under the influence of ADH, glucose is not a usual constituent of urine.");
			
				p.addAnswer(2, "bloody urine",
				false,
				"Blood in the urine can be caused by kidney stones and other pathological conditions, but not by ADH.");
			
				p.addAnswer(3, "urine containing a lower concentration of urea",
				false,
				"Under the influence of ADH the concentration of urea in the urine would increase.");
			
				p.addAnswer(4, "more concentrated urine",
				true,
				"Under the influence of ADH more concentrated urine is produced and the body conserves water.");
			
				p.addAnswer(5, "less concentrated urine",
				false,
				"You may have the right idea, just a bit reversed.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336552;


		
		

		
			
			p.question = "Antidiuretic hormone (ADH) makes the _____ permeable to water. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?44&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Control of Water Reabsorption</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "ascending portion of the loop of Henle",
				false,
				"ADH does not act on the ascending portion of the loop of Henle.");
			
				p.addAnswer(2, "collecting duct",
				true,
				"Making the collecting duct permeable to water results in the reabsorption of water.");
			
				p.addAnswer(3, "Bowman\'s capsule",
				false,
				"ADH does not act on Bowman\'s capsule.");
			
				p.addAnswer(4, "proximal tubule",
				false,
				"ADH does not act on the proximal tubule.");
			
				p.addAnswer(5, "descending portion of the loop of Henle",
				false,
				"ADH does not act on the descending portion of the loop of Henle.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

