

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "6: A Tour of the Cell > Activities Quiz";
	ak.quiz_loc_with_commas = "6: A Tour of the Cell, Activities Quiz";
	ak.quiz_title = "Activities Quiz";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 24;
	ak.non_essay_total = 24;
	ak.scored_item_total = 24;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334313;


		
		

		
			
			p.question = "1 meter = _____ centimeters. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?6&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Metric System Review</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "100",
				true,
				"A centimeter is 1 hundredth of a meter.");
			
				p.addAnswer(2, "1,000,000,000",
				false,
				"A nanometer is 1 billionth of a meter.");
			
				p.addAnswer(3, "1,000",
				false,
				"A millimeter is 1 thousandth of a meter.");
			
				p.addAnswer(4, "1,000,000,000,000",
				false,
				"A picometer is 1 trillionth of a meter.");
			
				p.addAnswer(5, "1,000,000",
				false,
				"A micrometer is 1 millionth of a meter.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334314;


		
		

		
			
			p.question = "_____ are surface appendages that allow a bacterium to stick to a surface. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?6&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Prokaryotic Cell Structure and Function</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Cell walls",
				false,
				"The cell wall is a protective structure that surrounds a bacterium.");
			
				p.addAnswer(2, "Flagella",
				false,
				"Flagella play a role in locomotion.");
			
				p.addAnswer(3, "Ribosomes",
				false,
				"Ribosomes are involved in polypeptide (protein) synthesis.");
			
				p.addAnswer(4, "Mitochondria",
				false,
				"Bacteria do not posses mitochondria.");
			
				p.addAnswer(5, "Pili",
				true,
				"Pili enable bacterial cells to stick to a surface.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334315;


		
		

		
			
			p.question = "What is the function of a bacterium\'s capsule? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?6&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Prokaryotic Cell Structure and Function</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "protection",
				true,
				"A bacterium\'s capsule has a protective role.");
			
				p.addAnswer(2, "adhesion",
				false,
				"Pili play a role in adhesion.");
			
				p.addAnswer(3, "protein synthesis",
				false,
				"This is the function of ribosomes.");
			
				p.addAnswer(4, "DNA storage",
				false,
				"The nucleoid region contains a bacterium\'s DNA.");
			
				p.addAnswer(5, "propulsion",
				false,
				"Flagella propel bacterial cells.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334316;


		
		

		
			
			p.question = "In eukaryotic cells the first step in protein synthesis is the _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?6&E','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Role of the Nucleus and Ribosomes in Protein Synthesis</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "translation of an RNA nucleotide sequence into a sequence of amino acids",
				false,
				"This is a component of the second of the two main steps of protein synthesis.");
			
				p.addAnswer(2, "linking of nucleotides to form a polypeptide",
				false,
				"Polypeptides are not composed of nucleotides.");
			
				p.addAnswer(3, "translation of a DNA nucleotide sequence into a sequence of amino acids",
				false,
				"A DNA sequence is not directly translated into an amino acid sequence.");
			
				p.addAnswer(4, "transferring of information from DNA to messenger RNA",
				true,
				"Transcription is the first of the two main steps of protein synthesis.");
			
				p.addAnswer(5, "removal of introns from RNA and the stitching together of exons",
				false,
				"Such post-transcriptional modification is not the first step in protein synthesis.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334317;


		
		

		
			
			p.question = "Which organelle plays a role in intracellular digestion? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?6&F','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Endomembrane System</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "lysosome",
				true,
				"The prefix \"lyso-\" means decomposition.");
			
				p.addAnswer(2, "ribosome",
				false,
				"Ribosomes are involved in protein synthesis.");
			
				p.addAnswer(3, "chloroplast",
				false,
				"Chloroplasts are involved in photosynthesis.");
			
				p.addAnswer(4, "Golgi apparatus",
				false,
				"The Golgi apparatus modifies and transports proteins.");
			
				p.addAnswer(5, "plasmodesma",
				false,
				"Plasmodesmata are a type of cell junction.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334318;


		
		

		
			
			p.question = "The cilia and flagella of eukaryotic cells are composed of _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?6&H','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Cilia and Flagella</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "microtubules",
				true,
				"Eukaryotic cilia and flagella are composed of microtubules.");
			
				p.addAnswer(2, "intermediate filaments",
				false,
				"Cilia and flagella are not composed of intermediate filaments.");
			
				p.addAnswer(3, "microfilaments",
				false,
				"Cilia and flagella are not composed of microfilaments.");
			
				p.addAnswer(4, "pili",
				false,
				"Cilia and flagella are not composed of pili.");
			
				p.addAnswer(5, "tonofilaments",
				false,
				"Cilia and flagella are not composed of tonofilaments.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334319;


		
		

		
			
			p.question = "Which of these cell junctions form a barrier to the passage of materials? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?6&I','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Cell Junctions</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "tight junctions",
				true,
				"Tight junctions form a barrier that prevents fluids from moving between cells.");
			
				p.addAnswer(2, "gap (communicating) junctions",
				false,
				"Consider what \"communicating\" means.");
			
				p.addAnswer(3, "desmosomes (anchoring junctions)",
				false,
				"Desmosomes do not form a barrier to the passage of fluid.");
			
				p.addAnswer(4, "keratin fibers",
				false,
				"Keratin fibers are used to anchor cells to one another.");
			
				p.addAnswer(5, "plasmodesmata",
				false,
				"Plasmodesmata do not form a barrier to the passage of fluid.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334320;


		
		

		
			
			p.question = "The primary role of _____ is to bind animal cells together. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?6&I','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Cell Junctions</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "plasmodesmata",
				false,
				"Plasmodesmata are not found in animals.");
			
				p.addAnswer(2, "gap (communicating) junctions",
				false,
				"The primary role of gap (communicating) junctions is cell-to-cell communication.");
			
				p.addAnswer(3, "the cytoskeleton",
				false,
				"The cytoskeleton is a network of fibers that organizes the structures and activities within a cell.");
			
				p.addAnswer(4, "desmosomes",
				true,
				"The primary role of desmosomes (anchoring junctions) is to bind cells together.");
			
				p.addAnswer(5, "tight junctions",
				false,
				"The primary role of tight junctions is to form a barrier that prevents fluids from moving between cells.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334321;


		
		

		
			
			p.question = "_____ aid in the coordination of the activities of adjacent animal cells. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?6&I','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Cell Junctions</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Gap (communicating) junctions",
				true,
				"Gap junctions allow for the passage of material between cells, thus facilitating communication between these cells.");
			
				p.addAnswer(2, "Tight junctions",
				false,
				"Tight junctions form a barrier to the movement of fluid.");
			
				p.addAnswer(3, "Keratin fibers",
				false,
				"Keratin fibers are used to anchor cells to one another.");
			
				p.addAnswer(4, "Plasmodesmata",
				false,
				"Plasmodesmata are not found in animals.");
			
				p.addAnswer(5, "Desmosomes",
				false,
				"Desmosomes (anchoring junctions) join cells.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334322;


		
		

		
			
			p.question = "Choose the letter that indicates the organelle that contains most of a cell\'s DNA. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?6&J','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Review: Animal Cell Structure and Function</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0610q.jpg\" ALT=\"Question #10\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A",
				false,
				"Lysosomes do not contain DNA.");
			
				p.addAnswer(2, "B",
				false,
				"Peroxisomes do not contain DNA.");
			
				p.addAnswer(3, "C",
				true,
				"The nucleus contains most of a cell\'s DNA.");
			
				p.addAnswer(4, "D",
				false,
				"The Golgi apparatus does not contain DNA.");
			
				p.addAnswer(5, "E",
				false,
				"Ribsosomes do not contain DNA.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334323;


		
		

		
			
			p.question = "Which of these organelles carries out cellular respiration? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?6&J','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Review: Animal Cell Structure and Function</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "nucleolus",
				false,
				"The nucleolus is an organelle found within the nucleus.");
			
				p.addAnswer(2, "chromatin",
				false,
				"Chromatin is found within the nucleus.");
			
				p.addAnswer(3, "smooth endoplasmic reticulum",
				false,
				"The smooth ER is a component of the endomembrane system.");
			
				p.addAnswer(4, "mitochondrion",
				true,
				"Mitochondria convert the chemical energy of organic molecules to chemical energy in the form of ATP.");
			
				p.addAnswer(5, "ribosomes",
				false,
				"Ribosomes do not carry out cellular respiration.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334324;


		
		

		
			
			p.question = "Which of these is the double membrane that encloses the nucleus? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?6&J','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Review: Animal Cell Structure and Function</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0612q.jpg\" ALT=\"Question #12\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A",
				false,
				"The plasma membrane is a double membrane that encloses the entire cell.");
			
				p.addAnswer(2, "B",
				false,
				"However, two membranes surround a mitochondrion.");
			
				p.addAnswer(3, "C",
				false,
				"The nucleolus is an organelle found within the nucleus.");
			
				p.addAnswer(4, "D",
				false,
				"This indicates the nucleus.");
			
				p.addAnswer(5, "E",
				true,
				"This is the nuclear envelope.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334325;


		
		

		
			
			p.question = "The _____ is composed of DNA and protein. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?6&J','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Review: Animal Cell Structure and Function</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "mitochondrion",
				false,
				"However, mitochondria do contain DNA.");
			
				p.addAnswer(2, "flagellum",
				false,
				"Flagella are composed of microtubules.");
			
				p.addAnswer(3, "centriole",
				false,
				"Centrioles are composed of microtubules.");
			
				p.addAnswer(4, "chromatin",
				true,
				"Chromatin is composed of DNA and protein.");
			
				p.addAnswer(5, "ribosome",
				false,
				"Ribsosomes are composed of RNA and protein.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334326;


		
		

		
			
			p.question = "Ribosomal subunits are manufactured by the _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?6&J','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Review: Animal Cell Structure and Function</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "lysosome",
				false,
				"Consider the meaning of the prefix \"lyso-.\"");
			
				p.addAnswer(2, "nucleolus",
				true,
				"Ribosomes are manufactured by the nucleolus.");
			
				p.addAnswer(3, "peroxisome",
				false,
				"Peroxisomes do not manufacture ribosomal subunits.");
			
				p.addAnswer(4, "rough endoplasmic reticulum",
				false,
				"However, the rough ER is studded with ribosomes.");
			
				p.addAnswer(5, "smooth endoplasmic reticulum",
				false,
				"The smooth ER does not manufacture ribosomal subunits.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334327;


		
		

		
			
			p.question = "_____ are the sites of protein synthesis. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?6&J','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Review: Animal Cell Structure and Function</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Mitochondria",
				false,
				"Mitochondria are involved in cellular respiration.");
			
				p.addAnswer(2, "Peroxisomes",
				false,
				"Peroxisomes do not synthesize proteins.");
			
				p.addAnswer(3, "Golgi apparatuses",
				false,
				"However, the Golgi apparatus does modify and package proteins.");
			
				p.addAnswer(4, "Microfilaments",
				false,
				"Microfilaments are a component of the cytoskeleton.");
			
				p.addAnswer(5, "Ribosomes",
				true,
				"Ribosomes are the site of protein synthesis.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334328;


		
		

		
			
			p.question = "Which of these is involved in the manufacture of membrane? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?6&J','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Review: Animal Cell Structure and Function</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "smooth endoplasmic reticulum",
				false,
				"Membrane manufacture is not a function of the smooth ER.");
			
				p.addAnswer(2, "ribosomes",
				false,
				"Ribosomes manufacture protein.");
			
				p.addAnswer(3, "Golgi apparatus",
				false,
				"While it is composed of membrane, the Golgi apparatus does not manufacture membrane.");
			
				p.addAnswer(4, "nucleolus",
				false,
				"The nucleolus manufactures ribosomal subunits.");
			
				p.addAnswer(5, "rough endoplasmic reticulum",
				true,
				"The rough ER is where membrane is manufactured.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334329;


		
		

		
			
			p.question = "The _____ is a selective barrier, regulating the passage of material into and out of the cell. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?6&J','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Review: Animal Cell Structure and Function</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "lysosome",
				false,
				"The lysosome plays a role in intracellular digestion.");
			
				p.addAnswer(2, "nuclear envelope",
				false,
				"The nuclear envelope does not surround the cell.");
			
				p.addAnswer(3, "chloroplast",
				false,
				"The chloroplast is the site of photosynthesis.");
			
				p.addAnswer(4, "plasma membrane",
				true,
				"The plasma membrane regulates the passage of material into and out of the cell.");
			
				p.addAnswer(5, "nucleus",
				false,
				"The nucleus does not form a selective barrier.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334330;


		
		

		
			
			p.question = "Where is calcium stored? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?6&J','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Review: Animal Cell Structure and Function</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "mitochondria",
				false,
				"Mitochondria are not a component of the endomembrane system.");
			
				p.addAnswer(2, "smooth endoplasmic reticulum",
				true,
				"In addition to storing calcium, the smooth ER also plays a role in detoxification and lipid synthesis.");
			
				p.addAnswer(3, "centrioles",
				false,
				"Centrioles are not a component of the endomembrane system.");
			
				p.addAnswer(4, "rough endoplasmic reticulum",
				false,
				"While a component of the endomembrane system, the rough ER does not store calcium.");
			
				p.addAnswer(5, "microtubules",
				false,
				"Microtubules are not a component of the endomembrane system.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334331;


		
		

		
			
			p.question = "Which of these structures stores, modifies, and packages products? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?6&J','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Review: Animal Cell Structure and Function</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0619q.jpg\" ALT=\"Question #19\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A",
				true,
				"The Golgi apparatus modifies, stores, and packages products of the ER.");
			
				p.addAnswer(2, "B",
				false,
				"Microfilaments are a component of the cytoskeleton.");
			
				p.addAnswer(3, "C",
				false,
				"Lysosomes are involved in intracellular digestion.");
			
				p.addAnswer(4, "D",
				false,
				"This is the rough ER.");
			
				p.addAnswer(5, "E",
				false,
				"This is the smooth ER.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334332;


		
		

		
			
			p.question = "Which of these are hollow rods that shape and support the cell? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?6&J','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Review: Animal Cell Structure and Function</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "plasma membrane",
				false,
				"The plasma membrane regulates the passage of material into and out of the cell.");
			
				p.addAnswer(2, "microtubules",
				true,
				"Microtubules are rods that also play a role in organelle movement.");
			
				p.addAnswer(3, "chloroplasts",
				false,
				"Chloroplasts are not hollow rods.");
			
				p.addAnswer(4, "microfilaments",
				false,
				"Microfilaments are not hollow.");
			
				p.addAnswer(5, "peroxisomes",
				false,
				"Peroxisomes are membranous sacs.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334333;


		
		

		
			
			p.question = "_____ is/are identical in structure to centrioles. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?6&J','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Review: Animal Cell Structure and Function</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Mitochondria",
				false,
				"Mitochondria are not composed of microtubules.");
			
				p.addAnswer(2, "Nuclear envelopes",
				false,
				"Nuclear envelopes are composed of membrane.");
			
				p.addAnswer(3, "Chromatin",
				false,
				"Chromatin is composed of DNA and protein.");
			
				p.addAnswer(4, "Microfilaments",
				false,
				"Centrioles are not composed of microtubules.");
			
				p.addAnswer(5, "Basal bodies",
				true,
				"Basal bodies and centrioles have identical structures.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334334;


		
		

		
			
			p.question = "Which of these organelles produces H<sub>2</sub>O<sub>2</sub> as a by-product? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?6&J','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Review: Animal Cell Structure and Function</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "mitochondrion",
				false,
				"Mitochondria do not produce H<sub>2</sub>O<sub>2</sub>.");
			
				p.addAnswer(2, "nucleus",
				false,
				"The nucleus contains the genetic material and nucleoli.");
			
				p.addAnswer(3, "centrioles",
				false,
				"Centrioles do not produce H<sub>2</sub>O<sub>2</sub>.");
			
				p.addAnswer(4, "flagellum",
				false,
				"Flagella do not produce H<sub>2</sub>O<sub>2</sub>.");
			
				p.addAnswer(5, "peroxisome",
				true,
				"Peroxisomes produce hydrogen peroxide as a by-product of their metabolic processes.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334335;


		
		

		
			
			p.question = "Which of these provides the cell with structural support? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?6&J','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Review: Animal Cell Structure and Function</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0623q.jpg\" ALT=\"Question #23\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A",
				false,
				"Flagella do not play a role in structural support.");
			
				p.addAnswer(2, "B",
				false,
				"The rough endoplasmic reticulum does not physically support the cell.");
			
				p.addAnswer(3, "C",
				false,
				"Ribosomes manufacture protein.");
			
				p.addAnswer(4, "D",
				true,
				"Microfilaments are a component of the cytoskeleton.");
			
				p.addAnswer(5, "E",
				false,
				"Lysosomes are involved in intracellular digestion.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334336;


		
		

		
			
			p.question = "Which of these organelles is responsible for photosynthesis? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?6&J','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Review: Animal Cell Structure and Function</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0624q.jpg\" ALT=\"Question #24\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A",
				false,
				"Mitochondria do not contain chlorophyll.");
			
				p.addAnswer(2, "B",
				false,
				"The central vacuole does not contain chlorophyll.");
			
				p.addAnswer(3, "C",
				false,
				"Plasmodesmata are cell junctions.");
			
				p.addAnswer(4, "D",
				true,
				"In eukaryotic cells, chloroplasts are the site of photosynthesis.");
			
				p.addAnswer(5, "E",
				false,
				"Chromatin is composed of DNA and protein.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

