

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "GraphIt! Quiz > GraphIt! Quiz > An Introduction to Graphing";
	ak.quiz_loc_with_commas = "GraphIt! Quiz, GraphIt! Quiz, An Introduction to Graphing";
	ak.quiz_title = "An Introduction to Graphing";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 14;
	ak.non_essay_total = 14;
	ak.scored_item_total = 14;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337420;


		
		

		
			
			p.question = "For the graph of data on stem density and snowshoe hare density, which statement best summarizes the trend shown in the graph?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The density of hares increases as the density of stems increases.",
				true,
				"");
			
				p.addAnswer(2, "The density of stems decreases as hare density increases.",
				false,
				"");
			
				p.addAnswer(3, "There appears to be no relationship between stem density and hare density.",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337421;


		
		

		
			
			p.question = "As stem density increases from about 35 stems to about 55 stems per hectare, what is the increase in snowshoe hare density?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "1 hare per hectare",
				true,
				"");
			
				p.addAnswer(2, "5 hares per hectare",
				false,
				"");
			
				p.addAnswer(3, "0.2 hares per hectare",
				false,
				"");
			
				p.addAnswer(4, "1000 hares per hectare",
				false,
				"");
			
				p.addAnswer(5, "0 hares per hectare",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- truefalse ------------
		//
		
			p = new Problem("truefalse");
		
		p.id = 337422;


		
		

		
			
			p.question = "Increasing density of tree and bush stems has a positive effect on snowshoe hare abundance.";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			
				
				p.addAnswer(1, "True", true, "");
				
			
				
				p.addAnswer(2, "False", false, "");
				
				

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- truefalse ------------
		//
		
			p = new Problem("truefalse");
		
		p.id = 337423;


		
		

		
			
			p.question = "Areas with more than 100 stems per hectare should have hare densities approaching 4 hares per hectare.";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			
				
				p.addAnswer(1, "True", false, "");
				
			
				
				p.addAnswer(2, "False", true, "");
				
				

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- truefalse ------------
		//
		
			p = new Problem("truefalse");
		
		p.id = 337424;


		
		

		
			
			p.question = "Greater abundance of tree and bush stems results in higher birth rates for snowshoe hares.";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			
				
				p.addAnswer(1, "True", false, "");
				
			
				
				p.addAnswer(2, "False", true, "");
				
				

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337425;


		
		

		
			
			p.question = "For the graph showing fish body lengths and the percentage of tern diets that they comprise, which statement best summarizes the trend shown in the graph?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The sooty tern\'s diet is composed mostly of smaller fish and the blue-grey noddy\'s diet is composed mostly of moderate to large fish.",
				false,
				"");
			
				p.addAnswer(2, "The blue-grey noddy\'s diet is composed primarily of smaller fish and the sooty tern\'s diet is composed mostly of moderate sized fish.",
				true,
				"");
			
				p.addAnswer(3, "The blue-grey noddy tern and the sooty tern have identical diets with respect to fish size.",
				false,
				"");
			
				p.addAnswer(4, "There is no overlap in the diets of the two species with respect to fish size.",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337426;


		
		

		
			
			p.question = "For what sizes of fish is there the least amount of overlap in the diets of these two tern species?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "greater than 6 cm",
				true,
				"");
			
				p.addAnswer(2, "0-2 cm",
				false,
				"");
			
				p.addAnswer(3, "less than 6 cm",
				false,
				"");
			
				p.addAnswer(4, "4-6 cm",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- truefalse ------------
		//
		
			p = new Problem("truefalse");
		
		p.id = 337427;


		
		

		
			
			p.question = "For the sooty tern, there is a steady decrease in the percent of diet as fish length decreases from 6 cm to 0 cm.";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			
				
				p.addAnswer(1, "True", false, "");
				
			
				
				p.addAnswer(2, "False", true, "");
				
				

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- truefalse ------------
		//
		
			p = new Problem("truefalse");
		
		p.id = 337428;


		
		

		
			
			p.question = "The sooty tern consumes more fish than the blue-grey noddy tern.";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			
				
				p.addAnswer(1, "True", false, "");
				
			
				
				p.addAnswer(2, "False", true, "");
				
				

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- truefalse ------------
		//
		
			p = new Problem("truefalse");
		
		p.id = 337429;


		
		

		
			
			p.question = "Even though they live in the same location, these two species probably experience minimal competition for food.";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			
				
				p.addAnswer(1, "True", true, "");
				
			
				
				p.addAnswer(2, "False", false, "");
				
				

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- truefalse ------------
		//
		
			p = new Problem("truefalse");
		
		p.id = 337430;


		
		

		
			
			p.question = "Since the points don\'t form a straight line, it would have been better to draw this as a scatter plot.";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			
				
				p.addAnswer(1, "True", false, "");
				
			
				
				p.addAnswer(2, "False", true, "");
				
				

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- truefalse ------------
		//
		
			p = new Problem("truefalse");
		
		p.id = 337431;


		
		

		
			
			p.question = "It would have been reasonable to place stream flow on the X-axis instead of year.";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			
				
				p.addAnswer(1, "True", false, "");
				
			
				
				p.addAnswer(2, "False", true, "");
				
				

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- truefalse ------------
		//
		
			p = new Problem("truefalse");
		
		p.id = 337432;


		
		

		
			
			p.question = "Stream flow rates have apparently been decreasing worldwide since 1966.";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			
				
				p.addAnswer(1, "True", false, "");
				
			
				
				p.addAnswer(2, "False", true, "");
				
				

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 337433;


		
		

		
			
			p.question = "Between 1966 and 1995, what has been the approximate decrease in stream flow rates in Monteverde?";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 0;
			p.correct_expls_flag = 0;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "1.2 m<sup>3</sup>/sec",
				false,
				"");
			
				p.addAnswer(2, "There has been no observable change.",
				false,
				"");
			
				p.addAnswer(3, "0.8 m<sup>3</sup>/sec",
				true,
				"");
			
				p.addAnswer(4, "1.7 m<sup>3</sup>/sec",
				false,
				"");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

