

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "27: Bacteria and Archaea > Activities Quiz";
	ak.quiz_loc_with_commas = "27: Bacteria and Archaea, Activities Quiz";
	ak.quiz_title = "Activities Quiz";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 15;
	ak.non_essay_total = 15;
	ak.scored_item_total = 15;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335626;


		
		

		
			
			p.question = "The DNA-containing region of this bacterial cell is indicated by the letter _____.  (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?6&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Prokaryotic Cell Structure and Function</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/2701q.jpg\" ALT=\"Question #1\" BORDER=\"1\" >";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A",
				false,
				"This is the capsule.");
			
				p.addAnswer(2, "B",
				false,
				"These are pili.");
			
				p.addAnswer(3, "C",
				false,
				"This is the plasma membrane.");
			
				p.addAnswer(4, "D",
				true,
				"The nucleoid region contains DNA.");
			
				p.addAnswer(5, "E",
				false,
				"This is a flagellum.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335627;


		
		

		
			
			p.question = "_____ are surface appendages that allow a bacterium to stick to a surface. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?6&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Prokaryotic Cell Structure and Function</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Cell walls",
				false,
				"The cell wall is a protective structure that surrounds a bacterium.");
			
				p.addAnswer(2, "Flagella",
				false,
				"Flagella play a role in locomotion.");
			
				p.addAnswer(3, "Ribosomes",
				false,
				"Ribosomes are involved in polypeptide (protein) synthesis.");
			
				p.addAnswer(4, "Mitochondria",
				false,
				"Bacteria do not posses mitochondria.");
			
				p.addAnswer(5, "Pili",
				true,
				"Pili enable bacterial cells to stick to a surface.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335628;


		
		

		
			
			p.question = "What is the function of a bacterium\'s capsule? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?6&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Prokaryotic Cell Structure and Function</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "protection",
				true,
				"A bacterium\'s capsule has a protective role.");
			
				p.addAnswer(2, "adhesion",
				false,
				"Pili play a role in adhesion.");
			
				p.addAnswer(3, "protein synthesis",
				false,
				"This is the function of ribosomes.");
			
				p.addAnswer(4, "DNA containment",
				false,
				"The nucleoid region contains a bacterium\'s DNA.");
			
				p.addAnswer(5, "propulsion",
				false,
				"Flagella propel bacterial cells.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335629;


		
		

		
			
			p.question = "Where is a bacterial cell\'s DNA found? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?6&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Prokaryotic Cell Structure and Function</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "ribosomes",
				false,
				"Ribosomes are involved in the manufacture of polypeptides (proteins).");
			
				p.addAnswer(2, "nucleus",
				false,
				"Bacterial cells do not have a nucleus.");
			
				p.addAnswer(3, "peroxisome",
				false,
				"Bacterial cells do not have peroxisomes.");
			
				p.addAnswer(4, "nucleoid region",
				true,
				"Bacteria lack a nucleus; their DNA is found in the nucleoid region.");
			
				p.addAnswer(5, "capsule",
				false,
				"The capsule is a protective layer that surrounds a bacterial cell.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335630;


		
		

		
			
			p.question = "In a bacterium, where are proteins synthesized? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?6&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Prokaryotic Cell Structure and Function</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "ribosomes",
				true,
				"Ribosomes are involved in the manufacture of polypeptides (proteins).");
			
				p.addAnswer(2, "nucleus",
				false,
				"Bacterial cells do not have a nucleus.");
			
				p.addAnswer(3, "peroxisome",
				false,
				"Bacterial cells do not have peroxisomes.");
			
				p.addAnswer(4, "nucleoid region",
				false,
				"Bacterial DNA is found in the nucleoid region.");
			
				p.addAnswer(5, "capsule",
				false,
				"The capsule is a protective layer that surrounds a bacterial cell.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335631;


		
		

		
			
			p.question = "What name is given to the rigid structure, found outside the plasma membrane, that surrounds and supports the bacterial cell? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?6&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Prokaryotic Cell Structure and Function</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "capsule",
				false,
				"The capsule is not rigid.");
			
				p.addAnswer(2, "pili",
				false,
				"Pili play a role in adhesion.");
			
				p.addAnswer(3, "cell wall",
				true,
				"The cell wall is a rigid supporting structure.");
			
				p.addAnswer(4, "flagella",
				false,
				"Flagella propel bacterial cells.");
			
				p.addAnswer(5, "nucleoid region",
				false,
				"Bacterial DNA is found in the nucleoid region.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335632;


		
		

		
			
			p.question = "The _____ is the bacterial structure that acts as a selective barrier, allowing nutrients to enter the cell and wastes to leave the cell. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?6&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Prokaryotic Cell Structure and Function</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "plasma membrane",
				true,
				"The plasma membrane is selectively permeable.");
			
				p.addAnswer(2, "nucleoid region",
				false,
				"Bacterial DNA is found in the nucleoid region.");
			
				p.addAnswer(3, "ribosome",
				false,
				"Ribosomes are the site of polypeptide (protein) synthesis.");
			
				p.addAnswer(4, "pili",
				false,
				"Pili play a role in adhesion.");
			
				p.addAnswer(5, "cell wall",
				false,
				"The cell wall is a rigid supporting structure.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335633;


		
		

		
			
			p.question = "The structure that regulates the passage of material into and out of this bacterial cell is indicated by the letter _____.  (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?6&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Prokaryotic Cell Structure and Function</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/2708q.jpg\" ALT=\"Question #8\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A",
				false,
				"This is the capsule.");
			
				p.addAnswer(2, "B",
				false,
				"These are pili.");
			
				p.addAnswer(3, "C",
				true,
				"The plasma membrane is selectively permeable.");
			
				p.addAnswer(4, "D",
				false,
				"The nucleoid region contains DNA.");
			
				p.addAnswer(5, "E",
				false,
				"This is a flagellum.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335634;


		
		

		
			
			p.question = "The prokaryotic cells that built stromatolites are classified as _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?27&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Classification of Prokaryotes</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "proteobacteria",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(2, "chlamydias",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(3, "spirochetes",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(4, "gram-positive bacteria",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(5, "cyanobacteria",
				true,
				"Cyanobacteria built stromatolites.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335635;


		
		

		
			
			p.question = "The prokaryotic cells that were the first to add significant quantities of oxygen to Earth\'s atmosphere are classified as _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?27&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Classification of Prokaryotes</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "proteobacteria",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(2, "chlamydias",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(3, "spirochetes",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(4, "gram-positive bacteria",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(5, "cyanobacteria",
				true,
				"Cyanobacteria are aerobic photosynthesizers.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335636;


		
		

		
			
			p.question = "<i>Streptococcus aureus</i> is classified with _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?27&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Classification of Prokaryotes</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "proteobacteria",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(2, "chlamydias",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(3, "spirochetes",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(4, "gram-positive bacteria",
				true,
				"<i>S. aureus</i> attracts the violet Gram stain.");
			
				p.addAnswer(5, "cyanobacteria",
				false,
				"No, that is incorrect.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335637;


		
		

		
			
			p.question = "Organisms that can cause nongonococcal urethritis are classified with _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?27&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Classification of Prokaryotes</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "proteobacteria",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(2, "chlamydias",
				true,
				"<i>Chlamydia trachomatis</i> causes nongonococcal urethritis.");
			
				p.addAnswer(3, "spirochetes",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(4, "gram-positive bacteria",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(5, "cyanobacteria",
				false,
				"No, that is incorrect.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335638;


		
		

		
			
			p.question = "The chemoheterotroph <i>Proteus vulgaris</i> is a rod-shaped bacterium classified with _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?27&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Classification of Prokaryotes</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "proteobacteria",
				true,
				"<i>Proteus vulgaris</i> is classified with proteobacteria.");
			
				p.addAnswer(2, "chlamydias",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(3, "spirochetes",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(4, "gram-positive bacteria",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(5, "cyanobacteria",
				false,
				"No, that is incorrect.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335639;


		
		

		
			
			p.question = "Spiral-shaped bacteria are likely to be placed with _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?27&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Classification of Prokaryotes</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "proteobacteria",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(2, "chlamydias",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(3, "spirochetes",
				true,
				"The name of these organisms provides the answer to the question.");
			
				p.addAnswer(4, "gram-positive bacteria",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(5, "cyanobacteria",
				false,
				"No, that is incorrect.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335640;


		
		

		
			
			p.question = "Which of these pairs of prokaryotic subgroups share the most recent common ancestor? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?27&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Classification of Prokaryotes</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/2715q.jpg\" ALT=\"Question #15\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Euryarchaeota ... Cyanobacteria",
				false,
				"These subgroups are in two different domains.");
			
				p.addAnswer(2, "Proteobacteria ... Crenarchaeota",
				false,
				"According to the phylogenetic tree these are the most distantly related of the pairings.");
			
				p.addAnswer(3, "Proteobacteria ... Euryarchaeota",
				false,
				"These subgroups are in two different domains.");
			
				p.addAnswer(4, "Euryarchaeota ... Crenarchaeota",
				true,
				"The branching pattern of the phylogenetic tree indicates that, of the pairs listed here, this is the one whose members are the most closely related.");
			
				p.addAnswer(5, "Crenarchaeota ... Cyanobacteria",
				false,
				"These subgroups are in two different domains.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

