

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "42: Circulation and Gas Exchange > Practice Test";
	ak.quiz_loc_with_commas = "42: Circulation and Gas Exchange, Practice Test";
	ak.quiz_title = "Practice Test";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 43;
	ak.non_essay_total = 43;
	ak.scored_item_total = 43;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336434;


		
		

		
			
			p.question = "Which type of epithelial tissue would you suppose covers the gills of axolotls? (<script type=\"text/javascript\">ebook(\'42OV\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "stratified squamous epithelium",
				false,
				"No. Stratified means having multiple layers of cells. It would not be thin. This type of tissue forms a protective barrier in high-abrasion areas.");
			
				p.addAnswer(2, "simple columnar epithelium",
				false,
				"No. Columnar cells are tall and thin. This type of tissue is generally secretory as well as absorptive and is not a part of the alveoli.");
			
				p.addAnswer(3, "simple squamous epithelium",
				true,
				"Correct. Simple means \"one-cell thick\" and squamous means \"flat cell.\" A respiratory surface needs to be a thin, moist epithelium.");
			
				p.addAnswer(4, "stratified cuboidal epithelium",
				false,
				"No. These cells are box-like. This tissue would be too thick for alveolar epithelia, where rapid diffusion needs to occur.");
			
				p.addAnswer(5, "stratified columnar epithelium",
				false,
				"No. This epithelium would be too thick. Alveolar epithelia need to be much thinner to accommodate the rapid diffusion of gases.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336435;


		
		

		
			
			p.question = "Which of the following is a function of the circulatory system? (<script type=\"text/javascript\">ebook(\'42OV\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "producing mucus",
				false,
				"No. Mucus is produced by specialized epithelial cells. By transporting fluid throughout the body, the circulatory system functionally connects the aqueous environment of the body cells to the organs that exchange gases, absorb nutrients, and dispose of wastes.");
			
				p.addAnswer(2, "transporting nutrients",
				true,
				"Correct. The circulatory system transports nutrients such as glucose.");
			
				p.addAnswer(3, "eliminating hormones",
				false,
				"No. The circulatory system transports hormones throughout the body, working closely with endocrine organs.");
			
				p.addAnswer(4, "producing wastes",
				false,
				"No. The circulatory system transports nitrogenous waste and carbon dioxide. It does not produce them.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. Only one of the choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336436;


		
		

		
			
			p.question = "An open circulatory system _____. (<script type=\"text/javascript\">ebook(\'4201\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "is less common in crabs and beetles than in mice and snakes",
				false,
				"No. All arthropods have an open circulatory system, and all vertebrates have a closed circulatory system.");
			
				p.addAnswer(2, "does not rely on muscle contraction",
				false,
				"No. Both contractions of the tubular heart and contractions of body muscles move blood in an open circulatory system.");
			
				p.addAnswer(3, "allows interstitial fluid to mix freely with vascular fluid",
				true,
				"Correct. In animals with an open circulatory system, the vascular fluid also functions as the interstitial fluid.");
			
				p.addAnswer(4, "restricts the backflow of blood by valves in the trachea",
				false,
				"No. The trachea is a tube that carries atmospheric gases to the animal\'s respiratory surface; blood does not flow through it.");
			
				p.addAnswer(5, "has no valves",
				false,
				"No. The pores that allow reentry of blood into the tubular heart have valves that prevent backflow and force blood to leave from small vessels.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336437;


		
		

		
			
			p.question = "Why do larger animals, like a bullfrog, require a circulatory system, but animals such as a planarian do not? (<script type=\"text/javascript\">ebook(\'4201\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Each cell in a bullfrog requires more oxygen and nutrients than each cell in a planarian.",
				false,
				"No. The size of the animal does not change the needs of its cells.");
			
				p.addAnswer(2, "The cells of a bullfrog are many times larger than the cells of a planarian.",
				false,
				"No. The cells of each type of animal are about the same size.");
			
				p.addAnswer(3, "Diffusion is inadequate to move gases through the surface and into all parts of a larger animal body. However, diffusion alone is sufficient to move gases in and out of the thin body of a planarian.",
				true,
				"Correct.");
			
				p.addAnswer(4, "Gases do not diffuse through bone. Therefore, any animal with bones, such as a bullfrog, has to have a circulatory system. Any animal without bones, such as a planarian, does not have a circulatory system.",
				false,
				"No. Gases can diffuse through bone, although this occurs slowly. However, this is not the reason that larger animals need a circulatory system.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336438;


		
		

		
			
			p.question = "In which animal does the circulatory system include a heart and a system of closed vessels? (<script type=\"text/javascript\">ebook(\'4201\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "sea anemone",
				false,
				"No. The sea anemone has a highly branched gastrovascular cavity lined with flagella, which serve to circulate fluids within the cavity.");
			
				p.addAnswer(2, "sponge",
				false,
				"No. Sponges do not have a circulatory system or true tissues.");
			
				p.addAnswer(3, "fish",
				true,
				"Correct. The fish is a vertebrate; all vertebrates have a closed circulatory system.");
			
				p.addAnswer(4, "beetle",
				false,
				"No. All insects have an open circulatory system.");
			
				p.addAnswer(5, "crayfish",
				false,
				"No. All arthropods have an open circulatory system.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336439;


		
		

		
			
			p.question = "The function of pulmonary circulation in a dog is to _____. (<script type=\"text/javascript\">ebook(\'4201\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "carry oxygen and nutrients to tissues where they are needed",
				false,
				"No. This is the function of the systemic circulation.");
			
				p.addAnswer(2, "retrieve waste products from the body tissues",
				false,
				"No. This is the function of the systemic circulation.");
			
				p.addAnswer(3, "carry blood through the heart, lungs, and all of the body tissues",
				false,
				"No. This is accomplished by the entire circulatory system.");
			
				p.addAnswer(4, "carry carbon dioxide to the lungs and pick up oxygen from the lungs",
				true,
				"Correct. As blood flows through the capillary beds in the lungs, oxygen is absorbed into the blood and carbon dioxide is released into the lungs.");
			
				p.addAnswer(5, "carry absorbed nutrients from the small intestine to the liver",
				false,
				"No. The hepatic portal system carries absorbed nutrients from the digestive tract to the liver.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336440;


		
		

		
			
			p.question = "In a fish, blood circulates through ____, whereas in a mammal, it circulates through ____. (<script type=\"text/javascript\">ebook(\'4201\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "two circuits; four circuits",
				false,
				"No. At most, two circuits would be required. One circuit is required for the pulmonary circulation, and one circuit is required for the systemic circulation.");
			
				p.addAnswer(2, "one circuit; two circuits",
				true,
				"Correct. Fish have a single circuit that utilizes one atrium and one ventricle, whereas the mammalian heart has a double circuit.");
			
				p.addAnswer(3, "four circuits; two circuits",
				false,
				"No. Mammals do have two circuits, but fish only have one.");
			
				p.addAnswer(4, "one circuit; four circuits",
				false,
				"No. Fish only have one circuit, but mammals have two.");
			
				p.addAnswer(5, "two circuits; one circuit",
				false,
				"No. For each circuit, an atrium and a ventricle are necessary. How many ventricles does a fish heart have?");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336441;


		
		

		
			
			p.question = "Which of the following is an example of a portal vein? (<script type=\"text/javascript\">ebook(\'4201\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a blood vessel carrying blood from the stomach to the liver",
				true,
				"Correct. portal veins carry blood between pairs of capillary beds outside of the heart and lungs.");
			
				p.addAnswer(2, "the blood vessel carrying blood from the heart to the lungs",
				false,
				"No. This would be part of the pulmonary circuit. Further, this would be an artery, not a vein, because it is carrying blood away from the heart.");
			
				p.addAnswer(3, "the blood vessel carrying blood from the lungs to the heart",
				false,
				"No. This would be part of the pulmonary circuit.");
			
				p.addAnswer(4, "a blood vessel carrying blood from the major muscles of the lower leg back to the heart",
				false,
				"No. Because it involves the heart, it is not a portal vein");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336442;


		
		

		
			
			p.question = "All known birds and mammals have _____. (<script type=\"text/javascript\">ebook(\'4201\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a double circulatory system and a four-chambered heart",
				true,
				"Correct.");
			
				p.addAnswer(2, "a single circulatory system and a four-chambered heart",
				false,
				"No. A four-chambered heart separates the blood flow into a double circulatory system.");
			
				p.addAnswer(3, "a double circulatory system and a three-chambered heart",
				false,
				"No. Birds and mammals have four-chambered hearts.");
			
				p.addAnswer(4, "a double circulatory system and a two-chambered heart",
				false,
				"No. Birds and mammals have four-chambered hearts.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336443;


		
		

		
			
			p.question = "What is unique about blood in pulmonary arteries compared with blood in other arteries? (<script type=\"text/javascript\">ebook(\'4202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Blood in pulmonary arteries is always blue; it is red in all other arteries.",
				false,
				"No. The colors red and blue are often used in textbooks to indicate oxygenated and deoxygenated blood. The blood itself doesn\'t change from red to blue.");
			
				p.addAnswer(2, "It is moving away from the heart.",
				false,
				"No. Blood in all arteries is propelled away from the heart when the ventricles contract.");
			
				p.addAnswer(3, "It is moving toward the heart.",
				false,
				"No. An artery is defined as a vessel that carries blood away from the heart.");
			
				p.addAnswer(4, "It is the same as blood in other arteries.",
				false,
				"No. There is something about the composition of the blood in the pulmonary arteries that sets it apart from blood in other arteries.");
			
				p.addAnswer(5, "It is loaded with carbon dioxide.",
				true,
				"Correct. The blood in pulmonary arteries has not yet delivered its load of carbon dioxide to the lungs, and conversely, it is the only arterial blood that is not described as oxygenated.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336444;


		
		

		
			
			p.question = "Which chambers of a human heart receive and pump oxygenated blood? (<script type=\"text/javascript\">ebook(\'4202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "left ventricle and left atrium",
				true,
				"Correct. The left side of the heart receives oxygenated blood from the lungs and pumps it into the aorta for further distribution to the body.");
			
				p.addAnswer(2, "both left and right atria",
				false,
				"No. The right atrium receives deoxygenated blood from the veins.");
			
				p.addAnswer(3, "left atrium only",
				false,
				"No. The left atrium receives oxygenated blood from the lungs, but where does the blood go next before being propelled out of the aorta?");
			
				p.addAnswer(4, "right atrium and right ventricle",
				false,
				"No. The right atrium receives deoxygenated blood from the veins and passes it into the right ventricle for delivery to the lungs, where it is oxygenated.");
			
				p.addAnswer(5, "right atrium only",
				false,
				"No. The right atrium is the heart\'s intake chamber for deoxygenated blood arriving through veins from the capillary beds of the body.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336445;


		
		

		
			
			p.question = "Where does blood go directly after it leaves the inferior (posterior) vena cava? (<script type=\"text/javascript\">ebook(\'4202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "into the capillaries of the upper body",
				false,
				"No. The vena cava is a large vein; veins take blood from capillaries, not into them.");
			
				p.addAnswer(2, "into the lungs",
				false,
				"No. Blood moves directly from the right ventricle of the heart through the pulmonary artery into the lungs.");
			
				p.addAnswer(3, "into the pulmonary artery",
				false,
				"No. Veins do not discharge blood into arteries without it first cycling through the heart.");
			
				p.addAnswer(4, "into the right atrium",
				true,
				"Correct. The inferior vena cava is the major vein carrying blood from the capillaries of the lower body into the heart via the right intake chamber, the atrium.");
			
				p.addAnswer(5, "into the most powerful side of the heart",
				false,
				"No. The most powerful side of the heart is the left side, which delivers oxygenated blood to the body. The vena cava takes blood into the less powerfully muscled side of the heart.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336446;


		
		

		
			
			p.question = "Heart valves function to _____. (<script type=\"text/javascript\">ebook(\'4202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "keep blood moving forward through the heart",
				true,
				"Correct. Because the valves are unidirectional, blood movement is restricted to one direction.");
			
				p.addAnswer(2, "mix blood thoroughly as it passes through the heart",
				false,
				"No. Valves only open and close. This would not cause any significant mixing of the blood as it passes through the heart.");
			
				p.addAnswer(3, "control the amount of blood pumped by the heart",
				false,
				"No. Cardiac output is controlled by the strength and rate of contraction.");
			
				p.addAnswer(4, "slow blood down as it passes through the heart",
				false,
				"No. Because nothing is added or removed from the blood while it is in the heart, there would be no advantage to slowing it down.");
			
				p.addAnswer(5, "propel blood as it passes through the heart",
				false,
				"No. Valves are compliant, passive structures. They are not constructed from muscle, and they do not contract.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336447;


		
		

		
			
			p.question = "Pressure is greatest in the ventricles when _____. (<script type=\"text/javascript\">ebook(\'4202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "blood arrives at the right ventricle",
				false,
				"No. Consider what happens in the ventricle as it contracts.");
			
				p.addAnswer(2, "blood arrives at the left atrium",
				false,
				"No. During diastole the heart is relaxed, and blood enters the atria.");
			
				p.addAnswer(3, "AV valves are open and semilunar valves are closed",
				false,
				"No. Think about the location of the heart valves and when they would be open or closed during ventricular contraction.");
			
				p.addAnswer(4, "the ventricles contract",
				true,
				"Correct. The ventricles, being the most muscular part of the heart, create enough pressure upon contraction to lock AV valves closed and force semilunar valves open, discharging blood from the heart at peak pressure.");
			
				p.addAnswer(5, "the atria contract during early systole",
				false,
				"No. The pressure of atrial contraction is not sufficient to open semilunar valves.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336448;


		
		

		
			
			p.question = "The SA node generates an electrical impulse from its location in the _____. (<script type=\"text/javascript\">ebook(\'4202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "left atrium, causing ventricular contraction",
				false,
				"No. The AV node transfers the impulse from the atria to the ventricles.");
			
				p.addAnswer(2, "left ventricle wall, from which the impulse is carried to the bundle branches and on to the Purkinje fibers",
				false,
				"No. Consider what the \"A\" in SA stands for.");
			
				p.addAnswer(3, "right atrium, causing atrial contraction",
				true,
				"Correct. The sinoatrial node is located in the wall of the right atrium.");
			
				p.addAnswer(4, "left ventricle, causing atrial contraction",
				false,
				"No. Consider what the \"A\" in SA stands for.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336449;


		
		

		
			
			p.question = "A recording of the electrical activity of a patient\'s heart shows that the atria are contracting regularly and normally, but every few beats the ventricles fail to contract. Which of the following is probably functioning improperly? (<script type=\"text/javascript\">ebook(\'4202\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "AV node",
				true,
				"Correct. The AV node sets the rhythm for the ventricles. Ventricular delay or missed contractions are termed \"heart block.\"");
			
				p.addAnswer(2, "aortic semilunar valve",
				false,
				"No. The semilunar valves present in the aorta and pulmonary trunk prevent backflow into the ventricles.");
			
				p.addAnswer(3, "coronary artery",
				false,
				"No. A blocked coronary artery can lead to irregularities in ventricular contraction because the larger ventricular muscle mass requires more oxygen than the atria. The problem, however, would be continuous rather than intermittent.");
			
				p.addAnswer(4, "pacemaker",
				false,
				"No. The pacemaker, or SA node, sets the heart rate. Problems here would also affect the atria.");
			
				p.addAnswer(5, "AV valve",
				false,
				"No. The AV valves prevent backflow into the atria during ventricular systole.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336450;


		
		

		
			
			p.question = "Your blood pressure is 120/70. The \"120\" indicates _____, and the \"70\" indicates _____. (<script type=\"text/javascript\">ebook(\'4203\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "pressure in the left ventricle; pressure in the right ventricle",
				false,
				"No. Both ventricles contract at the same time.");
			
				p.addAnswer(2, "arterial pressure; venous pressure",
				false,
				"No. Venous pressure is quite low.");
			
				p.addAnswer(3, "arterial pressure during heart contraction; arterial pressure during heart relaxation",
				true,
				"Correct. The top number is the systolic pressure, the pressure in the arteries when the ventricles are contracting. The other number is the diastolic pressure, the pressure during the relaxation phase.");
			
				p.addAnswer(4, "pressure in the left ventricle; pressure in the left atrium",
				false,
				"No. The top number is the systolic pressure, the pressure in the arteries when the ventricles are contracting. The other number is the diastolic pressure, the pressure during the relaxation phase.");
			
				p.addAnswer(5, "pressure in the systemic system; pressure in the pulmonary system",
				false,
				"No. Consider how and where blood pressure is taken.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336451;


		
		

		
			
			p.question = "If resistance increases in the capillary beds of the lung, which structure would be affected first? (<script type=\"text/javascript\">ebook(\'4203\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "aorta",
				false,
				"No. The aorta delivers blood to the systemic circulation.");
			
				p.addAnswer(2, "right atrium",
				false,
				"No. The right atrium is not connected to the aorta.");
			
				p.addAnswer(3, "left atrium",
				false,
				"No. Blood leaving the left atrium moves into the left ventricle.");
			
				p.addAnswer(4, "right ventricle",
				true,
				"Correct. The right ventricle discharges into the pulmonary arteries. Increased resistance within the lung would initially force blood back into the pulmonary arteries and right ventricle.");
			
				p.addAnswer(5, "left ventricle",
				false,
				"No. The left ventricle pumps blood into the aorta and on into the systemic circulation, not the pulmonary circulation.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336452;


		
		

		
			
			p.question = "Which one of the following is the main factor that causes lymph to move through lymphatic vessels? (<script type=\"text/javascript\">ebook(\'4203\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "blood pressure",
				false,
				"No. Contractions of the heart do not power the flow of lymph.");
			
				p.addAnswer(2, "osmotic pressure",
				false,
				"No. Osmotic pressure is concerned with the movement of substances into and out of vessels. However, capillary bed osmotic pressure can have a significant effect on how much interstitial fluid needs to be returned to the circulation through the lymphatic system.");
			
				p.addAnswer(3, "contractions of capillaries",
				false,
				"No. Capillaries do not contract and propel blood.");
			
				p.addAnswer(4, "contractions of body muscles near lymph vessels",
				true,
				"Correct. Lymph vessels depend mainly on the movement of skeletal muscles to move fluid toward the heart.");
			
				p.addAnswer(5, "diffusion",
				false,
				"No. The interstitial fluid does enter the lymphatic capillaries by diffusion, but this is not the major factor responsible for movement of the lymphatic fluid.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336453;


		
		

		
			
			p.question = " When we compare the structures and functions of arteries and veins, we find that the walls of arteries are _____, the blood pressure inside arteries is _____, and the blood is moving _____ the heart. (<script type=\"text/javascript\">ebook(\'4203\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "thicker; higher; away from",
				true,
				"Correct.");
			
				p.addAnswer(2, "thinner; lower; away from",
				false,
				"No. The walls of arteries are thicker to resist the higher blood pressures.");
			
				p.addAnswer(3, "thinner; lower; towards",
				false,
				"No. The walls of arteries are thicker to resist the higher blood pressures as blood moves away from the heart.");
			
				p.addAnswer(4, "thicker; lower; towards",
				false,
				"No. Veins carry blood with lower blood pressure towards the heart.");
			
				p.addAnswer(5, "thinner; higher; away from",
				false,
				"No. Arteries are thicker to resist the higher blood pressure as blood moves away from the heart.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336454;


		
		

		
			
			p.question = "Which of the following decrease(s) blood pressure? (<script type=\"text/javascript\">ebook(\'4203\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "vasodilation",
				true,
				"Correct. Vasodilation is the increase in diameter of blood vessels, which would lower blood pressure.");
			
				p.addAnswer(2, "vasoconstriction",
				false,
				"No. The smaller diameter of blood vessels increases blood pressure.<b> </b>");
			
				p.addAnswer(3, "the peptide endothelin",
				false,
				"No. This chemical is the most potent known inducer of vasoconstriction, which increases blood pressure.");
			
				p.addAnswer(4, "contraction of the ventricles of the heart",
				false,
				"No. When the ventricles contract, blood pressure increases.");
			
				p.addAnswer(5, "all of the above",
				false,
				"No. Only one of the choices above decreases blood pressure.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336455;


		
		

		
			
			p.question = "Which of the following is a function of erythrocytes (red blood cells)? (<script type=\"text/javascript\">ebook(\'4204\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "scavenging dead cells",
				false,
				"No. This is a leukocyte function.");
			
				p.addAnswer(2, "synthesizing antibodies",
				false,
				"No. This is a leukocyte function.");
			
				p.addAnswer(3, "engulfing bacteria",
				false,
				"No. This is a leukocyte function.");
			
				p.addAnswer(4, "engulfing viruses",
				false,
				"No. This is a leukocyte function.");
			
				p.addAnswer(5, "none of the above",
				true,
				"Correct. The main function of erythrocytes is the transport of oxygen. The choices are all functions of leukocytes.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336456;


		
		

		
			
			p.question = "A patient with which of the following conditions would probably benefit by injections of purified multipotent stem cells? (<script type=\"text/javascript\">ebook(\'4204\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "impaired resistance to infection",
				false,
				"No. Although introduced healthy stem cells could produce immune cells and improve immune resistance, this is not the only correct answer.");
			
				p.addAnswer(2, "leukemia",
				false,
				"No. It is true that following destruction of the cancerous stem cells, introduced healthy stem cells can repopulate the bone marrow and result in the normal production of blood cells. However, this is not the only correct answer.");
			
				p.addAnswer(3, "AIDS",
				false,
				"No. Although it is true that introduced virus-free stem cells could possibly generate a population of functional B and T cells, this is not the only correct answer.");
			
				p.addAnswer(4, "sickle-cell disease",
				false,
				"No. It is true that if a patient\'s stem cells were destroyed and replaced with cells with normal genes for hemoglobin, the patient could benefit. However, this is not the only correct answer.");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336457;


		
		

		
			
			p.question = "The primary sealants that plug leaks in damaged blood vessels are _____. (<script type=\"text/javascript\">ebook(\'4204\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "clotting factors released by platelets and fibrin",
				true,
				"Correct. Platelets release a clotting factor that initiates a cascade that converts fibrinogen to fibrin.");
			
				p.addAnswer(2, "red blood cells and albumin",
				false,
				"No. Red blood cells are adapted for oxygen and carbon dioxide transport; they do not participate in clotting.");
			
				p.addAnswer(3, "fibrin and white blood cells",
				false,
				"No. White blood cells are primarily associated with disease prevention; they do not participate in clotting.");
			
				p.addAnswer(4, "white blood cells and clotting factors released by platelets",
				false,
				"No. White blood cells are primarily associated with disease prevention; they do not participate in clotting.");
			
				p.addAnswer(5, "hemoglobin and clotting factors released by platelets",
				false,
				"No. The primary function of hemoglobin is oxygen transport; it does not participate in clotting.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336458;


		
		

		
			
			p.question = "What is atherosclerosis? (<script type=\"text/javascript\">ebook(\'4204\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "severe pain of the heart muscle due to lack of oxygen",
				false,
				"No. This is angina.");
			
				p.addAnswer(2, "hardening of the arteries by accumulation of fatty deposits",
				true,
				"Correct. This is one of the leading causes of heart attacks.");
			
				p.addAnswer(3, "a condition promoted by over-exertion during exercise",
				false,
				"No. Exercise and proper diet help to prevent development of atherosclerosis.");
			
				p.addAnswer(4, "a failure of blood to clot",
				false,
				"No. The failure of blood to clot would lead to problems with excessive bleeding.");
			
				p.addAnswer(5, "the non-contracting scar tissue that replaces heart muscle when heart vessels are blocked",
				false,
				"No. This forms as a result of muscle tissue death due to atherosclerosis in the vessels of the heart.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336459;


		
		

		
			
			p.question = "What is the physiological cause of a heart attack? (<script type=\"text/javascript\">ebook(\'4204\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "rupture of coronary arteries",
				false,
				"No. Coronary arteries are more likely to be blocked than to burst.");
			
				p.addAnswer(2, "severe angina",
				false,
				"No. Angina is a painful condition, caused by blocked arteries, which may eventually lead to heart attack.");
			
				p.addAnswer(3, "a blood clot moving through the chambers of the heart",
				false,
				"No. If the blood clot lodges in a blood vessel supplying the heart, it will cause a heart attack.");
			
				p.addAnswer(4, "a blood clot lodging in a blood vessel supplying the heart",
				true,
				"Correct. This would result in a lack of blood flow to heart muscle and the death of this tissue.");
			
				p.addAnswer(5, "scar tissue in the heart muscle",
				false,
				"No. Scar tissue may form after a heart attack. This tissue will weaken the heart\'s ability to pump blood because it is not able to contract.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336460;


		
		

		
			
			p.question = "For a body surface to be a respiratory surface, it must _____. (<script type=\"text/javascript\">ebook(\'4205\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "be dry and covered with hair",
				false,
				"No. This describes the vertebrate skin. Vertebrates do not respire across their skin.");
			
				p.addAnswer(2, "be moist and glandular",
				false,
				"No. You have the moist part right, but some glandular secretions can impede diffusion.");
			
				p.addAnswer(3, "have a large surface area",
				false,
				"No. Perhaps in a large animal, but many animals are extremely small and have tiny respiratory surfaces.");
			
				p.addAnswer(4, "be thin and moist",
				true,
				"Correct. Carbon dioxide and oxygen must be dissolved in water to diffuse through the thin cells of a respiratory surface.");
			
				p.addAnswer(5, "be internal",
				false,
				"No. This is true of most terrestrial animals, but the main respiratory surface of an amphibian is its skin.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336461;


		
		

		
			
			p.question = "Which of the following is an essential feature for an animal\'s gas exchange surface? (<script type=\"text/javascript\">ebook(\'4205\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "small surface area in proportion to body size",
				false,
				"No. A large ratio of surface to size is necessary to provide an adequate oxygen supply and to remove carbon dioxide.");
			
				p.addAnswer(2, "contact with a circulating body fluid",
				false,
				"No. Single-celled organisms do not have a circulating body fluid. The gases in the cytoplasm are exchanged directly across the plasma membrane.");
			
				p.addAnswer(3, "thick cell layers",
				false,
				"No. Thin cell layers are essential. The diffusion of gases through anything but thin cell layers would take too long to provide an efficient exchange.");
			
				p.addAnswer(4, "living cells",
				true,
				"Correct. Living cells are essential. Gas exchange could not proceed efficiently through layers of dead cells, which would actually protect against diffusion.");
			
				p.addAnswer(5, "a dry surface",
				false,
				"No. Moisture is necessary in gas exchange, which occurs as dissolved gases move in solution through interstitial fluids and across moist membranes.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336462;


		
		

		
			
			p.question = "Which respiratory organ is most often found only in fully aquatic animals? (<script type=\"text/javascript\">ebook(\'4205\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "tracheae",
				false,
				"No. These are found in insects, and insects are mostly terrestrial organisms.");
			
				p.addAnswer(2, "lungs",
				false,
				"No. Animals with lungs generally live on land. Some exceptions are whales, dolphins, manatees, sea snakes, and lungfish.");
			
				p.addAnswer(3, "air sacs called alveoli",
				false,
				"No. Alveoli are the microscopic sacs in the lung where gas exchange occurs.");
			
				p.addAnswer(4, "skin surface",
				false,
				"No. Animals such as frogs, salamanders, and caecilians respire through their skin, but these are amphibians and live in water only part of the time, if at all.");
			
				p.addAnswer(5, "gills",
				true,
				"Correct. Fishes and sharks rely on gills for gas exchange. These animals are fully aquatic, with some exceptions: catfish that travel between ponds and mud skippers that forage on mud flats.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336463;


		
		

		
			
			p.question = "Countercurrent exchange in the gills of a fish _____. (<script type=\"text/javascript\">ebook(\'4205\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "speeds up the flow of water through the gills",
				false,
				"No. \"Countercurrent exchange\" refers to the direction of the movement of blood within the gill and water moving across its surface.");
			
				p.addAnswer(2, "maintains a gradient that enhances diffusion",
				true,
				"Correct. This arrangement permits gas exchange along the entire length of the gill surface.");
			
				p.addAnswer(3, "enables blood oxygenation in fish regardless of the direction of water flow relative to blood flow",
				false,
				"No. If the flow of water across a fish\'s gills were reversed, there would be no countercurrent system.");
			
				p.addAnswer(4, "means that blood and water flow in the same direction",
				false,
				"No. This describes concurrent flow. It is called \"countercurrent\" because the water crosses the gill in the opposite direction that blood moves within it.");
			
				p.addAnswer(5, "interferes with the efficient absorption of oxygen",
				false,
				"No. The countercurrent systems seen in bony fish are much more efficient than the non-countercurrent systems seen in cartilaginous fish such as sharks and rays.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336464;


		
		

		
			
			p.question = "What is the major reason land-dwelling mammals have evolved lungs rather than gills as a primary respiratory organ? (<script type=\"text/javascript\">ebook(\'4205\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Gills are not as efficient as lungs in picking up oxygen.",
				false,
				"No. The countercurrent exchange in fish gills is actually more efficient at removing available oxygen from water than the \"tidal\" breathing mechanisms of mammal lungs.");
			
				p.addAnswer(2, "Gills are too small to provide oxygen for a mammal.",
				false,
				"No. There are many fish that are much larger than most mammals.");
			
				p.addAnswer(3, "Protecting gas-exchange surfaces from desiccation is difficult in terrestrial environments.",
				true,
				"Correct. Gills function only when immersed in fluid. Some land snails manage with gills, but the gills are small and protected in a moist chamber.");
			
				p.addAnswer(4, "Air has higher oxygen content than water, so gills were no longer necessary.",
				false,
				"No. Gills are an impediment to life on land because they cannot function for very long without being immersed in water. The lungfish lineage was the one to move onto land.");
			
				p.addAnswer(5, "Gills work only in aquatic animals; lungs work only in terrestrial animals.",
				false,
				"No. Some land snails have gills; whales, dolphins, and manatees all have lungs.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336465;


		
		

		
			
			p.question = "What is the order of passage as air is inhaled during ventilation of the lungs in a typical mammal? (<script type=\"text/javascript\">ebook(\'4205\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "nasal cavity, pharynx, larynx, bronchiole, bronchus, trachea, alveolus",
				false,
				"No. The trachea is larger than bronchi.");
			
				p.addAnswer(2, "nasal cavity, larynx, pharynx, trachea, bronchus, bronchiole, alveolus",
				false,
				"No. Air flows through the pharynx before it reaches the larynx.");
			
				p.addAnswer(3, "nasal cavity, pharynx, larynx, trachea, bronchus, bronchiole, alveolus",
				true,
				"Correct. Air enters through the nostrils and passes through the pharynx and the larynx. From there, the air passes into the trachea and into the two bronchi. Each bronchus branches repeatedly into bronchioles, which eventually terminate in tiny air sacs called alveoli.");
			
				p.addAnswer(4, "nasal cavity, pharynx, larynx, trachea, bronchiole, bronchus, alveolus",
				false,
				"No. Bronchioles are smaller than bronchi.");
			
				p.addAnswer(5, "nasal cavity, pharynx, trachea, larynx, bronchus, bronchiole, alveolus",
				false,
				"No. During inhalation, air flows through the larynx before it reaches the trachea.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336466;


		
		

		
			
			p.question = "Which one of the following components of the mammalian gas exchange system has a surface covered by a thin film of mucus without cilia? (<script type=\"text/javascript\">ebook(\'4205\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "trachea",
				false,
				"No. The trachea has a ciliated surface.");
			
				p.addAnswer(2, "midsize to small bronchioles",
				false,
				"No. Bronchioles have ciliated surfaces.");
			
				p.addAnswer(3, "bronchi",
				false,
				"No. Bronchi have ciliated surfaces.");
			
				p.addAnswer(4, "major bronchioles",
				false,
				"No. Bronchioles have ciliated surfaces.");
			
				p.addAnswer(5, "alveoli",
				true,
				"Correct. The tiniest bronchioles dead-end in tiny air sacs called alveoli, which have a very thin epithelium.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336467;


		
		

		
			
			p.question = "Which structure in a human is most similar in function to the gill lamellae of a fish? (<script type=\"text/javascript\">ebook(\'4205\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "vocal cords",
				false,
				"No. Vocal cords are within the conducting portion of the airway; no gas exchange occurs within this region.");
			
				p.addAnswer(2, "bronchioles",
				false,
				"No. Bronchioles are within the conducting portion of the airway; no gas exchange occurs within this region.");
			
				p.addAnswer(3, "alveoli",
				true,
				"Correct. In a fish, the actual exchange of oxygen and carbon dioxide occurs at the gill lamellae; these events occur at the alveoli in the human lung.");
			
				p.addAnswer(4, "trachea",
				false,
				"No. The trachea is within the conducting portion of the airway; no gas exchange occurs within this region.");
			
				p.addAnswer(5, "diaphragm",
				false,
				"No. The diaphragm alters the dimensions of the thorax, but it does not directly participate in gas exchange.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336468;


		
		

		
			
			p.question = "In the alveoli and lung capillaries, carbon dioxide and oxygen are exchanged by means of _____. (<script type=\"text/javascript\">ebook(\'4205\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "diffusion",
				true,
				"Correct. Oxygen and carbon dioxide exchange occurs across the epithelium of the alveoli by diffusion.");
			
				p.addAnswer(2, "active transport",
				false,
				"No. Cells do not expend energy to move these gases across alveoli.");
			
				p.addAnswer(3, "endocytosis",
				false,
				"No. Cells do not expend energy to move these gases across alveoli.");
			
				p.addAnswer(4, "pinocytosis",
				false,
				"No. Pinocytosis occurs when a cell engulfs a liquid and its dissolved solutes.");
			
				p.addAnswer(5, "osmosis",
				false,
				"No. Osmosis is the diffusion of water across a selectively permeable membrane.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336469;


		
		

		
			
			p.question = "When you exhale, _____. (<script type=\"text/javascript\">ebook(\'4206\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "both the diaphragm and rib muscles contract",
				false,
				"No. This results in inhalation.");
			
				p.addAnswer(2, "both the diaphragm and the rib muscles relax",
				true,
				"Correct. Exhalation occurs when the rib muscles and diaphragm relax, restoring the thoracic cavity to its smaller volume.");
			
				p.addAnswer(3, "the rib muscles contract and the air pressure in the alveoli becomes lower than atmospheric pressure",
				false,
				"No. Pressure in the alveoli does decrease when the rib muscles relax, but the result of this is inhalation.");
			
				p.addAnswer(4, "the volume of the chest cavity increases",
				false,
				"No. This decreases thoracic pressure and results in inhalation.");
			
				p.addAnswer(5, "the diaphragm relaxes and the lungs expand",
				false,
				"No. When the diaphragm relaxes the lungs will deflate, not expand. This decreases the pressure within the lungs and results in inhalation.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336470;


		
		

		
			
			p.question = "The maximum amount of air a person can exhale, after maximal inhalation, is called _____. (<script type=\"text/javascript\">ebook(\'4206\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "vital capacity",
				true,
				"Correct. Vital capacity is the amount of air a person can exhale after maximal inhalation.");
			
				p.addAnswer(2, "tidal volume",
				false,
				"No. Tidal volume is the volume of air in a normal breath.");
			
				p.addAnswer(3, "residual capacity",
				false,
				"No. This is the volume of air left in the lungs after a maximal exhalation.");
			
				p.addAnswer(4, "ventilation volume",
				false,
				"No. Vital capacity is the amount of air a person can exhale after maximal inhalation.");
			
				p.addAnswer(5, "end tidal volume",
				false,
				"No. Vital capacity is the amount of air a person can exhale after maximal inhalation.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336471;


		
		

		
			
			p.question = "Which one of the following statements about the respiratory systems of mammals and birds is true? (<script type=\"text/javascript\">ebook(\'4206\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Mammals have a higher maximum lung oxygen concentration than birds.",
				false,
				"No. Birds have the higher maximum lung oxygen concentration.");
			
				p.addAnswer(2, "In both types of animals, the sites of gas exchange are parabronchi.",
				false,
				"No. In mammals the sites of gas exchange are alveoli. In birds the sites of gas exchange are parabronchi.");
			
				p.addAnswer(3, "Mammals perform better at higher altitudes.",
				false,
				"No. Birds perform better at higher altitudes.");
			
				p.addAnswer(4, "The gas exchange system of mammals is confined to the thoracic cavity, but that of birds is not.",
				true,
				"Correct. The lungs of mammals are located in the thoracic cavity. Besides lungs, birds have eight or nine air sacs that penetrate the abdomen, neck, and even wings; however, keep in mind that gas exchange does not occur across these air sacs.");
			
				p.addAnswer(5, "In both types of animals, air flows through the lungs in only one direction.",
				false,
				"No. This is only true of birds.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336472;


		
		

		
			
			p.question = "What happens when the CO<sub>2</sub> level from cellular respiration increases in the blood? (<script type=\"text/javascript\">ebook(\'4206\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Cellular respiration decreases.",
				false,
				"No. Increased CO<sub>2</sub> is a result of cellular respiration. When the CO<sub>2</sub> level increases in the blood, the pH decreases.");
			
				p.addAnswer(2, "A decrease in the pH of the cerebrospinal fluid triggers the brain\'s breathing control centers, which stimulate diaphragm and rib muscle contractions.",
				true,
				"Correct. This is exactly what happens to increase the breathing rate and bring down the concentration of CO<sub>2</sub> in the blood.");
			
				p.addAnswer(3, "The pH of the cerebrospinal fluid also increases and is detected by O<sub>2</sub> sensors in arteries near the heart.",
				false,
				"No. The pH of the cerebrospinal fluid decreases when the CO<sub>2</sub> level increases. When the CO<sub>2</sub> level increases, O<sub>2</sub> concurrently decreases and this lowered level of oxygen is detected by arterial O<sub>2</sub> sensors, which signal the breathing control centers, which then stimulate an increase in the respiratory rate.");
			
				p.addAnswer(4, "The O<sub>2</sub> level automatically increases.",
				false,
				"No. The nervous system and muscles associated with the respiratory system must be stimulated before more rapid breathing removes the excess CO<sub>2</sub> and brings in more O<sub>2</sub>.");
			
				p.addAnswer(5, "The medulla, moderated by the pons, signals the heart muscle to beat harder, bringing in more O<sub>2</sub>.",
				false,
				"No. The medulla, moderated by the pons, signals the breathing control center (not the heart) to increase the breathing rate and depth, eliminating CO<sub>2</sub>, allowing the blood pH to increase, and bringing in more O<sub>2</sub>.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336473;


		
		

		
			
			p.question = "When you hold your breath, which of the following blood gas changes leads initially to the urge to breathe again? (<script type=\"text/javascript\">ebook(\'4206\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "rising oxygen concentration",
				false,
				"No. This does not decrease the pH of CSF.");
			
				p.addAnswer(2, "rising carbon dioxide concentration",
				true,
				"Correct. The breathing control centers in the brain monitor the amount of carbon dioxide in the blood.");
			
				p.addAnswer(3, "falling oxygen concentration",
				false,
				"No. This does not decrease the pH of CSF.");
			
				p.addAnswer(4, "falling carbon dioxide concentration",
				false,
				"No. This would increase the pH of CSF.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336474;


		
		

		
			
			p.question = "What causes CO<sub>2</sub> in the blood to decrease? (<script type=\"text/javascript\">ebook(\'4206\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "exercise",
				false,
				"No. Exercise increases cellular respiration, which produces CO<sub>2</sub>.");
			
				p.addAnswer(2, "increased cellular respiration",
				false,
				"No. Cellular respiration always results in increased concentrations of CO<sub>2</sub>.");
			
				p.addAnswer(3, "hyperventilation",
				true,
				"Correct. Hyperventilation removes CO<sub>2</sub> and overloads the blood with O<sub>2</sub>.");
			
				p.addAnswer(4, "running",
				false,
				"No. Running is a form of exercise, which<b> </b>increases cellular respiration, producing CO<sub>2</sub>.");
			
				p.addAnswer(5, "exercise and increased cellular respiration",
				false,
				"No. Both of these are wrong answers.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336475;


		
		

		
			
			p.question = "Which one of the following would increase the release of oxygen from red blood cells? (<script type=\"text/javascript\">ebook(\'4207\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a decrease in pH and a decrease in the P<sub>O2</sub>",
				true,
				"Correct.");
			
				p.addAnswer(2, "a decrease in pH and an increase in the P<sub>O2</sub>",
				false,
				"No. Oxygen diffuses into regions with a lower P<sub>O2</sub>.");
			
				p.addAnswer(3, "an increase in pH and an increase in the P<sub>O2</sub>",
				false,
				"No. Oxygen diffuses fastest at a lower pH and a lower P<sub>O2</sub>.");
			
				p.addAnswer(4, "an increase in pH and a decrease in the P<sub>O2</sub>",
				false,
				"No. Oxygen diffuses fastest at a lower pH.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336476;


		
		

		
			
			p.question = "How does myoglobin aid diving mammals such as the Weddell seal? (<script type=\"text/javascript\">ebook(\'4207\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "It allows diving males to store twice as much oxygen in their blood as the average human of similar size.",
				false,
				"No. It\'s true that Weddell seals can store much more oxygen in their blood than the average human can, but this is not due to myoglobin.");
			
				p.addAnswer(2, "It allows diving males to store a considerable amount of oxygenated blood in their spleens.",
				false,
				"No. Weddell seals do store a considerable amount of oxygenated blood in their spleens, but this is not due to myoglobin.");
			
				p.addAnswer(3, "It allows diving males to store a considerable amount of oxygenated blood in their muscles.",
				true,
				"Correct. The action of myoglobin in muscle tissue allows some diving mammals to spend an amazing amount of time underwater.");
			
				p.addAnswer(4, "It allows seals to switch from cellular respiration to fermentation after the oxygen in muscle cells has been depleted.",
				false,
				"No. Myoglobin stores oxygen in muscle tissue that is used for cellular respiration during long dives.");
			
				p.addAnswer(5, "none of the above",
				false,
				"No. One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

