

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "Investigation Quiz > How Do New Species Arise by Genetic Isolation?";
	ak.quiz_loc_with_commas = "Investigation Quiz, How Do New Species Arise by Genetic Isolation?";
	ak.quiz_title = "How Do New Species Arise by Genetic Isolation?";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 7;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 7;
	ak.non_essay_total = 0;
	ak.scored_item_total = 0;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337702;


		
		

		
			p.question = "Humans have 46 chromosomes in the diploid cell. How many chromosomes would be found in each gamete and in a zygote resulting from normal fertilization?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337703;


		
		

		
			p.question = "Predict the outcomes of a plant with 6 diploid chromosomes that fertilized a similar plant in which the egg failed to undergo meiosis. Assume that the plant producing the sperm undergoes meiosis normally.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337704;


		
		

		
			p.question = "Why are the tetraploid plants considered a new species by biologists?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337705;


		
		

		
			p.question = "Think of a commercial use for triploid plants incapable of producing viable gametes and zygotes.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337706;


		
		

		
			p.question = "Is plant Q capable of producing viable gametes? If so, what is the chromosome number of the gametes?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337707;


		
		

		
			p.question = "What is the evidence that this allopolyploid is self-fertile and a new species?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337708;


		
		

		
			p.question = "Would hybridizing plant Q with plants W or X produce fertile offspring?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

