

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "46: Animal Reproduction > Activities Quiz";
	ak.quiz_loc_with_commas = "46: Animal Reproduction, Activities Quiz";
	ak.quiz_title = "Activities Quiz";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 15;
	ak.non_essay_total = 15;
	ak.scored_item_total = 15;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336650;


		
		

		
			
			p.question = "Sperm develop in the _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?46&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Reproductive System of the Human Male</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "prostate gland",
				false,
				"The prostate gland contributes to seminal fluid, which nourishes and protects sperm.");
			
				p.addAnswer(2, "bulbourethral glands",
				false,
				"Bulbourethral glands contribute to seminal fluid, which nourishes and protects sperm.");
			
				p.addAnswer(3, "seminiferous tubules",
				true,
				"Sperm develop in seminiferous tubules, found within testes.");
			
				p.addAnswer(4, "hypothalamus",
				false,
				"The hypothalamus secretes hormones that, ultimately, regulate sperm production and the secretion of male sex hormones.");
			
				p.addAnswer(5, "seminal vesicles",
				false,
				"Seminal vesicles contribute to seminal fluid, which nourishes and protects sperm.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336651;


		
		

		
			
			p.question = "Sperm exit a male\'s body via the _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?46&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Reproductive System of the Human Male</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "ejaculatory duct",
				false,
				"The ejaculatory duct, formed where a duct from a seminal vesicle meets with a vas deferens, empties into the urethra.");
			
				p.addAnswer(2, "urethra",
				true,
				"The urethra carries both sperm and urine out of a male\'s body.");
			
				p.addAnswer(3, "oviduct",
				false,
				"Oviducts are components of the female reproductive system.");
			
				p.addAnswer(4, "ureter",
				false,
				"Ureters carry urine from the kidneys to the urinary bladder.");
			
				p.addAnswer(5, "epididymis",
				false,
				"The epididymis is a coiled tube that carries sperm from the seminiferous tubules to the vas deferens.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336652;


		
		

		
			
			p.question = "Which pituitary secretion stimulates sperm production? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?46&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Reproductive System of the Human Male</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "LH",
				false,
				"In males, luteinizing hormone (LH) stimulates the testes to secrete androgens.");
			
				p.addAnswer(2, "ACTH",
				false,
				"Adrenocorticotropic hormone (ACTH) acts on the adrenal cortex.");
			
				p.addAnswer(3, "TSH",
				false,
				"Thyroid-stimulating hormone (TSH) acts on the thyroid gland.");
			
				p.addAnswer(4, "PRL",
				false,
				"Prolactin (PRL) acts on mammary glands.");
			
				p.addAnswer(5, "FSH",
				true,
				"In males, follicle-stimulating hormone (FSH) stimulates sperm production.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336653;


		
		

		
			
			p.question = "Which pituitary secretion stimulates the testes to secrete androgens? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?46&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Reproductive System of the Human Male</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "LH",
				true,
				"In males, luteinizing hormone (LH) stimulates the testes to secrete androgens.");
			
				p.addAnswer(2, "ACTH",
				false,
				"Adrenocorticotropic hormone (ACTH) acts on the adrenal cortex.");
			
				p.addAnswer(3, "TSH",
				false,
				"Thyroid-stimulating hormone (TSH) acts on the thyroid gland.");
			
				p.addAnswer(4, "PRL",
				false,
				"Prolactin (PRL) acts on mammary glands");
			
				p.addAnswer(5, "FSH",
				false,
				"In males, follicle-stimulating (FSH) hormone stimulates sperm production.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336654;


		
		

		
			
			p.question = "Which hormone(s) is(are) directly responsible for triggering the development of the secondary sex characteristics of males, such as beard growth? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?46&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Reproductive System of the Human Male</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "androgens",
				true,
				"Androgens, such as testosterone, are responsible for both sperm production and the secondary sex characteristics of males.");
			
				p.addAnswer(2, "thymosin",
				false,
				"Thymosin, secreted by the thymus, plays a role in the immune system.");
			
				p.addAnswer(3, "epinephrine",
				false,
				"Epinephrine, secreted by the adrenal cortex and components of the nervous system, plays a role in the \"fight or flight\" response.");
			
				p.addAnswer(4, "insulin",
				false,
				"Insulin, secreted by the pancreas, plays a role in the regulation of blood sugar levels.");
			
				p.addAnswer(5, "parathyroid hormone",
				false,
				"Parathyroid hormone, secreted by the parathyroids, plays a role in the regulation of blood calcium levels.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336655;


		
		

		
			
			p.question = "The secretion of androgens is regulated by a _____ feedback mechanism involving the _____ and _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?46&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Reproductive System of the Human Male</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "positive ... hypothalamus ... pituitary gland",
				false,
				"Androgen secretion is regulated by a negative feedback mechanism.");
			
				p.addAnswer(2, "negative ... hypothalamus ... pituitary gland",
				true,
				"An increase in androgens inhibits the secretion of releasing hormones by the hypothalamus and LH secretion by the pituitary gland. A decrease in androgens stimulates the secretion of releasing hormones by the hypothalamus and LH secretion by the pituitary gland.");
			
				p.addAnswer(3, "positive ... thyroid ... pituitary gland",
				false,
				"Androgen secretion is regulated by a negative feedback mechanism.");
			
				p.addAnswer(4, "negative ... pancreas ... pituitary gland",
				false,
				"The pancreas does not play a role in regulating the secretion of androgens.");
			
				p.addAnswer(5, "negative ... seminal vesicles ... prostate gland",
				false,
				"The seminal vesicles and prostate glands are not involved in regulating the secretion of androgens.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336656;


		
		

		
			
			p.question = "Sperm become capable of movement while in the _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?46&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Reproductive System of the Human Male</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "seminiferous tubules",
				false,
				"Sperm are formed in, but do not become capable of movement while in, the seminiferous tubules.");
			
				p.addAnswer(2, "vas deferens",
				false,
				"Sperm are motile prior to their entry into the vas deferens.");
			
				p.addAnswer(3, "ejaculatory ducts",
				false,
				"Sperm are motile prior to their entry into the ejaculatory ducts.");
			
				p.addAnswer(4, "urethra",
				false,
				"Sperm are motile prior to their entry into the urethra.");
			
				p.addAnswer(5, "epididymis",
				true,
				"Sperm mature and become motile while in the epididymis.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336657;


		
		

		
			
			p.question = "What is the usual site of the fertilization of an egg cell? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?46&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Reproductive System of the Human Female</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "uterus",
				false,
				"If fertilization occurs, it usually occurs prior to the egg\'s entry into the uterus.");
			
				p.addAnswer(2, "ovary",
				false,
				"Fertilization usually occurs after ovulation (after the egg has left the ovary).");
			
				p.addAnswer(3, "oviduct",
				true,
				"The oviducts are the usual sites of fertilization.");
			
				p.addAnswer(4, "abdominal cavity",
				false,
				"Fertilization rarely occurs within the abdominal cavity.");
			
				p.addAnswer(5, "vagina",
				false,
				"Fertilization does not occur in the vagina.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336658;


		
		

		
			
			p.question = "A fertilized egg usually implants itself and develops in the _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?46&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Reproductive System of the Human Female</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "uterus",
				true,
				"the uterus is the usual site of the implantation and development of the fertilized egg");
			
				p.addAnswer(2, "ovary",
				false,
				"Development within the ovary is referred to as an ectopic pregnancy; this is a life-threatening situation.");
			
				p.addAnswer(3, "oviduct",
				false,
				"Development within an oviduct is referred to as an ectopic pregnancy; this is a life-threatening situation.");
			
				p.addAnswer(4, "abdominal cavity",
				false,
				"Development within the abdominal cavity is referred to as an ectopic pregnancy; this is a life-threatening situation.");
			
				p.addAnswer(5, "none of these",
				false,
				"One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336659;


		
		

		
			
			p.question = "Developing ovarian follicles primarily secrete _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?46&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Reproductive System of the Human Female</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "progesterone",
				false,
				"The corpus luteum, which forms after ovulation, secretes both progesterone and estrogen.");
			
				p.addAnswer(2, "estrogens",
				true,
				"Developing ovarian follicles secrete estrogen.");
			
				p.addAnswer(3, "luteinizing hormone",
				false,
				"The anterior pituitary secretes LH.");
			
				p.addAnswer(4, "follicle-stimulating hormone",
				false,
				"The anterior pituitary secretes FSH.");
			
				p.addAnswer(5, "human chorionic gonadotropin",
				false,
				"The embryo secretes HCG.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336660;


		
		

		
			
			p.question = "A rapid increase in the _____ level stimulates ovulation. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?46&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Reproductive System of the Human Female</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "progesterone",
				false,
				"The corpus luteum, which secretes progesterone, is formed from the ruptured follicle after ovulation.");
			
				p.addAnswer(2, "estrogen",
				false,
				"However, estrogen stimulates the secretion of the hormone responsible for stimulating ovulation.");
			
				p.addAnswer(3, "luteinizing hormone",
				true,
				"A surge in LH levels is responsible for triggering ovulation.");
			
				p.addAnswer(4, "follicle-stimulating hormone",
				false,
				"While FSH levels increase about the time ovulation occurs, this increase is not responsible for stimulating ovulation.");
			
				p.addAnswer(5, "human chorionic gonadotropin",
				false,
				"Since the embryo secretes HCG, HCG cannot be responsible for ovulation.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336661;


		
		

		
			
			p.question = "Ovulation usually occurs on or about day _____ of a 28-day ovarian cycle. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?46&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Reproductive System of the Human Female</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "1",
				false,
				"Day 1 is the first day of the ovarian cycle; at this time follicles begin to develop.");
			
				p.addAnswer(2, "7",
				false,
				"At this time follicles are still developing.");
			
				p.addAnswer(3, "14",
				true,
				"Ovulation usually occurs about halfway through the 28-day ovarian cycle.");
			
				p.addAnswer(4, "21",
				false,
				"Usually, by day 21 ovulation has already occurred and the corpus luteum is present.");
			
				p.addAnswer(5, "28",
				false,
				"If fertilization has not occurred, day 28 is usually the last day of the ovarian cycle; the corpus luteum has degenerated and a new ovarian cycle is about to begin.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336662;


		
		

		
			
			p.question = "After ovulation, high levels of _____ inhibit _____ secretion. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?46&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Reproductive System of the Human Female</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "estrogen and progesterone ... FSH and LH",
				true,
				"By secreting estrogen and progesterone, the corpus luteum maintains the endometrium and inhibits FSH and LH secretion.");
			
				p.addAnswer(2, "FSH and LH ... estrogen and progesterone",
				false,
				"LH stimulates the development of the corpus luteum, which secretes estrogen and progesterone.");
			
				p.addAnswer(3, "HCG ... estrogen and progesterone",
				false,
				"HCG, secreted by the embryo, stimulates the maintenance of the corpus luteum, which secretes estrogen and progesterone.");
			
				p.addAnswer(4, "estrogen ... FSH",
				false,
				"This choice is correct in part, but there is a more complete answer among the choices.");
			
				p.addAnswer(5, "androgens ... FSH and LH",
				false,
				"While females do secrete androgens (and males do secrete estrogen), after ovulation androgens are not responsible for inhibiting FSH and LH secretion.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336663;


		
		

		
			
			p.question = "If there is no fertilization, degeneration of the corpus luteum results in a drop in _____, which results in the sloughing off of the uterus\'s endometrium. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?46&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Reproductive System of the Human Female</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "FSH",
				false,
				"Degeneration of the corpus luteum leads to an increase in FSH levels.");
			
				p.addAnswer(2, "estrogen and progesterone",
				true,
				"Estrogen and progesterone are responsible for maintaining the endometrium in the event that the egg has been fertilized.");
			
				p.addAnswer(3, "hypothalamic secretion of releasing hormones",
				false,
				"Degeneration of the corpus luteum leads to an increase in the hypothalamic secretion of releasing hormones.");
			
				p.addAnswer(4, "HCG",
				false,
				"HCG is secreted by the embryo; thus the presence of HCG is evidence that fertilization has occurred.");
			
				p.addAnswer(5, "LH",
				false,
				"Degeneration of the corpus luteum leads to an increase in LH levels.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336664;


		
		

		
			
			p.question = "If there is fertilization, secretion of _____ by the early embryo maintains the corpus luteum. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?46&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Reproductive System of the Human Female</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "progesterone",
				false,
				"The early embryo does not secrete progesterone.");
			
				p.addAnswer(2, "estrogen",
				false,
				"The early embryo does not secrete estrogen.");
			
				p.addAnswer(3, "luteinizing hormone",
				false,
				"LH is secreted by the anterior pituitary, not by the embryo.");
			
				p.addAnswer(4, "follicle-stimulating hormone",
				false,
				"FSH is secreted by the anterior pituitary, not by the embryo.");
			
				p.addAnswer(5, "human chorionic gonadotropin",
				true,
				"HCG, secreted by the early embryo, maintains the corpus luteum. The corpus luteum secretes estrogen and progesterone, which maintain the endometrium for implantation.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

