

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "Investigation Quiz > How Are Trees Identified by Their Leaves?";
	ak.quiz_loc_with_commas = "Investigation Quiz, How Are Trees Identified by Their Leaves?";
	ak.quiz_title = "How Are Trees Identified by Their Leaves?";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 14;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 14;
	ak.non_essay_total = 0;
	ak.scored_item_total = 0;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337731;


		
		

		
			p.question = "Write a description of this leaf using the leaf characteristics vocabulary you just learned.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337732;


		
		

		
			p.question = "What else did you observe about Leaf 2? What is its leaf type? What is its leaf venation?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337733;


		
		

		
			p.question = "What kind of tree is Tree #1? Write a complete description, including its leaf type, leaf venation, leaf arrangement, common name, and scientific name.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337734;


		
		

		
			p.question = "What kind of tree is Tree #2? Write a complete description, including its leaf type, leaf venation, leaf arrangement, common name, and scientific name.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337735;


		
		

		
			p.question = "What kind of tree is Tree #3? Write a complete description, including its leaf type, leaf venation, leaf arrangement, common name, and scientific name.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337736;


		
		

		
			p.question = "What kind of tree is Tree #4? Write a complete description, including its leaf type, leaf venation, leaf arrangement, common name, and scientific name.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337737;


		
		

		
			p.question = "What kind of tree is Tree #5? Write a complete description, including its leaf type, leaf venation, leaf arrangement, common name, and scientific name.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337738;


		
		

		
			p.question = "What kind of tree is Tree #6? Write a complete description, including its leaf type, leaf venation, leaf arrangement, common name, and scientific name.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337739;


		
		

		
			p.question = "What kind of tree is Tree #7? Write a complete description, including its leaf type, leaf venation, leaf arrangement, common name, and scientific name.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337740;


		
		

		
			p.question = "What kind of tree is Tree #8? Write a complete description, including its leaf type, leaf venation, leaf arrangement, common name, and scientific name.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337741;


		
		

		
			p.question = "What kind of tree is Tree #9? Write a complete description, including its leaf type, leaf venation, leaf arrangement, common name, and scientific name.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337742;


		
		

		
			p.question = "What kind of tree is Tree #10? Write a complete description, including its leaf type, leaf venation, leaf arrangement, common name, and scientific name.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337743;


		
		

		
			p.question = "What kind of tree is Tree #11? Write a complete description, including its leaf type, leaf venation, leaf arrangement, common name, and scientific name.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337744;


		
		

		
			p.question = "What kind of tree is Tree #12? Write a complete description, including its leaf type, leaf venation, leaf arrangement, common name, and scientific name.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

