

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "4: Carbon and the Molecular Diversity of Life > Activities Quiz";
	ak.quiz_loc_with_commas = "4: Carbon and the Molecular Diversity of Life, Activities Quiz";
	ak.quiz_title = "Activities Quiz";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 25;
	ak.non_essay_total = 25;
	ak.scored_item_total = 25;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334177;


		
		

		
			
			p.question = "How do these hydrocarbons differ? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?4&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Diversity of Carbon-Based Molecules</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0401q.jpg\" ALT=\"Question #1\" BORDER=\"1\" >";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "One of these hydrocarbons has a ring structure.",
				false,
				"Neither of these hydrocarbons has a ring structure.");
			
				p.addAnswer(2, "One of these hydrocarbons has a double bond.",
				false,
				"Neither of these hydrocarbons has a double bond.");
			
				p.addAnswer(3, "One of these hydrocarbons is branched.",
				false,
				"Neither of these hydrocarbons is branched.");
			
				p.addAnswer(4, "These hydrocarbons are identical.",
				false,
				"These hydrocarbons are not identical.");
			
				p.addAnswer(5, "One of these hydrocarbons is longer than the other.",
				true,
				"The hydrocarbon on the right is longer than the hydrocarbon on the left.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334178;


		
		

		
			
			p.question = "How do these hydrocarbons differ? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?4&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Diversity of Carbon-Based Molecules</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0402q.jpg\" ALT=\"Question #2\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "One of these hydrocarbons is longer than the other.",
				false,
				"Both of these hydrocarbons contain 4 carbons.");
			
				p.addAnswer(2, "One of these hydrocarbons has a double bond.",
				false,
				"Neither of these hydrocarbons has a double bond.");
			
				p.addAnswer(3, "One of these hydrocarbons is branched.",
				true,
				"The hydrocarbon on the right is branched.");
			
				p.addAnswer(4, "One of these hydrocarbons has a ring structure.",
				false,
				"Neither of these hydrocarbons has a ring structure.");
			
				p.addAnswer(5, "These hydrocarbons are identical.",
				false,
				"These hydrocarbons are not identical.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334179;


		
		

		
			
			p.question = "How do these hydrocarbons differ? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?4&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Diversity of Carbon-Based Molecules</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0403q.jpg\" ALT=\"Question #3\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "These hydrocarbons are identical.",
				false,
				"These hydrocarbons are not identical.");
			
				p.addAnswer(2, "One of these hydrocarbons has a ring structure.",
				false,
				"Neither of these hydrocarbons has a ring structure.");
			
				p.addAnswer(3, "One of these hydrocarbons is longer than the other.",
				false,
				"Both of these hydrocarbons contain 4 carbons.");
			
				p.addAnswer(4, "One of these hydrocarbons is branched.",
				false,
				"Neither of these hydrocarbons is branched.");
			
				p.addAnswer(5, "One of these hydrocarbons has a double bond.",
				true,
				"The hydrocarbon on the right has a double bond.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334180;


		
		

		
			
			p.question = "How do these hydrocarbons differ? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?4&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Diversity of Carbon-Based Molecules</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0404q.jpg\" ALT=\"Question #4\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "One of these hydrocarbons is branched.",
				false,
				"Neither of these hydrocarbons is branched.");
			
				p.addAnswer(2, "One of these hydrocarbons has a ring structure.",
				true,
				"The hydrocarbon on the right has a ring structure.");
			
				p.addAnswer(3, "One of these hydrocarbons has a double bond.",
				false,
				"Neither of these hydrocarbons has a double bond.");
			
				p.addAnswer(4, "The hydrocarbon on the left contains more carbon atoms than the hydrocarbon on the right.",
				false,
				"Count again.");
			
				p.addAnswer(5, "These hydrocarbons are identical.",
				false,
				"These hydrocarbons are not identical.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334181;


		
		

		
			
			p.question = "How many hydrogen atoms can be attached to carbon A? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?4&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Diversity of Carbon-Based Molecules</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0405q.jpg\" ALT=\"Question #5\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "0",
				false,
				"Consider how many covalent bonds a carbon atom can form.");
			
				p.addAnswer(2, "1",
				false,
				"Consider how many covalent bonds a carbon atom can form.");
			
				p.addAnswer(3, "2",
				false,
				"Consider how many covalent bonds a carbon atom can form.");
			
				p.addAnswer(4, "3",
				true,
				"A carbon atom can form up to four covalent bonds.");
			
				p.addAnswer(5, "4",
				false,
				"This would be a total of five covalent bonds.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334182;


		
		

		
			
			p.question = "How many hydrogen atoms can be attached to carbon B? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?4&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Diversity of Carbon-Based Molecules</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0406q.jpg\" ALT=\"Question #6\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "1",
				true,
				"A carbon atom can form up to four covalent bonds.");
			
				p.addAnswer(2, "2",
				false,
				"Consider how many covalent bonds a carbon atom can form.");
			
				p.addAnswer(3, "3",
				false,
				"Consider how many covalent bonds a carbon atom can form.");
			
				p.addAnswer(4, "4",
				false,
				"Consider how many covalent bonds a carbon atom can form.");
			
				p.addAnswer(5, "0",
				false,
				"Consider how many covalent bonds a carbon atom can form.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334183;


		
		

		
			
			p.question = "L-dopa is used to treat _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?4&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Isomers</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Alzheimer\'s disease",
				false,
				"L-dopa is not a treatment for Alzheimer\'s disease.");
			
				p.addAnswer(2, "muscle sprains",
				false,
				"L-dopa is not used to treat muscle sprains.");
			
				p.addAnswer(3, "Marfan\'s syndrome",
				false,
				"L-dopa is not used to treat Marfan\'s syndrome.");
			
				p.addAnswer(4, "laryngitis",
				false,
				"L-dopa is not used to treat laryngitis.");
			
				p.addAnswer(5, "Parkinson\'s disease",
				true,
				"People with Parkinson\'s disease lack dopamine.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334184;


		
		

		
			
			p.question = "What kind of effect does R-dopa have on Parkinson\'s disease? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?4&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Isomers</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "It alleviates the symptoms.",
				false,
				"R-dopa does not alleviate the symptoms of Parkinson\'s disease.");
			
				p.addAnswer(2, "It makes the symptoms of Parkinson\'s disease worse.",
				false,
				"R-dopa does not worsen the symptoms of Parkinson\'s disease.");
			
				p.addAnswer(3, "At first it makes the symptoms worse but over the long term it alleviates the symptoms.",
				false,
				"This is not the effect of R-dopa on the symptoms of Parkinson\'s disease.");
			
				p.addAnswer(4, "None.",
				true,
				"R-dopa has no effect on Parkinson\'s disease.");
			
				p.addAnswer(5, "At first it alleviates the symptoms but over the long term it makes the symptoms worse.",
				false,
				"This is not the effect of R-dopa on the symptoms of Parkinson\'s disease.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334185;


		
		

		
			
			p.question = "These molecules are _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?4&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Isomers</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0409q.jpg\" ALT=\"Question #9\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "geometric isomers",
				false,
				"The molecules are not geometric isomers.");
			
				p.addAnswer(2, "amines",
				false,
				"These molecules do not contain an amino group.");
			
				p.addAnswer(3, "enantiomers",
				false,
				"These molecules are not enantiomers.");
			
				p.addAnswer(4, "structural isomers",
				true,
				"The two molecules differ in the covalent bond relationships among their atoms.");
			
				p.addAnswer(5, "thiols",
				false,
				"These molecules do not contain a sulfhydryl group.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334186;


		
		

		
			
			p.question = "These molecules are _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?4&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Isomers</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0410q.jpg\" ALT=\"Question #10\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "structural isomers",
				false,
				"These molecules, while isomers, are not structural isomers.");
			
				p.addAnswer(2, "ATP and ADP",
				false,
				"These molecules do not contain a phosphate group.");
			
				p.addAnswer(3, "enantiomers",
				false,
				"These molecules are not enantiomers.");
			
				p.addAnswer(4, "thiols",
				false,
				"These molecules do not contain a sulfhydryl group.");
			
				p.addAnswer(5, "geometric isomers",
				true,
				"These molecules differ in how their atoms are arranged about a double bond.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334187;


		
		

		
			
			p.question = "These molecules are _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?4&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Isomers</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0411q.jpg\" ALT=\"Question #11\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "geometric isomers",
				false,
				"The molecules are not geometric isomers.");
			
				p.addAnswer(2, "enantiomers",
				true,
				"These molecules are mirror images.");
			
				p.addAnswer(3, "thiols",
				false,
				"These molecules do not contain a sulfhydryl group.");
			
				p.addAnswer(4, "structural isomers",
				false,
				"These molecules are not structural isomers.");
			
				p.addAnswer(5, "R-dopa and L-dopa",
				false,
				"R-dopa and L-dopa have more complex structures than do these molecules.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334188;


		
		

		
			
			p.question = "Enantiomers are molecules that _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?4&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Isomers</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "are isomers that differ in the covalent partnerships between their atoms",
				false,
				"This is not the definition of enantiomers.");
			
				p.addAnswer(2, "contain a carboxyl group",
				false,
				"This is not the definition of enantiomers.");
			
				p.addAnswer(3, "differ in the arrangement of their molecules about a double bond",
				false,
				"This is not the definition of enantiomers.");
			
				p.addAnswer(4, "are mirror images",
				true,
				"This is the definition of enantiomers.");
			
				p.addAnswer(5, "contain an &#150;OH group",
				false,
				"Hydroxyl groups are characteristic of alcohols.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334189;


		
		

		
			
			p.question = "Geometric isomers are molecules that _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?4&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Isomers</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "are isomers that differ in the covalent partnerships between their atoms",
				false,
				"Such isomers are not geometric isomers.");
			
				p.addAnswer(2, "are isomers in which one of the molecules contains an amino group and the other contains a phosphate group",
				false,
				"Isomers have identical molecular formulas.");
			
				p.addAnswer(3, "are mirror images",
				false,
				"Such isomers are not geometric isomers.");
			
				p.addAnswer(4, "differ in their molecular formulas",
				false,
				"Isomers have identical molecular formulas.");
			
				p.addAnswer(5, "differ in the arrangement of their atoms about a double bond",
				true,
				"This is the definition of geometric isomers.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334190;


		
		

		
			
			p.question = "This pair of molecules are _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?4&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Isomers</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0414q.jpg\" ALT=\"Question #14\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "enantiomers",
				false,
				"These molecules are not mirror images.");
			
				p.addAnswer(2, "identical",
				false,
				"Take another look at the molecules.");
			
				p.addAnswer(3, "geometric isomers",
				false,
				"Take another look at the molecules.");
			
				p.addAnswer(4, "structural isomers",
				false,
				"Take another look at the molecules.");
			
				p.addAnswer(5, "not isomers",
				true,
				"These molecules have different molecular formulas.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334191;


		
		

		
			
			p.question = "Which one of these is an amino group? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?4&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Functional Groups</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0415q.jpg\" ALT=\"Question #15\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "B",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(2, "D",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(3, "E",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(4, "A",
				true,
				"This is an amino group, NH<sub>2</sub>.");
			
				p.addAnswer(5, "C",
				false,
				"No, that is incorrect.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334192;


		
		

		
			
			p.question = "Which of these is a phosphate group? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?4&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Functional Groups</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0416q.jpg\" ALT=\"Question #16\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "B",
				true,
				"Of the choices, this is the only one that contains phosphorus.");
			
				p.addAnswer(2, "A",
				false,
				"This functional group does not contain phosphorus.");
			
				p.addAnswer(3, "C",
				false,
				"This functional group does not contain phosphorus.");
			
				p.addAnswer(4, "E",
				false,
				"This functional group does not contain phosphorus.");
			
				p.addAnswer(5, "F",
				false,
				"This functional group does not contain phosphorus.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334193;


		
		

		
			
			p.question = "Which of these is a hydroxyl group? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?4&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Functional Groups</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0417q.jpg\" ALT=\"Question #17\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A",
				false,
				"Consider the similarity of the term \"hydroxyl\" with what you learned about the properties of water.");
			
				p.addAnswer(2, "E",
				false,
				"Sulfur is not a component of water molecules.");
			
				p.addAnswer(3, "C",
				false,
				"Carbon is not a component of water molecules.");
			
				p.addAnswer(4, "D",
				true,
				"This is a hydroxyl group.");
			
				p.addAnswer(5, "F",
				false,
				"Carbon is not a component of water molecules.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334194;


		
		

		
			
			p.question = "Which of these is a carboxyl group? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?4&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Functional Groups</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0418q.jpg\" ALT=\"Question #18\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "B",
				false,
				"Carboxyl groups do not contain phosphorus.");
			
				p.addAnswer(2, "A",
				false,
				"Carboxyl groups do not contain nitrogen.");
			
				p.addAnswer(3, "C",
				false,
				"This is a carbonyl group.");
			
				p.addAnswer(4, "F",
				true,
				"This is a carboxyl group.");
			
				p.addAnswer(5, "E",
				false,
				"Carboxyl groups do not contain sulfur.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334195;


		
		

		
			
			p.question = "Which of these functional groups is characteristic of alcohol? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?4&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Functional Groups</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0419q.jpg\" ALT=\"Question #19\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A",
				false,
				"Alcohols are not characterized by the presence of nitrogen.");
			
				p.addAnswer(2, "D",
				true,
				"Hydroxyl groups are characteristic of alcohol.");
			
				p.addAnswer(3, "C",
				false,
				"Carbonyl groups are not characteristic of alcohol.");
			
				p.addAnswer(4, "B",
				false,
				"Alcohols are not characterized by the presence of phosphorus.");
			
				p.addAnswer(5, "E",
				false,
				"Alcohols are not characterized by the presence of sulfur.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334196;


		
		

		
			
			p.question = "Which of the functional groups behaves as a base? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?4&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Functional Groups</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0420q.jpg\" ALT=\"Question #20\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A",
				true,
				"The electronegativity of nitrogen means that amino groups tend to pick up hydrogen ions.");
			
				p.addAnswer(2, "E",
				false,
				"Sulfhydryl groups do not behave as bases.");
			
				p.addAnswer(3, "C",
				false,
				"Carbonyl groups do not behave as bases.");
			
				p.addAnswer(4, "F",
				false,
				"Carboxyl groups behave as acids.");
			
				p.addAnswer(5, "B",
				false,
				"Phosphate groups do not behave as bases.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334197;


		
		

		
			
			p.question = "Which of these groups is characteristic of thiols? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?4&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Functional Groups</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0421q.jpg\" ALT=\"Question #21\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A",
				false,
				"Thiols are not characterized by the presence of an amino group.");
			
				p.addAnswer(2, "B",
				false,
				"Thiols are not characterized by the presence of a phosphate group.");
			
				p.addAnswer(3, "D",
				false,
				"Thiols are not characterized by the presence of a hydroxyl group.");
			
				p.addAnswer(4, "F",
				false,
				"Thiols are not characterized by the presence of a carboxyl group.");
			
				p.addAnswer(5, "E",
				true,
				"Thiols are characterized by the presence of a sulfhydryl group.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334198;


		
		

		
			
			p.question = "Which of these groups plays a major role in energy transfer? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?4&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Functional Groups</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0422q.jpg\" ALT=\"Question #22\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "D",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(2, "C",
				false,
				"This is a carbonyl group.");
			
				p.addAnswer(3, "A",
				false,
				"This is an amino group.");
			
				p.addAnswer(4, "B",
				true,
				"Phosphate groups are a component of ATP.");
			
				p.addAnswer(5, "E",
				false,
				"Sulfur is not a component of ATP.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334199;


		
		

		
			
			p.question = "Which of these is a carbonyl group? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?4&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Functional Groups</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0423q.jpg\" ALT=\"Question #23\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "C",
				true,
				"This is a carbonyl group.");
			
				p.addAnswer(2, "E",
				false,
				"Carbonyl groups do not contain sulfur.");
			
				p.addAnswer(3, "B",
				false,
				"Carbonyl groups do not contain phosphorus.");
			
				p.addAnswer(4, "F",
				false,
				"However, this does have features in common with a carbonyl group.");
			
				p.addAnswer(5, "A",
				false,
				"Carbonyl groups do not contain nitrogen.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334200;


		
		

		
			
			p.question = "Which of these functional groups is characteristic of a ketone? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?4&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Functional Groups</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0424q.jpg\" ALT=\"Question #24\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "E",
				false,
				"Ketones are not characterized by the presence of sulfur.");
			
				p.addAnswer(2, "B",
				false,
				"Ketones are not characterized by the presence of phosphorus.");
			
				p.addAnswer(3, "A",
				false,
				"Ketones are not characterized by the presence of nitrogen.");
			
				p.addAnswer(4, "D",
				false,
				"A hydroxyl group does not characterize ketones.");
			
				p.addAnswer(5, "C",
				true,
				"A carbonyl group in the middle of a carbon skeleton characterizes ketones.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334201;


		
		

		
			
			p.question = "Which of these functional groups behaves as an acid? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?4&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Functional Groups</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0425q.jpg\" ALT=\"Question #25\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A",
				false,
				"Amino groups act as bases.");
			
				p.addAnswer(2, "E",
				false,
				"Sulfhydryl groups do not act as acids.");
			
				p.addAnswer(3, "F",
				true,
				"By donating hydrogen ions, carboxyl groups act as an acid.");
			
				p.addAnswer(4, "C",
				false,
				"Carbonyl groups do not act as acids.");
			
				p.addAnswer(5, "D",
				false,
				"Hydroxyl groups do not act as acids.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

