

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "50: Sensory and Motor Mechanisms > Activities Quiz";
	ak.quiz_loc_with_commas = "50: Sensory and Motor Mechanisms, Activities Quiz";
	ak.quiz_title = "Activities Quiz";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 15;
	ak.non_essay_total = 15;
	ak.scored_item_total = 15;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336855;


		
		

		
			
			p.question = "The _____ is the region of the eye where photoreceptors are most highly concentrated. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?49&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Structure and Function of the Eye</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "lens",
				false,
				"The function of the lens is to focus light on the retina.");
			
				p.addAnswer(2, "fovea",
				true,
				"Photoreceptors are most highly concentrated in the region of the retina known as the fovea.");
			
				p.addAnswer(3, "optic nerve",
				false,
				"The optic nerve conducts impulses from photoreceptors to the brain.");
			
				p.addAnswer(4, "pupil",
				false,
				"The pupil is the opening in the iris that lets light into the interior of the eye.");
			
				p.addAnswer(5, "sclera",
				false,
				"The sclera is the tough outer layer of the eye.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336856;


		
		

		
			
			p.question = "What name is given to the tough layer that forms the \"white\" of the eye? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?49&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Structure and Function of the Eye</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "blind spot",
				false,
				"The blind spot is the region attached to the optic nerve at the back of the eye. It is referred to as the \"blind spot\" since it lacks photoreceptors.");
			
				p.addAnswer(2, "choroid",
				false,
				"The choroid is a pigmented region behind the retina that prevents light waves from scattering about the eye.");
			
				p.addAnswer(3, "fovea",
				false,
				"The fovea is the region of the retina where photoreceptors are most highly concentrated.");
			
				p.addAnswer(4, "sclera",
				true,
				"The sclera is the tough outer layer that forms the white of the eye.");
			
				p.addAnswer(5, "aqueous humor",
				false,
				"The aqueous humor fills the anterior chamber of the eye and plays a role in bending light waves.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336857;


		
		

		
			
			p.question = "The _____ changes shape to focus light on the retina. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?49&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Structure and Function of the Eye</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "vitreous humor",
				false,
				"The vitreous humor fills the space behind the lens; it helps to maintain the shape of the eye and holds the retina against the choroid.");
			
				p.addAnswer(2, "blind spot",
				false,
				"The blind spot is the region attached to the optic nerve at the back of the eye. It is referred to as the \"blind spot\" since it lacks photoreceptors.");
			
				p.addAnswer(3, "cornea",
				false,
				"The cornea is the transparent part of the sclera that lets light into the eye.");
			
				p.addAnswer(4, "lens",
				true,
				"By changing the shape of the lens the eye can bend light rays such that they focus on the retina.");
			
				p.addAnswer(5, "optic nerve",
				false,
				"The optic nerve conducts nerve impulses from the eye to the brain.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336858;


		
		

		
			
			p.question = "What name is given to the opening that allows light into the interior of the eye? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?49&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Structure and Function of the Eye</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "sclera",
				false,
				"The sclera is the tough outer layer of the eye.");
			
				p.addAnswer(2, "pupil",
				true,
				"The pupil is the opening in the iris that lets light into the interior of the eye.");
			
				p.addAnswer(3, "ligament",
				false,
				"Ligaments play a role in changing the shape of the lens.");
			
				p.addAnswer(4, "optic nerve",
				false,
				"The optic nerve conducts nerve impulses from the eye to the brain.");
			
				p.addAnswer(5, "retina",
				false,
				"The retina contains photoreceptors.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336859;


		
		

		
			
			p.question = "Which of these is a component of a human\'s appendicular skeleton? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?49&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Human Skeleton</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "ribs",
				false,
				"Ribs are a component of a human\'s axial skeleton.");
			
				p.addAnswer(2, "sternum",
				false,
				"The sternum is a component of a human\'s axial skeleton.");
			
				p.addAnswer(3, "femur",
				true,
				"The femur, the thigh bone, is a component of the appendicular skeleton.");
			
				p.addAnswer(4, "skull",
				false,
				"The skull is a component of a human\'s axial skeleton.");
			
				p.addAnswer(5, "vertebral column",
				false,
				"The vertebral column is a component of a human\'s axial skeleton.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336860;


		
		

		
			
			p.question = "What type of joint allows you to open and close your mouth? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?49&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Human Skeleton</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "ball and socket",
				false,
				"The joint that allows you to open and close your mouth provides less range of motion than is typical of ball-and-socket joints.");
			
				p.addAnswer(2, "hinge",
				true,
				"The joint between the temporal bone and the mandible is a hinge joint.");
			
				p.addAnswer(3, "pivot",
				false,
				"A pivot joint allows for rotational movement.");
			
				p.addAnswer(4, "saddle",
				false,
				"A saddle joint is found between the thumb and the trapezium (a wrist bone).");
			
				p.addAnswer(5, "none of the above",
				false,
				"One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336861;


		
		

		
			
			p.question = "What type of joint allows you to shake your head \"no\"? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?49&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Human Skeleton</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "ball and socket",
				false,
				"The joint that allows you to shake your head \"no\" provides less range of motion than is typical of ball-and-socket joints.");
			
				p.addAnswer(2, "hinge",
				false,
				"Hinge joints typically allow only opening and closing motions.");
			
				p.addAnswer(3, "pivot",
				true,
				"A pivot joint allows for rotational movement such as shaking your head \"no.\"");
			
				p.addAnswer(4, "saddle",
				false,
				"A saddle joint is found between the thumb and the trapezium (a wrist bone).");
			
				p.addAnswer(5, "none of the above",
				false,
				"One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336862;


		
		

		
			
			p.question = "What type of joint is found where the humerus joins the shoulder blade? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?49&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Human Skeleton</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "ball and socket",
				true,
				"The joint that allows the considerable range of motion seen at the shoulder joint is a ball and socket.");
			
				p.addAnswer(2, "hinge",
				false,
				"Hinge joints typically allow only opening and closing motions.");
			
				p.addAnswer(3, "pivot",
				false,
				"A pivot joint allows for rotational movement, less range of motion than is seen at the shoulder joint.");
			
				p.addAnswer(4, "saddle",
				false,
				"A saddle joint is found between the thumb and the trapezium (a wrist bone).");
			
				p.addAnswer(5, "none of the above",
				false,
				"One of the other choices is correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336863;


		
		

		
			
			p.question = "The thick filaments of sarcomeres are composed of _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?49&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Skeletal Muscle Structure</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "myofibrils",
				false,
				"Sarcomeres are components of myofibrils.");
			
				p.addAnswer(2, "actin",
				false,
				"Thin filaments are composed of actin.");
			
				p.addAnswer(3, "motor neurons",
				false,
				"Sarcomeres are a component of muscle fibers.");
			
				p.addAnswer(4, "myosin",
				true,
				"Thick filaments are composed of myosin.");
			
				p.addAnswer(5, "Z lines",
				false,
				"Z lines, while components of sarcomeres, are not a component of thick filaments.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336864;


		
		

		
			
			p.question = "The thin filaments of sarcomeres are composed of _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?49&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Skeletal Muscle Structure</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "myofibrils",
				false,
				"Sarcomeres are components of myofibrils.");
			
				p.addAnswer(2, "actin",
				true,
				"Thin filaments are composed of actin.");
			
				p.addAnswer(3, "motor neurons",
				false,
				"Sarcomeres are a component of muscle fibers (cells).");
			
				p.addAnswer(4, "myosin",
				false,
				"Thick filaments are composed of myosin.");
			
				p.addAnswer(5, "Z lines",
				false,
				"Z lines, while components of sarcomeres, are not a component of thin filaments.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336865;


		
		

		
			
			p.question = "A single muscle cell is referred to as a _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?49&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Skeletal Muscle Structure</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "myofibril",
				false,
				"Myofibrils are components of muscle cells.");
			
				p.addAnswer(2, "muscle fiber",
				true,
				"Muscle cells are referred to as muscle fibers.");
			
				p.addAnswer(3, "muscle neurons",
				false,
				"Neurons innervate muscles.");
			
				p.addAnswer(4, "sarcolemma",
				false,
				"\"Sarcolemma\" is the name given to the plasma membrane of a muscle cell.");
			
				p.addAnswer(5, "sarcomere",
				false,
				"Sarcomeres are components of muscle cells.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336866;


		
		

		
			
			p.question = "During the course of muscle contraction the potential energy stored in ATP is transferred to potential energy stored in _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?49&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Muscle Contraction</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the myosin head",
				true,
				"The hydrolysis of ATP causes the myosin head to change position, storing energy that will be used to contract the muscle.");
			
				p.addAnswer(2, "the myosin tail",
				false,
				"The myosin tail does not store the energy from a hydrolyzed molecule of ATP.");
			
				p.addAnswer(3, "the thin filament",
				false,
				"The thin filament does not store the energy from a hydrolyzed molecule of ATP.");
			
				p.addAnswer(4, "actin",
				false,
				"Actin does not store the energy from a hydrolyzed molecule of ATP.");
			
				p.addAnswer(5, "the Z line",
				false,
				"The Z line does not store the energy from a hydrolyzed molecule of ATP.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336867;


		
		

		
			
			p.question = "The release of _____ ions from the sarcoplasmic reticulum is required for skeletal muscle contraction. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?49&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Muscle Contraction</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "sodium",
				false,
				"The sarcoplasmic reticulum does not release sodium ions.");
			
				p.addAnswer(2, "phosphate",
				false,
				"The sarcoplasmic reticulum does not release phosphate ions.");
			
				p.addAnswer(3, "potassium",
				false,
				"The sarcoplasmic reticulum does not release potassium ions.");
			
				p.addAnswer(4, "chloride",
				false,
				"The sarcoplasmic reticulum does not release chloride ions.");
			
				p.addAnswer(5, "calcium",
				true,
				"Calcium ions interact with proteins on the thin filament, resulting in the exposure of the myosin-binding sites on the actin.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336868;


		
		

		
			
			p.question = "Myosin heads bind to _____, which they then pull and cause to slide toward the center of the sarcomere. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?49&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Muscle Contraction</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "thin filaments",
				true,
				"Myosin heads bind to thin filaments, release their bound ADP and phosphate, and bend, sliding the thin filaments toward the center of the sarcomere.");
			
				p.addAnswer(2, "Z lines",
				false,
				"Myosin heads do not bind to Z lines.");
			
				p.addAnswer(3, "sarcomeres",
				false,
				"Myosin heads, a component of thick filaments (themselves a component of sarcomeres), do not bind to entire sarcomeres.");
			
				p.addAnswer(4, "myofibrils",
				false,
				"Myosin heads are a component of thick filaments (themselves a component of sarcomeres, which are in turn a component of myofibrils); they do not bind to entire myofibrils.");
			
				p.addAnswer(5, "thick filaments",
				false,
				"Myosin heads, a component of thick filaments, do not bind to other thick filaments.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336869;


		
		

		
			
			p.question = "Of these events, the first to occur when a motor neuron stops sending an impulse to a muscle is _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?49&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Muscle Contraction</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the pumping of calcium ions out of the cytoplasm and back into the sarcoplasmic reticulum",
				true,
				"This is the first of the events that ultimately result in the relaxation of a muscle.");
			
				p.addAnswer(2, "the release of myosin heads from the thin filament",
				false,
				"This event is not the first to follow the cessation of the nerve impulse.");
			
				p.addAnswer(3, "thin filaments slide back to their relaxed positions",
				false,
				"This is the last of the events listed here.");
			
				p.addAnswer(4, "proteins on the thin filaments block actin\'s myosin-binding sites",
				false,
				"Another event must occur before this one can occur.");
			
				p.addAnswer(5, "all of these events occur simultaneously",
				false,
				"No, they don\'t.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

