

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "Investigation Quiz > How Is a Metabolic Pathway Analyzed?";
	ak.quiz_loc_with_commas = "Investigation Quiz, How Is a Metabolic Pathway Analyzed?";
	ak.quiz_title = "How Is a Metabolic Pathway Analyzed?";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 5;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 5;
	ak.non_essay_total = 0;
	ak.scored_item_total = 0;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337650;


		
		

		
			p.question = "In this activity, what type of media did you use to identify the specific mutation in the <i>Neurospora</i> strain?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337651;


		
		

		
			p.question = "Suppose you isolate a mutant strain of <i>Neurospora</i> that grows on media supplemented with arginine, agininosuccinate, citrulline, and ornithine, but not on unsupplemented minimal media. What type of enzyme do you think this mutant enzyme would require?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337652;


		
		

		
			p.question = "A doctor finds an accumulation of argininosuccinate in a newborn infant\'s blood. What is the most likely diagnosis?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337653;


		
		

		
			p.question = "The doctor treating the infant described in Question 3 determines that the infant has a mild form of the disorder. To control the deficiency, what supplement might be added to a high-calorie restricted-protein diet?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337654;


		
		

		
			p.question = "Which type of <i>Neurospora</i> mutant would require the same nutritional supplement as a person who has citrullinemia: argE, argF, argG, or argH?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

