

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "Investigation Quiz > Why Do AIDS Rates Differ Across the U.S.?";
	ak.quiz_loc_with_commas = "Investigation Quiz, Why Do AIDS Rates Differ Across the U.S.?";
	ak.quiz_title = "Why Do AIDS Rates Differ Across the U.S.?";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 9;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 9;
	ak.non_essay_total = 0;
	ak.scored_item_total = 0;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337669;


		
		

		
			p.question = "Consider the epidemiological evidence described in the table. Does this suggest that an infectious agent might cause AIDS? If so, how might that infectious agent be transmitted from person to person?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337670;


		
		

		
			p.question = "Write a hypothesis for the geographic or population factors you think might contribute to a high rate of AIDS.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337671;


		
		

		
			p.question = "What is your modified hypothesis?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337672;


		
		

		
			p.question = "What is your final hypothesis?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337673;


		
		

		
			p.question = "Write a hypothesis that might explain the mechanism that causes people of different ages to have different AIDS incidence rates.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337674;


		
		

		
			p.question = "How might you test this hypothesis?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337675;


		
		

		
			p.question = "Do the data show an effect of gender on age distribution for the likelihood of having AIDS? If you observed a gender effect on AIDS incidence, is it as you predicted in your Lab Notebook? If not, how can you explain the difference? How would you modify your ideas to better account for the data?";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337676;


		
		

		
			p.question = "Write a hypothesis (a possible answer) to your question.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

		// ----- essay ------------
		//
		
			p = new Problem("essay");
		
		p.id = 337677;


		
		

		
			p.question = "Using the data you collected, draw a conclusion and support it with reasons and evidence.";
			p.explanation = "";

		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

