

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "8: An Introduction to Metabolism > Activities Quiz";
	ak.quiz_loc_with_commas = "8: An Introduction to Metabolism, Activities Quiz";
	ak.quiz_title = "Activities Quiz";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 25;
	ak.non_essay_total = 25;
	ak.scored_item_total = 25;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334448;


		
		

		
			
			p.question = "Which of these is exhibiting kinetic energy? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?8&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Energy Transformations</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a rock on a mountain ledge",
				false,
				"The rock contains potential energy.");
			
				p.addAnswer(2, "the high-energy phosphate bonds of a molecule of ATP",
				false,
				"This is potential energy.");
			
				p.addAnswer(3, "a person sitting on a couch while watching TV",
				false,
				"This person is exhibiting potential energy (maybe).");
			
				p.addAnswer(4, "an archer with a flexed bow",
				false,
				"This is potential energy.");
			
				p.addAnswer(5, "a space station orbiting Earth",
				true,
				"Kinetic energy is energy of motion.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334449;


		
		

		
			
			p.question = "\"Conservation of energy\" refers to the fact that _____.  (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?8&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Energy Transformations</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the entropy of the universe is always increasing",
				false,
				"While true, this is not what is meant by conservation of energy.");
			
				p.addAnswer(2, "if you conserve energy you will not be as tired",
				false,
				"This is not what is meant by conservation of energy.");
			
				p.addAnswer(3, "the net amount of disorder is always increasing",
				false,
				"While true, this is not what is meant by conservation of energy.");
			
				p.addAnswer(4, "no chemical reaction is 100 percent efficient",
				false,
				"While true, this is not what is meant by conservation of energy.");
			
				p.addAnswer(5, "energy cannot be created or destroyed but can be converted from one form to another",
				true,
				"This is what is meant by conservation of energy.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334450;


		
		

		
			
			p.question = "Chemical energy is a form of _____ energy. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?8&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Energy Transformations</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "kinetic energy",
				false,
				"Kinetic energy is the energy of motion.");
			
				p.addAnswer(2, "heat energy",
				false,
				"However, chemical energy can be released as heat.");
			
				p.addAnswer(3, "potential",
				true,
				"Chemical energy is a form of stored energy.");
			
				p.addAnswer(4, "motion",
				false,
				"Kinetic energy is the energy of motion.");
			
				p.addAnswer(5, "entropic",
				false,
				"Entropy is a measure of disorder.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334451;


		
		

		
			
			p.question = "In your body, what process converts the chemical energy found in glucose into the chemical energy found in ATP? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?8&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Energy Transformations</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "potentiation",
				false,
				"This process is concerned with the nervous system.");
			
				p.addAnswer(2, "cellular respiration",
				true,
				"This is the name given to the process by which the body converts food energy to energy stored in ATP.");
			
				p.addAnswer(3, "digestion",
				false,
				"However, this process may be involved in making glucose available to your cells.");
			
				p.addAnswer(4, "anabolism",
				false,
				"In an anabolic reaction the products are more complex than the reactants.");
			
				p.addAnswer(5, "redox",
				false,
				"While redox reactions are involved, this is not the name of the entire process.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334452;


		
		

		
			
			p.question = "Which of these are by-products of cellular respiration? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?8&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Energy Transformations</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "ATP, carbon dioxide, and water",
				false,
				"While ATP is produced by cellular respiration, it is not considered a by-product of the process.");
			
				p.addAnswer(2, "glucose, carbon dioxide, and water",
				false,
				"The process of cellular respiration may break down glucose.");
			
				p.addAnswer(3, "ATP and carbon dioxide",
				false,
				"While ATP is produced by cellular respiration, it is not considered a by-product of the process.");
			
				p.addAnswer(4, "heat, carbon dioxide, and water",
				true,
				"These are the by-products of cellular respiration.");
			
				p.addAnswer(5, "carbon dioxide and water",
				false,
				"While correct this choice is incomplete.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334453;


		
		

		
			
			p.question = "Which of these is ATP? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?8&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Structure of ATP</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "<IMG SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0806a1.jpg\" ALT=\"Question #6, Answer #1\" BORDER=\"1\"><br>",
				false,
				"ATP does not contain deoxyribose.");
			
				p.addAnswer(2, "<IMG SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0806a2.jpg\" ALT=\"Question #6, Answer #2\" BORDER=\"1\"><br>",
				false,
				"Consider how many phosphate groups ATP has.");
			
				p.addAnswer(3, "<IMG SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0806a3.jpg\" ALT=\"Question #6, Answer #3\" BORDER=\"1\"><br>",
				true,
				"This is ATP.");
			
				p.addAnswer(4, "<IMG SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0806a4.jpg\" ALT=\"Question #6, Answer #4\" BORDER=\"1\"><br>",
				false,
				"Consider what the \"T\" stands for.");
			
				p.addAnswer(5, "<IMG SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0806a5.jpg\" ALT=\"Question #6, Answer #5\" BORDER=\"1\"><br>",
				false,
				"ATP does not contain deoxyribose.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334454;


		
		

		
			
			p.question = "What type of reaction breaks the bonds that join the phosphate groups in an ATP molecule? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?8&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Structure of ATP</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "anabolism",
				false,
				"In anabolic reactions the products are more complex than the reactants.");
			
				p.addAnswer(2, "hydrolysis",
				true,
				"Hydrolysis involves breaking bonds with the addition of water.");
			
				p.addAnswer(3, "dehydration decomposition",
				false,
				"Water is removed when forming bonds.");
			
				p.addAnswer(4, "dehydration synthesis",
				false,
				"Dehydration synthesis would add a phosphate group.");
			
				p.addAnswer(5, "entropic",
				false,
				"However, breaking these bonds increases entropy.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334455;


		
		

		
			
			p.question = "In this reaction _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?8&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Chemical Reactions and ATP</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0808q.jpg\" ALT=\"Question #8\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the products have less potential energy than the reactants",
				true,
				"This is what is shown by the graph.");
			
				p.addAnswer(2, "CD is a product",
				false,
				"CD is a reactant.");
			
				p.addAnswer(3, "entropy has decreased",
				false,
				"Entropy always increases.");
			
				p.addAnswer(4, "the products have been rearranged to form reactants",
				false,
				"Reactants are rearranged to form products.");
			
				p.addAnswer(5, "AC is a reactant",
				false,
				"AC is a product.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334456;


		
		

		
			
			p.question = "In this reaction _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?8&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Chemical Reactions and ATP</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0809q.jpg\" ALT=\"Question #9\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "the chemical energy of the products is greater than that of the reactants",
				false,
				"Chemical energy is a form of potential energy.");
			
				p.addAnswer(2, "the kinetic energy of the reactants is less than that of the products",
				false,
				"Consider what has happened to the amount of chemical energy.");
			
				p.addAnswer(3, "entropy has decreased",
				false,
				"Entropy has increased.");
			
				p.addAnswer(4, "disorder has decreased",
				false,
				"Disorder has increased.");
			
				p.addAnswer(5, "heat has been released to the environment",
				true,
				"The potential energy of the products is less than that of the reactants.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334457;


		
		

		
			
			p.question = "The reaction A --> B + C + heat is released in a(n) _____ reaction. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?8&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Chemical Reactions and ATP</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "endergonic",
				false,
				"Consider the meaning of the suffix \"ender-.\"");
			
				p.addAnswer(2, "dehydration synthesis",
				false,
				"This is not a synthesis reaction.");
			
				p.addAnswer(3, "exergonic",
				true,
				"Energy has been released.");
			
				p.addAnswer(4, "exchange",
				false,
				"This is not an exchange reaction.");
			
				p.addAnswer(5, "anabolic",
				false,
				"In an anabolic reaction the products are more complex than the reactants.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334458;


		
		

		
			
			p.question = "A(n) _____ reaction occurs spontaneously. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?8&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Chemical Reactions and ATP</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "anabolic",
				false,
				"In anabolic reactions the products have more potential energy than the reactants.");
			
				p.addAnswer(2, "endergonic",
				false,
				"In endergonic reactions the products have more potential energy than the reactants.");
			
				p.addAnswer(3, "chemical",
				false,
				"Some chemical reactions occur spontaneously and some don\'t.");
			
				p.addAnswer(4, "exergonic",
				true,
				"In exergonic reactions the products have less potential energy than the reactants.");
			
				p.addAnswer(5, "kinetic",
				false,
				"Kinetic energy is the energy of motion.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334459;


		
		

		
			
			p.question = "Which of these reactions requires a net input of energy from its surroundings? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?8&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Chemical Reactions and ATP</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "exergonic",
				false,
				"The products of exergonic reactions have less potential energy than the reactants.");
			
				p.addAnswer(2, "hydrolysis",
				false,
				"The products of such a reaction have less potential energy than the reactants.");
			
				p.addAnswer(3, "endergonic",
				true,
				"The products of endergonic reactions have more potential energy than the reactants.");
			
				p.addAnswer(4, "ATP --> ADP + P",
				false,
				"This reaction releases energy.");
			
				p.addAnswer(5, "catabolic",
				false,
				"The products of catabolic reactions have less potential energy than the reactants.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334460;


		
		

		
			
			p.question = "In cells, what is usually the immediate source of energy for an endergonic reaction? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?8&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Chemical Reactions and ATP</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "glucose",
				false,
				"While a source of energy, glucose is not the immediate source of energy for such reactions.");
			
				p.addAnswer(2, "as spontaneous reactions, endergonic reactions do not need an addition of energy",
				false,
				"Endergonic reactions require energy from their surroundings.");
			
				p.addAnswer(3, "ADP",
				false,
				"Almost correct.");
			
				p.addAnswer(4, "ATP",
				true,
				"The hydrolysis of ATP provides the energy needed for an endergonic reaction.");
			
				p.addAnswer(5, "sugar",
				false,
				"While a source of energy, sugar is not the immediate source of energy for such reactions.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334461;


		
		

		
			
			p.question = "The reaction ADP + P --> ATP is a(n) _____ reaction. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?8&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Chemical Reactions and ATP</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "hydrolysis",
				false,
				"Hydrolysis breaks molecules apart.");
			
				p.addAnswer(2, "exergonic",
				false,
				"Energy has been released in this type of reaction.");
			
				p.addAnswer(3, "chemical",
				false,
				"Be more specific.");
			
				p.addAnswer(4, "endergonic",
				true,
				"Energy has been acquired from the surroundings.");
			
				p.addAnswer(5, "spontaneous",
				false,
				"Energy has been acquired from the surroundings.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334462;


		
		

		
			
			p.question = "The energy for an endergonic reaction comes from a(n) _____ reaction. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?8&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Chemical Reactions and ATP</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "anabolic",
				false,
				"Anabolic reactions are endergonic.");
			
				p.addAnswer(2, "exergonic",
				true,
				"The energy released by an exergonic reaction can be used to drive an endergonic reaction.");
			
				p.addAnswer(3, "synthesis",
				false,
				"Synthesis reactions are endergonic.");
			
				p.addAnswer(4, "ADP + P --> ATP",
				false,
				"This is an endergonic reaction.");
			
				p.addAnswer(5, "glucose + glucose --> maltose",
				false,
				"This is an endergonic reaction.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334463;


		
		

		
			
			p.question = "What is the fate of the phosphate group that is removed when ATP is converted to ADP? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?8&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Chemical Reactions and ATP</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "It is acquired by a reactant in an endergonic reaction.",
				true,
				"By acquiring the phosphate group the reactant acquires energy.");
			
				p.addAnswer(2, "It is used to convert an ATP into an AQP.",
				false,
				"What is an AQP?");
			
				p.addAnswer(3, "It is acquired by a reactant in a spontaneous reaction.",
				false,
				"Spontaneous reactions are exergonic.");
			
				p.addAnswer(4, "It is acquired by a reactant in an exergonic reaction.",
				false,
				"Exergonic reactions are spontaneous reactions.");
			
				p.addAnswer(5, "It is broken down into one phosphorus and four oxygen atoms.",
				false,
				"The phosphate group is not broken down.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334464;


		
		

		
			
			p.question = "This graph illustrates a(n) _____ reaction. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?8&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Chemical Reactions and ATP</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0817q.jpg\" ALT=\"Question #17\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "spontaneous",
				false,
				"In a spontaneous reaction the products contain less potential energy than the reactants.");
			
				p.addAnswer(2, "endergonic",
				true,
				"The products contain more potential energy than the reactants.");
			
				p.addAnswer(3, "hydrolysis",
				false,
				"The products of the illustrated reaction contain more potential energy than the reactants.");
			
				p.addAnswer(4, "exergonic",
				false,
				"The products of the illustrated reaction contain more potential energy than the reactants.");
			
				p.addAnswer(5, "catabolic",
				false,
				"In a catabolic reaction the products contain less potential energy than the reactants.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334465;


		
		

		
			
			p.question = "Select the INCORRECT association. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?8&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Chemical Reactions and ATP</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "potential energy ... positional energy",
				false,
				"Potential energy is energy of position.");
			
				p.addAnswer(2, "exergonic ... uphill",
				true,
				"Exergonic reactions release energy.");
			
				p.addAnswer(3, "enzyme ... protein",
				false,
				"Enzymes are proteins.");
			
				p.addAnswer(4, "exergonic ... spontaneous",
				false,
				"Exergonic reactions occur spontaneously.");
			
				p.addAnswer(5, "kinetic energy ... motion",
				false,
				"Kinetic energy is the energy of motion.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334466;


		
		

		
			
			p.question = "What is energy coupling? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?8&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Chemical Reactions and ATP</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "a description of the energetic relationship between the reactants and products in an exergonic reaction",
				false,
				"This is not what energy coupling means.");
			
				p.addAnswer(2, "the use of an enzyme to reduce E<sub>A</sub>",
				false,
				"While enzymes reduce a reaction\'s energy of activation, that is not what is meant by energy coupling.");
			
				p.addAnswer(3, "a barrier to the initiation of a reaction",
				false,
				"Such a barrier is referred to as the energy of activation.");
			
				p.addAnswer(4, "the use of energy released from an exergonic reaction to drive an endergonic reaction",
				true,
				"This is energy coupling.");
			
				p.addAnswer(5, "the hydrolysis of ATP to ADP + P",
				false,
				"Now consider the fate of the phosphate that has been released.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334467;


		
		

		
			
			p.question = "Enzymes are _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?8&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: How Enzymes Work</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "carbohydrates",
				false,
				"Enzymes are not carbohydrates.");
			
				p.addAnswer(2, "minerals",
				false,
				"While some catalysts are minerals, enzymes are not minerals.");
			
				p.addAnswer(3, "lipids",
				false,
				"Enzymes are not lipids.");
			
				p.addAnswer(4, "nucleic acids",
				false,
				"Enzymes are not nucleic acids.");
			
				p.addAnswer(5, "proteins",
				true,
				"Enzymes are proteins.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334468;


		
		

		
			
			p.question = "Enzymes work by _____.  (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?8&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: How Enzymes Work</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "adding a phosphate group to a reactant",
				false,
				"ATP adds a phosphate group to a reactant.");
			
				p.addAnswer(2, "decreasing the potential energy difference between reactant and product",
				false,
				"Enzymes do not affect this potential energy difference.");
			
				p.addAnswer(3, "adding energy to a reaction",
				false,
				"Enzymes are not an energy source.");
			
				p.addAnswer(4, "increasing the potential energy difference between reactant and product",
				false,
				"Enzymes do not affect this potential energy difference.");
			
				p.addAnswer(5, "reducing E<sub>A</sub>",
				true,
				"Enzymes work by reducing the energy of activation.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334469;


		
		

		
			
			p.question = "An enzyme _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?8&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: How Enzymes Work</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "is a source of energy for endergonic reactions",
				false,
				"Enzymes do not contribute energy to a reaction.");
			
				p.addAnswer(2, "is an organic catalyst",
				true,
				"Enzymes are proteins that behave as catalysts.");
			
				p.addAnswer(3, "increases the E<sub>A</sub> of a reaction",
				false,
				"Enzymes decrease the energy of activation.");
			
				p.addAnswer(4, "is a inorganic catalyst",
				false,
				"Enzymes are organic.");
			
				p.addAnswer(5, "can bind to nearly any molecule",
				false,
				"Enzymes are selective.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334470;


		
		

		
			
			p.question = "What name is given to the reactants in an enzymatically catalyzed reaction? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?8&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: How Enzymes Work</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "E<sub>A</sub>",
				false,
				"\"E<sub>A</sub>\" stands for energy of activation.");
			
				p.addAnswer(2, "products",
				false,
				"Products are the end result of a reaction.");
			
				p.addAnswer(3, "active sites",
				false,
				"An active site is located on an enzyme.");
			
				p.addAnswer(4, "reactors",
				false,
				"No, that is incorrect.");
			
				p.addAnswer(5, "substrate",
				true,
				"This is the name given to the reactants in an enzymatically catalyzed reaction.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334471;


		
		

		
			
			p.question = "As a result of its involvement in a reaction, an enzyme _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?8&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: How Enzymes Work</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "loses a phosphate group",
				false,
				"An enzyme does not contribute a phosphate to a reaction that it catalyzes.");
			
				p.addAnswer(2, "permanently alters its shape.",
				false,
				"An enzyme\'s shape is not permanently altered as a result of its participation in a reaction.");
			
				p.addAnswer(3, "loses energy",
				false,
				"Enzymes do not contribute energy to reactions that they catalyze.");
			
				p.addAnswer(4, "is unchanged",
				true,
				"Enzymes are not changed as a result of their participation in a reaction.");
			
				p.addAnswer(5, "is used up",
				false,
				"Enzymes are not used up by the reactions they catalyze.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 334472;


		
		

		
			
			p.question = "What is the correct label for \"A\"? (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?8&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: How Enzymes Work</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/0825q.jpg\" ALT=\"Question #25\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "ATP",
				false,
				"ATP is an immediate source of energy for a reaction but is not the correct label.");
			
				p.addAnswer(2, "energy of activation",
				true,
				"The energy of activation must be overcome in order for a reaction to proceed.");
			
				p.addAnswer(3, "substrate energy",
				false,
				"A substrate is a reactant in an enzymatically catalyzed reaction.");
			
				p.addAnswer(4, "enzyme energy",
				false,
				"Enzymes do not contribute energy to a reaction.");
			
				p.addAnswer(5, "uphill",
				false,
				"While there is an uphill movement of energy, this is not the correct label.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

