

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "30: Plant Diversity II: The Evolution of Seed Plants > Practice Test";
	ak.quiz_loc_with_commas = "30: Plant Diversity II: The Evolution of Seed Plants, Practice Test";
	ak.quiz_title = "Practice Test";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 33;
	ak.non_essay_total = 33;
	ak.scored_item_total = 33;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335802;


		
		

		
			
			p.question = "Which of the following adaptations is common to all seed plants? (<script type=\"text/javascript\">ebook(\'3001\',\'quiz\')</script>)";
			p.incorrect_any_expl = "No. This is an adaptation common to all seed plants, but there is a better answer.";
			p.incorrect_any_expl_flag = 1;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "reduced gametophytes",
				false,
				"");
			
				p.addAnswer(2, "heterospory",
				false,
				"");
			
				p.addAnswer(3, "pollen",
				false,
				"");
			
				p.addAnswer(4, "ovules",
				false,
				"");
			
				p.addAnswer(5, "all of the above",
				true,
				"Correct. All of these adaptations are common to seed plants.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335803;


		
		

		
			
			p.question = "Which one of the following is true of seed plants, but not true of seedless plants? (<script type=\"text/javascript\">ebook(\'3001\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The sporophyte is dependent on the gametophyte.",
				false,
				"No. In seed plants, the sporophyte is not dependent on the gametophyte.");
			
				p.addAnswer(2, "The sporophyte is large, and the gametophyte is small and independent.",
				false,
				"No. The seed plant gametophyte is not independent.");
			
				p.addAnswer(3, "The gametophyte is reduced and dependent on the sporophyte.",
				true,
				"Correct. The gametophytes of seedless vascular plants develop in the soil as an independent generation. The minute gametophytes of seed plants are protected from desiccation by being retained within the moist reproductive tissue of the sporophyte generation.");
			
				p.addAnswer(4, "The spore is the main means of dispersing the offspring.",
				false,
				"No. For seed plants, seeds are the main means of dispersing offspring.");
			
				p.addAnswer(5, "A film of water is necessary for sperm to come in contact with eggs.",
				false,
				"No. This is true of the flagellated sperm found in most seedless plants.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335804;


		
		

		
			
			p.question = "The diploid generation of the plant life cycle always _____. (<script type=\"text/javascript\">ebook(\'3001\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "produces spores",
				true,
				"Correct. The diploid generation of the plant life cycle always produces spores.");
			
				p.addAnswer(2, "is called the gametophyte",
				false,
				"No. The gametophyte is the haploid generation.");
			
				p.addAnswer(3, "is larger and more conspicuous than the haploid stage",
				false,
				"No. In mosses and bryophytes the haploid stage is larger and more conspicuous than the diploid stage.");
			
				p.addAnswer(4, "develops from a spore",
				false,
				"No. It develops from gametes.");
			
				p.addAnswer(5, "produces eggs and sperm",
				false,
				"No. The gametophyte produces gametes.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335805;


		
		

		
			
			p.question = "The closest seedless relatives of seed plants produce one kind of spore that gives rise to a bisexual gametophyte. What does this suggest about the ancestors of seed plants? (<script type=\"text/javascript\">ebook(\'3001\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "They were gymnosperms.",
				false,
				"No. Gymnosperms are seed plants.");
			
				p.addAnswer(2, "They were bryophytes.",
				false,
				"No. Since bryophytes are nonvascular plants, this is not likely.");
			
				p.addAnswer(3, "They were heterosporous.",
				false,
				"No. Seed plants are generally heterosporous, which means that they produce megaspores that give rise to female gametophytes and microspores that give rise to male gametophytes.");
			
				p.addAnswer(4, "They were homosporous.",
				true,
				"Correct. The closest relatives of seed plants are homosporous, suggesting that seed plants also had homosporous ancestors.");
			
				p.addAnswer(5, "They produced separate male and female gametophytes.",
				false,
				"No. The closest relatives of seed plants are homosporous, suggesting that seed plants also had homosporous ancestors.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335806;


		
		

		
			
			p.question = "The eggs of seed plants are fertilized within ovules, and the ovules then develop into _____. (<script type=\"text/javascript\">ebook(\'3001\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "seeds",
				true,
				"Correct. Ovules develop into seeds that are enclosed within the mature ovary.");
			
				p.addAnswer(2, "spores",
				false,
				"No. Spores give rise to gametophytes.");
			
				p.addAnswer(3, "gametophytes",
				false,
				"No. Gametophytes produce the male and female gametes.");
			
				p.addAnswer(4, "fruit",
				false,
				"No. The mature ovules are enclosed within the fruit.");
			
				p.addAnswer(5, "ovaries",
				false,
				"No. The ovules are contained within the ovary, the wall of which will later develop into fruit.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335807;


		
		

		
			
			p.question = "The cells within pollen grains are _____ and together comprise the _____. (<script type=\"text/javascript\">ebook(\'3001\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "diploid; spores",
				false,
				"No. The pollen grain is the male gametophyte (haploid) and produces the sperm.");
			
				p.addAnswer(2, "diploid; sperm nuclei",
				false,
				"No. However, this choice is partially correct.");
			
				p.addAnswer(3, "haploid; spores",
				false,
				"No. However, this choice is partially correct.");
			
				p.addAnswer(4, "haploid; male gametophyte",
				true,
				"Correct. Both egg cells and pollen cells are haploid and would have half the diploid chromosome number. The pollen grain is the male gametophyte and produces the sperm.");
			
				p.addAnswer(5, "diploid; a new sporophyte",
				false,
				"No. The pollen grain is the male gametophyte (haploid) and produces the sperm.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335808;


		
		

		
			
			p.question = "Which example below is evidence provided by living gymnosperms of an evolutionary transition between seedless and seed plants? (<script type=\"text/javascript\">ebook(\'3001\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The sperm of some gymnosperms have flagella.",
				true,
				"Correct. Although the sperm of seed plants do not require water or mobility, some gymnosperm sperm still retain the ancient flagellated condition.");
			
				p.addAnswer(2, "The sperm of gymnosperms do not require water or mobility for fertilization.",
				false,
				"No. This is not evidence of a transition. The sperm of seed plants do not require water or mobility to fertilize an egg.");
			
				p.addAnswer(3, "Some gymnosperms do not have reduced gametophytes.",
				false,
				"No. Reduced gametophytes are a characteristic of all seed plants.");
			
				p.addAnswer(4, "Gymnosperms only have one integument.",
				false,
				"No. This is true, but it is not evidence of a transition from seedless to seed plants.");
			
				p.addAnswer(5, "In gymnosperms, two sperm are discharged into the pollen tube.",
				false,
				"No. This is true, but it is not evidence of a transition from seedless to seed plants.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335809;


		
		

		
			
			p.question = "Seeds have advantages over spores. For example, _____. (<script type=\"text/javascript\">ebook(\'3001\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "seeds contain embryonic plants, an abundant food supply, and a protective covering",
				true,
				"Correct. A seed contains a multicellular, well-developed young plant, with embryonic root, stem, and one or more leaves. The seed contains an abundant food supply, nourishing the plant from germination to self-sufficiency. It is protected by a resistant seed coat. Both spores and seeds can live for extended periods of time under harsh conditions, germinating when conditions allow.");
			
				p.addAnswer(2, "seeds can survive for extended periods of time at reduced metabolic rates",
				false,
				"No. This trait is not unique to seeds.");
			
				p.addAnswer(3, "seeds are single cells, demanding fewer nutrients from the parent plants",
				false,
				"No. Seeds are multicellular.");
			
				p.addAnswer(4, "seeds can survive even in conditions that are unfavorable for the parent plants",
				false,
				"No. Spores can also survive under such conditions.");
			
				p.addAnswer(5, "most seeds are poisonous; therefore, they are not consumed by animals and persist in the environment for long periods of time",
				false,
				"No. It is not true to say that most seeds are poisonous. When an animal consumes seeds, it is often facilitating seed dispersal.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335810;


		
		

		
			
			p.question = "Which gymnosperm phylum below is characterized by large cones and fern-like leaves and thrived during the Mesozoic? (<script type=\"text/javascript\">ebook(\'3002\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Anthopyta",
				false,
				"No. This phylum includes the angiosperms.");
			
				p.addAnswer(2, "Gnetophyta",
				false,
				"No. This phylum contains the genera <i>Gnetum</i>, <i>Ephedra</i>, and <i>Welwitschia</i>.");
			
				p.addAnswer(3, "Coniferophyta",
				false,
				"No. This phylum consists of about 600 species of conifers.");
			
				p.addAnswer(4, "Ginkgophyta",
				false,
				"No. The only extant species of this phylum is <i>Ginkgo biloba</i>.");
			
				p.addAnswer(5, "Cycadophyta",
				true,
				"Correct. Cycads are the second largest group of gymnosperms behind conifers. Only about 130 species survive today, but they thrived during the Mesozoic era. They have both large cones and fern-like leaves.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335811;


		
		

		
			
			p.question = "Dietary supplements and decongestants containing ephedrine have recently become more strongly regulated in the United States. Ephedrine is an extract of a plant belonging to which phylum? (<script type=\"text/javascript\">ebook(\'3002\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "phylum Anthopyta",
				false,
				"No. This phylum includes the angiosperms.");
			
				p.addAnswer(2, "phylum Gnetophyta",
				true,
				"Correct. This phylum contains the genera <i>Gnetum</i>, <i>Ephedra</i>, and <i>Welwitschia</i>.");
			
				p.addAnswer(3, "phylum Coniferophyta",
				false,
				"No. The genus Ephedra belongs to the phylum Gnetophyta.");
			
				p.addAnswer(4, "phylum Ginkgophyta",
				false,
				"No. The only extant species of this phylum is <i>Ginkgo biloba</i>.");
			
				p.addAnswer(5, "phylum Cycadophyta",
				false,
				"No. The genus Ephedra belongs to the phylum Gnetophyta.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335812;


		
		

		
			
			p.question = "What significant change occurred on Earth between the Carboniferous period and the Permian that most likely contributed to the success of the gymnosperms? (<script type=\"text/javascript\">ebook(\'3002\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The climate became drier and warmer.",
				true,
				"Correct. A drier, warmer climate was more suited to seed plants than seedless plants, which depend on a film of moisture for fertilization to occur.");
			
				p.addAnswer(2, "An asteroid hit Earth, leading to mass extinctions that made way for gymnosperms to take over lands where other plants had perished.",
				false,
				"No. Many hypothesize that an asteroid collision may have led to the mass extinctions that occurred at the end of the Mesozoic. The planet has gradually cooled since, and angiosperms now dominate most terrestrial ecosystems.");
			
				p.addAnswer(3, "Reptiles decreased in diversity and were replaced with amphibians better adapted for seed dispersal.",
				false,
				"No. Actually, reptiles increased in diversity during this period.");
			
				p.addAnswer(4, "The breakup of Pangaea changed the flora and fauna of Earth dramatically.",
				false,
				"No. The formation of Pangaea may have been one reason for the climate change that occurred during the Permian.");
			
				p.addAnswer(5, "Insects developed flight.",
				false,
				"No. Gymnosperms are wind-pollinated.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335813;


		
		

		
			
			p.question = "What is located in the scalelike structures packed densely in pollen cones? (<script type=\"text/javascript\">ebook(\'3002\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "sporophytes",
				false,
				"No. Cones grow on sporophytes.");
			
				p.addAnswer(2, "sporangia",
				true,
				"Correct. In conifers, the two types of spores are produced by separate cones.");
			
				p.addAnswer(3, "developing seedlings",
				false,
				"No. Seedlings sprout from dispersed seeds after germination.");
			
				p.addAnswer(4, "megasporocytes",
				false,
				"No. These would be found in ovulate cones.");
			
				p.addAnswer(5, "developing pollen tubes",
				false,
				"No. These would be found in ovulate cones after pollination.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335814;


		
		

		
			
			p.question = "Each pollen grain of a gymnosperm contains a _____. (<script type=\"text/javascript\">ebook(\'3002\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "male gametophyte",
				true,
				"Correct. The haploid pollen grains contain the male gametophytes.");
			
				p.addAnswer(2, "progymnosperm",
				false,
				"No. A progymnosperm is a transitional species of seedless vascular plant such as <i>Archaeopteris</i>.");
			
				p.addAnswer(3, "microsporocyte",
				false,
				"No. The microsporocytes give rise to microspores by way of meiosis.");
			
				p.addAnswer(4, "megasporocyte",
				false,
				"No. These are found in ovulate cones and give rise to megaspores by way of meiosis.");
			
				p.addAnswer(5, "fertilized ovule",
				false,
				"No. The pollen grain contains the male gametophyte. A fertilized ovule would be found in the ovulate cone after fertilization.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335815;


		
		

		
			
			p.question = "In ovulate cones megasporocytes undergo _______ and produce ______ megaspores. (<script type=\"text/javascript\">ebook(\'3002\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Mitosis; diploid",
				false,
				"No. Meiosis produces haploid megaspores.");
			
				p.addAnswer(2, "Meiosis; diploid",
				false,
				"No. Meiosis produces haploid megaspores.");
			
				p.addAnswer(3, "Mitosis; haploid",
				false,
				"No. Meiosis produces haploid megaspores.");
			
				p.addAnswer(4, "Meiosis; haploid",
				true,
				"Correct. Meiosis produces haploid megaspores.");
			
				p.addAnswer(5, "Depending on environmental conditions, any of the above may occur.",
				false,
				"No. Megasporocytes always give rise to megaspores through meiosis.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335816;


		
		

		
			
			p.question = "In a typical conifer, how long does it take for fertilization to occur after pollination? (<script type=\"text/javascript\">ebook(\'3002\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "The processes are simultaneous.",
				false,
				"No. The process can take a year or longer.");
			
				p.addAnswer(2, "one season",
				false,
				"No. The process can take a year or longer.");
			
				p.addAnswer(3, "one year",
				true,
				"Correct. It takes nearly three years to produce the male and female gametophytes, bring them together during pollination, and form mature seeds from the fertilized ovules. The period from pollination to fertilization takes about one year of that time.");
			
				p.addAnswer(4, "three years",
				false,
				"No. It takes nearly three years to produce the male and female gametophytes, bring them together during pollination, and form mature seeds from the fertilized ovules. The period from pollination to fertilization takes about one year of that time.");
			
				p.addAnswer(5, "Pollination occurs after fertilization.",
				false,
				"No. Certainly not. Pollination is the process in which pollen comes in contact with parts of the plant containing ovules. This contact must occur in order for fertilization to occur.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335817;


		
		

		
			
			p.question = "Which types of angiosperms would most likely be wind-pollinated rather than animal-pollinated? (<script type=\"text/javascript\">ebook(\'3003\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "maize and wheat",
				false,
				"No. This answer is correct, but there is a better answer.");
			
				p.addAnswer(2, "oak and maple trees",
				false,
				"No. This answer is correct, but there is a better answer.");
			
				p.addAnswer(3, "roses and tiger lilies",
				false,
				"No. Typically, angiosperms with brightly colored fragrant flowers are animal-pollinated.");
			
				p.addAnswer(4, "The first and second answers are correct.",
				true,
				"Correct. Wind-pollination among flowered plants is common for plants that occur in dense populations, such as grasses and tree species in temperate forests.");
			
				p.addAnswer(5, "None of the choices are correct. Plants with flowers are not wind-pollinated.",
				false,
				"No. Wind-pollination among flowered plants is common for plants that occur in dense populations, such as grasses and tree species in temperate forests.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335818;


		
		

		
			
			p.question = "Like gymnosperms, many grasses and angiosperm trees are wind-pollinated. To conserve energy, these angiosperms do not produce complete flowers (complete flowers have all four of the basic parts). Which part would be unnecessary for wind-pollinated angiosperms? (<script type=\"text/javascript\">ebook(\'3003\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "petals",
				true,
				"Correct. Petals are nonreproductive parts of a flower. They advertise a flower to pollinators and would not be needed by wind-pollinated angiosperms.");
			
				p.addAnswer(2, "sepals",
				false,
				"No. Sepals protect the flower prior to its opening, and they are often photosynthetic.");
			
				p.addAnswer(3, "anthers",
				false,
				"No. Anthers bear pollen.");
			
				p.addAnswer(4, "ovaries",
				false,
				"No. Ovaries are female reproductive structures.");
			
				p.addAnswer(5, "fruits",
				false,
				"No. Fruits play a role in seed dispersal.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335819;


		
		

		
			
			p.question = "The portion of a flower that receives the pollen is the _____. (<script type=\"text/javascript\">ebook(\'3003\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "filament",
				false,
				"No. The filament is a stalk that bears the anther.");
			
				p.addAnswer(2, "ovary",
				false,
				"No. The ovary houses the ovules.");
			
				p.addAnswer(3, "anther",
				false,
				"No. The anther produces pollen.");
			
				p.addAnswer(4, "stigma",
				true,
				"Correct. The sticky stigma receives the pollen.");
			
				p.addAnswer(5, "style",
				false,
				"No. The style connects the stigma to the ovary.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335820;


		
		

		
			
			p.question = "During pollination, pollen grains are transferred from the _____ to the _____. (<script type=\"text/javascript\">ebook(\'3003\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "ovary; anther",
				false,
				"No. The ovary is the site of ovum production, and ova are not transferred during pollination.");
			
				p.addAnswer(2, "stigma; ovary",
				false,
				"No. The stigma, style, and ovary are all parts of the carpel.");
			
				p.addAnswer(3, "anther; sepal",
				false,
				"No. A sepal is a structure that encloses and protects the flower bud.");
			
				p.addAnswer(4, "carpel; stigma",
				false,
				"No. The stigma forms a portion of the carpel.");
			
				p.addAnswer(5, "anther; stigma",
				true,
				"Correct. Pollen is produced within the anther and is transferred to the stigma, from which it can grow to the ova.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335821;


		
		

		
			
			p.question = "A pea pod is formed from _____. A pea inside the pod is formed from _____. (<script type=\"text/javascript\">ebook(\'3003\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "an ovule; a carpel",
				false,
				"No. An ovule contains the female gametophyte and develops into the seed coat, not into the pea pod. Only a portion of the carpel is involved in the formation of the pea and pea pod.");
			
				p.addAnswer(2, "an ovary; an ovule",
				true,
				"Correct. A pod is a fruit, and a fruit develops from an ovary. The pea develops from an ovule surrounding a zygote and its food supply.");
			
				p.addAnswer(3, "an ovary; a pollen grain",
				false,
				"No. The ovary does develop into the pea pod. However, a pollen grain, which carries the male gamete, does not develop into the pea.");
			
				p.addAnswer(4, "an anther; an ovule",
				false,
				"No. The anther houses sporangia, which give rise to the male gametophyte. However, the pea does develop from the ovule and the tissues that it surrounds.");
			
				p.addAnswer(5, "endosperm; an ovary",
				false,
				"No. Endosperm is a food source found within a seed. The ovary develops into the fruit and not into the pea.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335822;


		
		

		
			
			p.question = "After fertilization, the _____ develops into a seed and the _____ develops into a fruit. (<script type=\"text/javascript\">ebook(\'3003\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "ovule; ovary",
				true,
				"Correct. The integuments of the ovule develop into the seed coat, which gives rise to the seed, and the ovary develops into a fruit.");
			
				p.addAnswer(2, "pollen grain; ovule",
				false,
				"No. The pollen grain carries the male gamete. The ovule houses the female gametophyte and develops into the seed coat.");
			
				p.addAnswer(3, "ovary; ovule",
				false,
				"No. The ovary develops into a fruit, and the ovule houses the female gametophyte and develops into the seed coat.");
			
				p.addAnswer(4, "egg; ovule",
				false,
				"No. Fertilization of the egg gives rise to an embryo. The female gametophyte, which produces the egg, is housed within the ovule.");
			
				p.addAnswer(5, "egg; ovary",
				false,
				"No. Fertilization of the egg gives rise to an embryo, which is contained within a seed. However, the ovary does develop into a fruit.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335823;


		
		

		
			
			p.question = "Which one of the following best describes the function of fruits? (<script type=\"text/javascript\">ebook(\'3003\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "protection and dispersal of seeds",
				true,
				"Correct. When seeds develop from ovules, the ovary of a flower develops into a fruit, which protects the enclosed seeds and aids in their dispersal by wind or animals.");
			
				p.addAnswer(2, "reward for pollinators",
				false,
				"No. Nectar, for example, rewards pollinators. Fruit production is a result of successful pollination, but it usually occurs much later.");
			
				p.addAnswer(3, "food storage for the plant to use over the winter",
				false,
				"No. Plants do not use fruit for the storage of food. It takes a lot of energy to maintain fruit; therefore, fruit usually drops from the plant before winter.");
			
				p.addAnswer(4, "to distract herbivores from eating the leaves",
				false,
				"No. The function of fruit is the dispersal and protection of seeds.");
			
				p.addAnswer(5, "Depending on the plant species, any of the above are possible.",
				false,
				"No. When seeds develop from ovules, the ovary of a flower develops into a fruit, which protects the enclosed seeds and aids in their dispersal by wind or animals.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335824;


		
		

		
			
			p.question = "A plant is said to be cross-pollinated if _____. (<script type=\"text/javascript\">ebook(\'3003\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "pollen grains are transferred to a flower on a different plant",
				true,
				"Correct. Cross-pollination occurs when pollen from one plant is transferred to a different plant.");
			
				p.addAnswer(2, "it is pollinated by wind",
				false,
				"No. Cross-pollination could be due to wind, but so could self-pollination.");
			
				p.addAnswer(3, "it is pollinated by insects",
				false,
				"No. Cross-pollination could be due to insects, but so could self-pollination.");
			
				p.addAnswer(4, "its source of pollen is a different species of plant",
				false,
				"No. The pollen source must be a plant of the same species.");
			
				p.addAnswer(5, "pollen grains are transferred from a different flower on the same plant",
				false,
				"No. This is self-pollination.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335825;


		
		

		
			
			p.question = "The pollen tube releases two sperm cells into the embryo sac. The result of this is the _____. (<script type=\"text/javascript\">ebook(\'3003\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "union of the two sperm nuclei, forming a zygote",
				false,
				"No. The sperm nuclei do not unite.");
			
				p.addAnswer(2, "union of one sperm nucleus with the egg nucleus while the other sperm nucleus unites with two nuclei of another megagametophyte cell, forming a triploid nucleus",
				true,
				"Correct. This is referred to as double fertilization.");
			
				p.addAnswer(3, "union of one sperm nucleus with the egg nucleus and the disintegration of the other sperm nucleus",
				false,
				"No. This is what happens in conifers.");
			
				p.addAnswer(4, "fusion of both sperm nuclei with the egg nucleus and the formation of a triploid zygote",
				false,
				"No. The zygote is diploid.");
			
				p.addAnswer(5, "formation of a gametophyte",
				false,
				"No. The embryo sac is the female gametophyte.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335826;


		
		

		
			
			p.question = "Of the following, which is a difference in how reproduction occurs in gymnosperms compared to angiosperms? (<script type=\"text/javascript\">ebook(\'3003\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "Only angiosperm pollen grains form pollen tubes.",
				false,
				"No. Both types of seed plants have pollen grains that form pollen tubes.");
			
				p.addAnswer(2, "Only the sperm of angiosperms combine with megagametophyte nuclei to form triploid endosperm.",
				true,
				"Correct. The endosperm serves as the nutrient source for the developing embryo.");
			
				p.addAnswer(3, "Double fertilization only occurs in gymnosperms.",
				false,
				"No. Double fertilization is more prevalent in angiosperms. In angiosperms, one sperm fertilizes the egg and another fuses with two nuclei, forming endosperm. In some gymnosperms, double fertilization results in two embryos.");
			
				p.addAnswer(4, "Only gymnosperms can contain male and female sporangia on the same plant.",
				false,
				"No. Most angiosperms contain male and female sporangia within the same flower.");
			
				p.addAnswer(5, "Only angiosperms have reduced gametophytes.",
				false,
				"No. This is a trait of all seed plants.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335827;


		
		

		
			
			p.question = "The triploid nucleus of the embryo sac develops into the _____. (<script type=\"text/javascript\">ebook(\'3003\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "embryo",
				false,
				"No. The embryo is diploid.");
			
				p.addAnswer(2, "endosperm",
				true,
				"Correct. The endosperm is a nutrient-rich tissue.");
			
				p.addAnswer(3, "fruit",
				false,
				"No. A fruit is a mature ovary.");
			
				p.addAnswer(4, "carpel",
				false,
				"No. The carpel is the female part of a flower.");
			
				p.addAnswer(5, "seed",
				false,
				"No. The seed is the mature ovule that surrounds the embryo and endosperm.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335828;


		
		

		
			
			p.question = "In gymnosperms, the seed coat develops from the integument. In angiosperms, the seed coat develops from the _____. (<script type=\"text/javascript\">ebook(\'3003\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "ovary wall",
				false,
				"No. The ovary wall gives rise to the pericarp.");
			
				p.addAnswer(2, "receptacle",
				false,
				"No. The receptacle is part of the flower stem.");
			
				p.addAnswer(3, "endosperm",
				false,
				"No. Endosperm is a nutritive tissue for the developing embryo.");
			
				p.addAnswer(4, "female gametophyte",
				false,
				"No. The embryo and its food supply are enclosed by a seed coat formed from the integuments of the ovule.");
			
				p.addAnswer(5, "integuments",
				true,
				"Correct. The embryo and its food supply are enclosed by a seed coat formed from the two integuments of the ovule.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335829;


		
		

		
			
			p.question = "The vast majority of angiosperms with two cotyledons formerly classified as _____ are now classified as _____. (<script type=\"text/javascript\">ebook(\'3003\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "monocots; dicots",
				false,
				"No. Until the late 1990s, these are the two groups that systematists used.");
			
				p.addAnswer(2, "eudicots; dicots",
				false,
				"No. The group formerly called dicots was divided into three new groups. Most of the dicots were placed in a group called eudicots.");
			
				p.addAnswer(3, "dicots; eudicots",
				true,
				"Correct. The vast majority of species traditionally called dicots are now known as eudicots. The others are divided into several small lineages.");
			
				p.addAnswer(4, "monocots; magnoliids",
				false,
				"No. The vast majority of species traditionally called dicots are now known as eudicots. The others are divided into several small lineages.");
			
				p.addAnswer(5, "eudicots; basal angiosperms",
				false,
				"No. The vast majority of species traditionally called dicots are now known as eudicots. The others are divided into several small lineages.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335830;


		
		

		
			
			p.question = "Which of the following characterizes eudicots? (<script type=\"text/javascript\">ebook(\'3003\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "pollen grains with three openings, floral parts in multiples of three, netlike veins",
				false,
				"No. Eudicots have floral parts in multiples of five.");
			
				p.addAnswer(2, "two cotyledons, netlike veins, taproot usually present",
				true,
				"Correct. These are three typical characteristics of eudicots.");
			
				p.addAnswer(3, "one cotyledon, vascular bundles in rings, pollen grains with three openings",
				false,
				"No. Eudicots have two cotyledons.");
			
				p.addAnswer(4, "scattered vascular bundles, netlike veins, floral parts in multiples of five",
				false,
				"No. Eudicots have vascular bundles arranged in rings.");
			
				p.addAnswer(5, "leaves with parallel veins, taproot usually present, vascular bundles arranged in rings",
				false,
				"No. Eudicots have leaves with netlike veins.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335831;


		
		

		
			
			p.question = "A bright pink flower with deep floral tubes will most likely be pollinated by which mechanism? (<script type=\"text/javascript\">ebook(\'3003\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "birds with long beaks",
				true,
				"Correct. Flowers such as the one in this example could have coevolved with nectar-feeding birds. Only birds with long beaks can feed on the plant\'s nectar. Meanwhile, pollen becomes attached to the top of the bird\'s head, from which it is transported to another flower.");
			
				p.addAnswer(2, "bats",
				false,
				"No. Flowers that are pollinated by nocturnal animals are usually light-colored and highly fragrant. The bat may not be able to access the nectar contained in a long floral tube.");
			
				p.addAnswer(3, "honeybees",
				false,
				"No. Insects most likely wouldn\'t have access to the nectar contained in long floral tubes.");
			
				p.addAnswer(4, "wind",
				false,
				"No. Plants that spend that much energy producing flowers would not be wind-pollinated.");
			
				p.addAnswer(5, "self-pollination",
				false,
				"No. Plants that spend that much energy producing flowers would most likely not be self-pollinators.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335832;


		
		

		
			
			p.question = "Six major crops-wheat, rice, maize, potatoes, cassava, and sweet potatoes-constitute what percentage of all the calories consumed by humans? (<script type=\"text/javascript\">ebook(\'3004\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "50%",
				false,
				"No. These six crops account for 80% of the calories consumed by humans.");
			
				p.addAnswer(2, "30%",
				false,
				"No. These six crops account for 80% of the calories consumed by humans.");
			
				p.addAnswer(3, "90%",
				false,
				"No. These six crops account for 80% of the calories consumed by humans.");
			
				p.addAnswer(4, "80%",
				true,
				"Correct. These six crops account for 80% of the calories consumed by humans.");
			
				p.addAnswer(5, "65%",
				false,
				"No. These six crops account for 80% of the calories consumed by humans.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335833;


		
		

		
			
			p.question = "At current rates of deforestation, tropical rain forests will be eliminated in _____ years. (<script type=\"text/javascript\">ebook(\'3004\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "10",
				false,
				"No. Hopefully, they will last longer than this.");
			
				p.addAnswer(2, "100-150",
				true,
				"Correct. At current deforestation rates, it is estimated that tropical rain forests will be eliminated from Earth in 100-150 years.");
			
				p.addAnswer(3, "50",
				false,
				"No. The estimate is a little more optimistic than this.");
			
				p.addAnswer(4, "250",
				false,
				"No. Unless deforestation is controlled, the number of years remaining is far less than 250.");
			
				p.addAnswer(5, "1,000",
				false,
				"No. Unless deforestation is controlled, the number of years is far less than 1,000.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 335834;


		
		

		
			
			p.question = "Besides the plant tissue that humans ingest, which angiosperm tissue is most directly important for human survival? (<script type=\"text/javascript\">ebook(\'3004\',\'quiz\')</script>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "phloem",
				false,
				"No. Not a bad answer, because phloem may be a component of wood, but it\'s not the best answer.");
			
				p.addAnswer(2, "sepals",
				false,
				"No. It would be difficult to argue that sepals in general are important to human survival.");
			
				p.addAnswer(3, "bark",
				false,
				"No. Bark is used for mulch and to make paper, but these are not crucial to human survival.");
			
				p.addAnswer(4, "cones",
				false,
				"No. Cones are not produced in angiosperms.");
			
				p.addAnswer(5, "xylem",
				true,
				"Correct. Xylem is the primary component of wood, which is so important for providing shelter to a large proportion of the human population.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

