

function InitializeAnswerKey(ak) {
	var p = null;
	

	ak.site_title = "BIOLOGY 8e AP* Edition CD-ROM";
	ak.book_title = "BIOLOGY 8e AP* Edition";
	ak.author = "Campbell and Reece";
	ak.quiz_location = "42: Circulation and Gas Exchange > Activities Quiz";
	ak.quiz_loc_with_commas = "42: Circulation and Gas Exchange, Activities Quiz";
	ak.quiz_title = "Activities Quiz";

	
		ak.help_url = "../../placeholders/help_placeholder.html";
	
	ak.essay_total = 0;
	ak.pair_problem_total = 0;
	ak.pair_total = 0;
	ak.problem_total = 15;
	ak.non_essay_total = 15;
	ak.scored_item_total = 15;

	
	
	


	
	ak.copyright_date = "2008";
	ak.brandname = "Pearson Benjamin Cummings";
	ak.legal = "../../placeholders/external_placeholder.html?http%3A%2F%2Fwww.pearsoned.com%2Flegal%2Findex.htm";


	// Loop over all problems
	
	
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336418;


		
		

		
			
			p.question = "The posterior inferior vena cava is indicated by the letter _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?42&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Mammalian Cardiovascular System Structure</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/4201q.jpg\" ALT=\"Question #1\" BORDER=\"1\" >";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A",
				false,
				"This is a pulmonary artery.");
			
				p.addAnswer(2, "B",
				false,
				"This is a pulmonary vein.");
			
				p.addAnswer(3, "C",
				true,
				"This is the posterior vena cava.");
			
				p.addAnswer(4, "D",
				false,
				"This is a portion of the aorta.");
			
				p.addAnswer(5, "E",
				false,
				"This is a portion of the aorta.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336419;


		
		

		
			
			p.question = "Arteries carry blood _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?42&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Mammalian Cardiovascular System Structure</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "away from capillaries",
				false,
				"Veins carry blood away from capillaries.");
			
				p.addAnswer(2, "away from the heart and away from the lungs",
				false,
				"This choice is partially correct.");
			
				p.addAnswer(3, "to the heart and away from the lungs",
				false,
				"Veins carry blood to the heart and away from the lungs.");
			
				p.addAnswer(4, "to the heart only",
				false,
				"All veins carry blood to the heart.");
			
				p.addAnswer(5, "away from the heart only",
				true,
				"All arteries carry blood away from the heart.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336420;


		
		

		
			
			p.question = "Blood returns to the heart via the _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?42&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Mammalian Cardiovascular System Structure</a>, <a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?42&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Path of Blood Flow in Mammals</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "aorta",
				false,
				"The aorta carries blood away from the heart.");
			
				p.addAnswer(2, "pulmonary arteries",
				false,
				"Pulmonary arteries carry deoxygenated blood from the right ventricle to the lungs.");
			
				p.addAnswer(3, "pulmonary veins",
				true,
				"Pulmonary veins carry oxygenated blood from the lungs to the left atrium.");
			
				p.addAnswer(4, "aorta and pulmonary arteries",
				false,
				"Both of these arteries carry blood away from the heart.");
			
				p.addAnswer(5, "aorta and pulmonary veins",
				false,
				"This choice is partially correct.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336421;


		
		

		
			
			p.question = "From the pulmonary veins, blood flows to the _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?42&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Mammalian Cardiovascular System Structure</a>, <a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?42&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Path of Blood Flow in Mammals</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "right atrium",
				false,
				"Blood enters the right atrium from the anterior and posterior venae cavae.");
			
				p.addAnswer(2, "left atrium",
				true,
				"Blood enters the left atrium via the pulmonary veins.");
			
				p.addAnswer(3, "aorta",
				false,
				"Blood enters the aorta from the left ventricle.");
			
				p.addAnswer(4, "capillaries of the lungs",
				false,
				"Blood enters the capillaries of the lungs from the pulmonary arteries.");
			
				p.addAnswer(5, "posterior vena cava",
				false,
				"Blood enters the posterior vena cava from the capillaries of the abdominal organs and hind limbs.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336422;


		
		

		
			
			p.question = "From the anterior vena cava, blood flows to the _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?42&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Mammalian Cardiovascular System Structure</a>, <a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?42&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Path of Blood Flow in Mammals</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "right atrium",
				true,
				"Blood enters the right atrium from the anterior and posterior venae cavae.");
			
				p.addAnswer(2, "left atrium",
				false,
				"Blood enters the left atrium via the pulmonary veins.");
			
				p.addAnswer(3, "aorta",
				false,
				"Blood enters the aorta from the left ventricle.");
			
				p.addAnswer(4, "capillaries of the lungs",
				false,
				"Blood enters the capillaries of the lungs from the pulmonary arteries.");
			
				p.addAnswer(5, "posterior vena cava",
				false,
				"Blood enters the posterior vena cava from the capillaries of the abdominal organs and hind limbs.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336423;


		
		

		
			
			p.question = "From the capillaries of the abdominal organs and hind limbs, blood flows to the _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?42&A','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Mammalian Cardiovascular System Structure</a>, <a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?42&B','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Path of Blood Flow in Mammals</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "right atrium",
				false,
				"Blood enters the right atrium from the anterior and posterior venae cavae.");
			
				p.addAnswer(2, "left atrium",
				false,
				"Blood enters the left atrium via the pulmonary veins.");
			
				p.addAnswer(3, "aorta",
				false,
				"Blood enters the aorta from the left ventricle.");
			
				p.addAnswer(4, "capillaries of the lungs",
				false,
				"Blood enters the capillaries of the lungs from the pulmonary arteries.");
			
				p.addAnswer(5, "posterior vena cava",
				true,
				"Blood enters the posterior vena cava from the capillaries of the abdominal organs and hind limbs.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336424;


		
		

		
			
			p.question = "Carbon dioxide enters the blood at the _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?42&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Mammalian Cardiovascular System Function</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "capillaries of the lungs",
				false,
				"Oxygen diffuses into, and carbon dioxide diffuses out of, these capillaries.");
			
				p.addAnswer(2, "capillaries of the abdominal organs",
				false,
				"In these capillaries oxygen diffuses into, and carbon dioxide diffuses out of, body tissues. However, is this the only correct answer?");
			
				p.addAnswer(3, "capillaries of the hind limbs",
				false,
				"In these capillaries oxygen diffuses into, and carbon dioxide diffuses out of, body tissues. However, is this the only correct answer?");
			
				p.addAnswer(4, "capillaries of the head and forelimbs",
				false,
				"In these capillaries oxygen diffuses into, and carbon dioxide diffuses out of, body tissues. However, is this the only correct answer?");
			
				p.addAnswer(5, "capillaries of the head, forelimbs, abdominal organs, and hind limbs",
				true,
				"In these capillaries oxygen diffuses into, and carbon dioxide diffuses out of, body tissues.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336425;


		
		

		
			
			p.question = "The _____ has(have) the thinnest walls. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?42&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Mammalian Cardiovascular System Function</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "aorta",
				false,
				"Of the blood vessels, the aorta has the thickest walls.");
			
				p.addAnswer(2, "capillaries",
				true,
				"The thin walls of the capillaries facilitate gas exchange.");
			
				p.addAnswer(3, "posterior vena cava",
				false,
				"While veins have thinner walls than arteries, they do not have the thinnest walls.");
			
				p.addAnswer(4, "pulmonary artery",
				false,
				"The muscular walls of arteries increase their thickness.");
			
				p.addAnswer(5, "right ventricle",
				false,
				"The right ventricle has a thick muscular wall.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336426;


		
		

		
			
			p.question = "Blood pressure is highest in the _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?42&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Mammalian Cardiovascular System Function</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "aorta",
				true,
				"The aorta, which carries blood that has just left the left ventricle, has the highest blood pressure.");
			
				p.addAnswer(2, "posterior vena cava",
				false,
				"The blood pressure in veins is relatively low.");
			
				p.addAnswer(3, "anterior vena cava",
				false,
				"The blood pressure in veins is relatively low.");
			
				p.addAnswer(4, "pulmonary artery",
				false,
				"Blood pressure is higher in another of the blood vessels listed here.");
			
				p.addAnswer(5, "capillaries",
				false,
				"The blood pressure in capillaries is relatively low.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336427;


		
		

		
			
			p.question = "Most gas exchange with blood vessels occurs across the walls of the structure indicated by the letter _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?42&C','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Mammalian Cardiovascular System Function</a>)<br><br><img SRC=\""+qzmediapath+"bc_campbell_biology_8/img/activities_quizzes/4210q.jpg\" ALT=\"Question #10\" BORDER=\"1\">";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "A",
				false,
				"Little, if any, gas exchange with blood vessels occurs across the walls of the nasal cavity.");
			
				p.addAnswer(2, "B",
				false,
				"Little, if any, gas exchange with blood vessels occurs across the walls of the larynx.");
			
				p.addAnswer(3, "C",
				false,
				"Little, if any, gas exchange with blood vessels occurs across the walls of bronchi.");
			
				p.addAnswer(4, "D",
				false,
				"Little, if any, gas exchange with blood vessels occurs across the walls of bronchioles.");
			
				p.addAnswer(5, "E",
				true,
				"Gas exchange occurs across the walls of the alveoli.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336428;


		
		

		
			
			p.question = "Voice sounds are produced by the _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?42&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Human Respiratory System</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "trachea",
				false,
				"The trachea carries gases to and from the lungs.");
			
				p.addAnswer(2, "diaphragm",
				false,
				"The diaphragm is a muscle that plays a role in helping move air into and out of the lungs.");
			
				p.addAnswer(3, "bronchioles",
				false,
				"Bronchioles carry gases to and from the lungs.");
			
				p.addAnswer(4, "larynx",
				true,
				"The larynx houses the vocal cords.");
			
				p.addAnswer(5, "lungs",
				false,
				"Gas exchange occurs within the lungs.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336429;


		
		

		
			
			p.question = "The primary functions of the _____ are to warm, filter, and humidify air. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?42&D','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: The Human Respiratory System</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "lungs",
				false,
				"Gas exchange is the primary function of the lungs.");
			
				p.addAnswer(2, "trachea",
				false,
				"The primary function of the trachea is to carry gases to and from the lungs.");
			
				p.addAnswer(3, "bronchus",
				false,
				"The primary function of bronchi is to carry gases to and from the lungs.");
			
				p.addAnswer(4, "nasal cavity",
				true,
				"The functions of the nasal cavity are to warm, filter, and humidify air.");
			
				p.addAnswer(5, "alveoli",
				false,
				"Alveoli are the specific location in the lungs across which most gas exchange occurs.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336430;


		
		

		
			
			p.question = "Most carbon dioxide is carried from the body tissues to the lungs _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?42&E','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Transport of Respiratory Gases</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "as bicarbonate ions (HCO<sub>3</sub><sup>-</sup>)",
				true,
				"Most carbon dioxide released from body tissues combines with water to form carbonic acid, which then breaks up into hydrogen and bicarbonate ions.");
			
				p.addAnswer(2, "combined with hemoglobin",
				false,
				"Some, but not most, carbon dioxide is carried to the lungs attached to hemoglobin.");
			
				p.addAnswer(3, "by the trachea",
				false,
				"The trachea carries carbon dioxide from the lungs to the exterior of the body.");
			
				p.addAnswer(4, "as hydrogen ions (H<sup>+</sup>)",
				false,
				"There is no carbon dioxide in hydrogen ions.");
			
				p.addAnswer(5, "dissolved in blood plasma",
				false,
				"Some, but not most, carbon dioxide is carried to the lungs dissolved in blood plasma.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336431;


		
		

		
			
			p.question = "By picking up hydrogen ions, hemoglobin prevents the blood from becoming too _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?42&E','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Transport of Respiratory Gases</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "acidic",
				true,
				"If not carried by hemoglobin, hydrogen ions would reduce the pH, or increase the acidity, of the blood.");
			
				p.addAnswer(2, "basic",
				false,
				"You might want to review some basic chemistry.");
			
				p.addAnswer(3, "thick",
				false,
				"Hydrogen ion concentration will not affect the thickness of the blood.");
			
				p.addAnswer(4, "low in oxygen concentration",
				false,
				"As acidity increases (as pH decreases), the affinity of hemoglobin for oxygen decreases.");
			
				p.addAnswer(5, "red",
				false,
				"No, that is incorrect.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

		// ----- multiplechoice ------------
		//
		
			p = new Problem("multiplechoice");
		
		p.id = 336432;


		
		

		
			
			p.question = "In the blood most of the oxygen that will be used in cellular respiration is carried from the lungs to the body tissues _____. (<a href=\"javascript:void(0)\" onclick=\"window.open('"+qzmediapath+"bc_campbell_biology_7/activities/load.html?42&E','rrpop','menubar=0,toolbar=0,location=0,status=0,scrollbars=1,resizable=1,width=740,height=600,screenX=10,screenY=10,left=10,top=10')\" class=\"quizList\">Activity: Transport of Respiratory Gases</a>)";
			p.incorrect_any_expl = "";
			p.incorrect_any_expl_flag = 0;
			p.incorrect_expls_flag = 1;
			p.correct_expls_flag = 1;
			
			
			// num_correct: 1

			
			
				p.addAnswer(1, "as bicarbonate ions (HCO<sub>3</sub><sup>-</sup>)",
				false,
				"This is the form in which most carbon dioxide is carried from the body tissues to the lungs.");
			
				p.addAnswer(2, "combined with hemoglobin",
				true,
				"In the blood most oxygen is transported attached to hemoglobin.");
			
				p.addAnswer(3, "by the trachea",
				false,
				"The trachea carries oxygen from the exterior of the body to the lungs.");
			
				p.addAnswer(4, "water (H<sub>2</sub>O)",
				false,
				"The oxygen in water is not the oxygen used in cellular respiration.");
			
				p.addAnswer(5, "dissolved in blood plasma",
				false,
				"Some, but not most, oxygen is carried to the lungs dissolved in blood plasma.");
			
			
		

		

		
			ak.addProblem(p);
		

		
	

} // end function InitializeAnswerKey

